module.exports = {
  slug: 'ch10-practice-ncert-exercises',
  title: 'Practice — NCERT Exercises',
  subtitle: 'All 13 NCERT textbook exercises for the chapter, grouped into 4 revision themes with full worked solutions.',
  page_type: 'lesson',
  tags: ['ncert-exercises', 'practice'],
  blocks: [
    {
      id: '83b3dfec-4c7e-4e72-b183-f19b086da168',
      type: 'image',
      order: 0,
      src: '',
      alt: 'Applications of biotechnology: a tissue-culture flask growing tiny plantlets, a Bt-cotton leaf with protected bolls, an E. coli cell making human insulin, and a golden rice grain.',
      caption: '',
      width: 'full',
      aspect_ratio: '16:5',
      generation_prompt: 'A hand-drawn coloured illustration on a deep-charcoal dark background, muted earthy palette (soft greens, ochre, warm amber, dull teal), no glow, no neon, no 3D. A single horizontal panel showing the applications of biotechnology, left to right: (1) a glass tissue-culture flask on a lab bench with a cluster of identical tiny green plantlets growing from a small explant; (2) a healthy cotton plant leaf with intact white bolls and a small caterpillar turning away, labelled "Bt"; (3) a rod-shaped E. coli bacterium with a small circular plasmid inside and a tiny insulin-protein icon budding out; (4) a golden-yellow rice grain glowing warmly beside pale ordinary grains. Hand-inked outlines, textured shading like a naturalist field notebook, calm and academic. No text labels except the small "Bt". 16:5 landscape.',
    },
    {
      id: '910de752-b82a-48fd-9d6c-a0c066ddf9da',
      type: 'text',
      order: 1,
      markdown: "You've read the chapter — now drill it. Below are **all 13 NCERT exercises** for *Biotechnology and Its Applications*, pulled out of the textbook's running order and regrouped into **4 revision themes**: plant tissue culture, Bt crops and Cry proteins, transgenic organisms and rDNA applications, and molecular medicine. Each question is the exact NCERT wording, and each comes with a full worked solution — read the solution even when you got the answer right, because the whole idea lives there.",
    },
    {
      id: 'c9762f6b-2a8c-421c-923e-e307fc043385',
      type: 'practice_bank',
      order: 2,
      title: 'NCERT Exercises 10.1–10.13',
      intro: 'Thirteen exercises, four themes. Try each on your own first, then open the solution.',
      sections: [
        {
          id: '5d0b8b40-3594-49ff-86c5-40b8346ebde7',
          title: 'Plant tissue culture & micropropagation',
          blurb: 'Growing whole plants from a scrap of tissue — virus-free stock, somaclones, and what goes in the medium.',
          items: [
            {
              kind: 'numerical',
              id: '346cdfc7-6f55-4b77-870b-e1d953f32b50',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.1',
              prompt: 'Which part of the plant is best suited for making virus-free plants and why?',
              answer: 'The meristem (apical and axillary) — it stays virus-free even in an infected plant.',
              solution: "The **meristem** — the apical and axillary meristem — is the best part to use.\n\nHere's why. Even when a plant is infected by a virus, the virus does not manage to reach the meristem. The cells there are dividing so fast that the virus lags behind and never catches up, so the meristematic tip stays **free of the virus**.\n\nSo a scientist removes this virus-free meristem and grows it in vitro by tissue culture. The plantlet that grows from it is healthy and virus-free. This method has been used successfully to recover virus-free banana, sugarcane, potato and many other crops.",
            },
            {
              kind: 'numerical',
              id: '60ccd662-d4d2-49aa-8a80-f7d058001ced',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.2',
              prompt: 'What is the major advantage of producing plants by micropropagation?',
              answer: 'Thousands of genetically identical (somaclone), healthy plants in a very short time.',
              solution: "Micropropagation is the method of producing thousands of plants through tissue culture, starting from a small piece of tissue (an explant).\n\nThe **major advantage** is that every one of these plants is **genetically identical** to the original plant it was grown from — such a plant is called a **somaclone**. On top of that, you can raise a very large number of plants in a very short time, and they are healthy (often virus-free) stock.\n\nMany important food plants — tomato, banana, apple — are now produced on a commercial scale this way.",
            },
            {
              kind: 'numerical',
              id: 'cb6101c7-00b4-4dfd-a4b6-6b13a695fef8',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.3',
              prompt: 'Find out what the various components of the medium used for propagation of an explant in vitro are?',
              answer: 'A carbon source (sucrose), inorganic salts, vitamins, amino acids and growth regulators (auxins, cytokinins).',
              solution: "To grow an explant in vitro, the nutrient medium has to supply everything the tissue needs to divide and grow. A standard medium (like the Murashige and Skoog / MS medium) contains:\n\n- a **carbon source** — usually **sucrose** — to provide energy,\n- **inorganic salts** — the macro- and micro-nutrients (nitrogen, phosphorus, potassium, calcium, iron, etc.),\n- **vitamins**,\n- **amino acids**, and\n- **plant growth regulators** — mainly **auxins and cytokinins** — which drive the cells to divide and then differentiate into roots and shoots.\n\nThe whole set-up has to be maintained under strict **sterile (aseptic)** conditions, or contaminating microbes will overrun the culture.",
            },
          ],
        },
        {
          id: 'fdbb6a73-5efc-4c8b-8b7c-8b7160121591',
          title: 'Bt crops, Cry proteins & GM crops',
          blurb: 'How Bacillus thuringiensis makes an insecticidal protein, why it does not kill the bacterium, and the two-sided ledger of GM crops.',
          items: [
            {
              kind: 'mcq',
              id: '8bbe4fd5-84bc-40ee-9892-41dd433ef34f',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.4',
              prompt: 'Crystals of Bt toxin produced by some bacteria do not kill the bacteria themselves because –',
              options: [
                '(a) bacteria are resistant to the toxin',
                '(b) toxin is immature',
                '(c) toxin is inactive',
                '(d) bacteria encloses toxin in a special sac',
              ],
              correct_index: 2,
              explanation: "The correct answer is **(c) toxin is inactive**.\n\nInside *Bacillus thuringiensis* the Bt toxin is stored in the crystal as an **inactive protoxin** — it has no toxic effect in that form, so it does no harm to the bacterium that made it.\n\nThe protoxin only becomes dangerous once an insect eats it. In the insect's gut the **alkaline pH** dissolves the crystals and converts the inactive protoxin into the **active toxin**. The active toxin then binds to the surface of the midgut epithelial cells, punches pores in them, and the cells swell and burst — killing the insect. Because the bacterium's own environment never activates the protoxin, it survives unharmed.",
            },
            {
              kind: 'numerical',
              id: '00bf820a-97b0-437e-94cc-0f8697c8e3a8',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.6',
              prompt: 'Compare and contrast the advantages and disadvantages of production of genetically modified crops.',
              answer: 'Advantages: stress tolerance, less pesticide, less spoilage, better nutrition. Disadvantages: harm to non-target species, gene flow, biodiversity and safety concerns.',
              solution: "Genetically modified (GM) crops are plants whose genes have been altered by rDNA technology. The ledger has two sides.\n\n| Advantages | Disadvantages |\n|---|---|\n| More tolerant of abiotic stresses — cold, drought, salt, heat | May harm **non-target organisms** (useful insects, soil life) |\n| Reduced use of chemical pesticides (pest-resistant crops like Bt cotton) | Foreign gene may **flow** into wild relatives or weeds |\n| Reduced post-harvest losses | Threat to **biodiversity** |\n| Plants use minerals more efficiently, preventing early soil exhaustion | Possible **allergenicity** and other unknown effects on human health |\n| Enhanced nutritional value (e.g. golden rice — vitamin A) | Ethical and biosafety concerns |\n\nSo GM crops raise yield and quality and cut chemical use, but they carry ecological and safety risks that must be tested and regulated (in India, by the **GEAC — Genetic Engineering Approval Committee**) before release.",
            },
            {
              kind: 'numerical',
              id: '763e2355-4098-4e90-9082-fe4ffa8f342c',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.7',
              prompt: 'What are Cry proteins? Name an organism that produce it. How has man exploited this protein to his benefit?',
              answer: 'Insecticidal proteins made by Bacillus thuringiensis; man put their cry genes into crops (Bt cotton) for built-in pest resistance.',
              solution: "**Cry proteins** are insect-killing (toxin) proteins. They are coded by genes called **cry genes**.\n\n**The organism** that produces them is the bacterium **_Bacillus thuringiensis_** (Bt). During a certain phase of its growth it forms protein crystals containing this toxic insecticidal protein.\n\n**How man has exploited it:** different cry proteins kill different insects — for example *cryIAc* and *cryIIAb* control the **cotton bollworms**, and *cryIAb* controls the **corn borer**. Scientists isolated these *cry* genes and inserted them into crop plants (most famously **Bt cotton**, also Bt corn). The plant now makes its own Bt toxin, so the specific pest that eats it is killed — giving the crop built-in protection and greatly cutting the need for chemical insecticides.",
            },
          ],
        },
        {
          id: '0e648fb1-48d6-40c2-8a09-d4d042d8e98d',
          title: 'Transgenic organisms & rDNA applications',
          blurb: 'Bacteria carrying human genes, cloning a growth-hormone gene into E. coli, an rDNA puzzle, and golden rice.',
          items: [
            {
              kind: 'numerical',
              id: '30743d5c-b17c-4168-9923-a84b08380550',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.5',
              prompt: 'What are transgenic bacteria? Illustrate using any one example.',
              answer: 'Bacteria carrying and expressing a foreign gene — e.g. E. coli engineered to make human insulin (Humulin).',
              solution: "**Transgenic bacteria** are bacteria that have been given a **foreign gene** (usually a human gene) by rDNA technology, and that then **express** it — that is, make the human protein.\n\n**Example — engineered insulin (Humulin).** Human insulin is made of two short chains: **chain A (21 amino acids)** and **chain B (30 amino acids)**, held together by disulphide bonds. In the body, insulin is first made as a bigger molecule called **pro-insulin**, which has an extra stretch called the **C-peptide** in the middle; this C-peptide is removed as the insulin matures.\n\nIn 1983 the company **Eli Lilly** prepared the two DNA sequences that code for the **A and B chains** and introduced them into **_E. coli_** to produce the two chains separately. The chains were then extracted and joined by disulphide bonds to give mature human insulin. Because a bacterium was carrying and expressing human genes, it is a transgenic bacterium.",
            },
            {
              kind: 'numerical',
              id: '21aab19a-b1f3-497d-b517-f3d7877b36cb',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.9',
              prompt: 'Digrammatically represent the experimental steps in cloning and expressing an human gene (say the gene for growth hormone) into a bacterium like E. coli?',
              answer: 'Isolate the gene → cut a plasmid with the same enzyme → ligate into recombinant DNA → transform E. coli → multiply (clone) → express and harvest growth hormone.',
              solution: "We can't draw here, so picture the flow chart as a chain of six labelled boxes:\n\n1. **Isolate the gene of interest** — cut out the human **growth-hormone gene** from human DNA using a **restriction enzyme**, which leaves 'sticky ends'.\n2. **Cut the vector** — take a **plasmid** from *E. coli* and cut it open with the **same restriction enzyme**, so its ends are complementary (sticky) to the gene's ends.\n3. **Join them** — mix the gene and the cut plasmid; **DNA ligase** seals the growth-hormone gene into the plasmid, forming a **recombinant DNA (rDNA)** molecule.\n4. **Transform the host** — introduce this recombinant plasmid into a competent **_E. coli_** cell.\n5. **Cloning (multiplication)** — the bacterium divides again and again; every daughter cell carries a copy of the recombinant plasmid, so we get millions of identical copies (clones) of the gene.\n6. **Expression and harvest** — grown in a **bioreactor**, the bacteria read the gene and make **human growth hormone**, which is then extracted and purified for use.\n\nSo the diagram is: *human cell → growth-hormone gene* and *E. coli → plasmid* feeding into *rDNA → E. coli → multiplication → product (growth hormone)*.",
            },
            {
              kind: 'numerical',
              id: '2744a5d6-ff8d-4dc2-b9fb-d6686d37d969',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.10',
              prompt: 'Can you suggest a method to remove oil (hydrocarbon) from seeds based on your understanding of rDNA technology and chemistry of oil?',
              answer: 'Silence the gene for the oil-synthesis enzyme using RNAi/antisense so the seed makes no oil; already-formed oil can be removed by solvent extraction or hydrolysis.',
              solution: "This is a 'think it through' question. Two lines of attack — one genetic, one chemical.\n\n**Using rDNA technology (stop the oil being made):** seed oils are **triglycerides** — esters of glycerol and fatty acids — built by specific enzymes in the seed. If we identify the gene that codes for a key enzyme of this fatty-acid/oil pathway, we can **silence it** — for example by **RNA interference (RNAi)** or an **antisense gene** that blocks that mRNA. With the enzyme gone, the seed cannot make the oil, giving low-oil or oil-free seeds.\n\n**Using the chemistry of oil (remove oil already present):** because oil is an **ester**, the oil already in the seed can be taken out by **solvent extraction** (a non-polar solvent such as hexane dissolves the oil) or broken down by **hydrolysis / saponification** of the ester bonds.\n\nSo the best answer combines both: block oil synthesis at the gene level with rDNA technology, and/or extract the residual oil chemically knowing it is an ester.",
            },
            {
              kind: 'numerical',
              id: '0ee39a54-d991-4aac-9139-ba08a623ee50',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.11',
              prompt: 'Find out from internet what is golden rice.',
              answer: 'A transgenic rice rich in provitamin A (beta-carotene), giving the grain a golden colour, made to fight vitamin-A deficiency.',
              solution: "**Golden rice** is a genetically engineered variety of rice (*Oryza sativa*) into which the genes for making **beta-carotene (provitamin A)** have been introduced.\n\nThe grain accumulates beta-carotene, which is a yellow-orange pigment — this gives the rice its **golden-yellow colour**, and hence the name.\n\nIt was developed to fight **vitamin-A deficiency**, a serious problem in poor communities whose staple food is ordinary rice (which contains almost no vitamin A). Because the body converts beta-carotene into vitamin A, eating golden rice can supply the vitamin A these people lack, helping to prevent blindness and other deficiency diseases.",
            },
          ],
        },
        {
          id: '442d76f3-28d1-4dda-92d8-fbce186674a6',
          title: 'Gene therapy & molecular medicine',
          blurb: 'Correcting a faulty gene (ADA-SCID), why blood does not digest its own proteins, and the problem with oral protein drugs.',
          items: [
            {
              kind: 'numerical',
              id: '2059a862-e2c8-4631-a247-7bf9ca37fecf',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.8',
              prompt: 'What is gene therapy? Illustrate using the example of adenosine deaminase (ADA) deficiency.',
              answer: 'Correcting a disease by inserting a normal gene; in ADA-SCID a normal ADA gene is put into the patient\'s lymphocytes (a permanent cure needs it in bone-marrow cells).',
              solution: "**Gene therapy** is a set of methods that lets us **correct a gene defect** in a person born with it. Instead of treating symptoms with drugs, a **normal (functional) gene** is introduced into the patient's cells and tissues to do the job the faulty gene cannot.\n\n**Example — ADA deficiency (ADA-SCID).** Some children are born unable to make the enzyme **adenosine deaminase (ADA)** because the gene for it is missing or defective. Without ADA the immune system fails — this is a form of **severe combined immunodeficiency (SCID)**.\n\nThe first gene therapy (1990) treated such a child like this:\n1. **Lymphocytes** were taken from the patient's blood and grown in culture.\n2. A **functional ADA gene** was introduced into these lymphocytes using a **retroviral vector**.\n3. The engineered lymphocytes were **returned to the patient's body**, where they made ADA and restored immune function.\n\nBut because these lymphocytes are not long-lived, the treatment must be **repeated periodically**. A **permanent cure** would need the normal ADA gene to be introduced into **bone-marrow cells** (the cells that produce lymphocytes) at an early embryonic stage.",
            },
            {
              kind: 'numerical',
              id: 'bfabcfe3-7894-424b-811d-7c2cf6e1b43d',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.12',
              prompt: 'Does our blood have proteases and nucleases?',
              answer: 'No — normal blood does not contain free proteases and nucleases.',
              solution: "**No.** Normal human blood (plasma/serum) does **not** contain free **proteases** (protein-digesting enzymes) or **nucleases** (DNA/RNA-digesting enzymes).\n\nAnd that is a good thing. Blood carries around many valuable proteins and nucleic acids — antibodies, hormones like insulin, clotting factors. If proteases and nucleases were floating free in the blood, they would digest these molecules and destroy them.\n\nDigestive proteases and nucleases are instead made and released into the **alimentary canal** (stomach, pancreas, intestine), where their job is to break down food — not into the bloodstream.",
            },
            {
              kind: 'numerical',
              id: '1e7bf827-d1f3-42a9-a234-15993f67fb42',
              source: 'ncert_exercise',
              source_label: 'NCERT 10.13',
              prompt: 'Consult internet and find out how to make orally active protein pharmaceutical. What is the major problem to be encountered?',
              answer: 'The drug must survive digestion; the major problem is that proteases and stomach acid digest the protein before it can be absorbed.',
              solution: "A protein pharmaceutical (like insulin) is normally given by **injection**. To make it **orally active**, the protein taken by mouth has to travel through the digestive tract and reach the blood **still intact and still working**.\n\n**The major problem:** the digestive system is designed to break proteins down. The **proteases** (protein-digesting enzymes in the stomach and intestine) and the strong **stomach acid** would **digest the protein drug** into amino acids before it could ever be absorbed — so it loses all its activity. That is exactly why insulin is injected, not swallowed.\n\nTo get around this, an oral protein drug would need to be **protected from digestion** — for example by giving it a special acid-resistant coating (encapsulation), adding **protease inhibitors**, or chemically modifying the protein so the enzymes cannot break it — while still letting it be absorbed across the gut wall.",
            },
          ],
        },
      ],
    },
  ],
};
