// Handwritten chemistry notes — static catalog.
//
// The full list lives in handwrittenNotes.data.ts, regenerated by
// scripts/migrate_handwritten_notes_to_r2.js when new PDFs are uploaded to R2.
// To add a new note manually: upload the PDF to R2 under
// handwritten-notes/{chapter-slug}/, then add an entry to NOTES with the
// resulting public URL.

import { NOTES } from './handwrittenNotes.data';

export interface HandwrittenNote {
    id: string;
    title: string;
    notesUrl: string;
    category: string;
    chapter: string;
    thumbnailUrl: string | null;
    addedOrder: number;
}

// Async signature kept for compatibility with existing call sites
// (app/handwritten-notes/page.tsx and app/handwritten-notes/[chapter]/page.tsx
// both `await` this). Returns instantly — no network, no DB.
export async function fetchHandwrittenNotes(): Promise<HandwrittenNote[]> {
    return NOTES;
}

// Convert a stored R2 public URL into the same-origin proxy path that the
// inline PDF viewer should embed. Cross-origin PDFs in <iframe> are blocked
// by Chrome's PDF viewer + privacy-strict browsers (Brave, Safari ITP);
// proxying through /api/handwritten-notes/* makes the request same-origin
// and bypasses every variant of that block.
//
// When a custom R2 domain (e.g. cdn.canvasclasses.in) is wired up later,
// this helper becomes a no-op — change the if-branch to return notesUrl.
export function toInlineViewerUrl(notesUrl: string): string {
    const idx = notesUrl.indexOf('/handwritten-notes/');
    if (idx >= 0) return '/api' + notesUrl.slice(idx);
    return notesUrl;
}

// Get unique categories for filtering.
export function getUniqueCategories(notes: HandwrittenNote[]): string[] {
    return Array.from(new Set(notes.map((n) => n.category).filter(Boolean))).sort();
}

// Exact-match counts (matches the four UI buckets).
export function getNotesStats(notes: HandwrittenNote[]) {
    const total = notes.length;
    const organic = notes.filter((n) => n.category === 'Organic Chemistry').length;
    const inorganic = notes.filter((n) => n.category === 'Inorganic Chemistry').length;
    const physical = notes.filter((n) => n.category === 'Physical Chemistry').length;
    const general = notes.filter((n) => n.category === 'General chemistry').length;
    return { total, organic, inorganic, physical, general };
}
