'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

// Modal wizard that turns predictor inputs + a small set of preferences into
// an ordered, annotated JoSAA choice list. Designed to be the single replacement
// for the older flat "Export choice list" modal.

type BranchFlex = 'cse-only' | 'tech-adjacent' | 'flexible';
type RiskProfile = 'conservative' | 'balanced' | 'aggressive';
type Tranche = 'moonshot' | 'target' | 'safety';
type Region = 'North' | 'South' | 'East' | 'West' | 'Central' | 'Northeast';

interface ChoiceEntry {
  position: number;
  college_id: string;
  college_short_name: string;
  college_type: 'NIT' | 'IIIT' | 'GFTI' | 'IIT';
  college_state: string;
  college_region: string;
  branch_short_name: string;
  branch_name: string;
  quota_matched: string;
  probability_pct: number;
  bucket: 'safe' | 'target' | 'reach' | 'unlikely';
  tranche: Tranche;
  reason: string;
  desirability: number;
}

interface BuildResponse {
  success: boolean;
  error?: string;
  entries?: ChoiceEntry[];
  summary?: {
    total: number;
    by_tranche: Record<Tranche, number>;
    best_case: string;
    worst_case: string;
  };
}

interface Props {
  open: boolean;
  onClose: () => void;
  /** Base predictor inputs already collected from the predictor form. */
  baseInputs: {
    rank?: number;
    percentile?: number;
    rank_type?: 'CRL' | 'CAT';
    category: string;
    gender: string;
    home_state: string;
    year?: number;
    college_types?: string[];
    dream_branch?: string;
  };
}

const TRANCHE_META: Record<Tranche, { label: string; color: string; ring: string }> = {
  moonshot: { label: 'Moonshot', color: 'text-sky-300',    ring: 'ring-sky-500/40' },
  target:   { label: 'Target',   color: 'text-orange-300', ring: 'ring-orange-500/40' },
  safety:   { label: 'Safety',   color: 'text-emerald-300', ring: 'ring-emerald-500/40' },
};

export default function ChoiceListBuilder({ open, onClose, baseInputs }: Props) {
  const [branchFlex, setBranchFlex] = useState<BranchFlex>('flexible');
  const [risk, setRisk] = useState<RiskProfile>('balanced');
  const [listSize, setListSize] = useState<number>(60);
  const [regions, setRegions] = useState<Set<Region>>(new Set());
  const [dreamColleges, setDreamColleges] = useState<string>('');

  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState<BuildResponse | null>(null);
  const [copied, setCopied] = useState(false);

  function toggleRegion(r: Region) {
    setRegions((prev) => {
      const next = new Set(prev);
      if (next.has(r)) next.delete(r); else next.add(r);
      return next;
    });
  }

  async function build() {
    setLoading(true);
    setResponse(null);
    try {
      const body = {
        ...baseInputs,
        branch_flexibility: branchFlex,
        risk_profile: risk,
        list_size: listSize,
        preferred_regions: regions.size > 0 ? [...regions] : undefined,
        dream_branch: baseInputs.dream_branch,
        dream_colleges: dreamColleges.trim()
          ? dreamColleges.split(',').map((s) => s.trim()).filter(Boolean)
          : undefined,
      };
      const res = await fetch('/api/v2/college-predictor/choice-list', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const j = (await res.json()) as BuildResponse;
      setResponse(j);
    } catch (err) {
      console.error(err);
      setResponse({ success: false, error: 'Request failed' });
    } finally {
      setLoading(false);
    }
  }

  function asPlainText(): string {
    if (!response?.entries) return '';
    const lines: string[] = [];
    lines.push('# JoSAA choice list — generated by Canvas Predictor');
    lines.push('# JoSAA fills top-down. Keep this order when entering choices on the portal.');
    lines.push('');
    if (response.summary) {
      lines.push(`# ${response.summary.total} choices · ${response.summary.by_tranche.moonshot} moonshot · ${response.summary.by_tranche.target} target · ${response.summary.by_tranche.safety} safety`);
      lines.push(`# ${response.summary.worst_case}`);
      lines.push('');
    }
    let lastTranche: Tranche | null = null;
    for (const e of response.entries) {
      if (e.tranche !== lastTranche) {
        lines.push('');
        lines.push(`## ${TRANCHE_META[e.tranche].label} tier`);
        lastTranche = e.tranche;
      }
      lines.push(
        `${e.position}. ${e.college_short_name} — ${e.branch_name} · Quota ${e.quota_matched} · ${e.probability_pct}% chance`,
      );
    }
    return lines.join('\n');
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(asPlainText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  }

  function downloadText() {
    const blob = new Blob([asPlainText()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'josaa-choice-list.txt';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center p-4 bg-black/70 backdrop-blur-sm overflow-y-auto"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.97, y: 16 }}
        animate={{ scale: 1, y: 0 }}
        transition={{ duration: 0.15 }}
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-4xl rounded-2xl bg-[#0B0F15] border border-white/10 overflow-hidden my-8"
      >
        <div className="flex items-start justify-between p-5 border-b border-white/5">
          <div>
            <div className="text-base font-semibold text-white">Build a smart JoSAA choice list</div>
            <div className="text-[11px] text-zinc-500 mt-1">
              We'll generate an ordered list with moonshots at top, targets in the middle, and safety nets at the bottom — the shape JoSAA's top-down fill mechanism rewards.
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-zinc-500 hover:text-white text-xl leading-none px-2"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="p-5 space-y-5">
          {/* Preferences */}
          <div className="grid md:grid-cols-2 gap-4">
            <Field label="Branch flexibility">
              <div className="grid grid-cols-3 gap-1.5">
                {[
                  { id: 'cse-only',      label: 'CSE only',    hint: 'CSE / IT / AI / M&C' },
                  { id: 'tech-adjacent', label: 'Tech-adjacent', hint: '+ ECE / EE / VLSI' },
                  { id: 'flexible',      label: 'Any branch',  hint: 'All engineering' },
                ].map((o) => (
                  <button
                    key={o.id}
                    type="button"
                    onClick={() => setBranchFlex(o.id as BranchFlex)}
                    className={`text-left p-2.5 rounded-lg border transition-colors ${
                      branchFlex === o.id
                        ? 'bg-orange-500/10 border-orange-500/40'
                        : 'bg-white/5 border-white/10 hover:bg-white/10'
                    }`}
                  >
                    <div className="text-xs font-medium text-white">{o.label}</div>
                    <div className="text-[10px] text-zinc-500 mt-0.5">{o.hint}</div>
                  </button>
                ))}
              </div>
            </Field>

            <Field label="Risk profile">
              <div className="grid grid-cols-3 gap-1.5">
                {[
                  { id: 'conservative', label: 'Safe-first',    hint: '50% safety nets' },
                  { id: 'balanced',     label: 'Balanced',      hint: '30/40/30 split' },
                  { id: 'aggressive',   label: 'Chase reach',   hint: '50% moonshots' },
                ].map((o) => (
                  <button
                    key={o.id}
                    type="button"
                    onClick={() => setRisk(o.id as RiskProfile)}
                    className={`text-left p-2.5 rounded-lg border transition-colors ${
                      risk === o.id
                        ? 'bg-orange-500/10 border-orange-500/40'
                        : 'bg-white/5 border-white/10 hover:bg-white/10'
                    }`}
                  >
                    <div className="text-xs font-medium text-white">{o.label}</div>
                    <div className="text-[10px] text-zinc-500 mt-0.5">{o.hint}</div>
                  </button>
                ))}
              </div>
            </Field>

            <Field label={`List size — ${listSize} choices`}>
              <input
                type="range"
                min={20}
                max={150}
                step={10}
                value={listSize}
                onChange={(e) => setListSize(parseInt(e.target.value, 10))}
                className="w-full accent-orange-500"
              />
              <div className="flex justify-between text-[10px] text-zinc-500 mt-1">
                <span>20 (compact)</span>
                <span>60 (recommended)</span>
                <span>150 (comprehensive)</span>
              </div>
            </Field>

            <Field label="Preferred regions (optional)">
              <div className="flex flex-wrap gap-1.5">
                {(['North', 'South', 'East', 'West', 'Central', 'Northeast'] as Region[]).map((r) => (
                  <button
                    key={r}
                    type="button"
                    onClick={() => toggleRegion(r)}
                    className={`px-2.5 py-1 rounded-full text-[11px] border transition-colors ${
                      regions.has(r)
                        ? 'bg-orange-500 text-black border-orange-500'
                        : 'bg-white/5 text-zinc-300 border-white/10 hover:bg-white/10'
                    }`}
                  >
                    {r}
                  </button>
                ))}
              </div>
              <p className="mt-1 text-[10px] text-zinc-500">Leave empty for no regional bias.</p>
            </Field>

            <div className="md:col-span-2">
              <Field label="Dream colleges (optional)">
                <input
                  type="text"
                  value={dreamColleges}
                  onChange={(e) => setDreamColleges(e.target.value)}
                  placeholder="e.g. NIT Trichy, NIT Surathkal, IIIT Hyderabad"
                  className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm outline-none focus:border-orange-500/60"
                />
                <p className="mt-1 text-[10px] text-zinc-500">
                  Comma-separated. We'll pin these to the top of their tier when they match.
                </p>
              </Field>
            </div>
          </div>

          <button
            type="button"
            onClick={build}
            disabled={loading}
            className="w-full md:w-auto px-6 py-3 rounded-full bg-gradient-to-r from-orange-500 to-amber-500 text-black font-bold text-sm disabled:opacity-60 transition-opacity"
          >
            {loading ? 'Building…' : 'Build my choice list'}
          </button>
        </div>

        {/* Results */}
        <AnimatePresence>
          {response && (
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.2 }}
              className="border-t border-white/5"
            >
              {!response.success && (
                <div className="p-5 text-sm text-red-300">
                  {response.error ?? 'Something went wrong.'}
                </div>
              )}

              {response.success && response.entries && response.summary && (
                <>
                  {/* Summary banner */}
                  <div className="px-5 pt-5 pb-3 grid grid-cols-3 gap-3 text-center">
                    {(['moonshot', 'target', 'safety'] as Tranche[]).map((t) => (
                      <div
                        key={t}
                        className={`rounded-xl bg-white/[0.03] border border-white/10 ring-1 ${TRANCHE_META[t].ring} p-3`}
                      >
                        <div className={`text-2xl font-bold tabular-nums ${TRANCHE_META[t].color}`}>
                          {response.summary!.by_tranche[t]}
                        </div>
                        <div className="text-[10px] uppercase tracking-wider text-zinc-500">
                          {TRANCHE_META[t].label}
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="px-5 pb-4 text-[11px] text-zinc-400 leading-relaxed">
                    <div>{response.summary.best_case}</div>
                    <div className="mt-0.5">{response.summary.worst_case}</div>
                  </div>

                  {/* Action row */}
                  <div className="px-5 pb-3 flex flex-wrap items-center gap-2 border-b border-white/5">
                    <button
                      type="button"
                      onClick={copyToClipboard}
                      className="px-4 py-2 rounded-full bg-gradient-to-r from-orange-500 to-amber-500 text-black font-bold text-xs hover:opacity-90"
                    >
                      {copied ? 'Copied ✓' : 'Copy as text'}
                    </button>
                    <button
                      type="button"
                      onClick={downloadText}
                      className="px-4 py-2 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 text-xs text-zinc-200"
                    >
                      Download .txt
                    </button>
                  </div>

                  {/* Entries — grouped by tranche */}
                  <div className="max-h-[460px] overflow-y-auto px-5 py-3 space-y-2">
                    {(['moonshot', 'target', 'safety'] as Tranche[]).map((tr) => {
                      const rows = response.entries!.filter((e) => e.tranche === tr);
                      if (rows.length === 0) return null;
                      return (
                        <div key={tr} className="space-y-2">
                          <div className={`mt-3 mb-1.5 text-[11px] uppercase tracking-[0.18em] font-semibold ${TRANCHE_META[tr].color}`}>
                            {TRANCHE_META[tr].label} tier · {rows.length} choices
                          </div>
                          {rows.map((e) => (
                            <div
                              key={`${e.college_id}-${e.branch_short_name}`}
                              className="flex items-start gap-3 p-3 rounded-lg bg-white/[0.02] border border-white/5"
                            >
                              <div className="text-[11px] font-bold text-zinc-500 tabular-nums w-6 text-right pt-0.5">
                                #{e.position}
                              </div>
                              <div className="min-w-0 flex-1">
                                <div className="text-sm text-white">
                                  <span className="font-semibold">{e.college_short_name}</span>
                                  <span className="text-zinc-400"> — {e.branch_name}</span>
                                </div>
                                <div className="text-[10px] text-zinc-500 mt-0.5">
                                  Quota {e.quota_matched} · {e.reason}
                                </div>
                              </div>
                              <div className="text-right shrink-0">
                                <div className="text-sm font-bold text-orange-400 tabular-nums">{e.probability_pct}%</div>
                              </div>
                            </div>
                          ))}
                        </div>
                      );
                    })}
                  </div>
                </>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="block text-xs font-medium uppercase tracking-wider text-zinc-500 mb-1.5">
        {label}
      </span>
      {children}
    </label>
  );
}
