// AUTO-GENERATED by scripts/college-predictor/fetch_wikipedia_images.js
// Do not edit by hand — re-run the script to refresh.
// Images are downloaded to /public/college-images so they serve same-origin.

export const COLLEGE_IMAGES: Record<string, string[]> = {
  "iit-bombay": [
    "/college-images/iit-bombay-1.jpg",
    "/college-images/iit-bombay-2.jpg",
    "/college-images/iit-bombay-3.jpg",
    "/college-images/iit-bombay-4.jpg"
  ],
  "iit-delhi": [
    "/college-images/iit-delhi-1.jpg",
    "/college-images/iit-delhi-2.jpg",
    "/college-images/iit-delhi-3.jpg",
    "/college-images/iit-delhi-4.jpg"
  ],
  "iit-madras": [
    "/college-images/iit-madras-1.jpg",
    "/college-images/iit-madras-2.jpg",
    "/college-images/iit-madras-3.png",
    "/college-images/iit-madras-4.jpg"
  ],
  "iit-kanpur": [
    "/college-images/iit-kanpur-1.jpg",
    "/college-images/iit-kanpur-2.jpg",
    "/college-images/iit-kanpur-3.jpg",
    "/college-images/iit-kanpur-4.jpg"
  ],
  "iit-kharagpur": [
    "/college-images/iit-kharagpur-1.jpg",
    "/college-images/iit-kharagpur-2.jpg",
    "/college-images/iit-kharagpur-3.jpg",
    "/college-images/iit-kharagpur-4.jpg"
  ],
  "iit-roorkee": [
    "/college-images/iit-roorkee-1.jpg",
    "/college-images/iit-roorkee-2.jpg",
    "/college-images/iit-roorkee-3.jpg",
    "/college-images/iit-roorkee-4.jpg"
  ],
  "iit-guwahati": [
    "/college-images/iit-guwahati-1.jpg",
    "/college-images/iit-guwahati-2.jpg",
    "/college-images/iit-guwahati-3.jpg",
    "/college-images/iit-guwahati-4.jpg"
  ],
  "iit-bhu": [
    "/college-images/iit-bhu-1.jpg",
    "/college-images/iit-bhu-2.jpg",
    "/college-images/iit-bhu-3.jpg",
    "/college-images/iit-bhu-4.jpg"
  ],
  "nit-trichy": [
    "/college-images/nit-trichy-1.jpg",
    "/college-images/nit-trichy-2.jpg",
    "/college-images/nit-trichy-3.jpg",
    "/college-images/nit-trichy-4.jpg"
  ],
  "nit-warangal": [
    "/college-images/nit-warangal-1.jpg",
    "/college-images/nit-warangal-2.jpg",
    "/college-images/nit-warangal-3.jpg"
  ],
  "nit-surathkal": [
    "/college-images/nit-surathkal-1.jpg",
    "/college-images/nit-surathkal-2.jpg",
    "/college-images/nit-surathkal-3.jpg",
    "/college-images/nit-surathkal-4.jpg"
  ],
  "nit-calicut": [
    "/college-images/nit-calicut-1.jpg",
    "/college-images/nit-calicut-2.jpg",
    "/college-images/nit-calicut-3.jpg"
  ],
  "nit-rourkela": [
    "/college-images/nit-rourkela-1.jpg",
    "/college-images/nit-rourkela-2.jpg",
    "/college-images/nit-rourkela-3.jpg"
  ],
  "mnit-jaipur": [
    "/college-images/mnit-jaipur-1.jpg",
    "/college-images/mnit-jaipur-2.jpg",
    "/college-images/mnit-jaipur-3.jpg",
    "/college-images/mnit-jaipur-4.jpg"
  ],
  "vnit-nagpur": [
    "/college-images/vnit-nagpur-1.jpg",
    "/college-images/vnit-nagpur-2.jpg",
    "/college-images/vnit-nagpur-3.jpg",
    "/college-images/vnit-nagpur-4.jpg"
  ],
  "mnnit-allahabad": [
    "/college-images/mnnit-allahabad-1.jpg",
    "/college-images/mnnit-allahabad-2.jpg",
    "/college-images/mnnit-allahabad-3.jpg"
  ],
  "iiit-hyderabad": [
    "/college-images/iiit-hyderabad-1.jpg",
    "/college-images/iiit-hyderabad-2.jpg",
    "/college-images/iiit-hyderabad-3.jpg",
    "/college-images/iiit-hyderabad-4.jpg"
  ],
  "iiit-bangalore": [
    "/college-images/iiit-bangalore-1.jpg",
    "/college-images/iiit-bangalore-2.jpg",
    "/college-images/iiit-bangalore-3.jpg",
    "/college-images/iiit-bangalore-4.jpg"
  ],
  "iiit-delhi": [
    "/college-images/iiit-delhi-1.jpg",
    "/college-images/iiit-delhi-2.jpg",
    "/college-images/iiit-delhi-3.jpg"
  ],
  "iiit-allahabad": [
    "/college-images/iiit-allahabad-1.jpg",
    "/college-images/iiit-allahabad-2.jpg",
    "/college-images/iiit-allahabad-3.jpg",
    "/college-images/iiit-allahabad-4.jpg"
  ],
  "abv-iiitm-gwalior": [
    "/college-images/abv-iiitm-gwalior-1.jpg",
    "/college-images/abv-iiitm-gwalior-2.jpg",
    "/college-images/abv-iiitm-gwalior-3.jpg",
    "/college-images/abv-iiitm-gwalior-4.jpg"
  ],
  "bits-pilani": [
    "/college-images/bits-pilani-1.jpg",
    "/college-images/bits-pilani-2.png",
    "/college-images/bits-pilani-3.jpg",
    "/college-images/bits-pilani-4.jpg"
  ],
  "bits-goa": [
    "/college-images/bits-goa-1.jpg",
    "/college-images/bits-goa-2.jpg",
    "/college-images/bits-goa-3.jpg",
    "/college-images/bits-goa-4.jpg"
  ],
  "bits-hyderabad": [
    "/college-images/bits-hyderabad-1.jpg",
    "/college-images/bits-hyderabad-2.jpg",
    "/college-images/bits-hyderabad-3.jpg",
    "/college-images/bits-hyderabad-4.jpg"
  ],
  "vit-vellore": [
    "/college-images/vit-vellore-1.jpg",
    "/college-images/vit-vellore-2.jpg",
    "/college-images/vit-vellore-3.jpg",
    "/college-images/vit-vellore-4.jpg"
  ],
  "thapar": [
    "/college-images/thapar-1.jpg",
    "/college-images/thapar-2.jpg",
    "/college-images/thapar-3.jpg"
  ],
  "srm-chennai": [
    "/college-images/srm-chennai-1.jpg",
    "/college-images/srm-chennai-2.jpg",
    "/college-images/srm-chennai-3.jpg",
    "/college-images/srm-chennai-4.jpg"
  ],
  "manipal": [
    "/college-images/manipal-1.jpg",
    "/college-images/manipal-2.jpg",
    "/college-images/manipal-3.jpg",
    "/college-images/manipal-4.jpg"
  ],
  "shiv-nadar": [
    "/college-images/shiv-nadar-1.jpg",
    "/college-images/shiv-nadar-2.jpg",
    "/college-images/shiv-nadar-3.jpg"
  ]
};

export const TOP_COLLEGES_HERO_IMAGE: string | null = "/college-images/_hero.jpg";
