// ============================================
// Top engineering colleges — static content used by the predictor page.
// Facts chosen for durability: qualitative NIRF claims over exact ranks
// (which change yearly) and only well-established distinctives.
// Image URLs come from topCollegesImages.ts, auto-generated by
// scripts/college-predictor/fetch_wikipedia_images.js.
// ============================================

import { COLLEGE_IMAGES, TOP_COLLEGES_HERO_IMAGE } from './topCollegesImages';

export type Tier = 'IIT' | 'NIT' | 'IIIT' | 'BITS' | 'Private';

export interface TopCollege {
  slug: string;
  name: string;             // display name e.g. "IIT Bombay"
  fullName: string;         // official full name
  tier: Tier;
  city: string;
  state: string;
  established: number;
  description: string;      // 2-3 sentences
  fees: string;             // compact 4-year institute fee for general category, excl. hostel/mess, e.g. "~₹9 L (4 yrs)"
  flagshipBranches: string[]; // 3 most sought/recognized undergraduate programmes
  connectivity: {
    road: string;
    rail: string;
    air: string;
  };
  climate: string;
  images?: string[];        // Wikipedia Commons URLs — populated by Phase 2 script
}

// Ultra-wide hero image shown above the Top Colleges section.
// Populated by fetch_wikipedia_images.js; falls back to gradient when empty.
export const TOP_COLLEGES_HERO: string | null = TOP_COLLEGES_HERO_IMAGE;

export const TOP_COLLEGES: TopCollege[] = [
  // ── IITs ───────────────────────────────────────────────────────────────────
  {
    slug: 'iit-bombay',
    name: 'IIT Bombay',
    fullName: 'Indian Institute of Technology Bombay',
    tier: 'IIT',
    city: 'Mumbai',
    state: 'Maharashtra',
    established: 1958,
    description:
      'Among the most sought-after IITs, known for record-setting placements and a strong startup culture. The Powai campus sits next to Powai Lake and Sanjay Gandhi National Park. Computer Science, Electrical, and Mechanical are the flagship programs.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Electrical', 'Mechanical'],
    connectivity: {
      road: 'Well-connected via Eastern Express Highway; Mumbai metro and monorail nearby.',
      rail: 'Kanjurmarg and Vikhroli on the Central Line (~5 km); Mumbai suburban network reaches the whole city.',
      air: 'Chhatrapati Shivaji Maharaj International Airport ~7 km.',
    },
    climate: 'Tropical coastal — hot humid summers (28-35°C), heavy June-Sept monsoon, mild pleasant winters.',
  },
  {
    slug: 'iit-delhi',
    name: 'IIT Delhi',
    fullName: 'Indian Institute of Technology Delhi',
    tier: 'IIT',
    city: 'New Delhi',
    state: 'Delhi',
    established: 1961,
    description:
      'A Delhi institution at Hauz Khas with a premium South Delhi location, heavy research output, and top placements. Consistently top 3 in NIRF Engineering, with CSE, Electrical, and Mathematics & Computing among its most competitive programs.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Math & Computing', 'Electrical'],
    connectivity: {
      road: 'On NH-48; Outer Ring Road adjoins the campus.',
      rail: 'New Delhi and Hazrat Nizamuddin stations ~12 km; Delhi Metro IIT station (Magenta Line) at the campus gate.',
      air: 'Indira Gandhi International Airport ~15 km.',
    },
    climate: 'Semi-arid — very hot dry summers (up to 45°C), cold foggy winters (down to 4°C), short July-Sept monsoon.',
  },
  {
    slug: 'iit-madras',
    name: 'IIT Madras',
    fullName: 'Indian Institute of Technology Madras',
    tier: 'IIT',
    city: 'Chennai',
    state: 'Tamil Nadu',
    established: 1959,
    description:
      'Ranked #1 in NIRF Engineering for several consecutive years. The 620-acre forest campus is a protected wildlife reserve with deer and blackbuck roaming freely. Known for deep research ecosystems and strength across every engineering discipline.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Electrical', 'Mechanical'],
    connectivity: {
      road: 'On Sardar Patel Road; linked to GST Road and the Chennai ring roads.',
      rail: 'Chennai Central and Egmore ~15 km; Chennai Metro Guindy station nearby.',
      air: 'Chennai International Airport ~15 km.',
    },
    climate: 'Tropical coastal — hot humid year-round (26-38°C), heavy North-East monsoon Oct-Dec.',
  },
  {
    slug: 'iit-kanpur',
    name: 'IIT Kanpur',
    fullName: 'Indian Institute of Technology Kanpur',
    tier: 'IIT',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    established: 1959,
    description:
      'Pioneer of Computer Science education in India with one of the oldest CS departments. The 1,000-acre campus houses a flight lab and an airstrip — a legacy of its early aerospace focus. Consistently top-5 in NIRF Engineering.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Electrical', 'Aerospace'],
    connectivity: {
      road: 'On GT Road / NH-19; NH-27 passes through Kanpur.',
      rail: 'Kanpur Central ~15 km — one of India\'s busiest junctions.',
      air: 'Kanpur Airport ~17 km (limited flights); Lucknow CCS International ~80 km is the major hub.',
    },
    climate: 'Humid subtropical — very hot summers (up to 47°C), cold foggy winters, heavy July-Sept monsoon.',
  },
  {
    slug: 'iit-kharagpur',
    name: 'IIT Kharagpur',
    fullName: 'Indian Institute of Technology Kharagpur',
    tier: 'IIT',
    city: 'Kharagpur',
    state: 'West Bengal',
    established: 1951,
    description:
      'The first IIT (1951), founded in a former pre-independence detention camp. India\'s largest IIT by campus area (~2,100 acres), with the broadest department mix — including Architecture, Mining, Ocean Engineering, and Agricultural Engineering.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Electrical', 'Mechanical'],
    connectivity: {
      road: 'On NH-16 (Kolkata–Chennai corridor).',
      rail: 'Kharagpur Junction ~8 km — historically home to one of the world\'s longest railway platforms.',
      air: 'Kolkata (NSCBI) ~125 km.',
    },
    climate: 'Tropical — hot humid summers, heavy monsoon, pleasant short winters.',
  },
  {
    slug: 'iit-roorkee',
    name: 'IIT Roorkee',
    fullName: 'Indian Institute of Technology Roorkee',
    tier: 'IIT',
    city: 'Roorkee',
    state: 'Uttarakhand',
    established: 1847,
    description:
      'India\'s oldest engineering institution (founded 1847 as Thomason College), upgraded to IIT in 2001. Particularly strong in Civil, Water Resources, and Earthquake Engineering. Located at the Himalayan foothills with cool hill proximity.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Electrical', 'Civil'],
    connectivity: {
      road: 'On NH-334; connected to Delhi, Dehradun, and Haridwar.',
      rail: 'Roorkee station on the Delhi–Dehradun line (~5 km).',
      air: 'Dehradun (Jolly Grant) ~70 km; Delhi IGI ~180 km.',
    },
    climate: 'Humid subtropical — hot summers (up to 42°C), chilly winters with occasional frost, monsoon July-Sept.',
  },
  {
    slug: 'iit-guwahati',
    name: 'IIT Guwahati',
    fullName: 'Indian Institute of Technology Guwahati',
    tier: 'IIT',
    city: 'Guwahati',
    state: 'Assam',
    established: 1994,
    description:
      'The youngest of the "old seven" IITs, with a picturesque campus along the Brahmaputra river at the foothills of the Himalayas. Fast-rising NIRF position, with CSE, Electronics, and Design among the strongest programs.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Design'],
    connectivity: {
      road: 'On NH-27 (East-West Corridor).',
      rail: 'Guwahati station ~25 km — the major rail gateway to Northeast India.',
      air: 'Lokpriya Gopinath Bordoloi International Airport ~20 km.',
    },
    climate: 'Humid subtropical — warm humid summers, very heavy May-Sept monsoon, mild winters.',
  },
  {
    slug: 'iit-bhu',
    name: 'IIT (BHU) Varanasi',
    fullName: 'Indian Institute of Technology (BHU) Varanasi',
    tier: 'IIT',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    established: 1919,
    description:
      'Formed in 2012 by upgrading the century-old Banaras Engineering College (1919) inside the iconic Banaras Hindu University campus. Strong legacy departments — Mining, Metallurgy, Ceramic, and Pharmaceutical Engineering — reflect its BHU heritage.',
    fees: '~₹9 L (4 yrs)',
    flagshipBranches: ['CSE', 'Electrical', 'Mechanical'],
    connectivity: {
      road: 'On NH-19 (Grand Trunk Road); on the Varanasi ring road.',
      rail: 'Varanasi Junction and Banaras stations ~10 km.',
      air: 'Lal Bahadur Shastri International Airport ~25 km.',
    },
    climate: 'Humid subtropical — very hot summers (up to 45°C), foggy cold winters, heavy monsoon.',
  },

  // ── NITs ───────────────────────────────────────────────────────────────────
  {
    slug: 'nit-trichy',
    name: 'NIT Trichy',
    fullName: 'National Institute of Technology, Tiruchirappalli',
    tier: 'NIT',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    established: 1964,
    description:
      'Consistently the top-ranked NIT in India. CSE, ECE, and Electrical placements rival mid-tier IITs, and its 800-acre lush campus is one of the prettiest NIT campuses.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Electrical'],
    connectivity: {
      road: 'On NH-38 (Trichy-Chennai); NH-83 to Madurai.',
      rail: 'Tiruchirappalli Junction ~15 km.',
      air: 'Tiruchirappalli International Airport ~5 km.',
    },
    climate: 'Hot semi-arid — very hot dry summers (up to 40°C), mild winters, sparse rain.',
  },
  {
    slug: 'nit-warangal',
    name: 'NIT Warangal',
    fullName: 'National Institute of Technology, Warangal',
    tier: 'NIT',
    city: 'Warangal',
    state: 'Telangana',
    established: 1959,
    description:
      'India\'s first Regional Engineering College (1959), now perennially in the top three NITs. Strong across CSE, ECE, and Mechanical. About 2.5 hours from Hyderabad, giving easy access to the city\'s tech ecosystem.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'EEE'],
    connectivity: {
      road: 'On NH-163; ~150 km from Hyderabad via NH-163.',
      rail: 'Kazipet Junction (~10 km) and Warangal station (~5 km) on the Chennai–Delhi line.',
      air: 'Hyderabad (Rajiv Gandhi International) ~150 km.',
    },
    climate: 'Tropical — very hot dry summers (up to 44°C), pleasant winters, moderate monsoon.',
  },
  {
    slug: 'nit-surathkal',
    name: 'NIT Karnataka (Surathkal)',
    fullName: 'National Institute of Technology Karnataka, Surathkal',
    tier: 'NIT',
    city: 'Mangalore (Surathkal)',
    state: 'Karnataka',
    established: 1960,
    description:
      'Beachfront campus directly on the Arabian Sea — the only NIT with its own beach. Historically top-three NITs, with strong Mechanical, Civil, and CSE programs. Unique coastal setting draws students from across India.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'Mechanical', 'Civil'],
    connectivity: {
      road: 'On NH-66 (Mumbai-Kanyakumari coastal highway).',
      rail: 'Surathkal station (~2 km) on the Konkan Railway.',
      air: 'Mangalore International Airport ~25 km.',
    },
    climate: 'Tropical coastal — warm humid year-round (24-34°C), very heavy SW monsoon June-Sept.',
  },
  {
    slug: 'nit-calicut',
    name: 'NIT Calicut',
    fullName: 'National Institute of Technology Calicut',
    tier: 'NIT',
    city: 'Kozhikode',
    state: 'Kerala',
    established: 1961,
    description:
      'Lush Western Ghats campus in Kerala, among the most scenic NITs. Strong in Architecture, CSE, and ECE; popular with students who want a top NIT in a green, pleasant setting.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Architecture'],
    connectivity: {
      road: 'On NH-66; ~22 km north of Kozhikode city on the Mukkam route.',
      rail: 'Kozhikode station ~22 km.',
      air: 'Calicut International Airport (Karipur) ~30 km.',
    },
    climate: 'Tropical coastal — warm humid year-round (24-33°C), very heavy monsoon June-Sept.',
  },
  {
    slug: 'nit-rourkela',
    name: 'NIT Rourkela',
    fullName: 'National Institute of Technology Rourkela',
    tier: 'NIT',
    city: 'Rourkela',
    state: 'Odisha',
    established: 1961,
    description:
      'Large 648-acre campus in Odisha\'s steel city. Traditional strength in Metallurgy, Ceramic, and Mining Engineering (reflecting regional industry), alongside strong and rising CSE and ECE placements.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'Metallurgical', 'Mechanical'],
    connectivity: {
      road: 'On NH-143; industrial steel-belt connectivity.',
      rail: 'Rourkela Junction ~5 km on the Howrah–Mumbai line.',
      air: 'Jharsuguda (~105 km) or Ranchi (~165 km); direct flights limited.',
    },
    climate: 'Tropical — hot summers (up to 43°C), mild winters, heavy monsoon.',
  },
  {
    slug: 'mnit-jaipur',
    name: 'MNIT Jaipur',
    fullName: 'Malaviya National Institute of Technology Jaipur',
    tier: 'NIT',
    city: 'Jaipur',
    state: 'Rajasthan',
    established: 1963,
    description:
      'Located in Jaipur\'s Malaviya Nagar, close to the Pink City\'s urban core. Known for Civil, Architecture, and Electronics programs, with a strong alumni network in Indian Railways and civil services.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Architecture'],
    connectivity: {
      road: 'On NH-48 (Delhi-Mumbai); city-accessible.',
      rail: 'Jaipur Junction ~7 km.',
      air: 'Jaipur International Airport ~12 km.',
    },
    climate: 'Hot semi-arid — very hot dry summers (up to 46°C), cold winters (down to 5°C), sparse rain.',
  },
  {
    slug: 'vnit-nagpur',
    name: 'VNIT Nagpur',
    fullName: 'Visvesvaraya National Institute of Technology Nagpur',
    tier: 'NIT',
    city: 'Nagpur',
    state: 'Maharashtra',
    established: 1960,
    description:
      'Located in Nagpur, the geographical heart of India. Strong in Mechanical, Electrical, and Civil — with steadily growing CSE intake. The city\'s MIHAN SEZ offers rising internship opportunities.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Civil'],
    connectivity: {
      road: 'On NH-44 and NH-53 (Nagpur is a key central India junction).',
      rail: 'Nagpur Junction ~5 km — major central India railway hub.',
      air: 'Dr. Babasaheb Ambedkar International Airport ~5 km.',
    },
    climate: 'Tropical — very hot dry summers (up to 47°C), mild winters, moderate monsoon.',
  },
  {
    slug: 'mnnit-allahabad',
    name: 'MNNIT Allahabad',
    fullName: 'Motilal Nehru National Institute of Technology Allahabad',
    tier: 'NIT',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    established: 1961,
    description:
      'One of the oldest NITs, established in 1961 and upgraded in 2002. Prayagraj\'s Sangam location adds civilizational heritage to the campus; known for solid Computer Science and Electronics programs.',
    fees: '~₹6.5 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Electrical'],
    connectivity: {
      road: 'On NH-19 (GT Road); well-connected central UP.',
      rail: 'Prayagraj Junction ~5 km on the Delhi–Howrah trunk line.',
      air: 'Prayagraj Airport ~15 km; Varanasi Airport ~125 km.',
    },
    climate: 'Humid subtropical — very hot summers (up to 46°C), cold foggy winters, heavy July-Sept monsoon.',
  },

  // ── IIITs ──────────────────────────────────────────────────────────────────
  {
    slug: 'iiit-hyderabad',
    name: 'IIIT Hyderabad',
    fullName: 'International Institute of Information Technology, Hyderabad',
    tier: 'IIIT',
    city: 'Hyderabad',
    state: 'Telangana',
    established: 1998,
    description:
      'The premier IIIT for Computer Science and research. Not a JoSAA college — admits through JEE Main + its own counseling process. Located in Gachibowli\'s IT corridor; placements in CS roles rival the top IITs.',
    fees: '~₹13 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Comp. Nat. Sciences'],
    connectivity: {
      road: 'On the Outer Ring Road; Gachibowli IT corridor.',
      rail: 'Secunderabad (~20 km) and Hyderabad Deccan (~15 km).',
      air: 'Rajiv Gandhi International Airport ~25 km.',
    },
    climate: 'Tropical savanna — warm most of the year (20-38°C), mild winters, moderate monsoon.',
  },
  {
    slug: 'iiit-bangalore',
    name: 'IIIT Bangalore',
    fullName: 'International Institute of Information Technology, Bangalore',
    tier: 'IIIT',
    city: 'Bengaluru',
    state: 'Karnataka',
    established: 1999,
    description:
      'A PPP-model IIIT in Bengaluru\'s Electronic City, known for research-driven CS and Electronics education. Most students are on integrated M.Tech / PG programs; academic rigor is high.',
    fees: '~₹16 L (5 yrs integrated)',
    flagshipBranches: ['Integrated M.Tech CSE', 'Integrated M.Tech ECE', 'Digital Society'],
    connectivity: {
      road: 'On NH-44 via Hosur Road; Electronic City Elevated Expressway access.',
      rail: 'Bengaluru City (KSR) ~22 km.',
      air: 'Kempegowda International Airport ~55 km.',
    },
    climate: 'Tropical savanna — mild year-round (17-30°C), moderate June-Oct monsoon, pleasant winters.',
  },
  {
    slug: 'iiit-delhi',
    name: 'IIIT Delhi',
    fullName: 'Indraprastha Institute of Information Technology Delhi',
    tier: 'IIIT',
    city: 'New Delhi',
    state: 'Delhi',
    established: 2008,
    description:
      'A Delhi state government university in Okhla, with a focused research culture and interdisciplinary CS programs (CS + Biosciences, CS + Design, CS + Social Sciences). Small cohort, strong tech placements.',
    fees: '~₹16 L (4 yrs)',
    flagshipBranches: ['CSE', 'CS + Applied Maths', 'ECE'],
    connectivity: {
      road: 'On the Okhla industrial area; Ring Road accessible.',
      rail: 'Hazrat Nizamuddin ~8 km; New Delhi ~18 km.',
      air: 'IGI Airport ~20 km; Delhi Metro Okhla Vihar / Govindpuri nearby.',
    },
    climate: 'Semi-arid — very hot dry summers (up to 45°C), cold winters (down to 4°C).',
  },
  {
    slug: 'iiit-allahabad',
    name: 'IIIT Allahabad',
    fullName: 'Indian Institute of Information Technology Allahabad',
    tier: 'IIIT',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    established: 1999,
    description:
      'The first IIIT under the Ministry of Education (1999). Known for its Information Technology and Computer Science programs and a large alumni network across core tech and product companies.',
    fees: '~₹8 L (4 yrs)',
    flagshipBranches: ['IT', 'ECE', 'IT + Business Informatics'],
    connectivity: {
      road: 'On the Devghat-Jhalwa road; NH-19 connects Prayagraj.',
      rail: 'Prayagraj Junction ~20 km.',
      air: 'Prayagraj Airport ~12 km; Varanasi ~135 km.',
    },
    climate: 'Humid subtropical — very hot summers, cold foggy winters, heavy July-Sept monsoon.',
  },
  {
    slug: 'abv-iiitm-gwalior',
    name: 'ABV-IIITM Gwalior',
    fullName: 'Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior',
    tier: 'IIIT',
    city: 'Gwalior',
    state: 'Madhya Pradesh',
    established: 1997,
    description:
      'Among the earliest IIITs (1997). Offers distinctive 5-year integrated IT and Management programs. Scenic campus on Morena Link Road, close to the historic Gwalior Fort.',
    fees: '~₹11 L (5 yrs integrated)',
    flagshipBranches: ['IT dual degree', 'CSE', 'ECE'],
    connectivity: {
      road: 'On NH-44 (north-south central corridor).',
      rail: 'Gwalior Junction ~10 km.',
      air: 'Gwalior Airport (limited); Agra ~120 km; Delhi ~320 km.',
    },
    climate: 'Humid subtropical — hot summers (up to 45°C), chilly winters, moderate monsoon.',
  },

  // ── BITS campuses ──────────────────────────────────────────────────────────
  {
    slug: 'bits-pilani',
    name: 'BITS Pilani',
    fullName: 'Birla Institute of Technology and Science, Pilani',
    tier: 'BITS',
    city: 'Pilani',
    state: 'Rajasthan',
    established: 1964,
    description:
      'India\'s most prestigious private engineering institute. Admission purely through BITSAT (merit-only, no reservations in the central admission). Known for a flexible curriculum with dual degrees and minors, the "Practice School" industry program, and a strong Silicon Valley alumni network.',
    fees: '~₹22 L (4 yrs)',
    flagshipBranches: ['CSE', 'EEE', 'Mechanical'],
    connectivity: {
      road: 'On NH-11; Pilani is ~220 km from Delhi, ~230 km from Jaipur.',
      rail: 'Loharu (~30 km) and Chirawa (~20 km) are the closest stations.',
      air: 'Delhi (IGI) ~220 km or Jaipur ~230 km — the standard travel routes.',
    },
    climate: 'Semi-arid desert fringe — very hot dry summers (up to 47°C), chilly winters (down to 3°C), sparse rain.',
  },
  {
    slug: 'bits-goa',
    name: 'BITS Pilani, Goa',
    fullName: 'Birla Institute of Technology and Science, Pilani — Goa Campus',
    tier: 'BITS',
    city: 'Zuarinagar',
    state: 'Goa',
    established: 2004,
    description:
      'Same rigorous BITSAT-based curriculum as Pilani, set on a scenic South Goa campus close to beaches. Popular for its setting, coastal lifestyle, and strong CS and Electronics intake.',
    fees: '~₹22 L (4 yrs)',
    flagshipBranches: ['CSE', 'EEE', 'Mechanical'],
    connectivity: {
      road: 'On NH-66 (coastal highway); close to Vasco.',
      rail: 'Madgaon ~25 km; Vasco-da-Gama ~15 km.',
      air: 'Dabolim (GOI) ~15 km; Mopa (new Goa airport) ~50 km.',
    },
    climate: 'Tropical coastal — warm humid year-round (22-33°C), very heavy SW monsoon June-Sept.',
  },
  {
    slug: 'bits-hyderabad',
    name: 'BITS Pilani, Hyderabad',
    fullName: 'Birla Institute of Technology and Science, Pilani — Hyderabad Campus',
    tier: 'BITS',
    city: 'Hyderabad',
    state: 'Telangana',
    established: 2008,
    description:
      'Established 2008 in north Hyderabad\'s Jawahar Nagar, leveraging the city\'s tech ecosystem. Same curriculum as Pilani and Goa; Computer Science and Electronics dominate admissions.',
    fees: '~₹22 L (4 yrs)',
    flagshipBranches: ['CSE', 'EEE', 'ECE'],
    connectivity: {
      road: 'On the Outer Ring Road; off NH-44 north of Hyderabad.',
      rail: 'Secunderabad ~30 km.',
      air: 'Rajiv Gandhi International Airport ~45 km.',
    },
    climate: 'Tropical savanna — warm year-round (20-38°C), mild winters, moderate monsoon.',
  },

  // ── Private ────────────────────────────────────────────────────────────────
  {
    slug: 'vit-vellore',
    name: 'VIT Vellore',
    fullName: 'Vellore Institute of Technology, Vellore',
    tier: 'Private',
    city: 'Vellore',
    state: 'Tamil Nadu',
    established: 1984,
    description:
      'One of India\'s largest private engineering institutions. Admission via VITEEE. Known for a broad set of CS specializations, an active international exchange program, and consistent NIRF top-15 Engineering rankings.',
    fees: '~₹8-14 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Mechanical'],
    connectivity: {
      road: 'On NH-48 (Chennai-Bengaluru); NH-46 nearby.',
      rail: 'Katpadi Junction ~5 km on the Chennai-Bengaluru main line.',
      air: 'Chennai International ~140 km; Bengaluru ~225 km.',
    },
    climate: 'Hot semi-arid — hot dry summers (up to 40°C), mild winters, moderate NE monsoon.',
  },
  {
    slug: 'thapar',
    name: 'Thapar Institute',
    fullName: 'Thapar Institute of Engineering and Technology, Patiala',
    tier: 'Private',
    city: 'Patiala',
    state: 'Punjab',
    established: 1956,
    description:
      'One of India\'s oldest private engineering institutions (1956). Admits through JEE Main. Strong in Computer Science, Mechanical, and Chemical Engineering, with a robust academic culture and industry ties.',
    fees: '~₹17 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Mechanical'],
    connectivity: {
      road: 'On NH-7; well-connected within Punjab.',
      rail: 'Patiala Junction ~3 km.',
      air: 'Chandigarh Airport ~65 km; Delhi IGI ~245 km.',
    },
    climate: 'Semi-arid — very hot summers (up to 45°C), cold winters (down to 3°C), short monsoon.',
  },
  {
    slug: 'srm-chennai',
    name: 'SRM Chennai',
    fullName: 'SRM Institute of Science and Technology, Kattankulathur',
    tier: 'Private',
    city: 'Kattankulathur',
    state: 'Tamil Nadu',
    established: 1985,
    description:
      'A deemed university with a large campus south of Chennai. Admits via SRMJEEE or JEE Main. Broad CS and ECE specializations, a large placement pool, and active student clubs across specializations.',
    fees: '~₹10-15 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Mechanical'],
    connectivity: {
      road: 'On NH-45 (GST Road, Chennai-Trichy).',
      rail: 'Potheri station on-campus — stops on the Chennai Beach-Chengalpattu line.',
      air: 'Chennai International ~25 km.',
    },
    climate: 'Tropical coastal — hot humid year-round (26-38°C), heavy NE monsoon Oct-Dec.',
  },
  {
    slug: 'manipal',
    name: 'MIT Manipal',
    fullName: 'Manipal Institute of Technology, Manipal',
    tier: 'Private',
    city: 'Manipal',
    state: 'Karnataka',
    established: 1957,
    description:
      'Part of the Manipal Academy of Higher Education (est. 1957). Admission via MET or JEE Main. Iconic "college town" atmosphere, international student mix, and strong Mechanical, CSE, and Biotechnology programs.',
    fees: '~₹18 L (4 yrs)',
    flagshipBranches: ['CSE', 'Mechanical', 'Aeronautical'],
    connectivity: {
      road: 'On NH-66 (coastal highway); ~60 km north of Mangalore.',
      rail: 'Udupi station ~8 km on the Konkan Railway.',
      air: 'Mangalore International Airport ~65 km.',
    },
    climate: 'Tropical coastal — warm humid year-round (22-33°C), very heavy SW monsoon.',
  },
  {
    slug: 'shiv-nadar',
    name: 'Shiv Nadar IoE',
    fullName: 'Shiv Nadar Institution of Eminence, Greater Noida',
    tier: 'Private',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    established: 2011,
    description:
      'Established 2011 by the Shiv Nadar Foundation; designated an Institution of Eminence. Small-cohort residential campus blending rigorous CSE and Data Science with liberal-arts cross-electives. Admission via SNUSAT.',
    fees: '~₹20 L (4 yrs)',
    flagshipBranches: ['CSE', 'ECE', 'Data Science'],
    connectivity: {
      road: 'Off the Yamuna Expressway, ~35 km from Greater Noida city centre.',
      rail: 'Ghaziabad and Anand Vihar ~55 km; New Delhi ~65 km.',
      air: 'Indira Gandhi International ~60 km; Jewar (upcoming Noida Intl) ~30 km.',
    },
    climate: 'Semi-arid — very hot dry summers (up to 45°C), cold foggy winters, moderate monsoon.',
  },
];

// Merge auto-generated Wikipedia image URLs into each college at module load.
for (const c of TOP_COLLEGES) {
  const urls = COLLEGE_IMAGES[c.slug];
  if (urls && urls.length > 0) c.images = urls;
}

export const TIER_INTROS: Record<Tier, { heading: string; blurb: string }> = {
  IIT: {
    heading: 'Top IITs',
    blurb:
      'The Indian Institutes of Technology are the country\'s flagship engineering schools, admitted through JEE Advanced. Below are eight that consistently rank at the top of NIRF Engineering.',
  },
  NIT: {
    heading: 'Top NITs',
    blurb:
      'National Institutes of Technology admit via JEE Main + JoSAA counseling. Below are the eight NITs that consistently anchor the top of NIRF among NITs.',
  },
  IIIT: {
    heading: 'Top IIITs',
    blurb:
      'Indian Institutes of Information Technology specialise in CS and related fields. Below are five IIITs with the strongest reputations — note that IIIT Hyderabad and IIIT Bangalore run their own admissions, not JoSAA.',
  },
  BITS: {
    heading: 'BITS Pilani campuses',
    blurb:
      'BITS admits purely through BITSAT — no JEE, no reservations in central admission. All three campuses share the same curriculum and degree; the location and culture differ.',
  },
  Private: {
    heading: 'Top private universities',
    blurb:
      'Reputable private engineering universities that admit through JEE Main or their own entrance tests. Fees are higher than NITs/IITs, but admissions are broader and campus facilities are typically extensive.',
  },
};

export const TIER_ORDER: Tier[] = ['IIT', 'NIT', 'IIIT', 'BITS', 'Private'];
