// Seed career database — Phase 1 MVP (30 careers).
//
// Mix of mainstream and hidden-gem careers. Every career gets the nine-layer
// taxonomy, even when values are rough — we want the matcher to have
// something on every axis. Editorial team will refine via the admin panel.
//
// Money is in ₹ lakhs per annum unless noted. Ranges are intentionally
// conservative — we'd rather be slightly pessimistic than oversell.

import type { ICareerPath } from '@/lib/models/CareerPath';

type SeedCareer = Omit<ICareerPath, 'created_at' | 'updated_at'>;

export const SEED_CAREERS: SeedCareer[] = [
  // ── Mainstream engineering / tech ───────────────────────────────────────
  {
    _id: 'software-engineer',
    name: 'Software Engineer',
    family: 'Technology → Software',
    one_liner: 'Builds, ships, and maintains software products and systems.',
    typical_titles: ['SDE', 'Backend Engineer', 'Full-stack Engineer', 'Staff Engineer'],
    riasec_primary: 'I', riasec_secondary: ['R', 'C'],
    cognitive_styles: ['logical', 'numerical', 'spatial'],
    hard_filters: { min_logical: 3 },
    indoor_outdoor: 10, desk_field: 15, solo_team: 60,
    communication_intensity: 3, public_facing: 2, travel: 'occasional',
    work_hours: 'flexible', physical_demand: 1,
    stress_profile: 'deadline-driven, sustained cognitive load',
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 20], premium_inr_lakh: [20, 45] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [6, 12], mid_salary_inr_lpa: [18, 45], top_salary_inr_lpa: [60, 200],
    roi_timeline_years: 3, scholarship_availability: 3, loan_worthiness: 5,
    india_market_depth: 5, metro_concentration: 4, international_mobility: 5,
    top_destinations: ['USA', 'Germany', 'UK', 'Canada', 'Singapore'],
    licensing_portability: 'easy', remote_feasibility: 5, immigration_pathway: 5,
    automation_vulnerability: 3, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    ten_year_outlook: 'Reshaped by AI. Product and systems thinking will matter more than pure code output.',
    disruption_risks: ['AI code generation', 'offshoring'],
    adjacent_pivots: ['Product Manager', 'ML Engineer', 'Tech Entrepreneur'],
    required_stream: ['PCM', 'Any'], entrance_exams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'CUET'],
    degree_paths: ['B.Tech CS/IT', 'BCA + MCA', 'B.Sc CS'],
    min_qualification: 'B.Tech or equivalent',
    alternative_paths: ['Self-taught + bootcamp → entry-level role'],
    job_stability: 4, work_life_balance: 3, social_prestige_india: 4, autonomy: 4,
    creative_expression: 3, impact: 3,
    day_in_life: 'Mornings usually start with standups and checking what broke overnight. The day splits between deep-focus blocks (writing code, reviewing PRs) and short bursts of collaboration on Slack or calls. Good days end with a feature shipped or a nasty bug cornered; tough days are spent debugging something that makes no sense until it suddenly does. Remote or hybrid is common. You rarely wear anything formal.',
    misconceptions: ['You must be a math genius.', 'Only for people who code from age 12.'],
    what_people_love: ['The leverage — your work runs for thousands of users.', 'Remote-friendly, pays well in India.'],
    burnout_triggers: ['On-call rotations.', 'Constantly shifting priorities.', 'Legacy code with no tests.'],
    is_active: true,
  },

  {
    _id: 'mechanical-engineer',
    name: 'Mechanical Engineer',
    family: 'Engineering → Mechanical',
    one_liner: 'Designs, analyses, and manufactures physical systems — from engines to medical devices.',
    typical_titles: ['Design Engineer', 'Production Engineer', 'R&D Engineer'],
    riasec_primary: 'R', riasec_secondary: ['I'],
    cognitive_styles: ['spatial', 'numerical', 'logical'],
    indoor_outdoor: 40, desk_field: 55, solo_team: 55,
    communication_intensity: 3, public_facing: 2, travel: 'occasional',
    work_hours: 'standard', physical_demand: 3,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 15] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [3.5, 7], mid_salary_inr_lpa: [10, 22], top_salary_inr_lpa: [35, 80],
    scholarship_availability: 3, loan_worthiness: 3,
    india_market_depth: 4, metro_concentration: 2, international_mobility: 3,
    top_destinations: ['Germany', 'USA', 'Japan'],
    licensing_portability: 'moderate', remote_feasibility: 2, immigration_pathway: 3,
    automation_vulnerability: 3, demand_trajectory: 'flat', supply_saturation: 'oversaturated',
    emerging_score: 2, hidden_gem: false,
    ten_year_outlook: 'Core manufacturing mechanical roles are flat in India. EV, robotics, and aerospace niches are growing.',
    disruption_risks: ['Generative design tools', 'offshoring of design work'],
    adjacent_pivots: ['Robotics Engineer', 'EV Engineer', 'Product Manager'],
    required_stream: ['PCM'], entrance_exams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'State CETs'],
    degree_paths: ['B.Tech Mechanical', 'B.E. Mechanical'],
    min_qualification: 'B.Tech',
    job_stability: 4, work_life_balance: 3, social_prestige_india: 4, autonomy: 3,
    creative_expression: 3, impact: 3,
    day_in_life: 'Depending on the employer, days split between a CAD workstation and the shop floor. You review drawings, run simulations, walk the production line to see why tolerances are drifting, and sit in design reviews. Shift work shows up if you\'re in operations; standard hours if you\'re in design.',
    misconceptions: ['It\'s just IC engines.', 'Mechanical is a dying branch.'],
    what_people_love: ['Tangible output you can touch.', 'Applies across industries — cars, aerospace, biomedical.'],
    burnout_triggers: ['Stagnant salary growth in core industry.', 'Slow-moving corporate environments.'],
    is_active: true,
  },

  {
    _id: 'electrical-engineer',
    name: 'Electrical Engineer',
    family: 'Engineering → Electrical',
    one_liner: 'Works on power systems, electronics, or embedded hardware.',
    typical_titles: ['Power Systems Engineer', 'Embedded Engineer', 'Electronics Designer'],
    riasec_primary: 'R', riasec_secondary: ['I'],
    cognitive_styles: ['logical', 'spatial', 'numerical'],
    indoor_outdoor: 35, desk_field: 50, solo_team: 50,
    communication_intensity: 3, public_facing: 2, travel: 'occasional', work_hours: 'standard', physical_demand: 3,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 15] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [4, 8], mid_salary_inr_lpa: [10, 25], top_salary_inr_lpa: [35, 80],
    india_market_depth: 4, metro_concentration: 3, international_mobility: 3,
    top_destinations: ['Germany', 'USA', 'UAE'], licensing_portability: 'moderate',
    remote_feasibility: 2, immigration_pathway: 3,
    automation_vulnerability: 3, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    ten_year_outlook: 'Grid modernisation, EVs, and semiconductor push will create demand. Power sector roles are stable government-linked options.',
    adjacent_pivots: ['Renewable Energy Engineer', 'Hardware Startup Founder'],
    required_stream: ['PCM'], entrance_exams: ['JEE Main', 'JEE Advanced', 'State CETs'],
    degree_paths: ['B.Tech EE / ECE / EEE'], min_qualification: 'B.Tech',
    job_stability: 4, work_life_balance: 3, social_prestige_india: 4, autonomy: 3, creative_expression: 2, impact: 3,
    day_in_life: 'Split between circuit design, simulations, and lab testing — oscilloscopes, measurements, soldering. Embedded roles involve a lot of firmware debugging; power roles involve substation visits and SCADA systems.',
    misconceptions: ['You\'ll only work in factories.'],
    what_people_love: ['Tangible hardware outputs.', 'Strong government-sector options.'],
    burnout_triggers: ['PSU bureaucracy.', 'Bad shift rosters in plants.'],
    is_active: true,
  },

  {
    _id: 'civil-engineer',
    name: 'Civil Engineer',
    family: 'Engineering → Civil',
    one_liner: 'Designs and builds infrastructure — buildings, roads, bridges, water systems.',
    typical_titles: ['Site Engineer', 'Structural Engineer', 'Project Manager — Construction'],
    riasec_primary: 'R', riasec_secondary: ['E'],
    cognitive_styles: ['spatial', 'logical', 'kinesthetic'],
    indoor_outdoor: 70, desk_field: 70, solo_team: 60,
    communication_intensity: 4, public_facing: 3, travel: 'frequent', work_hours: 'long', physical_demand: 4,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [3, 12] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [8, 18], top_salary_inr_lpa: [30, 70],
    india_market_depth: 4, metro_concentration: 2, international_mobility: 3,
    top_destinations: ['Middle East', 'Australia', 'Canada'], licensing_portability: 'moderate',
    remote_feasibility: 1, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    ten_year_outlook: 'Smart-city and infrastructure push keeps demand steady. Climate-resilient construction is an emerging premium niche.',
    adjacent_pivots: ['Urban Planner', 'Construction Tech Entrepreneur'],
    required_stream: ['PCM'], entrance_exams: ['JEE Main', 'State CETs'],
    degree_paths: ['B.Tech Civil', 'B.Arch + Civil M.Tech'], min_qualification: 'B.Tech',
    job_stability: 4, work_life_balance: 2, social_prestige_india: 3, autonomy: 3, creative_expression: 3, impact: 4,
    day_in_life: 'If you\'re on site, days start early, end late, and happen in the dust. You inspect, measure, coordinate contractors, and solve dozens of small problems before lunch. Design roles are calmer and desk-based.',
    misconceptions: ['It\'s a low-paying field.'],
    what_people_love: ['Your work stays standing for decades.'],
    burnout_triggers: ['Site conditions.', 'Delayed projects.'],
    is_active: true,
  },

  {
    _id: 'chemical-engineer',
    name: 'Chemical Engineer',
    family: 'Engineering → Chemical',
    one_liner: 'Designs processes to convert raw materials into products — fuels, pharma, food, materials.',
    riasec_primary: 'I', riasec_secondary: ['R'],
    cognitive_styles: ['numerical', 'logical', 'spatial'],
    indoor_outdoor: 50, desk_field: 55, solo_team: 55,
    communication_intensity: 3, public_facing: 2, travel: 'occasional', work_hours: 'shift', physical_demand: 3,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 15] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [4, 9], mid_salary_inr_lpa: [10, 22], top_salary_inr_lpa: [30, 60],
    india_market_depth: 3, metro_concentration: 2, international_mobility: 3,
    top_destinations: ['USA', 'Middle East', 'Singapore'], licensing_portability: 'moderate',
    remote_feasibility: 2, immigration_pathway: 3,
    automation_vulnerability: 3, demand_trajectory: 'flat', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    ten_year_outlook: 'Traditional process chemical is flat; pharma, specialty chem, and green-hydrogen niches are hot.',
    adjacent_pivots: ['Process Safety', 'Sustainability Consultant', 'R&D Scientist'],
    required_stream: ['PCM'], entrance_exams: ['JEE Main', 'JEE Advanced'], degree_paths: ['B.Tech Chemical'],
    min_qualification: 'B.Tech',
    job_stability: 4, work_life_balance: 3, social_prestige_india: 4, autonomy: 3, creative_expression: 2, impact: 3,
    day_in_life: 'Plant roles involve shift rotations, DCS monitoring, and chasing down off-spec batches. R&D roles sit in pilot labs designing reactor tweaks. Safety is constant — near-misses are investigated hard.',
    is_active: true,
  },

  // ── Medical & health ───────────────────────────────────────────────────
  {
    _id: 'physician',
    name: 'Physician (MBBS → Specialist)',
    family: 'Healthcare → Clinical',
    one_liner: 'Diagnoses and treats illness. Long training, high responsibility, deep trust-based relationship with patients.',
    riasec_primary: 'I', riasec_secondary: ['S'],
    cognitive_styles: ['logical', 'interpersonal', 'intrapersonal'],
    hard_filters: { min_logical: 4, min_interpersonal: 3 },
    indoor_outdoor: 15, desk_field: 20, solo_team: 55,
    communication_intensity: 5, public_facing: 5, travel: 'none', work_hours: 'long', physical_demand: 3,
    education_cost: { govt_inr_lakh: [0.5, 5], private_inr_lakh: [25, 120], premium_inr_lakh: [50, 200] },
    education_duration_years: 9,
    entry_salary_inr_lpa: [6, 15], mid_salary_inr_lpa: [18, 45], top_salary_inr_lpa: [60, 300],
    roi_timeline_years: 10, scholarship_availability: 2, loan_worthiness: 5,
    india_market_depth: 5, metro_concentration: 3, international_mobility: 3,
    top_destinations: ['USA', 'UK', 'Australia'], licensing_portability: 'hard',
    remote_feasibility: 2, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'undersupplied',
    emerging_score: 2, hidden_gem: false,
    ten_year_outlook: 'India is under-doctored. Specialist demand will outpace supply for decades. Rural practice remains underserved.',
    disruption_risks: ['AI diagnostic assistance (augments rather than replaces).'],
    adjacent_pivots: ['Hospital Administration', 'Medical Researcher', 'Health-tech Founder'],
    required_stream: ['PCB', 'PCMB'], entrance_exams: ['NEET-UG', 'NEET-PG'],
    degree_paths: ['MBBS + MD/MS', 'MBBS + DNB'], min_qualification: 'MBBS',
    job_stability: 5, work_life_balance: 2, social_prestige_india: 5, autonomy: 4, creative_expression: 2, impact: 5,
    day_in_life: 'Residents run long shifts in wards — rounds, procedures, documentation, handovers. Private practice is calmer but builds slowly. The emotional load of breaking bad news and holding families together is real and rarely discussed in the brochure.',
    misconceptions: ['You earn a lot quickly.'],
    what_people_love: ['The depth of the trust patients place in you.', 'Unambiguous impact.'],
    burnout_triggers: ['Long residencies.', 'Financial pressure during training.', 'Litigation risk.'],
    is_active: true,
  },

  {
    _id: 'dentist',
    name: 'Dentist',
    family: 'Healthcare → Clinical',
    one_liner: 'Diagnoses and treats oral health — from cleanings to full-mouth reconstructions.',
    riasec_primary: 'R', riasec_secondary: ['I', 'S'],
    cognitive_styles: ['kinesthetic', 'spatial', 'interpersonal'],
    indoor_outdoor: 10, desk_field: 15, solo_team: 45,
    communication_intensity: 4, public_facing: 5, travel: 'none', work_hours: 'standard', physical_demand: 3,
    education_cost: { govt_inr_lakh: [1, 5], private_inr_lakh: [12, 60] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [8, 20], top_salary_inr_lpa: [30, 100],
    india_market_depth: 4, metro_concentration: 3, international_mobility: 3,
    top_destinations: ['USA', 'UK', 'Canada', 'Australia'], licensing_portability: 'hard',
    remote_feasibility: 1, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['PCB', 'PCMB'], entrance_exams: ['NEET-UG'],
    degree_paths: ['BDS', 'BDS + MDS'], min_qualification: 'BDS',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 4, autonomy: 4, creative_expression: 3, impact: 4,
    day_in_life: 'Chair-side most of the day, precise hand-work under a loupe, a steady stream of patients. Owning a clinic is common mid-career.',
    is_active: true,
  },

  {
    _id: 'clinical-psychologist',
    name: 'Clinical Psychologist',
    family: 'Healthcare → Mental Health',
    one_liner: 'Assesses and provides therapy for mental-health conditions — not medication, but evidence-based talking therapy.',
    riasec_primary: 'S', riasec_secondary: ['I'],
    cognitive_styles: ['interpersonal', 'intrapersonal', 'verbal'],
    hard_filters: { min_interpersonal: 4 },
    indoor_outdoor: 10, desk_field: 15, solo_team: 30,
    communication_intensity: 5, public_facing: 4, travel: 'none', work_hours: 'standard', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 15] },
    education_duration_years: 6,
    entry_salary_inr_lpa: [4, 8], mid_salary_inr_lpa: [10, 25], top_salary_inr_lpa: [30, 80],
    india_market_depth: 3, metro_concentration: 4, international_mobility: 3,
    top_destinations: ['UK', 'Australia', 'Canada'], licensing_portability: 'hard',
    remote_feasibility: 4, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 4, hidden_gem: true,
    ten_year_outlook: 'India has < 1 clinical psychologist per 100,000 people. Demand is surging as stigma drops. Undersupply will persist for a decade.',
    adjacent_pivots: ['Organisational Psychologist', 'UX Researcher', 'Mental Health Entrepreneur'],
    required_stream: ['Any'], entrance_exams: ['CUET', 'College entrance', 'RCI-recognised M.Phil'],
    degree_paths: ['BA/BSc Psychology → MA/MSc → M.Phil Clinical Psychology (RCI)'],
    min_qualification: 'M.Phil Clinical Psychology (RCI licence)',
    alternative_paths: ['Counselling Psychologist (shorter path, different scope)'],
    job_stability: 4, work_life_balance: 4, social_prestige_india: 3, autonomy: 5, creative_expression: 3, impact: 5,
    day_in_life: 'Mostly 45-minute sessions back-to-back, with notes in between. Online practice has exploded post-2020. You manage your own client load once licensed.',
    misconceptions: ['It\'s just "listening to people".', 'You\'ll absorb everyone\'s problems and break.'],
    what_people_love: ['Deep, one-on-one impact you can see over months.', 'Portable, flexible work.'],
    burnout_triggers: ['Vicarious trauma if you don\'t have your own supervision.'],
    is_active: true,
  },

  {
    _id: 'nurse',
    name: 'Nurse (B.Sc Nursing → Specialisation)',
    family: 'Healthcare → Nursing',
    one_liner: 'Hands-on patient care, inside hospitals or community settings.',
    riasec_primary: 'S', riasec_secondary: ['R'],
    cognitive_styles: ['interpersonal', 'kinesthetic', 'logical'],
    indoor_outdoor: 10, desk_field: 25, solo_team: 75,
    communication_intensity: 5, public_facing: 4, travel: 'none', work_hours: 'shift', physical_demand: 4,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [3, 10] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [2.5, 5], mid_salary_inr_lpa: [6, 12], top_salary_inr_lpa: [15, 35],
    india_market_depth: 5, metro_concentration: 3, international_mobility: 5,
    top_destinations: ['UK', 'Germany', 'USA', 'Middle East'], licensing_portability: 'moderate',
    remote_feasibility: 1, immigration_pathway: 5,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'undersupplied',
    emerging_score: 2, hidden_gem: true,
    ten_year_outlook: 'Global ageing crisis is creating massive nursing demand. International mobility for Indian nurses is among the best of any profession.',
    required_stream: ['PCB', 'PCMB'], entrance_exams: ['NEET-UG (for some colleges)', 'State nursing CETs'],
    degree_paths: ['B.Sc Nursing', 'GNM (diploma path)'], min_qualification: 'GNM or B.Sc Nursing',
    job_stability: 5, work_life_balance: 3, social_prestige_india: 3, autonomy: 3, creative_expression: 2, impact: 5,
    day_in_life: 'Shift-based. Rounds, medication administration, patient monitoring, documentation. Physical and emotional stamina required.',
    what_people_love: ['International work visas are the easiest in healthcare.', 'Deep patient relationships.'],
    burnout_triggers: ['Rotational shifts.', 'Understaffed wards.'],
    is_active: true,
  },

  {
    _id: 'pharmacist',
    name: 'Pharmacist (Clinical / Community / Industry)',
    family: 'Healthcare → Pharmacy',
    one_liner: 'Drug expertise — dispensing, safety checking, or pharmaceutical industry roles.',
    riasec_primary: 'I', riasec_secondary: ['C', 'S'],
    cognitive_styles: ['logical', 'numerical', 'verbal'],
    indoor_outdoor: 10, desk_field: 20, solo_team: 50,
    communication_intensity: 3, public_facing: 3, travel: 'none', work_hours: 'standard', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [3, 10] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [7, 15], top_salary_inr_lpa: [20, 50],
    india_market_depth: 4, metro_concentration: 3, international_mobility: 4,
    top_destinations: ['USA', 'Canada', 'Australia'], licensing_portability: 'hard',
    remote_feasibility: 2, immigration_pathway: 4,
    automation_vulnerability: 3, demand_trajectory: 'flat', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['PCB', 'PCMB', 'PCM'], entrance_exams: ['GPAT', 'State CETs'],
    degree_paths: ['B.Pharm', 'Pharm.D', 'D.Pharm'], min_qualification: 'B.Pharm',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 3, autonomy: 3, creative_expression: 1, impact: 3,
    day_in_life: 'Retail: dispensing and counselling. Industry: QA, formulation, regulatory affairs — desk + lab. Clinical: ward rounds with doctors.',
    is_active: true,
  },

  // ── Data, AI, cyber ────────────────────────────────────────────────────
  {
    _id: 'data-scientist',
    name: 'Data Scientist / Analyst',
    family: 'Technology → Data',
    one_liner: 'Turns messy data into decisions — analysis, modelling, storytelling with numbers.',
    riasec_primary: 'I', riasec_secondary: ['C'],
    cognitive_styles: ['numerical', 'logical', 'verbal'],
    hard_filters: { min_numerical: 4 },
    indoor_outdoor: 10, desk_field: 15, solo_team: 55,
    communication_intensity: 4, public_facing: 2, travel: 'occasional', work_hours: 'flexible', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 20] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [8, 14], mid_salary_inr_lpa: [20, 45], top_salary_inr_lpa: [60, 150],
    india_market_depth: 5, metro_concentration: 4, international_mobility: 5,
    top_destinations: ['USA', 'UK', 'Singapore'], licensing_portability: 'easy',
    remote_feasibility: 5, immigration_pathway: 4,
    automation_vulnerability: 3, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    ten_year_outlook: 'Pure analyst roles will shrink; roles that combine business judgement + technical depth will grow.',
    adjacent_pivots: ['ML Engineer', 'Product Manager', 'Analytics Founder'],
    required_stream: ['PCM', 'Commerce', 'Any'],
    entrance_exams: ['JEE Main', 'CUET', 'College entrance'],
    degree_paths: ['B.Tech + MS Data Science', 'B.Sc Stats/Math + MS', 'Self-taught with portfolio'],
    min_qualification: 'Bachelor\'s',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 4, autonomy: 4, creative_expression: 3, impact: 4,
    is_active: true,
  },

  {
    _id: 'ml-engineer',
    name: 'AI / ML Engineer',
    family: 'Technology → AI',
    one_liner: 'Builds and deploys machine-learning systems in production — model training, serving, evaluation.',
    riasec_primary: 'I', riasec_secondary: ['R'],
    cognitive_styles: ['logical', 'numerical', 'spatial'],
    hard_filters: { min_numerical: 4, min_logical: 4 },
    indoor_outdoor: 10, desk_field: 15, solo_team: 55,
    communication_intensity: 3, public_facing: 2, travel: 'occasional', work_hours: 'flexible', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 25] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [12, 25], mid_salary_inr_lpa: [30, 70], top_salary_inr_lpa: [100, 400],
    india_market_depth: 4, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['USA', 'UK', 'Singapore'], licensing_portability: 'easy',
    remote_feasibility: 5, immigration_pathway: 5,
    automation_vulnerability: 2, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 5, hidden_gem: false,
    ten_year_outlook: 'The hottest technical career of the decade. Top-tier comp in India and abroad.',
    required_stream: ['PCM'], entrance_exams: ['JEE Main', 'JEE Advanced', 'GATE'],
    degree_paths: ['B.Tech CS/AI', 'B.Tech + MS AI/ML'], min_qualification: 'B.Tech',
    job_stability: 4, work_life_balance: 3, social_prestige_india: 5, autonomy: 4, creative_expression: 3, impact: 4,
    day_in_life: 'Days oscillate between running experiments, debugging training runs, reading papers, and productionising models. GPU time is the bottleneck.',
    is_active: true,
  },

  {
    _id: 'cybersecurity-analyst',
    name: 'Cybersecurity Analyst / Engineer',
    family: 'Technology → Security',
    one_liner: 'Defends systems and data from attackers. Incident response, threat hunting, security engineering.',
    riasec_primary: 'I', riasec_secondary: ['R', 'C'],
    cognitive_styles: ['logical', 'numerical', 'intrapersonal'],
    indoor_outdoor: 10, desk_field: 15, solo_team: 45,
    communication_intensity: 3, public_facing: 2, travel: 'occasional', work_hours: 'shift', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 15] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [6, 12], mid_salary_inr_lpa: [20, 40], top_salary_inr_lpa: [60, 150],
    india_market_depth: 3, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['USA', 'UK', 'Singapore', 'UAE'], licensing_portability: 'easy',
    remote_feasibility: 5, immigration_pathway: 5,
    automation_vulnerability: 2, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 4, hidden_gem: true,
    ten_year_outlook: 'Near-zero supply, infinite demand. India produces a fraction of the cyber talent it needs. CERT-In regulations are growing the market further.',
    adjacent_pivots: ['Security Researcher', 'Red-team Consultant', 'Security Founder'],
    required_stream: ['PCM', 'Any'], entrance_exams: ['JEE Main', 'CUET', 'Certifications (CEH, OSCP)'],
    degree_paths: ['B.Tech CS/Cybersecurity', 'BCA + MCA + certs', 'Self-taught + certs'],
    min_qualification: 'Bachelor\'s or strong certifications',
    job_stability: 5, work_life_balance: 3, social_prestige_india: 4, autonomy: 4, creative_expression: 3, impact: 4,
    day_in_life: 'SOC analysts watch alerts and run playbooks. Pen-testers break systems on purpose. Security engineers harden infra. On-call is real — breaches don\'t wait.',
    what_people_love: ['Mission-driven work.', 'Ethical hacking is genuinely fun.'],
    burnout_triggers: ['24x7 SOC rotations.', 'Alert fatigue.'],
    is_active: true,
  },

  // ── Design & creative ──────────────────────────────────────────────────
  {
    _id: 'ux-designer',
    name: 'UX / Product Designer',
    family: 'Design → Digital Product',
    one_liner: 'Designs how digital products feel and behave — research, flows, interfaces, prototypes.',
    riasec_primary: 'A', riasec_secondary: ['I', 'S'],
    cognitive_styles: ['spatial', 'verbal', 'interpersonal'],
    indoor_outdoor: 10, desk_field: 15, solo_team: 60,
    communication_intensity: 4, public_facing: 3, travel: 'occasional', work_hours: 'flexible', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [6, 20] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [5, 10], mid_salary_inr_lpa: [14, 30], top_salary_inr_lpa: [40, 100],
    india_market_depth: 4, metro_concentration: 5, international_mobility: 4,
    top_destinations: ['USA', 'UK', 'Singapore'], licensing_portability: 'easy',
    remote_feasibility: 5, immigration_pathway: 4,
    automation_vulnerability: 3, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    required_stream: ['Any'], entrance_exams: ['UCEED', 'NID DAT', 'CEED', 'College entrance'],
    degree_paths: ['B.Des', 'B.Arch + pivot', 'Self-taught + portfolio'], min_qualification: 'Strong portfolio',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 4, autonomy: 4, creative_expression: 5, impact: 4,
    is_active: true,
  },

  {
    _id: 'graphic-designer',
    name: 'Graphic / Visual Designer',
    family: 'Design → Visual',
    one_liner: 'Creates brand identity, marketing visuals, illustrations, motion graphics.',
    riasec_primary: 'A', riasec_secondary: ['E'],
    cognitive_styles: ['spatial', 'verbal', 'kinesthetic'],
    indoor_outdoor: 10, desk_field: 15, solo_team: 50,
    communication_intensity: 3, public_facing: 3, travel: 'occasional', work_hours: 'flexible', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [4, 15] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [8, 18], top_salary_inr_lpa: [25, 60],
    india_market_depth: 4, metro_concentration: 5, international_mobility: 4,
    top_destinations: ['USA', 'UK', 'UAE'], licensing_portability: 'easy', remote_feasibility: 5, immigration_pathway: 3,
    automation_vulnerability: 4, demand_trajectory: 'flat', supply_saturation: 'oversaturated',
    emerging_score: 3, hidden_gem: false,
    ten_year_outlook: 'Generative AI is compressing the bottom of this market. Top-end brand and motion work remains strong; commodity design is disappearing.',
    required_stream: ['Any'], entrance_exams: ['NID', 'NIFT', 'UCEED', 'College entrance'],
    degree_paths: ['B.Des', 'BFA', 'Self-taught + portfolio'], min_qualification: 'Strong portfolio',
    job_stability: 3, work_life_balance: 4, social_prestige_india: 3, autonomy: 5, creative_expression: 5, impact: 3,
    is_active: true,
  },

  {
    _id: 'architect',
    name: 'Architect',
    family: 'Design → Built Environment',
    one_liner: 'Designs buildings and spaces — blends creativity, engineering, and client management.',
    riasec_primary: 'A', riasec_secondary: ['R', 'I'],
    cognitive_styles: ['spatial', 'verbal', 'kinesthetic'],
    indoor_outdoor: 40, desk_field: 50, solo_team: 55,
    communication_intensity: 4, public_facing: 4, travel: 'frequent', work_hours: 'long', physical_demand: 2,
    education_cost: { govt_inr_lakh: [1, 5], private_inr_lakh: [8, 25] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [3.5, 7], mid_salary_inr_lpa: [10, 25], top_salary_inr_lpa: [30, 100],
    india_market_depth: 3, metro_concentration: 4, international_mobility: 3,
    top_destinations: ['Middle East', 'UK', 'Singapore'], licensing_portability: 'hard',
    remote_feasibility: 3, immigration_pathway: 3,
    automation_vulnerability: 3, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['PCM'], entrance_exams: ['NATA', 'JEE Main Paper 2'],
    degree_paths: ['B.Arch', 'B.Arch + M.Arch'], min_qualification: 'B.Arch + COA registration',
    job_stability: 3, work_life_balance: 2, social_prestige_india: 4, autonomy: 4, creative_expression: 5, impact: 4,
    day_in_life: 'Studio work is intense, iterative, opinion-driven. Site visits break up the week. The long education and low early salaries put some people off; those who stick through the first decade do well.',
    is_active: true,
  },

  // ── Business, finance, law ─────────────────────────────────────────────
  {
    _id: 'product-manager',
    name: 'Product Manager',
    family: 'Business → Product',
    one_liner: 'Owns what gets built and why. Bridges users, engineering, design, and business.',
    riasec_primary: 'E', riasec_secondary: ['I', 'S'],
    cognitive_styles: ['verbal', 'logical', 'interpersonal'],
    indoor_outdoor: 10, desk_field: 15, solo_team: 80,
    communication_intensity: 5, public_facing: 3, travel: 'occasional', work_hours: 'long', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 5], private_inr_lakh: [10, 30], premium_inr_lakh: [30, 80] },
    education_duration_years: 6,
    entry_salary_inr_lpa: [15, 25], mid_salary_inr_lpa: [30, 60], top_salary_inr_lpa: [80, 250],
    india_market_depth: 4, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['USA', 'UK', 'Singapore'], licensing_portability: 'easy',
    remote_feasibility: 4, immigration_pathway: 4,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    required_stream: ['Any'], entrance_exams: ['CAT', 'GMAT (for MBA)'],
    degree_paths: ['B.Tech + MBA', 'Any bachelor\'s + APM/associate route'], min_qualification: 'Bachelor\'s + experience',
    job_stability: 4, work_life_balance: 3, social_prestige_india: 5, autonomy: 4, creative_expression: 3, impact: 4,
    is_active: true,
  },

  {
    _id: 'chartered-accountant',
    name: 'Chartered Accountant',
    family: 'Business → Finance',
    one_liner: 'Audits, taxation, advisory, or corporate finance roles. India\'s most respected finance credential.',
    riasec_primary: 'C', riasec_secondary: ['E', 'I'],
    cognitive_styles: ['numerical', 'logical', 'verbal'],
    hard_filters: { min_numerical: 3 },
    indoor_outdoor: 10, desk_field: 20, solo_team: 50,
    communication_intensity: 3, public_facing: 3, travel: 'occasional', work_hours: 'long', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [1, 3] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [7, 15], mid_salary_inr_lpa: [18, 40], top_salary_inr_lpa: [50, 200],
    india_market_depth: 5, metro_concentration: 3, international_mobility: 3,
    top_destinations: ['UAE', 'Singapore', 'UK'], licensing_portability: 'moderate',
    remote_feasibility: 3, immigration_pathway: 3,
    automation_vulnerability: 4, demand_trajectory: 'flat', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    ten_year_outlook: 'Automation is compressing basic audit and tax-filing work. Advisory and forensic niches are strong.',
    required_stream: ['Commerce', 'Any'], entrance_exams: ['CA Foundation, Intermediate, Final'],
    degree_paths: ['CA (ICAI)', 'B.Com + CA'], min_qualification: 'CA',
    job_stability: 5, work_life_balance: 3, social_prestige_india: 5, autonomy: 3, creative_expression: 1, impact: 3,
    is_active: true,
  },

  {
    _id: 'investment-banker',
    name: 'Investment Banker / Corporate Finance',
    family: 'Business → Finance',
    one_liner: 'Advises companies on deals — M&A, capital raising, IPOs. Known for high pay and brutal hours.',
    riasec_primary: 'E', riasec_secondary: ['C'],
    cognitive_styles: ['numerical', 'verbal', 'interpersonal'],
    hard_filters: { min_numerical: 4 },
    indoor_outdoor: 10, desk_field: 15, solo_team: 70,
    communication_intensity: 4, public_facing: 4, travel: 'frequent', work_hours: 'long', physical_demand: 1,
    education_cost: { govt_inr_lakh: [5, 25], private_inr_lakh: [25, 80], premium_inr_lakh: [30, 80] },
    education_duration_years: 6,
    entry_salary_inr_lpa: [20, 35], mid_salary_inr_lpa: [60, 150], top_salary_inr_lpa: [200, 1000],
    india_market_depth: 3, metro_concentration: 5, international_mobility: 4,
    top_destinations: ['USA', 'UK', 'Singapore', 'Hong Kong'], licensing_portability: 'moderate',
    remote_feasibility: 2, immigration_pathway: 4,
    automation_vulnerability: 2, demand_trajectory: 'flat', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['Commerce', 'PCM', 'Any'], entrance_exams: ['CAT', 'GMAT', 'CFA'],
    degree_paths: ['B.Com/B.Tech + MBA (IIM/ISB)', 'CA + MBA', 'CFA'], min_qualification: 'MBA or CFA',
    job_stability: 3, work_life_balance: 1, social_prestige_india: 5, autonomy: 2, creative_expression: 1, impact: 3,
    is_active: true,
  },

  {
    _id: 'management-consultant',
    name: 'Management Consultant',
    family: 'Business → Consulting',
    one_liner: 'Solves big strategic problems for clients. Intense, fast-paced, structured thinking.',
    riasec_primary: 'E', riasec_secondary: ['I', 'S'],
    cognitive_styles: ['logical', 'verbal', 'interpersonal'],
    indoor_outdoor: 10, desk_field: 20, solo_team: 75,
    communication_intensity: 5, public_facing: 4, travel: 'frequent', work_hours: 'long', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 25], private_inr_lakh: [15, 60], premium_inr_lakh: [30, 80] },
    education_duration_years: 6,
    entry_salary_inr_lpa: [15, 30], mid_salary_inr_lpa: [40, 80], top_salary_inr_lpa: [100, 400],
    india_market_depth: 3, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['USA', 'UK', 'Singapore', 'Middle East'], licensing_portability: 'easy',
    remote_feasibility: 2, immigration_pathway: 4,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 3, hidden_gem: false,
    required_stream: ['Any'], entrance_exams: ['CAT', 'GMAT'],
    degree_paths: ['Any bachelor\'s + MBA (top-20)'], min_qualification: 'MBA or strong UG from IIT/IIM/BITS',
    job_stability: 3, work_life_balance: 2, social_prestige_india: 5, autonomy: 3, creative_expression: 3, impact: 3,
    is_active: true,
  },

  {
    _id: 'lawyer',
    name: 'Lawyer / Advocate',
    family: 'Law & Policy → Practice',
    one_liner: 'Litigation, corporate law, policy — deeply verbal, argument-driven, long apprenticeship.',
    riasec_primary: 'E', riasec_secondary: ['S'],
    cognitive_styles: ['verbal', 'logical', 'interpersonal'],
    hard_filters: { min_verbal: 4 },
    indoor_outdoor: 15, desk_field: 30, solo_team: 55,
    communication_intensity: 5, public_facing: 5, travel: 'occasional', work_hours: 'long', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [8, 40], premium_inr_lakh: [15, 50] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [3, 15], mid_salary_inr_lpa: [10, 50], top_salary_inr_lpa: [40, 500],
    india_market_depth: 5, metro_concentration: 3, international_mobility: 2,
    top_destinations: ['Singapore', 'UK'], licensing_portability: 'hard',
    remote_feasibility: 3, immigration_pathway: 2,
    automation_vulnerability: 3, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['Any'], entrance_exams: ['CLAT', 'AILET'],
    degree_paths: ['5-year integrated LLB', 'BA/BCom + 3-year LLB'], min_qualification: 'LLB + Bar Council enrolment',
    job_stability: 4, work_life_balance: 2, social_prestige_india: 5, autonomy: 4, creative_expression: 2, impact: 4,
    is_active: true,
  },

  {
    _id: 'civil-services',
    name: 'Civil Services (IAS/IPS/IFS)',
    family: 'Public Service → Administration',
    one_liner: 'India\'s bureaucracy. Generalist leadership across governance, police, diplomacy.',
    riasec_primary: 'E', riasec_secondary: ['S', 'C'],
    cognitive_styles: ['verbal', 'logical', 'interpersonal'],
    indoor_outdoor: 30, desk_field: 50, solo_team: 60,
    communication_intensity: 5, public_facing: 5, travel: 'frequent', work_hours: 'long', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0.5, 3] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [10, 14], mid_salary_inr_lpa: [18, 30], top_salary_inr_lpa: [30, 50],
    india_market_depth: 5, metro_concentration: 2, international_mobility: 1,
    remote_feasibility: 1, immigration_pathway: 1,
    automation_vulnerability: 1, demand_trajectory: 'flat', supply_saturation: 'balanced',
    emerging_score: 1, hidden_gem: false,
    required_stream: ['Any'], entrance_exams: ['UPSC CSE'],
    degree_paths: ['Any bachelor\'s + UPSC prep'], min_qualification: 'Bachelor\'s',
    job_stability: 5, work_life_balance: 2, social_prestige_india: 5, autonomy: 3, creative_expression: 2, impact: 5,
    day_in_life: 'Hugely variable by posting. District collectors juggle a dozen departments; secretariat postings are desk-heavy and political. Transfers every few years are a feature, not a bug.',
    is_active: true,
  },

  {
    _id: 'teacher',
    name: 'Teacher / Educator (School → College)',
    family: 'Education → Teaching',
    one_liner: 'Teaches, mentors, shapes. Ranges from school teaching to university professorship.',
    riasec_primary: 'S', riasec_secondary: ['A', 'I'],
    cognitive_styles: ['verbal', 'interpersonal', 'intrapersonal'],
    indoor_outdoor: 15, desk_field: 25, solo_team: 75,
    communication_intensity: 5, public_facing: 5, travel: 'none', work_hours: 'standard', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [2, 8] },
    education_duration_years: 4,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [7, 15], top_salary_inr_lpa: [20, 60],
    india_market_depth: 5, metro_concentration: 2, international_mobility: 3,
    top_destinations: ['UAE', 'UK', 'Singapore'], licensing_portability: 'moderate',
    remote_feasibility: 3, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['Any'], entrance_exams: ['CTET', 'NET-SET (for college)', 'College entrance'],
    degree_paths: ['B.Ed', 'MA/MSc + NET', 'Integrated B.A.B.Ed'], min_qualification: 'B.Ed (school) / NET + PhD (college)',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 3, autonomy: 3, creative_expression: 4, impact: 5,
    is_active: true,
  },

  // ── Media & content ────────────────────────────────────────────────────
  {
    _id: 'content-creator',
    name: 'Content Creator / Creator Economy',
    family: 'Media → Independent',
    one_liner: 'Builds an audience around expertise or personality — YouTube, newsletters, podcasts, Instagram, niche tech.',
    riasec_primary: 'A', riasec_secondary: ['E'],
    cognitive_styles: ['verbal', 'interpersonal', 'intrapersonal'],
    indoor_outdoor: 20, desk_field: 30, solo_team: 35,
    communication_intensity: 5, public_facing: 5, travel: 'occasional', work_hours: 'flexible', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0, 2], private_inr_lakh: [0, 5] },
    education_duration_years: 3,
    entry_salary_inr_lpa: [0, 4], mid_salary_inr_lpa: [6, 40], top_salary_inr_lpa: [50, 500],
    india_market_depth: 5, metro_concentration: 2, international_mobility: 5,
    top_destinations: ['USA', 'UK', 'anywhere online'], licensing_portability: 'easy',
    remote_feasibility: 5, immigration_pathway: 3,
    automation_vulnerability: 3, demand_trajectory: 'exploding', supply_saturation: 'balanced',
    emerging_score: 5, hidden_gem: true,
    ten_year_outlook: 'Creator economy continues to eat traditional media. Niche-expert creators (finance, tech, health, education) are the most defensible.',
    disruption_risks: ['Platform algorithm changes.', 'AI-generated content glut.'],
    adjacent_pivots: ['Course/edtech entrepreneur', 'Media company founder', 'Consultant'],
    required_stream: ['Any'], entrance_exams: [],
    degree_paths: ['Any bachelor\'s — portfolio matters more'], min_qualification: 'Audience + portfolio',
    alternative_paths: ['Drop out + full-time creation (high risk)'],
    job_stability: 2, work_life_balance: 3, social_prestige_india: 3, autonomy: 5, creative_expression: 5, impact: 4,
    day_in_life: 'Ideation, filming, editing, publishing, engaging with audience. Revenue comes from sponsorships, memberships, courses. First 2–3 years are usually unpaid; the 1% who break through do very well.',
    misconceptions: ['It\'s easy money.', 'You need to be famous to start.'],
    what_people_love: ['Total ownership of your work and time.', 'Direct relationship with an audience.'],
    burnout_triggers: ['Algorithm pressure.', 'Audience parasocial demands.', 'Income volatility.'],
    is_active: true,
  },

  {
    _id: 'journalist',
    name: 'Journalist / Editor',
    family: 'Media → Journalism',
    one_liner: 'Reports, analyses, edits. From hard news to long-form investigation to niche newsletters.',
    riasec_primary: 'A', riasec_secondary: ['I', 'S'],
    cognitive_styles: ['verbal', 'interpersonal', 'intrapersonal'],
    hard_filters: { min_verbal: 4 },
    indoor_outdoor: 30, desk_field: 50, solo_team: 50,
    communication_intensity: 5, public_facing: 4, travel: 'frequent', work_hours: 'long', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [3, 12] },
    education_duration_years: 3,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [8, 20], top_salary_inr_lpa: [25, 80],
    india_market_depth: 3, metro_concentration: 5, international_mobility: 3,
    top_destinations: ['USA', 'UK', 'Singapore'], licensing_portability: 'easy',
    remote_feasibility: 4, immigration_pathway: 3,
    automation_vulnerability: 4, demand_trajectory: 'declining', supply_saturation: 'oversaturated',
    emerging_score: 2, hidden_gem: false,
    ten_year_outlook: 'Traditional journalism is shrinking; independent / newsletter journalism is growing.',
    required_stream: ['Any'], entrance_exams: ['Mass comm CETs', 'CUET'],
    degree_paths: ['BA Journalism', 'Any bachelor\'s + MA', 'Self-taught + portfolio'],
    min_qualification: 'Bachelor\'s + portfolio',
    job_stability: 3, work_life_balance: 2, social_prestige_india: 3, autonomy: 4, creative_expression: 5, impact: 4,
    is_active: true,
  },

  // ── Emerging / hidden gems ─────────────────────────────────────────────
  {
    _id: 'climate-risk-analyst',
    name: 'Climate Risk / Carbon Analyst',
    family: 'Sustainability → Analytics',
    one_liner: 'Assesses climate risk for companies and funds — carbon accounting, ESG analysis, transition planning.',
    riasec_primary: 'I', riasec_secondary: ['C', 'E'],
    cognitive_styles: ['numerical', 'logical', 'verbal'],
    indoor_outdoor: 20, desk_field: 30, solo_team: 55,
    communication_intensity: 4, public_facing: 3, travel: 'occasional', work_hours: 'standard', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [5, 20] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [8, 15], mid_salary_inr_lpa: [20, 45], top_salary_inr_lpa: [50, 150],
    india_market_depth: 3, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['UK', 'Singapore', 'Netherlands', 'USA'], licensing_portability: 'easy',
    remote_feasibility: 4, immigration_pathway: 4,
    automation_vulnerability: 2, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 5, hidden_gem: true,
    ten_year_outlook: 'SEBI BRSR disclosures + global net-zero pressure + EU CBAM = decade of growth. Currently almost no Indian supply.',
    adjacent_pivots: ['Sustainability Consultant', 'Climate-tech PM', 'ESG Founder'],
    required_stream: ['PCM', 'Commerce', 'Any'], entrance_exams: ['CAT', 'GMAT', 'Certifications (GARP SCR, CFA ESG)'],
    degree_paths: ['B.Tech Environmental + MBA/MSc', 'B.Com + MSc Sustainability', 'Economics + ESG certs'],
    min_qualification: 'Bachelor\'s + certification',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 4, autonomy: 4, creative_expression: 2, impact: 5,
    day_in_life: 'Modelling climate scenarios, writing disclosure reports, interviewing operations teams, building transition roadmaps. Heavily cross-functional.',
    what_people_love: ['Your work actually shifts corporate behaviour.', 'Scarce skill, fast compensation growth.'],
    is_active: true,
  },

  {
    _id: 'genomics-biotech-researcher',
    name: 'Genomics / Biotech Researcher',
    family: 'Healthcare → Research',
    one_liner: 'Works at the intersection of biology, computation, and clinical research — from CRISPR to precision medicine.',
    riasec_primary: 'I', riasec_secondary: ['R'],
    cognitive_styles: ['logical', 'numerical', 'spatial'],
    hard_filters: { min_logical: 4, min_numerical: 3 },
    indoor_outdoor: 10, desk_field: 15, solo_team: 60,
    communication_intensity: 3, public_facing: 2, travel: 'occasional', work_hours: 'long', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [5, 20] },
    education_duration_years: 8,
    entry_salary_inr_lpa: [5, 10], mid_salary_inr_lpa: [15, 35], top_salary_inr_lpa: [40, 150],
    india_market_depth: 2, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['USA', 'Germany', 'UK', 'Singapore'], licensing_portability: 'easy',
    remote_feasibility: 2, immigration_pathway: 5,
    automation_vulnerability: 2, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 5, hidden_gem: true,
    ten_year_outlook: 'Post-COVID biotech infrastructure, genomics cost collapse, and ML-for-biology are reshaping the field. India is scaling up fast.',
    adjacent_pivots: ['Biotech Founder', 'Healthcare VC', 'Computational Biologist'],
    required_stream: ['PCB', 'PCMB'], entrance_exams: ['IIT JAM', 'GATE Biotech', 'CSIR-NET'],
    degree_paths: ['B.Sc + M.Sc + PhD', 'B.Tech Biotech + MS/PhD'], min_qualification: 'MSc + research experience',
    job_stability: 3, work_life_balance: 3, social_prestige_india: 4, autonomy: 4, creative_expression: 3, impact: 5,
    is_active: true,
  },

  {
    _id: 'urban-planner',
    name: 'Urban Planner / Smart City Consultant',
    family: 'Public Service → Urban Systems',
    one_liner: 'Designs how cities work — transport, housing, land use, resilience. Sits between architecture, policy, and tech.',
    riasec_primary: 'I', riasec_secondary: ['S', 'E'],
    cognitive_styles: ['spatial', 'verbal', 'interpersonal'],
    indoor_outdoor: 30, desk_field: 50, solo_team: 65,
    communication_intensity: 4, public_facing: 4, travel: 'frequent', work_hours: 'standard', physical_demand: 2,
    education_cost: { govt_inr_lakh: [1, 4], private_inr_lakh: [6, 20] },
    education_duration_years: 6,
    entry_salary_inr_lpa: [5, 10], mid_salary_inr_lpa: [12, 25], top_salary_inr_lpa: [30, 70],
    india_market_depth: 3, metro_concentration: 4, international_mobility: 3,
    top_destinations: ['Singapore', 'UK', 'Netherlands'], licensing_portability: 'moderate',
    remote_feasibility: 2, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'undersupplied',
    emerging_score: 4, hidden_gem: true,
    ten_year_outlook: 'Smart-city push + urbanisation + climate retrofits = sustained demand. India has very few trained planners.',
    required_stream: ['PCM', 'Arts', 'Any'], entrance_exams: ['CEED', 'College entrance'],
    degree_paths: ['B.Arch + M.Plan', 'B.Tech Civil + M.Plan', 'B.A. Geography + M.Plan'],
    min_qualification: 'Master\'s in Urban Planning',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 3, autonomy: 3, creative_expression: 3, impact: 5,
    is_active: true,
  },

  {
    _id: 'ai-trainer',
    name: 'AI Trainer / Applied AI Specialist',
    family: 'Technology → AI Applied',
    one_liner: 'Non-coding AI work — evaluating outputs, crafting training data, red-teaming, prompt engineering, AI product design.',
    riasec_primary: 'A', riasec_secondary: ['I'],
    cognitive_styles: ['verbal', 'logical', 'intrapersonal'],
    indoor_outdoor: 10, desk_field: 15, solo_team: 50,
    communication_intensity: 3, public_facing: 2, travel: 'none', work_hours: 'flexible', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [2, 15] },
    education_duration_years: 3,
    entry_salary_inr_lpa: [6, 15], mid_salary_inr_lpa: [18, 40], top_salary_inr_lpa: [50, 120],
    india_market_depth: 3, metro_concentration: 4, international_mobility: 4,
    top_destinations: ['USA', 'UK', 'remote-anywhere'], licensing_portability: 'easy',
    remote_feasibility: 5, immigration_pathway: 3,
    automation_vulnerability: 3, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 5, hidden_gem: true,
    ten_year_outlook: 'Every enterprise deploying LLMs needs humans in the loop. Domain-expert trainers (medicine, law, finance) are especially scarce.',
    adjacent_pivots: ['AI PM', 'AI Safety Researcher', 'AI Consultant'],
    required_stream: ['Any'], entrance_exams: [],
    degree_paths: ['Any bachelor\'s + portfolio of AI work'], min_qualification: 'Bachelor\'s + strong portfolio',
    job_stability: 3, work_life_balance: 4, social_prestige_india: 3, autonomy: 4, creative_expression: 4, impact: 4,
    day_in_life: 'Mornings reviewing model outputs and tagging failure modes. Afternoons designing evaluation rubrics or red-teaming new releases. Heavily remote and contract-friendly.',
    is_active: true,
  },

  {
    _id: 'counsellor',
    name: 'Counsellor / Mental Health Practitioner',
    family: 'Healthcare → Mental Health',
    one_liner: 'Non-clinical mental-health support — school counselling, career counselling, employee wellbeing.',
    riasec_primary: 'S', riasec_secondary: ['A'],
    cognitive_styles: ['interpersonal', 'intrapersonal', 'verbal'],
    hard_filters: { min_interpersonal: 4 },
    indoor_outdoor: 10, desk_field: 20, solo_team: 40,
    communication_intensity: 5, public_facing: 4, travel: 'occasional', work_hours: 'standard', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 2], private_inr_lakh: [2, 10] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [7, 15], top_salary_inr_lpa: [20, 50],
    india_market_depth: 4, metro_concentration: 3, international_mobility: 3,
    top_destinations: ['UK', 'Canada', 'Australia'], licensing_portability: 'moderate',
    remote_feasibility: 4, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'exploding', supply_saturation: 'undersupplied',
    emerging_score: 4, hidden_gem: true,
    ten_year_outlook: 'Schools, colleges, and corporates are all adding counsellors. Much faster to become than a clinical psychologist.',
    required_stream: ['Any'], entrance_exams: ['College entrance'],
    degree_paths: ['MA Psychology / Counselling', 'PG Diploma in Counselling'], min_qualification: 'MA + supervised hours',
    job_stability: 4, work_life_balance: 4, social_prestige_india: 3, autonomy: 4, creative_expression: 3, impact: 5,
    is_active: true,
  },

  // Filling out to 30
  {
    _id: 'research-scientist',
    name: 'Research Scientist (Physics / Chemistry / Math)',
    family: 'Science → Academic Research',
    one_liner: 'Pursues fundamental questions. Long training, modest pay early, deep autonomy once established.',
    riasec_primary: 'I', riasec_secondary: ['A'],
    cognitive_styles: ['logical', 'numerical', 'intrapersonal'],
    hard_filters: { min_logical: 4, min_numerical: 4 },
    indoor_outdoor: 15, desk_field: 20, solo_team: 50,
    communication_intensity: 3, public_facing: 2, travel: 'occasional', work_hours: 'long', physical_demand: 1,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [2, 10] },
    education_duration_years: 10,
    entry_salary_inr_lpa: [5, 10], mid_salary_inr_lpa: [12, 25], top_salary_inr_lpa: [25, 60],
    india_market_depth: 2, metro_concentration: 3, international_mobility: 5,
    top_destinations: ['USA', 'Germany', 'UK', 'Switzerland'], licensing_portability: 'easy',
    remote_feasibility: 2, immigration_pathway: 5,
    automation_vulnerability: 2, demand_trajectory: 'flat', supply_saturation: 'oversaturated',
    emerging_score: 2, hidden_gem: false,
    required_stream: ['PCM', 'PCB'], entrance_exams: ['IIT JAM', 'JEST', 'GATE', 'CSIR-NET'],
    degree_paths: ['B.Sc + M.Sc + PhD', 'Integrated MS + PhD'], min_qualification: 'PhD',
    job_stability: 3, work_life_balance: 3, social_prestige_india: 4, autonomy: 5, creative_expression: 4, impact: 4,
    is_active: true,
  },

  {
    _id: 'entrepreneur-founder',
    name: 'Entrepreneur / Startup Founder',
    family: 'Business → Entrepreneurship',
    one_liner: 'Builds a company from zero. Brutal on money and stability early; potentially life-changing outcomes.',
    riasec_primary: 'E', riasec_secondary: ['I'],
    cognitive_styles: ['verbal', 'logical', 'interpersonal'],
    indoor_outdoor: 20, desk_field: 40, solo_team: 75,
    communication_intensity: 5, public_facing: 5, travel: 'frequent', work_hours: 'long', physical_demand: 2,
    education_cost: { govt_inr_lakh: [0, 5], private_inr_lakh: [0, 25] },
    education_duration_years: 3,
    entry_salary_inr_lpa: [0, 5], mid_salary_inr_lpa: [10, 50], top_salary_inr_lpa: [50, 10000],
    india_market_depth: 5, metro_concentration: 5, international_mobility: 5,
    top_destinations: ['USA', 'Singapore', 'UAE'], licensing_portability: 'easy',
    remote_feasibility: 4, immigration_pathway: 4,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'balanced',
    emerging_score: 4, hidden_gem: false,
    ten_year_outlook: 'India\'s startup decade continues. Capital has tightened but the opportunity is real for those who ship.',
    required_stream: ['Any'], entrance_exams: [],
    degree_paths: ['Any — execution matters more than credentials'], min_qualification: 'None enforced',
    alternative_paths: ['Drop out + build', 'Join a YC/top accelerator'],
    job_stability: 1, work_life_balance: 1, social_prestige_india: 4, autonomy: 5, creative_expression: 5, impact: 5,
    day_in_life: 'Every day is different: fundraising, hiring, firing, product, sales, operations. 80% of first-time founders fail — and many try again.',
    is_active: true,
  },

  {
    _id: 'veterinarian',
    name: 'Veterinarian',
    family: 'Healthcare → Animal Care',
    one_liner: 'Medical care for animals — companion, livestock, or wildlife.',
    riasec_primary: 'R', riasec_secondary: ['I', 'S'],
    cognitive_styles: ['kinesthetic', 'interpersonal', 'logical'],
    indoor_outdoor: 40, desk_field: 55, solo_team: 50,
    communication_intensity: 4, public_facing: 4, travel: 'occasional', work_hours: 'long', physical_demand: 4,
    education_cost: { govt_inr_lakh: [0.5, 3], private_inr_lakh: [5, 20] },
    education_duration_years: 5,
    entry_salary_inr_lpa: [3, 6], mid_salary_inr_lpa: [8, 18], top_salary_inr_lpa: [25, 60],
    india_market_depth: 3, metro_concentration: 3, international_mobility: 4,
    top_destinations: ['UK', 'Australia', 'Canada'], licensing_portability: 'hard',
    remote_feasibility: 1, immigration_pathway: 3,
    automation_vulnerability: 2, demand_trajectory: 'growing', supply_saturation: 'undersupplied',
    emerging_score: 3, hidden_gem: true,
    required_stream: ['PCB', 'PCMB'], entrance_exams: ['NEET-UG', 'ICAR AIEEA'],
    degree_paths: ['BVSc & AH', 'BVSc + MVSc'], min_qualification: 'BVSc + VCI licence',
    job_stability: 4, work_life_balance: 3, social_prestige_india: 3, autonomy: 4, creative_expression: 2, impact: 5,
    is_active: true,
  },
];
