'use strict';
/* NCERT Exemplar (Class 12, Unit 4 Chemical Kinetics) — 66 questions, answer-key cross-verified,
 * mapped to the 5 practice-bank sections, with improvised explanations.
 * MCQ Type-I (Q1–20) + Assertion-Reason (Q57–61) → gradable `mcq`; everything else → tap-to-reveal `numerical`.
 * Tagged source 'ncert_exemplar'. Two key errors flagged inline: Q14 (rate constant, not rate) and Q25(iv). */
const { pnum, pmcq } = require('./_lib');

const EX = 'ncert_exemplar';
const m = (label, prompt, options, ci, exp) => pmcq(label, prompt, options, ci, exp, EX);
const n = (label, prompt, answer, solution) => pnum(label, prompt, answer, solution, EX);

// 5 standard Assertion–Reason options
const AR = [
  'Both assertion and reason are correct and the reason is the correct explanation of the assertion',
  'Both assertion and reason are correct but the reason does not explain the assertion',
  'Assertion is correct but reason is incorrect',
  'Both assertion and reason are incorrect',
  'Assertion is incorrect but reason is correct',
];
const ar = (label, assertion, reason, ci, exp) =>
  m(label, `**Assertion:** ${assertion}\n\n**Reason:** ${reason}`, AR, ci, exp);

// ─── Section A — Rate of Reaction ───────────────────────────────────────────
const A = [
  m('NCERT Exemplar Q8',
    'A graph of the volume of hydrogen released vs time for the reaction of zinc with dilute $\\ce{HCl}$ is recorded (volumes $V_1, V_2, V_3$ at $t = 20, 30, 40$ s). The average rate up to 40 s is:',
    ['$(V_3 - V_2)/40$', '$(V_3 - V_2)/(40 - 30)$', '$V_3/40$', '$(V_3 - V_1)/(40 - 20)$'], 2,
    'Average rate over an interval = total change ÷ total time. From $t = 0$ (volume 0) to $t = 40$ s the volume is $V_3$, so the average rate up to 40 s is $V_3/40$.'),
  m('NCERT Exemplar Q10',
    'For the same hydrogen-release graph, which of the following does NOT give the instantaneous rate of reaction at the 40th second?',
    ['$(V_5 - V_2)/(50 - 30)$', '$(V_4 - V_2)/(50 - 30)$', '$(V_3 - V_2)/(40 - 30)$', '$(V_3 - V_1)/(40 - 20)$'], 1,
    'The instantaneous rate at $t = 40$ s is approximated by the slope of a secant taken symmetrically about 40 s (e.g. $(V_5 - V_2)/(50 - 30)$). Option (ii) pairs the volume points with a mismatched time interval, so it does not represent the instantaneous rate at 40 s.'),
  m('NCERT Exemplar Q11',
    'Which of the following statements is correct?',
    ['The rate of a reaction decreases with time as the concentration of reactants decreases', 'The rate of a reaction is the same at any time during the reaction', 'The rate of a reaction is independent of temperature change', 'The rate of a reaction decreases with an increase in reactant concentration'], 0,
    'Rate depends on reactant concentration. As reactants are consumed their concentration falls, so the rate decreases over time. The other three statements contradict basic kinetics.'),
  m('NCERT Exemplar Q12',
    'Which expression is correct for the rate of the reaction $\\ce{5Br^- + BrO3^- + 6H^+ -> 3Br2 + 3H2O}$?',
    ['$\\dfrac{\\Delta[\\ce{Br^-}]}{\\Delta t} = 5\\,\\dfrac{\\Delta[\\ce{H^+}]}{\\Delta t}$', '$\\dfrac{\\Delta[\\ce{Br^-}]}{\\Delta t} = \\dfrac{6}{5}\\,\\dfrac{\\Delta[\\ce{H^+}]}{\\Delta t}$', '$\\dfrac{\\Delta[\\ce{Br^-}]}{\\Delta t} = \\dfrac{5}{6}\\,\\dfrac{\\Delta[\\ce{H^+}]}{\\Delta t}$', '$\\dfrac{\\Delta[\\ce{Br^-}]}{\\Delta t} = 6\\,\\dfrac{\\Delta[\\ce{H^+}]}{\\Delta t}$'], 2,
    'The single rate divides each species by its coefficient: $\\frac{1}{5}\\frac{\\Delta[\\ce{Br^-}]}{\\Delta t} = \\frac{1}{6}\\frac{\\Delta[\\ce{H^+}]}{\\Delta t}$, so $\\frac{\\Delta[\\ce{Br^-}]}{\\Delta t} = \\frac{5}{6}\\frac{\\Delta[\\ce{H^+}]}{\\Delta t}$.'),
  m('NCERT Exemplar Q20',
    'For the reaction $\\ce{A <=> B}$, the concentrations of both reactant and product vary exponentially with time. Which figure correctly describes the change in concentration with time?',
    ['[A] falls, while [B] rises only sharply near the very end', '[A] falls exponentially and [B] rises exponentially to a plateau', '[A] falls while [B] rises as a straight line', '[A] rises while [B] falls (the two swapped)'], 1,
    'As A is converted to B, $[\\ce{A}]$ decays exponentially while $[\\ce{B}]$ builds up exponentially toward a plateau — the standard reactant-falls / product-rises pair.'),
  n('NCERT Exemplar Q47',
    'Why does the rate of any reaction generally decrease during the course of the reaction?',
    'Because reactant concentration falls as the reaction proceeds.',
    'The rate depends on the concentration of the reactants. As the reaction proceeds, reactants are converted to products, so their concentration steadily decreases and the rate decreases with it. (Autocatalysis, where a product speeds the reaction, is the rare exception.)'),
  n('NCERT Exemplar Q55',
    'Match Column I with Column II.\n\n| Column I | Column II |\n|---|---|\n| (i) Diamond | (a) short interval of time |\n| (ii) Instantaneous rate | (b) ordinarily the rate of conversion is imperceptible |\n| (iii) Average rate | (c) long duration of time |',
    '(i) → (b), (ii) → (a), (iii) → (c)',
    'Diamond → graphite conversion is so slow its rate is imperceptible (i→b). The instantaneous rate is measured over a vanishingly short interval (ii→a). The average rate is taken over a longer duration of time (iii→c).'),
  n('NCERT Exemplar Q65',
    'Explain the difference between the instantaneous rate of a reaction and the average rate of a reaction.',
    undefined,
    'The **average rate** is the change in concentration over a finite time interval — the slope of the straight line (secant) joining two points on the concentration–time curve. The **instantaneous rate** is the rate at a single moment — the slope of the tangent to the curve at that point, i.e. the limit of the average rate as the interval shrinks to zero. Because the rate changes continuously, the instantaneous rate is the true "rate right now," while the average rate only summarises a stretch of the reaction.'),
];

// ─── Section B — Rate Law, Order & Molecularity ─────────────────────────────
const B = [
  m('NCERT Exemplar Q9',
    'Which of the following statements is NOT correct about the order of a reaction?',
    ['The order of a reaction can be a fractional number', 'Order of a reaction is an experimentally determined quantity', 'The order of a reaction is always equal to the sum of the stoichiometric coefficients of the reactants in the balanced equation', 'The order is the sum of the powers of the molar concentrations of the reactants in the rate-law expression'], 2,
    'Order is found by experiment and equals the sum of the stoichiometric coefficients ONLY for an elementary reaction. For most reactions it does not, so statement (iii) is the false one.'),
  m('NCERT Exemplar Q14',
    'The rate law for $\\ce{A + 2B -> C}$ is found to be Rate $= k[\\ce{A}][\\ce{B}]$. If the concentration of B is doubled while [A] is kept constant, the value of the rate CONSTANT will be:',
    ['the same', 'doubled', 'quadrupled', 'halved'], 0,
    'The rate **constant** $k$ depends only on temperature, not on concentration — so doubling $[\\ce{B}]$ leaves $k$ unchanged: it stays **the same**.\n\n**Answer-key note:** the NCERT Exemplar key marks (ii) "doubled," which is how the *rate* (not the rate *constant*) responds. Since the question explicitly asks for the rate constant, the correct answer is (i) the same.'),
  m('NCERT Exemplar Q17',
    'For $\\ce{A(g) + 2B(g) -> 2C(g)}$, the initial rate of formation of C was measured:\n\n| Exp | $[\\ce{A}]$ | $[\\ce{B}]$ | Rate |\n|---|---|---|---|\n| 1 | 0.30 | 0.30 | 0.10 |\n| 2 | 0.30 | 0.60 | 0.40 |\n| 3 | 0.60 | 0.30 | 0.20 |\n\nThe correct rate law is:',
    ['Rate $= k[\\ce{A}]^2[\\ce{B}]$', 'Rate $= k[\\ce{A}][\\ce{B}]^2$', 'Rate $= k[\\ce{A}][\\ce{B}]$', 'Rate $= k[\\ce{A}]^2[\\ce{B}]^0$'], 1,
    'Exp 1→2: $[\\ce{B}]$ doubled, rate ×4 ⇒ order 2 in B. Exp 1→3: $[\\ce{A}]$ doubled, rate ×2 ⇒ order 1 in A. So Rate $= k[\\ce{A}][\\ce{B}]^2$.'),
  n('NCERT Exemplar Q21',
    'The rate law cannot be determined directly from the balanced chemical equation if ___ (more than one option may be correct).',
    '(i), (iii), (iv)',
    'You can read the rate law off the equation only for a single elementary step. It fails when (i) a reverse reaction is involved, (iii) the reaction is a sequence of elementary steps (complex), or (iv) any reactant is in excess (pseudo-order). The exception is (ii) — a genuine elementary reaction, where the powers do equal the coefficients.'),
  n('NCERT Exemplar Q22',
    'Which statements apply to a balanced chemical equation of an ELEMENTARY reaction? (more than one may be correct)',
    '(i), (iv)',
    'For an elementary reaction (i) the order is the same as the molecularity, and (iv) molecularity — a count of colliding species — can never be zero. Statements (ii) and (iii) (order less than / greater than molecularity) do not hold for an elementary step.'),
  n('NCERT Exemplar Q23',
    'In any unimolecular reaction ___ (more than one option may be correct).',
    '(i), (ii)',
    'A unimolecular reaction has (i) only one reacting species involved in the rate-determining step, and (ii) both the order and the molecularity of that slowest step equal to one.'),
  n('NCERT Exemplar Q24',
    'For a complex reaction ___ (more than one option may be correct).',
    '(i), (iv)',
    'For a complex reaction (i) the order of the overall reaction equals the molecularity of its slowest (rate-determining) step, and (iv) the molecularity of that slowest step is always a whole number ≥ 1 — never zero or a non-integer.'),
  n('NCERT Exemplar Q34',
    'Write the rate equation for the reaction $\\ce{2A + B -> C}$ if the order of the reaction is zero.',
    'Rate $= k[\\ce{A}]^0[\\ce{B}]^0 = k$',
    'Zero order means the rate does not depend on any concentration. So Rate $= k[\\ce{A}]^0[\\ce{B}]^0 = k$ — a constant.'),
  n('NCERT Exemplar Q35',
    'How can you determine the rate law of the reaction $\\ce{2NO(g) + O2(g) -> 2NO2(g)}$?',
    'By the initial-rate method (experiment).',
    'Use the **initial-rate method**: measure the initial rate while changing one reactant at a time. Doubling $[\\ce{NO}]$ (with $[\\ce{O2}]$ fixed) quadruples the rate ⇒ order 2 in NO; doubling $[\\ce{O2}]$ (with $[\\ce{NO}]$ fixed) doubles the rate ⇒ order 1 in $\\ce{O2}$. Hence Rate $= k[\\ce{NO}]^2[\\ce{O2}]$. Orders must be found by experiment, never read off the equation.'),
  n('NCERT Exemplar Q36',
    'For which type of reaction do the order and the molecularity have the same value?',
    'Elementary (single-step) reactions.',
    'For an elementary reaction the rate law mirrors the actual molecular event, so the powers (order) equal the number of colliding species (molecularity). For multi-step (complex) reactions the two can differ.'),
  n('NCERT Exemplar Q37',
    'In a reaction, if the concentration of reactant A is tripled, the rate becomes twenty-seven times. What is the order of the reaction?',
    'Order = 3 (third order).',
    'Rate $\\propto [\\ce{A}]^n$. Tripling A multiplies the rate by $3^n$. Given $3^n = 27 = 3^3$, so $n = 3$.'),
  n('NCERT Exemplar Q39',
    'For $\\ce{A + B -> Products}$ the rate law is Rate $= k[\\ce{A}][\\ce{B}]^{3/2}$. Can the reaction be an elementary reaction? Explain.',
    'No.',
    'For an elementary reaction the order in each reactant equals its molecularity — a whole number. Here the order in B is $\\tfrac32$, a fraction, which a single elementary step cannot give. The fractional order shows the reaction must be complex (multi-step).'),
  n('NCERT Exemplar Q41',
    'For a zero-order reaction, will the molecularity be equal to zero? Explain.',
    'No.',
    'Order and molecularity are different ideas. A zero ORDER means the rate is independent of concentration (often a surface- or light-controlled reaction). MOLECULARITY counts the molecules in an elementary step, and at least one molecule must react — so it can never be zero (or fractional).'),
  n('NCERT Exemplar Q46',
    'Why is the probability of a reaction with molecularity higher than three very rare?',
    'A simultaneous collision of four or more particles is extremely improbable.',
    'A molecularity above three would require four or more molecules to collide at the very same instant with the right orientation and energy — a statistically negligible event. So such steps essentially never occur, and molecularity is limited to 1, 2 or 3.'),
  n('NCERT Exemplar Q50',
    'Why can the molecularity of any reaction not be equal to zero?',
    'At least one molecule must take part.',
    'Molecularity is the number of species coming together in an elementary step. A reaction needs at least one molecule to react, so the minimum molecularity is one — it can never be zero (or a fraction).'),
  n('NCERT Exemplar Q51',
    'Why is molecularity applicable only to elementary reactions while order is applicable to elementary as well as complex reactions?',
    undefined,
    'Molecularity describes a single elementary step (a real collision), so it is meaningful only for an elementary reaction. A complex reaction is a sequence of steps with different molecularities, so an overall molecularity is undefined. Order, by contrast, is an experimental property of the overall rate law and is defined for any reaction — for a complex reaction it is set by the slowest step.'),
  n('NCERT Exemplar Q52',
    'Why can we not determine the order of a reaction by considering the balanced chemical equation?',
    undefined,
    'Most reactions are complex (multi-step), and the balanced equation only summarises the net change, not the mechanism. The order is fixed by the slowest step and must be measured experimentally. For example, $\\ce{KClO3 + 6FeSO4 + 3H2SO4 -> KCl + 3Fe2(SO4)3 + 3H2O}$ looks tenth-order from the equation but is actually second order.'),
  n('NCERT Exemplar Q53',
    'Match each graph in Column I with the order of reaction in Column II (more than one item in Column I may link to the same item in Column II).\n\n| Column I | Column II |\n|---|---|\n| (i) Rate vs concentration — straight line through the origin | (a) 1st order |\n| (ii) Rate vs concentration — horizontal line | (b) zero order |\n| (iii) Concentration vs time — straight line falling | |\n| (iv) log(concentration) vs time — straight line falling | |',
    '(i) → (a), (ii) → (b), (iii) → (b), (iv) → (a)',
    'Rate proportional to concentration (a straight line through the origin) is first order (i→a). Rate independent of concentration (horizontal) is zero order (ii→b). Concentration falling linearly with time is zero order (iii→b). $\\log(\\text{conc})$ falling linearly with time is first order (iv→a).'),
  n('NCERT Exemplar Q56',
    'Match Column I with Column II.\n\n| Column I | Column II |\n|---|---|\n| (i) Mathematical expression for rate of reaction | (a) rate constant |\n| (ii) Rate of reaction for a zero-order reaction equals | (b) rate law |\n| (iii) Units of rate constant for a zero-order reaction are the same as those of | (c) order of the slowest step |\n| (iv) Order of a complex reaction is determined by | (d) rate of a reaction |',
    '(i) → (b), (ii) → (a), (iii) → (d), (iv) → (c)',
    'The mathematical expression for the rate is the rate law (i→b). For zero order, rate $= k$ = the rate constant (ii→a). The zero-order $k$ has units $\\text{mol L}^{-1}\\text{s}^{-1}$ — the same as the rate of a reaction (iii→d). A complex reaction’s order is set by its slowest step (iv→c).'),
  ar('NCERT Exemplar Q57',
    'Order of the reaction can be zero or fractional.',
    'We cannot determine the order from the balanced chemical equation.', 1,
    'Both statements are true, but the reason is not the cause of the assertion: order can be zero/fractional because of the reaction’s mechanism (found by experiment), not merely because it can’t be read off the equation. So both are correct but the reason does not explain the assertion.'),
  ar('NCERT Exemplar Q58',
    'Order and molecularity are the same.',
    'Order is determined experimentally and molecularity is the sum of the stoichiometric coefficients of the reacting species in the rate-determining elementary step.', 4,
    'The assertion is false in general — order equals molecularity only for an elementary reaction, not always. The reason, however, is a correct statement. So the assertion is incorrect but the reason is correct.'),
];

// ─── Section C — Integrated Rate Laws (Zero & First Order) ──────────────────
const C = [
  m('NCERT Exemplar Q16',
    'A first-order reaction is 50% completed in $1.26\\times10^{14}$ s. How much time would it take for 100% completion?',
    ['$1.26\\times10^{15}$ s', '$2.52\\times10^{14}$ s', '$2.52\\times10^{28}$ s', 'Infinite'], 3,
    'A first-order reaction approaches zero exponentially and never truly reaches 100% — completion would take infinite time. (The given $1.26\\times10^{14}$ s is simply its half-life.)'),
  m('NCERT Exemplar Q19',
    'The value of the rate constant of a pseudo first-order reaction ___.',
    ['depends on the concentration of the reactant present in small amount', 'depends on the concentration of the reactant present in excess', 'is independent of the concentration of the reactants', 'depends only on temperature'], 1,
    'For a pseudo first-order reaction (e.g. A + B with B in excess), the observed constant is $k\' = k[\\ce{B}]$. Since $[\\ce{B}]$ is the excess reactant held essentially constant, $k\'$ depends on that excess concentration.'),
  n('NCERT Exemplar Q25',
    'At high pressure the reaction $\\ce{2NH3(g) ->[1130 K][Pt] N2(g) + 3H2(g)}$ is zero order. Which options are correct? (more than one may be correct)',
    '(i), (iii)  — see note on (iv)',
    '(i) Rate = rate constant (a zero-order reaction has rate $= k$); (iii) the rate of decomposition stays constant until the ammonia is completely used up. (ii) is wrong — the rate does NOT depend on $[\\ce{NH3}]$.\n\n**Answer-key note:** the official key also marks (iv) "further increase in pressure will change the rate." But at high pressure the platinum surface is already saturated (which is why the reaction is zero order), so a further pressure increase should NOT change the rate. (i) and (iii) are the unambiguous answers.'),
  n('NCERT Exemplar Q31',
    'Which of the following graphs is/are correct for a zero-order reaction? (more than one may be correct)\n\n(i) reaction rate vs time = constant, then drops to zero · (ii) concentration vs time = curved (exponential) decay · (iii) reaction rate vs time = rising straight line · (iv) concentration vs time = straight line falling with slope $= -k$',
    '(i), (iv)',
    'For zero order the rate is constant ($= k$) until the reactant runs out and then drops to zero — graph (i). And the concentration falls linearly with time, $[\\ce{R}] = [\\ce{R}]_0 - kt$, a straight line of slope $-k$ — graph (iv).'),
  n('NCERT Exemplar Q32',
    'Which of the following graphs is/are correct for a first-order reaction? (more than one may be correct)\n\n(i) $t_{1/2}$ vs $[\\ce{R}]_0$ = horizontal line · (ii) $t_{1/2}$ vs $[\\ce{R}]_0$ = falling line · (iii) molar concentration of P vs time = curve · (iv) $\\log\\dfrac{[\\ce{R}]_0}{[\\ce{R}]}$ vs time = straight line of slope $k/2.303$',
    '(i), (iv)',
    'For first order (i) the half-life is independent of the initial concentration, so $t_{1/2}$ vs $[\\ce{R}]_0$ is a horizontal line; and (iv) $\\log\\frac{[\\ce{R}]_0}{[\\ce{R}]}$ vs time is a straight line of slope $k/2.303$.'),
  n('NCERT Exemplar Q33',
    'State a condition under which a bimolecular reaction is kinetically first order.',
    'When one reactant is in large excess (pseudo first order).',
    'If one of the two reactants is present in large excess, its concentration barely changes during the reaction, so it can be absorbed into the rate constant. The (genuinely bimolecular) reaction then depends only on the other reactant and behaves as first order — e.g. ester hydrolysis with water in excess.'),
  n('NCERT Exemplar Q38',
    'Derive an expression to calculate the time required for the completion of a zero-order reaction.',
    '$t_{\\text{complete}} = \\dfrac{[\\ce{R}]_0}{k}$',
    'For a zero-order reaction $[\\ce{R}] = [\\ce{R}]_0 - kt$. At completion $[\\ce{R}] = 0$, so $0 = [\\ce{R}]_0 - kt_{\\text{complete}}$, giving $t_{\\text{complete}} = \\dfrac{[\\ce{R}]_0}{k}$.'),
  n('NCERT Exemplar Q42',
    'For a general reaction $\\ce{A -> B}$, the plot of the concentration of A vs time is a straight line falling with time (Fig 4.3). From this graph, find (i) the order of the reaction, (ii) the slope of the curve, (iii) the units of the rate constant.',
    '(i) zero order; (ii) slope $= -k$; (iii) $\\text{mol L}^{-1}\\text{s}^{-1}$',
    'A linear concentration–time plot is the signature of a zero-order reaction, $[\\ce{A}] = [\\ce{A}]_0 - kt$. Its slope is $-k$, and the zero-order rate constant carries the units of rate, $\\text{mol L}^{-1}\\text{s}^{-1}$.'),
  n('NCERT Exemplar Q66',
    'With the help of an example, explain what is meant by a pseudo first-order reaction.',
    undefined,
    'A pseudo first-order reaction is genuinely second order but behaves as first order because one reactant is in large excess. Example — acid hydrolysis of an ester: $\\ce{CH3COOC2H5 + H2O ->[H+] CH3COOH + C2H5OH}$. Water (the solvent) is in vast excess, so $[\\ce{H2O}]$ barely changes; the rate $= k[\\text{ester}][\\ce{H2O}]$ reduces to $k\'[\\text{ester}]$ with $k\' = k[\\ce{H2O}]$ — first order in the ester alone.'),
];

// ─── Section D — Gas-Phase & Radioactive First Order ────────────────────────
const D = [
  m('NCERT Exemplar Q5',
    'For the first-order gas-phase decomposition $\\ce{A(g) -> B(g) + C(g)}$ with initial pressure $p_i$, the total pressure after time $t$ has risen by $x$ to become $p_t$. The rate constant is given by:',
    ['$k = \\dfrac{2.303}{t}\\log\\dfrac{p_i}{p_i - x}$', '$k = \\dfrac{2.303}{t}\\log\\dfrac{p_i}{2p_i - p_t}$', '$k = \\dfrac{2.303}{t}\\log\\dfrac{p_i}{2p_i + p_t}$', '$k = \\dfrac{2.303}{t}\\log\\dfrac{p_i}{p_i + x}$'], 1,
    'The total pressure is $p_t = p_i + x$, so the amount reacted is $x = p_t - p_i$, and the pressure of A remaining is $p_i - x = 2p_i - p_t$. The first-order law uses the reactant pressure: $k = \\dfrac{2.303}{t}\\log\\dfrac{p_i}{2p_i - p_t}$.'),
];

// ─── Section E — Temperature, Arrhenius & Catalysis ─────────────────────────
const E = [
  m('NCERT Exemplar Q1',
    'The role of a catalyst is to change ___.',
    ['Gibbs energy of reaction', 'enthalpy of reaction', 'activation energy of reaction', 'equilibrium constant'], 2,
    'A catalyst provides an alternative path with a lower activation energy. It does not change $\\Delta G$, $\\Delta H$ or the equilibrium constant — only the barrier between reactants and products.'),
  m('NCERT Exemplar Q2',
    'In the presence of a catalyst, the heat evolved or absorbed during the reaction ___.',
    ['increases', 'decreases', 'remains unchanged', 'may increase or decrease'], 2,
    'The heat of reaction ($\\Delta H$) depends only on the reactant and product energy levels, which a catalyst does not change — it only lowers the barrier between them. So the heat remains unchanged.'),
  m('NCERT Exemplar Q3',
    'The activation energy of a chemical reaction can be determined by ___.',
    ['determining the rate constant at standard temperature', 'determining the rate constants at two temperatures', 'determining the probability of collision', 'using a catalyst'], 1,
    'From the Arrhenius two-temperature relation $\\ln\\dfrac{k_2}{k_1} = \\dfrac{E_a}{R}\\left(\\dfrac{1}{T_1} - \\dfrac{1}{T_2}\\right)$, measuring the rate constant at two temperatures lets you solve for $E_a$.'),
  m('NCERT Exemplar Q4',
    'In the energy profile of Fig 4.1 (forward activation split into $E_1$ above and $E_2$ below the products level), mark the correct option.',
    ['Activation energy of the forward reaction is $E_1 + E_2$ and the product is less stable than the reactant', 'Activation energy of the forward reaction is $E_1 + E_2$ and the product is more stable than the reactant', 'Activation energy of both forward and backward reactions is $E_1 + E_2$ and the reactant is more stable than the product', 'Activation energy of the backward reaction is $E_1$ and the product is more stable than the reactant'], 0,
    'The forward activation energy is the full climb from reactants to the activated complex, $E_1 + E_2$. Since the products sit above the reactants, the product is at higher energy — i.e. less stable than the reactant.'),
  m('NCERT Exemplar Q6',
    'According to the Arrhenius equation $k = A e^{-E_a/RT}$, which graph correctly represents $\\ln k$ vs $\\dfrac{1}{T}$?',
    ['A straight line with negative slope (falling)', 'A straight line rising from the origin', 'A straight line rising steeply', 'A straight line rising with a positive intercept'], 0,
    'Taking logs, $\\ln k = \\ln A - \\dfrac{E_a}{R}\\cdot\\dfrac{1}{T}$ — a straight line with a NEGATIVE slope $-E_a/R$. So $\\ln k$ falls as $1/T$ increases.'),
  m('NCERT Exemplar Q7',
    'Consider $k = A e^{-E_a/RT}$ and mark the correct option.',
    ['Rate constant increases exponentially with increasing activation energy and decreasing temperature', 'Rate constant decreases exponentially with increasing activation energy and decreasing temperature', 'Rate constant increases exponentially with decreasing activation energy and decreasing temperature', 'Rate constant increases exponentially with decreasing activation energy and increasing temperature'], 3,
    'Lowering $E_a$ and raising $T$ both shrink the magnitude of the negative exponent $-E_a/RT$, so $e^{-E_a/RT}$ — and hence $k$ — increases.'),
  m('NCERT Exemplar Q13',
    'Which of the following energy-profile graphs represents an exothermic reaction?',
    ['(a) — products at lower energy than reactants', '(b) — products at higher energy than reactants', '(c) — products at the same energy as reactants', '(a) and (b) both'], 0,
    'An exothermic reaction releases energy, so the products sit at lower energy than the reactants — graph (a).'),
  m('NCERT Exemplar Q15',
    'Which statement is INCORRECT about the collision theory of chemical reactions?',
    ['It considers reacting molecules or atoms to be hard spheres and ignores their structural features', 'The number of effective collisions determines the rate of reaction', 'Collision of atoms or molecules possessing sufficient threshold energy results in product formation', 'Molecules should collide with sufficient threshold energy and proper orientation for the collision to be effective'], 2,
    'Sufficient energy alone is not enough — proper orientation is also required. So statement (iii) (energy alone guarantees product formation) is the incorrect one.'),
  m('NCERT Exemplar Q18',
    'Which of the following statements is NOT correct for a catalyst?',
    ['It catalyses the forward and backward reactions to the same extent', 'It alters $\\Delta G$ of the reaction', 'It is a substance that does not change the equilibrium constant of a reaction', 'It provides an alternate mechanism by reducing the activation energy between reactants and products'], 1,
    'A catalyst does NOT alter $\\Delta G$ (nor $\\Delta H$ or $K$) — it only lowers the activation barrier and speeds both directions equally. So statement (ii) is the incorrect one.'),
  n('NCERT Exemplar Q26',
    'During the decomposition of an activated complex ___ (more than one option may be correct).',
    '(i), (iv)',
    'When the activated complex breaks down, (i) energy is always released as it falls to a lower-energy state, and (iv) reactants may be formed — the complex can collapse back to reactants as well as forward to products.'),
  n('NCERT Exemplar Q27',
    'According to the Maxwell–Boltzmann distribution of energy ___ (more than one option may be correct).',
    '(i), (iii)',
    'On heating, (i) the fraction of molecules with the most-probable kinetic energy decreases (the peak of the curve lowers), and (iii) the most-probable kinetic energy itself increases (the peak shifts to the right).'),
  n('NCERT Exemplar Q28',
    'In the graph showing the Maxwell–Boltzmann distribution of energy ___ (more than one option may be correct).',
    '(i), (iv)',
    '(i) The area under the curve (the total number of molecules) must not change with temperature; (iv) with an increase in temperature the curve broadens and shifts to the right.'),
  n('NCERT Exemplar Q29',
    'Which statements are in accordance with the Arrhenius equation? (more than one may be correct)',
    '(i), (ii)',
    'The Arrhenius equation gives (i) rate increases with an increase in temperature, and (ii) rate increases with a decrease in activation energy. Statements (iii) and (iv) describe the opposite trends and are wrong.'),
  n('NCERT Exemplar Q30',
    'Mark the INCORRECT statements about a catalyst. (more than one may be correct)',
    '(ii), (iv)',
    '(ii) "Catalyst raises the activation energy" is wrong — it lowers it. (iv) "Catalyst alters the enthalpy change of the reaction" is wrong — $\\Delta H$ is unchanged. Statements (i) and (iii) are correct.'),
  n('NCERT Exemplar Q40',
    'For a certain reaction a large fraction of molecules has energy more than the threshold energy, yet the rate of reaction is very slow. Why?',
    'Proper orientation is also needed for an effective collision.',
    'Energy is not the only requirement for an effective collision — the colliding molecules must also be correctly oriented. If the proper orientation is rarely achieved, most energetic collisions are still ineffective, so the reaction stays slow.'),
  n('NCERT Exemplar Q43',
    'The reaction between $\\ce{H2(g)}$ and $\\ce{O2(g)}$ is highly feasible, yet allowing the gases to stand together at room temperature does not lead to the formation of water. Explain.',
    'The activation energy is very high at room temperature.',
    'Although the reaction is thermodynamically feasible, its activation energy is very high. At room temperature almost no collisions carry that much energy, so the reaction does not start on its own until it is heated or ignited.'),
  n('NCERT Exemplar Q44',
    'Why does the rate of a reaction increase with a rise in temperature?',
    undefined,
    'Heating shifts the Maxwell–Boltzmann distribution so a larger fraction of colliding molecules has energy equal to or greater than the activation energy. More molecules can cross the barrier, so a greater number of collisions are effective and the rate rises (often roughly doubling per 10 °C).'),
  n('NCERT Exemplar Q45',
    'Oxygen is available in plenty in air, yet fuels do not burn by themselves at room temperature. Explain.',
    'Combustion has a very high activation energy.',
    'The combustion of fuels has a very high activation energy, so at room temperature almost no molecules have enough energy to react and the fuel does not ignite on its own. A spark or flame supplies the initial energy needed to get over the barrier.'),
  n('NCERT Exemplar Q48',
    'Thermodynamic feasibility of a reaction alone cannot decide the rate of the reaction. Explain with the help of one example.',
    undefined,
    'Feasibility ($\\Delta G < 0$) tells you a reaction CAN happen, not how fast. The conversion of diamond to graphite is thermodynamically feasible (graphite is more stable), yet it is immeasurably slow because its activation energy is enormous. Rate is governed by the activation barrier, not by $\\Delta G$.'),
  n('NCERT Exemplar Q49',
    'Why, in the redox titration of $\\ce{KMnO4}$ vs oxalic acid, do we heat the oxalic acid solution before starting the titration?',
    'To speed up the otherwise slow reaction.',
    'The reaction between $\\ce{KMnO4}$ and oxalic acid is very slow at room temperature. Warming the oxalic acid (to about 60 °C) raises the fraction of molecules with energy above the activation barrier, so the reaction proceeds fast enough for an accurate titration.'),
  n('NCERT Exemplar Q54',
    'Match Column I with Column II.\n\n| Column I | Column II |\n|---|---|\n| (i) Catalyst alters the rate of reaction | (a) cannot be a fraction or zero |\n| (ii) Molecularity | (b) proper orientation is not there always |\n| (iii) Second half-life of a first-order reaction | (c) by lowering the activation energy |\n| (iv) $e^{-E_a/RT}$ | (d) is the same as the first |\n| (v) Energetically favourable reactions are sometimes slow | (e) total probability is one |\n| (vi) Area under the Maxwell–Boltzmann curve is constant | (f) refers to the fraction of molecules with energy ≥ activation energy |',
    '(i) → (c), (ii) → (a), (iii) → (d), (iv) → (f), (v) → (b), (vi) → (e)',
    'A catalyst speeds a reaction by lowering the activation energy (i→c). Molecularity is a whole number ≥ 1, never a fraction or zero (ii→a). For first order the half-life is constant, so the second half-life equals the first (iii→d). $e^{-E_a/RT}$ is the fraction of molecules with energy ≥ $E_a$ (iv→f). Favourable reactions can be slow when proper orientation is not achieved (v→b). The area under the M–B curve is the total probability, equal to one (vi→e).'),
  ar('NCERT Exemplar Q59',
    'The enthalpy of reaction remains constant in the presence of a catalyst.',
    'A catalyst participating in the reaction forms a different activated complex and lowers the activation energy, but the difference in energy between reactant and product remains the same.', 0,
    'Both statements are true, and the reason correctly explains the assertion: the catalyst changes the barrier (and the activated complex), not the reactant or product energy levels, so their difference — $\\Delta H$ — is unchanged.'),
  ar('NCERT Exemplar Q60',
    'All collisions of reactant molecules lead to product formation.',
    'Only those collisions in which molecules have the correct orientation and sufficient kinetic energy lead to product (compound) formation.', 4,
    'The assertion is false — only a tiny fraction of collisions actually react. The reason is true (orientation plus sufficient energy are both required). So the assertion is incorrect but the reason is correct.'),
  ar('NCERT Exemplar Q61',
    'Rate constants determined from the Arrhenius equation are fairly accurate for simple as well as complex molecules.',
    'Reactant molecules undergo a chemical change irrespective of their orientation during a collision.', 2,
    'The assertion is correct (the Arrhenius equation works well, especially for simple species). The reason is false — orientation DOES matter; molecules do not react regardless of orientation. So the assertion is correct but the reason is incorrect.'),
  n('NCERT Exemplar Q62',
    'All energetically effective collisions do not result in a chemical change. Explain with the help of an example.',
    undefined,
    'Even when colliding molecules have enough energy, they react only if they are correctly oriented. For example, in the reaction $\\ce{NO2Cl + Cl -> NO2 + Cl2}$, the incoming Cl must strike the chlorine end of $\\ce{NO2Cl}$ to form the new Cl–Cl bond; a collision on the oxygen end — however energetic — gives no product. So energy is necessary but not sufficient: proper orientation is also required.'),
  n('NCERT Exemplar Q63',
    'What happens to the most probable kinetic energy and the energy of activation with an increase in temperature?',
    undefined,
    'On heating, the Maxwell–Boltzmann curve flattens and its maximum (the most-probable kinetic energy) shifts to a higher energy value, while the area beyond the activation energy increases — so more molecules can react. The activation energy itself is a property of the reaction and does NOT change with temperature; what changes is the fraction of molecules that can cross it.'),
  n('NCERT Exemplar Q64',
    'Describe how the enthalpy of a reaction remains unchanged when a catalyst is used in the reaction.',
    undefined,
    'Enthalpy is a state function — it depends only on the initial (reactant) and final (product) states, not on the path taken. A catalyst opens a new, lower-energy path between the same reactants and products, lowering the activation energy, but the reactant and product energy levels are unchanged. Since $\\Delta H$ is the difference between those two levels, it stays the same.'),
];

module.exports = { A, B, C, D, E };
