'use strict';
/**
 * Set `correct_index` on every `reasoning_prompt` block in class12-physics, and
 * re-spread the option order so the answer stops living at position A.
 *
 * WHY (two defects, one fix):
 *   1. PEDAGOGY — the schema allows `correct_index` and ReasoningPromptRenderer
 *      renders a right/wrong verdict when it is a number, but NO block set it.
 *      Students were shown only a "your answer" chip and never marked.
 *   2. POSITION BIAS — because `_hygiene.js` only tallies items that carry a
 *      `correct_index`, these 87 blocks were invisible to the answer-position
 *      gate, and the answer drifted to option A in 82 of 87 cases (94%), with
 *      option D never correct. A student could score 94% by always picking A,
 *      which defeats the point of a reasoning check.
 *
 * The correct option for each block was identified by three reviewing agents
 * (files `_reasoning_answers_ch{12,345,6}.json`) and cross-checked against the
 * physics, not just string-matched.
 *
 * ROBUSTNESS: block ids are regenerated by `uuidv4()` on every build-script run,
 * so a block-id key would go stale the moment a chapter is rebuilt. This script
 * therefore keys on the PROMPT TEXT and identifies the answer by the OPTION'S
 * TEXT, both of which survive a rebuild. The rotation seed is the prompt text
 * too, so re-running reproduces the identical layout.
 *
 * SAFETY: writes go through book-writer's `savePage`, which version-snapshots
 * each page first. Idempotent — re-running produces no further change.
 *
 * Run:  node scripts/physics12-book/_apply_reasoning_answers.js --dry
 *       node scripts/physics12-book/_apply_reasoning_answers.js
 */
const fs = require('fs');
const path = require('path');
const bw = require('../lib/book-writer');

/**
 * Rotate the correct answer TO an absolute hash-chosen position.
 *
 * Deliberately NOT `_book.js`'s `spread()`, which rotates *by* `hash % 4`. A
 * relative rotation is not idempotent: running this script twice rotates twice,
 * so every re-run churns all 85 pages and writes a fresh version snapshot. Here
 * the hash picks the DESTINATION index, so the second run computes the same
 * destination, finds the answer already there, and changes nothing.
 * (Same fix the Class 11 Physics Ch.3 build made to its own spreader.)
 */
function rotateHash(seed) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) { h ^= seed.charCodeAt(i); h = Math.imul(h, 16777619); }
  return Math.abs(h);
}
function spreadTo(options, correctIdx, seed) {
  const target = rotateHash(seed) % 4;
  const k = (correctIdx - target + 4) % 4;      // rotate left by k
  if (k === 0) return { options, correct_index: correctIdx };
  return { options: options.slice(k).concat(options.slice(0, k)), correct_index: target };
}

const DRY = process.argv.includes('--dry');
const here = (f) => path.join(__dirname, f);

/**
 * Normalise for comparison. `\dfrac` is folded to `\frac` because the dump was
 * taken before the §4 compliance pass rewrote every `\dfrac`, and the two must
 * still compare equal.
 */
const norm = (s) => String(s || '').replace(/\\dfrac/g, '\\frac').replace(/\s+/g, ' ').trim();

/**
 * Identify a block by (chapter, page, OPTION SET) — deliberately NOT by prompt
 * and NOT by option set alone.
 *
 *  • not the block id — `b()` calls `uuidv4()`, so ids are regenerated on every
 *    build-script run and any id-based key goes stale the moment a chapter is rebuilt;
 *  • not the prompt — prompts are editable (one ch1 prompt gained the word
 *    "identical" during this same fix pass, which broke a prompt-keyed match);
 *  • not the option set alone — ch2 p9 and ch2 p13 have IDENTICAL options
 *    ("It halves / It doubles / It stays the same / It falls to a quarter") but
 *    OPPOSITE answers, because one keeps the battery connected and the other
 *    disconnects it. Keying on options alone silently wrote one block's answer
 *    onto the other. Chapter+page separates them.
 *
 * The key is (chapter, page, CORRECT OPTION TEXT) rather than the whole option
 * set, so that rewording a DISTRACTOR — which the length-tell fix does — cannot
 * break the mapping. It also survives the re-spread this script performs, so
 * re-running is idempotent rather than double-rotating.
 */
const answerKey = (chapter, page, correctText) => `ch${chapter}|p${page}|${norm(correctText)}`;

// ── build prompt-text -> correct-option-TEXT map ────────────────────────────
const dump = JSON.parse(fs.readFileSync(here('_reasoning_dump.json'), 'utf8'));
const byId = new Map(dump.map((d) => [d.block_id, d]));

const answers = ['_reasoning_answers_ch12.json', '_reasoning_answers_ch345.json', '_reasoning_answers_ch6.json']
  .flatMap((f) => {
    const j = JSON.parse(fs.readFileSync(here(f), 'utf8'));
    if (j.uncertain && j.uncertain.length) {
      console.log(`  note: ${f} parked ${j.uncertain.length} item(s) as uncertain — deliberately NOT written`);
    }
    return j.confident || [];
  });

const wanted = new Map(); // option-set key -> correct option text
for (const a of answers) {
  const src = byId.get(a.block_id);
  if (!src) { console.error(`  ⚠ answer references unknown block_id ${a.block_id} — skipped`); continue; }
  const txt = src.options[a.correct_index];
  if (typeof txt !== 'string') { console.error(`  ⚠ bad correct_index ${a.correct_index} for ${a.block_id} — skipped`); continue; }
  wanted.set(answerKey(src.chapter, src.page, txt), norm(txt));
}
if (wanted.size !== answers.length) {
  throw new Error(`key collision: ${answers.length} answers collapsed to ${wanted.size} keys — `
    + 'two blocks would receive the same answer. Refusing to write.');
}
console.log(`answers loaded: ${answers.length} · unique keys: ${wanted.size} (no collisions)\n`);

bw.withDb(async (db) => {
  const book = await db.collection('books').findOne({ slug: 'class12-physics' });
  const pages = (await db.collection('book_pages')
    .find({ book_id: book._id, deleted_at: null }).toArray())
    .sort((a, c) => a.chapter_number - c.chapter_number || a.page_number - c.page_number);

  const before = { 0: 0, 1: 0, 2: 0, 3: 0 };
  const after = { 0: 0, 1: 0, 2: 0, 3: 0 };
  let changedPages = 0; let setCount = 0; let unmatched = 0;

  for (const p of pages) {
    let dirty = false;
    const blocks = (p.blocks || []).map((b) => {
      if (b.type !== 'reasoning_prompt' || !Array.isArray(b.options) || b.options.length !== 4) return b;
      // Find which of this block's options is the one an answer file names.
      const hit = b.options.map(norm).find((o) => wanted.get(answerKey(p.chapter_number, p.page_number, o)) === o);
      if (!hit) { unmatched++; return b; }
      const key = answerKey(p.chapter_number, p.page_number, hit);
      const correctText = hit;
      const idx = b.options.findIndex((o) => norm(o) === correctText);
      if (idx < 0) {
        console.error(`  ⚠ ch${p.chapter_number} p${p.page_number}: correct option text not found among options — skipped`);
        return b;
      }
      before[idx]++;
      // seed on the stable key so the layout is reproducible across rebuilds
      const s = spreadTo(b.options, idx, key);
      after[s.correct_index]++;
      setCount++;
      if (s.correct_index !== b.correct_index || s.options.some((o, i) => o !== b.options[i])) dirty = true;
      return { ...b, options: s.options, correct_index: s.correct_index };
    });
    if (!dirty) continue;
    changedPages++;
    if (!DRY) {
      await bw.savePage(db, { pageId: p._id }, blocks, {
        author: 'script:_apply_reasoning_answers',
        summary: 'set reasoning_prompt correct_index (enables the reader verdict) + re-spread option positions',
      });
    }
  }

  const pct = (t) => Object.values(t).reduce((a, b) => a + b, 0)
    ? Object.entries(t).map(([k, v]) => `${'ABCD'[k]}:${v} (${(100 * v / setCount).toFixed(1)}%)`).join('  ') : '—';
  console.log(`answer position BEFORE : ${pct(before)}`);
  console.log(`answer position AFTER  : ${pct(after)}`);
  console.log(`\n${DRY ? 'DRY RUN — ' : ''}blocks given a correct_index: ${setCount} · pages ${DRY ? 'to change' : 'changed'}: ${changedPages}`
    + (unmatched ? ` · unmatched blocks left untouched: ${unmatched}` : ''));
}).then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
