'use strict';
/**
 * Class 12 Physics · Ch.4 "Magnetic Properties of Matter" — page 11,
 * Practice — NCERT Exercises.
 *
 * Every exercise (5.1–5.25) printed at the end of NCERT's own chapter 5
 * ("Magnetism and Matter") is transcribed here verbatim (Rule 0) and worked
 * in full. NCERT's own exercise numbers ("5.x") are kept in the source_label
 * for citation accuracy — our book's chapter number (4) is a deliberate
 * taxonomy-driven reordering and never renumbers NCERT's own numbering.
 *
 * No figures are referenced anywhere in this exercise set, so nothing is
 * skipped — all 25 items are included.
 *
 * Run: node scripts/physics12-book/build_ch4_d_ncert_exercises.js
 */
const { b, num, ensureBookAndChapter, upsertPages, withDb } = require('./_book');

const CH = 4;

const p11 = {
  page_number: 11,
  slug: 'magnetic-properties-ncert-exercises',
  title: 'Practice — NCERT Exercises',
  subtitle: 'Every exercise from NCERT\'s chapter, worked in full',
  page_type: 'lesson',
  blocks: [
    b('callout', 0, {
      variant: 'note',
      markdown: 'These are the exercises printed at the end of NCERT\'s chapter on magnetism, transcribed word for word. Attempt each one on paper and commit to an answer before you reveal the solution — that struggle is where the method actually gets learned, not the reading afterward.\n\nA few of the discussion questions (5.2 especially) are ones NCERT itself flags as open-ended or not fully settled — for those, look for the best physical reasoning rather than a single "correct" sentence.',
    }),
    b('practice_bank', 1, {
      title: 'NCERT Exercises 5.1 – 5.25',
      intro: 'Twenty-five exercises across five themes, numbered exactly as NCERT numbers them. Work a whole section before you check any of it.',
      sections: [
        // ── A · Dipole moment, torque and energy ─────────────────────────────
        {
          id: 'ncert-a-torque',
          title: 'A · The magnetic dipole moment and torque',
          blurb: 'Exercises 5.3, 5.4, 5.6, 5.7, 5.9, 5.21 — a magnet as a dipole sitting in a field.',
          items: [
            num('ncert-4-3',
              'A short bar magnet placed with its axis at $ 30^\\circ $ with a uniform external magnetic field of $ 0.25 $ T experiences a torque of magnitude equal to $ 4.5 \\times 10^{-2} $ J. What is the magnitude of magnetic moment of the magnet?',
              '$ m = 0.36\\ \\text{J T}^{-1} $ (equivalently $ 0.36\\ \\text{A·m}^{2} $)',
              '$ \\tau = mB\\sin\\theta $, so\n\n$ m = \\frac{\\tau}{B\\sin\\theta} = \\frac{4.5\\times10^{-2}}{(0.25)\\sin30^\\circ} = \\frac{4.5\\times10^{-2}}{(0.25)(0.5)} = \\frac{4.5\\times10^{-2}}{0.125} $\n\n$ m = 0.36\\ \\text{J T}^{-1} $\n\n**Unit check.** Torque is in N·m ( = J), field is in T, and $ \\tau/B\\sin\\theta $ works out to J/T — exactly the unit a magnetic moment should carry.',
              'ncert_exercise', 'NCERT Ex 5.3'),
            num('ncert-4-4',
              'A short bar magnet of magnetic moment $ m = 0.32 $ J T⁻¹ is placed in a uniform magnetic field of $ 0.15 $ T. If the bar is free to rotate in the plane of the field, which orientation would correspond to its (a) stable, and (b) unstable equilibrium? What is the potential energy of the magnet in each case?',
              'Stable: $ \\vec m $ aligned with $ \\vec B $, $ U = -0.048 $ J. Unstable: $ \\vec m $ opposite to $ \\vec B $, $ U = +0.048 $ J.',
              'The potential energy of a dipole in a field is $ U = -mB\\cos\\theta $.\n\n**Stable equilibrium** is the lowest-energy orientation, $ \\theta = 0 $ — the moment points the same way as the field:\n\n$ U_{\\text{stable}} = -mB = -(0.32)(0.15) = -0.048\\ \\text{J} $\n\n**Unstable equilibrium** is the highest-energy orientation, $ \\theta = 180^\\circ $ — moment antiparallel to the field:\n\n$ U_{\\text{unstable}} = +mB = +0.048\\ \\text{J} $\n\nBoth are equilibria because the torque $ \\tau = mB\\sin\\theta $ vanishes at $ 0^\\circ $ and $ 180^\\circ $ — but only $ 0^\\circ $ is *stable*: nudge the magnet slightly there and the restoring torque swings it back. Nudge it at $ 180^\\circ $ and the torque grows, pushing it further away.',
              'ncert_exercise', 'NCERT Ex 5.4'),
            num('ncert-4-6',
              'If the solenoid in Exercise 5.5 is free to turn about the vertical direction and a uniform horizontal magnetic field of $ 0.25 $ T is applied, what is the magnitude of torque on the solenoid when its axis makes an angle of $ 30^\\circ $ with the direction of applied field?',
              '$ \\tau = 0.075\\ \\text{N·m} $',
              'From Exercise 5.5, the solenoid\'s magnetic moment is $ m = NIA = (800)(3.0)(2.5\\times10^{-4}) = 0.60\\ \\text{A·m}^{2} $ — a current-carrying solenoid behaves exactly like a bar magnet of this moment, pointing along its axis.\n\nTreating it as a single magnetic dipole sitting in the applied field:\n\n$ \\tau = mB\\sin\\theta = (0.60)(0.25)\\sin30^\\circ = (0.60)(0.25)(0.5) $\n\n$ \\tau = 0.075\\ \\text{N·m} $\n\nThis is the entire point of the solenoid-as-bar-magnet equivalence: once you have $ m $, a solenoid in a field is no different a calculation from a bar magnet in a field.',
              'ncert_exercise', 'NCERT Ex 5.6'),
            num('ncert-4-7',
              'A bar magnet of magnetic moment $ 1.5 $ J T⁻¹ lies aligned with the direction of a uniform magnetic field of $ 0.22 $ T.\n\n(a) What is the amount of work required by an external torque to turn the magnet so as to align its magnetic moment: (i) normal to the field direction, (ii) opposite to the field direction?\n\n(b) What is the torque on the magnet in cases (i) and (ii)?',
              '(a) $ W_{\\perp} = 0.33 $ J; $ W_{180^\\circ} = 0.66 $ J. (b) $ \\tau_{\\perp} = 0.33 $ N·m; $ \\tau_{180^\\circ} = 0 $.',
              'The work to rotate a dipole from $ \\theta_1 $ to $ \\theta_2 $ against the field is $ W = mB(\\cos\\theta_1 - \\cos\\theta_2) $, starting here from $ \\theta_1 = 0 $ (aligned, the given initial state).\n\n**(a)(i) Normal to the field, $ \\theta_2 = 90^\\circ $:**\n\n$ W = mB(\\cos0^\\circ - \\cos90^\\circ) = mB(1-0) = (1.5)(0.22) = 0.33\\ \\text{J} $\n\n**(a)(ii) Opposite to the field, $ \\theta_2 = 180^\\circ $:**\n\n$ W = mB(\\cos0^\\circ - \\cos180^\\circ) = mB(1-(-1)) = 2mB = 2(1.5)(0.22) = 0.66\\ \\text{J} $\n\nNotice the second value is exactly double the first — turning a dipole all the way around costs twice as much work as turning it a quarter-turn, because $ 180^\\circ $ is the point of *highest* energy, not just "the far side of $ 90^\\circ $."\n\n**(b)** Torque at the two final orientations, $ \\tau = mB\\sin\\theta $:\n\nAt $ \\theta = 90^\\circ $: $ \\tau = mB\\sin90^\\circ = mB = (1.5)(0.22) = 0.33\\ \\text{N·m} $ — the maximum possible torque.\n\nAt $ \\theta = 180^\\circ $: $ \\tau = mB\\sin180^\\circ = 0 $ — zero torque, even though *more* work has been done to reach here than to reach $ 90^\\circ $. Work and torque answer different questions: work is energy spent over the whole rotation; torque is how hard the field twists the magnet right now.',
              'ncert_exercise', 'NCERT Ex 5.7'),
            num('ncert-4-9',
              'A circular coil of $ 16 $ turns and radius $ 10 $ cm carrying a current of $ 0.75 $ A rests with its plane normal to an external field of magnitude $ 5.0 \\times 10^{-2} $ T. The coil is free to turn about an axis in its plane perpendicular to the field direction. When the coil is turned slightly and released, it oscillates about its stable equilibrium with a frequency of $ 2.0\\ \\text{s}^{-1} $. What is the moment of inertia of the coil about its axis of rotation?',
              '$ \\mathcal I \\approx 1.2\\times10^{-4}\\ \\text{kg·m}^{2} $',
              'First, the coil\'s magnetic moment:\n\n$ m = NIA = NI(\\pi r^{2}) = (16)(0.75)\\pi(0.10)^{2} = (12)\\pi(0.010) = 0.377\\ \\text{A·m}^{2} $\n\nA coil displaced slightly from alignment with the field oscillates exactly like a bar magnet, with period\n\n$ T = 2\\pi\\sqrt{\\frac{\\mathcal I}{mB}} \\quad\\Rightarrow\\quad \\mathcal I = \\frac{mBT^{2}}{4\\pi^{2}} $\n\nThe frequency is given directly, so $ T = 1/f = 1/2.0 = 0.50 $ s.\n\n$ \\mathcal I = \\frac{(0.377)(0.050)(0.50)^{2}}{4\\pi^{2}} = \\frac{(0.377)(0.050)(0.25)}{39.48} = \\frac{4.71\\times10^{-3}}{39.48} $\n\n$ \\mathcal I \\approx 1.19\\times10^{-4} \\approx 1.2\\times10^{-4}\\ \\text{kg·m}^{2} $\n\n**Sanity check.** This is a light, small coil, so a moment of inertia in the $ 10^{-4}\\ \\text{kg·m}^{2} $ range — comparable to a light plastic ring a few centimetres across — is entirely reasonable.',
              'ncert_exercise', 'NCERT Ex 5.9'),
            num('ncert-4-21',
              'A magnetic dipole is under the influence of two magnetic fields. The angle between the field directions is $ 60^\\circ $, and one of the fields has a magnitude of $ 1.2 \\times 10^{-2} $ T. If the dipole comes to stable equilibrium at an angle of $ 15^\\circ $ with this field, what is the magnitude of the other field?',
              '$ B_2 \\approx 4.4\\times10^{-3}\\ \\text{T} $',
              'At equilibrium the net torque on the dipole is zero: the torque pulling it toward $ B_1 $ (trying to shrink the $ 15^\\circ $ angle) must exactly balance the torque pulling it toward $ B_2 $ (trying to shrink the remaining $ 60^\\circ - 15^\\circ = 45^\\circ $ angle) — the two fields pull the dipole in opposite rotational senses:\n\n$ mB_1\\sin15^\\circ = mB_2\\sin45^\\circ $\n\nThe dipole moment $ m $ cancels — the equilibrium angle never depended on it:\n\n$ B_2 = B_1\\frac{\\sin15^\\circ}{\\sin45^\\circ} = (1.2\\times10^{-2})\\frac{0.259}{0.707} = (1.2\\times10^{-2})(0.366) $\n\n$ B_2 \\approx 4.39\\times10^{-3}\\ \\text{T} $\n\n**Sanity check on the geometry.** $ B_2 < B_1 $, and the dipole settles closer to $ B_1 $\'s direction ($ 15^\\circ $ away) than to $ B_2 $\'s ($ 45^\\circ $ away) — a dipole caught between two fields always leans closer to the stronger one, exactly as found here.',
              'ncert_exercise', 'NCERT Ex 5.21'),
          ],
        },
        // ── B · Solenoids and coils as magnets ───────────────────────────────
        {
          id: 'ncert-b-solenoids',
          title: 'B · Solenoids and coils as magnets',
          blurb: 'Exercises 5.5, 5.8, 5.20 — a current loop behaving exactly like a bar magnet.',
          items: [
            num('ncert-4-5',
              'A closely wound solenoid of 800 turns and area of cross section $ 2.5 \\times 10^{-4}\\ \\text{m}^{2} $ carries a current of 3.0 A. Explain the sense in which the solenoid acts like a bar magnet. What is its associated magnetic moment?',
              '$ m = 0.60\\ \\text{A·m}^{2} $',
              'A solenoid carrying current $ I $ is a stack of $ N $ current loops, each with a magnetic moment $ IA $ pointing the same way along the axis, so their moments simply add:\n\n$ m = NIA = (800)(3.0)(2.5\\times10^{-4}) $\n\n$ m = 0.60\\ \\text{A·m}^{2} $\n\n**Why it behaves like a bar magnet.** Field lines emerge from one end and curl back into the other, exactly as for a bar magnet, because the fields of the internal loops cancel everywhere except near the two ends. By the right-hand rule — curl your fingers along the current, and your thumb marks the pole the field lines emerge from — that end is the solenoid\'s "north" pole.',
              'ncert_exercise', 'NCERT Ex 5.5'),
            num('ncert-4-8',
              'A closely wound solenoid of 2000 turns and area of cross-section $ 1.6 \\times 10^{-4}\\ \\text{m}^{2} $, carrying a current of 4.0 A, is suspended through its centre allowing it to turn in a horizontal plane.\n\n(a) What is the magnetic moment associated with the solenoid?\n\n(b) What is the force and torque on the solenoid if a uniform horizontal magnetic field of $ 7.5 \\times 10^{-2} $ T is set up at an angle of $ 30^\\circ $ with the axis of the solenoid?',
              '(a) $ m = 1.28\\ \\text{A·m}^{2} $. (b) Net force $ = 0 $; torque $ = 0.048\\ \\text{N·m} $.',
              '**(a)**\n\n$ m = NIA = (2000)(4.0)(1.6\\times10^{-4}) = 1.28\\ \\text{A·m}^{2} $\n\n**(b)** A dipole in a **uniform** field feels a torque but never a net force — the pushes on its two "poles" are equal and opposite, so they cancel even though they don\'t act along the same line. The net force here is exactly zero.\n\nThe torque:\n\n$ \\tau = mB\\sin\\theta = (1.28)(7.5\\times10^{-2})\\sin30^\\circ = (1.28)(0.075)(0.5) $\n\n$ \\tau = 0.048\\ \\text{N·m} $',
              'ncert_exercise', 'NCERT Ex 5.8'),
            num('ncert-4-20',
              'A compass needle free to turn in a horizontal plane is placed at the centre of circular coil of 30 turns and radius 12 cm. The coil is in a vertical plane making an angle of $ 45^\\circ $ with the magnetic meridian. When the current in the coil is 0.35 A, the needle points west to east.\n\n(a) Determine the horizontal component of the earth\'s magnetic field at the location.\n\n(b) The current in the coil is reversed, and the coil is rotated about its vertical axis by an angle of $ 90^\\circ $ in the anticlockwise sense looking from above. Predict the direction of the needle. Take the magnetic declination at the place to be zero.',
              '(a) $ B_H \\approx 0.39 $ G. (b) The needle again shows a $ 90^\\circ $ deflection, but reverses to point from east to west.',
              '**(a)** The coil\'s plane sits at $ 45^\\circ $ to the magnetic meridian, so its axis — the direction of the field it produces at its centre — is also at $ 45^\\circ $ to the meridian (perpendicular to a plane at $ 45^\\circ $ is itself $ 90^\\circ - 45^\\circ = 45^\\circ $ from the meridian).\n\nThe needle settling exactly **west to east** means the resultant field has no north–south part at all: the meridian-component of the coil\'s field must exactly cancel $ B_H $, i.e. $ B_{\\text{coil}}\\cos45^\\circ = B_H $.\n\nThe coil\'s own field at its centre:\n\n$ B_{\\text{coil}} = \\frac{\\mu_0 NI}{2r} = \\frac{(4\\pi\\times10^{-7})(30)(0.35)}{2(0.12)} = \\frac{1.32\\times10^{-5}}{0.24} $\n\n$ B_{\\text{coil}} \\approx 5.50\\times10^{-5}\\ \\text{T} = 0.550\\ \\text{G} $\n\nSo:\n\n$ B_H = B_{\\text{coil}}\\cos45^\\circ = (0.550)(0.707) \\approx 0.39\\ \\text{G} $\n\n**(b)** Because the coil\'s field made exactly $ 45^\\circ $ with the meridian, its meridian-component and its east–west component were **equal in size** — both equal to $ B_H $, since $ \\sin45^\\circ = \\cos45^\\circ $. Reversing the current flips the whole field by $ 180^\\circ $; rotating the coil a further $ 90^\\circ $ about the vertical turns it by another quarter turn. Tracking the two together, the field ends up still $ 45^\\circ $ from the meridian — so its meridian-component is still exactly $ B_H $ in size and still cancels $ B_H $ — but the east–west component, equal in size to before, has flipped sign.\n\nSo the needle again settles exactly along east–west, but now points from **east to west**: the mirror image of part (a).',
              'ncert_exercise', 'NCERT Ex 5.20'),
          ],
        },
        // ── C · Earth's magnetism, dip and neutral points ────────────────────
        {
          id: 'ncert-c-earth',
          title: "C · The Earth's magnetism, dip and neutral points",
          blurb: 'Exercises 5.1, 5.2, 5.10, 5.11, 5.12, 5.13, 5.14, 5.15, 5.18, 5.19 — the largest set, and where a wrong formula choice does the most damage.',
          items: [
            num('ncert-4-1',
              'Answer the following questions regarding earth\'s magnetism:\n\n(a) A vector needs three quantities for its specification. Name the three independent quantities conventionally used to specify the earth\'s magnetic field.\n\n(b) The angle of dip at a location in southern India is about $ 18^\\circ $. Would you expect a greater or smaller dip angle in Britain?\n\n(c) If you made a map of magnetic field lines at Melbourne in Australia, would the lines seem to go into the ground or come out of the ground?\n\n(d) In which direction would a compass free to move in the vertical plane point to, if located right on the geomagnetic north or south pole?\n\n(e) The earth\'s field, it is claimed, roughly approximates the field due to a dipole of magnetic moment $ 8 \\times 10^{22} $ J T⁻¹ located at its centre. Check the order of magnitude of this number in some way.\n\n(f) Geologists claim that besides the main magnetic N-S poles, there are several local poles on the earth\'s surface oriented in different directions. How is such a thing possible at all?',
              '(a) Declination, dip, horizontal component $ B_H $. (b) Greater. (c) Come out of the ground. (d) Vertically down at the north pole, vertically up at the south pole. (e) Order of magnitude checks out. (f) Local magnetised mineral deposits distort the field.',
              '**(a)** The three magnetic elements: **declination** (the horizontal angle between geographic and magnetic north), the **angle of dip** (the angle the field makes with the horizontal), and the **horizontal component** $ B_H $. Together they fix the field vector completely, exactly as three coordinates fix a point.\n\n**(b)** Southern India sits close to the magnetic equator, where dip is small. Britain is at a much higher magnetic latitude (dip grows steadily from equator to pole), so you would expect a **greater** dip angle there — roughly $ 66^\\circ $ in reality, against about $ 18^\\circ $ in southern India.\n\n**(c)** Melbourne is in the southern hemisphere. Field lines run from the (northern) magnetic south region down through the earth and emerge in the southern hemisphere, so at Melbourne they would seem to **come out of the ground** — the vertical component points upward there, the reverse of the northern-hemisphere case.\n\n**(d)** Right at either geomagnetic pole the field is purely vertical ($ B_H = 0 $), so a needle free to swing in the vertical plane simply aligns with it: pointing **straight down** at the geomagnetic north pole (where field lines converge into the ground) and **straight up** at the geomagnetic south pole (where they emerge).\n\n**(e)** A quick order-of-magnitude check: spread that dipole moment over the entire volume of the earth ($ R \\approx 6.4\\times10^{6} $ m) and see what magnetisation it implies.\n\n$ V = \\frac{4}{3}\\pi R^{3} \\approx 1.1\\times10^{21}\\ \\text{m}^{3} $\n\n$ M = \\frac{m}{V} = \\frac{8\\times10^{22}}{1.1\\times10^{21}} \\approx 73\\ \\text{A/m} $\n\nCompare this with the saturation magnetisation of a strongly magnetised ferromagnet like iron, of order $ 10^{6} $ A/m. The implied magnetisation here is **four to five orders of magnitude smaller** — entirely reasonable for a field produced by circulating currents rather than a solidly magnetised core, and consistent in *order of magnitude* with the claimed dipole moment being physically sensible rather than absurd.\n\n**(f)** Local pole-like anomalies come from magnetised mineral deposits (iron ore bodies) and other geological structures near the surface, which superpose their own small field on the earth\'s main dipole field. They are local distortions riding on top of the global field, not evidence of additional "true" poles.',
              'ncert_exercise', 'NCERT Ex 5.1'),
            num('ncert-4-2',
              'Answer the following questions:\n\n(a) The earth\'s magnetic field varies from point to point in space. Does it also change with time? If so, on what time scale does it change appreciably?\n\n(b) The earth\'s core is known to contain iron. Yet geologists do not regard this as a source of the earth\'s magnetism. Why?\n\n(c) The charged currents in the outer conducting regions of the earth\'s core are thought to be responsible for earth\'s magnetism. What might be the \'battery\' (i.e., the source of energy) to sustain these currents?\n\n(d) The earth may have even reversed the direction of its field several times during its history of 4 to 5 billion years. How can geologists know about the earth\'s field in such distant past?\n\n(e) The earth\'s field departs from its dipole shape substantially at large distances (greater than about 30,000 km). What agencies may be responsible for this distortion?\n\n(f) Interstellar space has an extremely weak magnetic field of the order of $ 10^{-12} $ T. Can such a weak field be of any significant consequence? Explain.',
              'All six are discussion answers — see the full reasoning; (c) is genuinely unsettled and NCERT flags it as such.',
              '**(a)** Yes. The field changes on a "secular" (century-scale) time scale — for instance, the magnetic declination measured at London shifted by about $ 3.5^\\circ $ between 1580 and 1975. Superimposed on this slow drift are much faster day-to-day and hour-to-hour variations driven by currents in the upper atmosphere and by the solar wind.\n\n**(b)** The earth\'s core is far hotter than the Curie temperature of iron (about $ 770^\\circ\\text{C} $), above which a material loses its ferromagnetic ordering and can no longer hold a permanent magnetisation — it behaves merely as a paramagnet. Molten core iron simply cannot be a bar-magnet-like source in the way solid iron at room temperature can.\n\n**(c)** This is the least settled part of the question, and NCERT itself treats it as open. The leading picture is a **dynamo mechanism**: convective motion of molten, electrically conducting iron in the outer core, combined with the earth\'s rotation, sustains circulating electric currents that generate the field. The ultimate energy source feeding this convection is thought to be a mix of residual heat from the earth\'s formation and heat released by radioactive decay in the interior — but the precise energy budget remains a genuine research question.\n\n**(d)** Through **palaeomagnetism**. When molten rock (particularly on the ocean floor, at spreading ridges) cools through its Curie temperature, the magnetic domains that form freeze in alignment with whatever the earth\'s field direction was *at that moment* — like a fossil compass reading. Stripes of alternating magnetic polarity in rock of different ages, symmetric on either side of mid-ocean ridges, are the direct evidence that the field has reversed many times.\n\n**(e)** At large distances the earth\'s own dipole field becomes weak enough that it is overwhelmed by the **solar wind** — the stream of charged particles from the sun — which compresses the field on the sunward side and stretches it into a long tail on the night side, distorting it far from the simple dipole shape close to the surface.\n\n**(f)** Yes — a field can matter enormously even at $ 10^{-12} $ T, because its effect on a charged particle accumulates over the enormous distances and times available in interstellar space. A charged particle\'s path curves with a radius set by that (tiny) field, and over light-years of travel even a very gentle curvature adds up to a significant deflection — which is exactly why interstellar magnetic fields shape the paths of cosmic rays despite being many orders of magnitude weaker than the earth\'s own field.',
              'ncert_exercise', 'NCERT Ex 5.2'),
            num('ncert-4-10',
              'A magnetic needle free to rotate in a vertical plane parallel to the magnetic meridian has its north tip pointing down at $ 22^\\circ $ with the horizontal. The horizontal component of the earth\'s magnetic field at the place is known to be 0.35 G. Determine the magnitude of the earth\'s magnetic field at the place.',
              '$ B \\approx 0.38 $ G',
              'The needle\'s north tip dipping $ 22^\\circ $ below horizontal means the angle of dip is $ \\delta = 22^\\circ $.\n\n$ B_H = B\\cos\\delta \\quad\\Rightarrow\\quad B = \\frac{B_H}{\\cos\\delta} = \\frac{0.35}{\\cos22^\\circ} = \\frac{0.35}{0.927} $\n\n$ B \\approx 0.378 \\approx 0.38\\ \\text{G} $\n\n**Check:** the total field must exceed its own horizontal component, and $ 0.38 > 0.35 $ ✓. Dividing by $ \\cos\\delta $ rather than multiplying is the check that catches the commonest slip here.',
              'ncert_exercise', 'NCERT Ex 5.10'),
            num('ncert-4-11',
              'At a certain location in Africa, a compass points $ 12^\\circ $ west of the geographic north. The north tip of the magnetic needle of a dip circle placed in the plane of magnetic meridian points $ 60^\\circ $ above the horizontal. The horizontal component of the earth\'s field is measured to be 0.16 G. Specify the direction and magnitude of the earth\'s field at the location.',
              '$ B \\approx 0.32 $ G, directed $ 12^\\circ $ west of geographic north and $ 60^\\circ $ above the horizontal.',
              'The compass bearing gives the **declination**: $ 12^\\circ $ west of geographic north fixes the vertical plane (the magnetic meridian) that the field lies in.\n\nThe dip circle gives the **dip**: the needle\'s north tip sits $ 60^\\circ $ **above** the horizontal — so $ \\delta = 60^\\circ $, with the field tilted upward rather than the more familiar downward tilt of the northern hemisphere. (An upward dip like this is exactly what you would expect at a location south of the magnetic equator.)\n\nMagnitude, from the horizontal component:\n\n$ B = \\frac{B_H}{\\cos\\delta} = \\frac{0.16}{\\cos60^\\circ} = \\frac{0.16}{0.5} = 0.32\\ \\text{G} $\n\nSo the full specification: **0.32 G**, lying in the vertical plane $ 12^\\circ $ west of geographic north, inclined $ 60^\\circ $ above the horizontal.',
              'ncert_exercise', 'NCERT Ex 5.11'),
            num('ncert-4-12',
              'A short bar magnet has a magnetic moment of 0.48 J T⁻¹. Give the direction and magnitude of the magnetic field produced by the magnet at a distance of 10 cm from the centre of the magnet on (a) the axis, (b) the equatorial lines (normal bisector) of the magnet.',
              '(a) $ B_{\\text{axial}} = 9.6\\times10^{-5} $ T, parallel to $ \\vec m $. (b) $ B_{\\text{eq}} = 4.8\\times10^{-5} $ T, antiparallel to $ \\vec m $.',
              '**(a) On the axis:**\n\n$ B = \\frac{\\mu_0}{4\\pi}\\cdot\\frac{2m}{d^{3}} = (10^{-7})\\cdot\\frac{2(0.48)}{(0.10)^{3}} = (10^{-7})\\cdot\\frac{0.96}{1.0\\times10^{-3}} $\n\n$ B = (10^{-7})(960) = 9.6\\times10^{-5}\\ \\text{T} $, directed **parallel to $ \\vec m $** — along the axis, from S towards N.\n\n**(b) On the equatorial line:**\n\n$ B = \\frac{\\mu_0}{4\\pi}\\cdot\\frac{m}{d^{3}} = (10^{-7})\\cdot\\frac{0.48}{1.0\\times10^{-3}} = (10^{-7})(480) = 4.8\\times10^{-5}\\ \\text{T} $, directed **antiparallel to $ \\vec m $** — opposite to the axis direction.\n\nNotice the equatorial value is exactly half the axial value at the same distance, and its direction is reversed — the same factor-of-two-and-a-flip relationship carried over unchanged from the electric dipole.',
              'ncert_exercise', 'NCERT Ex 5.12'),
            num('ncert-4-13',
              'A short bar magnet placed in a horizontal plane has its axis aligned along the magnetic north-south direction. Null points are found on the axis of the magnet at 14 cm from the centre of the magnet. The earth\'s magnetic field at the place is 0.36 G and the angle of dip is zero. What is the total magnetic field on the normal bisector of the magnet at the same distance as the null-point (i.e., 14 cm) from the centre of the magnet? (At null points, field due to a magnet is equal and opposite to the horizontal component of earth\'s magnetic field.)',
              '$ B_{\\text{total}} = 0.54 $ G',
              'Null points on the **axis** mean the magnet\'s north pole points **south** (the book\'s rule: N pointing south puts the neutral points on the axis, N pointing north puts them on the equatorial line). Since the dip is zero, $ B_H $ *is* the total earth field here.\n\nAt the axial null point, the magnet\'s axial field exactly cancels $ B_H $:\n\n$ \\frac{\\mu_0}{4\\pi}\\cdot\\frac{2m}{d^{3}} = B_H \\quad (d = 0.14\\ \\text{m}) $\n\nWe don\'t actually need $ m $ or $ d $ separately — only their combination, and it\'s already fixed by this equation. At the *same distance* $ d $, the magnet\'s **equatorial** field is exactly half its axial field (same $ \\mu_0/4\\pi $, same $ d^3 $, but $ m $ instead of $ 2m $):\n\n$ B_{\\text{eq, magnet}} = \\frac{\\mu_0}{4\\pi}\\cdot\\frac{m}{d^{3}} = \\frac{1}{2}\\left(\\frac{\\mu_0}{4\\pi}\\cdot\\frac{2m}{d^{3}}\\right) = \\frac{B_H}{2} = \\frac{0.36}{2} = 0.18\\ \\text{G} $\n\nNow the direction. The magnet\'s north pole points **south**, so $ \\vec m $ points south. On the equatorial line the field is **antiparallel to $ \\vec m $** — so it points **north**, the *same* direction as $ B_H $ (which always points along magnetic north). The two fields therefore **add**:\n\n$ B_{\\text{total}} = B_H + B_{\\text{eq, magnet}} = 0.36 + 0.18 = 0.54\\ \\text{G} $\n\n**The trap this problem is built to catch:** assuming the fields subtract just because they did at the null point. They only cancelled *there* because that was the whole point of a null point — on the equatorial line, at the same distance, the same magnet adds to $ B_H $ instead.',
              'ncert_exercise', 'NCERT Ex 5.13'),
            num('ncert-4-14',
              'If the bar magnet in exercise 5.13 is turned around by $ 180^\\circ $, where will the new null points be located?',
              'On the equatorial line, at $ d\' \\approx 11.1 $ cm from the centre.',
              'Turning the magnet $ 180^\\circ $ makes its north pole point **north** instead of south — so by the rule, the null points move from the axis onto the **equatorial line**.\n\nFrom Exercise 5.13, the axial condition at $ d = 0.14 $ m gave:\n\n$ \\frac{\\mu_0}{4\\pi}\\cdot\\frac{2m}{(0.14)^{3}} = B_H \\quad\\Rightarrow\\quad \\frac{\\mu_0}{4\\pi}\\,m = \\frac{B_H(0.14)^{3}}{2} $\n\nThe new (equatorial) null-point condition at some distance $ d\' $:\n\n$ \\frac{\\mu_0}{4\\pi}\\cdot\\frac{m}{d\'^{3}} = B_H \\quad\\Rightarrow\\quad d\'^{3} = \\frac{1}{B_H}\\cdot\\frac{\\mu_0}{4\\pi}\\,m = \\frac{1}{B_H}\\cdot\\frac{B_H(0.14)^{3}}{2} = \\frac{(0.14)^{3}}{2} $\n\n$ d\' = \\frac{0.14}{2^{1/3}} = \\frac{0.14}{1.26} \\approx 0.111\\ \\text{m} = 11.1\\ \\text{cm} $\n\n**Why smaller.** The equatorial field is weaker than the axial field at the same distance (by a factor of 2), so to still equal $ B_H $ it needs to be measured *closer in* — exactly what $ d\' < d $ says. One null point sits on each side of the magnet along the perpendicular bisector.',
              'ncert_exercise', 'NCERT Ex 5.14'),
            num('ncert-4-15',
              'A short bar magnet of magnetic moment $ 5.25 \\times 10^{-2} $ J T⁻¹ is placed with its axis perpendicular to the earth\'s field direction. At what distance from the centre of the magnet, the resultant field is inclined at $ 45^\\circ $ with earth\'s field on (a) its normal bisector and (b) its axis. Magnitude of the earth\'s field at the place is given to be 0.42 G. Ignore the length of the magnet in comparison to the distances involved.',
              '(a) On the normal bisector (equatorial line): $ d \\approx 5.0 $ cm. (b) On the axis: $ d \\approx 6.3 $ cm.',
              'Since the magnet\'s axis is perpendicular to $ B_H $, the magnet\'s own field — whether measured on the axis or on the equatorial line — always points **along the magnet\'s axis**, and is therefore always **perpendicular to $ B_H $** too. So in both parts the two fields are at right angles, and a $ 45^\\circ $ resultant means the two perpendicular fields are simply **equal in magnitude** ($ \\tan45^\\circ = 1 $).\n\n**(a) Equatorial line:** need $ \\frac{\\mu_0}{4\\pi}\\cdot\\frac{m}{d^{3}} = B_H $.\n\n$ d^{3} = \\frac{\\mu_0 m}{4\\pi B_H} = \\frac{(10^{-7})(5.25\\times10^{-2})}{0.42\\times10^{-4}} = \\frac{5.25\\times10^{-9}}{4.2\\times10^{-5}} = 1.25\\times10^{-4}\\ \\text{m}^{3} $\n\n$ d = (1.25\\times10^{-4})^{1/3} = (125\\times10^{-6})^{1/3} = 5\\times10^{-2}\\ \\text{m} = 5.0\\ \\text{cm} $\n\n**(b) Axis:** the axial field carries an extra factor of 2, so $ \\frac{\\mu_0}{4\\pi}\\cdot\\frac{2m}{d^{3}} = B_H $ gives $ d^{3} $ exactly double part (a)\'s value:\n\n$ d^{3} = 2\\times1.25\\times10^{-4} = 2.5\\times10^{-4}\\ \\text{m}^{3} $\n\n$ d = (2.5\\times10^{-4})^{1/3} \\approx 6.3\\times10^{-2}\\ \\text{m} = 6.3\\ \\text{cm} $\n\n**Sanity check.** The axial field is stronger at any given distance, so to still equal $ B_H $ it can be measured *farther out* — and indeed $ 6.3\\ \\text{cm} > 5.0\\ \\text{cm} $ ✓.',
              'ncert_exercise', 'NCERT Ex 5.15'),
            num('ncert-4-18',
              'A long straight horizontal cable carries a current of 2.5 A in the direction 10º south of west to 10º north of east. The magnetic meridian of the place happens to be 10º west of the geographic meridian. The earth\'s magnetic field at the location is 0.33 G, and the angle of dip is zero. Locate the line of neutral points (ignore the thickness of the cable). (At neutral points, magnetic field due to a current-carrying cable is equal and opposite to the horizontal component of earth\'s magnetic field.)',
              'A line parallel to the cable, about 1.5 cm from it (below or above, depending on the current direction).',
              '**First establish the cable\'s direction relative to the magnetic (not geographic) compass.** Magnetic north is $ 10^\\circ $ **west** of geographic north — rotate the geographic compass by $ 10^\\circ $ this way and geographic "west" becomes "$ 10^\\circ $ south of west," while geographic "east" becomes "$ 10^\\circ $ north of east." That is *exactly* the cable\'s stated direction — so the cable runs precisely along the **magnetic east–west** line, perpendicular to the magnetic meridian.\n\nSince the dip is zero, $ B_H $ equals the total earth field, 0.33 G, and it points along magnetic north — perpendicular to the cable. At a point directly below (or above) the cable, the field produced by the current is horizontal and lies along the magnetic north–south line too (a field circling an east–west wire is horizontal and north–south directly under it) — so the cable\'s field is perfectly set up to cancel $ B_H $ at some distance.\n\nSetting the cable\'s field equal to $ B_H $:\n\n$ \\frac{\\mu_0 I}{2\\pi d} = B_H \\quad\\Rightarrow\\quad d = \\frac{\\mu_0 I}{2\\pi B_H} = \\frac{(4\\pi\\times10^{-7})(2.5)}{2\\pi(0.33\\times10^{-4})} = \\frac{(2\\times10^{-7})(2.5)}{3.3\\times10^{-5}} $\n\n$ d = \\frac{5\\times10^{-7}}{3.3\\times10^{-5}} \\approx 1.5\\times10^{-2}\\ \\text{m} = 1.5\\ \\text{cm} $\n\nThe neutral points form a **line parallel to the cable**, at this $ 1.5 $ cm perpendicular distance — below the cable if the current cancels $ B_H $ there, above it if the current runs the other way (the problem doesn\'t fix which way the 2.5 A flows, only that it is 1.5 cm to one side).',
              'ncert_exercise', 'NCERT Ex 5.18'),
            num('ncert-4-19',
              'A telephone cable at a place has four long straight horizontal wires carrying a current of 1.0 A in the same direction east to west. The earth\'s magnetic field at the place is 0.39 G, and the angle of dip is 35º. The magnetic declination is nearly zero. What are the resultant magnetic fields at points 4.0 cm below the cable?',
              '$ B_{\\text{net}} \\approx 0.25 $ G',
              'With zero declination, magnetic north coincides with geographic north, and the wire (running east–west) is perpendicular to $ B_H $.\n\n**Resolve the earth\'s field first.** The given 0.39 G is the *total* field (dip is quoted separately):\n\n$ B_H = B\\cos35^\\circ = (0.39)(0.819) \\approx 0.319\\ \\text{G} $, pointing north (horizontal)\n\n$ B_V = B\\sin35^\\circ = (0.39)(0.574) \\approx 0.224\\ \\text{G} $, pointing down (vertical)\n\n**Field from the cable.** Treat the four wires as one, carrying $ 4\\times1.0 = 4.0 $ A, at perpendicular distance $ r = 0.04 $ m:\n\n$ B_{\\text{wire}} = \\frac{\\mu_0 I}{2\\pi r} = \\frac{(2\\times10^{-7})(4.0)}{0.04} = 2.0\\times10^{-5}\\ \\text{T} = 0.20\\ \\text{G} $\n\nDirectly below an east–west wire, this field is horizontal and lies along the north–south line — and by the right-hand rule (current flowing east to west) it points **south**, i.e. directly opposing $ B_H $.\n\n**Combine.** The wire\'s field only affects the horizontal part; the vertical component is untouched:\n\n$ B_H^{\\text{net}} = 0.319 - 0.20 = 0.119\\ \\text{G} $ (still north, since $ B_H $ was larger)\n\n$ B^{\\text{net}} = \\sqrt{(B_H^{\\text{net}})^{2} + B_V^{2}} = \\sqrt{(0.119)^{2}+(0.224)^{2}} = \\sqrt{0.0142+0.0502} = \\sqrt{0.0644} $\n\n$ B^{\\text{net}} \\approx 0.25\\ \\text{G} $\n\nThe field below the cable is weaker than the undisturbed earth field (0.39 G), because the cable\'s field partially undoes the horizontal part while leaving the dip\'s vertical part completely alone.',
              'ncert_exercise', 'NCERT Ex 5.19'),
          ],
        },
        // ── D · Diamagnetism, paramagnetism, ferromagnetism ──────────────────
        {
          id: 'ncert-d-materials',
          title: 'D · Diamagnetism, paramagnetism, ferromagnetism',
          blurb: 'Exercises 5.16, 5.17, 5.23, 5.24 — what matter does to a field, and how that\'s put to use.',
          items: [
            num('ncert-4-16',
              'Answer the following questions:\n\n(a) Why does a paramagnetic sample display greater magnetisation (for the same magnetising field) when cooled?\n\n(b) Why is diamagnetism, in contrast, almost independent of temperature?\n\n(c) If a toroid uses bismuth for its core, will the field in the core be (slightly) greater or (slightly) less than when the core is empty?\n\n(d) Is the permeability of a ferromagnetic material independent of the magnetic field? If not, is it more for lower or higher fields?\n\n(e) Magnetic field lines are always nearly normal to the surface of a ferromagnet at every point. Why?\n\n(f) Would the maximum possible magnetisation of a paramagnetic sample be of the same order of magnitude as the magnetisation of a ferromagnet?',
              '(a) Less thermal disorder to fight. (b) No permanent dipoles to disorder in the first place. (c) Slightly less — bismuth is diamagnetic. (d) No — greater at lower fields. (e) High permeability bends field lines toward the normal. (f) Same order at true saturation, but ordinary lab conditions fall far short of it.',
              '**(a)** Paramagnetism comes from **permanent** atomic dipoles that the applied field tries to align, opposed by random thermal motion. Cooling reduces that thermal agitation, so a larger fraction of dipoles stay aligned for the same applied field — magnetisation increases. This is exactly Curie\'s law, $ \\chi \\propto 1/T $.\n\n**(b)** Diamagnetism comes from an **induced** moment created by the field itself (essentially a Lenz\'s-law-type response in the electron orbits), not from permanent dipoles competing against thermal disorder. Since there is no alignment being fought by temperature in the first place, heating or cooling barely changes it.\n\n**(c)** Bismuth is diamagnetic ($ \\chi $ small and negative, $ \\mu_r $ slightly less than 1), so it slightly *weakens* the field compared with an empty (vacuum) core. The field would be **slightly less**.\n\n**(d)** No. A ferromagnet\'s permeability is **not** a constant — it rises steeply at low fields, and falls off again as the material approaches saturation at high fields. So $ \\mu_r $ is **greater at lower fields**.\n\n**(e)** A ferromagnet has $ \\mu_r \\gg 1 $. At a boundary, field lines refract according to $ \\tan\\theta_1/\\tan\\theta_2 = \\mu_1/\\mu_2 $ — with the ferromagnet\'s permeability enormously larger than air\'s, the lines inside run nearly parallel to the surface while the lines just outside are bent to run nearly **along the normal**. That is why, looking at the field just outside a ferromagnet, the lines appear to meet the surface almost perpendicularly at every point.\n\n**(f)** At true **saturation** — every atomic dipole fully aligned — a paramagnet\'s magnetisation can be of the *same order of magnitude* as a ferromagnet\'s, because both are ultimately set by a comparable density of atomic magnetic moments. The catch is *reaching* saturation: a ferromagnet gets there through the cooperative exchange interaction between neighbouring atoms, needing only a modest field. A paramagnet has no such cooperation — each dipole fights thermal agitation alone — so reaching anywhere near saturation needs impractically strong fields and impractically low temperatures. Under ordinary lab conditions, a paramagnet\'s actual magnetisation sits many orders of magnitude below a ferromagnet\'s.',
              'ncert_exercise', 'NCERT Ex 5.16'),
            num('ncert-4-17',
              'Answer the following questions:\n\n(a) Explain qualitatively on the basis of domain picture the irreversibility in the magnetisation curve of a ferromagnet.\n\n(b) The hysteresis loop of a soft iron piece has a much smaller area than that of a carbon steel piece. If the material is to go through repeated cycles of magnetisation, which piece will dissipate greater heat energy?\n\n(c) \'A system displaying a hysteresis loop such as a ferromagnet, is a device for storing memory?\' Explain the meaning of this statement.\n\n(d) What kind of ferromagnetic material is used for coating magnetic tapes in a cassette player, or for building \'memory stores\' in a modern computer?\n\n(e) A certain region of space is to be shielded from magnetic fields. Suggest a method.',
              '(a) Domain-wall motion is not fully reversible. (b) Carbon steel dissipates more. (c) The magnetisation state records which way the field was last applied. (d) A hard ferromagnetic material with high retentivity — e.g. a ceramic/ferrite. (e) Enclose the region in a high-permeability soft-iron shield.',
              '**(a)** Below saturation, magnetisation grows by domain walls sweeping through the material and by whole domains rotating to align with the field. This motion isn\'t frictionless — domain walls get pinned at crystal defects and impurities, and unpinning them costs energy that is dissipated, not recovered when the field is reduced. So the material doesn\'t retrace its own path backward: the magnetisation *lags* the field, tracing out different curves going up and coming down. That lag is exactly the hysteresis loop, and it exists because domain-wall motion is not a reversible process.\n\n**(b)** The area enclosed by a hysteresis loop equals the energy dissipated as heat **per cycle, per unit volume** of the material. A larger loop area means more dissipation per cycle — so **carbon steel**, with the much bigger loop, dissipates the greater heat energy over repeated cycles. (This is exactly why transformer cores are made of soft iron, not steel — you want the small loop.)\n\n**(c)** The statement means the material\'s current magnetisation state is not fixed by the *present* field alone — it also depends on the field\'s *history*, specifically the last direction it was strongly magnetised in. Two different histories can leave the material in two different stable states even under the same present field (zero, say). That dependence on history is precisely what "memory" means: the state itself encodes information about the past.\n\n**(d)** A **hard** ferromagnetic material — one with high retentivity and high coercivity, so it holds a magnetisation firmly once set and resists being erased by stray fields. Ceramic (ferrite) materials with a nearly rectangular hysteresis loop are used for cassette tapes and for magnetic "memory store" elements, because a nearly-square loop gives two clearly distinct, stable remanent states — a natural binary 0/1.\n\n**(e)** Enclose the region inside a shell of **high-permeability soft-iron** (or similar high-$ \\mu_r $ ferromagnetic material). Because field lines strongly prefer to travel through the high-permeability path (the same reasoning as part (e) of Exercise 5.16 — field lines bend toward a high-$ \\mu_r $ material), most of the external field is drawn through the shell\'s material instead of penetrating the enclosed space, leaving the interior largely field-free. This is standard practical **magnetic shielding**.',
              'ncert_exercise', 'NCERT Ex 5.17'),
            num('ncert-4-23',
              'A sample of paramagnetic salt contains $ 2.0 \\times 10^{24} $ atomic dipoles each of dipole moment $ 1.5 \\times 10^{-23} $ J T⁻¹. The sample is placed under a homogeneous magnetic field of 0.64 T, and cooled to a temperature of 4.2 K. The degree of magnetic saturation achieved is equal to 15%. What is the total dipole moment of the sample for a magnetic field of 0.98 T and a temperature of 2.8 K? (Assume Curie\'s law)',
              '$ M_2 \\approx 10.3\\ \\text{J T}^{-1} $',
              'The maximum possible total moment (100% saturation, every dipole aligned):\n\n$ M_{\\max} = Nm = (2.0\\times10^{24})(1.5\\times10^{-23}) = 30\\ \\text{J T}^{-1} $\n\nAt 15% saturation (the given initial state), the actual total moment is\n\n$ M_1 = 0.15 \\times 30 = 4.5\\ \\text{J T}^{-1} $\n\nCurie\'s law says magnetisation (well below saturation) is proportional to $ B/T $, so the total moment scales the same way:\n\n$ \\frac{M_2}{M_1} = \\frac{B_2/T_2}{B_1/T_1} = \\frac{B_2\\,T_1}{B_1\\,T_2} = \\frac{(0.98)(4.2)}{(0.64)(2.8)} = \\frac{4.116}{1.792} \\approx 2.30 $\n\n$ M_2 = 4.5 \\times 2.30 \\approx 10.3\\ \\text{J T}^{-1} $\n\n**Sanity check.** $ 10.3 $ J T⁻¹ is about 34% of $ M_{\\max} = 30 $ J T⁻¹ — still well below full saturation, so Curie\'s law (valid away from saturation) is a reasonable approximation to use here, and the growth from 15% to 34% saturation makes sense given both a stronger field and a colder sample.',
              'ncert_exercise', 'NCERT Ex 5.23'),
            num('ncert-4-24',
              'A Rowland ring of mean radius 15 cm has 3500 turns of wire wound on a ferromagnetic core of relative permeability 800. What is the magnetic field B in the core for a magnetising current of 1.2 A?',
              '$ B \\approx 4.48 $ T',
              'A Rowland ring is a toroid, so treat it exactly like a long solenoid bent into a circle: the magnetising field depends on turns per unit length along the mean circumference.\n\n$ H = \\frac{NI}{L} = \\frac{NI}{2\\pi R} = \\frac{(3500)(1.2)}{2\\pi(0.15)} = \\frac{4200}{0.9425} \\approx 4456\\ \\text{A/m} $\n\n$ B = \\mu_0\\mu_rH = (4\\pi\\times10^{-7})(800)(4456) $\n\n$ = (1.257\\times10^{-6})(800)(4456) \\approx 4.48\\ \\text{T} $\n\n**What this shows.** Without the ferromagnetic core, the same current would give only $ B = \\mu_0 H \\approx 5.6\\times10^{-3} $ T — the core has multiplied the field roughly 800-fold, exactly the meaning of $ \\mu_r = 800 $. This is the whole reason electromagnets and transformers use ferromagnetic cores rather than air.',
              'ncert_exercise', 'NCERT Ex 5.24'),
          ],
        },
        // ── E · The harder additional exercises ──────────────────────────────
        {
          id: 'ncert-e-hard',
          title: 'E · The harder additional exercises',
          blurb: 'Exercises 5.22, 5.25 — a charged-particle deflection, and where classical physics stops matching quantum reality.',
          items: [
            num('ncert-4-22',
              'A monoenergetic (18 keV) electron beam initially in the horizontal direction is subjected to a horizontal magnetic field of 0.04 G normal to the initial direction. Estimate the up or down deflection of the beam over a distance of 30 cm. ($ m_e = 9.11\\times10^{-31} $ kg)',
              'Deflection $ \\approx 0.40 $ mm (up or down, depending on the field\'s direction).',
              '**Find the electron\'s speed from its kinetic energy.**\n\n$ KE = 18\\ \\text{keV} = (18\\times10^{3})(1.6\\times10^{-19}) = 2.88\\times10^{-15}\\ \\text{J} $\n\n$ v = \\sqrt{\\frac{2\\,KE}{m_e}} = \\sqrt{\\frac{2(2.88\\times10^{-15})}{9.11\\times10^{-31}}} = \\sqrt{6.32\\times10^{15}} \\approx 7.95\\times10^{7}\\ \\text{m/s} $\n\n(About a quarter of the speed of light — fast, but the non-relativistic formula used here is the one this course expects and is accurate enough for an estimate.)\n\n**Radius of the circular arc in the field.** The magnetic force supplies the centripetal force, $ evB = \\frac{mv^{2}}{r} $, so $ r = \\frac{m_ev}{eB} $:\n\n$ B = 0.04\\ \\text{G} = 4\\times10^{-6}\\ \\text{T} $\n\n$ r = \\frac{(9.11\\times10^{-31})(7.95\\times10^{7})}{(1.6\\times10^{-19})(4\\times10^{-6})} = \\frac{7.24\\times10^{-23}}{6.4\\times10^{-25}} \\approx 113\\ \\text{m} $\n\n**Convert the arc to a sideways deflection over $ L = 0.30 $ m.** Since $ r \\gg L $, the path barely curves, and the small-angle "sagitta" approximation applies:\n\n$ y \\approx \\frac{L^{2}}{2r} = \\frac{(0.30)^{2}}{2(113)} = \\frac{0.09}{226} $\n\n$ y \\approx 3.98\\times10^{-4}\\ \\text{m} \\approx 0.40\\ \\text{mm} $\n\n**Why "up or down" and not a definite direction:** the deflection\'s sense depends on which way the field points and the sign of the electron\'s charge, neither of which is pinned down by the numbers alone — but the *magnitude*, a few tenths of a millimetre over 30 cm, is the physically interesting result: even a field as weak as $ 0.04 $ G noticeably bends a fast electron beam, which is exactly the sensitivity that makes stray magnetic fields a real nuisance around old CRT-style displays.',
              'ncert_exercise', 'NCERT Ex 5.22'),
            num('ncert-4-25',
              'The magnetic moment vectors $ \\mu_s $ and $ \\mu_l $ associated with the intrinsic spin angular momentum $ S $ and orbital angular momentum $ l $, respectively, of an electron are predicted by quantum theory (and verified experimentally to a high accuracy) to be given by:\n\n$ \\mu_s = -\\frac{e}{m}S $, $ \\qquad \\mu_l = -\\frac{e}{2m}l $\n\nWhich of these relations is in accordance with the result expected classically? Outline the derivation of the classical result.',
              'The orbital relation, $ \\mu_l = -\\frac{e}{2m}l $, matches the classical result. The spin relation carries an extra factor of 2 that classical physics cannot account for.',
              '**Classical derivation, for orbital motion.** Model the electron as a charge $ -e $ moving on a circular orbit of radius $ r $ with period $ T $. This is a tiny current loop, with current\n\n$ I = \\frac{-e}{T} $\n\nand magnetic moment (magnitude $ \\times $ area):\n\n$ \\mu = IA = \\frac{-e}{T}(\\pi r^{2}) $\n\nThe orbital angular momentum of this same motion is $ l = m_ev\\,r $, and since $ v = 2\\pi r/T $,\n\n$ l = m_e\\left(\\frac{2\\pi r}{T}\\right)r = \\frac{2\\pi m_e r^{2}}{T} $\n\nDivide the two expressions to eliminate $ T $ and $ r^2 $ together:\n\n$ \\frac{\\mu}{l} = \\frac{(-e/T)(\\pi r^{2})}{2\\pi m_e r^{2}/T} = \\frac{-e}{2m_e} $\n\n$ \\mu = -\\frac{e}{2m_e}\\,l $\n\nThis is **exactly** the given $ \\mu_l $ relation — a genuinely classical result, needing nothing more than "current loop" and the definition of angular momentum.\n\n**Why $ \\mu_s $ is different.** The spin relation carries a factor of $ e/m $, not $ e/2m $ — twice as large. That extra factor of 2 (called the electron\'s *g*-factor) has no classical derivation at all: electron spin is not literally a small charged sphere physically rotating, so there is no orbit, no radius and no period to run the argument above with. The factor of 2 emerges only from relativistic quantum mechanics (Dirac\'s equation) and is one of the clean signatures that spin is an intrinsically quantum property with no true classical counterpart — the classical picture only ever succeeds for the *orbital* moment.',
              'ncert_exercise', 'NCERT Ex 5.25'),
          ],
        },
      ],
    }),
    b('text', 2, {
      markdown: 'That closes the chapter\'s own exercise set. One promise made along the way is still open — that a current loop is itself a magnetic dipole with $ m = NIA $, seen here in Exercises 5.5, 5.6, 5.8 and 5.9. The next chapter, Magnetic Effects of Current, starts from the force on a single moving charge and builds up to exactly that result from the other direction.',
    }),
  ],
};

async function main() {
  await withDb(async (db) => {
    const bookId = await ensureBookAndChapter(db, CH);
    await upsertPages(db, bookId, CH, [p11]);
  });
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
