'use strict';
/**
 * Class 12 Physics · Ch.8 "Electromagnetic Waves" — page 10, Practice & Mastery.
 *
 * Every item carries source 'mcq' (no badge). Nothing here is attributed to a
 * third-party reference book (standing no-third-party-attribution rule), and
 * nothing is badged 'ncert_exemplar' because none of it was transcribed from
 * the Exemplar — inventing that badge would be a false provenance claim.
 * The genuine NCERT end-of-chapter exercises are page 11, built separately.
 *
 * Ch.8 is deliberately SHORTER than Ch.6 and Ch.7 (plan §6 rule 6): thirty-one
 * items, not thirty-six. Padding a low-yield chapter to match a heavy one is
 * how a book stops being trustworthy about what matters.
 *
 * Run: node scripts/physics12-book/build_ch8_c_practice.js
 */
const { b, mcq, num, ensureBookAndChapter, upsertPages, withDb } = require('./_book');

const CH = 8;

const p10 = {
  page_number: 10,
  slug: 'emw-practice-and-mastery',
  title: 'Practice & Mastery',
  subtitle: 'Six sections, thirty-one problems — commit to an answer before you look',
  page_type: 'lesson',
  blocks: [
    b('callout', 0, {
      variant: 'fun_fact',
      markdown: 'How to use this page.\n\nElectromagnetic waves is the chapter that feels easy while you read it and then costs marks quietly. Almost nothing here is hard algebra. What catches people is a picture held slightly wrong — fields imagined a quarter-cycle apart when they are in step, a ratio written upside down, a factor of two dropped from a mirror, a spectrum listed the wrong way round.\n\nSo work each item like this. Say the physical picture out loud in one sentence. Do the arithmetic on paper. Commit to the answer. **Only then** open the solution. If you were right for the wrong reason, the explanation is written to catch you.',
    }),
    b('practice_bank', 1, {
      title: 'Electromagnetic Waves — the full set',
      intro: 'The sections follow the chapter in order, from the crack in Ampere\u2019s law through to the spectrum. Numerical items ask you to produce the answer yourself; in the multiple-choice items every wrong option is a mistake somebody actually makes, so read all four before choosing. Take $ c = 3.0\\times10^{8} $ m/s and $ \\varepsilon_0 = 8.85\\times10^{-12} $ C²/(N·m²) throughout.',
      sections: [
        // ── 1 · Displacement current and the Ampere-Maxwell law ──────────────
        {
          id: 'ch8-s1-displacement-current',
          title: '1 · Displacement current and the Ampere-Maxwell law',
          blurb: 'A changing electric field does everything a current does. Once you believe that, the rest of the chapter is bookkeeping.',
          items: [
            mcq('ch8-p01', 'The displacement current between the plates of a charging capacitor is given by',
              ['$ \\varepsilon_0\\frac{d\\Phi_E}{dt} $', '$ \\mu_0\\frac{d\\Phi_B}{dt} $', '$ \\varepsilon_0\\frac{d\\Phi_B}{dt} $', '$ \\frac{1}{\\varepsilon_0}\\frac{d\\Phi_E}{dt} $'],
              0,
              'Maxwell\u2019s patch to Ampere\u2019s law is\n\n$ i_d = \\varepsilon_0\\frac{d\\Phi_E}{dt} $\n\nRead the two symbols carefully, because three of the four choices differ only in which one appears where. It is the **electric** flux that is changing, so the subscript is $ E $, not $ B $. And the constant that turns a rate of electric flux into an ampere is $ \\varepsilon_0 $, sitting on top — the version with $ \\varepsilon_0 $ in the denominator is off by a factor of about $ 10^{22} $.\n\nA quick dimension check settles it. Electric flux has units of $ \\text{V}\\cdot\\text{m} $, so its rate is $ \\text{V}\\cdot\\text{m}/\\text{s} $, and $ \\varepsilon_0 $ carries farads per metre. Multiply and you get farad-volts per second, which is coulombs per second — an ampere. Nothing else in that list does.'),
            num('ch8-p02', 'A parallel-plate capacitor has circular plates of radius $ 6.0 $ cm and is being charged by a steady conduction current of $ 0.15 $ A. Find (a) the displacement current between the plates, (b) the rate at which the electric field between them is growing, and (c) the magnetic field at a point $ 3.0 $ cm from the axis, midway between the plates.',
              '(a) $ 0.15 $ A  (b) $ 1.5\\times10^{12} $ V/(m·s)  (c) $ 2.5\\times10^{-7} $ T',
              '**(a)** The displacement current in the gap always equals the conduction current in the wire feeding it — that is exactly what Maxwell\u2019s term was invented to guarantee. So $ i_d = 0.15 $ A, with no calculation needed.\n\n**(b)** Between the plates $ \\Phi_E = EA $, so\n\n$ i_d = \\varepsilon_0 A\\,\\frac{dE}{dt} $\n\nwith $ A = \\pi r^{2} = \\pi(0.060)^{2} = 1.13\\times10^{-2} $ m².\n\n$ \\frac{dE}{dt} = \\frac{0.15}{(8.85\\times10^{-12})(1.13\\times10^{-2})} = \\frac{0.15}{1.00\\times10^{-13}} = 1.5\\times10^{12} $ V/(m·s)\n\n**(c)** Apply the Ampere-Maxwell law to a circle of radius $ r = 0.030 $ m in the gap. Only the fraction of the displacement current threading that circle counts:\n\n$ i_{\\text{enc}} = i_d\\frac{r^{2}}{R^{2}} = 0.15\\times\\frac{(0.030)^{2}}{(0.060)^{2}} = 0.15\\times0.25 = 0.0375 $ A\n\n$ B = \\frac{\\mu_0 i_{\\text{enc}}}{2\\pi r} = \\frac{(2\\times10^{-7})(0.0375)}{0.030} = 2.5\\times10^{-7} $ T\n\n**What to store.** Inside the gap the maths is identical to finding $ B $ inside a thick current-carrying wire — the displacement current is spread uniformly over the plate area, so it behaves like a uniform current density. Treat it as a current in every way except that no charge is moving.'),
            mcq('ch8-p03', 'For a parallel-plate capacitor being charged, the displacement current between the plates comes out exactly equal to the conduction current in the wire because',
              ['the flux $ \\Phi_E $ between the plates is exactly $ \\frac{q}{\\varepsilon_0} $', 'charge leaks slowly across the gap between the plates', 'the gap is narrow, so the two currents are nearly equal', 'the electric field between the plates does not change'],
              0,
              'Do the two lines. The field between the plates is $ E = \\frac{\\sigma}{\\varepsilon_0} = \\frac{q}{\\varepsilon_0 A} $, so the flux is\n\n$ \\Phi_E = EA = \\frac{q}{\\varepsilon_0} $\n\nThe area cancels. Now differentiate:\n\n$ i_d = \\varepsilon_0\\frac{d\\Phi_E}{dt} = \\varepsilon_0\\cdot\\frac{1}{\\varepsilon_0}\\frac{dq}{dt} = \\frac{dq}{dt} = i_c $\n\nSo the equality is **exact**, not an approximation that gets better as the gap shrinks, and it has nothing to do with any charge crossing the gap — the gap is an insulator and no charge crosses it at all. That is the whole point: the field in an empty gap does a current\u2019s job without any current being there.'),
            mcq('ch8-p04', 'A loop encircles the wire feeding a charging capacitor. Two different surfaces are stretched across that same loop: a flat disc pierced by the wire, and a bag that bulges out and passes between the capacitor plates. The Ampere-Maxwell law gives the same $ \\oint\\vec{B}\\cdot d\\vec{l} $ for both because',
              ['the bag carries no conduction current but an equal displacement current', 'the disc carries a displacement current equal to the conduction current', 'neither surface encloses any current of either kind', 'the field between the plates is zero, so the bag contributes nothing'],
              0,
              'This is the crisis the chapter opened with, and the resolution.\n\nThe disc is pierced by the wire, so it sees conduction current $ i_c $ and no changing electric flux. The bag is pierced by nothing — the wire misses it — but the growing field between the plates pours changing electric flux through it, giving displacement current $ i_d $.\n\nBecause $ i_d = i_c $ exactly, both surfaces report the same total $ \\mu_0(i_c + i_d) $, and the law stops contradicting itself. Notice which term is zero on which surface: the disc has $ i_c $ only, the bag has $ i_d $ only. Swapping those round is the commonest way to describe this correctly-but-backwards in an exam.\n\nThe deeper payoff is that Kirchhoff\u2019s junction rule survives. Current does not stop at the plate; it continues through the gap as displacement current, and the circuit is unbroken.'),
            mcq('ch8-p05', 'Inside the gap of a capacitor whose circular plates have radius $ R $ and which is charging at a steady rate, the magnetic field at distance $ r $ from the axis (with $ r < R $) is',
              ['directly proportional to $ r $', 'inversely proportional to $ r $', 'independent of $ r $', 'proportional to $ r^{2} $'],
              0,
              'The displacement current is spread evenly over the plate area, so the amount threading a circle of radius $ r $ grows as $ r^{2} $:\n\n$ i_{\\text{enc}} = i_d\\frac{r^{2}}{R^{2}} $\n\nPut that into $ B(2\\pi r) = \\mu_0 i_{\\text{enc}} $:\n\n$ B = \\frac{\\mu_0 i_d r}{2\\pi R^{2}} $\n\nOne power of $ r $ survives, so $ B $ rises linearly from zero on the axis to a maximum at the rim. **Outside** the plates it is a different story — all of $ i_d $ is now enclosed, so $ B = \\frac{\\mu_0 i_d}{2\\pi r} $ and the field falls off as $ \\frac{1}{r} $.\n\nThat inverse relation is the trap here, because it is the formula everybody memorised for a long straight wire. It is right outside and wrong inside.'),
          ],
        },
        // ── 2 · Maxwell's equations ─────────────────────────────────────────
        {
          id: 'ch8-s2-maxwell-equations',
          title: '2 · Maxwell\u2019s equations',
          blurb: 'Four lines that hold the whole of this book. Know what each one says in plain words before you worry about the symbols.',
          items: [
            mcq('ch8-p06', 'Of the four equations that now carry his name, the one Maxwell himself altered was',
              ['Ampere\u2019s law, by adding the displacement-current term', 'Faraday\u2019s law, by putting the minus sign in front of it', 'Gauss\u2019s law for electricity, by adding a magnetic term', 'Gauss\u2019s law for magnetism, by allowing isolated poles'],
              0,
              'Three of the four laws arrived intact from the people who discovered them: Gauss for electricity, Gauss for magnetism, and Faraday for induction — the minus sign in Faraday\u2019s law is Lenz\u2019s contribution, made decades before Maxwell.\n\nAmpere\u2019s law was the one that broke. As written it gave two different answers for the same loop depending on which surface you chose, and Maxwell mended it by adding $ \\varepsilon_0\\frac{d\\Phi_E}{dt} $ alongside the conduction current:\n\n$ \\oint\\vec{B}\\cdot d\\vec{l} = \\mu_0\\left(i_c + \\varepsilon_0\\frac{d\\Phi_E}{dt}\\right) $\n\nWhat makes this the great moment in the subject is that he was fixing a bookkeeping inconsistency, not hunting for waves. The waves fell out of the repaired equations by themselves.'),
            mcq('ch8-p07', 'The equation $ \\oint\\vec{B}\\cdot d\\vec{A} = 0 $, taken over any closed surface, is a statement that',
              ['isolated magnetic poles do not exist', 'a magnetic field can never do work on a charge', 'magnetic field lines can never cross each other', 'the magnetic field inside a conductor is zero'],
              0,
              'Compare it with its electric partner, $ \\oint\\vec{E}\\cdot d\\vec{A} = \\frac{q}{\\varepsilon_0} $. There, wrapping a surface round a lone charge gives a non-zero answer: electric field lines begin and end on charges, so a surface can enclose a **source**.\n\nThe magnetic version reads zero for every surface you can draw. Whatever field lines enter must also leave, which means there is nothing for them to start or stop on. Magnetic field lines close on themselves, and every magnet you cut in half gives you two magnets rather than a loose north pole.\n\nThe statement about work is true of magnetic forces but is a separate fact from the Lorentz force, not something this equation says. And field lines never crossing is true of both $ \\vec{E} $ and $ \\vec{B} $, so it cannot be what distinguishes this equation from Gauss\u2019s law for electricity.'),
            mcq('ch8-p08', 'Suppose an isolated north pole — a magnetic monopole — were discovered tomorrow. The equation that would have to be rewritten is',
              ['Gauss\u2019s law for magnetism, which at present reads zero', 'Gauss\u2019s law for electricity, which has a source term already', 'Faraday\u2019s law, which at present carries a minus sign', 'the Ampere-Maxwell law, which already carries two terms'],
              0,
              'The zero on the right of $ \\oint\\vec{B}\\cdot d\\vec{A} = 0 $ is not a mathematical convenience — it is the experimental claim that there is no magnetic charge to enclose. Find one and that zero becomes a source term, something like $ \\mu_0 q_m $, in exact parallel with $ \\frac{q}{\\varepsilon_0} $ on the electric side.\n\nGauss\u2019s law for electricity already has its source term and would not change. Faraday\u2019s law would in fact gain a magnetic-current term too, but its minus sign — which is conservation of energy — would stay exactly where it is.\n\nThis is worth doing as an exercise even though no monopole has ever been found, because it shows you what each symbol is actually claiming about the world. An equation you can imagine breaking is an equation you understand.'),
            mcq('ch8-p09', 'The law which says that a changing magnetic field produces an electric field is',
              ['Faraday\u2019s law, $ \\oint\\vec{E}\\cdot d\\vec{l} = -\\frac{d\\Phi_B}{dt} $', 'the Ampere-Maxwell law, $ \\oint\\vec{B}\\cdot d\\vec{l} = \\mu_0(i_c + i_d) $', 'Gauss\u2019s law for electricity, $ \\oint\\vec{E}\\cdot d\\vec{A} = \\frac{q}{\\varepsilon_0} $', 'Gauss\u2019s law for magnetism, $ \\oint\\vec{B}\\cdot d\\vec{A} = 0 $'],
              0,
              'Read the equation from the inside out. On the right sits $ \\frac{d\\Phi_B}{dt} $ — a **changing magnetic flux**. On the left sits a loop integral of $ \\vec{E} $ — an **electric field** running round a closed path. So the sentence the equation makes is: a changing magnetic field drives an electric field round a loop.\n\nThe Ampere-Maxwell law is the mirror image, with $ \\Phi_E $ on the right and $ \\vec{B} $ on the left: a changing electric field produces a magnetic field.\n\nThose two together are the engine of this chapter, and the reason they must be kept straight is that the wave uses them alternately — each field regenerating the other, endlessly, with no charge in sight.'),
            mcq('ch8-p10', 'In empty space — no charges anywhere, no conduction currents anywhere — a wave can still exist and keep going. The two equations that make this possible are',
              ['Faraday\u2019s law and the Ampere-Maxwell law', 'the two Gauss laws, for electricity and for magnetism', 'Gauss\u2019s law for electricity and Faraday\u2019s law', 'Gauss\u2019s law for magnetism and the Ampere-Maxwell law'],
              0,
              'Set $ q = 0 $ and $ i_c = 0 $ everywhere. Both Gauss laws collapse to zero on the right and say only that the field lines have no sources — useful, but they cannot make anything happen.\n\nWhat remains is a pair of feedback statements. Faraday: a changing $ \\vec{B} $ makes an $ \\vec{E} $. Ampere-Maxwell, with $ i_c $ gone: a changing $ \\vec{E} $ makes a $ \\vec{B} $. Each field is the cause of the other, so once the pattern is started it sustains itself and rolls forward through empty space.\n\nWithout Maxwell\u2019s added term the second half of that loop would not exist and the whole thing would die on the spot. This is why the small repair on the first page of the chapter turned out to predict light.'),
          ],
        },
        // ── 3 · Speed, and light as an EM wave ──────────────────────────────
        {
          id: 'ch8-s3-speed',
          title: '3 · Speed, and light as an EM wave',
          blurb: 'Two constants from a bench experiment, and out comes the speed of light. Then the routine conversions you will use for the rest of physics.',
          items: [
            num('ch8-p11', 'Using $ \\mu_0 = 4\\pi\\times10^{-7} $ T·m/A and $ \\varepsilon_0 = 8.85\\times10^{-12} $ C²/(N·m²), evaluate $ \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}} $ and say what the number is.',
              '$ 3.0\\times10^{8} $ m/s — the speed of light in vacuum.',
              'Multiply the two constants first:\n\n$ \\mu_0\\varepsilon_0 = (1.257\\times10^{-6})(8.85\\times10^{-12}) = 1.112\\times10^{-17} $\n\nTake the square root. Write the power as an even number before you do, or you will get the exponent wrong:\n\n$ \\sqrt{11.12\\times10^{-18}} = 3.335\\times10^{-9} $\n\n$ c = \\frac{1}{3.335\\times10^{-9}} = 3.0\\times10^{8} $ m/s\n\n**Sit with this for a moment.** $ \\mu_0 $ was fixed by measuring the force between two current-carrying wires. $ \\varepsilon_0 $ was fixed by measuring the force between two charges. Neither experiment involves light, or motion, or anything travelling. Combine them and out comes the speed at which light crosses the room — a number Fizeau had already measured with a toothed wheel and a distant mirror.\n\nThat agreement is the moment optics stopped being a separate subject.'),
            mcq('ch8-p12', 'A transparent medium has relative permittivity $ 4 $ and relative permeability $ 1 $. Light travels through it at',
              ['$ 1.5\\times10^{8} $ m/s', '$ 0.75\\times10^{8} $ m/s', '$ 3.0\\times10^{8} $ m/s', '$ 6.0\\times10^{8} $ m/s'],
              0,
              'In a medium the same derivation runs with $ \\mu $ and $ \\varepsilon $ in place of $ \\mu_0 $ and $ \\varepsilon_0 $:\n\n$ v = \\frac{1}{\\sqrt{\\mu\\varepsilon}} = \\frac{1}{\\sqrt{\\mu_r\\varepsilon_r}}\\cdot\\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}} = \\frac{c}{\\sqrt{\\mu_r\\varepsilon_r}} $\n\nHere $ \\sqrt{\\mu_r\\varepsilon_r} = \\sqrt{4} = 2 $, so $ v = \\frac{3.0\\times10^{8}}{2} = 1.5\\times10^{8} $ m/s.\n\nDividing by $ \\varepsilon_r $ instead of by its square root gives $ 0.75\\times10^{8} $ m/s, which is the slip this item is built around. And notice what the quantity $ \\sqrt{\\mu_r\\varepsilon_r} $ is: it is the **refractive index**, $ n = 2 $ here. Optics has just handed electromagnetism its most-used number.\n\nNothing travels faster than $ c $, so an answer above $ 3.0\\times10^{8} $ m/s should be rejected before you even check the arithmetic.'),
            num('ch8-p13', 'Find (a) the wavelength in vacuum of an FM radio signal at $ 100 $ MHz, and (b) the frequency of orange light of wavelength $ 600 $ nm.',
              '(a) $ 3.0 $ m  (b) $ 5.0\\times10^{14} $ Hz',
              'Both are the same one-line relation, $ c = \\nu\\lambda $, run in opposite directions.\n\n**(a)** $ \\lambda = \\frac{c}{\\nu} = \\frac{3.0\\times10^{8}}{1.0\\times10^{8}} = 3.0 $ m\n\n**(b)** $ \\nu = \\frac{c}{\\lambda} = \\frac{3.0\\times10^{8}}{6.0\\times10^{-7}} = 5.0\\times10^{14} $ Hz\n\n**Two habits worth building.** Convert every prefix to a power of ten *before* dividing — mega is $ 10^{6} $, nano is $ 10^{-9} $ — because a prefix left in place is the most common single error in this whole chapter.\n\nAnd carry a rough anchor in your head: visible light sits near $ 5\\times10^{14} $ Hz and half a micrometre, FM radio near $ 100 $ MHz and a few metres. If an answer lands far from the anchor for its band, check it before you write it down.'),
            mcq('ch8-p14', 'A beam of light passes from vacuum into glass of refractive index $ 1.5 $. Compared with their values in vacuum,',
              ['the wavelength falls to two-thirds, the frequency does not change', 'the frequency falls to two-thirds, the wavelength does not change', 'both the wavelength and the frequency fall to two-thirds', 'neither changes, because only the direction of travel changes'],
              0,
              'The frequency is set by the **source** — by how fast the charges that made the wave are shaking. The glass cannot reach back and change that, so every crest that arrives at the surface must leave into the glass, and $ \\nu $ is the same on both sides.\n\nThe speed does drop, to $ v = \\frac{c}{n} = \\frac{c}{1.5} $. Since $ v = \\nu\\lambda $ with $ \\nu $ fixed, the wavelength must fall in the same proportion:\n\n$ \\lambda_{\\text{glass}} = \\frac{\\lambda_0}{1.5} = \\frac{2}{3}\\lambda_0 $\n\n**Why this matters beyond this chapter.** The colour you see is set by frequency, not wavelength, which is why red light under water is still red even though its wavelength there is shorter. Any time a question mixes media, write down which quantity is protected — it is always the frequency.'),
            mcq('ch8-p15', 'Maxwell evaluated $ \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}} $ and got a number equal to the measured speed of light. What made that the turning point it was?',
              ['both constants came from bench experiments with charges and currents', 'both constants had been fixed by timing light over a measured distance', 'the two constants were defined so the answer would come out right', 'the result matched the speed of sound, linking the two kinds of wave'],
              0,
              '$ \\varepsilon_0 $ enters physics through Coulomb\u2019s law — two charged spheres on a torsion balance. $ \\mu_0 $ enters through the force between two current-carrying wires. Both are tabletop electricity experiments, done in a room, with no light involved and nothing moving fast.\n\nSo when their combination produced $ 3\\times10^{8} $ m/s, there was no way to dismiss it as a coincidence of definitions. Light had been *derived* from electricity and magnetism, and the honest conclusion was that light **is** an electromagnetic wave.\n\nEvery later prediction of the chapter — radio waves, X-rays, the whole spectrum — follows from taking that conclusion seriously. Hertz produced radio waves in the laboratory about twenty-five years later and measured their speed: the same $ c $.'),
          ],
        },
        // ── 4 · Structure of the wave ───────────────────────────────────────
        {
          id: 'ch8-s4-structure',
          title: '4 · Structure of the wave',
          blurb: 'The picture, held exactly right. Most marks lost in this chapter are lost here, to a diagram remembered slightly wrong.',
          items: [
            mcq('ch8-p16', 'In a plane electromagnetic wave travelling through vacuum, the electric and magnetic fields are',
              ['in phase — both reach their peaks together', '$ 90^\\circ $ out of phase, with $ \\vec{B} $ behind $ \\vec{E} $', '$ 180^\\circ $ out of phase, so one peaks as the other dips', 'in no fixed phase relation — it depends on the source'],
              0,
              'This is the single most common wrong picture in the chapter, and it comes from an honest place: in an LC circuit the energy really does slosh back and forth between the electric and magnetic stores a quarter-cycle apart, so students carry that image across.\n\nA travelling wave is not an oscillating circuit. Write the two fields down:\n\n$ E = E_0\\sin(kz - \\omega t) \\qquad B = B_0\\sin(kz - \\omega t) $\n\nSame sine, same argument, no phase offset anywhere. Both fields are zero at the same points and both are largest at the same points.\n\n**Why it must be so.** Faraday\u2019s law ties $ \\frac{\\partial E}{\\partial z} $ to $ \\frac{\\partial B}{\\partial t} $. Feed in a $ \\vec{B} $ that lags by a quarter cycle and the two sides of that equation stop matching. Only the in-phase pair satisfies both Faraday and Ampere-Maxwell at once, so it is the only wave the equations permit.'),
            mcq('ch8-p17', 'For a plane electromagnetic wave in vacuum with peak fields $ E_0 $ and $ B_0 $,',
              ['$ E_0 = cB_0 $', '$ B_0 = cE_0 $', '$ E_0 = c^{2}B_0 $', '$ E_0B_0 = c $'],
              0,
              'The relation is $ \\frac{E_0}{B_0} = c $, which rearranges to $ E_0 = cB_0 $. Getting it upside down is easy to do under exam pressure and easy to prevent, in two ways.\n\n**By size.** $ c $ is about $ 3\\times10^{8} $, so the electric field number is always enormously larger than the magnetic one. A wave with $ E_0 = 30 $ V/m has $ B_0 = 10^{-7} $ T. Whichever way you write the relation, the answer must come out with a big $ E $ and a tiny $ B $.\n\n**By units.** $ \\frac{E}{B} $ has units of $ \\frac{\\text{V/m}}{\\text{T}} $, which reduces to metres per second. So $ \\frac{E}{B} $ is a speed, and the only speed available is $ c $.\n\nThat tiny $ B $ is also why the magnetic force on a charge in a light beam is negligible compared with the electric one — a fact you will use again in wave optics.'),
            num('ch8-p18', 'A plane electromagnetic wave in vacuum has a peak electric field of $ 30 $ V/m. Find (a) the peak magnetic field, (b) the rms electric field, and (c) the rms magnetic field.',
              '(a) $ 1.0\\times10^{-7} $ T  (b) $ 21 $ V/m  (c) $ 7.1\\times10^{-8} $ T',
              '**(a)** $ B_0 = \\frac{E_0}{c} = \\frac{30}{3.0\\times10^{8}} = 1.0\\times10^{-7} $ T\n\n**(b)** The fields vary sinusoidally, so the rms value is the peak over $ \\sqrt{2} $ — the same relation you used all through Chapter 7:\n\n$ E_{\\text{rms}} = \\frac{30}{\\sqrt{2}} = 21.2 \\approx 21 $ V/m\n\n**(c)** $ B_{\\text{rms}} = \\frac{1.0\\times10^{-7}}{\\sqrt{2}} = 7.1\\times10^{-8} $ T\n\n**Cross-check.** The ratio $ \\frac{E_{\\text{rms}}}{B_{\\text{rms}}} = \\frac{21.2}{7.1\\times10^{-8}} = 3.0\\times10^{8} $ m/s. Dividing both fields by the same $ \\sqrt{2} $ cannot change their ratio, so $ E/B = c $ holds for peak values, rms values and instantaneous values alike. If your two answers do not reproduce $ c $ when divided, one of them is wrong.\n\nNote also how small $ 10^{-7} $ T is — about a five-hundredth of the Earth\u2019s field. That is a perfectly ordinary light wave.'),
            mcq('ch8-p19', 'At one point in a plane electromagnetic wave, at one instant, $ \\vec{E} $ points along $ +\\hat{x} $ and $ \\vec{B} $ points along $ +\\hat{y} $. The wave is travelling along',
              ['$ +\\hat{z} $', '$ -\\hat{z} $', '$ +\\hat{y} $', '$ -\\hat{x} $'],
              0,
              'The direction of travel is the direction of $ \\vec{E}\\times\\vec{B} $ — in that order, never the other way round, since reversing a cross product reverses the answer.\n\n$ \\hat{x}\\times\\hat{y} = \\hat{z} $, so the wave moves along $ +\\hat{z} $.\n\n**How to do it with your hand.** Point your right fingers along $ \\vec{E} $, curl them towards $ \\vec{B} $, and your thumb points the way the wave goes. Practise it now, slowly, because in the exam you will do it in three seconds.\n\nThe rule is worth more than direction alone: $ \\vec{E}\\times\\vec{B} $ scaled by $ \\frac{1}{\\mu_0} $ is the Poynting vector, which points the way the **energy** flows. Direction of travel and direction of energy flow are the same thing here.'),
            mcq('ch8-p20', 'Electromagnetic waves are',
              ['transverse, and able to travel through empty space', 'longitudinal, and able to travel through empty space', 'transverse, but needing a material medium to travel', 'longitudinal, and needing a material medium to travel'],
              0,
              'Two independent facts, and the four choices are every combination of them.\n\n**Transverse:** $ \\vec{E} $ and $ \\vec{B} $ are both perpendicular to the direction of travel, so the oscillation is across the line of motion, not along it. This is what makes polarisation possible — a longitudinal wave cannot be polarised, and sound, which is longitudinal, never is.\n\n**No medium needed:** the wave is $ \\vec{E} $ and $ \\vec{B} $ regenerating each other through Faraday and Ampere-Maxwell, and neither of those laws mentions matter. Sunlight crossing $ 150 $ million kilometres of vacuum is the daily proof.\n\nThe nineteenth century found the second fact so uncomfortable that it invented a medium — the ether — for the wave to travel in. Michelson and Morley looked hard for it, found nothing, and it was quietly dropped.'),
            mcq('ch8-p21', 'A plane electromagnetic wave in vacuum has $ E_y = 50\\sin\\left(kz - 6\\pi\\times10^{8}t\\right) $ V/m, with $ t $ in seconds. Its wavelength is',
              ['$ 1.0 $ m', '$ 0.16 $ m', '$ 2.0 $ m', '$ 6.3 $ m'],
              0,
              'The bracket has the standard form $ (kz - \\omega t) $, so read off $ \\omega = 6\\pi\\times10^{8} $ rad/s. That is an **angular** frequency; convert it before using it.\n\n$ \\nu = \\frac{\\omega}{2\\pi} = \\frac{6\\pi\\times10^{8}}{2\\pi} = 3.0\\times10^{8} $ Hz\n\n$ \\lambda = \\frac{c}{\\nu} = \\frac{3.0\\times10^{8}}{3.0\\times10^{8}} = 1.0 $ m\n\nFeeding $ \\omega $ straight in where $ \\nu $ belongs gives $ 0.16 $ m — wrong by $ 2\\pi $, and the trap this item exists to spring.\n\n**A second route, which is faster once you trust it.** The same wave has $ k = \\frac{\\omega}{c} = 2\\pi $ rad/m, and $ \\lambda = \\frac{2\\pi}{k} = 1.0 $ m. Either way, decide first whether the number in front of you is $ \\omega $ or $ \\nu $, $ k $ or $ \\lambda $ — the arithmetic is trivial and the labelling is where the marks are.'),
          ],
        },
        // ── 5 · Energy, intensity and momentum ──────────────────────────────
        {
          id: 'ch8-s5-energy-momentum',
          title: '5 · Energy, intensity and momentum',
          blurb: 'Light carries energy, and it carries push. The factors of two and the inverse squares are where this section bites.',
          items: [
            mcq('ch8-p22', 'In a plane electromagnetic wave in vacuum, the average energy density stored in the electric field, compared with that stored in the magnetic field, is',
              ['exactly equal to it', 'larger by a factor of $ c $', 'smaller by a factor of $ c $', 'larger by a factor of $ c^{2} $'],
              0,
              'It looks as if the electric half must dominate, because $ E $ is about $ 10^{8} $ times bigger than $ B $. Do the algebra and the two constants undo it exactly.\n\n$ u_E = \\frac{1}{2}\\varepsilon_0E^{2} \\qquad u_B = \\frac{B^{2}}{2\\mu_0} $\n\nPut $ B = \\frac{E}{c} $ into the second one and use $ c^{2} = \\frac{1}{\\mu_0\\varepsilon_0} $:\n\n$ u_B = \\frac{E^{2}}{2\\mu_0c^{2}} = \\frac{E^{2}\\mu_0\\varepsilon_0}{2\\mu_0} = \\frac{1}{2}\\varepsilon_0E^{2} = u_E $\n\nEqual at every instant, not merely on average. So the total is $ u = \\varepsilon_0E^{2} $, and averaging the sine squared over a cycle gives the factor of a half:\n\n$ u_{\\text{avg}} = \\frac{1}{2}\\varepsilon_0E_0^{2} $\n\n**Keep both halves in mind.** The energy of light is not "mostly electric". The split is exactly even, and either half doubled gives the whole.'),
            num('ch8-p23', 'A plane electromagnetic wave in vacuum has a peak electric field of $ 48 $ V/m. Find (a) the peak magnetic field, (b) the average energy density, and (c) the intensity of the wave.',
              '(a) $ 1.6\\times10^{-7} $ T  (b) $ 1.0\\times10^{-8} $ J/m³  (c) $ 3.1 $ W/m²',
              '**(a)** $ B_0 = \\frac{E_0}{c} = \\frac{48}{3.0\\times10^{8}} = 1.6\\times10^{-7} $ T\n\n**(b)** $ u_{\\text{avg}} = \\frac{1}{2}\\varepsilon_0E_0^{2} = \\frac{1}{2}(8.85\\times10^{-12})(48)^{2} $\n\n$ = \\frac{1}{2}(8.85\\times10^{-12})(2304) = 1.0\\times10^{-8} $ J/m³\n\n**(c)** Intensity is energy crossing unit area per second. In one second the wave delivers everything sitting in a column of length $ c $, so\n\n$ I = u_{\\text{avg}}\\,c = (1.0\\times10^{-8})(3.0\\times10^{8}) = 3.1 $ W/m²\n\n**The idea behind (c) is worth more than the formula.** Intensity is always "energy density times the speed it moves at" — the same reasoning gives the flow rate of water in a pipe, or of cars past a point on a road. If you ever forget $ I = \\frac{1}{2}\\varepsilon_0E_0^{2}c $, rebuild it from that sentence in ten seconds.'),
            num('ch8-p24', 'A $ 100 $ W lamp radiates $ 5\\% $ of its power as visible light, spreading it equally in all directions. At a distance of $ 2.0 $ m from the lamp, find (a) the intensity, (b) the peak electric field, and (c) the peak magnetic field. Treat the lamp as a point source.',
              '(a) $ 0.10 $ W/m²  (b) $ 8.7 $ V/m  (c) $ 2.9\\times10^{-8} $ T',
              '**(a)** Radiated visible power is $ P = 0.05\\times100 = 5.0 $ W, spread over a sphere of radius $ 2.0 $ m:\n\n$ I = \\frac{P}{4\\pi r^{2}} = \\frac{5.0}{4\\pi(2.0)^{2}} = \\frac{5.0}{50.3} = 0.099 \\approx 0.10 $ W/m²\n\n**(b)** Turn intensity back into a field with $ I = \\frac{1}{2}\\varepsilon_0E_0^{2}c $:\n\n$ E_0 = \\sqrt{\\frac{2I}{\\varepsilon_0 c}} = \\sqrt{\\frac{2(0.099)}{(8.85\\times10^{-12})(3.0\\times10^{8})}} = \\sqrt{\\frac{0.199}{2.66\\times10^{-3}}} = \\sqrt{75} = 8.7 $ V/m\n\n**(c)** $ B_0 = \\frac{E_0}{c} = \\frac{8.7}{3.0\\times10^{8}} = 2.9\\times10^{-8} $ T\n\n**Where the inverse square comes from.** The lamp pushes out the same $ 5 $ W every second whatever you do; that energy has to cross a sphere whose area is $ 4\\pi r^{2} $. Double the distance and the sphere is four times as big, so the intensity is a quarter. Triple it and the intensity is a ninth.\n\nAnd note how the fields respond: $ I \\propto E_0^{2} $, so $ E_0 $ falls only as $ \\frac{1}{r} $, not as $ \\frac{1}{r^{2}} $. Moving twice as far away quarters the intensity but merely halves the field.'),
            mcq('ch8-p25', 'A beam of intensity $ I $ falls perpendicularly on a flat surface. The radiation pressure on the surface is',
              ['$ \\frac{I}{c} $ when absorbed and $ \\frac{2I}{c} $ when reflected', '$ \\frac{2I}{c} $ when absorbed and $ \\frac{I}{c} $ when reflected', '$ \\frac{I}{c} $ whether the beam is absorbed or reflected', '$ \\frac{I}{c^{2}} $ when absorbed and $ \\frac{2I}{c^{2}} $ when reflected'],
              0,
              'Start from $ p = \\frac{U}{c} $: energy $ U $ arriving carries momentum $ \\frac{U}{c} $ with it.\n\n**Absorbed.** The light stops dead, so all of its momentum is handed over. Per second, per unit area, that is $ \\frac{I}{c} $ — and force per unit area is pressure.\n\n**Reflected.** The light arrives with momentum $ +p $ and leaves with $ -p $. The change is $ 2p $, so the surface receives twice as much push: $ \\frac{2I}{c} $.\n\nThis is the same factor of two you met when a ball bounces off a wall instead of sticking to it, and forgetting it is the standard error here. The version with $ c^{2} $ in the denominator can be dismissed on units alone — $ \\frac{I}{c} $ already has the units of pressure.\n\n**A design consequence.** A solar sail is made shiny rather than black precisely to collect the factor of two.'),
            num('ch8-p26', 'A perfectly absorbing black panel of area $ 1.5 $ m² is held facing the Sun, where the intensity of sunlight is $ 1.4 $ kW/m². Find (a) the energy it absorbs in one minute, (b) the momentum delivered to it in that minute, and (c) the average force the sunlight exerts on it.',
              '(a) $ 1.26\\times10^{5} $ J  (b) $ 4.2\\times10^{-4} $ kg·m/s  (c) $ 7.0\\times10^{-6} $ N',
              '**(a)** $ U = IAt = (1400)(1.5)(60) = 1.26\\times10^{5} $ J\n\n**(b)** $ p = \\frac{U}{c} = \\frac{1.26\\times10^{5}}{3.0\\times10^{8}} = 4.2\\times10^{-4} $ kg·m/s\n\n**(c)** Force is momentum delivered per second:\n\n$ F = \\frac{p}{t} = \\frac{4.2\\times10^{-4}}{60} = 7.0\\times10^{-6} $ N\n\n**Check it a second way**, since the whole calculation collapses to one line:\n\n$ F = \\frac{IA}{c} = \\frac{(1400)(1.5)}{3.0\\times10^{8}} = 7.0\\times10^{-6} $ N\n\n**What the number means.** Seven micronewtons — the weight of a grain of sand, on a panel a metre and a half across, from full sunlight. That is why nothing on Earth is ever visibly pushed by light.\n\nBut in space there is nothing else pushing. Keep that force on for a month and a light spacecraft picks up a real speed, for no fuel at all — the solar sail. The same feeble pressure, acting on the dust released by a comet, is what makes a comet\u2019s tail point away from the Sun no matter which way the comet is heading.'),
          ],
        },
        // ── 6 · Sources, antennas and the spectrum ──────────────────────────
        {
          id: 'ch8-s6-spectrum',
          title: '6 · Sources, antennas and the spectrum',
          blurb: 'Where waves come from, how we catch them, and the one ordered list you must be able to write from memory.',
          items: [
            mcq('ch8-p27', 'Electromagnetic waves are radiated by',
              ['a charge that is accelerating', 'a charge at rest in a strong field', 'a charge moving at constant velocity', 'any charge, whatever it happens to be doing'],
              0,
              'Take the three cases in turn.\n\nA **stationary** charge has a steady electric field and no magnetic field at all. Nothing changes, so nothing propagates.\n\nA charge at **constant velocity** has both fields, but ride alongside it and everything looks static again — you are back to the first case. A situation that is steady in some frame cannot radiate.\n\nAn **accelerating** charge has a field that genuinely changes with time, and no change of frame can undo it. The changing $ \\vec{E} $ makes a $ \\vec{B} $, that changing $ \\vec{B} $ makes an $ \\vec{E} $, and the disturbance walks away from the charge at $ c $.\n\nThis is the single sentence the whole of source physics rests on. An oscillating charge is accelerating all the time, which is why an alternating current in a wire radiates — and radiates at exactly the frequency at which it oscillates.'),
            num('ch8-p28', 'A transmitter is to broadcast at $ 60 $ MHz using a half-wave dipole antenna. What length should the antenna be?',
              '$ 2.5 $ m',
              'Find the wavelength first:\n\n$ \\lambda = \\frac{c}{\\nu} = \\frac{3.0\\times10^{8}}{60\\times10^{6}} = 5.0 $ m\n\nA half-wave dipole is $ \\frac{\\lambda}{2} $ long, so the antenna is $ 2.5 $ m.\n\n**Why the length is tied to the wavelength at all.** The antenna is a resonator for charge, exactly as an organ pipe is for air. Current must be zero at the two open ends and largest in the middle, and the shortest oscillation that fits that pattern has the rod half a wavelength long. Cut it much shorter and the charge is being driven far off resonance, so almost nothing radiates.\n\n**Sanity check against things you own.** Your phone works near $ 1 $ GHz, so $ \\lambda \\approx 0.3 $ m and the antenna inside is a few centimetres — it fits. An AM station at $ 1 $ MHz has $ \\lambda = 300 $ m, and its antenna is the whole steel mast you see from the road.'),
            mcq('ch8-p29', 'Arranged from the longest wavelength to the shortest, the correct order is',
              ['radio, microwave, infrared, visible, ultraviolet, X-ray', 'radio, microwave, ultraviolet, visible, infrared, X-ray', 'X-ray, ultraviolet, visible, infrared, microwave, radio', 'microwave, radio, infrared, visible, X-ray, ultraviolet'],
              0,
              'Learn the list in one direction only and derive the other two, or you will scramble them under pressure. The direction to fix is **increasing frequency**:\n\nradio $ \\to $ microwave $ \\to $ infrared $ \\to $ visible $ \\to $ ultraviolet $ \\to $ X-ray $ \\to $ gamma\n\nNow read off whatever you were asked for. Photon energy is $ E = h\\nu $, so energy runs the **same** way as frequency. Wavelength is $ \\lambda = \\frac{c}{\\nu} $, so wavelength runs the **opposite** way — longest at radio, shortest at gamma. This question asked for longest first, so the list is exactly the sequence above, read from the left.\n\nThe fully reversed list is the answer to a different question — order by frequency or by photon energy — and choosing it is the standard way to lose this mark. Read the first six words of the question twice.\n\nAn anchor for the middle: visible light runs from about $ 400 $ nm (violet) to about $ 700 $ nm (red). Infrared sits just beyond the red end, ultraviolet just beyond the violet. The names say it: *infra* is below, *ultra* is beyond.'),
            mcq('ch8-p30', 'The ozone layer in the stratosphere protects life at the surface mainly by absorbing',
              ['ultraviolet radiation, which would otherwise damage DNA', 'infrared radiation, which would otherwise overheat the air', 'microwave radiation, which would otherwise cook living tissue', 'radio waves, which would otherwise swamp all communication'],
              0,
              'Ozone absorbs strongly in the ultraviolet, and ultraviolet photons are energetic enough to break chemical bonds — including bonds in DNA, which is why unfiltered UV causes sunburn, cataracts and skin cancer.\n\nUse the photon-energy ordering from the previous item to see why it must be UV rather than anything on the long-wavelength side. Radio, microwave and infrared photons all carry **less** energy than visible light, and visible light lands on your skin all day without breaking anything. Only the bands beyond violet are dangerous in this way.\n\nThe layer is thin — compressed to sea-level pressure it would be a few millimetres thick — which is why chlorofluorocarbon damage to it in the 1980s was treated as an emergency, and why the international ban on those chemicals is the most successful environmental agreement so far written.'),
            mcq('ch8-p31', 'The greenhouse effect that keeps the Earth habitable works because carbon dioxide and water vapour in the atmosphere',
              ['let visible light in but absorb the infrared going back out', 'let infrared in but absorb the visible light going back out', 'reflect incoming ultraviolet back into space before it lands', 'absorb visible light and re-emit it as ultraviolet radiation'],
              0,
              'Follow the energy in two stages.\n\n**Coming in,** sunlight peaks in the visible, and the atmosphere is largely transparent to visible light. It reaches the ground and warms it.\n\n**Going out,** the ground is at about $ 300 $ K, far cooler than the Sun, so it radiates in the **infrared** rather than the visible. Carbon dioxide and water vapour absorb infrared strongly, so much of that outgoing energy is caught and re-radiated, partly back downward.\n\nThe atmosphere is therefore a one-way door: easy to enter as visible light, hard to leave as infrared. The surface must warm until enough infrared forces its way out to balance the incoming sunlight, and that balance point is about $ 33 $ °C warmer than it would be with no atmosphere at all.\n\nThe effect is not a fault — without it the Earth would be frozen. The concern is entirely about **strengthening** it by adding more absorber.'),
          ],
        },
      ],
    }),
    b('text', 2, {
      markdown: 'That is Chapter 8, and with it the whole electromagnetism block.\n\nLook back at the distance covered. Chapter 1 began with a rubbed balloon picking up a scrap of paper, and a law about the force between two charges. Chapter 4 said magnets always come with two poles. Chapter 6 found that a changing magnetic field pushes a current round a loop. Chapter 5 said a current makes a magnetic field — and this chapter found that statement incomplete, patched it with a term nobody had measured, and discovered that the four repaired equations describe something travelling through empty space at $ 3\\times10^{8} $ m/s.\n\nThat something is the light you are reading this by. The same physics is the radio in the next room, the X-ray plate at the hospital, the warmth on your face from a heater, and the ultraviolet the ozone layer is holding off your skin — one phenomenon, one set of four equations, wearing different wavelengths.\n\nNothing else in school physics closes a loop that wide. When you sit down to revise, do not revise eight separate chapters. Revise one argument told in eight parts.',
    }),
  ],
};

async function main() {
  await withDb(async (db) => {
    const bookId = await ensureBookAndChapter(db, CH);
    await upsertPages(db, bookId, CH, [p10]);
  });
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
