'use strict';
/**
 * Class 12 Physics · Ch.7 "Alternating Current" — page 14, Practice & Mastery.
 *
 * Every item carries source 'mcq' (no badge). Nothing here is attributed to a
 * third-party reference book (standing no-third-party-attribution rule), and
 * nothing is badged 'ncert_exemplar' because none of it was transcribed from
 * the Exemplar — inventing that badge would be a false provenance claim.
 * The genuine NCERT end-of-chapter exercises are page 15, built separately.
 *
 * Run: node scripts/physics12-book/build_ch7_d_practice.js
 */
const { b, mcq, num, ensureBookAndChapter, upsertPages, withDb } = require('./_book');

const CH = 7;

const p14 = {
  page_number: 14,
  slug: 'ac-practice-and-mastery',
  title: 'Practice & Mastery',
  subtitle: 'Seven sections, thirty-eight problems — commit to an answer before you look',
  page_type: 'lesson',
  blocks: [
    b('callout', 0, {
      variant: 'fun_fact',
      markdown: 'How to use this page.\n\nAlternating current is the chapter where a formula you half-remember will still give you a number, and the number will be wrong. Peak instead of rms. Reactances added instead of subtracted. A power factor quietly assumed to be one. None of those announce themselves — they just cost you the mark.\n\nSo for each item, do it in this order. Write down which quantity the question is actually asking for (peak? rms? average?). Do the working on paper. Commit to the number. **Only then** open the solution. If you were right for the wrong reason, the explanation is written to catch you.',
    }),
    b('practice_bank', 1, {
      title: 'Alternating Current — the full set',
      intro: 'The sections follow the chapter in order, from the free LC oscillation through to the transformer. Numerical items ask you to produce the answer yourself; in the multiple-choice items every wrong option is a mistake somebody actually makes, so read all four before choosing.',
      sections: [
        // ── 1 · LC oscillations ──────────────────────────────────────────────
        {
          id: 'ch7-s1-lc',
          title: '1 · LC oscillations',
          blurb: 'No source, no resistance — just energy sloshing between a capacitor and a coil. Get this picture right and resonance later is free.',
          items: [
            mcq('ch7-p01', 'A capacitor of $ 50\\ \\mu $F is given a charge and then connected across an inductor of $ 20 $ mH with negligible resistance. The angular frequency of the oscillation that follows is',
              ['$ 1.0\\times10^{3} $ rad/s', '$ 1.0\\times10^{6} $ rad/s', '$ 1.6\\times10^{2} $ rad/s', '$ 1.0\\times10^{-3} $ rad/s'],
              0,
              'Use $ \\omega = \\frac{1}{\\sqrt{LC}} $, and convert both prefixes before you touch it.\n\n$ LC = (20\\times10^{-3})(50\\times10^{-6}) = 1.0\\times10^{-6} $\n\n$ \\sqrt{LC} = 1.0\\times10^{-3} $, so $ \\omega = 1.0\\times10^{3} $ rad/s.\n\nTwo traps are built into the numbers. Skipping the square root gives $ 1.0\\times10^{6} $ rad/s — a thousand times too big. And $ 1.6\\times10^{2} $ is the **frequency** $ f = \\frac{\\omega}{2\\pi} = 159 $ Hz, which is a perfectly good number wearing the wrong label. Whenever a question says "angular frequency", the answer is in radians per second and there is no $ 2\\pi $ left over.'),
            mcq('ch7-p02', 'In a freely oscillating LC circuit, all of the energy is magnetic at the instant when',
              ['the capacitor charge is zero and the current is largest', 'the capacitor charge is largest and the current is zero', 'the charge and the current are both at their largest', 'the charge and the current are both exactly half of peak'],
              0,
              'The energy sits in two places: $ \\frac{q^{2}}{2C} $ on the capacitor and $ \\frac{1}{2}Li^{2} $ in the coil. Their sum is fixed, so when one is at its maximum the other must be zero.\n\nAll-magnetic therefore means the capacitor is holding nothing, $ q = 0 $, and every bit of the energy has become current: $ i $ is at its peak.\n\nThe pendulum is the same story. All the energy is kinetic exactly when the bob is passing through the lowest point — the point where its displacement is zero. Charge is the displacement here; current is the speed.'),
            num('ch7-p03', 'A $ 25\\ \\mu $F capacitor is charged to $ 100 $ V and then connected across a $ 10 $ mH inductor of negligible resistance. Find (a) the total energy in the circuit, (b) the maximum current, and (c) the time from the moment of connection until the current first reaches that maximum.',
              '(a) $ 0.125 $ J  (b) $ 5.0 $ A  (c) $ 7.9\\times10^{-4} $ s, about $ 0.79 $ ms',
              '**(a)** At the start the capacitor holds everything:\n\n$ U = \\frac{1}{2}CV^{2} = \\frac{1}{2}(25\\times10^{-6})(100)^{2} = 0.125 $ J\n\n**(b)** When the current is at its maximum the capacitor is empty, so the whole $ 0.125 $ J is magnetic:\n\n$ \\frac{1}{2}Li_{\\max}^{2} = 0.125 \\quad\\Rightarrow\\quad i_{\\max} = \\sqrt{\\frac{2(0.125)}{0.010}} = \\sqrt{25} = 5.0 $ A\n\n**(c)** The current goes from zero to its peak in a quarter of a cycle.\n\n$ \\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{(0.010)(25\\times10^{-6})}} = \\frac{1}{5.0\\times10^{-4}} = 2000 $ rad/s\n\n$ T = \\frac{2\\pi}{\\omega} = 3.14\\times10^{-3} $ s, so $ \\frac{T}{4} = 7.9\\times10^{-4} $ s.\n\n**Cross-check worth doing every time.** The peak current should also equal $ q_0\\omega $, where $ q_0 = CV = 2.5\\times10^{-3} $ C. That gives $ (2.5\\times10^{-3})(2000) = 5.0 $ A — the same answer by a different route, which is the cheapest confidence you can buy in an exam.'),
            mcq('ch7-p04', 'In the exact analogy between an LC circuit and a mass on a spring, the inductance $ L $ plays the part of',
              ['the mass $ m $, since $ \\frac{1}{2}Li^{2} $ matches $ \\frac{1}{2}mv^{2} $', 'the spring constant $ k $, since $ L $ stores energy', 'the amplitude, since $ L $ sets how large the current gets', 'the damping, since $ L $ makes the oscillation die away'],
              0,
              'Line the two energy expressions up and the whole dictionary falls out.\n\nCharge $ q $ behaves like displacement $ x $; current $ i = \\frac{dq}{dt} $ behaves like velocity $ v $. Then $ \\frac{1}{2}Li^{2} $ sits exactly where $ \\frac{1}{2}mv^{2} $ sits, so $ L $ is the mass — the thing that resists a change of rate. And $ \\frac{q^{2}}{2C} $ sits where $ \\frac{1}{2}kx^{2} $ sits, so it is $ \\frac{1}{C} $, not $ C $, that plays the spring constant.\n\nThe frequencies then match term for term: $ \\omega = \\sqrt{\\frac{k}{m}} $ becomes $ \\omega = \\sqrt{\\frac{1/C}{L}} = \\frac{1}{\\sqrt{LC}} $.\n\nDamping has no counterpart in an ideal LC circuit at all — that role belongs to resistance, which is why an ideal LC ring never stops.'),
            mcq('ch7-p05', 'A real LC circuit rings for a while and then goes quiet. The energy has gone',
              ['into heat in the resistance every real wire and coil has', 'into the capacitor, which keeps the last of the charge', 'nowhere — the oscillation only looks smaller on the meter', 'into the inductor, whose magnetic field holds it for ever'],
              0,
              'The ideal circuit in the formula has no resistance, so nothing removes energy and the oscillation would last for ever. A real one is made of copper, and copper has resistance. Every half-cycle of current dumps a little $ i^{2}R $ into the wire as heat, so the amplitude shrinks cycle by cycle — a damped oscillation, exactly like a real pendulum slowing in air.\n\nA second, smaller drain is worth knowing about because Chapter 8 is built on it: an oscillating current radiates electromagnetic waves. At $ 1000 $ rad/s the amount is negligible, but crank the frequency up into the megahertz and that "loss" becomes the whole point — it is how a radio transmitter works.\n\nThe two suggestions about energy being kept by the capacitor or the coil both miss that neither component can hold anything once the current has stopped: their stores are $ \\frac{q^{2}}{2C} $ and $ \\frac{1}{2}Li^{2} $, and both are zero when everything is at rest.'),
          ],
        },
        // ── 2 · RMS, peak and average ────────────────────────────────────────
        {
          id: 'ch7-s2-rms',
          title: '2 · RMS, peak and average',
          blurb: 'One question decides most of these: is the number in front of me a peak, an rms value, or an average? Label it before you use it.',
          items: [
            num('ch7-p06', 'The mains supply is quoted as $ 220 $ V at $ 50 $ Hz. Find (a) the peak voltage, (b) the peak-to-peak voltage, and (c) the time between one peak and the next.',
              '(a) $ 311 $ V  (b) $ 622 $ V  (c) $ 0.020 $ s',
              'The quoted $ 220 $ V is an **rms** value — that is the convention for every mains figure in the world.\n\n**(a)** $ V_0 = \\sqrt{2}\\,V_{rms} = 1.414 \\times 220 = 311 $ V\n\n**(b)** The voltage swings from $ +311 $ V to $ -311 $ V, so peak-to-peak is $ 622 $ V.\n\n**(c)** One peak to the next is one full period: $ T = \\frac{1}{f} = \\frac{1}{50} = 0.020 $ s, i.e. $ 20 $ ms.\n\n**Why this matters beyond the marks.** Insulation and capacitors in a mains circuit must survive $ 311 $ V, not $ 220 $ V — and a capacitor rated at exactly $ 220 $ V will fail. The rms value tells you about heating; the peak value tells you about breakdown. They are different questions and they need different numbers.'),
            mcq('ch7-p07', 'An AC ammeter in a circuit reads $ 5.0 $ A. The peak value of the current in that circuit is',
              ['$ 7.1 $ A', '$ 5.0 $ A', '$ 3.5 $ A', '$ 10.0 $ A'],
              0,
              'An AC meter is built to read the **rms** value, because that is the number that predicts heating. So the reading of $ 5.0 $ A is $ I_{rms} $, and\n\n$ I_0 = \\sqrt{2}\\,I_{rms} = 1.414 \\times 5.0 = 7.1 $ A\n\nDividing by $ \\sqrt{2} $ instead gives $ 3.5 $ A, which is the same slip run backwards. Fix the direction once and for all: the peak is always the **bigger** of the two, so $ \\sqrt{2} $ multiplies when you go rms $ \\rightarrow $ peak and divides when you go the other way. If your answer came out smaller than the meter reading, you have gone the wrong way.'),
            mcq('ch7-p08', 'Averaged over one complete cycle, the quantity $ \\sin^{2}\\omega t $ has the value',
              ['$ \\frac{1}{2} $', '$ 0 $', '$ \\frac{1}{\\sqrt{2}} $', '$ 1 $'],
              0,
              'The mean of $ \\sin\\omega t $ over a full cycle really is zero — the positive half exactly cancels the negative half. But squaring kills every minus sign, so $ \\sin^{2}\\omega t $ is never negative and its mean cannot be zero.\n\nThe clean way to see the value: $ \\sin^{2}\\theta + \\cos^{2}\\theta = 1 $ always, and over a full cycle the two have the same average by symmetry. So each must average $ \\frac{1}{2} $.\n\n(The identity $ \\sin^{2}\\theta = \\frac{1 - \\cos 2\\theta}{2} $ says the same thing: a constant $ \\frac{1}{2} $ with a cosine wobble on top, and the wobble averages away.)\n\nThis one number is the whole origin of rms. $ \\overline{i^{2}} = I_0^{2}\\times\\frac{1}{2} $, so $ I_{rms} = \\sqrt{\\overline{i^{2}}} = \\frac{I_0}{\\sqrt{2}} $. The $ \\frac{1}{\\sqrt{2}} $ is a consequence, not a definition — which is why it holds for a sine wave and for nothing else.'),
            num('ch7-p09', 'An alternating current is described by $ i = 4.0\\sin(100\\pi t) $ amperes, with $ t $ in seconds. Find (a) the peak current, (b) the rms current, (c) the frequency, and (d) the current at $ t = \\frac{1}{600} $ s.',
              '(a) $ 4.0 $ A  (b) $ 2.8 $ A  (c) $ 50 $ Hz  (d) $ 2.0 $ A',
              'Read the standard form $ i = I_0\\sin\\omega t $ straight off the expression.\n\n**(a)** $ I_0 = 4.0 $ A — the number sitting in front of the sine.\n\n**(b)** $ I_{rms} = \\frac{I_0}{\\sqrt{2}} = \\frac{4.0}{1.414} = 2.8 $ A\n\n**(c)** $ \\omega = 100\\pi $ rad/s, so $ f = \\frac{\\omega}{2\\pi} = \\frac{100\\pi}{2\\pi} = 50 $ Hz.\n\n**(d)** Put the time in and work in radians:\n\n$ 100\\pi \\times \\frac{1}{600} = \\frac{\\pi}{6} $, and $ \\sin\\frac{\\pi}{6} = 0.5 $, so $ i = 4.0 \\times 0.5 = 2.0 $ A\n\nNotice that (a), (b) and (d) are three different currents in the same circuit at the same moment in the chapter — peak, rms and instantaneous. Any question that just says "the current" without saying which one is a question you should re-read.'),
            mcq('ch7-p10', 'The average of an alternating current over a full cycle is zero, and yet the current still heats a resistor. The reason is that',
              ['the heating rate goes as $ i^{2} $, which is never negative', 'the heating rate goes as $ i $, and heat can never be negative', 'only the positive half of the cycle passes through the resistor', 'the negative half of the cycle cools the resistor back down'],
              0,
              'Power in a resistor is $ P = i^{2}R $. Square any number, positive or negative, and you get something positive — so the resistor is being heated during **both** halves of the cycle, and the two halves add rather than cancel.\n\nThe current itself does average to zero, and that is not a contradiction. It just means no net charge is transported over a cycle. Heating does not care which way the charge went, only how much of it went and how fast.\n\nThe suggestion that only the positive half gets through describes a rectifier, not a plain resistor — a resistor conducts equally well in both directions. And nothing anywhere cools a resistor by driving current through it.'),
          ],
        },
        // ── 3 · Single elements ─────────────────────────────────────────────
        {
          id: 'ch7-s3-single',
          title: '3 · One element at a time',
          blurb: 'Before the three-element circuit, be certain of each element alone: what it opposes, by how much, and who is ahead of whom.',
          items: [
            num('ch7-p11', 'A pure inductor of $ 80 $ mH is connected across a $ 220 $ V, $ 50 $ Hz supply. Find (a) its reactance and (b) the rms current. Then say how both would change if the supply frequency rose to $ 500 $ Hz.',
              '(a) $ X_L = 25.1\\ \\Omega $  (b) $ I_{rms} = 8.8 $ A. At $ 500 $ Hz: $ X_L = 251\\ \\Omega $ and the current falls to $ 0.88 $ A.',
              '**(a)** $ X_L = \\omega L = 2\\pi f L = 2\\pi(50)(0.080) = 314 \\times 0.080 = 25.1\\ \\Omega $\n\n**(b)** Ohm-style, with reactance in place of resistance:\n\n$ I_{rms} = \\frac{V_{rms}}{X_L} = \\frac{220}{25.1} = 8.8 $ A\n\n**At ten times the frequency:** $ X_L $ is proportional to $ f $, so it becomes $ 251\\ \\Omega $ and the current drops by the same factor of ten, to $ 0.88 $ A.\n\nThat is the sentence to store: **an inductor blocks high frequencies and passes low ones.** It fights any change in current, and a high frequency is nothing but rapid change. To a steady DC supply the same coil is just a piece of wire.'),
            num('ch7-p12', 'A $ 20\\ \\mu $F capacitor is connected across the same $ 220 $ V, $ 50 $ Hz supply. Find (a) its reactance and (b) the rms current. Then say what each becomes if the supply is replaced by a $ 220 $ V battery.',
              '(a) $ X_C = 159\\ \\Omega $  (b) $ I_{rms} = 1.4 $ A. On DC, $ X_C $ is infinite and the steady current is zero.',
              '**(a)** $ X_C = \\frac{1}{\\omega C} = \\frac{1}{2\\pi f C} = \\frac{1}{2\\pi(50)(20\\times10^{-6})} = \\frac{1}{6.28\\times10^{-3}} = 159\\ \\Omega $\n\n**(b)** $ I_{rms} = \\frac{V_{rms}}{X_C} = \\frac{220}{159} = 1.4 $ A\n\n**On a battery** the frequency is zero, so $ X_C = \\frac{1}{\\omega C} \\rightarrow \\infty $. A brief current flows while the capacitor charges up, and then nothing: **a capacitor blocks DC.**\n\nSet this beside the inductor in the previous item and you have the pair of opposites the rest of the chapter is built on. The inductor blocks high frequency and passes DC; the capacitor blocks DC and passes high frequency. That single contrast is what makes filters, tuners and the LCR circuit interesting.'),
            mcq('ch7-p13', 'In a circuit containing only a pure inductor across an AC source,',
              ['the current lags the voltage by $ \\frac{\\pi}{2} $', 'the current leads the voltage by $ \\frac{\\pi}{2} $', 'the current and the voltage stay exactly in phase', 'the current lags the voltage by $ \\pi $'],
              0,
              'The inductor obeys $ v = L\\frac{di}{dt} $. Feed it a sinusoidal current $ i = I_0\\sin\\omega t $ and the voltage comes out as $ \\omega L I_0\\cos\\omega t $ — a cosine where the current is a sine, so the voltage is a quarter of a cycle **ahead**. Equivalently the current is a quarter cycle behind: it **lags** by $ \\frac{\\pi}{2} $.\n\nThe physical reason is worth more than the algebra. The inductor resists change, so the current cannot respond to the applied voltage immediately — it is always playing catch-up.\n\nA capacitor does the mirror image, with the current leading by $ \\frac{\\pi}{2} $. The classroom mnemonic **CIVIL** packs both in: in a **C**, **I** comes before **V**; in an **L**, **V** comes before **I**.'),
            mcq('ch7-p14', 'The frequency of the source across a pure capacitor is doubled, with the peak voltage kept the same. The peak current',
              ['doubles, because $ X_C $ is halved', 'halves, because $ X_C $ is doubled', 'stays the same, because $ C $ has not changed', 'becomes four times larger'],
              0,
              '$ X_C = \\frac{1}{\\omega C} $, so doubling $ \\omega $ **halves** the reactance. With the same voltage across half the opposition, the current doubles.\n\nThe inverse relationship is the thing to hold on to, because it is the opposite way round to the inductor and the two get swapped constantly. A quick physical check: a higher frequency means the capacitor is charged and discharged more often per second, so more charge moves per second — and charge per second is current.\n\nThe idea that nothing changes because $ C $ is unchanged confuses the **component** with the **opposition it offers**. Capacitance is a fixed property of the plates; reactance depends on how fast you drive them.'),
            mcq('ch7-p15', 'Over one full cycle, the average power drawn by a pure inductor from an AC source is',
              ['zero — it gives back each cycle exactly what it took', 'equal to $ I_{rms}^{2}X_L $, which the coil turns to heat', 'equal to $ V_{rms}I_{rms} $, exactly as for a resistor', 'half of $ V_{rms}I_{rms} $, since only half a cycle counts'],
              0,
              'With the current lagging by $ \\frac{\\pi}{2} $, the instantaneous power $ p = vi $ is positive for a quarter cycle and negative for the next quarter. Positive means the inductor is taking energy from the source and storing it in its magnetic field; negative means it is pushing that energy straight back out. Over a whole cycle the two cancel exactly.\n\nThe formal statement is $ P = V_{rms}I_{rms}\\cos\\phi $ with $ \\phi = 90^{\\circ} $, and $ \\cos 90^{\\circ} = 0 $.\n\n**This is not a paradox and it is not a claim that nothing is happening.** Real current is flowing, the wires do carry it, and a meter reads it. It simply never converts to heat, because an ideal inductor has no resistance to convert it in. A real coil does have some resistance, and that part — and only that part — gets warm.\n\nWriting $ I_{rms}^{2}X_L $ is the commonest slip here: reactance is not resistance, and only resistance dissipates.'),
          ],
        },
        // ── 4 · Impedance and the series LCR circuit ────────────────────────
        {
          id: 'ch7-s4-lcr',
          title: '4 · Impedance and the series LCR circuit',
          blurb: 'Three oppositions, and you are not allowed to add them. Draw the triangle every single time until you no longer need to.',
          items: [
            num('ch7-p16', 'A series LCR circuit has $ R = 30\\ \\Omega $, $ X_L = 60\\ \\Omega $ and $ X_C = 20\\ \\Omega $, fed from a $ 200 $ V rms source. Find (a) the impedance, (b) the rms current, (c) the phase angle, and say whether the current leads or lags the voltage.',
              '(a) $ Z = 50\\ \\Omega $  (b) $ I_{rms} = 4.0 $ A  (c) $ \\phi = 53^{\\circ} $, with the current lagging',
              '**(a)** The two reactances act in opposite directions, so they subtract before anything else happens:\n\n$ X_L - X_C = 60 - 20 = 40\\ \\Omega $\n\n$ Z = \\sqrt{R^{2} + (X_L - X_C)^{2}} = \\sqrt{30^{2} + 40^{2}} = \\sqrt{2500} = 50\\ \\Omega $\n\n**(b)** $ I_{rms} = \\frac{V_{rms}}{Z} = \\frac{200}{50} = 4.0 $ A\n\n**(c)** $ \\tan\\phi = \\frac{X_L - X_C}{R} = \\frac{40}{30} = 1.33 $, so $ \\phi = 53^{\\circ} $.\n\nBecause $ X_L $ is the larger reactance the circuit is **inductive**, and in an inductive circuit the current lags the voltage — here by $ 53^{\\circ} $.\n\n**The picture behind the formula.** Put $ R $ along one axis and $ (X_L - X_C) $ at right angles to it; $ Z $ is the hypotenuse and $ \\phi $ is the angle at the corner. They are perpendicular because the voltage across $ R $ is in phase with the current while the reactive voltages are a quarter cycle away from it. That is why they combine by Pythagoras and not by addition.'),
            mcq('ch7-p17', 'A series LCR circuit has $ R = 8\\ \\Omega $, $ X_L = 12\\ \\Omega $ and $ X_C = 6\\ \\Omega $. Its impedance is',
              ['$ 10\\ \\Omega $', '$ 26\\ \\Omega $', '$ 19.7\\ \\Omega $', '$ 6\\ \\Omega $'],
              0,
              'Subtract the reactances, then use Pythagoras:\n\n$ X_L - X_C = 12 - 6 = 6\\ \\Omega $, so $ Z = \\sqrt{8^{2} + 6^{2}} = \\sqrt{100} = 10\\ \\Omega $\n\nThe three wrong values are the three ways this goes wrong. Adding all three straight ($ 8 + 12 + 6 $) gives $ 26\\ \\Omega $ and treats impedance like series resistance. Adding the reactances instead of subtracting, $ \\sqrt{8^{2} + 18^{2}} $, gives $ 19.7\\ \\Omega $. Using only $ X_L - X_C $ and forgetting the resistor gives $ 6\\ \\Omega $.\n\nA useful sanity rule: $ Z $ can never be smaller than $ R $, and it can never be as large as the plain sum of the three. If your answer falls outside that window, you have already made the mistake.'),
            mcq('ch7-p18', 'In a series LCR circuit the current is found to **lead** the applied voltage. It follows that',
              ['$ X_C > X_L $, and the circuit behaves capacitively', '$ X_L > X_C $, and the circuit behaves inductively', '$ X_L = X_C $, and the circuit is exactly at resonance', '$ R $ is larger than both reactances put together'],
              0,
              'The phase angle is set by $ \\tan\\phi = \\frac{X_L - X_C}{R} $, and it is the **sign** of the top line that decides who is ahead.\n\nA leading current is the capacitor winning, so $ X_C $ must be the bigger reactance and $ \\phi $ comes out negative. The circuit as a whole then behaves like a capacitor with some resistance, whatever components are physically in it.\n\nThat last clause is the real content. A circuit does not "look inductive" because it contains an inductor — it contains both. Which one wins depends on the frequency, and the same circuit will look inductive above resonance and capacitive below it.\n\nEqual reactances would be resonance, where the current is exactly in phase with the voltage and neither leads.'),
            num('ch7-p19', 'A series LCR circuit is fed from an AC source. A voltmeter reads $ 60 $ V across the resistor, $ 130 $ V across the inductor and $ 50 $ V across the capacitor. Find the rms voltage of the source, and explain how the inductor reading can be larger than the source voltage.',
              '$ V_{rms} = 100 $ V. The inductor and capacitor voltages are half a cycle apart and cancel in part, so an individual reading may exceed the source.',
              'The reactive voltages are in exact opposition, so subtract them first:\n\n$ V_L - V_C = 130 - 50 = 80 $ V\n\nThis net reactive voltage is at right angles to $ V_R $, so\n\n$ V = \\sqrt{V_R^{2} + (V_L - V_C)^{2}} = \\sqrt{60^{2} + 80^{2}} = \\sqrt{10000} = 100 $ V\n\n**Now the part that unsettles everybody.** The plain sum of the three readings is $ 240 $ V, more than twice the source. Nothing is broken. Kirchhoff’s loop rule holds at every instant, but the three voltages never peak at the same instant — $ V_L $ is at its maximum when $ V_C $ is at its minimum, and they spend the cycle cancelling each other.\n\nSo yes: a real $ 100 $ V supply can put $ 130 $ V across the inductor of a series LCR circuit, and if you have built one you must insulate for that, not for $ 100 $ V. At resonance the effect is at its most extreme — the reactive voltages become $ Q $ times the supply, which is exactly what the Q-factor items in the next section measure.'),
            mcq('ch7-p20', 'In a series LCR circuit the rms voltages measured across R, L and C',
              ['add as phasors, so their plain sum can exceed the source voltage', 'add arithmetically, and must total the source voltage exactly', 'are each always smaller than the source voltage in any circuit', 'are always equal to each other whatever the source frequency'],
              0,
              'Kirchhoff’s loop rule applies to **instantaneous** voltages, and it is obeyed at every moment. What it does not do is apply to rms values, because the three quantities reach their peaks at different times.\n\nIn phasor language: $ V_R $ points along the current, $ V_L $ points a quarter turn one way and $ V_C $ a quarter turn the other. Add those arrows head to tail and you get\n\n$ V = \\sqrt{V_R^{2} + (V_L - V_C)^{2}} $\n\nwhich is always **less** than the arithmetic sum whenever more than one of them is non-zero. So the individual readings can each be large while the source stays modest.\n\nThe reading that the three must total the source voltage is the DC habit carried over unexamined. It works in a DC circuit because everything there is in phase by default.'),
          ],
        },
        // ── 5 · Resonance and the Q-factor ──────────────────────────────────
        {
          id: 'ch7-s5-resonance',
          title: '5 · Resonance and the Q-factor',
          blurb: 'The frequency where the two reactances cancel — the same number that the free LC circuit oscillated at on the first page of the chapter.',
          items: [
            num('ch7-p21', 'A series LCR circuit has $ L = 2.0 $ H, $ C = 32\\ \\mu $F and $ R = 10\\ \\Omega $, fed from a $ 200 $ V rms source whose frequency can be varied. Find (a) the resonant angular frequency, (b) the current at resonance, and (c) the Q-factor.',
              '(a) $ \\omega_r = 125 $ rad/s  (b) $ I = 20 $ A  (c) $ Q = 25 $',
              '**(a)** Resonance is the condition $ X_L = X_C $, i.e. $ \\omega L = \\frac{1}{\\omega C} $, which rearranges to\n\n$ \\omega_r = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{(2.0)(32\\times10^{-6})}} = \\frac{1}{\\sqrt{6.4\\times10^{-5}}} = \\frac{1}{8.0\\times10^{-3}} = 125 $ rad/s\n\n**(b)** At resonance the reactances cancel completely, so $ Z = R $ and the current is at its largest possible value:\n\n$ I = \\frac{V}{R} = \\frac{200}{10} = 20 $ A\n\n**(c)** $ Q = \\frac{\\omega_r L}{R} = \\frac{(125)(2.0)}{10} = 25 $\n\n**Notice what the resonant frequency does not contain.** There is no $ R $ in $ \\omega_r = \\frac{1}{\\sqrt{LC}} $ — it is the same frequency the same $ L $ and $ C $ would oscillate at with no source and no resistor at all, which is the formula from the very first page of this chapter. Resistance decides how **big** and how **sharp** the resonance is, never **where** it is.'),
            mcq('ch7-p22', 'At the resonant frequency of a series LCR circuit,',
              ['the impedance is at its smallest and equals $ R $', 'the impedance is at its largest and equals $ R $', 'the impedance is zero and the current is unlimited', 'the impedance equals $ X_L + X_C $, which is largest'],
              0,
              'Start from $ Z = \\sqrt{R^{2} + (X_L - X_C)^{2}} $. The resistance is fixed, so the only way to make $ Z $ small is to make the bracket small — and the smallest it can be is zero, when $ X_L = X_C $. At that frequency $ Z = R $, its minimum, and the current $ \\frac{V}{Z} $ is at its maximum.\n\nThe circuit at resonance behaves as if the inductor and capacitor were not there: current in phase with voltage, power factor one, all the power going into the resistor.\n\nThe impedance never reaches zero, because $ R $ is still in the loop — which is exactly what stops the current running away. (A **parallel** LCR circuit does the opposite: at resonance its impedance is at a maximum and the line current is at a minimum. Do not carry the series result over to it without thinking.)'),
            mcq('ch7-p23', 'The resistance of a series LCR circuit is doubled, with $ L $, $ C $ and the source left alone. The resonant frequency',
              ['stays the same, while the current at resonance halves', 'halves, and the current at resonance halves as well', 'stays the same, and the current at resonance is unchanged', 'doubles, while the current at resonance stays the same'],
              0,
              'Two separate questions, and it pays to answer them separately.\n\n**Where is the peak?** At $ \\omega_r = \\frac{1}{\\sqrt{LC}} $, which contains no $ R $. So doubling the resistance moves it nowhere at all.\n\n**How tall is the peak?** At resonance $ Z = R $, so $ I = \\frac{V}{R} $. Double $ R $ and the peak current halves.\n\nThe resonance curve keeps the same centre but becomes lower and broader — and broader is the third consequence, since the bandwidth $ \\frac{R}{L} $ has doubled too. That is the same trade-off as the Q-factor: more resistance means a flatter, less selective response.'),
            num('ch7-p24', 'A series LCR circuit has $ L = 0.10 $ H, $ C = 10\\ \\mu $F and $ R = 5.0\\ \\Omega $, driven by a $ 10 $ V rms source. Find (a) the resonant angular frequency, (b) the Q-factor, (c) the bandwidth, and (d) the rms voltage across the inductor at resonance.',
              '(a) $ \\omega_r = 1000 $ rad/s  (b) $ Q = 20 $  (c) $ \\Delta\\omega = 50 $ rad/s  (d) $ V_L = 200 $ V',
              '**(a)** $ \\omega_r = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{(0.10)(10\\times10^{-6})}} = \\frac{1}{\\sqrt{1.0\\times10^{-6}}} = 1000 $ rad/s\n\n**(b)** $ Q = \\frac{\\omega_r L}{R} = \\frac{(1000)(0.10)}{5.0} = 20 $\n\n**(c)** $ \\Delta\\omega = \\frac{R}{L} = \\frac{5.0}{0.10} = 50 $ rad/s\n\nCheck the two against each other: $ Q = \\frac{\\omega_r}{\\Delta\\omega} = \\frac{1000}{50} = 20 $. They agree, as they must — that ratio is what the Q-factor **means**, and the $ \\frac{\\omega_r L}{R} $ form is just a convenient way to compute it.\n\n**(d)** At resonance $ Z = R $, so $ I = \\frac{10}{5.0} = 2.0 $ A, and $ X_L = \\omega_r L = (1000)(0.10) = 100\\ \\Omega $. Therefore\n\n$ V_L = I X_L = (2.0)(100) = 200 $ V\n\n**Twenty times the supply voltage.** That is not a coincidence: at resonance $ V_L = QV $ exactly, and $ V_C = QV $ too, the two of them cancelling to leave the source facing only $ V_R $. This is why a series LCR circuit at resonance is sometimes called a voltage magnifier — and why a high-Q circuit built carelessly will destroy its own capacitor.'),
            mcq('ch7-p25', 'Two tuning circuits resonate at the same frequency, but one has a much larger Q-factor. Compared with the other, it',
              ['has a narrower bandwidth and picks out one station better', 'has a wider bandwidth and picks out one station better', 'has a narrower bandwidth but a smaller current at resonance', 'resonates just as sharply, since Q does not affect bandwidth'],
              0,
              'The two are locked together by $ Q = \\frac{\\omega_r}{\\Delta\\omega} $: at a fixed resonant frequency, a bigger $ Q $ means a smaller $ \\Delta\\omega $. A narrow band of frequencies gets through strongly and everything else is rejected, which is precisely what "selective" means for a radio tuner.\n\nA high-Q circuit also tends to give a **larger** current at resonance, not a smaller one: for a given $ L $, the form $ Q = \\frac{\\omega_r L}{R} $ is large only when $ R $ is small, and a small $ R $ means a large $ \\frac{V}{R} $. Sharper and taller come together.\n\nSharpness is not free, though. A signal is never a single frequency — speech and music occupy a band around the carrier — so a tuner made too sharp will clip the edges of the very station it is tuned to and the sound goes muffled. Real receivers are designed to a bandwidth that matches the signal, not to the highest Q the components allow.'),
            num('ch7-p26', 'The tuning circuit of a radio contains an inductor of $ 200\\ \\mu $H. What capacitance must it be set to in order to receive a station broadcasting at $ 800 $ kHz?',
              '$ C \\approx 198 $ pF, i.e. about $ 2.0\\times10^{-10} $ F',
              'The station is received when the circuit resonates at the broadcast frequency, so set $ \\omega_r = 2\\pi f $ and solve $ \\omega_r = \\frac{1}{\\sqrt{LC}} $ for $ C $:\n\n$ C = \\frac{1}{\\omega_r^{2}L} $\n\n$ \\omega_r = 2\\pi(8.0\\times10^{5}) = 5.03\\times10^{6} $ rad/s, so $ \\omega_r^{2} = 2.53\\times10^{13} $.\n\n$ C = \\frac{1}{(2.53\\times10^{13})(200\\times10^{-6})} = \\frac{1}{5.05\\times10^{9}} = 1.98\\times10^{-10} $ F\n\nThat is about $ 198 $ picofarads — a tiny capacitance, which is why the tuning knob on an old radio turned a variable air capacitor with visible interleaving plates rather than anything electrolytic.\n\n**Watch the two prefixes.** Feeding $ 200\\ \\mu $H in as $ 200 $ H, or using $ f $ where $ \\omega $ belongs, are the two ways this calculation goes wrong, and both give answers absurd by many orders of magnitude. If your capacitance comes out in farads rather than picofarads, one of those two has happened.'),
          ],
        },
        // ── 6 · Power and the power factor ──────────────────────────────────
        {
          id: 'ch7-s6-power',
          title: '6 · Power and the power factor',
          blurb: 'Volts times amps is not watts any more. The angle between them decides how much of the product is real.',
          items: [
            num('ch7-p27', 'An AC source of $ 200 $ V rms drives a current of $ 5.0 $ A rms through a circuit in which the current lags the voltage by $ 60^{\\circ} $. Find (a) the average power, (b) the apparent power, (c) the power factor, and (d) the wattless component of the current.',
              '(a) $ P = 500 $ W  (b) $ 1000 $ VA  (c) $ \\cos\\phi = 0.50 $  (d) $ 4.3 $ A',
              '**(a)** $ P = V_{rms}I_{rms}\\cos\\phi = (200)(5.0)\\cos 60^{\\circ} = 1000 \\times 0.50 = 500 $ W\n\n**(b)** The apparent power is the plain product, quoted in volt-amperes to keep it distinct from watts:\n\n$ S = V_{rms}I_{rms} = 1000 $ VA\n\n**(c)** $ \\cos\\phi = \\cos 60^{\\circ} = 0.50 $ — which is also $ \\frac{P}{S} = \\frac{500}{1000} $, the definition read the other way.\n\n**(d)** Split the current into the part along the voltage and the part at right angles to it. The perpendicular part carries no power:\n\n$ I\\sin\\phi = (5.0)\\sin 60^{\\circ} = (5.0)(0.866) = 4.3 $ A\n\n**Why an electricity board cares.** The supply cable has to carry the whole $ 5.0 $ A and be heated by all of it, while the customer is billed for $ 500 $ W. The other $ 4.3 $ A of current does nothing useful and costs the supplier real copper and real heat — which is why industrial consumers with a poor power factor are penalised, and why they install correction capacitors.'),
            mcq('ch7-p28', 'A series LCR circuit has $ R = 6\\ \\Omega $ and impedance $ Z = 10\\ \\Omega $. Its power factor is',
              ['$ 0.60 $', '$ 0.80 $', '$ 1.67 $', '$ 0.36 $'],
              0,
              'The power factor is $ \\cos\\phi $, and in the impedance triangle $ R $ is the side adjacent to $ \\phi $ while $ Z $ is the hypotenuse. So\n\n$ \\cos\\phi = \\frac{R}{Z} = \\frac{6}{10} = 0.60 $\n\nThe value $ 0.80 $ is $ \\sin\\phi $, since the reactance here is $ \\sqrt{10^{2} - 6^{2}} = 8\\ \\Omega $ — right triangle, wrong side. Turning the fraction upside down gives $ 1.67 $, which cannot be a cosine at all: any answer above $ 1 $ is a free signal that the ratio is inverted. And $ 0.36 $ is $ \\cos^{2}\\phi $.\n\nThe power factor always lies between $ 0 $ and $ 1 $. Use that as a reflex check.'),
            num('ch7-p29', 'An AC source $ v = 100\\sin\\omega t $ volts drives a current $ i = 5.0\\sin\\left(\\omega t + \\frac{\\pi}{3}\\right) $ amperes through a circuit. Find the average power delivered, and say whether the circuit is inductive or capacitive.',
              '$ P = 125 $ W. The current leads, so the circuit is capacitive.',
              'The two numbers in front of the sines are **peak** values, so convert before using the power formula — or use the peak form of it directly:\n\n$ P = V_{rms}I_{rms}\\cos\\phi = \\frac{V_0}{\\sqrt{2}}\\cdot\\frac{I_0}{\\sqrt{2}}\\cos\\phi = \\frac{1}{2}V_0I_0\\cos\\phi $\n\nThe phase difference is $ \\phi = \\frac{\\pi}{3} = 60^{\\circ} $, so\n\n$ P = \\frac{1}{2}(100)(5.0)\\cos 60^{\\circ} = 250 \\times 0.50 = 125 $ W\n\n**The nature of the circuit** is read off the sign of the phase. The current expression carries $ +\\frac{\\pi}{3} $, so the current reaches its peak **before** the voltage does — the current leads, which is capacitive behaviour.\n\nThe expensive mistake here is writing $ P = (100)(5.0)\\cos 60^{\\circ} = 250 $ W, using peak values in a formula built for rms ones. That is exactly twice the truth, and the factor of two comes from the two hidden $ \\sqrt{2} $s.'),
            mcq('ch7-p30', 'To cut down the current in an AC circuit without wasting energy as heat, the right component to add in series is',
              ['an inductive choke, which drops voltage but dissipates nothing', 'a resistor, which drops voltage and dissipates nothing either', 'a resistor, because it is cheaper and works just as cleanly', 'a second source, since current cannot be cut any other way'],
              0,
              'Both a resistor and an inductor will reduce the current, so the question is entirely about where the energy goes.\n\nA resistor turns the voltage it drops into heat: $ P = I^{2}R $, wasted, and something has to carry it away. An ideal inductor drops voltage too, but its average power is zero — it borrows energy for a quarter cycle and hands it back in the next. The current comes down and nothing is burned.\n\nThat component is called a **choke**, and it is why a fluorescent tube has a heavy coil in series with it rather than a resistor. A resistor doing the same job in a mains fitting would run hot enough to be a fire risk and would waste power continuously.\n\nA capacitor works on the same principle for the same reason; the choke is simply the more usual choice at mains frequency.'),
            mcq('ch7-p31', 'The wattless component of the current in an AC circuit is',
              ['the part $ I\\sin\\phi $, at right angles to the voltage phasor', 'the part $ I\\cos\\phi $, lying along the voltage phasor', 'the whole current, whenever the power factor is below one', 'the part of the current that ends up as heat in the resistor'],
              0,
              'Resolve the current phasor into two pieces relative to the voltage.\n\nThe piece **along** the voltage is $ I\\cos\\phi $. Multiplied by $ V $ it gives $ VI\\cos\\phi $, the average power — so this is the working part.\n\nThe piece **at right angles** is $ I\\sin\\phi $. Over a cycle it delivers exactly as much energy as it takes back, so it transfers no net power: wattless.\n\nThe name is honest but easy to misread. Wattless does not mean imaginary or harmless. That current is really in the wire, the meter really reads it, and the cable is really heated by it — it just never does anything for the customer, which is why power-factor correction exists.\n\nIn a purely reactive circuit $ \\phi = 90^{\\circ} $ and the whole current is wattless. That is the only case in which the entire current earns that description.'),
            num('ch7-p32', 'A small factory draws $ 100 $ A from a $ 240 $ V supply at a power factor of $ 0.60 $. Find (a) the useful power it consumes, (b) the current it would draw for the same useful power if the power factor were corrected to $ 1.00 $, and (c) the factor by which the heating loss in the supply cable would then change.',
              '(a) $ 14.4 $ kW  (b) $ 60 $ A  (c) it falls to $ 0.36 $ of its former value',
              '**(a)** $ P = V_{rms}I_{rms}\\cos\\phi = (240)(100)(0.60) = 14400 $ W $ = 14.4 $ kW\n\n**(b)** With the same useful power and $ \\cos\\phi = 1 $:\n\n$ I = \\frac{P}{V\\cos\\phi} = \\frac{14400}{(240)(1.00)} = 60 $ A\n\n**(c)** Cable heating is $ I^{2}R $ and $ R $ has not changed, so the loss scales as the square of the current:\n\n$ \\left(\\frac{60}{100}\\right)^{2} = 0.36 $\n\nA $ 64\\% $ cut in wasted power in the supply line, with the factory getting exactly the same $ 14.4 $ kW of useful work as before.\n\n**How it is done in practice.** A factory full of motors is strongly inductive, so the current lags. Bolting a bank of capacitors across the supply produces a leading current that cancels the lagging one, pulling $ \\phi $ back towards zero. The capacitors consume no average power themselves — they simply supply the reactive current locally instead of dragging it all the way from the generating station.'),
          ],
        },
        // ── 7 · Transformers ────────────────────────────────────────────────
        {
          id: 'ch7-s7-transformer',
          title: '7 · Transformers',
          blurb: 'Mutual induction turned into a machine — and the single reason the world runs on AC rather than DC.',
          items: [
            num('ch7-p33', 'An ideal transformer steps $ 2200 $ V down to $ 220 $ V. The primary has $ 5000 $ turns, and the secondary delivers $ 10 $ A. Find (a) the number of secondary turns, (b) the primary current, and (c) the power handled.',
              '(a) $ 500 $ turns  (b) $ 1.0 $ A  (c) $ 2200 $ W',
              '**(a)** The voltage ratio equals the turns ratio:\n\n$ \\frac{N_s}{N_p} = \\frac{V_s}{V_p} = \\frac{220}{2200} = \\frac{1}{10} $, so $ N_s = \\frac{5000}{10} = 500 $ turns\n\n**(b)** An ideal transformer wastes nothing, so the power in equals the power out:\n\n$ V_pI_p = V_sI_s \\quad\\Rightarrow\\quad I_p = \\frac{(220)(10)}{2200} = 1.0 $ A\n\n**(c)** $ P = (220)(10) = 2200 $ W, and equally $ (2200)(1.0) = 2200 $ W.\n\n**Read the pattern in the two ratios.** Voltage went down by ten, and current went **up** by ten. A transformer does not create power; it trades volts for amps at a fixed product. Any answer in which both the voltage and the current change the same way has broken conservation of energy, and you can spot it without checking anything else.'),
            mcq('ch7-p34', 'A transformer has $ 100 $ turns on the primary and $ 500 $ on the secondary. Fed with $ 40 $ V, the secondary gives',
              ['$ 200 $ V, and carries less current than the primary', '$ 8 $ V, and carries less current than the primary', '$ 200 $ V, and carries more current than the primary', '$ 40 $ V, since a transformer only isolates the circuits'],
              0,
              'More turns on the secondary means a step-**up**:\n\n$ V_s = V_p\\frac{N_s}{N_p} = 40 \\times \\frac{500}{100} = 200 $ V\n\nWriting the ratio upside down gives $ 8 $ V, and that is the single commonest error with transformers. Fix it with a sentence rather than a formula: **the side with more turns has the higher voltage.** Then check your arithmetic against that sentence before moving on.\n\nThe current then has to go the other way. Power is conserved, so five times the voltage means one fifth of the current — the secondary here carries $ \\frac{1}{5} $ of the primary current. A step-up transformer gives you volts and charges you amps.'),
            mcq('ch7-p35', 'A transformer does nothing at all when connected to a DC supply, because',
              ['a steady current makes no changing flux, so nothing is induced', 'direct current cannot flow through the primary winding at all', 'the iron core blocks direct current but lets AC pass through', 'the secondary winding is not connected to the primary winding'],
              0,
              'A transformer is mutual induction in a box, and mutual induction needs $ \\frac{d\\Phi}{dt} \\neq 0 $. A steady DC current in the primary produces a steady flux in the core, a steady flux induces nothing in the secondary, and the output is flat zero.\n\nDC certainly does flow in the primary — that is the trouble. The winding has only a small resistance and no reactance to limit a steady current, so a transformer left across a DC supply draws a heavy current and burns its primary out. A brief pulse appears at the secondary at the instant of switching on and again at switch-off, and nothing in between.\n\nIt is true that the two windings are not electrically joined, but that is not a fault — it is the design, and the flux in the core is what carries the energy across. **This is the whole reason the world standardised on AC:** a transformer can raise and lower an alternating voltage almost losslessly, and nothing nearly as simple exists for DC.'),
            mcq('ch7-p36', 'Laminating a transformer core out of thin varnished sheets is done to reduce',
              ['eddy-current loss, by breaking up the circulating current paths', 'copper loss, by lowering the resistance of the two windings', 'hysteresis loss, by picking a material with a narrow loop', 'flux leakage, by keeping the whole field inside the core'],
              0,
              'Four losses, four different fixes, and the exam question is usually whether you can keep them apart.\n\n**Eddy-current loss** — induced currents circulating in the iron itself. Fixed by **laminating**: the varnish confines each loop to one thin sheet, so it is small and meets a high resistance. The sheets stack along the flux, so the magnetic path is untouched.\n\n**Copper loss** — $ I^{2}R $ heating in the windings. Fixed by using thicker wire, not by anything done to the core.\n\n**Hysteresis loss** — energy spent going round the B-H loop once per cycle. Fixed by choosing soft iron or silicon steel, whose loop is narrow.\n\n**Flux leakage** — field lines that miss the secondary. Fixed by a closed core and by winding the two coils over each other.\n\nMatch each loss to where it physically happens and none of them is confusable: two live in the core, one lives in the wire, one lives in the air around them.'),
            mcq('ch7-p37', 'Electric power is sent across the country at hundreds of kilovolts rather than at $ 240 $ V, because',
              ['the current is then small, and cable heating goes as $ i^{2}R $', 'a higher voltage pushes the power along the cables faster', 'the resistance of a cable falls as the voltage across it rises', 'a high voltage is safer for people living near the cables'],
              0,
              'For a fixed power $ P = VI $, raising $ V $ lowers $ I $ in exact proportion. The waste in the line is $ I^{2}R $, so the loss falls as the **square** of the factor by which you raised the voltage. Multiply the transmission voltage by a hundred and the line loss drops to one ten-thousandth.\n\nThe resistance of the cable is a property of its copper and its length; the voltage across it does not change it. And a high-voltage line is more dangerous, not less — which is why it runs on tall pylons through open country, and why the voltage is stepped back down before it reaches a street.\n\nThe whole grid is therefore a chain of transformers: step up at the generating station, carry the power thin and fast, step down at the substation, step down again at the pole. None of it is possible without the device in this section.'),
            num('ch7-p38', 'A generating station sends $ 20 $ kW along a line whose total resistance is $ 5.0\\ \\Omega $. Find the power wasted in the line if the power is transmitted (a) at $ 200 $ V and (b) at $ 10 $ kV, and comment on the comparison.',
              '(a) $ 50 $ kW — more than is being sent  (b) $ 20 $ W, one part in a thousand',
              '**(a)** At $ 200 $ V the line must carry\n\n$ I = \\frac{P}{V} = \\frac{20000}{200} = 100 $ A\n\n$ P_{\\text{loss}} = I^{2}R = (100)^{2}(5.0) = 50000 $ W $ = 50 $ kW\n\n**(b)** At $ 10 $ kV,\n\n$ I = \\frac{20000}{10000} = 2.0 $ A, and $ P_{\\text{loss}} = (2.0)^{2}(5.0) = 20 $ W\n\n**Now look at what (a) is saying.** The line would waste $ 50 $ kW while only $ 20 $ kW was being sent — an impossible situation, which in reality means the voltage collapses along the way and nothing useful arrives at the far end. Low-voltage transmission over any distance simply does not work.\n\nAt $ 10 $ kV the same line, the same copper and the same power lose $ 20 $ W: one part in a thousand. Nothing about the cable changed. Only the voltage did, and because the loss goes as $ I^{2} $, a fifty-fold rise in voltage bought a two-thousand-five-hundred-fold cut in waste.'),
          ],
        },
      ],
    }),
    b('text', 2, {
      markdown: 'That is Chapter 7 finished. Look back at what the chapter needed: a changing magnetic field to drive the transformer, and a changing electric field on the plates of every capacitor you put in an AC circuit. Each of those two ideas has been used on its own. Chapter 8 puts them together — a changing electric field turns out to make a magnetic field, the last gap in Ampere’s law closes, and what falls out is a wave that travels at the speed of light.',
    }),
  ],
};

async function main() {
  await withDb(async (db) => {
    const bookId = await ensureBookAndChapter(db, CH);
    await upsertPages(db, bookId, CH, [p14]);
  });
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
