'use strict';
/**
 * Class 11 Physics · Chapter 3 "Motion in Two Dimensions" — pages 15–17.
 * Wave 3: the retrieval recap, the NCERT exercises verbatim, and the drill bank.
 *
 * RULE 0: every NCERT exercise on p16 is transcribed from the chapter PDF
 * (Exercises 3.1–3.22), not reconstructed from memory. Two of them (3.8, 3.9)
 * depend on a printed figure; each names the figure it needs, and the page
 * carries a figure slot so the SVG pass has an explicit worklist.
 *
 * NOTE: Exercise 3.22 (the aircraft-angle problem) was ALREADY used as a worked
 * step_solver on p13 — verbatim, because it is the standard treatment of that
 * problem. It is included again here for completeness, matching the precedent
 * set by Ch.2 (exercise 2.14 appears both as a p13 solver and on the p16 recap).
 *
 * SOURCE BADGES: p16 items are `ncert_exercise`. p17 items are `mcq`/`num` — they
 * are original or reworded, and the two reference books are NEVER named.
 *
 * Run: node scripts/physics11-book/build_ch3_practice.js
 */
const { b, q, st, mcq, mcqFixed, num, ensureChapter, upsertPages, withDb } = require('./_book_ch3');

// ── p15 · Recap ───────────────────────────────────────────────────────────────
const p15 = {
  page_number: 15,
  slug: 'motion-in-two-dimensions-recap',
  title: 'Recap',
  subtitle: 'Retrieve it, do not re-read it',
  blocks: [
    b('callout', 0, {
      variant: 'note',
      title: 'How this page works',
      markdown: 'No summary paragraphs — retrieving an idea from your own memory is what makes it stick, not re-reading it.\n\nWork through the map with the chapter closed. Only then check the formula table against what you wrote.',
    }),
    b('mind_map', 1, {
      title: 'The whole chapter on one map',
      root_label: 'Motion in Two Dimensions',
      intro: 'Cover the right-hand side and try to state each idea before you reveal it.',
      branches: [
        {
          id: 'br-independence',
          label: 'The independence idea',
          children: [
            { id: 'l-two', label: 'Two motions, one clock', summary: 'A plane motion is two independent one-dimensional motions, sharing only time. Neither axis knows the other exists.' },
            { id: 'l-method', label: 'Resolve, solve, recombine', summary: 'The method for every problem in the chapter, without exception. Only the choice of axes changes from page to page.' },
            { id: 'l-vectors', label: 'r, v, a as vectors', formula: '$ \\mathbf{v} = d\\mathbf{r}/dt,\\ \\mathbf{a} = d\\mathbf{v}/dt $', summary: 'Differentiate component by component. Velocity is always tangent to the path; acceleration can point anywhere — that freedom is what lets a particle turn.' },
            { id: 'l-twomethods', label: 'Method 1 vs Method 2', summary: 'One vector equation when time is given and a vector is wanted. Six scalar equations — the workhorse — for everything else, especially when time is unknown.' },
          ],
        },
        {
          id: 'br-projectile',
          label: 'Projectile motion',
          children: [
            { id: 'l-setup', label: 'The four set-up quantities', formula: '$ u_x=u\\cos\\theta,\\ u_y=u\\sin\\theta,\\ a_x=0,\\ a_y=-g $', summary: 'Horizontal velocity never changes — the single most reusable fact in the chapter.' },
            { id: 'l-thr', label: 'T, H, R — and their precondition', formula: '$ T=\\frac{2u\\sin\\theta}{g},\\ H=\\frac{u^2\\sin^2\\theta}{2g},\\ R=\\frac{u^2\\sin2\\theta}{g} $', summary: 'All three assume launch and landing are at the same height. Break that and 45° is no longer best.' },
            { id: 'l-path', label: 'The equation of the path', formula: '$ y = x\\tan\\theta - \\frac{gx^2}{2u^2\\cos^2\\theta} $', summary: 'Quadratic in x because one motion is linear in t and the other quadratic in t — that is why the path is a parabola.' },
            { id: 'l-height', label: 'Launched from a height', summary: 'Landing below launch level means s_y is negative — solve the full quadratic, do not reach for the T/H/R formulas.' },
            { id: 'l-incline', label: 'On an inclined plane', formula: '$ \\theta_{\\max} = 45° + \\beta/2 $', summary: 'Rotate the axes along and perpendicular to the slope. Down the plane: replace β by −β.' },
          ],
        },
        {
          id: 'br-circular',
          label: 'Circular motion',
          children: [
            { id: 'l-omega', label: 'The angular language', formula: '$ \\omega = d\\theta/dt = 2\\pi/T,\\ v = r\\omega $', summary: 'Only valid in radians. A rotating body shares ω; a belt drive shares v.' },
            { id: 'l-centripetal', label: 'Centripetal acceleration', formula: '$ a_c = v^2/r = \\omega^2 r $', summary: 'Constant speed does not mean zero acceleration — the direction is always changing. No forces here; that is next chapter.' },
            { id: 'l-nonuniform', label: 'Two components at once', formula: '$ a_t = dv/dt = r\\alpha,\\quad a = \\sqrt{a_t^2+a_r^2} $', summary: 'Tangential changes the speed, radial changes the direction. a_r can never be zero on a circle; a_t can.' },
          ],
        },
        {
          id: 'br-relative',
          label: 'Relative velocity in 2D',
          children: [
            { id: 'l-sub', label: 'A vector subtraction now', formula: '$ \\mathbf{v}_{AB} = \\mathbf{v}_A - \\mathbf{v}_B $', summary: 'Reverse the second vector, add tip-to-tail. Read subscripts in order: A with respect to B.' },
            { id: 'l-freeze', label: 'Freeze one body', summary: 'Two-body problems become one-body straight-line problems, and closest approach becomes pure geometry.' },
            { id: 'l-frames', label: 'Frames agree only on acceleration', summary: 'Constant relative velocity between frames means they agree about every acceleration and disagree about everything else — even the shape of a path.' },
            { id: 'l-reference', label: 'Every quoted speed has a reference', summary: 'Muzzle speed is relative to the gun, swim speed to the water, air speed to the air. Ask what it is measured against.' },
          ],
        },
        {
          id: 'br-river',
          label: 'River, rain and wind',
          children: [
            { id: 'l-vb', label: 'The three velocities', formula: '$ \\mathbf{v}_b = \\mathbf{v}_{br} + \\mathbf{v}_r $', summary: 'What you steer, what the river does, and where you actually go — three different vectors, easily confused.' },
            { id: 'l-time', label: 'Shortest time vs zero drift', formula: '$ t_{\\min}=d/v_{br};\\ \\sin\\theta=v_r/v_{br} $', summary: 'Straight across wins on time but drifts. Angling upstream cancels the drift but always takes longer.' },
            { id: 'l-impossible', label: 'Impossible if v_r ≥ v_br', summary: 'A limit worth understanding, not memorising: the current can simply out-run you.' },
            { id: 'l-rain', label: 'The umbrella tilts into your motion', formula: '$ \\mathbf{v}_{rm} = \\mathbf{v}_r - \\mathbf{v}_m $', summary: 'What you shelter from is the rain relative to you, not the rain itself.' },
          ],
        },
      ],
    }),
    b('table', 2, {
      caption: 'Every formula in the chapter, in one place',
      headers: ['Quantity', 'Relation', 'Valid when'],
      rows: [
        ['Resolution', '$ u_x = u\\cos\\theta,\\ u_y = u\\sin\\theta $', 'Always'],
        ['Velocity, acceleration', '$ \\mathbf{v}=d\\mathbf{r}/dt,\\ \\mathbf{a}=d\\mathbf{v}/dt $', 'Always'],
        ['Speeding up / slowing / turning', '$ \\mathbf{v}\\cdot\\mathbf{a} \\gtrless 0 $', 'Always'],
        ['Constant acceleration (vector)', '$ \\mathbf{v}=\\mathbf{u}+\\mathbf{a}t,\\ \\mathbf{s}=\\mathbf{u}t+\\frac{1}{2}\\mathbf{a}t^2 $', 'Constant $ \\mathbf{a} $'],
        ['Time of flight', '$ T = \\dfrac{2u\\sin\\theta}{g} $', 'Level launch and landing'],
        ['Maximum height', '$ H = \\dfrac{u^2\\sin^2\\theta}{2g} $', 'Level launch and landing'],
        ['Range', '$ R = \\dfrac{u^2\\sin 2\\theta}{g} $', 'Level launch and landing'],
        ['Maximum range', '$ R_{\\max} = \\dfrac{u^2}{g} $ at $ \\theta=45° $', 'Level launch and landing'],
        ['Equation of trajectory', '$ y = x\\tan\\theta - \\dfrac{gx^2}{2u^2\\cos^2\\theta} $', 'Any projectile'],
        ['Up an incline', '$ T=\\dfrac{2u\\sin(\\theta-\\beta)}{g\\cos\\beta} $', 'Launch angle from horizontal'],
        ['Angular speed', '$ \\omega = \\dfrac{2\\pi}{T} = 2\\pi f $', 'Always, in rad/s'],
        ['Linear–angular bridge', '$ s=r\\theta,\\ v=r\\omega $', 'Radians only'],
        ['Centripetal acceleration', '$ a_c = v^2/r = \\omega^2 r $', 'Any circular path'],
        ['Tangential acceleration', '$ a_t = dv/dt = r\\alpha $', 'Any circular path'],
        ['Angular SUVAT', '$ \\omega=\\omega_0+\\alpha t $, etc.', 'Constant $ \\alpha $'],
        ['Relative velocity', '$ \\mathbf{v}_{AB} = \\mathbf{v}_A - \\mathbf{v}_B $', 'Always'],
        ['River — shortest time', '$ t_{\\min} = d/v_{br} $, drift $ = v_r d/v_{br} $', 'Steered straight across'],
        ['River — zero drift', '$ \\sin\\theta = v_r/v_{br} $, $ t = d/\\sqrt{v_{br}^2-v_r^2} $', 'Only if $ v_{br} > v_r $'],
      ],
    }),
    b('reasoning_prompt', 3, {
      reasoning_type: 'logical',
      prompt: 'Without looking back through the chapter, explain to someone who has not read it why a car going round a bend at a perfectly steady speed is accelerating — and why that acceleration is never a constant vector, even though its magnitude never changes.',
      reveal: 'Acceleration is the rate of change of **velocity**, and velocity carries a direction. Round the bend, the direction changes at every instant even though the speedometer does not move — so the velocity is changing, and there is an acceleration, however steady the speed feels.\n\nIts magnitude, $ v^2/r $, stays fixed as long as $ v $ and $ r $ do. But its **direction** always points at the centre, and the centre is a different way to point at every instant of the turn — so the vector itself never stops changing, even while its size holds still.\n\nThis is the case that could not exist in one dimension, where velocity and acceleration were stuck on the same line and could only agree or disagree in sign. In a plane they can be at any angle, and $ 90° $ — constant speed, changing direction — is exactly what a bend is.\n\nIf you produced this from memory, you own the second-biggest idea in the chapter after the independence of the two axes.',
      difficulty_level: 2,
    }),
    b('reasoning_prompt', 4, {
      reasoning_type: 'logical',
      prompt: 'A student says: "I can always find where a projectile lands using $ R = u^2\\sin 2\\theta / g $." Give a specific numerical example where this fails, say what actually happens instead, and describe the one check that would have caught the mistake before it was made.',
      reveal: '**A counterexample.** A ball thrown at $ 20 $ m/s at $ 30° $ from the top of a $ 20 $ m tower, $ g=10 $ m/s². The formula gives $ R = 400\\sin 60°/10 = 34.6 $ m. The true landing distance, solved from $ -20 = 10t - 5t^2 $ (giving $ t=3.24 $ s and $ x = 17.3 \\times 3.24 $), is about $ 56.1 $ m — a genuinely different answer, not a rounding difference.\n\n**What actually happens:** $ R = u^2\\sin 2\\theta/g $ was derived from the condition $ s_y = 0 $ — return to **launch height**. From a tower the ball keeps falling past that level, so the formula is answering a question that was never asked.\n\n**The check that would have caught it:** before reaching for $ T $, $ H $ or $ R $, ask "are the launch and landing points at the same height?" If not, go back to $ s_y = u_y t + \\frac{1}{2}a_y t^2 $ with the correct signed displacement and solve the quadratic directly — the method from page 7.\n\nThis is the single most common projectile error in exams, and it is entirely avoidable with one question asked before the first line of working.',
      difficulty_level: 3,
    }),
    b('inline_quiz', 5, {
      pass_threshold: 0.7,
      questions: [
        q('A ball is thrown at $ u $ and angle $ \\theta $. At the instant its velocity is purely horizontal, it is:',
          ['At the launch point', 'At the highest point of its path', 'At the landing point', 'Never — the velocity has no purely horizontal instant'], 1,
          '$ v_y = 0 $ defines the highest point, and at that instant only $ v_x = u\\cos\\theta $ survives — purely horizontal.', 1),
        q('Two projectiles are launched at $ 25° $ and $ 65° $ with the same speed on level ground. Comparing them:',
          ['Equal ranges, but $ 65° $ goes higher', 'Equal ranges and equal heights, both matching exactly', 'The $ 25° $ launch has the strictly greater range', 'The $ 65° $ launch has the strictly greater range'], 0,
          'Complementary angles give equal ranges. The steeper one has the larger vertical component, so it reaches further up and takes longer — the horizontal speed and the time trade off exactly.', 2),
        q('A particle moves on a circle of radius $ 5 $ m with speed $ v = 3t $ m/s. At $ t = 2 $ s, its radial acceleration is:',
          ['$ 3.6 $ m/s²', '$ 7.2 $ m/s²', '$ 1.8 $ m/s²', '$ 6 $ m/s²'], 1,
          'At $ t=2 $ s, $ v=6 $ m/s, so $ a_r = v^2/r = 36/5 = 7.2 $ m/s².', 2),
        q('A boat steered straight across a flowing river travels over the ground:',
          ['Straight across, exactly as steered', 'Along a straight line at an angle to the bank', 'Along a curved path away from the bank', 'Upstream, directly against the current'], 1,
          'The actual velocity is the vector sum of a constant across-river component and a constant downstream one, so the ground path is a straight line at an angle — the boat faces one way and travels another.', 2),
        q('If $ \\mathbf{v}_{PQ} = 6\\,\\hat{i} - 8\\,\\hat{j} $ m/s, then $ |\\mathbf{v}_{QP}| $ is:',
          ['$ 2 $ m/s', '$ 10 $ m/s', '$ 14 $ m/s', '$ 100 $ m/s'], 1,
          '$ \\mathbf{v}_{QP} = -\\mathbf{v}_{PQ} $, so the magnitude is unchanged: $ \\sqrt{36+64}=10 $ m/s. Only the direction reverses.', 1),
        q('A stone is thrown horizontally at $ 10 $ m/s from a $ 20 $ m cliff. Its time of flight and its impact angle are found using:',
          ['$ T = 2u\\sin\\theta/g $, directly, since it is a projectile', 'The vertical column alone for time, then the two components for the angle', 'The range formula $ R=u^2\\sin2\\theta/g $, solved for $ \\theta $', 'The centripetal acceleration formula, since it is falling'], 1,
          'Horizontal projection is not level-ground, so $ T=2u\\sin\\theta/g $ does not apply — with $ \\theta=0 $ it would wrongly give zero. Time comes from $ h=\\frac{1}{2}gt^2 $, and the impact angle from $ \\tan^{-1}(v_y/v_x) $ at that time.', 3),
        q('Two bodies have the same non-zero acceleration. In the frame of one, the other appears to move:',
          ['With constant acceleration', 'With constant velocity', 'At rest', 'With increasing acceleration'], 1,
          'Equal accelerations give zero relative acceleration, so the relative velocity is fixed — constant, though not necessarily zero.', 2),
        q('A projectile\'s trajectory is $ y = 5x - 2x^2 $ metres. Its range is:',
          ['$ 2.5 $ m', '$ 5 $ m', '$ 10 $ m', '$ 0.4 $ m'], 1,
          'Set $ y=0 $: $ x(5-2x)=0 $, giving $ x=0 $ or $ x=2.5 $. The range is $ 2.5 $ m — from the $ y=ax-bx^2 $ form, range $ = a/b = 5/2 = 2.5 $.', 2),
        q('A swimmer who can swim at $ 3 $ km/h faces a river flowing at $ 4 $ km/h. She wants to land directly opposite. This is:',
          ['Possible, by steering at some angle upstream', 'Possible, but only by steering straight across', 'Impossible, since the current is faster than she can swim', 'Impossible, regardless of how fast the current flows'], 2,
          '$ \\sin\\theta = v_r/v_{br} = 4/3 > 1 $, which no angle satisfies. Whenever $ v_r \\geq v_{br} $, landing directly opposite cannot be done.', 2),
        q('A wheel starts from rest with constant angular acceleration and completes $ 10 $ revolutions in $ 4 $ s. Which equation finds $ \\alpha $ directly?',
          ['$ \\theta = \\omega_0 t + \\frac{1}{2}\\alpha t^2 $, with $ \\omega_0=0 $', '$ \\omega = \\omega_0 + \\alpha t $, since $ \\omega $ is known', '$ a_c = \\omega^2 r $', '$ v = r\\omega $'], 0,
          'We know $ \\theta $ (in radians, from the revolutions), $ t $ and $ \\omega_0=0 $, and want $ \\alpha $ — exactly the second angular equation. The final $ \\omega $ is not given directly.', 2),
      ],
    }),
    b('callout', 6, {
      variant: 'exam_tip',
      title: 'If you only remember five things',
      markdown: '1. **Resolve, solve each axis separately, recombine.** The method for the whole chapter.\n2. **The horizontal velocity of a projectile never changes.** Almost every projectile shortcut traces back to this.\n3. **$ T $, $ H $, $ R $ need launch and landing at the same height.** Check before you reach for them.\n4. **Constant speed on a circle is not zero acceleration.** The direction is always changing.\n5. **Relative velocity is a vector subtraction: reverse, then add tip-to-tail.** Frames agree only about acceleration.',
    }),
  ],
};

// ── p16 · NCERT Exercises ─────────────────────────────────────────────────────
const p16 = {
  page_number: 16,
  slug: 'motion-in-two-dimensions-ncert-exercises',
  title: 'Practice — NCERT Exercises',
  subtitle: 'All twenty-two, grouped by what they test',
  blocks: [
    b('text', 0, {
      markdown: 'Every exercise from the NCERT chapter is here, in the textbook\'s own words, regrouped so that questions testing the same skill sit together.\n\nThe first theme is pure vector algebra — Chapter 0 territory, not new teaching here, but worth the retrieval practice in this chapter\'s own context. Work each one before revealing the solution.',
    }),
    b('practice_bank', 1, {
      title: 'Theme 1 — Scalars and Vectors: Concepts',
      intro: 'Exercises 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.16 and 3.21. Retrieval of Chapter 0 material, in the new context of motion in a plane.',
      sections: [
        {
          id: 'p16-t1',
          title: 'Vector concepts',
          items: [
            num('ncert-3-1', 'State, for each of the following physical quantities, if it is a scalar or a vector: volume, mass, speed, acceleration, density, number of moles, velocity, angular frequency, displacement, angular velocity.',
              'Scalars: volume, mass, speed, density, number of moles, angular frequency. Vectors: acceleration, velocity, displacement, angular velocity.',
              '**Scalars** — quantities with magnitude only: volume, mass, speed, density, number of moles, and angular frequency (a rate, with no direction attached to it).\n\n**Vectors** — quantities with magnitude and direction: acceleration, velocity, displacement, and angular velocity (which does have a direction, along the rotation axis).\n\nNote the pairing: speed is a scalar, velocity is the same idea with a direction added — a distinction this chapter has used constantly.',
              'ncert_exercise'),
            num('ncert-3-2', 'Pick out the two scalar quantities in the following list: force, angular momentum, work, current, linear momentum, electric field, average velocity, magnetic moment, relative velocity.',
              'Work and current.',
              'Everything else in the list is a vector: force, angular momentum, linear momentum, electric field, average velocity, magnetic moment, and relative velocity all carry a direction.\n\n**Work** is a scalar (it is a dot product of two vectors — force and displacement). **Current**, despite having "current direction" spoken of loosely, does not add like a vector — it is a scalar, which is why Kirchhoff\'s current law works with plain arithmetic sums at a junction.',
              'ncert_exercise'),
            num('ncert-3-3', 'Pick out the only vector quantity in the following list: Temperature, pressure, impulse, time, power, total path length, energy, gravitational potential, coefficient of friction, charge.',
              'Impulse.',
              '**Impulse** is force multiplied by time, $ \\mathbf{J} = \\mathbf{F}\\Delta t $ — a vector, in the direction of the force.\n\nEvery other item in the list is a scalar: temperature, pressure, time, power, path length, energy, gravitational potential, the coefficient of friction, and charge all have magnitude only, with no direction attached.',
              'ncert_exercise'),
            num('ncert-3-4', 'State with reasons, whether the following algebraic operations with scalar and vector physical quantities are meaningful: (a) adding any two scalars, (b) adding a scalar to a vector of the same dimensions, (c) multiplying any vector by any scalar, (d) multiplying any two scalars, (e) adding any two vectors, (f) adding a component of a vector to the same vector.',
              '(a) No, in general. (b) No. (c) Yes. (d) Yes. (e) No, unless they represent the same physical quantity. (f) No.',
              '(a) **Not meaningful in general** — only scalars representing the same physical quantity can be added; adding a mass to a temperature is meaningless even though both are scalars.\n\n(b) **Not meaningful.** A vector and a scalar are different kinds of object; sharing dimensions does not make them addable.\n\n(c) **Meaningful.** Multiplying a vector by a scalar scales its magnitude (and flips its direction if the scalar is negative) — this is used constantly, e.g. $ \\mathbf{F}=m\\mathbf{a} $.\n\n(d) **Meaningful.** Ordinary multiplication of numbers.\n\n(e) **Not meaningful unless the two vectors represent the same physical quantity** — you cannot add a velocity to a force, even though both are vectors.\n\n(f) **Not meaningful.** A component of a vector (its projection along an axis) is not the same kind of object as the vector itself, so the two cannot be added.',
              'ncert_exercise'),
            num('ncert-3-5', 'Read each statement below carefully and state with reasons, if it is true or false: (a) The magnitude of a vector is always a scalar, (b) each component of a vector is always a scalar, (c) the total path length is always equal to the magnitude of the displacement vector of a particle, (d) the average speed of a particle (defined as total path length divided by the time taken to cover the path) is either greater or equal to the magnitude of average velocity of the particle over the same interval of time, (e) three vectors not lying in a plane can never add up to give a null vector.',
              '(a) True (b) False (c) False (d) True (e) True',
              '(a) **True.** A magnitude is, by definition, a non-negative number with no direction attached — a scalar.\n\n(b) **False.** A vector component, written as $ A_x\\,\\hat{i} $, is itself a vector; only its coefficient $ A_x $ is a scalar.\n\n(c) **False.** Path length equals the magnitude of displacement only when the motion never reverses direction — otherwise the path is strictly greater.\n\n(d) **True.** This is page 10\'s result, generalised — average speed can never be smaller than the magnitude of average velocity, since path length can never be smaller than displacement magnitude.\n\n(e) **True.** If three vectors do not lie in a plane, no combination of two of them can produce a resultant lying along the line of the third (needed to cancel it), so they cannot sum to zero.',
              'ncert_exercise'),
            num('ncert-3-6', 'Establish the following vector inequalities geometrically or otherwise: (a) $ |\\mathbf{a}+\\mathbf{b}| \\leq |\\mathbf{a}| + |\\mathbf{b}| $ (b) $ |\\mathbf{a}+\\mathbf{b}| \\geq ||\\mathbf{a}| - |\\mathbf{b}|| $ (c) $ |\\mathbf{a}-\\mathbf{b}| \\leq |\\mathbf{a}| + |\\mathbf{b}| $ (d) $ |\\mathbf{a}-\\mathbf{b}| \\geq ||\\mathbf{a}| - |\\mathbf{b}|| $. When does the equality sign above apply?',
              'All four follow from the triangle inequality. Equality in (a): a, b parallel. In (b): a, b antiparallel. In (c): a, b antiparallel. In (d): a, b parallel.',
              'All four are versions of the same fact: **in any triangle, one side is never longer than the sum of the other two, and never shorter than their difference.**\n\n(a) Draw $ \\mathbf{a} $ and $ \\mathbf{b} $ tip-to-tail; $ \\mathbf{a}+\\mathbf{b} $ is the third side of the triangle they form (or a straight line if they are parallel), so it can be at most $ |\\mathbf{a}|+|\\mathbf{b}| $. **Equality when $ \\mathbf{a} $ and $ \\mathbf{b} $ point the same way.**\n\n(b) The third side of a triangle is also never shorter than the difference of the other two, giving $ |\\mathbf{a}+\\mathbf{b}| \\geq ||\\mathbf{a}|-|\\mathbf{b}|| $. **Equality when $ \\mathbf{a} $ and $ \\mathbf{b} $ point opposite ways.**\n\n(c) Since $ \\mathbf{a}-\\mathbf{b} = \\mathbf{a}+(-\\mathbf{b}) $, apply (a) with $ -\\mathbf{b} $ in place of $ \\mathbf{b} $: $ |\\mathbf{a}-\\mathbf{b}| \\leq |\\mathbf{a}|+|-\\mathbf{b}| = |\\mathbf{a}|+|\\mathbf{b}| $. **Equality when $ \\mathbf{a} $ and $ -\\mathbf{b} $ align — i.e. $ \\mathbf{a} $ and $ \\mathbf{b} $ point opposite ways.**\n\n(d) Similarly apply (b) with $ -\\mathbf{b} $: **equality when $ \\mathbf{a} $ and $ \\mathbf{b} $ point the same way.**',
              'ncert_exercise'),
            num('ncert-3-7', 'Given $ \\mathbf{a}+\\mathbf{b}+\\mathbf{c}+\\mathbf{d}=0 $, which of the following statements are correct: (a) $ \\mathbf{a}, \\mathbf{b}, \\mathbf{c} $ and $ \\mathbf{d} $ must each be a null vector, (b) the magnitude of $ (\\mathbf{a}+\\mathbf{c}) $ equals the magnitude of $ (\\mathbf{b}+\\mathbf{d}) $, (c) the magnitude of $ \\mathbf{a} $ can never be greater than the sum of the magnitudes of $ \\mathbf{b}, \\mathbf{c} $ and $ \\mathbf{d} $, (d) $ \\mathbf{b}+\\mathbf{c} $ must lie in the plane of $ \\mathbf{a} $ and $ \\mathbf{d} $ if $ \\mathbf{a} $ and $ \\mathbf{d} $ are not collinear, and in the line of $ \\mathbf{a} $ and $ \\mathbf{d} $, if they are collinear?',
              '(a) False (b) True (c) True (d) True',
              '(a) **False.** Four non-zero vectors can perfectly well sum to zero, provided they are arranged to cancel — nothing requires each one individually to vanish.\n\n(b) **True.** Rearranging, $ \\mathbf{a}+\\mathbf{c} = -(\\mathbf{b}+\\mathbf{d}) $, and a vector and its negative always have equal magnitudes.\n\n(c) **True.** Rearranging, $ \\mathbf{a} = -(\\mathbf{b}+\\mathbf{c}+\\mathbf{d}) $, so $ |\\mathbf{a}| = |\\mathbf{b}+\\mathbf{c}+\\mathbf{d}| \\leq |\\mathbf{b}|+|\\mathbf{c}|+|\\mathbf{d}| $ by the triangle inequality (exercise 3.6a, extended).\n\n(d) **True.** Since $ \\mathbf{b}+\\mathbf{c} = -(\\mathbf{a}+\\mathbf{d}) $, the vector $ \\mathbf{b}+\\mathbf{c} $ must point exactly opposite to $ \\mathbf{a}+\\mathbf{d} $ — so it lies in whatever plane contains $ \\mathbf{a} $ and $ \\mathbf{d} $, collapsing to their common line if they happen to be collinear.',
              'ncert_exercise'),
            num('ncert-3-16', 'Read each statement below carefully and state, with reasons, if it is true or false: (a) The net acceleration of a particle in circular motion is always along the radius of the circle towards the centre. (b) The velocity vector of a particle at a point is always along the tangent to the path of the particle at that point. (c) The acceleration vector of a particle in uniform circular motion averaged over one cycle is a null vector.',
              '(a) False (b) True (c) True',
              '(a) **False.** This is only true for *uniform* circular motion. If the speed is also changing there is a tangential component too, and the net acceleration then points somewhere between the tangent and the radius — page 12\'s whole subject.\n\n(b) **True**, for any path at all, not only circles. Shrinking the displacement swings the chord onto the tangent.\n\n(c) **True.** Over one full cycle the acceleration vector sweeps through every direction, and diametrically opposite points cancel in pairs, so the average is a null vector — even though the acceleration is never actually zero at any instant. The same is true of the average velocity over a full revolution.',
              'ncert_exercise'),
            num('ncert-3-21', 'Read each statement below carefully and state, with reasons and examples, if it is true or false: A scalar quantity is one that (a) is conserved in a process, (b) can never take negative values, (c) must be dimensionless, (d) does not vary from one point to another in space, (e) has the same value for observers with different orientations of axes.',
              '(a) False (b) False (c) False (d) False (e) True',
              '(a) **False.** Being a scalar has nothing to do with conservation — kinetic energy is a scalar and is not conserved in a collision with friction.\n\n(b) **False.** Temperature in Celsius, or electric charge, are scalars that take negative values routinely.\n\n(c) **False.** Mass and speed are scalars with dimensions.\n\n(d) **False.** Temperature, pressure and density are scalars that vary from point to point in a room.\n\n(e) **True — and this is the actual defining property.** A scalar\'s numerical value does not depend on how the observer has chosen to orient their coordinate axes, unlike the *components* of a vector, which change when the axes rotate even though the vector itself has not.',
              'ncert_exercise'),
          ],
        },
      ],
    }),
    b('practice_bank', 2, {
      title: 'Theme 2 — Vectors in Components',
      intro: 'Exercises 3.17, 3.18, 3.19 and 3.20. Position, velocity and acceleration written out in î ĵ form.',
      sections: [
        {
          id: 'p16-t2',
          title: 'Component calculations',
          items: [
            num('ncert-3-17', 'The position of a particle is given by $ \\mathbf{r} = 3.0t\\,\\hat{i} - 2.0t^2\\,\\hat{j} + 4.0\\,\\hat{k}\\ \\text{m} $, where t is in seconds and the coefficients have the proper units for r to be in metres. (a) Find the v and a of the particle. (b) What is the magnitude and direction of velocity of the particle at t = 2.0 s?',
              '(a) $ \\mathbf{v} = 3.0\\,\\hat{i} - 4.0t\\,\\hat{j} $ m/s, $ \\mathbf{a} = -4.0\\,\\hat{j} $ m/s² (b) $ 8.54 $ m/s at about $ 69.4° $ below the x-axis',
              '(a) Differentiate component by component: $ \\mathbf{v} = d\\mathbf{r}/dt = 3.0\\,\\hat{i} - 4.0t\\,\\hat{j} $ m/s. Differentiating again, $ \\mathbf{a} = -4.0\\,\\hat{j} $ m/s² — constant, with no $ \\hat{i} $ or $ \\hat{k} $ part.\n\n(b) At $ t=2.0 $ s: $ \\mathbf{v} = 3.0\\,\\hat{i} - 8.0\\,\\hat{j} $ m/s. So $ v = \\sqrt{9+64} = \\sqrt{73} = 8.54 $ m/s, and $ \\tan\\beta = 8/3 $ gives $ \\beta = 69.4° $ below the x-axis, since $ v_y $ is negative.',
              'ncert_exercise'),
            num('ncert-3-18', 'A particle starts from the origin at t = 0 s with a velocity of $ 10.0\\,\\hat{j} $ m/s and moves in the x-y plane with a constant acceleration of $ (8.0\\,\\hat{i}+2.0\\,\\hat{j}) $ m/s². (a) At what time is the x-coordinate of the particle 16 m? What is the y-coordinate of the particle at that time? (b) What is the speed of the particle at the time?',
              '(a) $ t = 2 $ s, $ y = 24 $ m (b) $ 21.3 $ m/s',
              '(a) Along x: $ u_x=0 $, $ a_x=8.0 $, so $ x = 4t^2 $. Setting $ x=16 $: $ t^2=4 $, $ t=2 $ s. Along y: $ u_y=10.0 $, $ a_y=2.0 $, so $ y = 10t+t^2 = 20+4 = 24 $ m.\n\n(b) $ v_x = a_x t = 16 $ m/s and $ v_y = u_y + a_y t = 10+4 = 14 $ m/s, so $ v = \\sqrt{256+196} = \\sqrt{452} = 21.3 $ m/s.',
              'ncert_exercise'),
            num('ncert-3-19', '$ \\hat{i} $ and $ \\hat{j} $ are unit vectors along x- and y-axes respectively. What is the magnitude and direction of the vectors $ \\hat{i}+\\hat{j} $ and $ \\hat{i}-\\hat{j} $? What are the components of a vector $ \\mathbf{A}=2\\hat{i}+3\\hat{j} $ along the directions of $ \\hat{i}+\\hat{j} $ and $ \\hat{i}-\\hat{j} $?',
              '$ |\\hat{i}+\\hat{j}|=\\sqrt{2} $ at $ 45° $; $ |\\hat{i}-\\hat{j}|=\\sqrt{2} $ at $ -45° $. Components of A: $ 5/\\sqrt{2} $ and $ -1/\\sqrt{2} $.',
              'Both $ \\hat{i}+\\hat{j} $ and $ \\hat{i}-\\hat{j} $ have magnitude $ \\sqrt{1^2+1^2}=\\sqrt{2} $. The first points at $ 45° $ from the x-axis (equally between $ \\hat{i} $ and $ \\hat{j} $); the second points at $ -45° $ (equally between $ \\hat{i} $ and $ -\\hat{j} $).\n\nThe component of $ \\mathbf{A} $ along a direction is $ \\mathbf{A} $ dotted with the **unit** vector in that direction. Along $ \\hat{i}+\\hat{j} $: unit vector is $ (\\hat{i}+\\hat{j})/\\sqrt{2} $, so the component is $ (2+3)/\\sqrt{2} = 5/\\sqrt{2} = 3.54 $.\n\nAlong $ \\hat{i}-\\hat{j} $: unit vector is $ (\\hat{i}-\\hat{j})/\\sqrt{2} $, so the component is $ (2-3)/\\sqrt{2} = -1/\\sqrt{2} = -0.71 $.',
              'ncert_exercise'),
            num('ncert-3-20', 'For any arbitrary motion in space, which of the following relations are true: (a) $ \\mathbf{v}_{\\text{average}} = \\frac{1}{2}(\\mathbf{v}(t_1)+\\mathbf{v}(t_2)) $ (b) $ \\mathbf{v}_{\\text{average}} = [\\mathbf{r}(t_2)-\\mathbf{r}(t_1)]/(t_2-t_1) $ (c) $ \\mathbf{v}(t) = \\mathbf{v}(0)+\\mathbf{a}t $ (d) $ \\mathbf{r}(t) = \\mathbf{r}(0)+\\mathbf{v}(0)t+\\frac{1}{2}\\mathbf{a}t^2 $ (e) $ \\mathbf{a}_{\\text{average}} = [\\mathbf{v}(t_2)-\\mathbf{v}(t_1)]/(t_2-t_1) $. (The "average" stands for average of the quantity over the interval $ t_1 $ to $ t_2 $.)',
              '(a) False in general (b) True (c) False in general (d) False in general (e) True',
              'This question is deliberately about **arbitrary** motion — not the constant-acceleration case this whole chapter has mostly used.\n\n(b) and (e) are **always true**, because they are the *definitions* of average velocity and average acceleration, valid for any motion whatsoever.\n\n(a), (c) and (d) are **only true when the acceleration is constant.** For arbitrary motion the velocity can vary in any way between $ t_1 $ and $ t_2 $, so its average need not equal the mean of the two endpoint values, and neither the linear velocity formula nor the SUVAT-style position formula need hold.\n\nThis is the calculus reminder from Chapter 2 page 14, generalised to two dimensions: the *definitions* always work; the neat formulas are a special case.',
              'ncert_exercise'),
          ],
        },
      ],
    }),
    b('image', 3, {
      src: '',
      alt: 'Placeholder for the NCERT figures needed by exercises 3.8 (three girls skating on a circular rink) and 3.9 (cyclist in a circular park).',
      aspect_ratio: '16:9',
      figure_key: 'ch3-ncert-exercise-figures',
      caption: 'The two figures needed for Theme 3 below. Refer to this while working exercises 3.8 and 3.9.',
    }),
    b('practice_bank', 4, {
      title: 'Theme 3 — Displacement, Path Length and Average Velocity',
      intro: 'Exercises 3.8, 3.9, 3.10 and 3.11. Four problems that turn entirely on keeping displacement and path length apart.',
      sections: [
        {
          id: 'p16-t3',
          title: 'Displacement vs path',
          items: [
            num('ncert-3-8', 'Three girls skating on a circular ice ground of radius 200 m start from a point P on the edge of the ground and reach a point Q diametrically opposite to P following different paths as shown in the figure. What is the magnitude of the displacement vector for each? For which girl is this equal to the actual length of path skated?',
              'Displacement = 400 m for all three (the diameter). Equal to the path length only for the girl who skates straight along the diameter PQ.',
              'P and Q are fixed points, diametrically opposite on a circle of radius 200 m — so the **displacement** is the diameter, $ 2 \\times 200 = 400 $ m, for **every** girl regardless of the route she took. Displacement depends only on start and finish, never on the path in between.\n\nThe **path length** differs for each girl, and is at least 400 m, equal to the displacement only for the girl who skates straight along the diameter — a curved route is always longer than the straight line it connects.',
              'ncert_exercise'),
            num('ncert-3-9', 'A cyclist starts from the centre O of a circular park of radius 1 km, reaches the edge P of the park, then cycles along the circumference, and returns to the centre along QO as shown in the figure. If the round trip takes 10 min, what is the (a) net displacement, (b) average velocity, and (c) average speed of the cyclist?',
              '(a) Zero (b) Zero (c) $ 21.4 $ km/h',
              '(a) The trip starts and ends at O, so the **net displacement is zero.**\n\n(b) Average velocity is displacement over time — with zero displacement, the **average velocity is also zero**, however far the cyclist actually travelled.\n\n(c) The path is $ OP $ (a radius, 1 km) plus the quarter-circle arc $ PQ $ (since P and Q are perpendicular radii, from the figure) plus $ QO $ (another radius, 1 km):\n\n$ \\text{path} = 1 + \\dfrac{1}{4}(2\\pi \\times 1) + 1 = 2 + \\dfrac{\\pi}{2} = 3.57\\ \\text{km} $\n\nTime is 10 min $ = \\frac{1}{6} $ h, so average speed $ = 3.57 \\div \\frac{1}{6} = 21.4 $ km/h. This is the standard example of a non-zero average speed coexisting with zero average velocity.',
              'ncert_exercise'),
            num('ncert-3-10', 'On an open ground, a motorist follows a track that turns to his left by an angle of 60° after every 500 m. Starting from a given turn, specify the displacement of the motorist at the third, sixth and eighth turn. Compare the magnitude of the displacement with the total path length covered by the motorist in each case.',
              '3rd turn: 1000 m at 60° to the start, path 1500 m. 6th turn: 0 m (back at start), path 3000 m. 8th turn: 866 m at 30° to the start, path 4000 m.',
              'A $ 60° $ turn every 500 m traces a regular hexagon, which closes after exactly 6 turns.\n\n**3rd turn:** adding three 500 m sides at $ 0°, 60°, 120° $ to the starting direction gives a resultant of magnitude $ 1000 $ m, at $ 60° $ to the initial direction. Path length $ = 3(500) = 1500 $ m.\n\n**6th turn:** the hexagon has closed, so the motorist is **back at the starting point** — displacement is **zero**. Path length $ = 6(500) = 3000 $ m — travelled, but not displaced.\n\n**8th turn:** two turns past closure, the geometry repeats the 2nd-turn pattern: resultant magnitude $ = 500\\sqrt{3} = 866 $ m, at $ 30° $ to the initial direction. Path length $ = 8(500) = 4000 $ m.\n\nAt every stage the **path length is strictly greater than the displacement** except when the displacement happens to be zero at the 6th turn — where the path is at its largest gap from the displacement of all three cases.',
              'ncert_exercise'),
            num('ncert-3-11', 'A passenger arriving in a new town wishes to go from the station to a hotel located 10 km away on a straight road from the station. A dishonest cabman takes him along a circuitous path 23 km long and reaches the hotel in 28 min. What is (a) the average speed of the taxi, (b) the magnitude of average velocity? Are the two equal?',
              '(a) $ 49.3 $ km/h (b) $ 21.4 $ km/h — not equal.',
              '(a) Average speed $ = \\dfrac{\\text{path length}}{\\text{time}} = \\dfrac{23\\ \\text{km}}{28/60\\ \\text{h}} = \\dfrac{23}{0.467} = 49.3 $ km/h.\n\n(b) Average velocity magnitude $ = \\dfrac{|\\text{displacement}|}{\\text{time}} = \\dfrac{10\\ \\text{km}}{28/60\\ \\text{h}} = \\dfrac{10}{0.467} = 21.4 $ km/h.\n\n**Not equal** — because the cabman\'s route was circuitous (23 km) rather than straight (10 km). This is exactly the inequality from exercise 3.5(d): average speed exceeds the magnitude of average velocity whenever the path is longer than the straight-line displacement, which is here by a large margin.',
              'ncert_exercise'),
          ],
        },
      ],
    }),
    b('practice_bank', 5, {
      title: 'Theme 4 — Projectiles and Circular Motion',
      intro: 'Exercises 3.12, 3.13, 3.14, 3.15 and 3.22. The numerical heart of the chapter.',
      sections: [
        {
          id: 'p16-t4',
          title: 'The chapter\'s core calculations',
          items: [
            num('ncert-3-12', 'The ceiling of a long hall is 25 m high. What is the maximum horizontal distance that a ball thrown with a speed of 40 m/s can go without hitting the ceiling of the hall?',
              '$ 150.5 $ m',
              'The steepest permitted throw just grazes the ceiling, so $ H = 25 $ m fixes the angle: $ 25 = \\dfrac{(40\\sin\\theta)^2}{2(9.8)} $, giving $ \\sin^2\\theta = \\dfrac{490}{1600} = 0.306 $, so $ \\sin\\theta = 0.553 $, $ \\theta = 33.6° $, $ \\cos\\theta = 0.833 $.\n\nThen $ R = \\dfrac{u^2\\sin2\\theta}{g} = \\dfrac{1600 \\times 2(0.553)(0.833)}{9.8} = \\dfrac{1475.7}{9.8} = 150.5 $ m.\n\nAny steeper and the ball hits the ceiling before landing; any shallower and the range is less than this maximum.',
              'ncert_exercise'),
            num('ncert-3-13', 'A cricketer can throw a ball to a maximum horizontal distance of 100 m. How much high above the ground can the cricketer throw the same ball?',
              '$ 50 $ m',
              'Maximum horizontal range means $ \\theta = 45° $ and $ R_{\\max} = u^2/g = 100 $ m, so $ u^2 = 100g $.\n\nThrown **vertically** instead, the height reached is $ h = u^2/(2g) = 100g/(2g) = 50 $ m.\n\nNote this is **not** the same as $ H_{\\max} $ at $ 45° $ (which would be $ R_{\\max}/4 = 25 $ m) — a vertical throw puts the entire speed into the vertical component, giving twice that height.',
              'ncert_exercise'),
            num('ncert-3-14', 'A stone tied to the end of a string 80 cm long is whirled in a horizontal circle with a constant speed. If the stone makes 14 revolutions in 25 s, what is the magnitude and direction of acceleration of the stone?',
              '$ 9.9 $ m/s², directed towards the centre (along the string).',
              '$ \\omega = \\dfrac{2\\pi(14)}{25} = 3.52 $ rad/s. Then $ a = \\omega^2 r = (3.52)^2(0.80) = 12.4(0.80) = 9.9 $ m/s², directed towards the centre of the circle — along the string, towards the hand holding it.\n\nThis is very close to $ g $, which is worth noticing: a whirled stone is under about the same acceleration as a falling one.',
              'ncert_exercise'),
            num('ncert-3-15', 'An aircraft executes a horizontal loop of radius 1.00 km with a steady speed of 900 km/h. Compare its centripetal acceleration with the acceleration due to gravity.',
              '$ a_c \\approx 62.5 $ m/s², about $ 6.4g $.',
              '$ 900 $ km/h $ = 900 \\times \\dfrac{5}{18} = 250 $ m/s. So $ a_c = v^2/r = 250^2/1000 = 62.5 $ m/s².\n\nComparing with $ g = 9.8 $ m/s²: $ a_c/g = 62.5/9.8 = 6.38 \\approx 6.4 $. The aircraft experiences over six times the acceleration due to gravity in this turn — close to the limit a trained pilot can withstand.',
              'ncert_exercise'),
            num('ncert-3-22', 'An aircraft is flying at a height of 3400 m above the ground. If the angle subtended at a ground observation point by the aircraft positions 10.0 s apart is 30°, what is the speed of the aircraft?',
              '$ \\approx 182 $ m/s (about 656 km/h)',
              'Halve the subtended angle to make a right triangle: $ 15° $ at the observer, with the $ 3400 $ m height as the adjacent side.\n\nHalf-distance $ = 3400\\tan 15° = 3400(0.268) = 911 $ m, so the full distance covered is $ 1822 $ m.\n\nSpeed $ = 1822/10.0 = 182 $ m/s — about 656 km/h, a plausible airliner cruising speed. (This exercise was already used as a worked step-by-step example on the Relative Velocity page — it is repeated here for completeness.)',
              'ncert_exercise'),
          ],
        },
      ],
    }),
  ],
};

// ── p17 · JEE & NEET Drill ────────────────────────────────────────────────────
const p17 = {
  page_number: 17,
  slug: 'motion-in-two-dimensions-jee-neet-drill',
  title: 'Practice — JEE & NEET Drill',
  subtitle: 'Five sections, one per topic this chapter has to cover',
  blocks: [
    b('text', 0, {
      markdown: 'Five sections, one for each topic in the chapter\'s taxonomy. Work a whole section in one sitting and mark it before moving on.\n\nAnything you get wrong, go back to the page it came from rather than reading the explanation a second time.',
    }),
    b('practice_bank', 1, {
      title: 'Section 1 — Vectors, Resolution and Motion in a Plane',
      sections: [
        {
          id: 'p17-s1',
          title: 'Ten questions',
          items: [
            mcq('d1-1', 'A particle moves in a plane with a constant acceleration. Its motion can always be treated as:',
              ['One two-dimensional problem, never split further', 'Two independent one-dimensional motions along perpendicular axes', 'A single one-dimensional motion along the resultant direction', 'Circular motion about some centre'], 1,
              'This is the sentence the whole chapter is built on: two perpendicular one-dimensional problems sharing only the time.'),
            mcq('d1-2', 'A particle is projected with velocity $ u $ at angle $ \\theta $ to the horizontal. Its horizontal component of velocity:',
              ['Decreases steadily throughout the flight', 'Is zero at the highest point', 'Remains constant throughout the flight', 'Increases steadily throughout the flight'], 2,
              'Gravity has no horizontal component, so $ v_x = u\\cos\\theta $ never changes — the single most reused fact in the chapter.'),
            num('d1-3', 'A particle has $ \\mathbf{u} = 3\\,\\hat{i} $ m/s and constant $ \\mathbf{a} = 4\\,\\hat{j} $ m/s². Find its speed at $ t = 2 $ s.',
              '$ 8.54 $ m/s',
              '$ v_x = 3 $ m/s (unchanged) and $ v_y = 4(2) = 8 $ m/s. So $ v = \\sqrt{9+64} = \\sqrt{73} = 8.54 $ m/s.'),
            mcq('d1-4', 'Two vectors of equal magnitude $ 5 $ units are perpendicular to each other. The magnitude of their difference is:',
              ['$ 5 $ units', '$ 10 $ units', '$ 5\\sqrt{2} $', 'Zero'], 2,
              'For perpendicular vectors of equal magnitude, both the sum and the difference have magnitude $ a\\sqrt{2} = 5\\sqrt{2} $.'),
            num('d1-5', 'A particle starts from the origin with $ \\mathbf{u} = 2\\,\\hat{i}+3\\,\\hat{j} $ m/s and $ \\mathbf{a}=4\\,\\hat{i} $ m/s². Find its y-coordinate when its x-coordinate is $ 12 $ m.',
              '$ 6 $ m',
              'Along x: $ 12 = 2t + 2t^2 $, so $ t^2+t-6=0 $, giving $ (t+3)(t-2)=0 $, $ t=2 $ s. Along y (no acceleration): $ y = 3(2) = 6 $ m.'),
            mcq('d1-6', 'A vector $ \\mathbf{A} $ makes an angle of $ 30° $ with the x-axis and has magnitude $ 10 $. Its y-component is:',
              ['$ 5 $', '$ 5\\sqrt{3} $', '$ 8.66 $', '$ 10 $'], 0,
              '$ A_y = A\\sin 30° = 10(0.5) = 5 $. The $ 8.66 $ value ($ 10\\cos 30° $) is the x-component instead.'),
            num('d1-7', 'A particle moving with constant acceleration changes its velocity from $ 4\\,\\hat{i}+2\\,\\hat{j} $ m/s to $ 8\\,\\hat{i}+6\\,\\hat{j} $ m/s in $ 2 $ s. Find its acceleration.',
              '$ 2\\,\\hat{i}+2\\,\\hat{j} $ m/s²',
              '$ \\mathbf{a} = \\Delta\\mathbf{v}/\\Delta t = (4\\,\\hat{i}+4\\,\\hat{j})/2 = 2\\,\\hat{i}+2\\,\\hat{j} $ m/s².'),
            mcq('d1-8', 'For a particle moving in a plane, if $ \\mathbf{v}\\cdot\\mathbf{a} = 0 $ at every instant, the particle is:',
              ['Moving in a straight line at constant speed', 'Speeding up while moving in a straight line', 'Moving on a curved path at constant speed', 'Momentarily at rest'], 2,
              'A perpendicular acceleration at every instant changes only the direction, never the speed — this is uniform circular motion, the extreme case of "turning at constant speed".'),
            num('d1-9', 'A particle at the origin has $ \\mathbf{u}=5\\,\\hat{j} $ m/s and $ \\mathbf{a}=6\\,\\hat{i}+8\\,\\hat{j} $ m/s². Find its displacement magnitude at $ t=1 $ s.',
              '$ 9.49 $ m',
              '$ \\mathbf{s} = \\mathbf{u}t+\\frac{1}{2}\\mathbf{a}t^2 = (0+3)\\,\\hat{i}+(5+4)\\,\\hat{j} = 3\\,\\hat{i}+9\\,\\hat{j} $ m, so $ |\\mathbf{s}|=\\sqrt{9+81}=\\sqrt{90}=9.49 $ m.'),
            mcq('d1-10', 'A body moving in a plane has a constant acceleration directed opposite to its initial velocity. Its path is:',
              ['A parabolic curve', 'A circular arc', 'A straight line', 'An elliptical arc'], 2,
              'When the acceleration is exactly parallel or antiparallel to the initial velocity, both remain along the same line for the whole motion — the path stays straight, exactly like one-dimensional motion.'),
          ],
        },
      ],
    }),
    b('practice_bank', 2, {
      title: 'Section 2 — Projectile Motion',
      sections: [
        {
          id: 'p17-s2',
          title: 'Twelve questions',
          items: [
            mcq('d2-1', 'The maximum range of a projectile on level ground is $ 80 $ m. Its maximum height, when fired at the range-maximising angle, is:',
              ['$ 80 $ m', '$ 40 $ m', '$ 20 $ m', '$ 10 $ m'], 2,
              '$ R_{\\max} = 4H_{\\max} $, so $ H_{\\max} = 80/4 = 20 $ m.'),
            num('d2-2', 'A projectile is launched at $ 30 $ m/s at $ 30° $. Find its time of flight. Take $ g=10 $ m/s².',
              '$ 3 $ s',
              '$ T = 2u\\sin\\theta/g = 2(30)(0.5)/10 = 3 $ s.'),
            mcq('d2-3', 'A ball thrown at $ 45° $ has range $ R $. At what smaller angle (same launch speed) is the range exactly $ R/2 $?',
              ['$ 15° $', '$ 22.5° $', '$ 30° $', '$ 37.5° $'], 0,
              '$ R \\propto \\sin 2\\theta $, and $ \\sin 90° = 1 $ at $ 45° $. For $ R/2 $: $ \\sin 2\\theta = 0.5 $, so $ 2\\theta = 30° $, giving $ \\theta = 15° $. (The other solution, $ 2\\theta = 150° $, gives $ \\theta = 75° $ — its complement, which gives the same range by the complementary-angle rule from page 5.)'),
            num('d2-4', 'A stone is projected horizontally at $ 20 $ m/s from a $ 45 $ m cliff. Find the horizontal distance it covers before landing. Take $ g=10 $ m/s².',
              '$ 60 $ m',
              '$ t=\\sqrt{2(45)/10}=3 $ s, so $ x=20(3)=60 $ m.'),
            mcq('d2-5', 'For a projectile fired at angle $ \\theta $, the ratio of maximum height to range is $ \\tan\\theta / 4 $. This ratio is largest when $ \\theta $ is:',
              ['$ 30° $', '$ 45° $', '$ 60° $', '$ 75° $'], 3,
              '$ H/R = \\tan\\theta/4 $ increases steadily as $ \\theta $ grows towards $ 90° $, since $ \\tan\\theta $ does. Of the four options, $ 75° $ has the largest tangent, so it gives the largest height-to-range ratio.'),
            num('d2-6', 'A projectile has time of flight $ 4 $ s and horizontal range $ 100 $ m. Find its speed of projection and angle. Take $ g=10 $ m/s².',
              '$ u=32.0 $ m/s at about $ 38.7° $',
              '$ u_x = 100/4=25 $ m/s. From $ T=2u_y/g $: $ u_y=10(4)/2=20 $ m/s. So $ u=\\sqrt{625+400}=\\sqrt{1025}=32.0 $ m/s and $ \\tan\\theta=20/25=0.8 $, giving $ \\theta=38.7° $.'),
            mcq('d2-7', 'A body is projected so that its horizontal range equals three times its maximum height. Its angle of projection is:',
              ['$ \\tan^{-1}(4/3) $', '$ \\tan^{-1}(3/4) $', '$ 45° $', '$ \\tan^{-1}(1/2) $'], 0,
              '$ R=3H $: $ \\dfrac{u^2\\sin2\\theta}{g}=3\\dfrac{u^2\\sin^2\\theta}{2g} $, so $ 2\\sin\\theta\\cos\\theta = \\dfrac{3\\sin^2\\theta}{2} $. Dividing both sides by $ \\sin\\theta $ gives $ 2\\cos\\theta = \\dfrac{3\\sin\\theta}{2} $, so $ \\tan\\theta = 4/3 $.'),
            num('d2-8', 'A ball is thrown at $ 40 $ m/s at $ 30° $ from the top of a $ 25 $ m building. Find the time to hit the ground. Take $ g=10 $ m/s².',
              '$ 5 $ s',
              '$ u_y=40(0.5)=20 $ m/s. $ -25=20t-5t^2 $, so $ t^2-4t-5=0 $, $ (t-5)(t+1)=0 $, $ t=5 $ s.'),
            mcq('d2-9', 'The equation of trajectory of a projectile is $ y = 10x - 2x^2 $ (SI units). Its angle of projection is:',
              ['$ \\tan^{-1}(2) $', '$ \\tan^{-1}(5) $', '$ \\tan^{-1}(10) $', '$ \\tan^{-1}(0.2) $'], 2,
              'The coefficient of $ x $ is $ \\tan\\theta $, so $ \\tan\\theta = 10 $.'),
            num('d2-10', 'A particle is projected up an incline of $ 30° $ at $ 20 $ m/s at $ 60° $ to the horizontal. Find its time of flight. Take $ g=10 $ m/s².',
              '$ 2.31 $ s',
              '$ \\theta-\\beta=30° $. $ T = 2u\\sin(\\theta-\\beta)/(g\\cos\\beta) = 2(20)(0.5)/(10 \\times 0.866) = 20/8.66 = 2.31 $ s.'),
            mcq('d2-11', 'Two projectiles are thrown with the same speed such that one makes an angle $ \\theta $ with the horizontal and the other makes the same angle with the vertical. If their ranges are equal, then $ \\theta $ equals:',
              ['Only $ 30° $, and no other angle', 'Only $ 45° $, and no other angle', 'Only $ 60° $, and no other angle', 'Any angle $ \\theta $'], 3,
              'An angle $ \\theta $ with the horizontal is the same launch as an angle $ (90°-\\theta) $ with the horizontal — which is $ \\theta $ with the vertical. These are complementary angles, so the ranges are equal for **any** $ \\theta $, not a special one.'),
            num('d2-12', 'A projectile has maximum height $ 20 $ m and time of flight $ 4 $ s. Find its vertical launch speed component $ u_y $, and the value of $ g $ these two are consistent with.',
              '$ u_y = 20 $ m/s, and $ g = 10 $ m/s²',
              'From $ T=2u_y/g $ and $ H=u_y^2/2g $, dividing one by the other gives $ H/T = u_y/4 $, so $ u_y = 4H/T = 4(20)/4 = 20 $ m/s. Substituting back into $ T=2u_y/g $: $ 4 = 2(20)/g $, so $ g = 10 $ m/s² — the standard value used throughout this chapter.'),
          ],
        },
      ],
    }),
    b('practice_bank', 3, {
      title: 'Section 3 — Relative Motion in 2D',
      sections: [
        {
          id: 'p17-s3',
          title: 'Ten questions',
          items: [
            mcq('d3-1', 'Rain falls vertically at $ 10 $ m/s. A man walks at $ 6 $ m/s. The rain appears to him to fall at:',
              ['$ 4 $ m/s', '$ 8 $ m/s', '$ 11.7 $ m/s', '$ 16 $ m/s'], 2,
              'Perpendicular vectors: $ |\\mathbf{v}_{rm}|=\\sqrt{10^2+6^2}=\\sqrt{136}=11.7 $ m/s.'),
            num('d3-2', 'Car A moves at $ 20 $ m/s east, car B at $ 15 $ m/s north. Find $ |\\mathbf{v}_{AB}| $.',
              '$ 25 $ m/s',
              '$ \\mathbf{v}_{AB}=20\\,\\hat{i}-15\\,\\hat{j} $, so $ |\\mathbf{v}_{AB}|=\\sqrt{400+225}=\\sqrt{625}=25 $ m/s.'),
            mcq('d3-3', 'Two bodies are projected simultaneously from the same point with different speeds and angles, on Earth. They will collide in mid-air only if:',
              ['Relative velocity is along the line joining them', 'They are launched with exactly the same speed', 'They are launched at exactly the same angle', 'They are launched at complementary angles'], 0,
              'Both share acceleration $ g $, so their relative acceleration is zero and one sees the other moving in a straight line at constant velocity — collision needs that line to pass through the other body\'s position, i.e. the relative velocity along the line joining them.'),
            num('d3-4', 'A swimmer can swim at $ 3 $ m/s in still water and faces a current of $ 4 $ m/s. Find her resultant speed if she swims perpendicular to the current (relative to water).',
              '$ 5 $ m/s',
              'Perpendicular components: $ \\sqrt{3^2+4^2}=5 $ m/s.'),
            mcq('d3-5', 'Two trains, each $ 100 $ m long, moving in opposite directions on parallel tracks at $ 20 $ m/s and $ 30 $ m/s cross each other in:',
              ['$ 2 $ s', '$ 4 $ s', '$ 5 $ s', '$ 10 $ s'], 1,
              'Their relative speed is $ 20+30=50 $ m/s (opposite directions), and they must cover a combined length of $ 200 $ m to fully pass, so $ t=200/50=4 $ s.'),
            num('d3-6', 'Ship A steams at $ 12 $ km/h due north. Ship B steams at $ 12 $ km/h due east. Find the velocity of B relative to A — its magnitude and direction.',
              '$ 12\\sqrt{2} = 17.0 $ km/h, towards the south-east',
              'With east $ = \\hat{i} $, north $ = \\hat{j} $: $ \\mathbf{v}_B = 12\\,\\hat{i} $ and $ \\mathbf{v}_A = 12\\,\\hat{j} $, so $ \\mathbf{v}_{BA} = \\mathbf{v}_B - \\mathbf{v}_A = 12\\,\\hat{i} - 12\\,\\hat{j} $ km/h. Two equal perpendicular components with the $ \\hat{j} $ part negative give a magnitude of $ 12\\sqrt{2} = 17.0 $ km/h, pointing south-east — B appears to pull ahead to the east while A leaves it behind to the south.'),
            mcq('d3-7', 'A man walking at $ 4 $ km/h finds rain falling vertically. When he doubles his speed, the rain appears to come at an angle $ \\theta $ to the vertical, where $ \\tan\\theta $ equals:',
              ['The ratio of his new speed to the rain\'s actual speed', '$ 1 $', '$ 2 $', 'Cannot be determined without the rain\'s speed'], 3,
              'At his original $ 4 $ km/h the rain appeared vertical, meaning its horizontal component was exactly $ 4 $ km/h. Doubling his speed to $ 8 $ km/h leaves a horizontal mismatch of $ 4 $ km/h, so $ \\tan\\theta = 4/v_r $ — which needs the rain\'s (vertical) speed to evaluate.'),
            num('d3-8', 'Two particles start simultaneously from the same point, one moving at $ 5 $ m/s east and the other at $ 12 $ m/s north. Find the rate at which the distance between them increases.',
              '$ 13 $ m/s',
              'This is exactly $ |\\mathbf{v}_{\\text{relative}}| $ for perpendicular velocities: $ \\sqrt{25+144}=13 $ m/s — constant, since both move at constant velocity.'),
            mcq('d3-9', 'A frame $ S\' $ moves relative to frame $ S $ with a constant velocity. Compared with observers in $ S $, observers in $ S\' $ measure:',
              ['A different acceleration for every particle', 'The same acceleration for any particle undergoing the same true motion', 'A different acceleration only if the particle is accelerating', 'No difference is possible to state without more information'], 1,
              'Frames in constant relative motion agree exactly about every acceleration — this is the derivation from page 13, and the reason the food-packet\'s "actual path" question has no answer.'),
            num('d3-10', 'A boat takes the shortest path across a $ 45 $ m river, landing directly opposite in $ 15 $ s. The river flows at $ 3 $ m/s. Find the boat\'s still-water speed.',
              '$ 4.24 $ m/s',
              'The shortest-path (zero-drift) crossing speed is $ \\sqrt{v_{br}^2-v_r^2} = d/t = 45/15 = 3 $ m/s. So $ v_{br}^2 = 3^2 + v_r^2 = 9+9 = 18 $, giving $ v_{br} = \\sqrt{18} = 4.24 $ m/s.'),
          ],
        },
      ],
    }),
    b('practice_bank', 4, {
      title: 'Section 4 — Circular Motion',
      sections: [
        {
          id: 'p17-s4',
          title: 'Ten questions',
          items: [
            mcq('d4-1', 'A particle moves in a circle of radius $ r $ with constant angular speed $ \\omega $. Its centripetal acceleration is:',
              ['$ \\omega r $', '$ \\omega^2 r $', '$ \\omega r^2 $', '$ \\omega^2 / r $'], 1,
              '$ a_c = \\omega^2 r $, from substituting $ v=r\\omega $ into $ v^2/r $.'),
            num('d4-2', 'A wheel of radius $ 0.5 $ m rotates at $ 4 $ rev/s. Find the linear speed of a point on its rim.',
              '$ 12.6 $ m/s',
              '$ \\omega = 2\\pi(4)=25.1 $ rad/s. $ v=r\\omega=0.5(25.1)=12.6 $ m/s.'),
            mcq('d4-3', 'In uniform circular motion, the angle between velocity and acceleration is always:',
              ['$ 0° $', '$ 45° $', '$ 90° $', '$ 180° $'], 2,
              'Uniform means $ a_t=0 $, leaving only the radial component, which is always perpendicular to the tangential velocity.'),
            num('d4-4', 'A particle in circular motion has $ a_t = 6 $ m/s² and $ a_r = 8 $ m/s². Find the net acceleration.',
              '$ 10 $ m/s²',
              'Perpendicular components: $ \\sqrt{36+64}=\\sqrt{100}=10 $ m/s².'),
            mcq('d4-5', 'A car moving at $ 10 $ m/s rounds a curve of radius $ 25 $ m. Its centripetal acceleration is:',
              ['$ 2.5 $ m/s²', '$ 4 $ m/s²', '$ 0.4 $ m/s²', '$ 250 $ m/s²'], 1,
              '$ a_c=v^2/r=100/25=4 $ m/s².'),
            num('d4-6', 'A particle starts from rest on a circle with constant angular acceleration $ 2 $ rad/s². Find the number of revolutions completed in $ 10 $ s.',
              'About $ 15.9 $ revolutions',
              '$ \\theta = \\frac{1}{2}\\alpha t^2 = \\frac{1}{2}(2)(100)=100 $ rad. Revolutions $ = 100/(2\\pi)=15.9 $.'),
            mcq('d4-7', 'Two pulleys of radii $ 6 $ cm and $ 18 $ cm are connected by a non-slipping belt. If the smaller rotates at $ 90 $ rev/min, the larger rotates at:',
              ['$ 30 $ rev/min', '$ 90 $ rev/min', '$ 270 $ rev/min', '$ 15 $ rev/min'], 0,
              'Belt-connected pulleys share rim speed, so $ \\omega \\propto 1/r $: $ \\omega_2 = \\omega_1(r_1/r_2)=90(6/18)=30 $ rev/min.'),
            num('d4-8', 'A particle moves on a circle of radius $ 2 $ m with speed $ v=5t $ m/s. Find the tangential and radial accelerations at $ t=2 $ s.',
              '$ a_t=5 $ m/s², $ a_r=50 $ m/s²',
              '$ a_t=dv/dt=5 $ m/s² (constant). At $ t=2 $ s, $ v=10 $ m/s, so $ a_r=v^2/r=100/2=50 $ m/s².'),
            mcq('d4-9', 'A car slows down steadily while going round a circular bend at constant radius. The angle between its velocity and its net acceleration is:',
              ['Acute', 'Exactly $ 90° $', 'Obtuse', 'Exactly $ 180° $'], 2,
              'Slowing down means $ a_t $ opposes the velocity, tilting the net acceleration backwards past $ 90° $ — obtuse. It cannot reach $ 180° $, because $ a_r $ is always present on a circular path and keeps the acceleration off the line of motion entirely.'),
            num('d4-10', 'The angular velocity of a particle changes from $ 10 $ rad/s to $ 20 $ rad/s in $ 5 $ s at constant angular acceleration. Find the angle turned through.',
              '$ 75 $ rad',
              '$ \\alpha = (20-10)/5=2 $ rad/s². $ \\theta=\\omega_0 t+\\frac{1}{2}\\alpha t^2 = 10(5)+\\frac{1}{2}(2)(25)=50+25=75 $ rad.'),
          ],
        },
      ],
    }),
    b('practice_bank', 5, {
      title: 'Section 5 — River-Boat and Rain Problems',
      sections: [
        {
          id: 'p17-s5a',
          title: 'Eight questions',
          items: [
            mcq('d5-1', 'A river 100 m wide flows at $ 5 $ m/s. A boat with still-water speed $ 5 $ m/s wants to cross to the point directly opposite. This is:',
              ['Possible, at $ 90° $ upstream', 'Possible, at $ 45° $ upstream', 'Impossible, since $ v_r=v_{br} $', 'Possible, at $ 30° $ upstream'], 2,
              '$ \\sin\\theta=v_r/v_{br}=1 $, giving $ \\theta=90° $ — pointing straight upstream, which cancels the current entirely and leaves zero crossing speed. Practically, this means it cannot actually be done.'),
            num('d5-2', 'A boat crosses a $ 200 $ m river in the shortest time of $ 25 $ s. If the current is $ 3 $ m/s, find the drift.',
              '$ 75 $ m',
              '$ v_{br}=200/25=8 $ m/s. Drift $ = v_r t = 3(25)=75 $ m.'),
            mcq('d5-3', 'An aircraft flies with a crosswind. Its ground speed compared with its air speed is:',
              ['Always the greater of the two speeds', 'Always the smaller of the two speeds', 'Could go either way, depending on the wind', 'Always exactly equal to the air speed'], 2,
              'A wind with a favourable component increases ground speed; an opposing component decreases it; a purely perpendicular wind changes only the direction, leaving speed close to unchanged — so no fixed relation holds in general.'),
            num('d5-4', 'Rain falls vertically at $ 5 $ km/h. A man walks at $ 5 $ km/h. Find the speed of the rain relative to him, and confirm it arrives at $ 45° $ to the vertical.',
              '$ 5\\sqrt{2} = 7.07 $ km/h, at $ 45° $ to the vertical',
              'With his velocity $ 5 $ km/h horizontal and the rain $ 5 $ km/h vertical, the relative velocity $ \\mathbf{v}_{rm} $ has equal horizontal and vertical parts of magnitude $ 5 $, giving $ \\tan\\theta = 5/5 = 1 $, so $ \\theta = 45° $ from the vertical — as stated. Its magnitude is $ \\sqrt{25+25} = 5\\sqrt{2} = 7.07 $ km/h.'),
            mcq('d5-5', 'A boat\'s still-water speed is less than the river\'s current speed. The boat can still manage to:',
              ['Cross to a point directly opposite where she started', 'Cross the river, ending up downstream of the starting point', 'Row directly upstream and hold her position', 'None of the above is possible'], 1,
              'Even if $ v_{br}<v_r $, steering with any across-river component still makes progress across — it will simply drift far downstream. Landing directly opposite or holding position upstream both need $ v_{br}\\geq v_r $.'),
            num('d5-6', 'A river flows at $ 4 $ km/h. A swimmer whose still-water speed is $ 5 $ km/h wants to cross by the shortest path. Find her time to cross a river $ 3 $ km wide.',
              '$ 1 $ h',
              'Shortest-path crossing speed $ = \\sqrt{25-16}=3 $ km/h. Time $ = 3/3=1 $ h.'),
            mcq('d5-7', 'A boat\'s resultant velocity while crossing a river is always the vector sum of:',
              ['The boat\'s steering velocity and the river\'s velocity', 'The boat\'s steering velocity, taken on its own', 'The river\'s velocity, taken on its own', 'The average of the two velocities'], 0,
              '$ \\mathbf{v}_b = \\mathbf{v}_{br} + \\mathbf{v}_r $ — the fundamental relation of this whole section.'),
            num('d5-8', 'An aircraft steers due east at $ 300 $ km/h air speed through a wind of $ 50 $ km/h blowing due south. Find its ground speed.',
              '$ 304 $ km/h',
              'Perpendicular components: $ \\sqrt{300^2+50^2}=\\sqrt{90000+2500}=\\sqrt{92500}=304.1 $ km/h.'),
          ],
        },
        {
          id: 'p17-s5b',
          title: 'Assertion and reason',
          items: [
            mcqFixed('d5-ar1', '**Assertion:** A boat steered straight across a flowing river always crosses in the least possible time.\n\n**Reason:** Steering straight across gives the largest possible across-river component of the boat\'s velocity.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 0,
              'Both are true, and R is exactly why A holds: the crossing time is $ d/(v_{br}\\cos\\theta) $, minimised when $ \\cos\\theta $ — and hence the across-river component — is largest, at $ \\theta=0 $.'),
            mcqFixed('d5-ar2', '**Assertion:** Two frames moving at constant velocity relative to each other always agree on the shape of a projectile\'s path.\n\n**Reason:** Frames in constant relative motion agree about every acceleration.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 3,
              'A is **false** — the food-packet example shows a straight line in one frame and a parabola in the other, precisely because the two frames have different velocities of their own. R is **true**, but it explains why they agree about acceleration, not why paths would look the same.'),
            mcqFixed('d5-ar3', '**Assertion:** A body moving in uniform circular motion has a constant acceleration vector.\n\n**Reason:** The magnitude of the centripetal acceleration, $ v^2/r $, does not change in uniform circular motion.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 3,
              'A is **false** — the acceleration constantly changes direction, so it is not a constant vector even though its magnitude is fixed. R is **true**, and is in fact part of why students mistakenly think A is true.'),
            mcqFixed('d5-ar4', '**Assertion:** The formula $ R=u^2\\sin2\\theta/g $ gives the correct range for a projectile launched from the top of a tower onto level ground below.\n\n**Reason:** The formula was derived assuming the projectile lands at the same height it was launched from.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 3,
              'A is **false** — launching from a tower breaks the same-height assumption, so the formula does not apply. R is **true**, and is precisely the reason A fails.'),
          ],
        },
      ],
    }),
    b('callout', 6, {
      variant: 'note',
      title: 'What to do with your score',
      markdown: 'Do not average the five sections into one number.\n\nFind your **weakest section** and return to the pages behind it. Section 1 → pages 1–3. Section 2 → pages 4–9. Section 3 → pages 13–14. Section 4 → pages 10–12. Section 5 → page 14.\n\nA section below about 60% is telling you something specific — and that is worth more of your time than repeating a section you already got right.',
    }),
  ],
};

withDb(async (db) => {
  const bookId = await ensureChapter(db);
  await upsertPages(db, bookId, [p15, p16, p17]);
}).then(() => { console.log('\nWave 3 done — p15–p17. Chapter is now 18 pages.'); process.exit(0); })
  .catch((e) => { console.error(e); process.exit(1); });
