'use strict';
/**
 * Class 11 Physics · Chapter 1 "Units and Dimensions" — pages 14–15.
 *   p14 — every NCERT exercise from the chapter, transcribed verbatim (Rule 0)
 *         and worked in full.
 *   p15 — a JEE/NEET drill bank in five sections.
 *
 * ATTRIBUTION RULE: items adapted from the founder's objective-physics reference
 * carry source 'mcq' and NO badge. Only genuine exam questions carry 'jee_neet'
 * with the exam + year. The reference book is never named to a student.
 *
 * Exercises 1.6 and 1.8(b) are deliberately NOT here — they are vernier /
 * screw-gauge items and move to the Experimental Physics chapter with the rest
 * of the instrument content (founder decision, 2026-07-29). A note on the page
 * says so, so the gap is visible rather than silent.
 *
 * Run: node scripts/physics11-book/build_ch1_practice.js
 */
const { b, mcq, mcqFixed, num, ensureChapter, upsertPages, withDb } = require('./_book_ch1');

// ── p14 · NCERT Exercises ────────────────────────────────────────────────────
const p14 = {
  page_number: 14,
  slug: 'practice-ncert-exercises',
  title: 'Practice — NCERT Exercises',
  subtitle: 'Every exercise from the chapter, worked in full',
  page_type: 'lesson',
  blocks: [
    b('text', 0, {
      markdown: 'These are the exercises printed at the end of the NCERT chapter, word for word. Work each one on paper before you open the solution — reading a worked answer feels like learning and is not.\n\nThey are grouped by skill rather than by number, so related ones sit together.',
    }),
    b('callout', 1, {
      variant: 'note',
      title: 'Two exercises have moved',
      markdown: 'NCERT Exercises **1.6** and **1.8(b)** are about vernier callipers and the screw gauge. Those belong with the laboratory work, so they move to the **Experimental Physics** chapter along with the rest of the instrument content.\n\nEverything else from the chapter is below.',
    }),
    b('practice_bank', 2, {
      title: 'NCERT Exercises 1.1 – 1.17',
      intro: 'Fifteen exercises across four themes. Answers are worked in full, in the same voice as the chapter.',
      sections: [
        {
          id: 'ncert-conversion',
          title: 'A · Units and conversion',
          blurb: 'Exercises 1.1, 1.2, 1.3, 1.5.',
          items: [
            num('n-1-1', 'Fill in the blanks:\n\n(a) The volume of a cube of side 1 cm is equal to ..... m³\n(b) The surface area of a solid cylinder of radius 2.0 cm and height 10.0 cm is equal to ... (mm)²\n(c) A vehicle moving with a speed of 18 km h⁻¹ covers .... m in 1 s\n(d) The relative density of lead is 11.3. Its density is .... g cm⁻³ or .... kg m⁻³.',
              '(a) $ 10^{-6}\\ \\text{m}^{3} $  (b) $ 1.5 \\times 10^{4}\\ \\text{mm}^{2} $  (c) 5 m  (d) $ 11.3\\ \\text{g cm}^{-3} $ or $ 1.13 \\times 10^{4}\\ \\text{kg m}^{-3} $',
              '(a) $ 1\\ \\text{cm} = 10^{-2}\\ \\text{m} $, so $ V = (10^{-2})^{3} = 10^{-6}\\ \\text{m}^{3} $. Remember to cube the conversion factor.\n\n(b) Work in millimetres from the start: $ r = 20 $ mm, $ h = 100 $ mm.\n\n$ A = 2\\pi r(r + h) = 2\\pi(20)(120) = 4800\\pi \\approx 1.5 \\times 10^{4}\\ \\text{mm}^{2} $\n\n(c) $ 18\\ \\text{km h}^{-1} = \\frac{18 \\times 1000}{3600} = 5\\ \\text{m s}^{-1} $, so it covers 5 m in one second.\n\n(d) Relative density is a pure ratio, so the density is $ 11.3 \\times 1\\ \\text{g cm}^{-3} = 11.3\\ \\text{g cm}^{-3} $. Converting: $ 11.3 \\times 10^{3}\\ \\text{kg m}^{-3} = 1.13 \\times 10^{4}\\ \\text{kg m}^{-3} $.',
              'ncert_exercise', 'NCERT Ex 1.1'),
            num('n-1-2', 'Fill in the blanks by suitable conversion of units:\n\n(a) $ 1\\ \\text{kg m}^{2}\\text{s}^{-2} $ = .... $ \\text{g cm}^{2}\\text{s}^{-2} $\n(b) 1 m = ..... ly\n(c) $ 3.0\\ \\text{m s}^{-2} $ = .... $ \\text{km h}^{-2} $\n(d) $ G = 6.67 \\times 10^{-11}\\ \\text{N m}^{2}(\\text{kg})^{-2} $ = .... $ (\\text{cm})^{3}\\text{s}^{-2}\\text{g}^{-1} $',
              '(a) $ 10^{7} $  (b) $ 1.057 \\times 10^{-16} $  (c) $ 3.9 \\times 10^{4} $  (d) $ 6.67 \\times 10^{-8} $',
              '(a) Mass $ \\times 10^{3} $, length squared $ \\times (10^{2})^{2} = 10^{4} $. Together $ 10^{7} $.\n\n(b) One light year is $ 9.46 \\times 10^{15} $ m, so $ 1\\ \\text{m} = \\frac{1}{9.46 \\times 10^{15}} = 1.057 \\times 10^{-16} $ ly.\n\n(c) $ 3.0 \\times \\frac{1}{1000}\\ \\text{km} \\times (3600)^{2}\\ \\text{h}^{-2} = 3.0 \\times 10^{-3} \\times 1.296 \\times 10^{7} = 3.9 \\times 10^{4}\\ \\text{km h}^{-2} $.\n\n(d) $ [G] = [\\text{M}^{-1}\\text{L}^{3}\\text{T}^{-2}] $, so $ n_2 = 6.67 \\times 10^{-11} \\times (10^{3})^{-1}(10^{2})^{3} = 6.67 \\times 10^{-11} \\times 10^{3} = 6.67 \\times 10^{-8} $.',
              'ncert_exercise', 'NCERT Ex 1.2'),
            num('n-1-3', 'A calorie is a unit of heat and it equals about 4.2 J, where 1 J = 1 kg m² s⁻². Suppose we employ a system of units in which the unit of mass equals $ \\alpha $ kg, the unit of length equals $ \\beta $ m and the unit of time is $ \\gamma $ s. Show that a calorie has a magnitude $ 4.2\\,\\alpha^{-1}\\beta^{-2}\\gamma^{2} $ in terms of the new units.',
              '$ 4.2\\,\\alpha^{-1}\\beta^{-2}\\gamma^{2} $',
              'Energy has $ a = 1 $, $ b = 2 $, $ c = -2 $.\n\n$ n_2 = n_1\\left[\\frac{M_1}{M_2}\\right]^{1}\\left[\\frac{L_1}{L_2}\\right]^{2}\\left[\\frac{T_1}{T_2}\\right]^{-2} = 4.2\\left[\\frac{1}{\\alpha}\\right]\\left[\\frac{1}{\\beta}\\right]^{2}\\left[\\frac{1}{\\gamma}\\right]^{-2} $\n\n$ = 4.2\\,\\alpha^{-1}\\beta^{-2}\\gamma^{2} $\n\nThis is worked step by step on page 4 of this chapter.',
              'ncert_exercise', 'NCERT Ex 1.3'),
            num('n-1-5', 'A new unit of length is chosen such that the speed of light in vacuum is unity. What is the distance between the Sun and the Earth in terms of the new unit if light takes 8 min and 20 s to cover this distance?',
              '500 new units',
              'The speed of light is 1 new unit of length per second, by choice.\n\nTime taken $ = 8 \\times 60 + 20 = 500 $ s.\n\nDistance $ = \\text{speed} \\times \\text{time} = 1 \\times 500 = 500 $ new units of length.\n\nThis is exactly how the light year and the light minute work as units — the number *is* the travel time.',
              'ncert_exercise', 'NCERT Ex 1.5'),
          ],
        },
        {
          id: 'ncert-sigfig',
          title: 'B · Significant figures',
          blurb: 'Exercises 1.10, 1.11, 1.12.',
          items: [
            num('n-1-10', 'State the number of significant figures in the following:\n\n(a) 0.007 m²  (b) $ 2.64 \\times 10^{24} $ kg  (c) 0.2370 g cm⁻³  (d) 6.320 J  (e) 6.032 N m⁻²  (f) 0.0006032 m²',
              '(a) 1  (b) 3  (c) 4  (d) 4  (e) 4  (f) 4',
              '(a) Leading zeros are placeholders — only the 7 counts.\n(b) The power of ten is ignored: 2, 6, 4.\n(c) 2, 3, 7 and the trailing 0 after the decimal point.\n(d) All four digits count.\n(e) The sandwiched zero counts.\n(f) Leading zeros out, then 6, 0, 3, 2.',
              'ncert_exercise', 'NCERT Ex 1.10'),
            num('n-1-11', 'The length, breadth and thickness of a rectangular sheet of metal are 4.234 m, 1.005 m and 2.01 cm respectively. Give the area and volume of the sheet to correct significant figures.',
              'Area $ = 8.72\\ \\text{m}^{2} $; volume $ = 0.0855\\ \\text{m}^{3} $',
              'Thickness $ = 2.01\\ \\text{cm} = 0.0201 $ m.\n\nTotal surface area $ = 2(lb + bt + tl) = 2(4.234 \\times 1.005 + 1.005 \\times 0.0201 + 0.0201 \\times 4.234) = 8.7209\\ \\text{m}^{2} $.\n\nThe thickness has the fewest significant figures — 3 — so the area is $ 8.72\\ \\text{m}^{2} $.\n\nVolume $ = 4.234 \\times 1.005 \\times 0.0201 = 0.08552\\ \\text{m}^{3} $, which to 3 significant figures is $ 0.0855\\ \\text{m}^{3} $.',
              'ncert_exercise', 'NCERT Ex 1.11'),
            num('n-1-12', 'The mass of a box measured by a grocer\'s balance is 2.30 kg. Two gold pieces of masses 20.15 g and 20.17 g are added to the box. What is (a) the total mass of the box, (b) the difference in the masses of the pieces to correct significant figures?',
              '(a) 2.3 kg  (b) 0.02 g',
              '(a) In kilograms: $ 2.30 + 0.02015 + 0.02017 = 2.34032 $ kg. This is an addition, so decimal places decide — and 2.30 kg has only two. Rounded, the total is 2.34 kg; taking the balance\'s stated precision of 2.3 kg strictly, NCERT gives **2.3 kg**.\n\n(b) $ 20.17 - 20.15 = 0.02 $ g. Both were measured to two decimal places, so the difference keeps two decimal places.\n\nNotice the sting in (b): two measurements each good to four significant figures produced a difference with only **one**. That is the danger of subtracting nearly equal numbers, met again on page 8.',
              'ncert_exercise', 'NCERT Ex 1.12'),
          ],
        },
        {
          id: 'ncert-estimation',
          title: 'C · Estimation and order of magnitude',
          blurb: 'Exercises 1.7, 1.9, 1.14, 1.15, 1.17.',
          items: [
            num('n-1-7', 'A student measures the thickness of a human hair by looking at it through a microscope of magnification 100. He makes 20 observations and finds that the average width of the hair in the field of view of the microscope is 3.5 mm. What is the estimate on the thickness of hair?',
              '0.035 mm',
              'The microscope magnifies 100 times, so the real width is the observed width divided by 100:\n\n$ \\text{thickness} = \\frac{3.5\\ \\text{mm}}{100} = 0.035\\ \\text{mm} $\n\nThe 20 observations matter for a different reason — averaging them beats down the random error, as on page 7.',
              'ncert_exercise', 'NCERT Ex 1.7'),
            num('n-1-9', 'The photograph of a house occupies an area of 1.75 cm² on a 35 mm slide. The slide is projected on to a screen, and the area of the house on the screen is 1.55 m². What is the linear magnification of the projector-screen arrangement?',
              'About 94',
              'Areal magnification is the ratio of the two areas — but both must be in the same units first.\n\n$ 1.55\\ \\text{m}^{2} = 1.55 \\times 10^{4}\\ \\text{cm}^{2} $\n\n$ \\text{areal magnification} = \\frac{1.55 \\times 10^{4}}{1.75} = 8857 $\n\nArea scales as the square of length, so the linear magnification is the square root:\n\n$ \\sqrt{8857} \\approx 94 $',
              'ncert_exercise', 'NCERT Ex 1.9'),
            num('n-1-14', 'The unit of length convenient on the atomic scale is known as an angstrom: 1 Å = 10⁻¹⁰ m. The size of a hydrogen atom is about 0.5 Å. What is the total atomic volume in m³ of a mole of hydrogen atoms?',
              'About $ 3 \\times 10^{-7}\\ \\text{m}^{3} $',
              'Radius $ = 0.5\\ \\text{Å} = 0.5 \\times 10^{-10} $ m.\n\nVolume of one atom $ = \\frac{4}{3}\\pi r^{3} = \\frac{4}{3}(3.14)(0.5 \\times 10^{-10})^{3} = 5.236 \\times 10^{-31}\\ \\text{m}^{3} $.\n\nA mole contains $ 6.022 \\times 10^{23} $ atoms, so\n\n$ V = 6.022 \\times 10^{23} \\times 5.236 \\times 10^{-31} = 3.15 \\times 10^{-7} \\approx 3 \\times 10^{-7}\\ \\text{m}^{3} $',
              'ncert_exercise', 'NCERT Ex 1.14'),
            num('n-1-15', 'One mole of an ideal gas at standard temperature and pressure occupies 22.4 L (molar volume). What is the ratio of molar volume to the atomic volume of a mole of hydrogen? (Take the size of a hydrogen molecule to be about 1 Å.) Why is this ratio so large?',
              'About $ 7 \\times 10^{4} $',
              'Molar volume $ = 22.4\\ \\text{L} = 22.4 \\times 10^{-3}\\ \\text{m}^{3} $.\n\nThe atomic volume of a mole is $ 3.15 \\times 10^{-7}\\ \\text{m}^{3} $ from the previous exercise.\n\n$ \\text{ratio} = \\frac{22.4 \\times 10^{-3}}{3.15 \\times 10^{-7}} \\approx 7 \\times 10^{4} $\n\n**Why so large:** in a gas the molecules are separated by distances enormously greater than their own size. The molecules themselves occupy only about one part in seventy thousand of the container — a gas is very nearly empty space, which is exactly why gases can be compressed and liquids cannot.',
              'ncert_exercise', 'NCERT Ex 1.15'),
            num('n-1-17', 'The Sun is a hot plasma with its inner core at a temperature exceeding $ 10^{7} $ K, and its outer surface at about 6000 K. At these high temperatures, no substance remains in a solid or liquid phase. In what range do you expect the mass density of the Sun to be — in the range of densities of solids and liquids, or of gases? Check if your guess is correct from the following data: mass of the Sun $ = 2.0 \\times 10^{30} $ kg, radius of the Sun $ = 7.0 \\times 10^{8} $ m.',
              'About $ 1.4 \\times 10^{3}\\ \\text{kg m}^{-3} $ — the range of solids and liquids',
              '$ V = \\frac{4}{3}\\pi R^{3} = \\frac{4}{3}(3.14)(7.0 \\times 10^{8})^{3} = 1.44 \\times 10^{27}\\ \\text{m}^{3} $\n\n$ \\rho = \\frac{M}{V} = \\frac{2.0 \\times 10^{30}}{1.44 \\times 10^{27}} = 1.4 \\times 10^{3}\\ \\text{kg m}^{-3} $\n\nThat is in the range of solids and liquids — a little denser than water — even though the Sun is a gas-like plasma throughout.\n\n**Why:** the Sun\'s own gravity compresses it enormously. Density and phase are different questions; a hot plasma held under that much pressure can be as dense as a liquid.',
              'ncert_exercise', 'NCERT Ex 1.17'),
          ],
        },
        {
          id: 'ncert-reasoning',
          title: 'D · Reasoning and dimensional arguments',
          blurb: 'Exercises 1.4, 1.8(a), 1.8(c), 1.13, 1.16.',
          items: [
            num('n-1-4', 'Explain this statement clearly: "To call a dimensional quantity large or small is meaningless without specifying a standard for comparison." In view of this, reframe the following statements wherever necessary:\n\n(a) atoms are very small objects\n(b) a jet plane moves with great speed\n(c) the mass of Jupiter is very large\n(d) the air inside this room contains a large number of molecules\n(e) a proton is much more massive than an electron\n(f) the speed of sound is much smaller than the speed of light',
              'Reframe (a)–(d); (e) and (f) are already comparative and need no change',
              'The point is that "large" and "small" are only meaningful **relative to something**. A metre is large for an insect and small for a road.\n\n(a) An atom is much smaller than the sharp tip of a pin.\n(b) A jet plane moves faster than a superfast train.\n(c) The mass of Jupiter is very large compared with the mass of the Earth.\n(d) The air in this room contains far more molecules than there are grains of sand on a beach.\n(e) Already correct — a proton is compared with an electron.\n(f) Already correct — the two speeds are compared with each other.\n\n(e) and (f) are fine precisely because each already names its standard of comparison.',
              'ncert_exercise', 'NCERT Ex 1.4'),
            num('n-1-8a', 'You are given a thread and a metre scale. How will you estimate the diameter of the thread?',
              'Wind it into a close coil and divide the coil length by the number of turns',
              'A single thread is far thinner than the 1 mm least count of a metre scale, so measuring it directly is hopeless.\n\nInstead, wind the thread closely around a pencil so that consecutive turns touch, with no gaps and no overlaps. Count the number of turns $ n $ and measure the total length $ L $ of the coil with the metre scale.\n\n$ \\text{diameter} = \\frac{L}{n} $\n\nThis is a general and rather beautiful trick: **measure many of a thing at once and divide.** It multiplies your instrument\'s effective precision by $ n $ — the same idea as timing 100 oscillations of a pendulum instead of one.',
              'ncert_exercise', 'NCERT Ex 1.8(a)'),
            num('n-1-8c', 'The mean diameter of a thin brass rod is to be measured. Why is a set of 100 measurements of the diameter expected to yield a more reliable estimate than a set of 5 measurements only?',
              'Because random error in the mean falls as $ 1/\\sqrt{N} $',
              'Random errors scatter both above and below the true value, so they partly cancel when you average. The more readings you average, the more complete that cancellation is.\n\nQuantitatively, the random error in the mean falls as $ \\frac{1}{\\sqrt{N}} $. Going from 5 readings to 100 is a twenty-fold increase, which reduces the random error by $ \\sqrt{20} \\approx 4.5 $ times.\n\n**One honest caution:** this only helps against *random* error. If the instrument has a zero error, all 100 readings are wrong in the same direction and averaging achieves nothing at all.',
              'ncert_exercise', 'NCERT Ex 1.8(c)'),
            num('n-1-13', 'A famous relation in physics relates the moving mass $ m $ to the rest mass $ m_0 $ of a particle in terms of its speed $ v $ and the speed of light $ c $. A boy recalls the relation almost correctly but forgets where to put the constant $ c $. He writes $ m = \\frac{m_0}{(1 - v^{2})^{1/2}} $. Guess where to put the missing $ c $.',
              '$ m = \\frac{m_0}{\\left(1 - \\frac{v^{2}}{c^{2}}\\right)^{1/2}} $',
              'Look at the bracket: $ 1 - v^{2} $. The 1 is a pure number, and only quantities with the same dimensions may be subtracted — so $ v^{2} $ must be made dimensionless too.\n\nThe only way to do that with the constants available is to divide by another squared speed. The speed of light is the squared speed on offer, so\n\n$ m = \\frac{m_0}{\\left(1 - \\frac{v^{2}}{c^{2}}\\right)^{1/2}} $\n\nThis is dimensional analysis doing something genuinely impressive: recovering a relativity formula without knowing any relativity.',
              'ncert_exercise', 'NCERT Ex 1.13'),
            num('n-1-16', 'Explain this common observation clearly: if you look out of the window of a fast moving train, the nearby trees, houses etc. seem to move rapidly in a direction opposite to the train\'s motion, but the distant objects (hill tops, the Moon, the stars etc.) seem to be stationary.',
              'Because the angle a moving observer sweeps out shrinks as the object gets further away',
              'What your eye actually detects is not the object moving, but the **angle** to it changing.\n\nIf the train moves a distance $ d $ and the object is at a distance $ D $, the angle swept is roughly\n\n$ \\theta \\approx \\frac{d}{D} $\n\nFor a nearby tree, $ D $ is small, so $ \\theta $ is large — the tree appears to whip past. For a hilltop or the Moon, $ D $ is enormous, so $ \\theta $ is almost zero and the object seems fixed.\n\nThis is the same geometry as the **parallax** method for measuring astronomical distances: measure the tiny angle, know your own baseline, and get the distance.',
              'ncert_exercise', 'NCERT Ex 1.16'),
          ],
        },
      ],
    }),
  ],
};

// ── p15 · JEE & NEET drill ───────────────────────────────────────────────────
const p15 = {
  page_number: 15,
  slug: 'practice-jee-neet-drill',
  title: 'Practice — JEE and NEET Drill',
  subtitle: 'Forty-five items, sorted by the skill each one tests',
  page_type: 'lesson',
  blocks: [
    b('text', 0, {
      markdown: 'Five sections, one skill each. Work through a whole section in one sitting rather than dipping in — the point is to make each skill automatic, and that only happens with repetition close together.\n\nItems marked with an exam name and year are past questions from that paper. The rest are practice items built to the same shapes.',
    }),
    b('practice_bank', 1, {
      title: 'Chapter drill',
      intro: 'Section A is warm-up. Section E is exam-level.',
      sections: [
        {
          id: 'drill-sigfig',
          title: 'A · Significant figures and rounding',
          blurb: 'Eight items. These should take well under a minute each.',
          items: [
            mcq('d-a1', 'The number of significant figures in 0.0310 is:',
              ['2', '3', '4', '5'], 1,
              'Leading zeros are placeholders. The 3, the 1 and the trailing 0 are significant — three in all.'),
            mcq('d-a2', 'The number of significant figures in $ 4.8000 \\times 10^{4} $ and in 48000.50 are respectively:',
              ['5 and 6', '5 and 7', '2 and 7', '2 and 6'], 1,
              '$ 4.8000 \\times 10^{4} $ has the digits 4, 8, 0, 0, 0 — five. In 48000.50 every digit counts once a decimal point is present, giving seven.',
              'jee_neet', 'JEE Main 2013'),
            mcq('d-a3', 'The result of $ (3.20 + 4.80) \\times 10^{5} $ has how many significant figures?',
              ['5', '4', '3', '2'], 2,
              '$ 3.20 + 4.80 = 8.00 $, and both inputs have two decimal places, so the sum keeps two: 8.00. That is three significant figures.'),
            mcq('d-a4', 'The value of $ (5.0 \\times 10^{-6})(5.0 \\times 10^{-8}) $ with due regard to significant figures is:',
              ['$ 25 \\times 10^{-14} $', '$ 25.0 \\times 10^{-14} $', '$ 2.50 \\times 10^{-13} $', '$ 2.5 \\times 10^{-13} $'], 3,
              'Both factors have 2 significant figures, so the answer must too. And proper scientific notation needs a front number between 1 and 10, which rules out the first two.'),
            mcq('d-a5', 'When 97.52 is divided by 2.54, the correct result is:',
              ['38.3937', '38.394', '38.39', '38.4'], 3,
              'The divisor 2.54 has 3 significant figures — the fewest — so the answer keeps 3: 38.4.'),
            mcq('d-a6', 'Subtracting 0.2 kg from 34 kg and expressing the result properly gives:',
              ['33.8 kg', '33.80 kg', '34.0 kg', '34 kg'], 3,
              'Subtraction, so decimal places decide. The value 34 kg has no decimal places at all, so the answer can have none either: 33.8 rounds to 34 kg.'),
            mcq('d-a7', 'A block has $ l = 12 $ cm, $ b = 6 $ cm and $ t = 2.45 $ cm. Its volume to the correct significant figures is:',
              ['176.4 cm³', '176 cm³', '$ 1.8 \\times 10^{2} $ cm³', '$ 2 \\times 10^{2} $ cm³'], 3,
              '$ 12 \\times 6 \\times 2.45 = 176.4\\ \\text{cm}^{3} $. But the breadth 6 cm carries only **one** significant figure — the weakest input — so the volume must be given to one: $ 2 \\times 10^{2}\\ \\text{cm}^{3} $.'),
            mcq('d-a8', 'Rounding 4.7250 and 4.7350 to three significant figures gives:',
              ['4.72 and 4.73', '4.73 and 4.74', '4.72 and 4.74', '4.73 and 4.73'], 2,
              'The dropped part is exactly 5 in both cases, so round to leave the preceding digit even. In 4.7250 the 2 is already even, so it stays: 4.72. In 4.7350 the 3 is odd, so it rises to 4: 4.74.'),
          ],
        },
        {
          id: 'drill-units',
          title: 'B · Units, conversion and order of magnitude',
          blurb: 'Nine items.',
          items: [
            mcq('d-b1', 'Which of these is **not** a unit of time?',
              ['Leap year', 'Shake', 'Light year', 'Solar day'], 2,
              'A light year is the distance light travels in a year — a length. A shake is $ 10^{-8} $ s, used in nuclear physics.'),
            mcq('d-b2', 'The parsec is a unit of:',
              ['Time', 'Distance', 'Frequency', 'Angular acceleration'], 1,
              'One parsec is about $ 3.08 \\times 10^{16} $ m, roughly 3.26 light years. The name comes from "parallax second".'),
            mcq('d-b3', 'One light year is equal to:',
              ['$ 9.46 \\times 10^{9} $ km', '$ 9.46 \\times 10^{10} $ km', '$ 9.46 \\times 10^{12} $ km', '$ 9.46 \\times 10^{15} $ km'], 2,
              'A light year is $ 9.46 \\times 10^{15} $ **m**, and dividing by $ 10^{3} $ gives $ 9.46 \\times 10^{12} $ km. The trap is $ 9.46 \\times 10^{15} $ km — that is the value in metres, offered unchanged.'),
            mcq('d-b4', 'In the SI system, the unit of thermodynamic temperature is:',
              ['Degree centigrade', 'Kelvin', 'Degree celsius', 'Degree fahrenheit'], 1,
              'The kelvin is one of the seven base units, and it takes no degree sign — write 300 K, never 300 °K.'),
            mcq('d-b5', 'A new unit of length is chosen so that the speed of light in vacuum is unity. If light takes 8 min 20 s to travel from the Sun to the Earth, that distance in the new unit is:',
              ['300', '400', '500', '600'], 2,
              'Time $ = 500 $ s, and speed is 1 new unit per second, so distance $ = 500 $ new units.'),
            mcq('d-b6', 'One kilowatt-hour is equal to:',
              ['$ 3.6 \\times 10^{4} $ J', '$ 3.6 \\times 10^{6} $ J', '$ 7.3 \\times 10^{6} $ J', '$ 3.6 \\times 10^{3} $ J'], 1,
              '$ 1\\ \\text{kWh} = 1000\\ \\text{W} \\times 3600\\ \\text{s} = 3.6 \\times 10^{6} $ J. This is the "unit" on an electricity bill.'),
            mcq('d-b7', 'Which quantity has a unit but is dimensionless?',
              ['Velocity gradient', 'Plane angle', 'Strain', 'Relative density'], 1,
              'A plane angle is arc over radius, so it is dimensionless — but it still has the radian as a named unit. Strain and relative density are dimensionless **and** unitless; velocity gradient has dimensions $ [\\text{T}^{-1}] $.'),
            mcq('d-b8', 'The order of magnitude of the mass of the Sun, $ 2.0 \\times 10^{30} $ kg, is:',
              ['$ 10^{29} $ kg', '$ 10^{30} $ kg', '$ 10^{31} $ kg', '$ 10^{32} $ kg'], 1,
              'The front number 2.0 is below 5, so the power stays as it is.'),
            mcq('d-b9', 'In a system where the unit of mass is 10 kg, the unit of length is 1 km and the unit of time is 1 minute, the value of 1 joule is:',
              ['360', '3.6', '$ 36 \\times 10^{5} $', '$ 36 \\times 10^{-5} $'], 3,
              'Energy has $ a = 1, b = 2, c = -2 $.\n\n$ n_2 = 1 \\times \\left(\\frac{1}{10}\\right)\\left(\\frac{1}{1000}\\right)^{2}\\left(\\frac{1}{60}\\right)^{-2} = 10^{-1} \\times 10^{-6} \\times 3600 = 3.6 \\times 10^{-4} = 36 \\times 10^{-5} $'),
          ],
        },
        {
          id: 'drill-errors',
          title: 'C · Errors and their propagation',
          blurb: 'Ten items. Decide sum-or-product before you calculate.',
          items: [
            mcq('d-c1', 'The radius of a ball is $ (5.2 \\pm 0.2) $ cm. The percentage error in its volume is about:',
              ['11%', '4%', '7%', '9%'], 0,
              '$ V \\propto r^{3} $, so $ \\frac{\\Delta V}{V} = 3\\frac{\\Delta r}{r} = 3 \\times \\frac{0.2}{5.2} = 11.5\\% $, about 11%.'),
            mcq('d-c2', 'A physical quantity is $ Q = \\frac{x^{3}y^{2}}{z} $. The percentage errors in $ x $, $ y $ and $ z $ are 1%, 2% and 4%. The percentage error in $ Q $ is:',
              ['4%', '3%', '11%', '1%'], 2,
              '$ 3(1\\%) + 2(2\\%) + 1(4\\%) = 3 + 4 + 4 = 11\\% $.',
              'jee_neet', 'Karnataka CET 2013'),
            mcq('d-c3', 'In a simple pendulum experiment, the maximum percentage error in the length is 2% and in the time period is 3%. The maximum percentage error in $ g $ is:',
              ['5%', '6%', '7%', '8%'], 3,
              '$ g = \\frac{4\\pi^{2}L}{T^{2}} $, so $ \\frac{\\Delta g}{g} = \\frac{\\Delta L}{L} + 2\\frac{\\Delta T}{T} = 2\\% + 2(3\\%) = 8\\% $.',
              'jee_neet', 'Kerala CEE 2014'),
            mcq('d-c4', 'A body travels $ (13.8 \\pm 0.2) $ m in $ (4.0 \\pm 0.3) $ s. Its velocity within error limits is:',
              ['$ (3.45 \\pm 0.2)\\ \\text{m s}^{-1} $', '$ (3.45 \\pm 0.3)\\ \\text{m s}^{-1} $', '$ (3.45 \\pm 0.4)\\ \\text{m s}^{-1} $', '$ (3.45 \\pm 0.5)\\ \\text{m s}^{-1} $'], 1,
              '$ v = \\frac{13.8}{4.0} = 3.45\\ \\text{m s}^{-1} $.\n\n$ \\frac{\\Delta v}{v} = \\frac{0.2}{13.8} + \\frac{0.3}{4.0} = 0.0145 + 0.075 = 0.0895 $\n\n$ \\Delta v = 0.0895 \\times 3.45 = 0.31 \\approx 0.3\\ \\text{m s}^{-1} $'),
            mcq('d-c5', 'If the percentage error in the radius of a sphere is 2%, the percentage error in its surface area is:',
              ['1%', '2%', '4%', '6%'], 2,
              '$ S = 4\\pi r^{2} $, so the exponent 2 doubles the error: $ 2 \\times 2\\% = 4\\% $. (Had the question asked for volume, the cube would have given 6%.)'),
            mcq('d-c6', 'A quantity is $ Q = \\frac{A^{3}B^{3}}{C\\sqrt{D}} $. If the percentage errors in $ A $, $ B $, $ C $ and $ D $ are 2%, 1%, 3% and 4%, the percentage error in $ Q $ is:',
              ['± 8%', '± 10%', '± 12%', '± 14%'], 3,
              '$ 3(2) + 3(1) + 1(3) + \\frac{1}{2}(4) = 6 + 3 + 3 + 2 = 14\\% $. The square root contributes only half of D\'s error.'),
            mcq('d-c7', 'Which of the following measurements is the most precise?',
              ['5.00 mm', '5.00 cm', '5.00 m', '5.00 km'], 0,
              'All four are quoted to three significant figures, so the uncertainty sits in the last digit of each — but that last digit is 0.01 mm in the first case and 0.01 km in the last. The smallest absolute uncertainty is the most precise measurement.'),
            mcq('d-c8', 'Two resistors $ (5.0 \\pm 0.2)\\ \\text{k}\\Omega $ and $ (10.0 \\pm 0.1)\\ \\text{k}\\Omega $ are joined in **series**. The percentage error in the total resistance is:',
              ['1%', '2%', '3%', '5%'], 1,
              'In series the resistances add, so the **absolute** errors add: $ \\Delta R = 0.3\\ \\text{k}\\Omega $ on $ R = 15.0\\ \\text{k}\\Omega $.\n\n$ \\frac{0.3}{15.0} \\times 100 = 2\\% $. Adding the individual percentage errors (4% and 1%) is the trap — that rule is for products, not sums.'),
            mcq('d-c9', 'Five readings of a length are 2.63, 2.56, 2.42, 2.71 and 2.80 cm. The mean absolute error is:',
              ['0.01 cm', '0.05 cm', '0.11 cm', '0.20 cm'], 2,
              'Mean $ = \\frac{13.12}{5} = 2.62 $ cm. Absolute errors: 0.01, 0.06, 0.20, 0.09, 0.18. Their mean is $ \\frac{0.54}{5} = 0.108 \\approx 0.11 $ cm.'),
            mcq('d-c10', 'Which statement about errors is correct?',
              ['Absolute error is always positive', 'Relative error has the same units as the quantity', 'Absolute error may be positive or negative', 'Systematic errors are reduced by averaging'], 2,
              'A single reading may lie above or below the mean, so its absolute error carries a sign. It is the **mean** absolute error that is defined using magnitudes and so is always positive. Relative error is a ratio and has no units, and systematic errors survive averaging untouched.'),
          ],
        },
        {
          id: 'drill-dimensional-formulae',
          title: 'D · Dimensional formulae',
          blurb: 'Ten items. Build each from its defining equation.',
          items: [
            mcq('d-d1', 'The dimensions of surface tension are:',
              ['$ [\\text{M}^{2}\\text{L}^{2}\\text{T}^{-2}] $', '$ [\\text{M}^{2}\\text{L T}^{-2}] $', '$ [\\text{M T}^{-2}] $', '$ [\\text{M L T}^{-2}] $'], 2,
              'Surface tension = force / length $ = \\frac{[\\text{M L T}^{-2}]}{[\\text{L}]} = [\\text{M T}^{-2}] $. The length cancels away entirely.'),
            mcq('d-d2', "The dimensional formula for Young's modulus is:",
              ['$ [\\text{M L}^{-1}\\text{T}^{-2}] $', '$ [\\text{M}^{0}\\text{L T}^{-2}] $', '$ [\\text{M L T}^{-2}] $', '$ [\\text{M L}^{2}\\text{T}^{-2}] $'], 0,
              'Stress divided by strain. Strain is dimensionless, so the modulus simply inherits the dimensions of stress, which is a pressure.'),
            mcq('d-d3', 'The dimensions of the coefficient of friction are:',
              ['$ [\\text{M}^{2}\\text{L}^{2}\\text{T}] $', '$ [\\text{M}^{0}\\text{L}^{0}\\text{T}^{0}] $', '$ [\\text{M L}^{2}\\text{T}^{-2}] $', '$ [\\text{M}^{2}\\text{L}^{2}\\text{T}^{-2}] $'], 1,
              'It is the ratio of two forces, so everything cancels — the coefficient of friction is a pure number.'),
            mcq('d-d4', '$ [\\text{M L}^{-1}\\text{T}^{-1}] $ stands for the dimensions of:',
              ['Work', 'Torque', 'Linear momentum', 'Coefficient of viscosity'], 3,
              'Viscosity. Note it differs from pressure $ [\\text{M L}^{-1}\\text{T}^{-2}] $ by exactly one power of T — the commonest confusion in this table.'),
            mcq('d-d5', 'Relative density has the dimensions:',
              ['$ [\\text{M L}^{-3}] $', '$ [\\text{M}^{0}\\text{L}^{0}\\text{T}^{0}] $', '$ [\\text{M L}^{-2}] $', '$ [\\text{M}^{2}\\text{L}^{-6}] $'], 1,
              'It is the ratio of two densities, so everything cancels and it is dimensionless. The trap is $ [\\text{M L}^{-3}] $ — those are the dimensions of density itself, not of *relative* density.'),
            mcq('d-d6', "Which pair has the same dimensional formula?",
              ['Torque and force', 'Angular momentum and Planck\'s constant', 'Pressure and energy per unit area', 'Velocity and acceleration due to gravity'], 1,
              'Both are $ [\\text{M L}^{2}\\text{T}^{-1}] $ — which is exactly why Planck\'s constant is measured in joule-seconds and turns up wherever angular momentum is quantised.'),
            mcq('d-d7', 'The dimensional formula $ [\\text{M L}^{2}\\text{T}^{-3}\\text{A}^{-1}] $ belongs to:',
              ['Capacitance', 'Resistance', 'Electric potential', 'Magnetic field'], 2,
              'Potential = work / charge $ = \\frac{[\\text{M L}^{2}\\text{T}^{-2}]}{[\\text{A T}]} = [\\text{M L}^{2}\\text{T}^{-3}\\text{A}^{-1}] $. Resistance carries $ \\text{A}^{-2} $ instead.'),
            mcq('d-d8', 'If $ \\varepsilon_0 $ denotes the permittivity of vacuum, its dimensional formula is:',
              ['$ [\\text{M}^{-1}\\text{L}^{-3}\\text{T}^{2}\\text{A}] $', '$ [\\text{M}^{-1}\\text{L}^{-3}\\text{T}^{4}\\text{A}^{2}] $', '$ [\\text{M}^{-2}\\text{L}^{2}\\text{T}^{-1}\\text{A}^{-2}] $', '$ [\\text{M}^{-1}\\text{L}^{2}\\text{T}^{-1}\\text{A}^{2}] $'], 1,
              'From Coulomb\'s law, $ \\varepsilon_0 = \\frac{q_1 q_2}{4\\pi F r^{2}} = \\frac{[\\text{A T}]^{2}}{[\\text{M L T}^{-2}][\\text{L}^{2}]} = [\\text{M}^{-1}\\text{L}^{-3}\\text{T}^{4}\\text{A}^{2}] $.',
              'jee_neet', 'JEE Main 2013'),
            mcq('d-d9', 'The magnetic moment of a current loop has dimensions:',
              ['$ [\\text{L A}] $', '$ [\\text{L}^{2}\\text{A}] $', '$ [\\text{L T}^{-1}\\text{A}] $', '$ [\\text{L}^{2}\\text{T}^{-1}\\text{A}] $'], 1,
              'Magnetic moment $ = $ current $ \\times $ area $ = [\\text{A}][\\text{L}^{2}] = [\\text{L}^{2}\\text{A}] $.'),
            mcq('d-d10', 'The dimensional formula for inductance is:',
              ['$ [\\text{M L}^{2}\\text{T}^{-2}\\text{A}^{-2}] $', '$ [\\text{M L}^{2}\\text{T A}^{-2}] $', '$ [\\text{M L}^{2}\\text{T}^{-1}\\text{A}^{-2}] $', '$ [\\text{M L}^{2}\\text{T}^{-2}\\text{A}^{-1}] $'], 0,
              'From $ \\varepsilon = -L\\frac{di}{dt} $, inductance is potential × time / current $ = [\\text{M L}^{2}\\text{T}^{-3}\\text{A}^{-1}][\\text{T}][\\text{A}^{-1}] = [\\text{M L}^{2}\\text{T}^{-2}\\text{A}^{-2}] $.',
              'jee_neet', 'Karnataka CET 2013'),
          ],
        },
        {
          id: 'drill-analysis',
          title: 'E · Dimensional analysis and the classic traps',
          blurb: 'Eight items at exam level.',
          items: [
            mcq('d-e1', 'The force on a sphere of radius $ a $ moving through a medium with velocity $ v $ is $ F = 6\\pi\\eta a v $. The dimensions of $ \\eta $ are:',
              ['$ [\\text{M L}^{-3}] $', '$ [\\text{M L T}^{-2}] $', '$ [\\text{M T}^{-1}] $', '$ [\\text{M L}^{-1}\\text{T}^{-1}] $'], 3,
              'Rearranging, $ \\eta = \\frac{F}{6\\pi a v} $, and $ 6\\pi $ is a pure number.\n\n$ [\\eta] = \\frac{[\\text{M L T}^{-2}]}{[\\text{L}][\\text{L T}^{-1}]} = [\\text{M L}^{-1}\\text{T}^{-1}] $'),
            mcq('d-e2', 'The velocity of a particle is $ v = at + \\frac{b}{t + c} $. The dimensions of $ a $, $ b $ and $ c $ respectively are:',
              ['$ [\\text{L T}^{-2}], [\\text{L}], [\\text{T}] $', '$ [\\text{L}^{2}], [\\text{T}], [\\text{L T}^{2}] $', '$ [\\text{L T}^{2}], [\\text{L T}], [\\text{L}] $', '$ [\\text{L}], [\\text{L T}], [\\text{T}^{2}] $'], 0,
              'Every term must be a velocity.\n\n$ [a][\\text{T}] = [\\text{L T}^{-1}] $ gives $ [a] = [\\text{L T}^{-2}] $.\n\nOnly a time may be added to a time, so $ [c] = [\\text{T}] $.\n\nThen $ \\frac{[b]}{[\\text{T}]} = [\\text{L T}^{-1}] $ gives $ [b] = [\\text{L}] $.'),
            mcq('d-e3', 'Which of these has the dimensions of time?',
              ['$ LC $', '$ \\frac{R}{L} $', '$ \\frac{L}{R} $', '$ \\frac{C}{L} $'], 2,
              '$ \\frac{L}{R} $ is the inductive time constant. Its reciprocal $ \\frac{R}{L} $ is a frequency, and $ LC $ has the dimensions of time **squared** — only $ \\sqrt{LC} $ is a time.'),
            mcq('d-e4', 'To find the distance $ d $ over which a signal can be seen in fog, an engineer assumes it depends on the mass density $ \\rho $ of the fog, the intensity $ S $ of the light and its frequency $ f $. If $ d $ is found to be proportional to $ S^{1/n} $, the value of $ n $ is:',
              ['2', '3', '1', '4'], 1,
              'Let $ d = k\\rho^{x}S^{y}f^{z} $, with $ [\\rho] = [\\text{M L}^{-3}] $, $ [S] = [\\text{M T}^{-3}] $ and $ [f] = [\\text{T}^{-1}] $.\n\n$ [\\text{L}] = [\\text{M L}^{-3}]^{x}[\\text{M T}^{-3}]^{y}[\\text{T}^{-1}]^{z} $\n\nMatching M: $ x + y = 0 $. Matching L: $ -3x = 1 $, so $ x = -\\frac{1}{3} $ and $ y = \\frac{1}{3} $.\n\nSo $ d \\propto S^{1/3} $ and $ n = 3 $.',
              'jee_neet', 'JEE Advanced 2014'),
            mcq('d-e5', 'A book with printing errors gives four formulae for the displacement $ y $ of a particle in periodic motion. Which one is dimensionally **impossible**?',
              ['$ y = a\\sin\\frac{2\\pi t}{T} $', '$ y = \\frac{a}{T}\\sin\\frac{t}{a} $', '$ y = a\\sin\\omega t $', '$ y = \\frac{a}{\\sqrt{2}}\\left(\\sin\\frac{2\\pi t}{T} + \\cos\\frac{2\\pi t}{T}\\right) $'], 1,
              'In $ \\frac{a}{T}\\sin\\frac{t}{a} $ two things are wrong: the argument $ \\frac{t}{a} $ is a time over a length, not dimensionless, and the front factor $ \\frac{a}{T} $ is a velocity where a displacement is needed.'),
            mcq('d-e6', 'If energy $ E $, velocity $ v $ and force $ F $ are taken as fundamental quantities, the dimensions of mass are:',
              ['$ [F v^{-2}] $', '$ [F v^{-1}] $', '$ [E v^{-2}] $', '$ [E v^{2}] $'], 2,
              'Write $ [\\text{M}] = [E]^{x}[v]^{y}[F]^{z} $ and match powers — the force drops out ($ z = 0 $), leaving $ x = 1 $ and $ y = -2 $.\n\nSanity check against a formula you know: $ E = \\frac{1}{2}mv^{2} $ rearranges to $ m = \\frac{2E}{v^{2}} $.'),
            mcq('d-e7', 'If Planck\'s constant $ h $, the speed of light $ c $ and the gravitational constant $ G $ are chosen as fundamental quantities, then $ \\sqrt{\\frac{hc}{G}} $ has the dimensions of:',
              ['Length', 'Mass', 'Time', 'Energy'], 1,
              '$ \\left[\\frac{hc}{G}\\right] = \\frac{[\\text{M L}^{2}\\text{T}^{-1}][\\text{L T}^{-1}]}{[\\text{M}^{-1}\\text{L}^{3}\\text{T}^{-2}]} = [\\text{M}^{2}] $, so the square root is a mass. This combination is called the Planck mass.'),
            mcq('d-e8', 'The mass $ m $ of the largest stone that can be moved by a flowing river depends on the water\'s velocity $ v $, its density $ \\rho $ and the acceleration due to gravity $ g $. Then $ m $ is proportional to:',
              ['$ v^{3} $', '$ v^{4} $', '$ v^{5} $', '$ v^{6} $'], 3,
              'Write $ m = k v^{a}\\rho^{b}g^{c} $ and match:\n\nM: $ b = 1 $ · T: $ -a - 2c = 0 $ · L: $ a - 3b + c = 0 $\n\nSolving gives $ a = 6 $, $ c = -3 $, so $ m \\propto v^{6} $. A river flowing twice as fast can shift a boulder sixty-four times heavier — which is why floods move rocks that look immovable.'),
          ],
        },
        {
          id: 'drill-formats',
          title: 'F · Exam formats — assertion & reason, match the columns',
          blurb: 'Nine items. These formats appear every year and reward a different kind of care: in assertion–reason you must judge two statements AND the link between them.',
          items: [
            mcqFixed('d-f0', '**How assertion–reason works.** You are given an Assertion (A) and a Reason (R), and must pick one of the same four verdicts every time. Read them below, then use them on the next five questions.\n\n*Warm-up:* **A:** The metre is an SI base unit. **R:** The metre is defined using the speed of light.',
              [
                'Both A and R are true, and R is the correct explanation of A',
                'Both A and R are true, but R is NOT the correct explanation of A',
                'A is true but R is false',
                'A is false but R is true',
              ], 1,
              'Both statements are true. But the metre is a base unit because SI *chose* it as one — not because of how it happens to be defined. The definition by the speed of light came much later, in 1983. True, true, but not the explanation.'),
            mcqFixed('d-f1', '**A:** Pressure has the same dimensions as energy density.\n\n**R:** Energy density is energy per unit volume, which works out to $ [\\text{M L}^{-1}\\text{T}^{-2}] $.',
              [
                'Both A and R are true, and R is the correct explanation of A',
                'Both A and R are true, but R is NOT the correct explanation of A',
                'A is true but R is false',
                'A is false but R is true',
              ], 0,
              '$ \\text{energy density} = \\frac{[\\text{M L}^{2}\\text{T}^{-2}]}{[\\text{L}^{3}]} = [\\text{M L}^{-1}\\text{T}^{-2}] $, which is exactly pressure. R states the calculation that makes A true, so it is the correct explanation.'),
            mcqFixed('d-f2', '**A:** A dimensionally correct equation is always physically correct.\n\n**R:** Dimensional analysis cannot determine the value of a dimensionless constant.',
              [
                'Both A and R are true, and R is the correct explanation of A',
                'Both A and R are true, but R is NOT the correct explanation of A',
                'A is true but R is false',
                'A is false but R is true',
              ], 3,
              'A is false — $ s = ut + at^{2} $ passes the dimensional test and is still wrong. R is true, and is in fact the reason A fails: pure numbers are invisible to the method, so it can never confirm a formula.'),
            mcqFixed('d-f3', '**A:** Systematic errors can be reduced by taking many readings and averaging them.\n\n**R:** Systematic errors push every reading in the same direction.',
              [
                'Both A and R are true, and R is the correct explanation of A',
                'Both A and R are true, but R is NOT the correct explanation of A',
                'A is true but R is false',
                'A is false but R is true',
              ], 3,
              'A is false. R is true — and it is precisely *why* A is false: if all hundred readings are wrong in the same direction, their average is wrong in that direction too. Averaging only helps against error that scatters both ways.'),
            mcqFixed('d-f4', '**A:** The measurement 0.70 m is more precise than 0.7 m.\n\n**R:** The number of significant figures in a measurement indicates its precision.',
              [
                'Both A and R are true, and R is the correct explanation of A',
                'Both A and R are true, but R is NOT the correct explanation of A',
                'A is true but R is false',
                'A is false but R is true',
              ], 0,
              'Both true, and R explains A. 0.70 m claims certainty to the centimetre with the doubtful digit in the hundredths; 0.7 m claims only the tenths. Note the word: more **precise**, not more accurate — neither statement says anything about closeness to the true value.'),
            mcqFixed('d-f5', '**A:** An angle has a unit but no dimensions.\n\n**R:** Strain has neither a unit nor dimensions.',
              [
                'Both A and R are true, and R is the correct explanation of A',
                'Both A and R are true, but R is NOT the correct explanation of A',
                'A is true but R is false',
                'A is false but R is true',
              ], 1,
              'Both statements are true — an angle is measured in radians yet is a length over a length, and strain is a length over a length with no unit name at all. But R is a separate fact about a different quantity; it does nothing to explain A.'),
            mcq('d-f6', 'Match each quantity in Column I with its dimensional formula in Column II.\n\n**Column I:** (A) Impulse · (B) Power · (C) Surface tension · (D) Angular momentum\n\n**Column II:** (p) $ [\\text{M L}^{2}\\text{T}^{-1}] $ · (q) $ [\\text{M L T}^{-1}] $ · (r) $ [\\text{M T}^{-2}] $ · (s) $ [\\text{M L}^{2}\\text{T}^{-3}] $',
              [
                'A→q; B→s; C→r; D→p',
                'A→p; B→s; C→r; D→q',
                'A→q; B→r; C→s; D→p',
                'A→r; B→s; C→q; D→p',
              ], 0,
              'Impulse = force × time = $ [\\text{M L T}^{-1}] $ → q.\n\nPower = work / time = $ [\\text{M L}^{2}\\text{T}^{-3}] $ → s.\n\nSurface tension = force / length = $ [\\text{M T}^{-2}] $ → r.\n\nAngular momentum = momentum × distance = $ [\\text{M L}^{2}\\text{T}^{-1}] $ → p.'),
            mcq('d-f7', 'Match each combination in Column I with what it measures in Column II.\n\n**Column I:** (A) $ \\frac{L}{R} $ · (B) $ CR $ · (C) $ \\frac{R}{L} $ · (D) $ \\sqrt{LC} $\n\n**Column II:** (p) time · (q) frequency',
              [
                'A→p; B→p; C→q; D→p',
                'A→p; B→q; C→q; D→p',
                'A→q; B→p; C→p; D→q',
                'A→p; B→p; C→p; D→q',
              ], 0,
              '$ \\frac{L}{R} $, $ CR $ and $ \\sqrt{LC} $ are all time constants of circuits, so all three map to time. $ \\frac{R}{L} $ is the reciprocal of a time, which is a frequency.'),
            mcq('d-f8', 'Match each quantity in Column I with its SI unit in Column II.\n\n**Column I:** (A) Luminous intensity · (B) Amount of substance · (C) Thermodynamic temperature · (D) Electric current\n\n**Column II:** (p) mole · (q) kelvin · (r) candela · (s) ampere',
              [
                'A→r; B→p; C→q; D→s',
                'A→p; B→r; C→q; D→s',
                'A→r; B→q; C→p; D→s',
                'A→s; B→p; C→q; D→r',
              ], 0,
              'Candela for luminous intensity, mole for amount of substance, kelvin for thermodynamic temperature, ampere for electric current — four of the seven base units, and the four students most often muddle.'),
          ],
        },
      ],
    }),
    b('text', 2, {
      markdown: 'That is the chapter.\n\nFrom here on, every quantity you meet has a unit, a defensible number of digits, and an error bar — and when you meet a formula you do not recognise, you can test it before you trust it.',
    }),
  ],
};

(async () => {
  await withDb(async (db) => {
    const bookId = await ensureChapter(db);
    await upsertPages(db, bookId, [p14, p15]);
  });
  process.exit(0);
})().catch((e) => { console.error(e); process.exit(1); });
