'use strict';
/**
 * Class 11 Physics · Chapter 2 "Motion in One Dimension" — pages 15–17.
 * Wave 3: the retrieval recap, the NCERT exercises verbatim, and the drill bank.
 *
 * RULE 0: every NCERT exercise on p16 is transcribed from the chapter PDF
 * (Exercises 2.1–2.18), not reconstructed from memory. Several of them depend on
 * a printed figure; each such item names the figure it needs and the page
 * carries a figure slot for it, so the SVG pass has an explicit worklist.
 *
 * SOURCE BADGES: p16 items are `ncert_exercise`. p17 items are `mcq` — they are
 * reworded from the two reference books, which are NEVER named student-facing.
 *
 * Run: node scripts/physics11-book/build_ch2_practice.js
 */
const { b, q, st, mcq, mcqFixed, num, ensureChapter, upsertPages, withDb } = require('./_book_ch2');

// ── p15 · Recap ───────────────────────────────────────────────────────────────
const p15 = {
  page_number: 15,
  slug: 'motion-in-one-dimension-recap',
  title: 'Recap',
  subtitle: 'Retrieve it, do not re-read it',
  blocks: [
    b('callout', 0, {
      variant: 'note',
      title: 'How this page works',
      markdown: 'There are **no summary paragraphs** on this page, and that is deliberate.\n\nRe-reading a chapter feels productive and is one of the weakest ways to remember it. Retrieving it from your own memory feels harder and works far better. So everything below asks you to produce something rather than recognise it.\n\nWork through the map first with the chapter closed. Only then check the formula table.',
    }),
    b('mind_map', 1, {
      title: 'The whole chapter on one map',
      root_label: 'Motion in One Dimension',
      intro: 'Cover the right-hand side and try to state each idea before you reveal it.',
      branches: [
        {
          id: 'br-describe',
          label: 'Describing where and how fast',
          children: [
            { id: 'l-frame', label: 'Frame of reference', summary: 'An origin plus a positive direction, both your free choice. Motion only means anything with respect to a frame — there is no absolute rest.' },
            { id: 'l-sign', label: 'A sign is a direction', summary: 'In one dimension the sign of a number carries its direction. That is the whole vector algebra of this chapter.' },
            { id: 'l-dist', label: 'Distance vs displacement', formula: '$ |\\Delta x| \\leq \\text{path length} $', summary: 'Equal only when the motion never reverses. The moment it turns, the path keeps growing while the displacement shrinks.' },
            { id: 'l-avg', label: 'The two averages', formula: '$ \\bar{v} = \\frac{\\Delta x}{\\Delta t} $ vs $ \\frac{\\text{path}}{\\Delta t} $', summary: 'Average speed ≥ |average velocity|. Half the distance gives the harmonic mean; half the time gives the ordinary mean.' },
          ],
        },
        {
          id: 'br-instant',
          label: 'From intervals to instants',
          children: [
            { id: 'l-vinst', label: 'Instantaneous velocity', formula: '$ v = \\frac{dx}{dt} $', summary: 'The limit of the average as the interval shrinks to zero. On a graph it is the slope of the tangent, not of a chord.' },
            { id: 'l-a', label: 'Acceleration', formula: '$ a = \\frac{dv}{dt} $', summary: 'The rate of change of velocity. Defined per second rather than per metre because that is the version that comes out constant in free fall.' },
            { id: 'l-speedinst', label: 'Instantaneous speed', summary: 'Always exactly |instantaneous velocity| — unlike the averages, because there is no room to reverse in a vanishing interval.' },
          ],
        },
        {
          id: 'br-signs',
          label: 'The sign trap',
          children: [
            { id: 'l-rule', label: 'Same signs, speeding up', summary: 'v and a with the same sign means the speed grows; opposite signs means it falls. The sign of a alone tells you nothing.' },
            { id: 'l-zero', label: 'Zero velocity ≠ zero acceleration', summary: 'At the top of its flight a ball has v = 0 and a = g. If a were zero too it would hang there.' },
            { id: 'l-decel', label: 'What "deceleration" means', summary: 'A description of the motion, not a sign. Read it as "the acceleration opposes the velocity", then choose your own axis.' },
          ],
        },
        {
          id: 'br-graphs',
          label: 'The three graphs',
          children: [
            { id: 'l-slope', label: 'Slope goes down the chain', summary: 'Slope of x–t is velocity; slope of v–t is acceleration. Steeper is faster; horizontal is at rest; negative slope is the negative direction.' },
            { id: 'l-area', label: 'Area goes back up it', summary: 'Area under v–t is displacement; area under a–t is the change in velocity. Area under x–t means nothing at all.' },
            { id: 'l-signed', label: 'Signed vs total area', summary: 'Signed area gives displacement, total area gives distance. They differ exactly where the graph crosses the time axis.' },
            { id: 'l-notpath', label: 'A graph is not a map', summary: 'The horizontal axis is time. A hill on an x–t graph does not mean the object went up a hill.' },
            { id: 'l-impossible', label: 'What cannot be drawn', summary: 'No vertical segments (infinite velocity or acceleration) and no double-valued curves (two places at one instant).' },
          ],
        },
        {
          id: 'br-eqns',
          label: 'The three equations',
          children: [
            { id: 'l-e1', label: 'First equation', formula: '$ v = u + at $', summary: 'Use it when the displacement is neither given nor asked for.' },
            { id: 'l-e2', label: 'Second equation', formula: '$ s = ut + \\frac{1}{2}at^2 $', summary: 'Use it when the final velocity is missing. The s is displacement, measured from the position at t = 0.' },
            { id: 'l-e3', label: 'Third equation', formula: '$ v^2 = u^2 + 2as $', summary: 'Use it when time is missing. This is the one behind stopping distance and free-fall speeds.' },
            { id: 'l-when', label: 'When they apply', summary: 'Constant acceleration only. They contain nothing beyond the definitions of v and a — they are consequences, not laws.' },
            { id: 'l-reverse', label: 'When distance ≠ |s|', formula: '$ t_0 = |u/a| $', summary: 'Past t₀ the motion has reversed, so add the two legs separately. The equations will not warn you.' },
          ],
        },
        {
          id: 'br-fall',
          label: 'Free fall',
          children: [
            { id: 'l-g', label: 'One acceleration', summary: 'a = g downward for every object, whatever its mass, at every instant including the top of a throw.' },
            { id: 'l-h', label: 'Maximum height', formula: '$ h = \\frac{u^2}{2g} $', summary: 'Proportional to the square of the launch speed — throw twice as fast and go four times as high.' },
            { id: 'l-t', label: 'Times', formula: '$ t_{up} = t_{down} = \\frac{u}{g},\\ T = \\frac{2u}{g} $', summary: 'Up and down take equal times, and it returns at the same speed it left.' },
            { id: 'l-drop', label: 'Dropped from height h', formula: '$ v = \\sqrt{2gh},\\ t = \\sqrt{2h/g} $', summary: 'Note the square roots: four times the height gives twice the time, not four times.' },
          ],
        },
        {
          id: 'br-rel',
          label: 'Relative and non-uniform',
          children: [
            { id: 'l-rel', label: 'Relative velocity', formula: '$ v_{AB} = v_A - v_B $', summary: 'Read the subscripts in order: A with respect to B. Swap them and the sign flips.' },
            { id: 'l-relacc', label: 'Shared acceleration', summary: 'Equal accelerations give zero relative acceleration, so two bodies in free fall see each other at constant velocity.' },
            { id: 'l-freeze', label: 'Freeze one body', summary: 'A two-body problem becomes one body carrying the relative u and relative a. Half the algebra, half the risk.' },
            { id: 'l-nonuni', label: 'When a is not constant', formula: '$ a = v\\frac{dv}{dx} $', summary: 'The equations die; the definitions survive. Differentiate to go down the chain, integrate to go up it.' },
          ],
        },
      ],
    }),
    b('table', 2, {
      caption: 'Every formula in the chapter, in one place',
      headers: ['Quantity', 'Relation', 'Valid when'],
      rows: [
        ['Average velocity', '$ \\bar{v} = \\dfrac{\\Delta x}{\\Delta t} $', 'Always'],
        ['Average speed', '$ \\dfrac{\\text{path length}}{\\Delta t} $', 'Always'],
        ['Half-distance average', '$ \\dfrac{2v_1v_2}{v_1+v_2} $', 'Two equal distances'],
        ['Half-time average', '$ \\dfrac{v_1+v_2}{2} $', 'Two equal times'],
        ['Instantaneous velocity', '$ v = \\dfrac{dx}{dt} $', 'Always'],
        ['Acceleration', '$ a = \\dfrac{dv}{dt} = v\\dfrac{dv}{dx} $', 'Always'],
        ['First equation', '$ v = u + at $', 'Constant $ a $'],
        ['Second equation', '$ s = ut + \\frac{1}{2}at^2 $', 'Constant $ a $'],
        ['Third equation', '$ v^2 = u^2 + 2as $', 'Constant $ a $'],
        ['Mean velocity', '$ \\bar{v} = \\dfrac{u+v}{2} $', 'Constant $ a $'],
        ['nth-second displacement', '$ s_n = u + \\dfrac{a}{2}(2n-1) $', 'Constant $ a $; needs the hidden $ (1\\,\\text{s}) $ factors'],
        ['Max height thrown up', '$ h = \\dfrac{u^2}{2g} $', 'Free fall'],
        ['Time of flight', '$ T = \\dfrac{2u}{g} $', 'Free fall, returning to launch level'],
        ['Landing speed from height', '$ v = \\sqrt{2gh} $', 'Free fall from rest'],
        ['Stopping distance', '$ d_s = \\dfrac{v_0^2}{2a} $', 'Constant retardation'],
        ['Relative velocity', '$ v_{AB} = v_A - v_B $', 'Always'],
      ],
    }),
    b('reasoning_prompt', 3, {
      reasoning_type: 'logical',
      prompt: 'Without looking back through the chapter, explain to someone who has not read it why these two statements are both true at the same time:\n\n(i) a ball thrown straight up has zero velocity at the top of its flight, and\n(ii) it is accelerating at the top of its flight just as much as at any other moment.\n\nThen say what would happen if (ii) were false.',
      reveal: 'Velocity and acceleration answer different questions. Velocity says *which way and how fast the ball is going right now*; acceleration says *how fast that is being changed*. There is no rule tying them together, so one can be zero while the other is not.\n\nAt the top the ball has finished going up and has not yet started coming down, so its velocity passes through zero. But gravity has not paused — it is still pulling down at $ 9.8 $ m/s², exactly as it was on the way up.\n\n**If (ii) were false** — if the acceleration really were zero at the top — the ball would have no velocity and nothing changing it. It would **hang in the air forever.** That it does not is the proof.\n\nIf you got this from memory without checking, you own the most important idea in the chapter.',
      difficulty_level: 2,
    }),
    b('reasoning_prompt', 4, {
      reasoning_type: 'logical',
      prompt: 'A student says: "I can always find the distance travelled by putting the numbers into $ s = ut + \\frac{1}{2}at^2 $." Give a specific numerical example where this is wrong, state what the equation actually gives, and describe the one extra step that fixes it.',
      reveal: '**A counterexample.** Throw a ball up at $ 20 $ m/s with $ g = 10 $ m/s² and ask about $ t = 4 $ s. The equation gives $ s = 20(4) - 5(16) = 0 $. So the equation says zero — and the ball has in fact travelled $ 40 $ m: up 20 m and back down 20 m.\n\n**What it actually gives** is the **displacement**, the change in position. Here the ball is back where it started, so the displacement is genuinely zero. The equation is not wrong; it is answering a different question.\n\n**The fix.** Find the instant the velocity reaches zero, $ t_0 = |u/a| = 2 $ s. If the time you were asked about is less than $ t_0 $, there was no reversal and distance $ = |s| $. If it is more, add the two legs: the distance up, $ u^2/2a $, plus the distance fallen back since the turn, $ \\frac{1}{2}|a(t - t_0)^2| $.\n\nHere: $ 400/20 + \\frac{1}{2}(10)(2)^2 = 20 + 20 = 40 $ m. ✓',
      difficulty_level: 3,
    }),
    b('inline_quiz', 5, {
      pass_threshold: 0.7,
      questions: [
        q('A particle travels the first half of a distance at $ 20 $ m/s and the second half at $ 30 $ m/s. Its average speed is:',
          ['$ 25 $ m/s', '$ 24 $ m/s', '$ 26 $ m/s', '$ 50 $ m/s'], 1,
          'Equal distances need the harmonic mean: $ \\frac{2(20)(30)}{50} = \\frac{1200}{50} = 24 $ m/s. The 25 m/s answer is the ordinary mean, which would be right only if the two halves took equal *times*.', 3),
        q('On a v–t graph, a region of area $ 40 $ above the time axis is followed by a region of area $ 15 $ below it. The distance travelled and the displacement are:',
          ['$ 55 $ and $ 25 $', '$ 25 $ and $ 55 $', '$ 55 $ and $ 55 $', '$ 40 $ and $ 15 $'], 0,
          'Distance ignores sign, giving $ 40 + 15 = 55 $. Displacement respects it, giving $ 40 - 15 = 25 $. Distance is always the larger of the two whenever the graph crosses the axis.', 2),
        q('A body has velocity $ -6 $ m/s and acceleration $ +2 $ m/s². It is:',
          ['Speeding up while moving in the negative direction', 'Slowing down while moving in the negative direction', 'Speeding up while moving in the positive direction', 'Momentarily at rest at the origin'], 1,
          'The signs are opposite, so the speed is falling. The negative velocity says it is still travelling in the negative direction while doing so — it will stop after 3 s and then reverse.', 2),
        q('A ball is dropped from rest and falls for $ 3 $ s. Taking $ g = 10 $ m/s², the distance it covers **during the third second** is:',
          ['$ 25 $ m', '$ 45 $ m', '$ 15 $ m', '$ 5 $ m'], 0,
          'Total in 3 s is $ \\frac{1}{2}(10)(9) = 45 $ m; total in 2 s is $ \\frac{1}{2}(10)(4) = 20 $ m. The third second alone is $ 45 - 20 = 25 $ m. The 45 m answer is the whole fall, not the third second of it.', 3),
        q('The x–t graph of a particle is a straight line with a negative slope. Which is true?',
          ['Its acceleration is negative and constant', 'Its velocity is constant and negative', 'It is steadily slowing down', 'It reverses direction partway through'], 1,
          'A straight line means a constant slope, so the velocity never changes — and a negative slope makes that constant velocity negative. Constant velocity means zero acceleration, and no reversal.', 2),
        q('Two stones are released from the same point $ 2 $ s apart. Taking $ g = 10 $ m/s², the rate at which the gap between them grows is:',
          ['$ 20 $ m/s, constant', '$ 20 $ m/s, increasing', '$ 10 $ m/s, constant', 'Zero'], 0,
          'Both share the acceleration $ g $, so their relative acceleration is zero and their relative velocity is fixed. When the second is released, the first is already moving at $ 10(2) = 20 $ m/s, and that 20 m/s never changes.', 3),
        q('A car brakes from $ 20 $ m/s to rest over $ 50 $ m. Its retardation is:',
          ['$ 4 $ m/s²', '$ 8 $ m/s²', '$ 2 $ m/s²', '$ 0.4 $ m/s²'], 0,
          '$ 0 = 400 + 2a(50) $, so $ a = -4 $ m/s², a retardation of 4 m/s². Time is neither given nor asked for, which is the signal to use $ v^2 = u^2 + 2as $.', 2),
        q('A particle has $ x = t^3 - 6t^2 $ (SI units). Its acceleration at $ t = 1 $ s is:',
          ['$ -6 $ m/s²', '$ -9 $ m/s²', '$ 6 $ m/s²', '$ -12 $ m/s²'], 0,
          'Differentiate twice: $ v = 3t^2 - 12t $ and $ a = 6t - 12 $. At $ t = 1 $ s, $ a = 6 - 12 = -6 $ m/s². Stopping after one differentiation gives $ -9 $, which is the velocity.', 3),
        q('Which quantity is the same for two objects thrown from the same height with the same speed, one upward and one downward?',
          ['Time of flight', 'Landing speed', 'Distance travelled', 'Average velocity'], 1,
          'Since $ v^2 = u^2 + 2gh $ contains $ u^2 $, reversing the launch direction does not change the landing speed. The upward one is in the air longer and travels further, so the other three all differ.', 3),
        q('The three equations of motion cannot be used for a particle whose acceleration is:',
          ['Negative', 'Large', '$ 6t $ m/s²', 'Directed opposite to the velocity'], 2,
          'An acceleration of $ 6t $ changes with time, so there is no single value to substitute and every equation fails. A negative acceleration, a large one, or one opposing the motion are all perfectly fine as long as they stay constant.', 2),
      ],
    }),
    b('callout', 6, {
      variant: 'exam_tip',
      title: 'If you only remember five things',
      markdown: '1. **A sign is a direction.** Declare your positive direction before writing any number.\n2. **Same signs, speeding up. Opposite signs, slowing down.** The sign of $ a $ alone says nothing.\n3. **Slope down the chain, area back up it.** Slope of x–t is $ v $; area under v–t is displacement.\n4. **The $ s $ in the equations is displacement**, measured from the position at $ t = 0 $. If the motion reverses, distance is more.\n5. **Constant acceleration or nothing.** The moment $ a $ changes, go back to $ \\frac{dx}{dt} $ and $ \\frac{dv}{dt} $.',
    }),
  ],
};

// ── p16 · NCERT Exercises ─────────────────────────────────────────────────────
const p16 = {
  page_number: 16,
  slug: 'ncert-exercises',
  title: 'Practice — NCERT Exercises',
  subtitle: 'All eighteen, grouped by what they test',
  blocks: [
    b('text', 0, {
      markdown: 'Every exercise from the NCERT chapter is here, in the textbook\'s own words, regrouped so that questions testing the same skill sit together.\n\nWork each one before you reveal the solution. Where a question asks you to *plot* or *sketch*, do it on paper — the marks in a board exam are for the graph, not for a description of it.',
    }),
    b('practice_bank', 1, {
      title: 'Theme 1 — Concepts, point objects and the two averages',
      intro: 'Exercises 2.1, 2.7, 2.9, 2.10 and 2.11. These are the "explain with reasons" questions, and they are worth more marks than students expect.',
      sections: [
        {
          id: 'p16-t1',
          title: 'Definitions and distinctions',
          items: [
            num('ncert-2-1', 'In which of the following examples of motion, can the body be considered approximately a point object: (a) a railway carriage moving without jerks between two stations; (b) a monkey sitting on top of a man cycling smoothly on a circular track; (c) a spinning cricket ball that turns sharply on hitting the ground; (d) a tumbling beaker that has slipped off the edge of a table.',
              '(a) and (b) yes; (c) and (d) no.',
              '(a) **Yes** — the carriage is tens of metres long while the journey is many kilometres, so its size is negligible.\n\n(b) **Yes** — the monkey is small compared with the circular track and is not doing anything of its own.\n\n(c) **No** — the ball turns sharply *because* it is spinning, and spin is a property of an extended body. Shrink it to a point and the effect disappears.\n\n(d) **No** — it is tumbling, so different parts of it are doing visibly different things, and its size is not small compared with the fall.\n\nThe test is not "is it small?" but **"does its size or rotation matter for this question?"**',
              'ncert_exercise'),
            num('ncert-2-7', 'Read each statement below carefully and state with reasons and examples, if it is true or false. A particle in one-dimensional motion: (a) with zero speed at an instant may have non-zero acceleration at that instant; (b) with zero speed may have non-zero velocity; (c) with constant speed must have zero acceleration; (d) with positive value of acceleration must be speeding up.',
              '(a) True  (b) False  (c) True  (d) False',
              '(a) **True.** A ball at the top of its flight has zero speed and acceleration $ g $ downward. If this were impossible, nothing thrown upward could return.\n\n(b) **False.** Speed is defined as the magnitude of the velocity, so if the magnitude is zero the velocity is zero.\n\n(c) **True, for one-dimensional motion.** A particle on a line can only reverse by passing through zero speed, so constant non-zero speed means the velocity never changes at all. *Careful:* this fails in two dimensions — uniform circular motion has constant speed and non-zero acceleration.\n\n(d) **False.** A positive acceleration acting on a particle with negative velocity opposes the motion and slows it down. Whether the speed grows depends on whether $ v $ and $ a $ share a sign.',
              'ncert_exercise'),
            num('ncert-2-9', 'Explain clearly, with examples, the distinction between: (a) magnitude of displacement (sometimes called distance) over an interval of time, and the total length of path covered by a particle over the same interval; (b) magnitude of average velocity over an interval of time, and the average speed over the same interval. Show in both (a) and (b) that the second quantity is either greater than or equal to the first. When is the equality sign true?',
              'In both cases the second quantity is the greater, with equality only when the motion does not reverse.',
              '(a) The **magnitude of displacement** is the straight-line separation between the start and finish; the **path length** is what the particle actually covered. A particle going from $ x = 0 $ to $ x = 5 $ m and back to $ x = 2 $ m has a displacement of magnitude 2 m and a path length of 8 m.\n\nThe path length can never be smaller, because every bit of motion adds to it while some bits subtract from the displacement. So $ \\text{path length} \\geq |\\Delta x| $.\n\n(b) Dividing both sides of that inequality by the same time interval gives $ \\text{average speed} \\geq |\\text{average velocity}| $ immediately.\n\n**The equality holds exactly when the particle does not reverse direction** during the interval — then every bit of motion adds to both quantities equally.',
              'ncert_exercise'),
            num('ncert-2-10', 'A man walks on a straight road from his home to a market 2.5 km away with a speed of 5 km/h. Finding the market closed, he instantly turns and walks back home with a speed of 7.5 km/h. What is the (a) magnitude of average velocity, and (b) average speed of the man over the interval of time (i) 0 to 30 min, (ii) 0 to 50 min, (iii) 0 to 40 min?',
              '(i) 5 km/h and 5 km/h  (ii) 0 and 6 km/h  (iii) 1.875 km/h and 5.625 km/h',
              'Timetable first: out takes $ 2.5/5 = 0.5 $ h $ = 30 $ min; back takes $ 2.5/7.5 = 1/3 $ h $ = 20 $ min. So he reaches the market at 30 min and gets home at 50 min.\n\n**(i) 0–30 min.** He has only gone one way, so displacement $ = $ path $ = 2.5 $ km over $ 0.5 $ h. Both answers are $ 5 $ km/h.\n\n**(ii) 0–50 min.** He is home, so the displacement is zero and the average velocity is **zero**. But he walked 5 km in $ 50/60 $ h, so the average speed is $ 5 \\div \\frac{5}{6} = 6 $ km/h.\n\n**(iii) 0–40 min.** He has been returning for 10 min at 7.5 km/h, covering $ 1.25 $ km, so he is $ 2.5 - 1.25 = 1.25 $ km from home. Average velocity $ = 1.25 \\div \\frac{2}{3} = 1.875 $ km/h. Path length $ = 2.5 + 1.25 = 3.75 $ km, so average speed $ = 3.75 \\div \\frac{2}{3} = 5.625 $ km/h.',
              'ncert_exercise'),
            num('ncert-2-11', 'In Exercises 2.9 and 2.10 we have carefully distinguished between average speed and magnitude of average velocity. No such distinction is necessary when we consider instantaneous speed and magnitude of velocity. The instantaneous speed is always equal to the magnitude of instantaneous velocity. Why?',
              'Because over a vanishingly small interval there is no room to reverse, so the path length and the magnitude of the displacement become identical.',
              'The gap between path length and displacement only opens up when the particle **reverses direction** during the interval — that is the one thing that lets the path keep growing while the displacement shrinks.\n\nAn instantaneous quantity is the limit as the interval shrinks to zero. In such an interval the particle cannot turn round, so over it the path length and the magnitude of the displacement are the same number.\n\nThe two limits therefore coincide, and instantaneous speed is exactly the magnitude of instantaneous velocity — with no exceptions.',
              'ncert_exercise'),
          ],
        },
      ],
    }),
    b('practice_bank', 2, {
      title: 'Theme 2 — The equations, free fall and relative velocity',
      intro: 'Exercises 2.5, 2.6 and 2.14. Pure calculation, and the three that are most likely to appear as numericals.',
      sections: [
        {
          id: 'p16-t2',
          title: 'Numerical problems',
          items: [
            num('ncert-2-5', 'A car moving along a straight highway with speed of 126 km/h is brought to a stop within a distance of 200 m. What is the retardation of the car (assumed uniform), and how long does it take for the car to stop?',
              'Retardation $ \\approx 3.06 $ m/s²; time $ \\approx 11.4 $ s.',
              'Convert first: $ 126 $ km/h $ = 126 \\times \\frac{5}{18} = 35 $ m/s.\n\nTime is neither given nor asked for in the first part, so use $ v^2 = u^2 + 2as $:\n$ 0 = 35^2 + 2a(200) $, so $ a = -\\frac{1225}{400} = -3.06 $ m/s². The retardation is $ 3.06 $ m/s².\n\nFor the time, use $ v = u + at $: $ 0 = 35 - 3.06t $, so $ t = 11.4 $ s.\n\nCheck: average velocity $ = 17.5 $ m/s, and $ 17.5 \\times 11.4 \\approx 200 $ m. ✓',
              'ncert_exercise'),
            num('ncert-2-6', 'A player throws a ball upwards with an initial speed of 29.4 m/s. (a) What is the direction of acceleration during the upward motion of the ball? (b) What are the velocity and acceleration of the ball at the highest point of its motion? (c) Choose the x = 0 m and t = 0 s to be the location and time of the ball at its highest point, vertically downward direction to be the positive direction of x-axis, and give the signs of position, velocity and acceleration of the ball during its upward and downward motion. (d) To what height does the ball rise and after how long does the ball return to the player\'s hands? Take g = 9.8 m/s² and neglect air resistance.',
              '(a) Vertically downward  (b) $ v = 0 $, $ a = 9.8 $ m/s² downward  (c) see solution  (d) $ 44.1 $ m; $ 6 $ s',
              '(a) **Vertically downward**, throughout — gravity does not care which way the ball is moving.\n\n(b) At the highest point the velocity is **zero**, but the acceleration is still $ 9.8 $ m/s² **downward**.\n\n(c) With the origin at the highest point, $ t = 0 $ there, and **downward positive**:\n- *Upward motion* (before the top, so $ t < 0 $): position **negative** (the ball is above the origin), velocity **negative** (moving up), acceleration **positive** (down).\n- *Downward motion* ($ t > 0 $): position **positive**, velocity **positive**, acceleration **positive**.\n\nNote the acceleration is positive in both phases — this convention makes that especially clear.\n\n(d) Height: $ h = \\frac{u^2}{2g} = \\frac{29.4^2}{2(9.8)} = \\frac{864.36}{19.6} = 44.1 $ m.\nTime of flight: $ T = \\frac{2u}{g} = \\frac{2(29.4)}{9.8} = 6 $ s.',
              'ncert_exercise'),
            num('ncert-2-14', 'A police van moving on a highway with a speed of 30 km/h fires a bullet at a thief\'s car speeding away in the same direction with a speed of 192 km/h. If the muzzle speed of the bullet is 150 m/s, with what speed does the bullet hit the thief\'s car? (Note: obtain that speed which is relevant for damaging the thief\'s car.)',
              '$ 105 $ m/s',
              'The muzzle speed is measured **with respect to the van**, so the bullet\'s speed over the ground is the muzzle speed plus the van\'s speed.\n\nVan: $ 30 $ km/h $ = 30 \\times \\frac{5}{18} = 8.33 $ m/s. So the bullet\'s ground speed is $ 150 + 8.33 = 158.33 $ m/s.\n\nThief\'s car: $ 192 $ km/h $ = 192 \\times \\frac{5}{18} = 53.33 $ m/s.\n\nThe speed that does the damage is the **relative** speed of the bullet with respect to the car:\n$ 158.33 - 53.33 = 105 $ m/s.\n\nThe note in the question is a hint: a bullet arriving at 158 m/s at a target already running away at 53 m/s hits it as though it were doing 105 m/s.',
              'ncert_exercise'),
          ],
        },
      ],
    }),
    b('image', 3, {
      src: '',
      alt: 'Placeholder for the NCERT figures needed by exercises 2.2, 2.8, 2.12, 2.13, 2.15, 2.16, 2.17 and 2.18.',
      aspect_ratio: '16:9',
      figure_key: 'ch2-ncert-exercise-figures',
      caption: 'The graphs for the figure-based exercises below. Refer to this while working Theme 3.',
    }),
    b('practice_bank', 4, {
      title: 'Theme 3 — Reading and drawing graphs',
      intro: 'Exercises 2.2, 2.3, 2.4, 2.8, 2.12, 2.13, 2.15, 2.16, 2.17 and 2.18. Ten of the eighteen exercises are about graphs — which tells you exactly where the marks are.',
      sections: [
        {
          id: 'p16-t3',
          title: 'Graph questions',
          items: [
            num('ncert-2-2', 'The position–time graphs for two children A and B returning from their school O to their homes P and Q respectively are shown in the figure. Choose the correct entries in the brackets: (a) (A/B) lives closer to the school than (B/A); (b) (A/B) starts from the school earlier than (B/A); (c) (A/B) walks faster than (B/A); (d) A and B reach home at the (same/different) time; (e) (A/B) overtakes (B/A) on the road (once/twice).',
              '(a) A  (b) A  (c) B  (d) same  (e) B overtakes A once',
              '(a) **A lives closer** — A\'s line ends at the lower position P, so A\'s home is nearer the school.\n\n(b) **A starts earlier** — A\'s line begins at $ t = 0 $ while B\'s begins later.\n\n(c) **B walks faster** — B\'s line is steeper, and on an x–t graph steepness is speed.\n\n(d) **The same time** — both lines terminate at the same value of $ t $.\n\n(e) **B overtakes A once** — the two lines cross exactly once, and a crossing means both children are at the same position at the same instant.',
              'ncert_exercise'),
            num('ncert-2-3', 'A woman starts from her home at 9.00 am, walks with a speed of 5 km/h on a straight road up to her office 2.5 km away, stays at the office up to 5.00 pm, and returns home by an auto with a speed of 25 km/h. Choose suitable scales and plot the x–t graph of her motion.',
              'Three straight segments: a gentle rise, a long horizontal line, then a steep fall.',
              'Work out the timetable first:\n- **Walk out:** $ 2.5/5 = 0.5 $ h, so 9.00 am to 9.30 am, position rising from 0 to 2.5 km.\n- **At the office:** 9.30 am to 5.00 pm, position constant at 2.5 km.\n- **Auto home:** $ 2.5/25 = 0.1 $ h $ = 6 $ min, so 5.00 pm to 5.06 pm, position falling from 2.5 km back to 0.\n\nSuitable scales: time along the horizontal axis at 1 cm per hour (9 am to 6 pm), position vertically at 1 cm per 0.5 km.\n\nThe graph is therefore a gently rising line, a long flat line, and a very steep falling line — and the steepness of that last segment is the visual statement that the auto is five times faster than her walking.',
              'ncert_exercise'),
            num('ncert-2-4', 'A drunkard walking in a narrow lane takes 5 steps forward and 3 steps backward, followed again by 5 steps forward and 3 steps backward, and so on. Each step is 1 m long and requires 1 s. Plot the x–t graph of his motion. Determine graphically and otherwise how long the drunkard takes to fall in a pit 13 m away from the start.',
              '37 s',
              'Each cycle is 8 steps taking 8 s, and produces a **net** advance of $ 5 - 3 = 2 $ m.\n\nSo after $ n $ cycles he is at $ 2n $ metres, having taken $ 8n $ seconds. After 4 cycles ($ 32 $ s) he is at $ 8 $ m. After 5 cycles ($ 40 $ s) he would be at $ 10 $ m — so he never reaches 13 m by completing cycles.\n\nThe key is that he reaches his **furthest point** partway through a cycle. Starting the 5th cycle at $ 8 $ m and $ 32 $ s, he walks forward: at $ 33 $ s he is at 9 m, at $ 34 $ s at 10 m, $ 35 $ s at 11 m, $ 36 $ s at 12 m, and at **$ 37 $ s at 13 m** — where he falls in.\n\nThe graph is a repeating zig-zag: five 1 m rises, then three 1 m falls, drifting steadily upward, and it crosses 13 m for the first time at $ t = 37 $ s.',
              'ncert_exercise'),
            num('ncert-2-8', 'A ball is dropped from a height of 90 m on a floor. At each collision with the floor, the ball loses one tenth of its speed. Plot the speed–time graph of its motion between t = 0 to 12 s. Take g = 10 m/s².',
              'A series of straight rising segments separated by sudden drops of one tenth at each bounce.',
              'First fall: $ 90 = \\frac{1}{2}(10)t^2 $ gives $ t = \\sqrt{18} \\approx 4.24 $ s, and the ball arrives at $ v = 10(4.24) \\approx 42.4 $ m/s.\n\nIt rebounds having lost a tenth of its speed, so it leaves the floor at $ 0.9 \\times 42.4 \\approx 38.2 $ m/s. That takes $ 38.2/10 \\approx 3.8 $ s to rise and the same to fall, returning to the floor at about $ t = 11.8 $ s at $ 38.2 $ m/s, then rebounding at about $ 34.4 $ m/s.\n\n**The speed–time graph** is therefore: a straight line rising from 0 to $ 42.4 $ m/s over the first $ 4.24 $ s; a **vertical drop** to $ 38.2 $ m/s at the bounce; a straight line falling to zero at the top of the rebound; a straight line rising back to $ 38.2 $ m/s; another drop at the next bounce; and so on.\n\nNote we plot **speed**, not velocity, so nothing goes below the axis. Each bounce shows as a small step down, and the ball\'s peak speed decays by a factor of $ 0.9 $ each time.',
              'ncert_exercise'),
            num('ncert-2-12', 'Look at the graphs (a) to (d) in the figure carefully and state, with reasons, which of these cannot possibly represent one-dimensional motion of a particle.',
              'All four are impossible.',
              '**(a)** An x–t graph that loops back on itself is **double-valued in time** — the particle would be in two places at the same instant. Impossible.\n\n**(b)** A v–t graph forming a closed loop is double-valued in the same way — the particle would have two velocities at once. Impossible.\n\n**(c)** A **speed**–time graph that goes below the axis is impossible: speed is a magnitude, so it can be zero but never negative.\n\n**(d)** A graph of **total path length** that decreases is impossible — path length only accumulates, so it can never come down.\n\nThe general lesson: check whether the graph is single-valued in time, and whether the quantity plotted is one that is allowed to be negative or to decrease.',
              'ncert_exercise'),
            num('ncert-2-13', 'The figure shows the x–t plot of one-dimensional motion of a particle. Is it correct to say from the graph that the particle moves in a straight line for t < 0 and on a parabolic path for t > 0? If not, suggest a suitable physical context for this graph.',
              'No — the particle moves in a straight line the whole time. The graph shape describes how the position changed, not the path.',
              '**No, it is not correct.** This is an x–t graph, not a map of where the particle went. The particle is in one-dimensional motion by assumption, so it moves along a straight line the entire time.\n\nWhat the shapes actually say is:\n- For $ t < 0 $, the slope is constant, so the particle moves at **constant velocity**.\n- For $ t > 0 $, the slope increases steadily, so the particle is **uniformly accelerated**.\n\n**A suitable physical context:** a ball rolling along level ground at constant speed until $ t = 0 $, when it reaches the top of an incline and begins rolling down it, picking up speed steadily. Or a car cruising at constant speed whose driver presses the accelerator at $ t = 0 $.',
              'ncert_exercise'),
            num('ncert-2-15', 'Suggest a suitable physical situation for each of the graphs in the figure.',
              'See solution for all three.',
              '**(a)** An x–t graph that rises to a peak A, drops sharply to B, and then runs flat. This suggests a **ball thrown against a wall and rebounding**: it travels away, hits the wall, returns quickly to a point, and then stays there (or is caught).\n\n**(b)** A v–t graph made of repeated negative-slope segments, each starting lower than the last, with the segments getting shorter. This suggests a **ball bouncing on the floor and losing speed at each impact** — each segment is one flight, and the sudden jumps are the collisions.\n\n**(c)** An a–t graph that is zero except for a single short positive pulse. This suggests a **ball at rest being struck by a bat**: the force acts only for the brief moment of contact, so the acceleration is a sharp spike and zero at all other times.',
              'ncert_exercise'),
            num('ncert-2-16', 'The figure gives the x–t plot of a particle executing one-dimensional simple harmonic motion. Give the signs of position, velocity and acceleration variables of the particle at t = 0.3 s, 1.2 s and −1.2 s.',
              'At 0.3 s: $ x < 0 $, $ v < 0 $, $ a > 0 $. At 1.2 s: $ x > 0 $, $ v > 0 $, $ a < 0 $. At $ -1.2 $ s: $ x < 0 $, $ v > 0 $, $ a > 0 $.',
              'For simple harmonic motion the acceleration always points back towards the origin, so **$ a $ has the opposite sign to $ x $** at every instant. That single fact fixes the third column once you have read off the first two.\n\n**At $ t = 0.3 $ s:** the curve is below the axis and still falling, so $ x $ is negative and $ v $ is negative. Therefore $ a $ is positive.\n\n**At $ t = 1.2 $ s:** the curve is above the axis and rising, so $ x $ and $ v $ are both positive. Therefore $ a $ is negative.\n\n**At $ t = -1.2 $ s:** the curve is below the axis but rising, so $ x $ is negative and $ v $ is positive. Therefore $ a $ is positive.',
              'ncert_exercise'),
            num('ncert-2-17', 'The figure gives the x–t plot of a particle in one-dimensional motion. Three different equal intervals of time are shown. In which interval is the average speed greatest, and in which is it the least? Give the sign of average velocity for each interval.',
              'Greatest in interval 3, least in interval 2. Signs: interval 1 positive, interval 2 positive, interval 3 negative.',
              'For equal intervals of time, the **average speed** is decided by how much the position changes — which on an x–t graph is how steep the segment is, ignoring the sign of the slope.\n\n**Greatest average speed: interval 3**, where the curve falls most steeply.\n\n**Least average speed: interval 2**, where the curve is flattest.\n\n**Signs of average velocity** come from whether the position ends higher or lower than it began:\n- Interval 1: the curve rises, so **positive**.\n- Interval 2: the curve still rises, so **positive**.\n- Interval 3: the curve falls, so **negative**.',
              'ncert_exercise'),
            num('ncert-2-18', 'The figure gives a speed–time graph of a particle in motion along a constant direction. Three equal intervals of time are shown. In which interval is the average acceleration greatest in magnitude? In which interval is the average speed greatest? Choosing the positive direction as the constant direction of motion, give the signs of v and a in the three intervals. What are the accelerations at the points A, B, C and D?',
              'Average acceleration greatest in interval 2; average speed greatest in interval 3. $ v > 0 $ throughout; $ a > 0 $ in 1, $ a < 0 $ in 2, $ a > 0 $ in 3. At A, B, C and D the acceleration is zero.',
              '**Average acceleration** over an interval is the change in speed divided by the time. Since the intervals are equal, it is the biggest change in speed that wins — **interval 2**, where the speed falls sharply from its peak.\n\n**Average speed** is greatest in **interval 3**, where the curve sits highest.\n\n**Signs.** The particle moves in a constant direction, taken as positive, so **$ v > 0 $ in all three intervals**. For the acceleration, look at the slope of the speed–time curve: rising in interval 1 (**$ a > 0 $**), falling in interval 2 (**$ a < 0 $**), rising again in interval 3 (**$ a > 0 $**).\n\n**At A, B, C and D** the curve is at a peak or a trough, so its slope is zero — and the slope of a speed–time graph is the acceleration. So **the acceleration is zero at all four points.**',
              'ncert_exercise'),
          ],
        },
      ],
    }),
  ],
};

// ── p17 · JEE & NEET Drill ────────────────────────────────────────────────────
const p17 = {
  page_number: 17,
  slug: 'jee-neet-drill',
  title: 'Practice — JEE & NEET Drill',
  subtitle: 'Sixty questions, one section per topic',
  blocks: [
    b('text', 0, {
      markdown: 'Six sections, one for each topic in the chapter. Work a whole section in one sitting and mark it before moving on — you learn more from finding out *which* ideas are shaky than from a single overall score.\n\nAnything you get wrong, go back to the page it came from rather than reading the explanation twice.',
    }),
    b('practice_bank', 1, {
      title: 'Section 1 — Distance, displacement and the two averages',
      sections: [
        {
          id: 'p17-s1',
          title: 'Ten questions',
          items: [
            mcq('d1-1', 'A particle moves along a straight line and returns to its starting point. Over the whole journey:',
              ['Both distance and displacement are zero', 'Distance is non-zero, displacement is zero', 'Distance is zero, displacement is non-zero', 'Both are non-zero and equal'], 1,
              'The particle really did travel, so the path length is non-zero — but its final position equals its initial position, so the displacement is exactly zero.'),
            mcq('d1-2', 'A particle covers the first half of a distance at $ 40 $ km/h and the second half at $ 60 $ km/h. Its average speed is:',
              ['$ 50 $ km/h', '$ 48 $ km/h', '$ 52 $ km/h', '$ 45 $ km/h'], 1,
              'Equal distances need the harmonic mean: $ \\frac{2(40)(60)}{100} = 48 $ km/h. The 50 km/h answer is the ordinary mean, correct only for equal *times*.'),
            mcq('d1-3', 'A particle travels at $ 30 $ m/s for half the total time and $ 50 $ m/s for the other half. Its average speed is:',
              ['$ 37.5 $ m/s', '$ 40 $ m/s', '$ 42 $ m/s', '$ 80 $ m/s'], 1,
              'Equal times give the ordinary mean: $ (30 + 50)/2 = 40 $ m/s. Reaching for the harmonic mean here would give 37.5, which belongs to the equal-distance version.'),
            num('d1-4', 'A man walks 4 km north, then 3 km east. Find the distance walked and the magnitude of his displacement.',
              'Distance $ 7 $ km; displacement $ 5 $ km',
              'Distance simply adds: $ 4 + 3 = 7 $ km. The two legs are perpendicular, so the displacement is the hypotenuse: $ \\sqrt{16 + 9} = 5 $ km.'),
            mcq('d1-5', 'Which of these can never be negative?',
              ['Displacement', 'Average velocity', 'Average speed', 'Position'], 2,
              'Average speed is path length over time, and neither can be negative. The other three all carry a sign encoding direction or which side of the origin the particle sits on.'),
            num('d1-6', 'A car travels one third of a journey at $ 20 $ m/s, the next third at $ 30 $ m/s and the last third at $ 60 $ m/s. Find its average speed.',
              '$ 30 $ m/s',
              'Let each third be $ d $. The times are $ \\frac{d}{20} $, $ \\frac{d}{30} $ and $ \\frac{d}{60} $, adding to $ \\frac{3d + 2d + d}{60} = \\frac{d}{10} $. So the average speed is $ 3d \\div \\frac{d}{10} = 30 $ m/s — not the $ 36.7 $ m/s you get by averaging the three speeds.'),
            mcq('d1-7', 'The average speed of a particle equals the magnitude of its average velocity over some interval. During that interval the particle:',
              ['Was at rest for the whole interval', 'Moved at a constant speed throughout', 'Did not reverse its direction of motion', 'Had zero acceleration throughout'], 2,
              'The two agree exactly when the path length equals the magnitude of the displacement, which happens precisely when the motion never doubles back. The particle may have sped up and slowed down freely.'),
            num('d1-8', 'A particle moves from $ x = 8 $ m to $ x = -4 $ m and then to $ x = 1 $ m. Find the total distance and the displacement.',
              'Distance $ 17 $ m; displacement $ -7 $ m',
              'First leg: $ |{-4} - 8| = 12 $ m. Second leg: $ |1 - (-4)| = 5 $ m. Total path $ = 17 $ m. Displacement compares only the ends: $ 1 - 8 = -7 $ m.'),
            mcq('d1-9', 'For a particle in one-dimensional motion, which inequality is always correct?',
              ['Path length $ \\leq $ |displacement|', 'Path length $ \\geq $ |displacement|', 'Path length $ = $ |displacement|', 'No general relation exists'], 1,
              'Path length accumulates while displacement can shrink, so the path can never be the smaller of the two. Equality is the special case of unreversed motion.'),
            num('d1-10', 'A cyclist covers $ 20 $ km at $ 10 $ km/h and returns along the same road at $ 30 $ km/h. Find the average speed for the round trip and the average velocity.',
              'Average speed $ 15 $ km/h; average velocity zero',
              'Equal distances, so the average speed is the harmonic mean: $ \\frac{2(10)(30)}{40} = 15 $ km/h. She finishes where she started, so the displacement — and hence the average velocity — is zero.'),
          ],
        },
      ],
    }),
    b('practice_bank', 2, {
      title: 'Section 2 — Velocity, acceleration and the sign trap',
      sections: [
        {
          id: 'p17-s2',
          title: 'Ten questions',
          items: [
            mcq('d2-1', 'A particle has velocity $ +5 $ m/s and acceleration $ -3 $ m/s². It is:',
              ['Speeding up while moving in the positive direction', 'Slowing down while moving in the positive direction', 'Speeding up while moving in the negative direction', 'Moving at a constant speed throughout'], 1,
              'Opposite signs mean the acceleration opposes the motion, so the speed falls. The positive velocity says it is still travelling in the positive direction while doing so.'),
            mcq('d2-2', '"A particle with negative acceleration must be slowing down." This statement is:',
              ['Always true', 'True only in free fall', 'False — it depends on the sign of the velocity', 'False — acceleration cannot be negative'], 2,
              'A negative acceleration acting on a particle with negative velocity speeds it up. Only the *relative* signs of $ v $ and $ a $ decide, and the sign of $ a $ alone also depends on which direction was chosen as positive.'),
            num('d2-3', 'A particle\'s velocity changes from $ +8 $ m/s to $ -4 $ m/s in $ 3 $ s. Find its average acceleration.',
              '$ -4 $ m/s²',
              '$ \\Delta v = (-4) - (+8) = -12 $ m/s, over 3 s, giving $ -4 $ m/s². Subtracting the magnitudes to get $ 4/3 $ m/s² is the classic error — the reversal makes the change larger than either velocity.'),
            mcq('d2-4', 'A particle has $ x = 6t - t^2 $ metres. At what time is it momentarily at rest?',
              ['$ t = 3 $ s', '$ t = 6 $ s', '$ t = 1.5 $ s', 'Never'], 0,
              '$ v = dx/dt = 6 - 2t $, which is zero at $ t = 3 $ s. At that instant the particle turns round; its acceleration there is $ -2 $ m/s², not zero.'),
            mcq('d2-5', 'At the highest point of the flight of a ball thrown vertically upward:',
              ['Velocity and acceleration are both zero', 'Velocity is zero, acceleration is $ g $', 'Velocity is $ g $, acceleration is zero', 'Neither is zero'], 1,
              'The ball is momentarily stationary so its velocity is zero, but gravity is unchanged and the acceleration remains $ g $ downward. If it were zero the ball would hover.'),
            num('d2-6', 'A particle has $ v = (12 - 3t) $ m/s. Find (a) its acceleration and (b) the time at which it reverses direction.',
              '(a) $ -3 $ m/s², constant  (b) $ t = 4 $ s',
              '(a) $ a = dv/dt = -3 $ m/s². (b) The velocity is zero when $ 12 = 3t $, so $ t = 4 $ s; after that it goes negative and the particle reverses.'),
            mcq('d2-7', 'An object moves in a circle at a constant speed of $ 15 $ m/s. Its acceleration is:',
              ['Zero, because its speed never changes at all', 'Non-zero, because the direction of the velocity changes', 'Zero except at the very start of the motion', 'Non-zero only at the moments it speeds up'], 1,
              'Acceleration is the rate of change of *velocity*, and velocity includes direction. Going round a bend changes the direction continuously, so there is an acceleration even with the speedometer steady.'),
            mcq('d2-8', 'A lift is descending and slowing down. Taking upward as positive, the signs of $ v $ and $ a $ are:',
              ['$ v > 0 $, $ a > 0 $', '$ v < 0 $, $ a > 0 $', '$ v < 0 $, $ a < 0 $', '$ v > 0 $, $ a < 0 $'], 1,
              'Descending makes the velocity negative. Slowing down means the acceleration opposes the velocity, so it must be positive — pointing upward while the lift moves down.'),
            num('d2-9', 'A particle has $ x = 2t^3 - 9t^2 + 12t $ metres. Find its acceleration when its velocity is zero.',
              '$ \\pm 6 $ m/s² (i.e. $ -6 $ m/s² at $ t = 1 $ s and $ +6 $ m/s² at $ t = 2 $ s)',
              '$ v = 6t^2 - 18t + 12 = 6(t-1)(t-2) $, which is zero at $ t = 1 $ s and $ t = 2 $ s. And $ a = 12t - 18 $, giving $ a = -6 $ m/s² at $ t = 1 $ s and $ a = +6 $ m/s² at $ t = 2 $ s. Two turning points, opposite accelerations.'),
            mcq('d2-10', 'For a particle moving along a straight line with constant non-zero speed, the acceleration is:',
              ['Zero', 'Non-zero and constant', 'Non-zero and changing', 'Cannot be determined'], 0,
              'On a line the particle cannot reverse without passing through zero speed, so a constant non-zero speed means the velocity never changes and the acceleration is zero. This fails in two dimensions.'),
          ],
        },
      ],
    }),
    b('practice_bank', 3, {
      title: 'Section 3 — Graphs',
      sections: [
        {
          id: 'p17-s3',
          title: 'Ten questions',
          items: [
            mcq('d3-1', 'The slope of a velocity–time graph gives:',
              ['The displacement', 'The acceleration', 'The distance', 'The average velocity'], 1,
              'Slope is always the rate of change of the vertical quantity, so on a v–t graph it is $ dv/dt $ — the acceleration. Displacement is the *area* under that graph.'),
            mcq('d3-2', 'The area under an acceleration–time graph gives:',
              ['The velocity at that instant', 'The change in velocity', 'The displacement so far', 'The acceleration at that instant'], 1,
              'Multiplying the axis units gives $ \\text{m/s}^2 \\times \\text{s} = \\text{m/s} $, a velocity — but it is the *change*, so you must add the velocity at some known instant to get an actual value.'),
            mcq('d3-3', 'The area under a position–time graph gives:',
              ['The velocity at that instant', 'The total displacement', 'The acceleration', 'No physically useful quantity'], 3,
              'The units come out as metre-seconds, which is not the unit of anything in mechanics. Slope is meaningful on all three graphs; area is meaningful only on the v–t and a–t graphs.'),
            num('d3-4', 'A v–t graph rises linearly from $ 4 $ m/s at $ t = 0 $ to $ 16 $ m/s at $ t = 6 $ s. Find the acceleration and the distance travelled.',
              '$ a = 2 $ m/s²; distance $ 60 $ m',
              'Acceleration is the slope: $ (16-4)/6 = 2 $ m/s². Distance is the area of the trapezium: $ \\frac{1}{2}(4 + 16)(6) = 60 $ m.'),
            mcq('d3-5', 'An x–t graph curves upward with a steadily increasing slope. The particle is:',
              ['Moving in the negative direction', 'Moving in the positive direction and speeding up', 'Moving in the positive direction and slowing down', 'At rest'], 1,
              'A positive slope means positive velocity; a slope that keeps growing means the velocity keeps growing. So it moves positively and speeds up.'),
            mcq('d3-6', 'Which of these is impossible for a real particle?',
              ['A v–t graph crossing the time axis', 'An x–t graph with a maximum', 'An x–t graph with a vertical segment', 'A v–t graph below the time axis'], 2,
              'A vertical segment on an x–t graph means the position changed while no time passed — infinite velocity. The others are all ordinary: an axis crossing on v–t is a reversal, a maximum on x–t is a turning point, and a negative velocity is perfectly normal.'),
            num('d3-7', 'A v–t graph is a triangle above the axis with area $ 24 $ m, followed by a triangle below the axis with area $ 9 $ m. Find the distance travelled and the displacement.',
              'Distance $ 33 $ m; displacement $ 15 $ m',
              'Distance ignores the sign: $ 24 + 9 = 33 $ m. Displacement respects it: $ 24 - 9 = 15 $ m.'),
            mcq('d3-8', 'A horizontal line on an x–t graph, well above the time axis, means the particle is:',
              ['Moving at a high constant speed', 'At rest at a position far from the origin', 'Accelerating steadily away from rest', 'Sitting exactly at the origin'], 1,
              'The *height* of the line is the position, so the particle sits far from the origin. The *slope* is the velocity, and a horizontal line has zero slope — so it is not moving at all.'),
            num('d3-9', 'A particle starts from rest. Its a–t graph is a horizontal line at $ 4 $ m/s² for $ 3 $ s, then zero for $ 2 $ s, then $ -6 $ m/s² for $ 2 $ s. Find its velocity at $ t = 7 $ s.',
              '$ 0 $',
              'First phase: area $ = 4 \\times 3 = +12 $ m/s. Second phase: zero area, so no change. Third phase: area $ = -6 \\times 2 = -12 $ m/s. Total change $ = 0 $, and the particle started from rest, so $ v = 0 $ at $ t = 7 $ s — momentarily at rest again.'),
            mcq('d3-10', 'A maximum on an x–t graph corresponds to which feature of the v–t graph?',
              ['A maximum on the velocity curve', 'A crossing of the time axis', 'A minimum on the velocity curve', 'A vertical segment on the curve'], 1,
              'A maximum on x–t means a horizontal tangent, so the velocity is zero there — and since the particle turns round, the v–t graph crosses the axis rather than merely touching it.'),
          ],
        },
      ],
    }),
    b('practice_bank', 4, {
      title: 'Section 4 — The equations of motion',
      sections: [
        {
          id: 'p17-s4',
          title: 'Ten questions',
          items: [
            num('d4-1', 'A body starts from rest with acceleration $ 3 $ m/s². Find its velocity and displacement after $ 6 $ s.',
              '$ v = 18 $ m/s; $ s = 54 $ m',
              '$ v = u + at = 0 + 3(6) = 18 $ m/s. $ s = \\frac{1}{2}(3)(36) = 54 $ m. Check with the mean velocity: $ 9 \\times 6 = 54 $ m. ✓'),
            mcq('d4-2', 'A body starting from rest with constant acceleration covers $ 5 $ m in the first second. In the first three seconds it covers:',
              ['$ 15 $ m', '$ 45 $ m', '$ 25 $ m', '$ 30 $ m'], 1,
              'From rest $ s \\propto t^2 $, so tripling the time multiplies the displacement by nine: $ 5 \\times 9 = 45 $ m. The 15 m answer assumes a linear relationship.'),
            num('d4-3', 'A train moving at $ 15 $ m/s decelerates uniformly and stops in $ 75 $ m. Find its retardation and the time taken.',
              '$ 1.5 $ m/s²; $ 10 $ s',
              '$ 0 = 225 + 2a(75) $, so $ a = -1.5 $ m/s². Then $ 0 = 15 - 1.5t $, giving $ t = 10 $ s. Check: mean velocity $ 7.5 \\times 10 = 75 $ m. ✓'),
            mcq('d4-4', 'The equation to use when time is neither given nor asked for is:',
              ['$ v = u + at $', '$ s = ut + \\frac{1}{2}at^2 $', '$ v^2 = u^2 + 2as $', '$ \\bar{v} = \\frac{u+v}{2} $'], 2,
              'Each equation omits one of the five quantities. The one without $ t $ is $ v^2 = u^2 + 2as $, which is why it is the workhorse for stopping-distance problems.'),
            num('d4-5', 'A body starting from rest with constant acceleration $ 8 $ m/s². Find its displacement during the 5th second.',
              '$ 36 $ m',
              '$ s_n = u + \\frac{a}{2}(2n-1) = 0 + 4(9) = 36 $ m. Check by subtraction: $ \\frac{1}{2}(8)(25) - \\frac{1}{2}(8)(16) = 100 - 64 = 36 $ m. ✓'),
            mcq('d4-6', 'The $ s $ in $ v^2 = u^2 + 2as $ is:',
              ['The distance travelled', 'The displacement', 'The path length', 'Always positive'], 1,
              'Every derivation came from the signed area under a v–t graph, so $ s $ is the displacement. It only equals the distance when the motion does not reverse.'),
            num('d4-7', 'A particle with initial velocity $ 6 $ m/s and constant acceleration $ -2 $ m/s² moves for $ 5 $ s. Find its displacement and the distance travelled.',
              'Displacement $ 5 $ m; distance $ 13 $ m',
              '$ t_0 = |6/2| = 3 $ s, so the motion reverses within the 5 s. Displacement: $ 6(5) - 1(25) = 5 $ m. Distance: it goes $ 36/4 = 9 $ m forward in the first 3 s, then $ \\frac{1}{2}(2)(4) = 4 $ m back in the remaining 2 s, giving $ 13 $ m.'),
            mcq('d4-8', 'For a body under constant acceleration, the average velocity over an interval equals:',
              ['$ \\frac{u+v}{2} $', '$ \\sqrt{uv} $', '$ \\frac{2uv}{u+v} $', 'The instantaneous velocity at the start'], 0,
              'The v–t graph is a straight line, so the average is the plain mean of the two end velocities. The other means belong to journeys split by equal distances rather than to constant acceleration.'),
            num('d4-9', 'A car accelerates uniformly from $ 10 $ m/s to $ 30 $ m/s over $ 100 $ m. Find its acceleration.',
              '$ 4 $ m/s²',
              '$ 900 = 100 + 2a(100) $, so $ 200a = 800 $ and $ a = 4 $ m/s². Time is not mentioned anywhere, which is the signal for this equation.'),
            mcq('d4-10', 'A body falling freely from rest covers distances in successive equal intervals in the ratio:',
              ['$ 1 : 2 : 3 $', '$ 1 : 3 : 5 $', '$ 1 : 4 : 9 $', '$ 1 : 1 : 1 $'], 1,
              'Galileo\'s law of odd numbers. The $ 1 : 4 : 9 $ ratio belongs to the *cumulative* distances, and the per-interval distances are their successive differences.'),
          ],
        },
      ],
    }),
    b('practice_bank', 5, {
      title: 'Section 5 — Free fall',
      sections: [
        {
          id: 'p17-s5',
          title: 'Ten questions',
          items: [
            num('d5-1', 'A stone is dropped from a height of $ 125 $ m. Find the time to land and the landing speed. Take $ g = 10 $ m/s².',
              '$ t = 5 $ s; $ v = 50 $ m/s',
              '$ t = \\sqrt{2h/g} = \\sqrt{25} = 5 $ s. And $ v = gt = 50 $ m/s, or $ v = \\sqrt{2gh} = \\sqrt{2500} = 50 $ m/s.'),
            mcq('d5-2', 'Two balls of different masses are dropped simultaneously from the same height, air resistance neglected. They:',
              ['Land together', 'The heavier lands first', 'The lighter lands first', 'It depends on their volumes'], 0,
              'The acceleration in free fall is $ g $ for every object, and mass appears in none of the equations of motion. In real air, shape and mass do matter — but "air resistance neglected" removes exactly that.'),
            num('d5-3', 'A ball is thrown upward at $ 40 $ m/s. Find its maximum height and total time of flight. Take $ g = 10 $ m/s².',
              '$ h = 80 $ m; $ T = 8 $ s',
              '$ h = u^2/2g = 1600/20 = 80 $ m. $ T = 2u/g = 80/10 = 8 $ s.'),
            mcq('d5-4', 'If the launch speed of a ball thrown upward is doubled, its maximum height becomes:',
              ['Exactly twice as much', 'Four times as much', 'Exactly half as much', 'Completely unchanged'], 1,
              '$ h = u^2/2g $, so the height goes as the square of the launch speed. Doubling $ u $ quadruples $ h $.'),
            num('d5-5', 'A ball is thrown upward at $ 25 $ m/s from the top of a $ 30 $ m tower. When does it land? Take $ g = 10 $ m/s².',
              '$ t = 6 $ s',
              'Upward positive, with $ s $ measured from the top of the tower: $ u = +25 $, $ a = -10 $, $ s = -30 $.\n\nSo $ -30 = 25t - 5t^2 $, giving $ 5t^2 - 25t - 30 = 0 $, or $ t^2 - 5t - 6 = 0 $. This factorises as $ (t-6)(t+1) = 0 $, so $ t = 6 $ s.'),
            mcq('d5-6', 'A ball thrown upward returns to the thrower. Which quantity is unchanged throughout the flight?',
              ['Speed', 'Velocity', 'Acceleration', 'Displacement'], 2,
              'The acceleration is $ g $ downward from launch to catch, unchanged in size and direction. The speed falls then rises, the velocity reverses sign, and the displacement changes continuously.'),
            num('d5-7', 'A body dropped from a tower takes $ 4 $ s to land. Find the tower height and the distance covered in the last second. Take $ g = 10 $ m/s².',
              'Height $ 80 $ m; last second $ 35 $ m',
              'Height $ = \\frac{1}{2}(10)(16) = 80 $ m. In 3 s it covers $ \\frac{1}{2}(10)(9) = 45 $ m, so the last second accounts for $ 80 - 45 = 35 $ m — nearly half the tower.'),
            mcq('d5-8', 'Two balls are thrown from a tower with the same speed, one up and one down. Their landing speeds are:',
              ['Equal', 'Greater for the one thrown down', 'Greater for the one thrown up', 'Dependent on the tower height'], 0,
              'Since $ v^2 = u^2 + 2gh $ involves $ u^2 $, reversing the launch direction leaves the landing speed unchanged. Only the flight times differ.'),
            num('d5-9', 'A ball is thrown upward and is at a height of $ 60 $ m at two instants $ 4 $ s apart. Find its launch speed. Take $ g = 10 $ m/s².',
              '$ u = 40 $ m/s',
              '$ 60 = ut - 5t^2 $ gives $ 5t^2 - ut + 60 = 0 $, whose two roots are the instants at that height. Their difference is $ \\frac{2\\sqrt{u^2 - 1200}}{10} $, and we are told it is 4 s.\n\nSo $ \\sqrt{u^2 - 1200} = 20 $, hence $ u^2 = 1600 $ and $ u = 40 $ m/s.\n\nCheck: $ h_{\\max} = u^2/2g = 1600/20 = 80 $ m, comfortably above 60 m — so the ball really does pass that height twice. ✓'),
            mcq('d5-10', 'A ball is released from rest inside a lift that is descending at a constant velocity. Relative to the lift, the ball\'s acceleration is:',
              ['$ g $ downward', 'Zero', 'Less than $ g $', 'Upward'], 0,
              'The lift moves at constant velocity, so its acceleration is zero and the relative acceleration is $ g - 0 = g $ downward. The ball falls inside the lift exactly as it would on the ground.'),
          ],
        },
      ],
    }),
    b('practice_bank', 6, {
      title: 'Section 6 — Relative motion, non-uniform acceleration and exam formats',
      sections: [
        {
          id: 'p17-s6a',
          title: 'Relative motion and changing acceleration',
          items: [
            mcq('d6-1', 'Two cars move towards each other at $ 20 $ m/s and $ 25 $ m/s. Their relative speed is:',
              ['$ 5 $ m/s', '$ 45 $ m/s', '$ 22.5 $ m/s', '$ 20 $ m/s'], 1,
              'Taking one direction as positive, the velocities are $ +20 $ and $ -25 $, so the relative velocity is $ 20 - (-25) = 45 $ m/s. Opposite directions make relative speeds add.'),
            num('d6-2', 'Two trains on parallel tracks move in the same direction at $ 30 $ m/s and $ 22 $ m/s. The slower is $ 160 $ m ahead. How long until the faster draws level?',
              '$ 20 $ s',
              'Relative speed $ = 30 - 22 = 8 $ m/s, closing a 160 m gap, so $ t = 160/8 = 20 $ s.'),
            mcq('d6-3', 'Two bodies in free fall, released at different times, have a relative acceleration of:',
              ['$ g $', '$ 2g $', 'Zero', 'It depends on the time gap'], 2,
              'Both have acceleration $ g $, so $ a_{AB} = g - g = 0 $. Their relative velocity is therefore constant, and the gap between them grows at a fixed rate.'),
            num('d6-4', 'A particle has $ x = 4t^3 - 6t^2 $ (SI units). Find its velocity and acceleration at $ t = 2 $ s.',
              '$ v = 24 $ m/s; $ a = 36 $ m/s²',
              '$ v = 12t^2 - 12t $, so at $ t = 2 $ s, $ v = 48 - 24 = 24 $ m/s. And $ a = 24t - 12 $, giving $ a = 36 $ m/s².'),
            mcq('d6-5', 'A particle\'s acceleration is $ a = 4t $ m/s². Which relation may be used to find its velocity?',
              ['$ v = u + at $', '$ v = u + \\int a\\,dt $', '$ v^2 = u^2 + 2as $', 'None of these'], 1,
              'The acceleration changes with time, so no equation of motion applies. The definition $ a = dv/dt $ still holds and integrates to $ v = u + \\int a\\,dt $.'),
            num('d6-6', 'A particle starts from rest at the origin with acceleration $ a = 9x $ (SI units). Find its speed at $ x = 2 $ m.',
              '$ 6 $ m/s',
              'The acceleration is given in terms of position, so use $ a = v\\dfrac{dv}{dx} $, i.e. $ v\\,dv = a\\,dx $.\n\n$ \\int_0^v v\\,dv = \\int_0^2 9x\\,dx $, so $ \\dfrac{v^2}{2} = \\left[\\dfrac{9x^2}{2}\\right]_0^2 = 18 $.\n\nHence $ v^2 = 36 $ and $ v = 6 $ m/s — found without ever knowing how long the particle took.'),
            mcq('d6-7', 'If $ v_{AB} = -7 $ m/s, then $ v_{BA} $ is:',
              ['$ -7 $ m/s', '$ +7 $ m/s', 'Zero', '$ +14 $ m/s'], 1,
              'Swapping the subscripts reverses the subtraction, so $ v_{BA} = -v_{AB} = +7 $ m/s.'),
            num('d6-8', 'Car A starts from rest with acceleration $ 2 $ m/s². Car B, $ 32 $ m ahead, moves at a constant $ 4 $ m/s in the same direction from the same instant. When does A catch B?',
              '$ t = 8 $ s',
              'In B\'s frame: $ u_{AB} = -4 $ m/s, $ a_{AB} = 2 $ m/s², gap $ 32 $ m. So $ 32 = -4t + t^2 $, giving $ t^2 - 4t - 32 = 0 $, which factorises as $ (t-8)(t+4) = 0 $, so $ t = 8 $ s.'),
          ],
        },
        {
          id: 'p17-s6b',
          title: 'Assertion and reason',
          items: [
            mcqFixed('d6-ar1', '**Assertion:** A body can have zero velocity and non-zero acceleration at the same instant.\n\n**Reason:** Velocity and acceleration are independent quantities, and nothing requires them to vanish together.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 0,
              'The assertion is true — a ball at the top of its flight is the standard case. The reason is also true and is exactly why: velocity describes the motion now, acceleration describes how it is changing, and there is no rule tying them together.'),
            mcqFixed('d6-ar2', '**Assertion:** A negative value of acceleration always means the body is slowing down.\n\n**Reason:** The sign of the acceleration depends on the choice of the positive direction of the axis.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 3,
              'The assertion is **false**: a negative acceleration acting on a body with negative velocity speeds it up. The reason is **true** and is part of why the assertion fails — the sign of $ a $ is a bookkeeping choice, not a physical fact about speeding up or slowing down.'),
            mcqFixed('d6-ar3', '**Assertion:** For a particle in one-dimensional motion, the average speed can never be less than the magnitude of the average velocity.\n\n**Reason:** The path length can never be less than the magnitude of the displacement.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 0,
              'Both are true, and the reason is precisely the explanation: dividing the inequality $ \\text{path} \\geq |\\Delta x| $ by the same time interval gives the statement about the two averages directly.'),
            mcqFixed('d6-ar4', '**Assertion:** The three equations of motion can be applied to a particle whose acceleration is $ a = 5t $ m/s².\n\n**Reason:** The equations of motion follow from the definitions of velocity and acceleration.',
              ['Both A and R are true, and R correctly explains A', 'Both A and R are true, but R does not explain A', 'A is true but R is false', 'A is false but R is true'], 3,
              'The assertion is **false** — the derivations require $ a $ to be constant so that it can be taken outside an integral, and $ 5t $ is not. The reason is **true**: the equations really are consequences of the definitions. That is exactly the step where the constant-acceleration condition enters.'),
          ],
        },
      ],
    }),
    b('callout', 7, {
      variant: 'note',
      title: 'What to do with your score',
      markdown: 'Do not average the six sections into one number — that hides the useful information.\n\nInstead find your **weakest section** and go back to the pages behind it. Section 1 → pages 1–2. Section 2 → pages 5–6. Section 3 → pages 4, 7 and 8. Section 4 → pages 9–10. Section 5 → page 11. Section 6 → pages 13–14.\n\nA section you scored below about 60% on is telling you something specific, and it is worth more of your time than re-doing a section you already got right.',
    }),
  ],
};

(async () => {
  await withDb(async (db) => {
    const bookId = await ensureChapter(db);
    await upsertPages(db, bookId, [p15, p16, p17]);
  });
  console.log('\n✅ Ch.2 wave 3 complete — pages 15–17. Chapter is now 18 pages.');
  process.exit(0);
})().catch((e) => { console.error(e); process.exit(1); });
