// Ch.4 (p-Block) · Page 15 · Sulphur — Allotropic Forms & Sulphur Dioxide
// (NCERT §7.14 + §7.15). Hero img → sulphur allotropes (rhombic/monoclinic,
// transition temperature, S₈ crown → Fig 7.5 img) → Example 7.12 (S₂
// paramagnetic) → SO₂ preparation → properties (bullets + bold-labeled
// reactions, incl. moist-SO₂ reducing-agent ★★★) → structure → uses. NCERT
// transcribed faithfully; notes-enrichment in `exam_tip`. Hosts In-text
// Questions 7.20, 7.21, 7.22.
module.exports = {
  page_number: 15,
  chapter: 4,
  slug: 'sulphur-and-sulphur-dioxide',
  title: 'Sulphur & Sulphur Dioxide',
  subtitle: 'The two important allotropes of sulphur, the S₈ crown ring, the paramagnetic S₂ trap — then sulphur dioxide, its preparation, its angular structure, and its career as a reducing agent.',
  tags: ['p-block', 'group-16', 'sulphur', 'sulphur-dioxide', 'allotropes'],
  reading_time_min: 7,
  build: (h) => [
    h.img(
      'A hand-drawn coloured science illustration on a deep charcoal (#121316) background, muted earthy palette (ochre, dusty teal, brick red), no glow or neon. Left: a bright yellow rhombic sulphur crystal lump. Right: a puckered eight-membered ring of sulphur atoms (the S₈ crown) drawn as a chalk-and-coloured-pencil textbook sketch. A small inset shows a colourless SO₂ gas molecule (bent). Clean inorganic plate, landscape, desktop-friendly.',
      '16:9',
      'Sulphur — yellow rhombic crystals built from puckered S₈ crown rings — and its dioxide.'
    ),

    h.heading('Sulphur — Allotropic Forms', 'Distinguish rhombic and monoclinic sulphur, state the transition temperature, and describe the S₈ ring.'),
    h.text(
      'Sulphur forms numerous allotropes of which the **yellow rhombic ($\\alpha$-sulphur)** and **monoclinic ($\\beta$-sulphur)** forms are the most important. The stable form at room temperature is rhombic sulphur, which transforms to monoclinic sulphur when heated above **369 K**.'
    ),
    h.text(
      '**Rhombic sulphur ($\\alpha$-sulphur).** This allotrope is yellow in colour, m.p. **385.8 K** and specific gravity **2.06**. Rhombic sulphur crystals are formed on evaporating the solution of roll sulphur in $\\ce{CS2}$. It is insoluble in water but dissolves to some extent in benzene, alcohol and ether. It is readily soluble in $\\ce{CS2}$.\n\n' +
      '**Monoclinic sulphur ($\\beta$-sulphur).** Its m.p. is **393 K** and specific gravity **1.98**. It is soluble in $\\ce{CS2}$. This form of sulphur is prepared by melting rhombic sulphur in a dish and cooling, till crust is formed. Two holes are made in the crust and the remaining liquid poured out. On removing the crust, colourless needle-shaped crystals of $\\beta$-sulphur are formed. It is stable above 369 K and transforms into $\\alpha$-sulphur below it. Conversely, $\\alpha$-sulphur is stable below 369 K and transforms into $\\beta$-sulphur above this. At 369 K both the forms are stable. This temperature is called **transition temperature**.'
    ),
    h.text(
      'Both rhombic and monoclinic sulphur have **$\\ce{S8}$ molecules**. These $\\ce{S8}$ molecules are packed to give different crystal structures. The $\\ce{S8}$ ring in both the forms is **puckered** and has a **crown shape**.\n\n' +
      'Several other modifications of sulphur containing 6–20 sulphur atoms per ring have been synthesised in the last two decades. In cyclo-$\\ce{S6}$, the ring adopts the chair form. At elevated temperatures (~1000 K), $\\ce{S2}$ is the dominant species and is **paramagnetic like $\\ce{O2}$**.'
    ),
    h.img(
      'A hand-drawn coloured molecular-structure sketch on a deep charcoal (#121316) background, muted earthy palette, no glow. Left (a): the puckered crown-shaped S₈ ring of rhombic sulphur, eight sulphur atoms drawn as small spheres in a zig-zag ring, with an S–S bond length marked 204 pm and an S–S–S bond angle marked 107°. Right (b): the chair-form cyclo-S₆ ring, six sulphur atoms, with bond length marked 205.7 pm and angle 102.2°. Clean inorganic textbook diagram, labelled (a) and (b).',
      '16:9',
      'Fig. 7.5 — The structures of (a) the S₈ ring in rhombic sulphur and (b) the S₆ form.'
    ),

    h.worked('NCERT Example 7.12', 'solved_example',
      'Which form of sulphur shows paramagnetic behaviour?',
      'In vapour state sulphur partly exists as $\\ce{S2}$ molecule which has two unpaired electrons in the antibonding $\\pi^*$ orbitals like $\\ce{O2}$ and, hence, exhibits paramagnetism.'),

    h.heading('Sulphur Dioxide', 'Describe the preparation, properties and structure of sulphur dioxide, and explain why moist SO₂ is a reducing agent.'),
    h.text('**Preparation**'),
    h.text(
      'Sulphur dioxide is formed together with a little (6–8%) sulphur trioxide when sulphur is burnt in air or oxygen:\n\n' +
      '$$\\ce{S(s) + O2(g) -> SO2(g)}$$\n\n' +
      'In the laboratory it is readily generated by treating a sulphite with dilute sulphuric acid.\n\n' +
      '$$\\ce{SO3^{2-}(aq) + 2H+(aq) -> H2O(l) + SO2(g)}$$\n\n' +
      'Industrially, it is produced as a by-product of the **roasting of sulphide ores**.\n\n' +
      '$$\\ce{4FeS2(s) + 11O2(g) -> 2Fe2O3(s) + 8SO2(g)}$$\n\n' +
      'The gas after drying is liquefied under pressure and stored in steel cylinders.'
    ),
    h.text(
      '**Physical properties**\n\n' +
      '- Sulphur dioxide is a **colourless gas with a pungent smell** and is highly soluble in water.\n' +
      '- It liquefies at room temperature under a pressure of two atmospheres and **boils at 263 K**.'
    ),
    h.text('**Chemical properties**'),
    h.text(
      '**Dissolves in water to give sulphurous acid.** When passed through water, $\\ce{SO2}$ forms a solution of sulphurous acid:\n\n' +
      '$$\\ce{SO2(g) + H2O(l) <=> H2SO3(aq)}$$'
    ),
    h.text(
      '**Reacts with sodium hydroxide.** It reacts readily with sodium hydroxide solution, forming sodium sulphite, which then reacts with more sulphur dioxide to form sodium hydrogen sulphite. (In its reaction with water and alkalies, the behaviour of $\\ce{SO2}$ is very similar to that of $\\ce{CO2}$.)\n\n' +
      '$$\\ce{2NaOH + SO2 -> Na2SO3 + H2O}$$\n' +
      '$$\\ce{Na2SO3 + H2O + SO2 -> 2NaHSO3}$$'
    ),
    h.text(
      '**Reacts with chlorine and is oxidised by oxygen.** $\\ce{SO2}$ reacts with chlorine in the presence of charcoal (which acts as a catalyst) to give sulphuryl chloride, $\\ce{SO2Cl2}$. It is oxidised to sulphur trioxide by oxygen in the presence of vanadium(V) oxide catalyst.\n\n' +
      '$$\\ce{SO2(g) + Cl2(g) -> SO2Cl2(l)}$$\n' +
      '$$\\ce{2SO2(g) + O2(g) ->[\\ce{V2O5}] 2SO3(g)}$$'
    ),
    h.text(
      '**Acts as a reducing agent when moist.** When moist, sulphur dioxide behaves as a reducing agent. For example, it converts iron(III) ions to iron(II) ions and decolourises acidified potassium permanganate(VII) solution; the latter reaction is a convenient test for the gas.\n\n' +
      '$$\\ce{2Fe^{3+} + SO2 + 2H2O -> 2Fe^{2+} + SO4^{2-} + 4H+}$$\n' +
      '$$\\ce{5SO2 + 2MnO4^{-} + 2H2O -> 5SO4^{2-} + 4H+ + 2Mn^{2+}}$$'
    ),
    h.callout('exam_tip', 'Exam Point — moist SO₂ is a reducing agent ★★★',
      '**Moist** sulphur dioxide is a classic reducing agent — high-yield for "identify the change" questions:\n\n' +
      '- $\\ce{Fe^{3+} -> Fe^{2+}}$ (decolourises/converts iron(III)).\n' +
      '- **Decolourises acidified $\\ce{KMnO4}$** ($\\ce{MnO4- -> Mn^{2+}}$) — this is the standard **test for $\\ce{SO2}$**.\n\n' +
      'Mnemonic: $\\ce{SO2}$ is reducing (S goes +4 → +6, i.e. it gets *oxidised* itself, reducing the other species).'),
    h.text(
      '**Structure.** The molecule of $\\ce{SO2}$ is **angular**. It is a **resonance hybrid** of the two canonical forms.'
    ),

    h.worked('In-text Question 7.20', 'ncert_intext',
      'What happens when sulphur dioxide is passed through an aqueous solution of Fe(III) salt?',
      'Moist sulphur dioxide acts as a reducing agent and reduces iron(III) to iron(II), itself being oxidised to sulphate:\n\n$$\\ce{2Fe^{3+} + SO2 + 2H2O -> 2Fe^{2+} + SO4^{2-} + 4H+}$$'),
    h.worked('In-text Question 7.21', 'ncert_intext',
      'Comment on the nature of two S–O bonds formed in $\\ce{SO2}$ molecule. Are the two S–O bonds in this molecule equal?',
      'The $\\ce{SO2}$ molecule is angular and is a resonance hybrid of two canonical forms. Because of this resonance, the **two S–O bonds are identical** (equal in length and strength) — each has the same intermediate (partial double-bond) character.'),
    h.worked('In-text Question 7.22', 'ncert_intext',
      'How is the presence of $\\ce{SO2}$ detected?',
      'The presence of $\\ce{SO2}$ is detected by its property of acting as a reducing agent when moist: it **decolourises acidified potassium permanganate(VII) solution**.\n\n$$\\ce{5SO2 + 2MnO4^{-} + 2H2O -> 5SO4^{2-} + 4H+ + 2Mn^{2+}}$$\n\nIt also has a characteristic pungent smell.'),

    h.heading('Uses'),
    h.text(
      'Sulphur dioxide is used (i) in refining petroleum and sugar (ii) in bleaching wool and silk and (iii) as an anti-chlor, disinfectant and preservative. Sulphuric acid, sodium hydrogen sulphite and calcium hydrogen sulphite (industrial chemicals) are manufactured from sulphur dioxide. Liquid $\\ce{SO2}$ is used as a solvent to dissolve a number of organic and inorganic chemicals.'
    ),

    h.recap([
      { label: 'Allotropes', text: '**rhombic ($\\alpha$, yellow, m.p. 385.8 K)** stable below 369 K; **monoclinic ($\\beta$, m.p. 393 K)** stable above; **369 K = transition temperature**. Both built from puckered crown-shaped $\\ce{S8}$ rings.' },
      { label: 'S₂ trap', text: 'at ~1000 K sulphur is mainly $\\ce{S2}$, **paramagnetic like $\\ce{O2}$** (two unpaired $\\pi^*$ electrons).' },
      { label: 'SO₂ made by', text: 'burning S in air; sulphite + dilute $\\ce{H2SO4}$; industrially roasting $\\ce{FeS2}$.' },
      { label: 'SO₂ reactions', text: '$\\ce{SO2 + H2O -> H2SO3}$; with NaOH → sulphite/bisulphite; **moist $\\ce{SO2}$ is reducing** ($\\ce{Fe^{3+} -> Fe^{2+}}$, decolourises $\\ce{KMnO4}$ — the test).' },
      { label: 'Structure', text: 'angular, **resonance hybrid**, two equal S–O bonds.' },
    ]),

    h.quiz([
      {
        question: 'The transition temperature at which rhombic and monoclinic sulphur are both stable is:',
        options: ['273 K', '369 K', '385.8 K', '393 K'],
        correct_index: 1,
        explanation: 'At 369 K both $\\alpha$ (rhombic) and $\\beta$ (monoclinic) forms are stable — this is the transition temperature. Below 369 K rhombic is stable; above it monoclinic is.',
      },
      {
        question: 'The S₈ molecule present in both rhombic and monoclinic sulphur has the shape of a:',
        options: [
          'puckered crown-shaped ring',
          'planar octagon',
          'linear chain',
          'tetrahedron',
        ],
        correct_index: 0,
        explanation: 'Both forms contain $\\ce{S8}$ rings that are puckered and crown-shaped; the two forms differ only in how these rings are packed.',
      },
      {
        question: 'Which form of sulphur is paramagnetic, like O₂?',
        options: [
          'rhombic S₈',
          'monoclinic S₈',
          'the S₂ molecule (dominant at ~1000 K)',
          'cyclo-S₆',
        ],
        correct_index: 2,
        explanation: 'At about 1000 K sulphur exists mainly as $\\ce{S2}$, which has two unpaired electrons in $\\pi^*$ orbitals like $\\ce{O2}$ and is therefore paramagnetic.',
      },
      {
        question: 'Industrially, sulphur dioxide is obtained chiefly as a by-product of:',
        options: [
          'electrolysis of water',
          'the Haber process',
          'thermal decomposition of HgO',
          'roasting of sulphide ores (e.g. FeS₂)',
        ],
        correct_index: 3,
        explanation: 'Roasting sulphide ores gives $\\ce{SO2}$: $\\ce{4FeS2 + 11O2 -> 2Fe2O3 + 8SO2}$.',
      },
      {
        question: 'The standard test for sulphur dioxide is that, when moist, it:',
        options: [
          'turns lime water milky permanently',
          'gives a deep-blue colour',
          'decolourises acidified potassium permanganate solution',
          'liberates a brown gas',
        ],
        correct_index: 2,
        explanation: 'Moist $\\ce{SO2}$ is a reducing agent and decolourises acidified $\\ce{KMnO4}$ ($\\ce{MnO4- -> Mn^{2+}}$) — a convenient test for the gas.',
      },
      {
        question: 'The two S–O bonds in the SO₂ molecule are:',
        options: [
          'equal, because SO₂ is a resonance hybrid',
          'unequal, one single and one double',
          'both pure single bonds',
          'arranged linearly',
        ],
        correct_index: 0,
        explanation: '$\\ce{SO2}$ is angular and a resonance hybrid, so its two S–O bonds are identical, each with partial double-bond character.',
      },
    ], 0.6),
  ],
};
