// CRITICAL: This taxonomy data is the single source of truth for the practice session.
// DO NOT MODIFY DIRECTLY — use the Taxonomy Dashboard at /crucible/admin/taxonomy
// Changes made in the dashboard are auto-saved here via POST /api/v2/taxonomy/save

export interface TaxonomyNode {
    id: string;
    name: string;
    parent_id: string | null;
    type: 'chapter' | 'topic';
    sequence_order?: number;
    class_level?: 11 | 12;
    chapterType?: 'physical' | 'inorganic' | 'organic' | 'practical';
}

export const TAXONOMY_FROM_CSV: TaxonomyNode[] = [
    // Unsorted - For bulk ingestion before categorization
    { id: 'ch_unsorted', name: 'Unsorted Questions', parent_id: null, type: 'chapter', sequence_order: 0, class_level: 11, chapterType: 'physical' },
    { id: 'tag_unsorted', name: 'Needs Categorization', parent_id: 'ch_unsorted', type: 'topic' },

    // Class 11
    { id: 'ch11_mole', name: 'Some Basic Concepts of Chemistry (Mole Concept)', parent_id: null, type: 'chapter', sequence_order: 1, class_level: 11, chapterType: 'physical' },
    { id: 'tag_mole_1', name: 'Laws Of Chemical Combination, Sig. Fig, Accuracy', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_2', name: 'Concentration Terms (M, m, X)', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_3', name: 'Empirical/Molecular Formula', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_4', name: 'Equivalent Concept & n-factor', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_5', name: 'Eudiometry (Gas Analysis)', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_6', name: 'Limiting Reagent', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_7', name: 'Mole Basics (Mass/Vol/Part)', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_8', name: 'Stoichiometry & Analysis', parent_id: 'ch11_mole', type: 'topic' },

    { id: 'ch11_atom', name: 'Structure of Atom', parent_id: null, type: 'chapter', sequence_order: 2, class_level: 11, chapterType: 'physical' },
    { id: 'tag_atom_1', name: 'Sub-atomic Particles & Discovery', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_2', name: 'Atomic Models (Thomson, Rutherford)', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_3', name: 'Quantum Mechanical Model of the Atom', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_4', name: 'EM Radiation & Planck\'s Quantum Theory', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_5', name: 'Photoelectric Effect & BBR', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_6', name: 'Bohr\'s Model & Hydrogen Spectrum', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_7', name: 'Quantum Numbers & Electronic Configuration', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_8', name: 'De-Broglie Theory & Uncertainty Principle', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_9', name: 'Wave function & Probability Graphs', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_10', name: 'Multi Concept', parent_id: 'ch11_atom', type: 'topic' },

    { id: 'ch11_periodic', name: 'Classification of Elements and Periodicity', parent_id: null, type: 'chapter', sequence_order: 3, class_level: 11, chapterType: 'physical' },
    { id: 'tag_periodic_1', name: 'Modern Periodic Law & IUPAC Nomenclature (Z > 100)', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_2', name: 'Atomic & lonic Radii Trends', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_3', name: 'Periodic Trends (I.E., E.A. E.N.)', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_4', name: 'Other Periodic Trends', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_5', name: 'Nature of Oxides', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_6', name: 'Valency & Diagonal Relationship', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_7', name: 'Multi-Concept', parent_id: 'ch11_periodic', type: 'topic' },

    { id: 'ch11_bonding', name: 'Chemical Bonding', parent_id: null, type: 'chapter', sequence_order: 4, class_level: 11, chapterType: 'physical' },
    { id: 'tag_bonding_1', name: 'lonic Bonding & Lattice Energy', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_2', name: 'Basics, Octet Rule, Formal Charge', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_3', name: 'Dipole Moment & Polarity', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_4', name: 'Fajan\'s Rule & Covalent Character', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_5', name: 'Hydrogen Bonding & Intermolecular Forces', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_6', name: 'VSEPR & Geometry', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_7', name: 'Misc. Concepts', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_8', name: 'Molecular Orbital Theory (MOT)', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_9', name: 'Molecular Properties (bond length, strength, angle) & Resonance', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_10', name: 'VBT and Hybridization', parent_id: 'ch11_bonding', type: 'topic' },

    { id: 'ch11_thermo', name: 'Thermodynamics', parent_id: null, type: 'chapter', sequence_order: 5, class_level: 11, chapterType: 'physical' },
    { id: 'tag_thermo_1', name: 'Basic Terms and Definitions', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_2', name: 'Calorimetry & Heat Capacity', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_3', name: 'Thermochemistry & Hess\'s Law', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_4', name: 'Internal Energy & Enthalpy change', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_5', name: 'Entropy & Second Law', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_6', name: 'Gibbs Free Energy & Spontaneity', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_7', name: 'First Law and Internal Energy', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_8', name: 'Work & Heat', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_9', name: 'Graphical Question', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_10', name: 'Multi Concept', parent_id: 'ch11_thermo', type: 'topic' },

    { id: 'ch11_chem_eq', name: 'Chemical Equilibrium', parent_id: null, type: 'chapter', sequence_order: 6, class_level: 11, chapterType: 'physical' },
    { id: 'tag_chem_eq_1', name: 'Law of Mass Action & Equilibrium Constants (K p, Kc)', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_2', name: 'Le Chatelier\'s Principle', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_3', name: 'Calculation of Kp, Kc, Kx', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_4', name: 'Physical & Chemical Equilibrium', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_5', name: 'Vapour Density & Degree of dissociation', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_6', name: 'Reaction Quotient & applications', parent_id: 'ch11_chem_eq', type: 'topic' },

    { id: 'ch11_ionic_eq', name: 'Ionic Equilibrium', parent_id: null, type: 'chapter', sequence_order: 7, class_level: 11, chapterType: 'physical' },
    { id: 'tag_ionic_eq_1', name: 'Buffer Solutions', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_2', name: 'Salt Hydrolysis', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_3', name: 'Solubility Product (Ksp)', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_4', name: 'pH Calculation (Acids/Bases)', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_5', name: 'Hydrolysis and pH calculation', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_6', name: 'lonic Product of water and pH scale', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_7', name: 'Theories of Acid/base & Ostwald Law', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_8', name: 'Titrations and Indicators', parent_id: 'ch11_ionic_eq', type: 'topic' },

    { id: 'ch11_redox', name: 'Redox Reactions', parent_id: null, type: 'chapter', sequence_order: 8, class_level: 11, chapterType: 'inorganic' },
    { id: 'tag_redox_1', name: 'Balancing of Redox Reactions', parent_id: 'ch11_redox', type: 'topic' },
    { id: 'tag_redox_2', name: 'Oxidation, Reduction and Oxidation Number', parent_id: 'ch11_redox', type: 'topic' },
    { id: 'tag_redox_3', name: 'Redox Titrations', parent_id: 'ch11_redox', type: 'topic' },
    { id: 'tag_redox_4', name: 'Types of Redox Reactions', parent_id: 'ch11_redox', type: 'topic' },

    { id: 'ch11_pblock', name: 'P Block (Class 11)', parent_id: null, type: 'chapter', sequence_order: 9, class_level: 11, chapterType: 'inorganic' },
    { id: 'tag_pblock11_1', name: 'Property Trends', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_2', name: 'Allotropes & Compounds of Carbon', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_3', name: 'Compounds of Boron (B2H6, Borax, Boric acid)', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_4', name: 'Properties & Reactions of Boron family', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_5', name: 'Properties & Reactions of Carbon Family', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_6', name: 'Silicates, Silicones and Zeolites', parent_id: 'ch11_pblock', type: 'topic' },

    { id: 'ch11_goc', name: 'GOC', parent_id: null, type: 'chapter', sequence_order: 10, class_level: 11, chapterType: 'organic' },
    { id: 'tag_goc_1', name: 'Classification & IUPAC Naming', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_2', name: 'Acidity & Basicity', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_3', name: 'Electronic Effects (Inductive, Resonance, Hyperconjugation)', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_4', name: 'Huckel\'s Rule & Aromaticity', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_5', name: 'Misc. Concepts', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_6', name: 'Reaction Intermediates', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_7', name: 'Structural Isomerism & Tautomerism', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_8', name: 'Electrophiles, Nucleophiles & Basic Terms', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_9', name: 'Stereoisomerism (Geometrical & Optical)', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_10', name: 'Chirality and Optical Activity', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_11', name: 'Enantiomers, Diastereomers & Meso Compounds', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_12', name: 'Conformational Isomerism', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_13', name: 'Conformations of Cycloalkanes', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_14', name: 'Geometrical Isomerism (E/Z, Cis/Trans)', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_15', name: 'Allenes, Atropisomers and Spiro Compounds', parent_id: 'ch11_goc', type: 'topic' },

    { id: 'ch11_hydrocarbon', name: 'Hydrocarbons', parent_id: null, type: 'chapter', sequence_order: 12, class_level: 11, chapterType: 'organic' },
    { id: 'tag_hydrocarbon_1', name: 'Alkynes (Acidity & Rxns)', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_2', name: 'Electrophilic addition across C=C', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_3', name: 'Misc. Reactions of Hydrocarbons', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_4', name: 'Oxidation Reactions of Alkenes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_5', name: 'Preparation & properties of benzene', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_6', name: 'Preparation Reactions of Alkanes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_7', name: 'Preparation and Properties of Alkenes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_8', name: 'Reactions of Alkanes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_9', name: 'Reactions of Benzene & Derivatives', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_10', name: 'Multi-Concept', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_ch11_hydrocarbon_1771659235901', name: 'Electrophilic Aromatic Substitution (SEAr)', parent_id: 'ch11_hydrocarbon', type: 'topic' },

    { id: 'ch11_prac_org', name: 'Practical Organic Chemistry', parent_id: null, type: 'chapter', sequence_order: 13, class_level: 11, chapterType: 'practical' },
    { id: 'tag_prac_org_1', name: 'Purification Methods (Distillation, Chromatography, Sublimation)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_2', name: 'Detection of Elements (Lassaigne\'s Test: N, S, Halogens)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_3', name: 'Quantitative Analysis (Dumas, Kjeldahl, Carius Methods)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_4', name: 'Tests for Unsaturation (Bromine Water, Bayer\'s Reagent)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_5', name: 'Tests for Hydroxyl Group (Ceric Ammonium Nitrate, Lucas Test)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_6', name: 'Tests for Carbonyls & Carboxyls (2, 4-DNP, Sodium Bicarbonate, Esterification)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_7', name: 'Tests for Amines (Hinsberg Test, Azo Dye Test, Carbylamine)', parent_id: 'ch11_prac_org', type: 'topic' },

    // Class 12
    { id: 'ch12_solutions', name: 'Solutions', parent_id: null, type: 'chapter', sequence_order: 15, class_level: 12, chapterType: 'physical' },
    { id: 'tag_solutions_1', name: 'Vapour Pressure & RLVP', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_2', name: 'Basics & Definitions', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_3', name: 'Raoult\'s Law (Ideal & Non ideal soln)', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_4', name: 'Concentration Terms', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_5', name: 'Elevation in BP / Depression in FP', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_6', name: 'Osmotic Pressure & Van\'t Hoff Factor', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_7', name: 'Solubility & Henry\'s Law', parent_id: 'ch12_solutions', type: 'topic' },

    { id: 'ch12_electrochem', name: 'Electrochemistry', parent_id: null, type: 'chapter', sequence_order: 16, class_level: 12, chapterType: 'physical' },
    { id: 'tag_electrochem_1', name: 'Batteries, Fuel Cells & Corrosion', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_2', name: 'Conductance & Kohlrausch Law', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_3', name: 'Electrochemical Series & its Applications', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_4', name: 'Electrode Potential and Galvanic Cell', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_5', name: 'Electrolysis & Faraday\'s Laws', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_6', name: 'Nernst Equation & Latimer Diagram', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_7', name: 'Multi-Concept', parent_id: 'ch12_electrochem', type: 'topic' },

    { id: 'ch12_kinetics', name: 'Chemical Kinetics', parent_id: null, type: 'chapter', sequence_order: 17, class_level: 12, chapterType: 'physical' },
    { id: 'tag_kinetics_1', name: 'Arrhenius Eq & Activation Energy', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_2', name: 'Complex Reactions', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_3', name: 'Radioactive Decay', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_4', name: 'Rate Law, Order of Reaction, Molecularity', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_5', name: 'Rate of Reactions and Factors affecting it', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_6', name: 'Reaction Mechanisms & Catalysis', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_7', name: 'Zero Order Reactions', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_8', name: 'First Order Reactions & Special cases', parent_id: 'ch12_kinetics', type: 'topic' },

    { id: 'ch12_pblock', name: 'P Block (12th)', parent_id: null, type: 'chapter', sequence_order: 18, class_level: 12, chapterType: 'inorganic' },
    { id: 'tag_pblock12_1', name: 'Properties of P-Block', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_2', name: 'Compounds of Halides', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_3', name: 'Compounds of Nitrogen', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_4', name: 'Compounds of Phosphorus', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_5', name: 'Compounds of Sulphur', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_6', name: 'Noble gases and their Reactions', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_7', name: 'Properties of Halogens', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_8', name: 'Properties of Nitrogen Family', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_9', name: 'Properties of Oxygen Family', parent_id: 'ch12_pblock', type: 'topic' },

    { id: 'ch12_dblock', name: 'D & F Block', parent_id: null, type: 'chapter', sequence_order: 19, class_level: 12, chapterType: 'inorganic' },
    { id: 'tag_dblock_1', name: 'Reactions of Transition Metals', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_2', name: 'Electronic Config. and Exceptions', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_3', name: 'I.E. ,Oxidation states, SRP', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_4', name: 'Preparation & Properties of KMnO4 & K2Cr2O7', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_5', name: 'Magnetic properties & Colour', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_6', name: 'Oxides, Catalytic Properties', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_7', name: 'Physical Properties of Transition metals', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_8', name: 'Properties of F block elements', parent_id: 'ch12_dblock', type: 'topic' },

    { id: 'ch12_coord', name: 'Coordination Compounds', parent_id: null, type: 'chapter', sequence_order: 20, class_level: 12, chapterType: 'inorganic' },
    { id: 'tag_coord_1', name: 'Basic Definitions & Ligands', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_2', name: 'Color & Magnetic Properties', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_3', name: 'Crystal Field Theory (CFT)', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_4', name: 'IUPAC Nomenclature', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_5', name: 'Isomerism (Structural/Stereo)', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_6', name: 'Metal Carbonyls & EAN', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_7', name: 'Stability & Applications', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_8', name: 'Valence Bond Theory (VBT)', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_9', name: 'Werner\'s Theory', parent_id: 'ch12_coord', type: 'topic' },

    { id: 'ch12_haloalkanes', name: 'Haloalkanes & Haloarenes', parent_id: null, type: 'chapter', sequence_order: 21, class_level: 12, chapterType: 'organic' },
    { id: 'tag_haloalkanes_1', name: 'Aryl Halides & Their Reactions', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_2', name: 'Elimination Reactions', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_4', name: 'Nucleophilicity, Basicity & Leaving Group', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_5', name: 'Physical properties of Haloalkanes', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_6', name: 'SN Reactions (SN1, SN2, SNi) & NGP', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_7', name: 'Preparation (From Alcohols, Hydrocarbons)', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_8', name: 'Elimination Reactions vs Substitution', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_9', name: 'Multi-Concept', parent_id: 'ch12_haloalkanes', type: 'topic' },

    { id: 'ch12_alcohols', name: 'Alcohols, Phenols & Ethers', parent_id: null, type: 'chapter', sequence_order: 22, class_level: 12, chapterType: 'organic' },
    { id: 'tag_alcohols_1', name: 'Alcohols Preparation (Grignard, Reduction)', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_2', name: 'Dehydration & Oxidation of Alcohols', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_3', name: 'Phenols Preparation & Acidic Nature', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_4', name: 'Phenol Reactions (Reimer-Tiemann, Kolbe etc)', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_5', name: 'Reactions of ethers, epoxides', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_6', name: 'Other Reactions of Alcohols', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_ch12_alcohols_1771659358099', name: 'SEAr Reactions of Phenols & Ethers', parent_id: 'ch12_alcohols', type: 'topic' },

    { id: 'ch12_carbonyl', name: 'Aldehydes, Ketones and Carboxylic Acids', parent_id: null, type: 'chapter', sequence_order: 23, class_level: 12, chapterType: 'organic' },
    { id: 'tag_aldehydes_1', name: 'Grignard Reagent', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_aldehydes_2', name: 'Name Reactions (Aldol, Cannizzaro, Perkins, Haloform, Claisen etc)', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_aldehydes_3', name: 'Other name reactions of carbonyl', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_aldehydes_4', name: 'Preparation raections of carbonyl', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_aldehydes_5', name: 'Tests for carbonyl compounds (Tollen\'s, Fehling, Benedict etc)', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_aldehydes_6', name: 'Nucleophilic Addition Reactions', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_aldehydes_7', name: 'Oxidation & Reduction Reactions of Carbony!', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_ch12_aldehydes_1771659373017', name: 'Reactions of Aromatic Aldehydes & Ketones', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_carboxylic_1', name: 'Acid Derivatives (Esters, Anhydrides, Amides)', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_carboxylic_2', name: 'Acidity Trends & Substituent Effects', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_carboxylic_3', name: 'Name Reactions (Dearboxylation, HVZ, Arndt Eistert etc.)', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_carboxylic_4', name: 'Preparation Methods', parent_id: 'ch12_carbonyl', type: 'topic' },
    { id: 'tag_ch12_carboxylic_1771659384907', name: 'Reactions of Aromatic Acids & Derivatives', parent_id: 'ch12_carbonyl', type: 'topic' },

    { id: 'ch12_amines', name: 'Amines', parent_id: null, type: 'chapter', sequence_order: 25, class_level: 12, chapterType: 'organic' },
    { id: 'tag_amines_1', name: 'Reactions of Aliphatic Amines', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_2', name: 'Tests for Amines (Hinsberg, Carbylamine, Hoffmann)', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_3', name: 'Basic Character (Gaseous vs Aqueous Phase)', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_4', name: 'Diazonium Salts & Coupling Reactions', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_5', name: 'Gabriel Phthalimide, Hofmann Bromamide & Carbylamine', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_ch12_amines_1771659399884', name: 'Reactions of Nitrobenzene & Aniline', parent_id: 'ch12_amines', type: 'topic' },

    { id: 'ch12_biomolecules', name: 'Biomolecules', parent_id: null, type: 'chapter', sequence_order: 26, class_level: 12, chapterType: 'organic' },
    { id: 'tag_biomolecules_1', name: 'Carbohydrates (Glucose Structure & Reactions)', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_2', name: 'Tests for Biomolecules', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_3', name: 'Di and Polysachharides', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_4', name: 'Nucleic Acids (DNA/RNA)', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_5', name: 'Proteins & Amino Acids', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_6', name: 'Vitamins & Enzymes', parent_id: 'ch12_biomolecules', type: 'topic' },

    { id: 'ch12_salt', name: 'Salt Analysis', parent_id: null, type: 'chapter', sequence_order: 27, class_level: 12, chapterType: 'practical' },
    { id: 'tag_salt_1', name: 'Anion Analysis', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_2', name: 'Cation Analysis', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_3', name: 'Anions: Conc. H2SO4 Group', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_4', name: 'Anions: Dil. H2SO4 Group', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_5', name: 'Anions: Special Group (S04, PO4)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_6', name: 'Cations: Group I (Pb, Ag, Hg)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_7', name: 'Cations: Group II (Cu, As, etc)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_8', name: 'Cations: Group III (Fe, Al, Cr)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_9', name: 'Cations: Group IV (Zn, Mn, Ni, Co)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_10', name: 'Cations: Group V (Ba, Sr, Ca)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_11', name: 'Cations: Group VI (Mg)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_12', name: 'Cations: Zero Group (NH4+)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_13', name: 'Dry Tests (Flame/Borax)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_14', name: 'Solubility Rules & Precipitation Colors', parent_id: 'ch12_salt', type: 'topic' },

    { id: 'ch12_prac_phys', name: 'Practical Physical Chemistry', parent_id: null, type: 'chapter', sequence_order: 28, class_level: 12, chapterType: 'practical' },
    { id: 'tag_prac_phys_1', name: 'Laboratory Apparatus & Errors in Measurement', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_2', name: 'Acid-Base Titration & Selection of Indicators (Phenolphthalein/Methyl Orange)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_3', name: 'Redox Titrations (K MnO4 / Oxalic Acid / Mohr\'s Salt)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_4', name: 'lodometric vs lodimetric Titrations (Starch Indicator)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_5', name: 'Hardness of Water (EDTA Titration)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_6', name: 'Surface Chemistry Practicals (Lyophilic/Lyophobic Sols & Dialysis)', parent_id: 'ch12_prac_phys', type: 'topic' },


    // ─── PHYSICS (Class 11) ─────────────────────────────────────────────────

    { id: 'ph11_units', name: 'Units, Dimensions & Errors', parent_id: null, type: 'chapter', sequence_order: 101, class_level: 11, chapterType: 'physical' },
    { id: 'tag_units_1', name: 'SI Units & Fundamental/Derived Quantities', parent_id: 'ph11_units', type: 'topic' },
    { id: 'tag_units_2', name: 'Dimensional Analysis & Applications', parent_id: 'ph11_units', type: 'topic' },
    { id: 'tag_units_3', name: 'Significant Figures & Rounding', parent_id: 'ph11_units', type: 'topic' },
    { id: 'tag_units_4', name: 'Error Analysis (Absolute, Relative, % Error)', parent_id: 'ph11_units', type: 'topic' },
    { id: 'tag_units_5', name: 'Vernier Callipers & Screw Gauge', parent_id: 'ph11_units', type: 'topic' },

    { id: 'ph11_kinematics1d', name: 'Kinematics 1D', parent_id: null, type: 'chapter', sequence_order: 102, class_level: 11, chapterType: 'physical' },
    { id: 'tag_k1d_1', name: 'Distance, Displacement & Speed', parent_id: 'ph11_kinematics1d', type: 'topic' },
    { id: 'tag_k1d_2', name: 'Velocity & Acceleration', parent_id: 'ph11_kinematics1d', type: 'topic' },
    { id: 'tag_k1d_3', name: 'Equations of Motion (SUVAT)', parent_id: 'ph11_kinematics1d', type: 'topic' },
    { id: 'tag_k1d_4', name: 'Motion Under Gravity (Free Fall)', parent_id: 'ph11_kinematics1d', type: 'topic' },
    { id: 'tag_k1d_5', name: 'Graphs (x-t, v-t, a-t)', parent_id: 'ph11_kinematics1d', type: 'topic' },
    { id: 'tag_k1d_6', name: 'Relative Motion in 1D', parent_id: 'ph11_kinematics1d', type: 'topic' },

    { id: 'ph11_kinematics2d', name: 'Kinematics 2D', parent_id: null, type: 'chapter', sequence_order: 103, class_level: 11, chapterType: 'physical' },
    { id: 'tag_k2d_1', name: 'Vectors (Addition, Resolution, Dot & Cross Product)', parent_id: 'ph11_kinematics2d', type: 'topic' },
    { id: 'tag_k2d_2', name: 'Projectile Motion', parent_id: 'ph11_kinematics2d', type: 'topic' },
    { id: 'tag_k2d_3', name: 'Relative Motion in 2D', parent_id: 'ph11_kinematics2d', type: 'topic' },
    { id: 'tag_k2d_4', name: 'Circular Motion (Uniform & Non-uniform)', parent_id: 'ph11_kinematics2d', type: 'topic' },
    { id: 'tag_k2d_5', name: 'River-Boat & Rain Problems', parent_id: 'ph11_kinematics2d', type: 'topic' },

    { id: 'ph11_nlm', name: 'Laws of Motion', parent_id: null, type: 'chapter', sequence_order: 104, class_level: 11, chapterType: 'physical' },
    { id: 'tag_nlm_1', name: "Newton's Laws (1st, 2nd, 3rd)", parent_id: 'ph11_nlm', type: 'topic' },
    { id: 'tag_nlm_2', name: 'Free Body Diagrams & Constraint Motion', parent_id: 'ph11_nlm', type: 'topic' },
    { id: 'tag_nlm_3', name: 'Friction (Static, Kinetic, Rolling)', parent_id: 'ph11_nlm', type: 'topic' },
    { id: 'tag_nlm_4', name: 'Pulley Systems & Connected Bodies', parent_id: 'ph11_nlm', type: 'topic' },
    { id: 'tag_nlm_5', name: 'Pseudo Force & Non-inertial Frames', parent_id: 'ph11_nlm', type: 'topic' },
    { id: 'tag_nlm_6', name: 'Circular Dynamics (Banking, Conical Pendulum)', parent_id: 'ph11_nlm', type: 'topic' },

    { id: 'ph11_wep', name: 'Work, Energy & Power', parent_id: null, type: 'chapter', sequence_order: 105, class_level: 11, chapterType: 'physical' },
    { id: 'tag_wep_1', name: 'Work Done by Constant & Variable Force', parent_id: 'ph11_wep', type: 'topic' },
    { id: 'tag_wep_2', name: 'Kinetic & Potential Energy', parent_id: 'ph11_wep', type: 'topic' },
    { id: 'tag_wep_3', name: 'Work-Energy Theorem', parent_id: 'ph11_wep', type: 'topic' },
    { id: 'tag_wep_4', name: 'Conservation of Energy', parent_id: 'ph11_wep', type: 'topic' },
    { id: 'tag_wep_5', name: 'Power & Efficiency', parent_id: 'ph11_wep', type: 'topic' },
    { id: 'tag_wep_6', name: 'Conservative vs Non-conservative Forces', parent_id: 'ph11_wep', type: 'topic' },

    { id: 'ph11_com_mom', name: 'Centre of Mass & Momentum', parent_id: null, type: 'chapter', sequence_order: 106, class_level: 11, chapterType: 'physical' },
    { id: 'tag_com_1', name: 'Centre of Mass (Discrete & Continuous)', parent_id: 'ph11_com_mom', type: 'topic' },
    { id: 'tag_com_2', name: 'Linear Momentum & Impulse', parent_id: 'ph11_com_mom', type: 'topic' },
    { id: 'tag_com_3', name: 'Conservation of Momentum', parent_id: 'ph11_com_mom', type: 'topic' },
    { id: 'tag_com_4', name: 'Collisions (Elastic, Inelastic, Perfectly Inelastic)', parent_id: 'ph11_com_mom', type: 'topic' },
    { id: 'tag_com_5', name: 'Coefficient of Restitution', parent_id: 'ph11_com_mom', type: 'topic' },

    { id: 'ph11_rotation', name: 'Rotational Motion', parent_id: null, type: 'chapter', sequence_order: 107, class_level: 11, chapterType: 'physical' },
    { id: 'tag_rot_1', name: 'Moment of Inertia & Theorems (PA, PP)', parent_id: 'ph11_rotation', type: 'topic' },
    { id: 'tag_rot_2', name: 'Torque & Angular Momentum', parent_id: 'ph11_rotation', type: 'topic' },
    { id: 'tag_rot_3', name: 'Rolling Motion (Pure Rolling)', parent_id: 'ph11_rotation', type: 'topic' },
    { id: 'tag_rot_4', name: 'Rotational Kinematics & Dynamics', parent_id: 'ph11_rotation', type: 'topic' },
    { id: 'tag_rot_5', name: 'Conservation of Angular Momentum', parent_id: 'ph11_rotation', type: 'topic' },
    { id: 'tag_rot_6', name: 'Equilibrium of Rigid Bodies', parent_id: 'ph11_rotation', type: 'topic' },

    { id: 'ph11_gravitation', name: 'Gravitation', parent_id: null, type: 'chapter', sequence_order: 108, class_level: 11, chapterType: 'physical' },
    { id: 'tag_grav_1', name: "Newton's Law of Gravitation", parent_id: 'ph11_gravitation', type: 'topic' },
    { id: 'tag_grav_2', name: 'Gravitational Field & Potential', parent_id: 'ph11_gravitation', type: 'topic' },
    { id: 'tag_grav_3', name: "Kepler's Laws & Orbital Motion", parent_id: 'ph11_gravitation', type: 'topic' },
    { id: 'tag_grav_4', name: 'Escape Velocity & Satellites', parent_id: 'ph11_gravitation', type: 'topic' },
    { id: 'tag_grav_5', name: 'Variation of g (Depth, Height, Rotation)', parent_id: 'ph11_gravitation', type: 'topic' },

    { id: 'ph11_matter', name: 'Properties of Matter', parent_id: null, type: 'chapter', sequence_order: 109, class_level: 11, chapterType: 'physical' },
    { id: 'tag_matter_1', name: 'Elasticity (Stress, Strain, Young\'s Modulus)', parent_id: 'ph11_matter', type: 'topic' },
    { id: 'tag_matter_2', name: 'Fluid Statics (Pressure, Buoyancy, Archimedes)', parent_id: 'ph11_matter', type: 'topic' },
    { id: 'tag_matter_3', name: 'Fluid Dynamics (Bernoulli, Continuity)', parent_id: 'ph11_matter', type: 'topic' },
    { id: 'tag_matter_4', name: 'Viscosity & Stokes\' Law', parent_id: 'ph11_matter', type: 'topic' },
    { id: 'tag_matter_5', name: 'Surface Tension & Capillarity', parent_id: 'ph11_matter', type: 'topic' },

    { id: 'ph11_thermo_phy', name: 'Thermodynamics & Kinetic Theory', parent_id: null, type: 'chapter', sequence_order: 110, class_level: 11, chapterType: 'physical' },
    { id: 'tag_phth_1', name: 'Thermal Expansion & Calorimetry', parent_id: 'ph11_thermo_phy', type: 'topic' },
    { id: 'tag_phth_2', name: 'Heat Transfer (Conduction, Convection, Radiation)', parent_id: 'ph11_thermo_phy', type: 'topic' },
    { id: 'tag_phth_3', name: 'Laws of Thermodynamics & Processes', parent_id: 'ph11_thermo_phy', type: 'topic' },
    { id: 'tag_phth_4', name: 'Carnot Engine & Efficiency', parent_id: 'ph11_thermo_phy', type: 'topic' },
    { id: 'tag_phth_5', name: 'Kinetic Theory (KE, RMS speed, Degrees of Freedom)', parent_id: 'ph11_thermo_phy', type: 'topic' },
    { id: 'tag_phth_6', name: 'Specific Heats (Cp, Cv) & Poisson\'s Ratio', parent_id: 'ph11_thermo_phy', type: 'topic' },

    { id: 'ph11_shm', name: 'Simple Harmonic Motion', parent_id: null, type: 'chapter', sequence_order: 111, class_level: 11, chapterType: 'physical' },
    { id: 'tag_shm_1', name: 'SHM Equations & Characteristics', parent_id: 'ph11_shm', type: 'topic' },
    { id: 'tag_shm_2', name: 'Energy in SHM', parent_id: 'ph11_shm', type: 'topic' },
    { id: 'tag_shm_3', name: 'Spring-Mass Systems', parent_id: 'ph11_shm', type: 'topic' },
    { id: 'tag_shm_4', name: 'Simple & Compound Pendulum', parent_id: 'ph11_shm', type: 'topic' },
    { id: 'tag_shm_5', name: 'Forced Oscillations & Resonance', parent_id: 'ph11_shm', type: 'topic' },

    { id: 'ph11_waves', name: 'Waves & Sound', parent_id: null, type: 'chapter', sequence_order: 112, class_level: 11, chapterType: 'physical' },
    { id: 'tag_waves_1', name: 'Wave Equation & Speed', parent_id: 'ph11_waves', type: 'topic' },
    { id: 'tag_waves_2', name: 'Superposition, Interference & Beats', parent_id: 'ph11_waves', type: 'topic' },
    { id: 'tag_waves_3', name: 'Standing Waves (Strings & Pipes)', parent_id: 'ph11_waves', type: 'topic' },
    { id: 'tag_waves_4', name: 'Doppler Effect', parent_id: 'ph11_waves', type: 'topic' },
    { id: 'tag_waves_5', name: 'Intensity & Loudness of Sound', parent_id: 'ph11_waves', type: 'topic' },

    // ─── PHYSICS (Class 12) ─────────────────────────────────────────────────

    { id: 'ph12_electrostatics', name: 'Electrostatics', parent_id: null, type: 'chapter', sequence_order: 113, class_level: 12, chapterType: 'physical' },
    { id: 'tag_elst_1', name: "Coulomb's Law & Electric Force", parent_id: 'ph12_electrostatics', type: 'topic' },
    { id: 'tag_elst_2', name: 'Electric Field (Point Charges, Dipole, Continuous)', parent_id: 'ph12_electrostatics', type: 'topic' },
    { id: 'tag_elst_3', name: "Gauss's Law & Applications", parent_id: 'ph12_electrostatics', type: 'topic' },
    { id: 'tag_elst_4', name: 'Electric Potential & Potential Energy', parent_id: 'ph12_electrostatics', type: 'topic' },
    { id: 'tag_elst_5', name: 'Conductors, Capacitors & Dielectrics', parent_id: 'ph12_electrostatics', type: 'topic' },
    { id: 'tag_elst_6', name: 'Energy Stored in Capacitors & Circuits', parent_id: 'ph12_electrostatics', type: 'topic' },

    { id: 'ph12_current', name: 'Current Electricity', parent_id: null, type: 'chapter', sequence_order: 114, class_level: 12, chapterType: 'physical' },
    { id: 'tag_curr_1', name: 'Ohm\'s Law, Resistance & Resistivity', parent_id: 'ph12_current', type: 'topic' },
    { id: 'tag_curr_2', name: 'Kirchhoff\'s Laws (KVL, KCL)', parent_id: 'ph12_current', type: 'topic' },
    { id: 'tag_curr_3', name: 'Wheatstone Bridge & Potentiometer', parent_id: 'ph12_current', type: 'topic' },
    { id: 'tag_curr_4', name: 'Cell EMF, Internal Resistance & Combination', parent_id: 'ph12_current', type: 'topic' },
    { id: 'tag_curr_5', name: 'Power Dissipation & Heating Effect', parent_id: 'ph12_current', type: 'topic' },

    { id: 'ph12_magnetism', name: 'Magnetism & Moving Charges', parent_id: null, type: 'chapter', sequence_order: 115, class_level: 12, chapterType: 'physical' },
    { id: 'tag_mag_1', name: 'Magnetic Force on Charges & Wires (Lorentz)', parent_id: 'ph12_magnetism', type: 'topic' },
    { id: 'tag_mag_2', name: 'Biot-Savart Law & Ampere\'s Law', parent_id: 'ph12_magnetism', type: 'topic' },
    { id: 'tag_mag_3', name: 'Magnetic Field of Solenoid & Toroid', parent_id: 'ph12_magnetism', type: 'topic' },
    { id: 'tag_mag_4', name: 'Motion of Charges in Magnetic Field', parent_id: 'ph12_magnetism', type: 'topic' },
    { id: 'tag_mag_5', name: 'Torque on Current Loop & Moving Coil Galvanometer', parent_id: 'ph12_magnetism', type: 'topic' },
    { id: 'tag_mag_6', name: 'Diamagnetism, Paramagnetism & Ferromagnetism', parent_id: 'ph12_magnetism', type: 'topic' },

    { id: 'ph12_emi', name: 'Electromagnetic Induction', parent_id: null, type: 'chapter', sequence_order: 116, class_level: 12, chapterType: 'physical' },
    { id: 'tag_emi_1', name: 'Magnetic Flux & Faraday\'s Law', parent_id: 'ph12_emi', type: 'topic' },
    { id: 'tag_emi_2', name: 'Lenz\'s Law & Motional EMF', parent_id: 'ph12_emi', type: 'topic' },
    { id: 'tag_emi_3', name: 'Self Inductance & Mutual Inductance', parent_id: 'ph12_emi', type: 'topic' },
    { id: 'tag_emi_4', name: 'Energy Stored in Inductors', parent_id: 'ph12_emi', type: 'topic' },
    { id: 'tag_emi_5', name: 'Eddy Currents & Applications', parent_id: 'ph12_emi', type: 'topic' },

    { id: 'ph12_ac', name: 'Alternating Current', parent_id: null, type: 'chapter', sequence_order: 117, class_level: 12, chapterType: 'physical' },
    { id: 'tag_ac_1', name: 'AC Fundamentals (RMS, Peak, Frequency)', parent_id: 'ph12_ac', type: 'topic' },
    { id: 'tag_ac_2', name: 'R, L, C in AC Circuits', parent_id: 'ph12_ac', type: 'topic' },
    { id: 'tag_ac_3', name: 'Series LCR & Resonance', parent_id: 'ph12_ac', type: 'topic' },
    { id: 'tag_ac_4', name: 'Power in AC Circuits & Power Factor', parent_id: 'ph12_ac', type: 'topic' },
    { id: 'tag_ac_5', name: 'Transformers', parent_id: 'ph12_ac', type: 'topic' },

    { id: 'ph12_ray_optics', name: 'Ray Optics', parent_id: null, type: 'chapter', sequence_order: 118, class_level: 12, chapterType: 'physical' },
    { id: 'tag_rop_1', name: 'Reflection (Plane & Curved Mirrors)', parent_id: 'ph12_ray_optics', type: 'topic' },
    { id: 'tag_rop_2', name: 'Refraction at Plane Surfaces & TIR', parent_id: 'ph12_ray_optics', type: 'topic' },
    { id: 'tag_rop_3', name: 'Prism & Dispersion', parent_id: 'ph12_ray_optics', type: 'topic' },
    { id: 'tag_rop_4', name: 'Refraction at Curved Surfaces & Lenses', parent_id: 'ph12_ray_optics', type: 'topic' },
    { id: 'tag_rop_5', name: 'Optical Instruments (Microscope, Telescope)', parent_id: 'ph12_ray_optics', type: 'topic' },
    { id: 'tag_rop_6', name: 'Power of Lens & Lens Maker\'s Equation', parent_id: 'ph12_ray_optics', type: 'topic' },

    { id: 'ph12_wave_optics', name: 'Wave Optics', parent_id: null, type: 'chapter', sequence_order: 119, class_level: 12, chapterType: 'physical' },
    { id: 'tag_wvop_1', name: 'Huygens\' Principle & Wavefronts', parent_id: 'ph12_wave_optics', type: 'topic' },
    { id: 'tag_wvop_2', name: 'Young\'s Double Slit Experiment (YDSE)', parent_id: 'ph12_wave_optics', type: 'topic' },
    { id: 'tag_wvop_3', name: 'Interference Conditions & Fringe Width', parent_id: 'ph12_wave_optics', type: 'topic' },
    { id: 'tag_wvop_4', name: 'Diffraction (Single Slit)', parent_id: 'ph12_wave_optics', type: 'topic' },
    { id: 'tag_wvop_5', name: 'Polarisation', parent_id: 'ph12_wave_optics', type: 'topic' },

    { id: 'ph12_modern', name: 'Modern Physics', parent_id: null, type: 'chapter', sequence_order: 120, class_level: 12, chapterType: 'physical' },
    { id: 'tag_mod_1', name: 'Photoelectric Effect & Einstein\'s Equation', parent_id: 'ph12_modern', type: 'topic' },
    { id: 'tag_mod_2', name: 'de Broglie Waves & Davisson-Germer', parent_id: 'ph12_modern', type: 'topic' },
    { id: 'tag_mod_3', name: 'Bohr\'s Model & Hydrogen Spectrum', parent_id: 'ph12_modern', type: 'topic' },
    { id: 'tag_mod_4', name: 'Nuclear Structure, Binding Energy & Mass Defect', parent_id: 'ph12_modern', type: 'topic' },
    { id: 'tag_mod_5', name: 'Radioactivity & Nuclear Reactions', parent_id: 'ph12_modern', type: 'topic' },
    { id: 'tag_mod_6', name: 'X-Rays', parent_id: 'ph12_modern', type: 'topic' },

    { id: 'ph12_semiconductors', name: 'Semiconductors & Communication', parent_id: null, type: 'chapter', sequence_order: 121, class_level: 12, chapterType: 'physical' },
    { id: 'tag_semi_1', name: 'Semiconductor Basics (n-type, p-type, Energy Bands)', parent_id: 'ph12_semiconductors', type: 'topic' },
    { id: 'tag_semi_2', name: 'p-n Junction Diode & Characteristics', parent_id: 'ph12_semiconductors', type: 'topic' },
    { id: 'tag_semi_3', name: 'Rectifiers (Half-wave, Full-wave)', parent_id: 'ph12_semiconductors', type: 'topic' },
    { id: 'tag_semi_4', name: 'Zener Diode & Voltage Regulation', parent_id: 'ph12_semiconductors', type: 'topic' },
    { id: 'tag_semi_5', name: 'Transistors (BJT, CE Config) & Logic Gates', parent_id: 'ph12_semiconductors', type: 'topic' },

    // ─── MATHEMATICS (Class 11) ─────────────────────────────────────────────

    { id: 'ma11_sets', name: 'Sets, Relations & Functions', parent_id: null, type: 'chapter', sequence_order: 201, class_level: 11, chapterType: 'physical' },
    { id: 'tag_sets_1', name: 'Sets & Set Operations (Union, Intersection, Complement)', parent_id: 'ma11_sets', type: 'topic' },
    { id: 'tag_sets_2', name: 'Venn Diagrams & Applications', parent_id: 'ma11_sets', type: 'topic' },
    { id: 'tag_sets_3', name: 'Relations (Types, Domain, Range)', parent_id: 'ma11_sets', type: 'topic' },
    { id: 'tag_sets_4', name: 'Functions (Injective, Surjective, Bijective)', parent_id: 'ma11_sets', type: 'topic' },
    { id: 'tag_sets_5', name: 'Composition of Functions & Inverse', parent_id: 'ma11_sets', type: 'topic' },

    { id: 'ma11_complex', name: 'Complex Numbers & Quadratic Equations', parent_id: null, type: 'chapter', sequence_order: 202, class_level: 11, chapterType: 'physical' },
    { id: 'tag_cmpx_1', name: 'Algebra of Complex Numbers & Argand Plane', parent_id: 'ma11_complex', type: 'topic' },
    { id: 'tag_cmpx_2', name: 'Modulus, Argument & Polar Form', parent_id: 'ma11_complex', type: 'topic' },
    { id: 'tag_cmpx_3', name: 'De Moivre\'s Theorem & Roots of Unity', parent_id: 'ma11_complex', type: 'topic' },
    { id: 'tag_cmpx_4', name: 'Quadratic Equations (Discriminant, Nature of Roots)', parent_id: 'ma11_complex', type: 'topic' },
    { id: 'tag_cmpx_5', name: 'Equations Reducible to Quadratic', parent_id: 'ma11_complex', type: 'topic' },
    { id: 'tag_cmpx_6', name: 'Locus Problems in Complex Plane', parent_id: 'ma11_complex', type: 'topic' },

    { id: 'ma11_sequences', name: 'Sequences & Series', parent_id: null, type: 'chapter', sequence_order: 203, class_level: 11, chapterType: 'physical' },
    { id: 'tag_seq_1', name: 'Arithmetic Progression (AP)', parent_id: 'ma11_sequences', type: 'topic' },
    { id: 'tag_seq_2', name: 'Geometric Progression (GP)', parent_id: 'ma11_sequences', type: 'topic' },
    { id: 'tag_seq_3', name: 'Harmonic Progression & AM-GM-HM Inequality', parent_id: 'ma11_sequences', type: 'topic' },
    { id: 'tag_seq_4', name: 'Sum of Special Series (n, n², n³)', parent_id: 'ma11_sequences', type: 'topic' },
    { id: 'tag_seq_5', name: 'Arithmetico-Geometric Series', parent_id: 'ma11_sequences', type: 'topic' },

    { id: 'ma11_pnc', name: 'Permutations & Combinations', parent_id: null, type: 'chapter', sequence_order: 204, class_level: 11, chapterType: 'physical' },
    { id: 'tag_pnc_1', name: 'Fundamental Counting Principle', parent_id: 'ma11_pnc', type: 'topic' },
    { id: 'tag_pnc_2', name: 'Permutations (with & without Repetition)', parent_id: 'ma11_pnc', type: 'topic' },
    { id: 'tag_pnc_3', name: 'Combinations & Selection', parent_id: 'ma11_pnc', type: 'topic' },
    { id: 'tag_pnc_4', name: 'Circular Permutations', parent_id: 'ma11_pnc', type: 'topic' },
    { id: 'tag_pnc_5', name: 'Distribution Problems', parent_id: 'ma11_pnc', type: 'topic' },

    { id: 'ma11_binomial', name: 'Binomial Theorem', parent_id: null, type: 'chapter', sequence_order: 205, class_level: 11, chapterType: 'physical' },
    { id: 'tag_bino_1', name: 'Binomial Expansion & General Term', parent_id: 'ma11_binomial', type: 'topic' },
    { id: 'tag_bino_2', name: 'Middle Term & Term Independent of x', parent_id: 'ma11_binomial', type: 'topic' },
    { id: 'tag_bino_3', name: 'Binomial Coefficients & Properties', parent_id: 'ma11_binomial', type: 'topic' },
    { id: 'tag_bino_4', name: 'Multinomial Theorem', parent_id: 'ma11_binomial', type: 'topic' },

    { id: 'ma11_trigonometry', name: 'Trigonometric Functions & Equations', parent_id: null, type: 'chapter', sequence_order: 206, class_level: 11, chapterType: 'physical' },
    { id: 'tag_trig_1', name: 'Trigonometric Ratios & Identities', parent_id: 'ma11_trigonometry', type: 'topic' },
    { id: 'tag_trig_2', name: 'Compound, Multiple & Sub-multiple Angle Formulas', parent_id: 'ma11_trigonometry', type: 'topic' },
    { id: 'tag_trig_3', name: 'Product-to-Sum & Sum-to-Product', parent_id: 'ma11_trigonometry', type: 'topic' },
    { id: 'tag_trig_4', name: 'Trigonometric Equations (General Solution)', parent_id: 'ma11_trigonometry', type: 'topic' },
    { id: 'tag_trig_5', name: 'Properties of Triangles (Sine Rule, Cosine Rule)', parent_id: 'ma11_trigonometry', type: 'topic' },

    { id: 'ma11_straight_lines', name: 'Straight Lines & Pair of Lines', parent_id: null, type: 'chapter', sequence_order: 207, class_level: 11, chapterType: 'physical' },
    { id: 'tag_stln_1', name: 'Equation of Line (Various Forms)', parent_id: 'ma11_straight_lines', type: 'topic' },
    { id: 'tag_stln_2', name: 'Angle, Distance & Foot of Perpendicular', parent_id: 'ma11_straight_lines', type: 'topic' },
    { id: 'tag_stln_3', name: 'Family of Lines & Concurrent Lines', parent_id: 'ma11_straight_lines', type: 'topic' },
    { id: 'tag_stln_4', name: 'Pair of Straight Lines (Combined Equation)', parent_id: 'ma11_straight_lines', type: 'topic' },

    { id: 'ma11_conics', name: 'Conic Sections', parent_id: null, type: 'chapter', sequence_order: 208, class_level: 11, chapterType: 'physical' },
    { id: 'tag_coni_1', name: 'Circle (Equation, Tangent, Normal)', parent_id: 'ma11_conics', type: 'topic' },
    { id: 'tag_coni_2', name: 'Parabola (Standard & Shifted)', parent_id: 'ma11_conics', type: 'topic' },
    { id: 'tag_coni_3', name: 'Ellipse (Standard Form, Foci, Eccentricity)', parent_id: 'ma11_conics', type: 'topic' },
    { id: 'tag_coni_4', name: 'Hyperbola (Standard Form, Asymptotes)', parent_id: 'ma11_conics', type: 'topic' },
    { id: 'tag_coni_5', name: 'Chord of Contact & Pair of Tangents', parent_id: 'ma11_conics', type: 'topic' },

    { id: 'ma11_limits', name: 'Limits & Derivatives', parent_id: null, type: 'chapter', sequence_order: 209, class_level: 11, chapterType: 'physical' },
    { id: 'tag_lim_1', name: 'Limits (Algebraic, Trigonometric Forms)', parent_id: 'ma11_limits', type: 'topic' },
    { id: 'tag_lim_2', name: 'L\'Hôpital\'s Rule & Standard Limits', parent_id: 'ma11_limits', type: 'topic' },
    { id: 'tag_lim_3', name: 'Continuity & Types of Discontinuity', parent_id: 'ma11_limits', type: 'topic' },
    { id: 'tag_lim_4', name: 'Derivatives from First Principles', parent_id: 'ma11_limits', type: 'topic' },

    { id: 'ma11_math_induction', name: 'Mathematical Reasoning & Induction', parent_id: null, type: 'chapter', sequence_order: 210, class_level: 11, chapterType: 'physical' },
    { id: 'tag_mi_1', name: 'Mathematical Induction (Principle & Application)', parent_id: 'ma11_math_induction', type: 'topic' },
    { id: 'tag_mi_2', name: 'Logical Connectives & Statements', parent_id: 'ma11_math_induction', type: 'topic' },

    { id: 'ma11_stats', name: 'Statistics & Probability (Class 11)', parent_id: null, type: 'chapter', sequence_order: 211, class_level: 11, chapterType: 'physical' },
    { id: 'tag_stat_1', name: 'Measures of Central Tendency (Mean, Median, Mode)', parent_id: 'ma11_stats', type: 'topic' },
    { id: 'tag_stat_2', name: 'Measures of Dispersion (Variance, SD)', parent_id: 'ma11_stats', type: 'topic' },
    { id: 'tag_stat_3', name: 'Classical Probability & Sample Space', parent_id: 'ma11_stats', type: 'topic' },
    { id: 'tag_stat_4', name: 'Conditional Probability & Independent Events', parent_id: 'ma11_stats', type: 'topic' },

    // ─── MATHEMATICS (Class 12) ─────────────────────────────────────────────

    { id: 'ma12_functions', name: 'Relations, Functions & Inverse Trigonometry', parent_id: null, type: 'chapter', sequence_order: 212, class_level: 12, chapterType: 'physical' },
    { id: 'tag_func_1', name: 'Types of Functions & Graphs', parent_id: 'ma12_functions', type: 'topic' },
    { id: 'tag_func_2', name: 'Composite & Inverse Functions', parent_id: 'ma12_functions', type: 'topic' },
    { id: 'tag_func_3', name: 'Inverse Trigonometric Functions (Domain, Range)', parent_id: 'ma12_functions', type: 'topic' },
    { id: 'tag_func_4', name: 'Properties & Identities of Inverse Trig', parent_id: 'ma12_functions', type: 'topic' },

    { id: 'ma12_matrices', name: 'Matrices & Determinants', parent_id: null, type: 'chapter', sequence_order: 213, class_level: 12, chapterType: 'physical' },
    { id: 'tag_mat_1', name: 'Matrix Operations & Types', parent_id: 'ma12_matrices', type: 'topic' },
    { id: 'tag_mat_2', name: 'Determinants & Properties', parent_id: 'ma12_matrices', type: 'topic' },
    { id: 'tag_mat_3', name: 'Adjoint, Inverse & Rank of Matrix', parent_id: 'ma12_matrices', type: 'topic' },
    { id: 'tag_mat_4', name: 'System of Linear Equations (Cramer\'s Rule)', parent_id: 'ma12_matrices', type: 'topic' },
    { id: 'tag_mat_5', name: 'Cayley-Hamilton Theorem', parent_id: 'ma12_matrices', type: 'topic' },

    { id: 'ma12_diff_calculus', name: 'Continuity, Differentiability & Methods of Differentiation', parent_id: null, type: 'chapter', sequence_order: 214, class_level: 12, chapterType: 'physical' },
    { id: 'tag_diff_1', name: 'Differentiability & Chain Rule', parent_id: 'ma12_diff_calculus', type: 'topic' },
    { id: 'tag_diff_2', name: 'Parametric, Implicit & Logarithmic Differentiation', parent_id: 'ma12_diff_calculus', type: 'topic' },
    { id: 'tag_diff_3', name: 'Higher Order Derivatives', parent_id: 'ma12_diff_calculus', type: 'topic' },
    { id: 'tag_diff_4', name: 'Mean Value Theorems (Rolle\'s, LMVT)', parent_id: 'ma12_diff_calculus', type: 'topic' },

    { id: 'ma12_aod', name: 'Application of Derivatives', parent_id: null, type: 'chapter', sequence_order: 215, class_level: 12, chapterType: 'physical' },
    { id: 'tag_aod_1', name: 'Tangents & Normals', parent_id: 'ma12_aod', type: 'topic' },
    { id: 'tag_aod_2', name: 'Monotonicity & Maxima/Minima', parent_id: 'ma12_aod', type: 'topic' },
    { id: 'tag_aod_3', name: 'Rate of Change & Approximation', parent_id: 'ma12_aod', type: 'topic' },
    { id: 'tag_aod_4', name: 'Curve Sketching & Concavity', parent_id: 'ma12_aod', type: 'topic' },

    { id: 'ma12_integrals', name: 'Integral Calculus', parent_id: null, type: 'chapter', sequence_order: 216, class_level: 12, chapterType: 'physical' },
    { id: 'tag_intg_1', name: 'Standard Integrals & Basic Rules', parent_id: 'ma12_integrals', type: 'topic' },
    { id: 'tag_intg_2', name: 'Integration by Substitution & Parts', parent_id: 'ma12_integrals', type: 'topic' },
    { id: 'tag_intg_3', name: 'Integration by Partial Fractions', parent_id: 'ma12_integrals', type: 'topic' },
    { id: 'tag_intg_4', name: 'Definite Integrals & Properties', parent_id: 'ma12_integrals', type: 'topic' },
    { id: 'tag_intg_5', name: 'Reduction Formulas & Special Integrals', parent_id: 'ma12_integrals', type: 'topic' },

    { id: 'ma12_aoi', name: 'Application of Integrals & Differential Equations', parent_id: null, type: 'chapter', sequence_order: 217, class_level: 12, chapterType: 'physical' },
    { id: 'tag_aoi_1', name: 'Area under Curves & Between Curves', parent_id: 'ma12_aoi', type: 'topic' },
    { id: 'tag_aoi_2', name: 'Differential Equations (Formation & Solutions)', parent_id: 'ma12_aoi', type: 'topic' },
    { id: 'tag_aoi_3', name: 'Variable Separable Method', parent_id: 'ma12_aoi', type: 'topic' },
    { id: 'tag_aoi_4', name: 'Linear Differential Equations (Integrating Factor)', parent_id: 'ma12_aoi', type: 'topic' },

    { id: 'ma12_vectors', name: 'Vector Algebra', parent_id: null, type: 'chapter', sequence_order: 218, class_level: 12, chapterType: 'physical' },
    { id: 'tag_vec_1', name: 'Vector Basics (Magnitude, Direction, Unit Vectors)', parent_id: 'ma12_vectors', type: 'topic' },
    { id: 'tag_vec_2', name: 'Dot Product & Scalar Projection', parent_id: 'ma12_vectors', type: 'topic' },
    { id: 'tag_vec_3', name: 'Cross Product & Area Applications', parent_id: 'ma12_vectors', type: 'topic' },
    { id: 'tag_vec_4', name: 'Scalar Triple Product & Volume', parent_id: 'ma12_vectors', type: 'topic' },

    { id: 'ma12_3d', name: '3D Geometry', parent_id: null, type: 'chapter', sequence_order: 219, class_level: 12, chapterType: 'physical' },
    { id: 'tag_3dg_1', name: 'Direction Cosines & Direction Ratios', parent_id: 'ma12_3d', type: 'topic' },
    { id: 'tag_3dg_2', name: 'Equation of Line in 3D (Cartesian & Vector)', parent_id: 'ma12_3d', type: 'topic' },
    { id: 'tag_3dg_3', name: 'Equation of Plane (Various Forms)', parent_id: 'ma12_3d', type: 'topic' },
    { id: 'tag_3dg_4', name: 'Angle & Distance (Line-Plane, Skew Lines)', parent_id: 'ma12_3d', type: 'topic' },
    { id: 'tag_3dg_5', name: 'Family of Planes & Sphere', parent_id: 'ma12_3d', type: 'topic' },

    { id: 'ma12_probability', name: 'Probability (Class 12)', parent_id: null, type: 'chapter', sequence_order: 220, class_level: 12, chapterType: 'physical' },
    { id: 'tag_prob2_1', name: 'Conditional Probability & Bayes\' Theorem', parent_id: 'ma12_probability', type: 'topic' },
    { id: 'tag_prob2_2', name: 'Probability Distributions (Binomial, Poisson)', parent_id: 'ma12_probability', type: 'topic' },
    { id: 'tag_prob2_3', name: 'Random Variables & Expected Value', parent_id: 'ma12_probability', type: 'topic' },
    { id: 'tag_prob2_4', name: 'Total Probability Theorem', parent_id: 'ma12_probability', type: 'topic' },
];

// Summary Statistics
// Total Chapters: 65 (26 Chemistry + 19 Physics + 20 Maths)
// Total Tags: ~430
// Last saved: 2026-03-05T04:30:00.000Z
// Chemistry chapters: ch11_*, ch12_*
// Physics chapters:   ph11_*, ph12_*
// Maths chapters:     ma11_*, ma12_*
