'use strict';
/**
 * Rewrites the STYLE of 19 pending (not-yet-generated) image generation_prompts
 * in Class 11 Chemistry (Ch.4 bonding-topic images + Ch.13 opener hero) to the
 * approved hand-drawn Live Book style (see memory: livebook_image_style,
 * canonical reference scripts/livebook-images/_ch7_newstyle.json).
 *
 * Only touches `generation_prompt` text on blocks with empty `src` — no images,
 * no other content, no already-generated blocks are touched. Pure prevention,
 * matching the pattern used for the Bio Ch.5-19 preventive sweep.
 *
 * Dry-run by default; pass --apply to write via book-writer.savePage.
 */
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env.local') });
const { MongoClient } = require('mongodb');
const bw = require('../lib/book-writer');

const APPLY = process.argv.includes('--apply');
const BOOK_ID = 'be7b5b7f-e993-4d3b-b9c8-52f7c308ab0e';

// blockId -> new generation_prompt (hand-drawn style, content preserved verbatim)
const REWRITES = {
  'd9fca770-49fd-4332-bb6b-e575c0248bb9':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent for arrows; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Side-by-side molecular dipole comparison: left panel a linear carbon dioxide molecule O=C=O drawn horizontally, two equal bond-dipole arrows on the C=O bonds pointing outward in exactly opposite directions along the axis, with a label showing they cancel to a net dipole of zero; right panel a bent water molecule H-O-H at about 104.5 degrees, two O-H bond-dipole arrows pointing toward the oxygen, plus a bold resultant arrow showing the net molecular dipole pointing downward through the oxygen, labelled 1.85 D. Show the vector-addition idea clearly with the small bond arrows and one big resultant arrow. All labels neat and fully legible hand-lettered: CO2 (net dipole = 0), H2O (net dipole 1.85 D), bond dipole, resultant. Calm and uncluttered.",
  '210ab098-67b1-47c4-989f-c1a1b2cb5531':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent for arrows; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Comparison of two pyramidal molecules: left, ammonia NH3 drawn as a pyramid with nitrogen at the apex and three hydrogens at the base, three N-H bond-dipole arrows point up toward the nitrogen, and a lone-pair dipole arrow also points up out of the top of the nitrogen — show them all reinforcing into a large net dipole arrow pointing up, labelled 1.47 D; right, nitrogen trifluoride NF3 drawn as the same pyramid with nitrogen at apex and three fluorines at the base, three N-F bond-dipole arrows point down toward the fluorines, while the lone-pair dipole still points up out of the top — show them opposing, leaving only a tiny net dipole arrow, labelled 0.23 D. Make the direction of every arrow unmistakable. All labels neat and fully legible hand-lettered: NH3 (dipoles add, 1.47 D), NF3 (dipoles oppose, 0.23 D), lone pair, bond dipole, net dipole. Calm and uncluttered.",
  '2f29745a-0192-4e84-8bc2-dbe7b678b02d':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. Two atoms on either side, each shown as a nucleus with a single dumbbell-shaped p-orbital lobe reaching toward the centre. In the middle, the two lobes meet head-on and merge into one shared region of soft colour sitting directly on the line joining the two nuclei — visually conveying that a bond is where two orbitals overlap. A faint second pair of parallel lobes hints at sideways overlap above and below. No text.",
  '48c80b13-0464-4f77-804b-f611f55366a7':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Two-panel comparison of sigma and pi bonds: left panel labelled 'sigma bond (head-on)' — two p-orbital dumbbell lobes pointing toward each other along a horizontal axis, overlapping end-to-end in one dense region sitting directly on the line joining the two nuclei, the two nuclei shown as dots on that axis, the cloud cylindrically symmetric about the axis; right panel labelled 'pi bond (sideways)' — two p-orbital dumbbells oriented vertically and parallel to each other on two adjacent atoms, overlapping side-on to form two separate cloud regions, one above and one below the horizontal bond axis, with a clearly marked nodal plane (zero density) along the axis between the nuclei. All labels neat and fully legible hand-lettered: axis, nuclei, overlap regions, nodal plane. Calm and uncluttered.",
  'd5a9e758-d207-4a7c-8ec7-1ce5ff100ea1':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. A central boron atom joined to a fluorine atom by a normal single bond drawn as a solid line. Above and beside it, a faint second connection forms as a lone pair of electrons on the fluorine drifts sideways into a soft, translucent empty orbital lobe on the boron — a delicate 'extra' partial bond layered over the real one, hinting at something hidden becoming visible. No text.",
  '4bbe1383-ef73-4137-9504-3565517c291a':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent for arrows; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Back bonding concept: a central boron atom bonded to three fluorine atoms in a flat trigonal-planar BF3 arrangement, the three B-F single bonds drawn as solid lines at 120 degrees. On boron, show one clearly labelled empty 2p-orbital as a translucent, unfilled dumbbell-shaped lobe standing perpendicular to the molecular plane. From one fluorine, show a filled lone-pair p-orbital tipping its electron density side-on (pi-type, sideways overlap) into that empty boron orbital, drawn as a soft partial second bond overlapping the existing B-F line. An arrow indicates electron donation from fluorine toward boron. All labels neat and fully legible hand-lettered: B, F, empty 2p orbital, fluorine lone pair, pi back bond, partial double-bond character. Calm and uncluttered.",
  'a059b000-2d73-48a7-bc19-39b4d4617625':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. Two separate atoms on the left and right, each with a faint spherical atomic-orbital cloud, merging in the centre into one continuous soft-coloured electron cloud that stretches over both nuclei — the visual idea that the electron now belongs to the whole molecule, not one atom. A gentle build-up of colour density sits in the region directly between the two nuclei. No text.",
  '9a7e4801-0111-4027-9cc9-322c3f4710a9':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Side-by-side comparison: centre-left, two identical spherical s atomic orbitals on two nuclei undergoing constructive (in-phase) overlap, merging into a single sigma bonding molecular orbital with a soft concentration of colour density in the region between the two nuclei, both nuclei shown as small dots inside the shared cloud; centre-right, the same two s orbitals undergoing destructive (out-of-phase) overlap, forming a sigma-star antibonding molecular orbital with a clear node (a flat plane of zero electron density, drawn as a dashed line) exactly between the two nuclei and the colour density pushed outside, beyond each nucleus. All labels neat and fully legible hand-lettered: 'bonding MO (lower energy)' on the left, 'antibonding MO* (node, higher energy)' on the right. Calm and uncluttered.",
  '8c15cde1-50b6-455a-b51c-3cb32cce0975':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. A vertical molecular-orbital energy-level ladder on the left, small hand-drawn electrons (some paired arrows up-down, two of them single and unpaired) filling the rungs from the bottom up. On the right, an O2 diatomic molecule with two highlighted unpaired electrons drawn near the pole of a simple horseshoe magnet — suggesting magnetism, the idea of counting electrons to predict a real property. No text.",
  'facdca5d-d396-4bc0-b34a-afd494e4e782':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Molecular orbital energy-level diagram for the oxygen molecule O2: a centre column of molecular orbitals between the two oxygen atomic-orbital columns (left and right). From bottom to top label the MOs: sigma2s (filled, paired arrows), sigma-star2s (filled), then sigma2p (filled, since O2 uses the post-N2 order with sigma below pi), then a degenerate pair pi2p (both filled, paired), then a degenerate pair pi-star2p containing two electrons shown as two single up-arrows, one in each of the two pi-star orbitals (the unpaired electrons, highlight these gently), then an empty sigma-star2p at the very top. Annotate '2 unpaired electrons -> paramagnetic' and 'Bond order = 2'. Use up/down arrows for paired electrons, single up-arrows for unpaired. All labels neat and fully legible hand-lettered. Calm and uncluttered.",
  '703d1427-0d8f-48a8-aeec-185e29dd2f83':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. A regular three-dimensional lattice of identical positive metal ions (small ochre spheres marked with a + sign) arranged in neat rows, immersed in a soft flowing teal sea of tiny electrons drifting freely through every gap between the ions — conveying fixed positive cores held together by a shared, mobile sea of negative charge. No text.",
  '918df858-d1c6-438a-ab18-e98292629e5c':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Electron-sea model of a metallic bond, cross-sectional diagram: a regular square grid of identical positive metal ions, each drawn as a sphere labelled with a + sign, sitting in fixed lattice positions. Filling all the space between and around the ions, many small free electrons (labelled e-) drawn with light motion trails to show they drift freely throughout the metal. A small arrow points to the attraction between a + ion and the surrounding electrons, labelled 'metallic bond = ion <-> electron-sea attraction'. All labels neat and fully legible hand-lettered: Positive metal ions (cations), Sea of delocalised electrons (e-), Metallic bond. Calm and uncluttered.",
  'becd4692-c177-465d-9f1a-236b4e225568':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Band theory comparison: three vertical energy-band charts side by side, labelled Conductor (metal), Semiconductor, and Insulator. In each chart show a lower filled band labelled 'Valence band' and an upper band labelled 'Conduction band', with energy increasing upward. For the Conductor: the valence and conduction bands overlap with no gap. For the Semiconductor: a small empty space between them labelled 'small band gap', with a couple of electrons drawn jumping the gap. For the Insulator: a tall empty space between them labelled 'large band gap' that electrons cannot cross. A vertical arrow on the left labelled 'Energy'. All labels neat and fully legible hand-lettered: Valence band, Conduction band, Band gap, Energy. Calm and uncluttered.",
  '46cfb188-fcb3-4284-9356-eabdde778f0a':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. A serene scene of liquid water: a steel sewing needle resting on top of the water surface without sinking on the left, and a clear ice cube floating in the same water on the right. Around and beneath the surface, a faint network of water molecules connected by dotted lines (hydrogen bonds) forming an open lattice. The visual idea is 'water breaks the rules' — surface tension holding the needle, ice floating. No text.",
  '21c73f6b-9b80-4229-84f7-fa0405c0e05d':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Chemical structure of solid/liquid hydrogen fluoride (HF) drawn as a long zigzag chain. Fluorine atoms (F) sit at the corners/points of the zigzag and hydrogen atoms (H) sit at the bends between them. Each F is connected to one H by a solid covalent line and to the next H by a dotted hydrogen-bond line. Mark the bend angle as approximately 120 degrees. Label one covalent H-F bond as 'covalent' and one dotted line as 'hydrogen bond'. Show at least four F atoms so the repeating zigzag is obvious. All labels neat and fully legible hand-lettered. Calm and uncluttered.",
  '88242ff5-f7d3-491b-a9be-04940754cc1f':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Chemical structure of ortho-nitrophenol: a benzene ring with an -OH group on one carbon and an -NO2 (nitro) group on the carbon right next to it (ortho position). A dotted hydrogen-bond line runs from the hydrogen of the -OH to an oxygen of the -NO2, folding them together into a small six-membered ring, all within the single molecule. Label 'intramolecular hydrogen bond' pointing at the dotted line. Beside it, a small inset shows two separate HF molecules joined by a dotted line labelled 'intermolecular' for contrast. All labels neat and fully legible hand-lettered. Calm and uncluttered.",
  '70b44442-5a5b-41fb-9ef4-d8b36c0b39b7':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide banner, 16:5. Several complete, separate molecules (already fully bonded — shown as small clusters of joined spheres) drifting close to one another in space, with very faint, thin threads of attraction stretching between them — not the thick strong bonds inside each molecule, but delicate whisper-thin links between molecules, like skydivers in free-fall briefly reaching toward each other before drifting apart. No text.",
  '91c773d8-8002-4992-8d0b-45392f60d7f3':
    "Hand-drawn coloured educational diagram — clean, elegant. Visible ink line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background; warm muted colours with a soft teal accent; no neon, no glow, no bright flashy colours, no 3D-render look. 4:3. Three panels side by side. Panel 1 'Ion-dipole': a positive ion (labelled Na+) with several polar water molecules around it, each turning its negative (oxygen) end toward the ion, with partial-charge labels delta-plus / delta-minus. Panel 2 'Dipole-dipole': two polar HCl molecules lined up head-to-tail, positive end of one near negative end of the other, with delta-plus and delta-minus labels and a faint attraction line between them. Panel 3 'London dispersion': two neutral atoms; the left atom shown with its electron cloud momentarily bunched to one side (an instantaneous dipole, delta-minus on the bunched side), inducing a matching dipole in the right atom; a small 'instant' / 'next moment' arrow hinting the dipole is fleeting. Keep the inter-molecular attraction lines visibly thin/faint compared to any internal bonds. All labels neat and fully legible hand-lettered. Calm and uncluttered.",
  '19e35122-5394-469c-8e68-5dbe5cb72d68':
    "Hand-drawn coloured illustration — clean, elegant, editorial. Visible ink and pencil line work with soft hand-painted colour fills (coloured-pencil / gouache feel). Deep charcoal near-black background so it sits on a dark page, but the artwork itself is warm and colourful in a muted earthy palette (ochre, terracotta, teal, sage green, indigo, cream); no neon, no glow, no light beams, no orange haze, no 3D-render look. Calm and uncluttered. Ultra-wide cover banner, 21:9. A cover image for the chapter 'Ch. 13 | Practical Organic Chemistry': lab glassware — a distillation flask, a chromatography jar, a crystallising dish — arranged with a sense of quiet transformation. No text overlay.",
};

async function main() {
  const client = new MongoClient(process.env.MONGODB_URI);
  await client.connect();
  try {
    const db = client.db('crucible');
    const pages = db.collection('book_pages');
    const allPages = await pages.find({ book_id: BOOK_ID }).toArray();

    // group target blockIds by page
    const byPage = new Map();
    for (const p of allPages) {
      for (const b of (p.blocks || [])) {
        if (REWRITES[b.id]) {
          if (!byPage.has(p._id)) byPage.set(p._id, { page: p, ids: [] });
          byPage.get(p._id).ids.push(b.id);
        }
      }
    }

    console.log(`Found ${[...byPage.values()].reduce((s, v) => s + v.ids.length, 0)} target blocks across ${byPage.size} pages.\n`);

    for (const { page, ids } of byPage.values()) {
      const newBlocks = (page.blocks || []).map((b) => {
        if (REWRITES[b.id]) {
          if (b.src) throw new Error(`SAFETY: block ${b.id} on ${page.slug} already has src — refusing to restyle a generated image`);
          return { ...b, generation_prompt: REWRITES[b.id] };
        }
        return b;
      });
      console.log(`${page.slug} (ch${page.chapter_number} p${page.page_number}): restyling ${ids.length} block(s) — ${ids.map((i) => i.slice(0, 8)).join(', ')}`);
      if (APPLY) {
        await bw.savePage(db, { pageId: page._id }, newBlocks, {
          author: 'agent', summary: 'Restyle pending image prompts to the approved hand-drawn Live Book style (no images generated yet, prompt-text only)',
        });
      }
    }

    console.log(APPLY ? '\n✅ APPLIED via book-writer.savePage (versioned).' : '\nDRY RUN — nothing written. Re-run with --apply.');
  } finally {
    await client.close();
  }
}
main().catch((e) => { console.error(e); process.exit(1); });
