// CRITICAL: This taxonomy data is the single source of truth for the practice session.
// DO NOT MODIFY DIRECTLY — use the Taxonomy Dashboard at /crucible/admin/taxonomy
// Changes made in the dashboard are auto-saved here via POST /api/v2/taxonomy/save

export interface TaxonomyNode {
    id: string;
    name: string;
    parent_id: string | null;
    type: 'chapter' | 'topic';
    sequence_order?: number;
    class_level?: 11 | 12;
    chapterType?: 'physical' | 'inorganic' | 'organic' | 'practical';
}

export const TAXONOMY_FROM_CSV: TaxonomyNode[] = [
    // Class 11
    { id: 'ch11_mole', name: 'Some Basic Concepts of Chemistry (Mole Concept)', parent_id: null, type: 'chapter', sequence_order: 1, class_level: 11, chapterType: 'physical' },
    { id: 'tag_mole_1', name: 'Laws Of Chemical Combination, Sig. Fig, Accuracy', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_2', name: 'Concentration Terms (M, m, X)', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_3', name: 'Empirical/Molecular Formula', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_4', name: 'Equivalent Concept & n-factor', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_5', name: 'Eudiometry (Gas Analysis)', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_6', name: 'Limiting Reagent', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_7', name: 'Mole Basics (Mass/Vol/Part)', parent_id: 'ch11_mole', type: 'topic' },
    { id: 'tag_mole_8', name: 'Stoichiometry & Analysis', parent_id: 'ch11_mole', type: 'topic' },

    { id: 'ch11_atom', name: 'Structure of Atom', parent_id: null, type: 'chapter', sequence_order: 2, class_level: 11, chapterType: 'physical' },
    { id: 'tag_atom_1', name: 'Sub-atomic Particles & Discovery', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_2', name: 'Atomic Models (Thomson, Rutherford)', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_3', name: 'Quantum Mechanical Model of the Atom', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_4', name: 'EM Radiation & Planck\'s Quantum Theory', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_5', name: 'Photoelectric Effect & BBR', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_6', name: 'Bohr\'s Model & Hydrogen Spectrum', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_7', name: 'Quantum Numbers & Electronic Configuration', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_8', name: 'De-Broglie Theory & Uncertainty Principle', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_9', name: 'Wave function & Probability Graphs', parent_id: 'ch11_atom', type: 'topic' },
    { id: 'tag_atom_10', name: 'Multi Concept', parent_id: 'ch11_atom', type: 'topic' },

    { id: 'ch11_periodic', name: 'Classification of Elements and Periodicity', parent_id: null, type: 'chapter', sequence_order: 3, class_level: 11, chapterType: 'physical' },
    { id: 'tag_periodic_1', name: 'Modern Periodic Law & IUPAC Nomenclature (Z > 100)', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_2', name: 'Atomic & lonic Radii Trends', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_3', name: 'Periodic Trends (I.E., E.A. E.N.)', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_4', name: 'Other Periodic Trends', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_5', name: 'Nature of Oxides', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_6', name: 'Valency & Diagonal Relationship', parent_id: 'ch11_periodic', type: 'topic' },
    { id: 'tag_periodic_7', name: 'Multi-Concept', parent_id: 'ch11_periodic', type: 'topic' },

    { id: 'ch11_bonding', name: 'Chemical Bonding', parent_id: null, type: 'chapter', sequence_order: 4, class_level: 11, chapterType: 'physical' },
    { id: 'tag_bonding_1', name: 'lonic Bonding & Lattice Energy', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_2', name: 'Basics, Octet Rule, Formal Charge', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_3', name: 'Dipole Moment & Polarity', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_4', name: 'Fajan\'s Rule & Covalent Character', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_5', name: 'Hydrogen Bonding & Intermolecular Forces', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_6', name: 'VSEPR & Geometry', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_7', name: 'Misc. Concepts', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_8', name: 'Molecular Orbital Theory (MOT)', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_9', name: 'Molecular Properties (bond length, strength, angle) & Resonance', parent_id: 'ch11_bonding', type: 'topic' },
    { id: 'tag_bonding_10', name: 'VBT and Hybridization', parent_id: 'ch11_bonding', type: 'topic' },

    { id: 'ch11_thermo', name: 'Thermodynamics', parent_id: null, type: 'chapter', sequence_order: 5, class_level: 11, chapterType: 'physical' },
    { id: 'tag_thermo_1', name: 'Basic Terms and Definitions', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_2', name: 'Calorimetry & Heat Capacity', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_3', name: 'Thermochemistry & Hess\'s Law', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_4', name: 'Internal Energy & Enthalpy change', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_5', name: 'Entropy & Second Law', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_6', name: 'Gibbs Free Energy & Spontaneity', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_7', name: 'First Law and Internal Energy', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_8', name: 'Work & Heat', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_9', name: 'Graphical Question', parent_id: 'ch11_thermo', type: 'topic' },
    { id: 'tag_thermo_10', name: 'Multi Concept', parent_id: 'ch11_thermo', type: 'topic' },

    { id: 'ch11_chem_eq', name: 'Chemical Equilibrium', parent_id: null, type: 'chapter', sequence_order: 6, class_level: 11, chapterType: 'physical' },
    { id: 'tag_chem_eq_1', name: 'Law of Mass Action & Equilibrium Constants (K p, Kc)', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_2', name: 'Le Chatelier\'s Principle', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_3', name: 'Calculation of Kp, Kc, Kx', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_4', name: 'Physical & Chemical Equilibrium', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_5', name: 'Vapour Density & Degree of dissociation', parent_id: 'ch11_chem_eq', type: 'topic' },
    { id: 'tag_chem_eq_6', name: 'Reaction Quotient & applications', parent_id: 'ch11_chem_eq', type: 'topic' },

    { id: 'ch11_ionic_eq', name: 'Ionic Equilibrium', parent_id: null, type: 'chapter', sequence_order: 7, class_level: 11, chapterType: 'physical' },
    { id: 'tag_ionic_eq_1', name: 'Buffer Solutions', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_2', name: 'Salt Hydrolysis', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_3', name: 'Solubility Product (Ksp)', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_4', name: 'pH Calculation (Acids/Bases)', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_5', name: 'Hydrolysis and pH calculation', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_6', name: 'lonic Product of water and pH scale', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_7', name: 'Theories of Acid/base & Ostwald Law', parent_id: 'ch11_ionic_eq', type: 'topic' },
    { id: 'tag_ionic_eq_8', name: 'Titrations and Indicators', parent_id: 'ch11_ionic_eq', type: 'topic' },

    { id: 'ch11_redox', name: 'Redox Reactions', parent_id: null, type: 'chapter', sequence_order: 8, class_level: 11, chapterType: 'inorganic' },
    { id: 'tag_redox_1', name: 'Balancing of Redox Reactions', parent_id: 'ch11_redox', type: 'topic' },
    { id: 'tag_redox_2', name: 'Oxidation, Reduction and Oxidation Number', parent_id: 'ch11_redox', type: 'topic' },
    { id: 'tag_redox_3', name: 'Redox Titrations', parent_id: 'ch11_redox', type: 'topic' },
    { id: 'tag_redox_4', name: 'Types of Redox Reactions', parent_id: 'ch11_redox', type: 'topic' },

    { id: 'ch11_pblock', name: 'P Block (Class 11)', parent_id: null, type: 'chapter', sequence_order: 9, class_level: 11, chapterType: 'inorganic' },
    { id: 'tag_pblock11_1', name: 'Property Trends', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_2', name: 'Allotropes & Compounds of Carbon', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_3', name: 'Compounds of Boron (B2H6, Borax, Boric acid)', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_4', name: 'Properties & Reactions of Boron family', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_5', name: 'Properties & Reactions of Carbon Family', parent_id: 'ch11_pblock', type: 'topic' },
    { id: 'tag_pblock11_6', name: 'Silicates, Silicones and Zeolites', parent_id: 'ch11_pblock', type: 'topic' },

    { id: 'ch11_goc', name: 'GOC', parent_id: null, type: 'chapter', sequence_order: 10, class_level: 11, chapterType: 'organic' },
    { id: 'tag_goc_1', name: 'Classification & IUPAC Naming', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_2', name: 'Acidity & Basicity', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_3', name: 'Electronic Effects (Inductive, Resonance, Hyperconjugation)', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_4', name: 'Huckel\'s Rule & Aromaticity', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_5', name: 'Misc. Concepts', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_6', name: 'Reaction Intermediates', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_7', name: 'Structural Isomerism & Tautomerism', parent_id: 'ch11_goc', type: 'topic' },
    { id: 'tag_goc_8', name: 'Electrophiles, Nucleophiles & Basic Terms', parent_id: 'ch11_goc', type: 'topic' },

    { id: 'ch11_stereo', name: 'Stereochemistry', parent_id: null, type: 'chapter', sequence_order: 11, class_level: 11, chapterType: 'organic' },
    { id: 'tag_stereo_1', name: 'Stereoisomerism (Geometrical & Optical)', parent_id: 'ch11_stereo', type: 'topic' },
    { id: 'tag_stereo_2', name: 'Allenes, Atropisomers and Spiro Compounds', parent_id: 'ch11_stereo', type: 'topic' },
    { id: 'tag_stereo_3', name: 'Chirality and Optical activity', parent_id: 'ch11_stereo', type: 'topic' },
    { id: 'tag_stereo_4', name: 'Conformational Isomerism', parent_id: 'ch11_stereo', type: 'topic' },
    { id: 'tag_stereo_5', name: 'Conformations of Cycloalkanes', parent_id: 'ch11_stereo', type: 'topic' },
    { id: 'tag_stereo_6', name: 'Enantiomers, Diastereomers & Meso Compounds', parent_id: 'ch11_stereo', type: 'topic' },
    { id: 'tag_stereo_7', name: 'Geometrical Isomerism', parent_id: 'ch11_stereo', type: 'topic' },

    { id: 'ch11_hydrocarbon', name: 'Hydrocarbons', parent_id: null, type: 'chapter', sequence_order: 12, class_level: 11, chapterType: 'organic' },
    { id: 'tag_hydrocarbon_1', name: 'Alkynes (Acidity & Rxns)', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_2', name: 'Electrophilic addition across C=C', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_3', name: 'Misc. Reactions of Hydrocarbons', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_4', name: 'Oxidation Reactions of Alkenes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_5', name: 'Preparation & properties of benzene', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_6', name: 'Preparation Reactions of Alkanes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_7', name: 'Preparation and Properties of Alkenes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_8', name: 'Reactions of Alkanes', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_9', name: 'Reactions of Benzene & Derivatives', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_hydrocarbon_10', name: 'Multi-Concept', parent_id: 'ch11_hydrocarbon', type: 'topic' },
    { id: 'tag_ch11_hydrocarbon_1771659235901', name: 'Electrophilic Aromatic Substitution (SEAr)', parent_id: 'ch11_hydrocarbon', type: 'topic' },

    { id: 'ch11_prac_org', name: 'Practical Organic Chemistry', parent_id: null, type: 'chapter', sequence_order: 13, class_level: 11, chapterType: 'practical' },
    { id: 'tag_prac_org_1', name: 'Purification Methods (Distillation, Chromatography, Sublimation)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_2', name: 'Detection of Elements (Lassaigne\'s Test: N, S, Halogens)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_3', name: 'Quantitative Analysis (Dumas, Kjeldahl, Carius Methods)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_4', name: 'Tests for Unsaturation (Bromine Water, Bayer\'s Reagent)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_5', name: 'Tests for Hydroxyl Group (Ceric Ammonium Nitrate, Lucas Test)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_6', name: 'Tests for Carbonyls & Carboxyls (2, 4-DNP, Sodium Bicarbonate, Esterification)', parent_id: 'ch11_prac_org', type: 'topic' },
    { id: 'tag_prac_org_7', name: 'Tests for Amines (Hinsberg Test, Azo Dye Test, Carbylamine)', parent_id: 'ch11_prac_org', type: 'topic' },

    // Class 12
    { id: 'ch12_solutions', name: 'Solutions', parent_id: null, type: 'chapter', sequence_order: 15, class_level: 12, chapterType: 'physical' },
    { id: 'tag_solutions_1', name: 'Vapour Pressure & RLVP', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_2', name: 'Basics & Definitions', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_3', name: 'Raoult\'s Law (Ideal & Non ideal soln)', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_4', name: 'Concentration Terms', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_5', name: 'Elevation in BP / Depression in FP', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_6', name: 'Osmotic Pressure & Van\'t Hoff Factor', parent_id: 'ch12_solutions', type: 'topic' },
    { id: 'tag_solutions_7', name: 'Solubility & Henry\'s Law', parent_id: 'ch12_solutions', type: 'topic' },

    { id: 'ch12_electrochem', name: 'Electrochemistry', parent_id: null, type: 'chapter', sequence_order: 16, class_level: 12, chapterType: 'physical' },
    { id: 'tag_electrochem_1', name: 'Batteries, Fuel Cells & Corrosion', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_2', name: 'Conductance & Kohlrausch Law', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_3', name: 'Electrochemical Series & its Applications', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_4', name: 'Electrode Potential and Galvanic Cell', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_5', name: 'Electrolysis & Faraday\'s Laws', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_6', name: 'Nernst Equation & Latimer Diagram', parent_id: 'ch12_electrochem', type: 'topic' },
    { id: 'tag_electrochem_7', name: 'Multi-Concept', parent_id: 'ch12_electrochem', type: 'topic' },

    { id: 'ch12_kinetics', name: 'Chemical Kinetics', parent_id: null, type: 'chapter', sequence_order: 17, class_level: 12, chapterType: 'physical' },
    { id: 'tag_kinetics_1', name: 'Arrhenius Eq & Activation Energy', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_2', name: 'Complex Reactions', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_3', name: 'Radioactive Decay', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_4', name: 'Rate Law, Order of Reaction, Molecularity', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_5', name: 'Rate of Reactions and Factors affecting it', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_6', name: 'Reaction Mechanisms & Catalysis', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_7', name: 'Zero Order Reactions', parent_id: 'ch12_kinetics', type: 'topic' },
    { id: 'tag_kinetics_8', name: 'First Order Reactions & Special cases', parent_id: 'ch12_kinetics', type: 'topic' },

    { id: 'ch12_pblock', name: 'P Block (12th)', parent_id: null, type: 'chapter', sequence_order: 18, class_level: 12, chapterType: 'inorganic' },
    { id: 'tag_pblock12_1', name: 'Properties of P-Block', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_2', name: 'Compounds of Halides', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_3', name: 'Compounds of Nitrogen', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_4', name: 'Compounds of Phosphorus', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_5', name: 'Compounds of Sulphur', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_6', name: 'Noble gases and their Reactions', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_7', name: 'Properties of Halogens', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_8', name: 'Properties of Nitrogen Family', parent_id: 'ch12_pblock', type: 'topic' },
    { id: 'tag_pblock12_9', name: 'Properties of Oxygen Family', parent_id: 'ch12_pblock', type: 'topic' },

    { id: 'ch12_dblock', name: 'D & F Block', parent_id: null, type: 'chapter', sequence_order: 19, class_level: 12, chapterType: 'inorganic' },
    { id: 'tag_dblock_1', name: 'Reactions of Transition Metals', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_2', name: 'Electronic Config. and Exceptions', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_3', name: 'I.E. ,Oxidation states, SRP', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_4', name: 'Preparation & Properties of KMnO4 & K2Cr2O7', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_5', name: 'Magnetic properties & Colour', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_6', name: 'Oxides, Catalytic Properties', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_7', name: 'Physical Properties of Transition metals', parent_id: 'ch12_dblock', type: 'topic' },
    { id: 'tag_dblock_8', name: 'Properties of F block elements', parent_id: 'ch12_dblock', type: 'topic' },

    { id: 'ch12_coord', name: 'Coordination Compounds', parent_id: null, type: 'chapter', sequence_order: 20, class_level: 12, chapterType: 'inorganic' },
    { id: 'tag_coord_1', name: 'Basic Definitions & Ligands', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_2', name: 'Color & Magnetic Properties', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_3', name: 'Crystal Field Theory (CFT)', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_4', name: 'IUPAC Nomenclature', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_5', name: 'Isomerism (Structural/Stereo)', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_6', name: 'Metal Carbonyls & EAN', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_7', name: 'Stability & Applications', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_8', name: 'Valence Bond Theory (VBT)', parent_id: 'ch12_coord', type: 'topic' },
    { id: 'tag_coord_9', name: 'Werner\'s Theory', parent_id: 'ch12_coord', type: 'topic' },

    { id: 'ch12_haloalkanes', name: 'Haloalkanes & Haloarenes', parent_id: null, type: 'chapter', sequence_order: 21, class_level: 12, chapterType: 'organic' },
    { id: 'tag_haloalkanes_1', name: 'Aryl Halides & Their Reactions', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_2', name: 'Elimination Reactions', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_4', name: 'Nucleophilicity, Basicity & Leaving Group', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_5', name: 'Physical properties of Haloalkanes', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_6', name: 'SN Reactions (SN1, SN2, SNi) & NGP', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_7', name: 'Preparation (From Alcohols, Hydrocarbons)', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_8', name: 'Elimination Reactions vs Substitution', parent_id: 'ch12_haloalkanes', type: 'topic' },
    { id: 'tag_haloalkanes_9', name: 'Multi-Concept', parent_id: 'ch12_haloalkanes', type: 'topic' },

    { id: 'ch12_alcohols', name: 'Alcohols, Phenols & Ethers', parent_id: null, type: 'chapter', sequence_order: 22, class_level: 12, chapterType: 'organic' },
    { id: 'tag_alcohols_1', name: 'Alcohols Preparation (Grignard, Reduction)', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_2', name: 'Dehydration & Oxidation of Alcohols', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_3', name: 'Phenols Preparation & Acidic Nature', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_4', name: 'Phenol Reactions (Reimer-Tiemann, Kolbe etc)', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_5', name: 'Reactions of ethers, epoxides', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_alcohols_6', name: 'Other Reactions of Alcohols', parent_id: 'ch12_alcohols', type: 'topic' },
    { id: 'tag_ch12_alcohols_1771659358099', name: 'SEAr Reactions of Phenols & Ethers', parent_id: 'ch12_alcohols', type: 'topic' },

    { id: 'ch12_aldehydes', name: 'Aldehydes & Ketones', parent_id: null, type: 'chapter', sequence_order: 23, class_level: 12, chapterType: 'organic' },
    { id: 'tag_aldehydes_1', name: 'Grignard Reagent', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_aldehydes_2', name: 'Name Reactions (Aldol, Cannizzaro, Perkins, Haloform, Claisen etc)', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_aldehydes_3', name: 'Other name reactions of carbonyl', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_aldehydes_4', name: 'Preparation raections of carbonyl', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_aldehydes_5', name: 'Tests for carbonyl compounds (Tollen\'s, Fehling, Benedict etc)', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_aldehydes_6', name: 'Nucleophilic Addition Reactions', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_aldehydes_7', name: 'Oxidation & Reduction Reactions of Carbony!', parent_id: 'ch12_aldehydes', type: 'topic' },
    { id: 'tag_ch12_aldehydes_1771659373017', name: 'Reactions of Aromatic Aldehydes & Ketones', parent_id: 'ch12_aldehydes', type: 'topic' },

    { id: 'ch12_amines', name: 'Amines', parent_id: null, type: 'chapter', sequence_order: 24, class_level: 12, chapterType: 'organic' },
    { id: 'tag_amines_1', name: 'Reactions of Aliphatic Amines', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_2', name: 'Tests for Amines (Hinsberg, Carbylamine, Hoffmann)', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_3', name: 'Basic Character (Gaseous vs Aqueous Phase)', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_4', name: 'Diazonium Salts & Coupling Reactions', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_amines_5', name: 'Gabriel Phthalimide, Hofmann Bromamide & Carbylamine', parent_id: 'ch12_amines', type: 'topic' },
    { id: 'tag_ch12_amines_1771659399884', name: 'Reactions of Nitrobenzene & Aniline', parent_id: 'ch12_amines', type: 'topic' },

    { id: 'ch12_carboxylic', name: 'Carboxylic Acids & Derivatives', parent_id: null, type: 'chapter', sequence_order: 25, class_level: 12, chapterType: 'organic' },
    { id: 'tag_carboxylic_1', name: 'Acid Derivatives (Esters, Anhydrides, Amides)', parent_id: 'ch12_carboxylic', type: 'topic' },
    { id: 'tag_carboxylic_2', name: 'Acidity Trends & Substituent Effects', parent_id: 'ch12_carboxylic', type: 'topic' },
    { id: 'tag_carboxylic_3', name: 'Name Reactions (Dearboxylation, HVZ, Arndt Eistert etc.)', parent_id: 'ch12_carboxylic', type: 'topic' },
    { id: 'tag_carboxylic_4', name: 'Preparation Methods', parent_id: 'ch12_carboxylic', type: 'topic' },
    { id: 'tag_ch12_carboxylic_1771659384907', name: 'Reactions of Aromatic Acids & Derivatives', parent_id: 'ch12_carboxylic', type: 'topic' },

    { id: 'ch12_biomolecules', name: 'Biomolecules', parent_id: null, type: 'chapter', sequence_order: 26, class_level: 12, chapterType: 'organic' },
    { id: 'tag_biomolecules_1', name: 'Carbohydrates (Glucose Structure & Reactions)', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_2', name: 'Tests for Biomolecules', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_3', name: 'Di and Polysachharides', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_4', name: 'Nucleic Acids (DNA/RNA)', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_5', name: 'Proteins & Amino Acids', parent_id: 'ch12_biomolecules', type: 'topic' },
    { id: 'tag_biomolecules_6', name: 'Vitamins & Enzymes', parent_id: 'ch12_biomolecules', type: 'topic' },

    { id: 'ch12_salt', name: 'Salt Analysis', parent_id: null, type: 'chapter', sequence_order: 27, class_level: 12, chapterType: 'practical' },
    { id: 'tag_salt_1', name: 'Anion Analysis', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_2', name: 'Cation Analysis', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_3', name: 'Anions: Conc. H2SO4 Group', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_4', name: 'Anions: Dil. H2SO4 Group', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_5', name: 'Anions: Special Group (S04, PO4)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_6', name: 'Cations: Group I (Pb, Ag, Hg)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_7', name: 'Cations: Group II (Cu, As, etc)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_8', name: 'Cations: Group III (Fe, Al, Cr)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_9', name: 'Cations: Group IV (Zn, Mn, Ni, Co)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_10', name: 'Cations: Group V (Ba, Sr, Ca)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_11', name: 'Cations: Group VI (Mg)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_12', name: 'Cations: Zero Group (NH4+)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_13', name: 'Dry Tests (Flame/Borax)', parent_id: 'ch12_salt', type: 'topic' },
    { id: 'tag_salt_14', name: 'Solubility Rules & Precipitation Colors', parent_id: 'ch12_salt', type: 'topic' },

    { id: 'ch12_prac_phys', name: 'Practical Physical Chemistry', parent_id: null, type: 'chapter', sequence_order: 28, class_level: 12, chapterType: 'practical' },
    { id: 'tag_prac_phys_1', name: 'Laboratory Apparatus & Errors in Measurement', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_2', name: 'Acid-Base Titration & Selection of Indicators (Phenolphthalein/Methyl Orange)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_3', name: 'Redox Titrations (K MnO4 / Oxalic Acid / Mohr\'s Salt)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_4', name: 'lodometric vs lodimetric Titrations (Starch Indicator)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_5', name: 'Hardness of Water (EDTA Titration)', parent_id: 'ch12_prac_phys', type: 'topic' },
    { id: 'tag_prac_phys_6', name: 'Surface Chemistry Practicals (Lyophilic/Lyophobic Sols & Dialysis)', parent_id: 'ch12_prac_phys', type: 'topic' },

];

// Summary Statistics
// Total Chapters: 27
// Total Tags: 210
// Last saved: 2026-02-21T07:36:39.932Z
