'use strict';
/**
 * crucible-state.js
 *
 * Regenerates the DB-state inventory inside _agents/state/CRUCIBLE_STATE.md.
 *
 * Reads `questions_v2` (live, non-deleted) + the taxonomy source of truth
 * (packages/data/taxonomy/taxonomyData_from_csv.ts) and rewrites ONLY the region
 * between the <!-- AUTO:BEGIN --> / <!-- AUTO:END --> markers. The Changelog
 * below the AUTO region is preserved untouched. If the file does not exist, a
 * full scaffold (header + empty Changelog) is created.
 *
 * Per chapter it reports: live question count, published, PYQ, flagged
 * (unresolved), how many questions are missing a PRIMARY concept tag (a
 * taxonomy `topic`-level tag) and how many are missing MICRO tags (a
 * `micro_topic`-level tag), and how many micro_topics the taxonomy actually
 * defines for that chapter (⚠0 = micro tags not even generated yet).
 *
 * Run after ANY question/solution add or update, then add a dated Changelog line.
 *
 * Run: node scripts/crucible-state.js
 */
const dotenv = require('dotenv');
dotenv.config({ path: '.env.local' });
const fs = require('fs');
const path = require('path');
const { MongoClient } = require('mongodb');

const OUT = path.join(__dirname, '..', '_agents', 'state', 'CRUCIBLE_STATE.md');
const TAXONOMY_FILE = path.join(__dirname, '..', 'packages', 'data', 'taxonomy', 'taxonomyData_from_csv.ts');
const AUTO_BEGIN = '<!-- AUTO:BEGIN — generated by scripts/crucible-state.js; do not edit by hand -->';
const AUTO_END = '<!-- AUTO:END -->';
const SUBJECT_ORDER = ['chemistry', 'physics', 'maths', 'biology'];

function cell(s) { return String(s == null ? '' : s).replace(/\|/g, '\\|'); }

// ── Load the taxonomy array out of the .ts source (no ts runtime needed) ──
// The array contains only plain object literals (verified: no spreads, template
// literals, or `as const`), so we slice out the literal and evaluate it.
function loadTaxonomy() {
  const text = fs.readFileSync(TAXONOMY_FILE, 'utf8');
  const anchor = text.indexOf('TAXONOMY_FROM_CSV');
  if (anchor === -1) throw new Error('TAXONOMY_FROM_CSV not found in taxonomy file');
  // Start AFTER the `=` so we skip the `: TaxonomyNode[]` type annotation —
  // otherwise indexOf('[') would grab the empty brackets of the type and
  // evaluate to an empty array.
  const eq = text.indexOf('=', anchor);
  if (eq === -1) throw new Error('taxonomy assignment "=" not found');
  const start = text.indexOf('[', eq);
  if (start === -1) throw new Error('taxonomy array opening "[" not found');
  let depth = 0, end = -1;
  for (let i = start; i < text.length; i++) {
    const c = text[i];
    if (c === '[') depth++;
    else if (c === ']') { depth--; if (depth === 0) { end = i; break; } }
  }
  if (end === -1) throw new Error('taxonomy array closing "]" not found');
  const literal = text.slice(start, end + 1);
  // eslint-disable-next-line no-new-func
  const nodes = Function(`"use strict"; return (${literal});`)();
  if (!Array.isArray(nodes)) throw new Error('taxonomy did not evaluate to an array');
  return nodes;
}

function buildTaxonomyIndex(nodes) {
  const byId = new Map(nodes.map(n => [n.id, n]));
  const chapterOf = (id) => {
    let n = byId.get(id), guard = 0;
    while (n && n.type !== 'chapter' && guard++ < 10) n = byId.get(n.parent_id);
    return n && n.type === 'chapter' ? n : null;
  };
  const tagType = (id) => byId.get(id)?.type || null; // 'topic' | 'micro_topic' | null(unknown)
  const microByChapter = new Map(); // chapterId -> count of micro_topic nodes
  const topicByChapter = new Map();
  for (const n of nodes) {
    if (n.type === 'micro_topic' || n.type === 'topic') {
      const ch = chapterOf(n.id);
      if (!ch) continue;
      const map = n.type === 'micro_topic' ? microByChapter : topicByChapter;
      map.set(ch.id, (map.get(ch.id) || 0) + 1);
    }
  }
  return { byId, tagType, microByChapter, topicByChapter };
}

function buildAutoBlock(rowsBySubject, tax, today) {
  const microGaps = []; // chapters with questions but 0 taxonomy micro_topics
  let gQ = 0, gPub = 0, gPyq = 0, gFlag = 0, gNoPrim = 0, gNoMicro = 0;
  const subjectLines = [];

  for (const subject of [...SUBJECT_ORDER, '(unknown)', '(no chapter_id)']) {
    const rows = rowsBySubject.get(subject);
    if (!rows || rows.length === 0) continue;
    rows.sort((a, b) => (a.seq - b.seq) || a.chapterId.localeCompare(b.chapterId));

    let sQ = 0, sPub = 0, sPyq = 0, sFlag = 0, sNoPrim = 0, sNoMicro = 0;
    for (const r of rows) { sQ += r.total; sPub += r.pub; sPyq += r.pyq; sFlag += r.flag; sNoPrim += r.noPrim; sNoMicro += r.noMicro; }
    gQ += sQ; gPub += sPub; gPyq += sPyq; gFlag += sFlag; gNoPrim += sNoPrim; gNoMicro += sNoMicro;

    subjectLines.push(`### ${subject[0].toUpperCase() + subject.slice(1)}`);
    subjectLines.push(`Totals: ${rows.length} chapters · ${sQ} questions · ${sPub} published · ${sPyq} PYQ · ${sFlag} flagged · ${sNoPrim} missing primary tag · ${sNoMicro} missing micro tags`);
    subjectLines.push('');
    subjectLines.push('| Chapter | Q | Pub | PYQ | ⚑ | NoPrim | NoMicro | TaxMicro |');
    subjectLines.push('|---|---|---|---|---|---|---|---|');
    for (const r of rows) {
      const taxMicro = tax.microByChapter.get(r.chapterId) || 0;
      if (taxMicro === 0) microGaps.push({ subject, name: r.name, q: r.total });
      const label = r.inTaxonomy ? r.name : `${r.chapterId} _(not in taxonomy)_`;
      subjectLines.push(`| ${cell(label)} | ${r.total} | ${r.pub} | ${r.pyq} | ${r.flag || ''} | ${r.noPrim || ''} | ${r.noMicro || ''} | ${taxMicro === 0 ? '⚠0' : taxMicro} |`);
    }
    subjectLines.push('');
  }

  const lines = [];
  lines.push(`_Last regenerated: ${today}_`);
  lines.push('');
  lines.push(`**Bank totals:** ${gQ} live questions · ${gPub} published · ${gPyq} PYQ · ${gFlag} flagged (unresolved) · ${gNoPrim} missing primary tag · ${gNoMicro} missing micro tags.`);
  lines.push('');
  lines.push('Legend: **Q** = live (non-deleted) questions · **Pub** = published · **PYQ** = sourceType PYQ · **⚑** = questions with ≥1 unresolved flag · **NoPrim** = missing a primary concept (topic) tag · **NoMicro** = missing a micro concept (neither a `microConcept` value nor a micro_topic tag) · **TaxMicro** = micro_topics the taxonomy defines for the chapter (⚠0 = micro tags not generated in the taxonomy).');
  lines.push('');
  lines.push(...subjectLines);

  // Micro-tag taxonomy gaps
  lines.push('### ⚠ Micro-tag taxonomy gaps');
  if (microGaps.length === 0) {
    lines.push('None — every chapter that has questions also has micro_topics defined in the taxonomy.');
  } else {
    lines.push('Chapters that **have questions but no micro_topics in the taxonomy** — micro-tagging is impossible until these are generated:');
    lines.push('');
    lines.push('| Subject | Chapter | Questions |');
    lines.push('|---|---|---|');
    microGaps.sort((a, b) => b.q - a.q);
    for (const g of microGaps) lines.push(`| ${cell(g.subject)} | ${cell(g.name)} | ${g.q} |`);
  }

  return lines.join('\n').trimEnd();
}

function scaffold(autoBlock, today) {
  return `# Crucible — Project State

> **Single source of truth for what exists in the Crucible question bank.**
> Read this at the start of any Crucible task (ingestion, solutions, tagging,
> flag triage) instead of re-querying Mongo from scratch. The inventory below is
> generated from the \`crucible\` DB (\`questions_v2\`) joined against the taxonomy
> source of truth, so it reflects real state, not intentions.
>
> **Keep this current.** After ANY change to the question bank — questions or
> solutions added/updated, flags resolved, tags changed, taxonomy edits — run
> \`node scripts/crucible-state.js\` to refresh the inventory, then add one dated
> line to the Changelog at the bottom. The script only rewrites the AUTO region;
> it never touches the Changelog.

${AUTO_BEGIN}
${autoBlock}
${AUTO_END}

## Changelog

<!-- Newest first. One line per change: \`- YYYY-MM-DD — what changed (subject / chapter / counts)\`. -->

- ${today} — Initial Crucible state file created.
`;
}

async function main() {
  const taxonomyNodes = loadTaxonomy();
  const tax = buildTaxonomyIndex(taxonomyNodes);

  const client = new MongoClient(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 60000 });
  await client.connect();
  const db = client.db('crucible');

  const cursor = db.collection('questions_v2').find(
    {},
    { projection: { 'metadata.chapter_id': 1, 'metadata.subject': 1, 'metadata.tags': 1, 'metadata.microConcept': 1, 'metadata.sourceType': 1, 'metadata.is_pyq': 1, flags: 1, status: 1, deleted_at: 1 } }
  );

  const chapters = new Map(); // chapterId -> aggregate row
  for await (const q of cursor) {
    if (q.deleted_at) continue; // soft-deleted
    const m = q.metadata || {};
    const chapterId = m.chapter_id || '(no chapter_id)';
    const subject = (m.subject || '(unknown)');
    let row = chapters.get(chapterId);
    if (!row) {
      const node = tax.byId.get(chapterId);
      row = {
        chapterId, subject,
        name: node ? node.name : chapterId,
        inTaxonomy: !!node,
        seq: node && typeof node.sequence_order === 'number' ? node.sequence_order : 999999,
        total: 0, pub: 0, pyq: 0, flag: 0, noPrim: 0, noMicro: 0,
      };
      chapters.set(chapterId, row);
    }
    row.total++;
    if (q.status === 'published') row.pub++;
    if (m.sourceType === 'PYQ' || m.is_pyq === true) row.pyq++;
    if (Array.isArray(q.flags) && q.flags.some(f => !f.resolved)) row.flag++;
    const tags = Array.isArray(m.tags) ? m.tags : [];
    const hasPrimary = tags.some(t => tax.tagType(t.tag_id) === 'topic');
    // A question is micro-tagged if it has a free-text `microConcept` (the field
    // solution-generation fills) OR a micro_topic tag in tags[].
    const hasMicroConcept = typeof m.microConcept === 'string' && m.microConcept.trim() !== '';
    const hasMicro = hasMicroConcept || tags.some(t => tax.tagType(t.tag_id) === 'micro_topic');
    if (!hasPrimary) row.noPrim++;
    if (!hasMicro) row.noMicro++;
  }
  await client.close();

  // group by subject
  const bySubject = new Map();
  for (const row of chapters.values()) {
    if (!bySubject.has(row.subject)) bySubject.set(row.subject, []);
    bySubject.get(row.subject).push(row);
  }

  const today = new Date().toISOString().slice(0, 10);
  const autoBlock = buildAutoBlock(bySubject, tax, today);

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  if (!fs.existsSync(OUT)) {
    fs.writeFileSync(OUT, scaffold(autoBlock, today));
    console.log(`Created ${path.relative(path.join(__dirname, '..'), OUT)} (scaffold + inventory).`);
    return;
  }
  const existing = fs.readFileSync(OUT, 'utf8');
  const begin = existing.indexOf(AUTO_BEGIN);
  const end = existing.indexOf(AUTO_END);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error('AUTO markers not found or malformed in CRUCIBLE_STATE.md — refusing to overwrite.');
  }
  const updated = existing.slice(0, begin + AUTO_BEGIN.length) + '\n' + autoBlock + '\n' + existing.slice(end);
  fs.writeFileSync(OUT, updated);
  console.log(`Refreshed inventory in ${path.relative(path.join(__dirname, '..'), OUT)} (Changelog preserved).`);
}

main().catch(err => { console.error(err); process.exit(1); });
