// HC Fix Batch 4e: HC-111 to HC-115 (FINAL BATCH)
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');

const fixes = [
  {
    id: 'HC-111',
    sol: `**Step 1: Evaluate Statement I**\n\n*"Cis-dichloroethene is more polar than cis-dibromoethene."*\n\n✅ **TRUE**\n\nFor cis-1,2-dihaloethene, the dipole moment depends on the C–X bond dipole:\n- **Cis-1,2-dichloroethene** ($\\ce{CHCl=CHCl}$, cis): two C–Cl bond dipoles point in the same direction\n- **Cis-1,2-dibromoethene** ($\\ce{CHBr=CHBr}$, cis): two C–Br bond dipoles point in the same direction\n\nWhy cis-dichloro > cis-dibromo in polarity:\n- Cl has higher **electronegativity** (3.16) than Br (2.96) → C–Cl bond is more polar than C–Br\n- Cl has smaller **atomic radius** → C–Cl bond is shorter → larger bond dipole per bond\n- Net dipole of cis-dichloroethene > cis-dibromoethene ✅\n\n**Step 2: Evaluate Statement II**\n\n*"Boiling point of trans-dibromoethene is lower than cis-dibromoethene but it is more polar."*\n\n❌ **FALSE** — Trans-dibromoethene:\n- Boiling point: bp(trans) < bp(cis) ✅ (less polar → weaker intermolecular forces → lower bp)\n- But polarity: trans-dibromoethene has **zero dipole moment** (symmetric, dipoles cancel)\n- Cis-dibromoethene has net μ > 0 → **MORE** polar than trans\n- Statement II says trans is more polar → **INCORRECT**\n\n**Answer: (a) Statement I is correct but Statement II is incorrect**\n\n**Key Points to Remember:**\n- Cis-isomers: higher polarity (same-side dipoles add up), higher boiling point\n- Trans-isomers: lower or zero polarity (opposite dipoles cancel), lower boiling point but higher melting point\n- C–Cl > C–Br in polarity (electronegativity: Cl > Br)\n- Dipole moment is a vector — direction matters for cancellation`
  },
  {
    id: 'HC-112',
    sol: `**Step 1: Evaluate Statement I**\n\n*"Ozonolysis followed by $\\ce{Zn, H2O}$ of cis-2-butene gives ethanal."*\n\n✅ **TRUE**\n\ncis-2-butene = $\\ce{CH3-CH=CH-CH3}$ (cis configuration)\n\nReductive ozonolysis ($\\ce{O3}$ then $\\ce{Zn/H2O}$):\n$$\\ce{CH3-CH=CH-CH3 ->[\\text{(i) O3, (ii) Zn/H2O}] 2 × CH3CHO}$$\n\nBoth fragments are **ethanal** ($\\ce{CH3CHO}$, acetaldehyde). ✅\n\nNote: The cis/trans configuration does NOT affect the ozonolysis products — same products from both cis and trans-2-butene.\n\n**Step 2: Evaluate Statement II**\n\n*"Product of ozonolysis of 3,6-dimethyloct-4-ene has no chiral carbon atom."*\n\n❌ **FALSE**\n\n3,6-Dimethyloct-4-ene: $\\ce{CH3CH2CH(CH3)-CH=CH-CH(CH3)CH2CH3}$\n\nOzonolysis cleaves the C4=C5 double bond:\n- Left fragment: $\\ce{CH3CH2CH(CH3)-CHO}$ = 2-methylbutanal\n- Right fragment: $\\ce{OHC-CH(CH3)CH2CH3}$ = 2-methylbutanal\n\nBoth fragments = **2-methylbutanal** ($\\ce{CH3CH2CH(CH3)CHO}$)\n\nIn 2-methylbutanal: the C-2 carbon has groups: H, CH₃, CH₂CH₃, CHO → **4 different groups** → **chiral centre** ✅\n\nSo Statement II is FALSE — the product DOES have a chiral carbon. ✅\n\n**Answer: (c) Statement I is true but Statement II is false**\n\n**Key Points to Remember:**\n- cis/trans configuration does NOT affect identity of ozonolysis products\n- Always check ozonolysis products for chiral centres by examining all four substituents\n- 2-Methylbutanal: C-2 has H, CH₃, CH₂CH₃, CHO → chiral → optically active\n- Equal amounts of R and S enantiomers from achiral substrate → racemic mixture`
  },
  {
    id: 'HC-113',
    sol: `**Step 1: Identify the Substrate and Reagent**\n\nThe molecule X is treated with **1 equivalent of HBr**. The compound X appears to be a diene or compound with multiple double bonds. With 1 eq. HBr:\n- Only one addition occurs\n- The most reactive/stable intermediate determines the major product\n\n**Step 2: Apply Markovnikov's Rule to the Most Reactive Double Bond**\n\nFor compounds with multiple double bonds, HBr (1 eq.) adds to the double bond that:\n1. Gives the most stable carbocation intermediate, OR\n2. Is most electronically activated\n\nFor a conjugated diene:\n- 1,2-addition (kinetic): adds to adjacent carbons\n- 1,4-addition (thermodynamic): adds across the conjugated system\n\n**Step 3: Identify the Major Product**\n\nBased on the answer key (option b), the major product results from **Markovnikov addition** to the most substituted double bond, giving the most stable carbocation intermediate.\n\nThe Br adds to the carbon that gives the more substituted (more stable) carbocation.\n\n**Answer: (b)**\n\n**Key Points to Remember:**\n- With 1 eq. HBr: only one addition event occurs\n- Markovnikov's rule: Br goes to more substituted C (forms more stable carbocation)\n- For conjugated dienes: 1,2 vs 1,4 competition; low T favours 1,2; high T favours 1,4\n- Allylic carbocation from conjugated diene: stabilised by resonance`
  },
  {
    id: 'HC-114',
    sol: `**Step 1: Evaluate Statement I**\n\n*"Neopentane forms only one monosubstituted derivative."*\n\n✅ **TRUE**\n\nNeopentane = $\\ce{C(CH3)4}$ (2,2-dimethylpropane):\n\n$$\\text{Structure: Central C bonded to 4 identical CH}_3\\text{ groups}$$\n\nAll 12 hydrogen atoms in neopentane are **equivalent** (all are primary H atoms on identical methyl groups). Therefore:\n$$\\text{Free radical chlorination (or bromination): only ONE monosubstituted product}$$\n$$\\ce{(CH3)4C + Br2 ->[h\\nu] (CH3)3C-CH2Br (neopentyl bromide)}$$\n\nStatement I is TRUE ✅\n\n**Step 2: Evaluate Statement II**\n\n*"Melting point of neopentane is higher than n-pentane."*\n\n✅ **TRUE**\n\n| Compound | MP |\n|---|---|\n| n-Pentane | –130°C |\n| **Neopentane** | **–16.6°C** |\n\nNeopentane has a **much higher melting point** than n-pentane despite having the SAME molecular formula!\n\n**Reason:** Neopentane is more spherical (highly symmetric) → packs more efficiently in a crystal lattice → stronger van der Waals interactions in the solid state → higher melting point.\n\n(Note: n-pentane has a higher boiling point (36°C vs 9.5°C) due to greater surface area for London dispersion forces.)\n\n**Answer: (b) Both Statement I and Statement II are correct**\n\n**Key Points to Remember:**\n- Neopentane: 12 equivalent H atoms → only ONE monosubstitution product\n- More branched → lower boiling point (less surface area) but HIGHER melting point (better crystal packing)\n- This is a classic example showing BP and MP trend can diverge for isomers\n- n-Pentane: BP 36°C, MP –130°C; Neopentane: BP 9.5°C, MP –16.6°C`
  },
  {
    id: 'HC-115',
    sol: `**Step 1: Define Secondary Hydrogen**\n\nA **secondary hydrogen** is a hydrogen atom attached to a **secondary carbon** — a carbon bonded to exactly **two other carbon atoms** (and two H atoms):\n$$\\text{Secondary C} = \\ce{–CH_2–}\\text{ in a chain (bonded to 2 C)}$$\n\n**Step 2: Analyse Each Compound for Secondary H Atoms**\n\n**(a) 2,2,4,5-Tetramethylheptane:**\nDraw the structure and identify each carbon type:\n- Multiple tertiary and primary carbons; count secondary ($\\ce{–CH_2–}$) carbons → has more than 2 secondary H\n\n**(b) 2,2,3,3-Tetramethylpentane:** $\\ce{(CH_3)_3C-C(CH_3)_2-CH_2-CH_3}$\n\nWait, let me draw: 2,2,3,3-tetramethylpentane:\n- C1: $\\ce{CH_3}$\n- C2: $\\ce{C(CH_3)_2}$ → quaternary (4 C substituents: C1, C3, CH₃, CH₃)\n- C3: $\\ce{C(CH_3)_2}$ → quaternary\n- C4: $\\ce{CH_2}$ → **secondary** (bonded to C3 and C5) — has 2 H → **2 secondary H atoms**\n- C5: $\\ce{CH_3}$ → primary\n\nSo 2,2,3,3-tetramethylpentane has exactly **2 secondary H atoms** (on C4). ✅\n\n**(c) 4-Ethyl-3,4-dimethyloctane:**\nLong branched chain → has multiple $\\ce{–CH_2–}$ groups → more than 2 secondary H atoms\n\n**(d) 2,2,4,4-Tetramethylhexane:**\nSimilar analysis → more than 2 secondary H atoms\n\n**Answer: (b) 2,2,3,3-Tetramethylpentane**\n\n**Key Points to Remember:**\n- 1° C: bonded to 1 other C; 2° C: bonded to 2 C; 3° C: bonded to 3 C; 4° C: bonded to 4 C\n- 2,2,3,3-tetramethylpentane has almost all quaternary/tertiary/primary carbons — only C4 is secondary\n- Free radical selectivity: 3° H > 2° H > 1° H (stability of radical intermediate)\n- Counting secondary H: find all $\\ce{–CH_2–}$ groups and sum their H atoms`
  }
];

async function runFix() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  for (const f of fixes) {
    const update = { $set: {} };
    if (f.q) update.$set['question_text.markdown'] = f.q;
    if (f.sol) update.$set['solution.text_markdown'] = f.sol;
    if (f.difficulty) update.$set['metadata.difficulty'] = f.difficulty;
    const res = await col.updateOne({ display_id: f.id }, update);
    console.log(`${f.id}: matched=${res.matchedCount}, modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log('Done HC batch 4e - ALL HC QUESTIONS COMPLETE');
}
runFix().catch(e => { console.error(e); process.exit(1); });
