// HC Fix Batch 2a: HC-031 to HC-035
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');

const fixes = [
  {
    id: 'HC-031',
    sol: `**Step 1: Identify the Reaction**\n\nThe reaction involves an alkene treated with $\\ce{H2SO4}$ at high temperature. This is the **sulfonation** reaction or more specifically, addition of $\\ce{H2SO4}$ to an alkene (acid-catalysed addition).\n\nHowever, at elevated temperature, $\\ce{H2SO4}$ can act differently:\n- At room temperature: Markovnikov addition of $\\ce{H-OSO3H}$ (gives alkyl hydrogen sulfate)\n- At high temperature: The reaction may lead to rearrangement or elimination\n\n**Step 2: Mechanism of H₂SO₄ Addition to Alkene**\n\nFor the addition of $\\ce{H2SO4}$ to an alkene:\n$$\\ce{R-CH=CH2 + H2SO4 -> R-CH(OSO3H)-CH3}$$\n\nMarkovnikov's rule applies:\n- $\\ce{H+}$ adds to the less substituted carbon (more H atoms)\n- $\\ce{HSO4^-}$ adds to the more substituted carbon\n\nThis produces an **alkyl hydrogen sulphate** (organosulfate).\n\n**Step 3: Identify the Major Product**\n\nThe major product A (per answer key) shows the $\\ce{-OSO3H}$ group attached to the more substituted carbon (Markovnikov's product).\n\n**Answer: (a)**\n\n**Key Points to Remember:**\n- $\\ce{H2SO4}$ adds to alkenes following Markovnikov's rule: H to less substituted C\n- Product: alkyl hydrogen sulphate ($\\ce{R-OSO3H}$)\n- On hydrolysis: alkyl hydrogen sulphate → alcohol (indirect hydration)\n- This is the basis of the industrial preparation of ethanol from ethene`
  },
  {
    id: 'HC-032',
    sol: `**Step 1: Understand Dehydrohalogenation**\n\nβ-Elimination using alc. KOH removes HX from alkyl halides. The alkene formed depends on:\n1. Zaitsev's rule: the more substituted (stable) alkene is the major product\n2. The β-carbons available (adjacent to the halogen-bearing carbon)\n\n**Step 2: Match Each Alkyl Halide to Its Elimination Product**\n\n**A. 1-Bromo-2-methylbutane:** $\\ce{CH3-CHBr-CH(CH3)-CH2CH3}$\n- Wait — 1-Bromo-2-methylbutane = $\\ce{BrCH2-CH(CH3)-CH2-CH3}$\n- β-carbons: C-2 (has 1H)\n- Elimination: removes HBr → **2-methylbut-1-ene** or **2-methylbut-2-ene**\n- By Zaitsev: 2-methylbut-2-ene is more substituted → **2-Methylbutene (II)** ✓\n\n**B. 2-Bromopropane:** $\\ce{CH3-CHBr-CH3}$\n- Only possible β-carbon: C-1 (both equivalent)\n- Elimination → **Propene (I)** ✓\n\n**C. 2-Bromopentane:** $\\ce{CH3-CHBr-CH2CH2CH3}$\n- β-carbons: C-1 (→ pent-1-ene) and C-3 (→ pent-2-ene)\n- Both products form → **Pent-1-ene and Pent-2-ene (III)** ✓\n\n**D. 2-Bromo-3,3-dimethylpentane:** $\\ce{CH3-CHBr-C(CH3)2-CH2CH3}$\n- β-carbons: C-1 (→ 3,3-dimethylpent-1-ene) and C-4 (→ 3,3-dimethylpent-2-ene)\n- Major product: 3,3-Dimethylpentene (**IV**) ✓\n\n**Step 3: Match Table**\n\n| Alkyl Halide | Alkene |\n|---|---|\n| A | II (2-Methylbutene) |\n| B | I (Propene) |\n| C | III (Pent-1-ene and Pent-2-ene) |\n| D | IV (3,3-Dimethylpentene) |\n\n**Answer: (c) A-II, B-I, C-III, D-IV**\n\n**Key Points to Remember:**\n- Zaitsev's rule: major product is more substituted alkene\n- β-carbon = carbon adjacent to C bearing the leaving group\n- Multiple β-carbons → multiple alkene products\n- Alc. KOH → elimination; aq. KOH → substitution (SN2)`
  },
  {
    id: 'HC-033',
    sol: `**Step 1: Identify the Reaction**\n\nThe reaction shows an alkene (likely a nitrile-containing alkene based on the solution note "CN group is written as C#N") being treated with HBr. This is **electrophilic addition of HBr to an alkene** following Markovnikov's rule.\n\n**Step 2: Apply Markovnikov's Rule**\n\nFor HBr addition to an alkene:\n- $\\ce{H+}$ (proton) adds to the double-bond carbon with MORE hydrogen atoms\n- $\\ce{Br^-}$ adds to the carbon with FEWER hydrogen atoms (more substituted)\n- This produces the more stable carbocation intermediate\n\n**Step 3: Consider the CN Group's Influence**\n\n$\\ce{-CN}$ (nitrile/cyano group) is an **electron-withdrawing group** (EWG) via both -I and -M effects:\n- It destabilises adjacent positive charges\n- The carbocation will form at the carbon AWAY from the $\\ce{-CN}$ group\n- Therefore Br⁻ adds at the carbon away from CN (Markovnikov's considering inductive effects)\n\n**Step 4: Identify Major Product**\n\nThe major product (per answer key a) shows Br attached to the correct carbon consistent with:\n- Markovnikov's rule applied to the CN-containing alkene\n- Carbocation stabilised away from the electron-withdrawing CN group\n\n**Answer: (a)**\n\n**Key Points to Remember:**\n- Markovnikov addition: H adds to less substituted C; nucleophile adds to more substituted C\n- EWG like -CN destabilise adjacent carbocations → cation forms farther from EWG\n- EDG like -OCH₃ stabilise adjacent carbocations via resonance → cation forms near EDG\n- Free radical HBr addition: anti-Markovnikov (Br to less substituted C)`
  },
  {
    id: 'HC-034',
    sol: `**Step 1: Identify the Reaction**\n\nThe reaction involves **hydroboration-oxidation** ($\\ce{BH3/THF}$ then $\\ce{H2O2/NaOH}$). This is a two-step process:\n1. **Hydroboration:** $\\ce{BH3}$ adds to the alkene (syn addition, anti-Markovnikov: B to less substituted C)\n2. **Oxidation:** $\\ce{H2O2/NaOH}$ replaces B with OH (with retention of configuration)\n\n**Step 2: Regiochemistry**\n\nHydroboration-oxidation gives **anti-Markovnikov addition** of OH:\n- OH goes to the **less substituted** carbon of the double bond\n- For $\\ce{CH3-CH=CH2}$: OH adds to C-1 (terminal C) → primary alcohol\n\n**Step 3: Stereochemistry**\n\nThe overall addition is **syn** (both H and OH add from the same face):\n- Hydroboration: syn addition of B-H\n- Oxidation: retention of configuration at B-bearing carbon\n- Net result: syn addition of OH\n\n**Step 4: Identify Product**\n\nFor the specific alkene in the image, the major product (option b) shows the OH group added anti-Markovnikov (at less substituted carbon) with syn stereospecificity.\n\n**Answer: (b)**\n\n**Key Points to Remember:**\n- Hydroboration-oxidation: anti-Markovnikov + syn addition (overall)\n- $\\ce{BH3}$ adds across double bond: B to less hindered C, H to more hindered C\n- Oxidation with $\\ce{H2O2/NaOH}$: retains stereochemistry at the B-bearing carbon\n- Compare with acid-catalysed hydration: Markovnikov + no stereospecificity`
  },
  {
    id: 'HC-035',
    sol: `**Step 1: Identify the Compound and Reaction**\n\n**2-Hexene:** $\\ce{CH3-CH=CH-CH2CH2CH3}$\n\n**Ozonolysis in presence of water** = oxidative ozonolysis:\n$$\\ce{R-CH=CH-R' ->[\\text{(i) O}_3, \\text{(ii) H}_2\\text{O/H}_2\\text{O}_2] RCOOH + R'COOH}$$\n\nNote: Ozonolysis with $\\ce{H2O}$ (or $\\ce{H2O2}$ workup) gives **carboxylic acids** from both aldehyde fragments (oxidative conditions).\n\n**Step 2: Apply Ozonolysis to 2-Hexene**\n\nBreaking the double bond at C2–C3:\n\n$$\\ce{CH3-\\underset{\\displaystyle|}{\\underset{}{\\overset{}{\\overset{}{CH}}}}=\\underset{}{\\underset{}{CH}}-CH2CH2CH3}$$\n\n- Left fragment: $\\ce{CH3-CH}$ → $\\ce{CH3-COOH}$ = **acetic acid (ethanoic acid)**\n- Right fragment: $\\ce{CH-CH2CH2CH3}$ → $\\ce{CH3CH2CH2-COOH}$ = **butanoic acid**\n\n**Step 3: Verify**\n\n$$\\ce{CH3-CH=CH-CH2CH2CH3 ->[\\text{(i) O}_3, \\text{(ii) H}_2\\text{O}] CH3COOH + CH3CH2CH2COOH}$$\n\n- Acetic acid: 2C (CH₃COOH) ✓ from C1–C2 fragment\n- Butanoic acid: 4C (CH₃CH₂CH₂COOH) ✓ from C3–C6 fragment\n\n**Answer: (a) Acetic acid and butanoic acid**\n\n**Key Points to Remember:**\n- Oxidative ozonolysis ($\\ce{H2O}$ or $\\ce{H2O2}$): gives carboxylic acids from both carbons\n- Reductive ozonolysis ($\\ce{Zn/H2O}$ or $\\ce{Me2S}$): gives aldehydes (and ketones)\n- Carbon balance: acetic acid (2C) + butanoic acid (4C) = 6C = hexene ✓\n- Identify which carbon is on which side of the double bond to assign products correctly`
  }
];

async function runFix() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  for (const f of fixes) {
    const update = { $set: {} };
    if (f.q) update.$set['question_text.markdown'] = f.q;
    if (f.sol) update.$set['solution.text_markdown'] = f.sol;
    if (f.difficulty) update.$set['metadata.difficulty'] = f.difficulty;
    const res = await col.updateOne({ display_id: f.id }, update);
    console.log(`${f.id}: matched=${res.matchedCount}, modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log('Done HC batch 2a');
}
runFix().catch(e => { console.error(e); process.exit(1); });
