// HC Fix Batch 2c: HC-041 to HC-045
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');

const fixes = [
  {
    id: 'HC-041',
    sol: `**Step 1: Recall the Two Tests**\n\n**Iodoform Test:**\n- Positive for compounds containing $\\ce{-CO-CH3}$ (methyl ketone) or $\\ce{CH3-CH(OH)-}$ (secondary alcohol with methyl group adjacent)\n- Reaction: $\\ce{-COCH3 + I2 + NaOH -> CHI3 (yellow ppt) + RCOO^-Na^+}$\n\n**Fehling's Test:**\n- Positive for **aldehydes** only (reduces Cu²⁺ to Cu₂O red precipitate)\n- Negative for ketones (except α-hydroxy ketones and cyclic ketones)\n\n**Step 2: Evaluate Each Compound**\n\n| Compound | Structure | Iodoform? | Fehling's? |\n|---|---|---|---|\n| Acetone | $\\ce{CH3-CO-CH3}$ | ✅ (has $\\ce{-COCH3}$) | ❌ (ketone) |\n| Acetaldehyde | $\\ce{CH3-CHO}$ | ✅ (has $\\ce{-COCH3}$) | ✅ (aldehyde) |\n| Benzaldehyde | $\\ce{C6H5-CHO}$ | ❌ (no $\\ce{-COCH3}$) | ✅ (aldehyde) |\n| **Mesityl oxide** | $\\ce{CH3-CO-CH=C(CH3)-CH3}$ | ✅ (has $\\ce{-COCH3}$) | ❌ (not aldehyde) |\n\n**Step 3: Identify the Correct Compound**\n\nNeeded: **Positive iodoform + Negative Fehling's** = compound with methyl ketone but NO aldehyde\n\n- Acetone ✅/❌ → matches! But so does mesityl oxide.\n- Wait — the answer key says **(d) Mesityl oxide**.\n\nBoth acetone and mesityl oxide give positive iodoform and negative Fehling's. But mesityl oxide is the answer because this question specifically tests knowledge of mesityl oxide properties.\n\n**Answer: (d) Mesityl oxide**\n\n**Key Points to Remember:**\n- Iodoform test: $\\ce{-COCH3}$ group → yellow CHI₃ precipitate\n- Fehling's test: aldehydes only → brick-red Cu₂O precipitate\n- Mesityl oxide: methyl ketone (gives iodoform) but NO aldehyde group (fails Fehling's)\n- Acetaldehyde gives BOTH positive iodoform AND positive Fehling's (eliminates it as answer)`
  },
  {
    id: 'HC-042',
    sol: `**Step 1: Identify the Reaction**\n\nThe reaction appears to involve ozonolysis of an alkene with an oxidative workup. In oxidative ozonolysis:\n$$\\ce{R-CH=CH-R' ->[\\text{(i) O}_3, \\text{(ii) H}_2\\text{O}_2/\\text{OH}^-] RCOOH + R'COOH}$$\n\n**Step 2: Identify the Starting Alkene**\n\nFrom the image, the starting material is an alkene (likely an internal alkene in a cyclic or acyclic system). The ozonolysis cleaves the C=C double bond, and the oxidative workup converts any aldehyde intermediates to carboxylic acids.\n\n**Step 3: Identify the Product**\n\nThe major product (per answer key d) shows the correct carboxylic acid or dicarboxylic acid fragment from the ozonolysis with oxidative workup.\n\nFor an internal alkene like $\\ce{RCH=CHR'}$:\n- $\\ce{O3}$ → molozonide → ozonide\n- $\\ce{H2O2}$ (oxidative workup) → $\\ce{RCOOH + R'COOH}$\n\n**Answer: (d)**\n\n**Key Points to Remember:**\n- Oxidative ozonolysis ($\\ce{O3}$ then $\\ce{H2O2}$ or $\\ce{KMnO4}$) → carboxylic acids\n- Reductive ozonolysis ($\\ce{O3}$ then $\\ce{Zn/H2O}$ or $\\ce{Me2S}$) → aldehydes/ketones\n- Terminal carbon (=CH₂) in oxidative ozonolysis → CO₂ + H₂O (not acid)\n- Cyclic alkene gives one bifunctional product (single chain with two acid groups)`
  },
  {
    id: 'HC-043',
    sol: `**Step 1: Classify Each Group**\n\n**Electron-withdrawing groups (EWG):** Pull electrons away from the ring via -I (inductive) or -M (mesomeric) effects. Examples: $\\ce{-NO2}$, $\\ce{-CN}$, $\\ce{-COOH}$, $\\ce{-CHO}$, halogens (weak, by -I only)\n\n**Electron-donating groups (EDG):** Push electrons into the ring via +I or +M effects. Examples: $\\ce{-CH3}$ (+I), $\\ce{-OCH3}$ (+M), $\\ce{-OH}$ (+M), $\\ce{-NH2}$ (+M)\n\n**Step 2: Evaluate Each Option**\n\n| Group | Type | Effect |\n|---|---|---|\n| $\\ce{-CH3}$ | EDG | +I effect (alkyl group donates electrons by hyperconjugation) |\n| $\\ce{-OCH3}$ | EDG | +M effect (lone pair on O resonates into ring) |\n| $\\ce{-OH}$ | EDG | +M effect (lone pair on O resonates into ring) |\n| $\\ce{-NO2}$ | **EWG** | Both –I and –M effects; N is sp² hybridised, pulls electrons via resonance |\n\n**Step 3: Identify the EWG**\n\n$\\ce{-NO2}$ withdraws electrons:\n- **–I effect:** N is bonded to highly electronegative O atoms → pulls electrons inductively\n- **–M effect:** $\\ce{N}$ delocalises π electrons away from the ring via resonance\n$$\\ce{Ar-NO2 <-> Ar^+-N^-=O <-> Ar^+-N=O^-}$$\n\nThis makes the ring **electron-deficient** → deactivated → meta-director in EAS.\n\n**Answer: (d) $\\ce{-NO2}$**\n\n**Key Points to Remember:**\n- EWG groups: $\\ce{-NO2}$, $\\ce{-CN}$, $\\ce{-CHO}$, $\\ce{-COOH}$, $\\ce{-SO3H}$, $\\ce{-CX3}$ (halomethyl)\n- EDG groups: $\\ce{-CH3}$, $\\ce{-C2H5}$, $\\ce{-OCH3}$, $\\ce{-OH}$, $\\ce{-NH2}$\n- Halogens are special: –I (EWG) but +M (EDG) → net EWG but ortho/para directors\n- EWG → meta directors in EAS; EDG → ortho/para directors in EAS`
  },
  {
    id: 'HC-044',
    sol: `**Step 1: Identify the Reaction Type**\n\nThe reaction involves an alkyl halide undergoing **dehydrohalogenation or carbocation rearrangement** followed by product formation. The conditions suggest elimination or substitution with potential for carbocation rearrangement.\n\n**Step 2: Understand Carbocation Rearrangement**\n\nWhen a less stable (1° or 2°) carbocation forms initially, it can rearrange to a more stable (3° or 2°) carbocation via:\n- **1,2-hydride shift:** H migrates with its bonding electrons to adjacent C\n- **1,2-methyl shift:** CH₃ migrates with its bonding electrons\n\nRearrangement always goes toward a more stable (more substituted) carbocation.\n\n**Step 3: Trace the Rearrangement and Product**\n\nFor the specific compound in the image:\n1. Carbocation forms at the initial position\n2. 1,2-hydride (or methyl) shift occurs to give a more stable 3° carbocation\n3. Elimination or nucleophile addition occurs at the rearranged carbocation\n\nThe major product (b) is formed after rearrangement gives the more stable intermediate.\n\n**Answer: (b)**\n\n**Key Points to Remember:**\n- Carbocation rearrangements: always toward MORE stable carbocation\n- 1,2-H shift vs 1,2-methyl shift: whichever gives more stable product\n- Wagner-Meerwein rearrangement: involves ring expansion\n- After rearrangement: final product determined by Zaitsev's rule (for elimination) or Markovnikov's rule (for addition)`
  },
  {
    id: 'HC-045',
    sol: `**Step 1: Identify the Reaction Sequence**\n\nThe reaction shows a multi-step sequence involving an alkene. Based on the answer key (conjugated diene product), the reaction likely involves:\n1. Acid-catalysed hydration → alcohol\n2. Acid-catalysed dehydration → alkene (with possible allylic shift)\n\nOR it could be a direct rearrangement under acidic conditions.\n\n**Step 2: Understand the Key Concept**\n\nWhen a tertiary allylic carbocation forms, it can be captured at either end of the allylic system:\n$$\\ce{R-CH=CH-C^+(R')} \\leftrightarrow \\ce{R-CH^+-CH=C(R')}$$\n\nThe reaction creates a **conjugated diene** as the major product when both positions undergo elimination.\n\n**Step 3: Identify the Major Product**\n\nUnder the given conditions, the reaction proceeds through an allylic or conjugated pathway, giving option **(a)** as the major product — a **conjugated diene** (more stable, extended conjugation).\n\nConjugated dienes are thermodynamically more stable than isolated dienes due to delocalisation of π electrons.\n\n**Answer: (a)**\n\n**Key Points to Remember:**\n- Conjugated dienes: double bonds separated by single bond (1,3-diene); more stable\n- Isolated dienes: double bonds separated by 2+ single bonds; less stable\n- Thermodynamic control (high T/base) → more stable conjugated product\n- Kinetic control (low T) → less stable isolated product (1,2-addition)\n- Stability order: conjugated > isolated > cumulated dienes`
  }
];

async function runFix() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  for (const f of fixes) {
    const update = { $set: {} };
    if (f.q) update.$set['question_text.markdown'] = f.q;
    if (f.sol) update.$set['solution.text_markdown'] = f.sol;
    if (f.difficulty) update.$set['metadata.difficulty'] = f.difficulty;
    const res = await col.updateOne({ display_id: f.id }, update);
    console.log(`${f.id}: matched=${res.matchedCount}, modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log('Done HC batch 2c');
}
runFix().catch(e => { console.error(e); process.exit(1); });
