/**
 * Scans all Inorganic Chemistry flashcards and flags cards where
 * an image or diagram would significantly improve learning efficiency.
 *
 * Outputs: scripts/image_candidates.md
 *
 * Usage:
 *   node scripts/identify_image_candidates.js
 */

require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');

// ─── Scoring rules ────────────────────────────────────────────────────────────
// Each rule adds a reason string if it matches. Cards with ≥1 reason are flagged.

const RULES = [
  // Molecular geometry / structure
  { re: /\b(structure|shape|geometry|angular|linear|pyramidal|planar|tetrahedral|octahedral|trigonal|square planar|T-shaped|see-saw|seesaw|bipyramidal|bent|V-shaped)\b/i,
    tag: 'Molecular structure / shape' },

  // Hybridisation
  { re: /\b(sp3d?2?|sp2|sp3|sp|hybridiz|hybridis)\b/i,
    tag: 'Hybridisation diagram' },

  // Bond angle
  { re: /bond angle|H[-–]N[-–]H|H[-–]O[-–]H|lone pair/i,
    tag: 'Bond angle / VSEPR' },

  // Allotropes with distinct 3D forms
  { re: /\b(allotrope|P4|S8|rhombic|monoclinic|buckminster|fullerene|graphite|diamond|carborundum)\b/i,
    tag: 'Allotrope structure' },

  // Industrial processes
  { re: /blast furnace|contact process|Haber|froth flotation|zone refining|electrolytic refining|down'?s cell|Hall.Héroult|Bayer process|Solvay|van Arkel/i,
    tag: 'Industrial process diagram' },

  // Salt analysis flowchart
  { re: /\b(Group [0IV]+|precipitate|centrifugate|filtrate|add H2S|group reagent|confirmatory)\b/i,
    tag: 'Salt analysis flowchart / precipitate colours' },

  // Colour of precipitate / compound (visual memory)
  { re: /\b(white ppt|yellow ppt|red ppt|black ppt|blue ppt|brown ppt|green ppt|cream ppt|pale yellow|brick.?red|prussian blue|blood.?red|chrome.?yellow|scarlet|vermilion)\b/i,
    tag: 'Precipitate / compound colour chart' },

  // Flame test colours
  { re: /flame test|crimson|lilac|violet flame|brick.?red flame|golden yellow|apple.?green|blue.?green/i,
    tag: 'Flame test colour reference' },

  // Crystal / unit cell structures
  { re: /\b(NaCl structure|CsCl structure|ZnS|zinc.?blende|wurtzite|fluorite|rock salt|unit cell|fcc|bcc|hcp|coordination number \d)\b/i,
    tag: 'Crystal structure / unit cell' },

  // Periodic trends (graphs)
  { re: /\b(increases down|decreases down|trend across period|anomalous(ly)?|first ioniz|ionisation energy|electron affinity|electronegativity)\b.*\b(group|period)\b/i,
    tag: 'Periodic trend graph' },

  // Coordination compound 3D shapes
  { re: /\b(fac|mer|cis|trans) isomer|optical isomer|geometri[cs] isomer.*complex|octahedral complex|square planar complex/i,
    tag: 'Coordination compound isomer diagram' },

  // Oxoacid structures (phosphorus, sulfur, chlorine series)
  { re: /\b(H3PO4|H3PO3|H3PO2|HPO3|H4P2O7|H2SO3|H2SO4|H2S2O7|H2S2O8|HClO4|HClO3|HClO2|HClO)\b.*\b(structure|P[-–]OH|S[-–]O|P=O)\b/i,
    tag: 'Oxoacid structure diagram' },

  // Noble gas / interhalogen structures
  { re: /\b(XeF2|XeF4|XeF6|XeO3|XeOF|ClF3|IF5|IF7|BrF3|BrF5)\b/i,
    tag: 'Interhalogen / noble gas structure' },

  // Process: extraction steps with multiple stages
  { re: /\b(slag|tuyere|hearth|stope|vat leaching|heap leaching|cyanide process|amalgamation)\b/i,
    tag: 'Metallurgical process diagram' },

  // Colour changes on heating (visual before/after)
  { re: /on heating.*colo(u)?r|colo(u)?r change.*heat|green to (black|brown)|blue to (white|black|red)/i,
    tag: 'Colour change on heating' },
];

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  const coll = mongoose.connection.db.collection('flashcards');

  const cards = await coll.find({
    'chapter.category': 'Inorganic Chemistry',
    deleted_at: null,
  }).sort({ 'chapter.name': 1, 'topic.order': 1, flashcard_id: 1 }).toArray();

  console.log(`Scanning ${cards.length} inorganic cards…`);

  // ── Categorise ──────────────────────────────────────────────────────────────
  const byChapter = {};
  for (const card of cards) {
    const combined = (card.question || '') + ' ' + (card.answer || '');
    const tags = [];
    for (const { re, tag } of RULES) {
      if (re.test(combined)) tags.push(tag);
    }
    if (!tags.length) continue;

    const ch = card.chapter?.name || card.chapter?.id;
    if (!byChapter[ch]) byChapter[ch] = [];
    byChapter[ch].push({
      id: card.flashcard_id,
      topic: card.topic?.name || '—',
      q: card.question?.replace(/\n/g, ' ').slice(0, 120),
      tags,
    });
  }

  // ── Build markdown ──────────────────────────────────────────────────────────
  const lines = [
    '# Inorganic Flashcards — Image Candidates',
    '',
    '> Generated by `scripts/identify_image_candidates.js`  ',
    '> Cards flagged where a diagram, chart, or illustration would meaningfully improve retention.',
    '',
    `**Total flagged:** ${Object.values(byChapter).flat().length} / ${cards.length} cards`,
    '',
    '---',
    '',
  ];

  for (const [chapter, items] of Object.entries(byChapter).sort()) {
    lines.push(`## ${chapter}  (${items.length} flagged)`);
    lines.push('');

    // Group by topic
    const byTopic = {};
    for (const item of items) {
      if (!byTopic[item.topic]) byTopic[item.topic] = [];
      byTopic[item.topic].push(item);
    }

    for (const [topic, topicItems] of Object.entries(byTopic)) {
      lines.push(`### ${topic}`);
      lines.push('');
      lines.push('| ID | Question (truncated) | Image type |');
      lines.push('|---|---|---|');
      for (const { id, q, tags } of topicItems) {
        const safeQ = (q || '').replace(/\|/g, '\\|');
        lines.push(`| \`${id}\` | ${safeQ} | ${tags.join('; ')} |`);
      }
      lines.push('');
    }
  }

  // ── Image type summary ──────────────────────────────────────────────────────
  const tagTally = {};
  for (const item of Object.values(byChapter).flat()) {
    for (const t of item.tags) tagTally[t] = (tagTally[t] ?? 0) + 1;
  }
  lines.push('---');
  lines.push('');
  lines.push('## Summary by Image Type');
  lines.push('');
  lines.push('| Image type | Cards |');
  lines.push('|---|---|');
  for (const [tag, n] of Object.entries(tagTally).sort((a,b)=>b[1]-a[1])) {
    lines.push(`| ${tag} | ${n} |`);
  }
  lines.push('');

  const outPath = path.join(__dirname, 'image_candidates.md');
  fs.writeFileSync(outPath, lines.join('\n'));
  console.log(`\nWrote ${outPath}`);
  console.log(`Flagged ${Object.values(byChapter).flat().length} cards across ${Object.keys(byChapter).length} chapters.`);

  await mongoose.disconnect();
}

run().catch(err => { console.error(err); process.exit(1); });
