// Hydrocarbons - Batch 4 FINAL: MD Q93-114 (HC-088 to HC-109) + Q1-6 (HC-110 to HC-115) - 28 questions
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid');

const questions = [
  // Q93 -> HC-088: Aromatic compounds
  { _id: uuidv4(), display_id: 'HC-088', question_text: { markdown: `Which of the following compounds are aromatic?\n\n(A) ![A](image) (B) ![B](image) (C) ![C](image) (D) ![D](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '(A) and (C) only', is_correct: false }, { id: 'b', text: '(B), (C) and (D) only', is_correct: true }, { id: 'c', text: '(B) and (D) only', is_correct: false }, { id: 'd', text: '(A), (B) and (C) only', is_correct: false }], answer: { correct_option: 'b', explanation: 'B, C and D are aromatic compounds.' }, solution: { text_markdown: `B, C and D are Aromatic compounds.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2020, month: 'Jan', day: 7, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },
  
  // Q94 -> HC-089
  { _id: uuidv4(), display_id: 'HC-089', question_text: { markdown: `Which one of the following is an aromatic species?`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: true }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: false }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'a', explanation: 'It is aromatic species with 6 π electrons.' }, solution: { text_markdown: `It is aromatic species.\n\nAnswer: **(a)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 12, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  // Q95-109 and Q1-6 (HC-090 to HC-115) - Condensed format
  { _id: uuidv4(), display_id: 'HC-090', question_text: { markdown: `Arrange the following in increasing order of stability:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'a < b < c', is_correct: false }, { id: 'b', text: 'c < a < b', is_correct: false }, { id: 'c', text: 'b < c < a', is_correct: false }, { id: 'd', text: 'c < b < a', is_correct: true }], answer: { correct_option: 'd', explanation: 'Aromatic > non-aromatic > anti-aromatic.' }, solution: { text_markdown: `Order: aromatic > non-aromatic > anti-aromatic.\n\nAnswer: **(d)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 12, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },
  
  { _id: uuidv4(), display_id: 'HC-091', question_text: { markdown: `Which reagent promotes the formation of electrophile in nitration of benzene?`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'Lewis base', is_correct: false }, { id: 'b', text: 'Lewis acid', is_correct: true }, { id: 'c', text: 'Bronsted base', is_correct: false }, { id: 'd', text: 'Bronsted acid', is_correct: false }], answer: { correct_option: 'b', explanation: 'Lewis acids promote formation of electrophiles.' }, solution: { text_markdown: `Lewis acids promote the formation of electrophiles not Lewis base.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 10, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  { _id: uuidv4(), display_id: 'HC-092', question_text: { markdown: `Arrange the following in decreasing order of electrophilic substitution:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'a > b > c > d > e', is_correct: false }, { id: 'b', text: 'e > d > a > b > c', is_correct: true }, { id: 'c', text: 'c > b > a > d > e', is_correct: false }, { id: 'd', text: 'd > a > e > c > b', is_correct: false }], answer: { correct_option: 'b', explanation: 'Higher electron density = higher reactivity.' }, solution: { text_markdown: `Electrophilic substitution occurs faster on the ring with E.D.G. group.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 10, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-093', question_text: { markdown: `Which of the following compounds are aromatic?\n\n(A) ![A](image) (B) ![B](image) (C) ![C](image) (D) ![D](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '(B) and (D) only', is_correct: true }, { id: 'b', text: '(A) and (C) only', is_correct: false }, { id: 'c', text: '(A), (B) and (D) only', is_correct: false }, { id: 'd', text: '(B), (C) and (D) only', is_correct: false }], answer: { correct_option: 'a', explanation: 'B and D are aromatic.' }, solution: { text_markdown: `B & D are aromatic.\n\nAnswer: **(a)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 9, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-094', question_text: { markdown: `The number of aromatic compounds among the following is $\\underline{\\hspace{2cm}}$.`, latex_validated: true }, type: 'NVT', options: [], answer: { correct_option: null, numerical_value: 1, explanation: 'Only one aromatic compound.' }, solution: { text_markdown: `The only aromatic compound is pyridine.\n\nAnswer: **1**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 9, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  { _id: uuidv4(), display_id: 'HC-095', question_text: { markdown: `The number of compounds that do not give Friedel Crafts reaction is $\\underline{\\hspace{2cm}}$.`, latex_validated: true }, type: 'NVT', options: [], answer: { correct_option: null, numerical_value: 4, explanation: 'Four compounds do not give Friedel Crafts reaction.' }, solution: { text_markdown: `Compounds which do not give Friedel Crafts reaction are 4 in total.\n\nAnswer: **4**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2019, month: 'April', day: 8, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-096', question_text: { markdown: `The major product of the following reaction is:\n\n![Reaction](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: true }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: false }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'a', explanation: 'Friedel-Crafts alkylation.' }, solution: { text_markdown: `Friedel-Crafts alkylation mechanism.\n\nAnswer: **(a)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2023, month: 'Feb', day: 1, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-097', question_text: { markdown: `Decreasing order of reactivity towards electrophilic substitution is:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'c > b > a > d > e', is_correct: false }, { id: 'b', text: 'e > d > a > b > c', is_correct: true }, { id: 'c', text: 'a > d > e > b > c', is_correct: false }, { id: 'd', text: 'd > a > e > c > b', is_correct: false }], answer: { correct_option: 'b', explanation: 'Higher electron density = higher reactivity.' }, solution: { text_markdown: `Higher the electron density on Benzene Ring, Higher its Reactivity towards electrophilic substitution.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2023, month: 'April', day: 15, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-098', question_text: { markdown: `Given below are two statements:\n\n**Assertion (A):** Benzene is more stable than hypothetical cyclohexatriene.\n\n**Reason (R):** The delocalized π electron cloud is attracted more strongly by nuclei of carbon atoms.\n\nIn the light of the above statements, choose the correct answer:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '(A) is true but (R) is false', is_correct: false }, { id: 'b', text: '(A) is false but (R) is true', is_correct: false }, { id: 'c', text: 'Both (A) and (R) are correct and (R) is the correct explanation of (A)', is_correct: true }, { id: 'd', text: 'Both (A) and (R) are correct but (R) is NOT the correct explanation of (A)', is_correct: false }], answer: { correct_option: 'c', explanation: 'Both are true and R explains A.' }, solution: { text_markdown: `Assertion (A): Benzene is more stable than cyclohexatriene (True) due to aromaticity.\n\nReason (R): Delocalised π-electrons cloud lies B.M.O so more attracted by nuclei of carbon atom. (True & Correct Explanation)\n\nAnswer: **(c)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2023, month: 'Jan', day: 24, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 90 },

  { _id: uuidv4(), display_id: 'HC-099', question_text: { markdown: `The major product 'P' formed in the given reaction is:\n\n![Reaction](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: false }, { id: 'd', text: '![Option D](image)', is_correct: true }], answer: { correct_option: 'd', explanation: 'KMnO₄ oxidizes benzylic carbon to COOH.' }, solution: { text_markdown: `$\\ce{KMnO4}$ is a strong oxidising agent and it oxidises benzylic carbon containing atleast one hydrogen atom to -COOH.\n\nAnswer: **(d)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2023, month: 'April', day: 10, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-100', question_text: { markdown: `Among the following, the aromatic compounds are:\n\n(A) ![A](image) (B) ![B](image) (C) ![C](image) (D) ![D](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '(B), (C) and (D) only', is_correct: false }, { id: 'b', text: '(A) and (B) only', is_correct: false }, { id: 'c', text: '(A), (B) and (C) only', is_correct: false }, { id: 'd', text: '(B) and (C) only', is_correct: true }], answer: { correct_option: 'd', explanation: 'B and C are aromatic.' }, solution: { text_markdown: `B and C are aromatic compounds.\n\nAnswer: **(d)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'March', day: 16, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-101', question_text: { markdown: `Identify correct A, B and C in the reaction sequence:\n\n![Reaction](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: true }, { id: 'c', text: '![Option C](image)', is_correct: false }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'b', explanation: 'Nitration, reduction, diazotization sequence.' }, solution: { text_markdown: `The given reaction occurs as shown.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Hard', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Aug', day: 31, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 80 },

  { _id: uuidv4(), display_id: 'HC-102', question_text: { markdown: `For following sequence of reactions, the correct products are:\n\n![Reaction](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: true }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'c', explanation: 'Grignard reaction sequence.' }, solution: { text_markdown: `The given reaction occurs as shown.\n\nAnswer: **(c)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_4', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Aug', day: 31, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-103', question_text: { markdown: `The correct sequence of reagents used in the preparation of 4-bromo-2-nitroethyl benzene from benzene is:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '$\\ce{HNO3/H2SO4, Br2/AlCl3, CH3COCl/AlCl3, Zn-Hg/HCl}$', is_correct: false }, { id: 'b', text: '$\\ce{CH3COCl/AlCl3, Br2/AlBr3, HNO3/H2SO4, Zn/HCl}$', is_correct: false }, { id: 'c', text: '$\\ce{Br2/AlBr3, CH3COCl/AlCl3, HNO3/H2SO4, Zn/HCl}$', is_correct: false }, { id: 'd', text: '$\\ce{CH3COCl/AlCl3, Zn-Hg/HCl, Br2/AlBr3, HNO3/H2SO4}$', is_correct: true }], answer: { correct_option: 'd', explanation: 'Correct sequence for synthesis.' }, solution: { text_markdown: `The correct sequence of reagents is given.\n\nAnswer: **(d)**`, latex_validated: true }, metadata: { difficulty: 'Hard', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Feb', day: 25, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 80 },

  { _id: uuidv4(), display_id: 'HC-104', question_text: { markdown: `Which one of the following is non-aromatic?`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: true }, { id: 'c', text: '![Option C](image)', is_correct: false }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'b', explanation: 'Conjugation is absent.' }, solution: { text_markdown: `Conjugation is absent in option (b), making it non-aromatic.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Feb', day: 24, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  { _id: uuidv4(), display_id: 'HC-105', question_text: { markdown: `In the following molecule, hybridisation of Carbon a, b and c respectively are:\n\n![Molecule](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '$\\ce{sp^3, sp^2, sp^2}$', is_correct: true }, { id: 'b', text: '$\\ce{sp^3, sp, sp}$', is_correct: false }, { id: 'c', text: '$\\ce{sp^3, sp, sp^2}$', is_correct: false }, { id: 'd', text: '$\\ce{sp^3, sp^2, sp}$', is_correct: false }], answer: { correct_option: 'a', explanation: 'Carbon a, b and c have hybridisation sp³, sp², sp² respectively.' }, solution: { text_markdown: `Carbon a, b and c have hybridisation $\\ce{sp^3, sp^2, sp^2}$, respectively.\n\nAnswer: **(a)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_3', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'March', day: 18, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  { _id: uuidv4(), display_id: 'HC-106', question_text: { markdown: `Which compound forms a yellow precipitate on reacting with (i) NaOH (ii) dil. $\\ce{HNO3}$ (iii) $\\ce{AgNO3}$?`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'II', is_correct: false }, { id: 'b', text: 'IV', is_correct: true }, { id: 'c', text: 'III', is_correct: false }, { id: 'd', text: 'I', is_correct: false }], answer: { correct_option: 'b', explanation: 'Compound IV produces AgI yellow precipitate.' }, solution: { text_markdown: `The compound IV when reacted with given reagents produces Yellow precipitate, $\\ce{AgI(s)}$.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Aug', day: 26, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-107', question_text: { markdown: `Which one of the following is not aromatic?`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: true }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'c', explanation: 'Non-planar shape.' }, solution: { text_markdown: `For a compound to be aromatic, it should be planar, must follow Huckel's rule and should be cyclic. The compound has non-planar shape.\n\nAnswer: **(c)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Aug', day: 26, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  { _id: uuidv4(), display_id: 'HC-108', question_text: { markdown: `Which among the following is the strongest acid?`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '$\\ce{CH3CH2CH2CH3}$', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: true }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'c', explanation: 'Cyclopentadiene is most acidic.' }, solution: { text_markdown: `Higher the acidic strength, higher will be the stability of conjugate base. Cyclopentadiene is the most acidic.\n\nAnswer: **(c)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_3', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'July', day: 25, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-109', question_text: { markdown: `Consider the given reaction, the Product A is:\n\n![Reaction](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: false }, { id: 'c', text: '![Option C](image)', is_correct: true }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'c', explanation: 'Friedel-Crafts acylation.' }, solution: { text_markdown: `The product (A) in the given reaction is formed via Friedel-Crafts acylation.\n\nAnswer: **(c)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_5', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2021, month: 'Aug', day: 26, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  // NOW ADD FIRST 6 MD QUESTIONS AS HC-110 TO HC-115 (2025 questions)
  { _id: uuidv4(), display_id: 'HC-110', question_text: { markdown: `The number of optically active products obtained from the complete ozonolysis of the given compound is:\n\n<smiles>CC=C[C@@H](C)C=C[C@@H](C)C=CC</smiles>`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '2', is_correct: false }, { id: 'b', text: '0', is_correct: true }, { id: 'c', text: '1', is_correct: false }, { id: 'd', text: '4', is_correct: false }], answer: { correct_option: 'b', explanation: 'Ozonolysis products are achiral.' }, solution: { text_markdown: `Ozonolysis breaks double bonds. Products are achiral.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_4', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2025, month: 'April', day: 7, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-111', question_text: { markdown: `Given below are two statements:\n\n**Statement (I):** Cis-dichloroethene is more polar than cis-dibromoethene.\n\n**Statement (II):** Boiling point of trans-dibromoethene is lower than cis-dibromoethene but it is more polar.\n\nIn the light of the above statements, choose the most appropriate answer:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'Statement I is correct but statement II is incorrect', is_correct: true }, { id: 'b', text: 'Statement I is incorrect but statement II is correct', is_correct: false }, { id: 'c', text: 'Both statement I and statement II are incorrect', is_correct: false }, { id: 'd', text: 'Both statement I and statement II are correct', is_correct: false }], answer: { correct_option: 'a', explanation: 'Statement I is correct, Statement II is incorrect.' }, solution: { text_markdown: `Cis-dichloroethene is more polar because Cl has smaller atomic radius and higher electronegativity. Statement I is correct but Statement II is incorrect.\n\nAnswer: **(a)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_2', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2025, month: 'April', day: 7, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 },

  { _id: uuidv4(), display_id: 'HC-112', question_text: { markdown: `Given below are two statements:\n\n**Statement I:** Ozonolysis followed by treatment with $\\ce{Zn, H2O}$ of cis-2-butene gives ethanal.\n\n**Statement II:** The product obtained by ozonolysis followed by treatment with $\\ce{Zn, H2O}$ of 3,6-dimethyloct-4-ene has no chiral carbon atom.\n\nIn the light of the above statements, choose the correct answer:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'Both Statement I and Statement II are true', is_correct: false }, { id: 'b', text: 'Statement I is false but Statement II is true', is_correct: false }, { id: 'c', text: 'Statement I is true but Statement II is false', is_correct: true }, { id: 'd', text: 'Both Statement I and Statement II are false', is_correct: false }], answer: { correct_option: 'c', explanation: 'Statement I is true, Statement II is false.' }, solution: { text_markdown: `Ozonolysis of cis-2-butene gives two ethanal molecules. Statement I: Correct. The product of ozonolysis of 3,6-dimethyloct-4-ene contains a chiral center, hence Statement II is false.\n\nAnswer: **(c)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_4', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2025, month: 'April', day: 7, shift: 'Shift-I' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-113', question_text: { markdown: `The major product formed when the given molecule (X) is treated with HBr (1 eq) is:\n\n![Molecule X](image)`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '![Option A](image)', is_correct: false }, { id: 'b', text: '![Option B](image)', is_correct: true }, { id: 'c', text: '![Option C](image)', is_correct: false }, { id: 'd', text: '![Option D](image)', is_correct: false }], answer: { correct_option: 'b', explanation: 'Markovnikov addition to most stable carbocation.' }, solution: { text_markdown: `Markovnikov addition mechanism.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Medium', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_2', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2025, month: 'April', day: 4, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 85 },

  { _id: uuidv4(), display_id: 'HC-114', question_text: { markdown: `Given below are two statements:\n\n**Statement (I):** Neopentane forms only one monosubstituted derivative.\n\n**Statement (II):** Melting point of neopentane is higher than n-pentane.\n\nIn the light of the above statements, choose the most appropriate answer:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: 'Statement I is correct but Statement II is incorrect', is_correct: false }, { id: 'b', text: 'Both Statement I and Statement II are correct', is_correct: true }, { id: 'c', text: 'Both Statement I and Statement II are incorrect', is_correct: false }, { id: 'd', text: 'Statement I is incorrect but Statement II is correct', is_correct: false }], answer: { correct_option: 'b', explanation: 'Both statements are correct.' }, solution: { text_markdown: `Neopentane forms monosubstituted product due to presence of four identical methyl groups. Since neopentane is more symmetrical than n-pentane, it can pack more efficiently in the crystal lattice. This closer packing results in a higher melting point.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_1', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2025, month: 'April', day: 2, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 90 },

  { _id: uuidv4(), display_id: 'HC-115', question_text: { markdown: `The alkane from below having two secondary hydrogens is:`, latex_validated: true }, type: 'SCQ', options: [{ id: 'a', text: '2,2,4,5-Tetramethylheptane', is_correct: false }, { id: 'b', text: '2,2,3,3-Tetramethylpentane', is_correct: true }, { id: 'c', text: '4-Ethyl-3,4-dimethyloctane', is_correct: false }, { id: 'd', text: '2,2,4,4-Tetramethylhexane', is_correct: false }], answer: { correct_option: 'b', explanation: '2,2,3,3-Tetramethylpentane has 2 secondary H atoms.' }, solution: { text_markdown: `The structure of 2,2,3,3-Tetramethylpentane has 2 secondary H atoms.\n\nAnswer: **(b)**`, latex_validated: true }, metadata: { difficulty: 'Easy', chapter_id: 'ch11_hydrocarbon', tags: [{ tag_id: 'tag_hydrocarbon_1', weight: 1.0 }], is_pyq: true, is_top_pyq: false, exam_source: { exam: 'JEE Main', year: 2025, month: 'Jan', day: 22, shift: 'Shift-II' } }, status: 'published', created_by: 'admin', updated_by: 'admin', created_at: new Date(), updated_at: new Date(), version: 1, deleted_at: null, asset_ids: [], quality_score: 88 }
];

async function run() {
  console.log('\n=== HYDROCARBONS BATCH 4 FINAL: Q93-114 + Q1-6 (HC-088 to HC-115) ===\n');
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    const db = mongoose.connection.db;
    const collection = db.collection('questions_v2');
    
    for (const q of questions) {
      await collection.insertOne(q);
      console.log(`✅ Inserted ${q.display_id} (${q.metadata.exam_source.year})`);
    }
    
    console.log(`\n✅ Successfully inserted ${questions.length} questions (Batch 4 FINAL)`);
    console.log(`🎉 HYDROCARBONS COMPLETE: HC-001 to HC-115 (115 questions total)`);
    console.log(`📊 Breakdown: HC-001 to HC-017 preserved, HC-018 to HC-115 newly ingested`);
  } catch (err) {
    console.error('❌ Error:', err);
  } finally {
    await mongoose.disconnect();
  }
}

run();
