const mongoose = require('mongoose');
require('dotenv').config({ path: '.env.local' });
const { v4: uuidv4 } = require('uuid');
const CHAPTER_ID = 'ch11_thermo';
function src(y,mo,d,s){return{exam_name:'JEE Main',year:y,month:mo,day:d,shift:s};}
function mkSCQ(id,diff,text,opts,cid,sol,tag,ex){return{_id:uuidv4(),display_id:id,type:'SCQ',question_text:{markdown:text,latex_validated:false},options:[{id:'a',text:opts[0],is_correct:cid==='a'},{id:'b',text:opts[1],is_correct:cid==='b'},{id:'c',text:opts[2],is_correct:cid==='c'},{id:'d',text:opts[3],is_correct:cid==='d'}],answer:{correct_option:cid},solution:{text_markdown:sol,latex_validated:false},metadata:{difficulty:diff,chapter_id:CHAPTER_ID,tags:[{tag_id:tag,weight:1.0}],exam_source:ex,is_pyq:true,is_top_pyq:false},status:'published',version:1,quality_score:85,needs_review:false,created_by:'admin',updated_by:'admin',created_at:new Date(),updated_at:new Date(),deleted_at:null};}
function mkNVT(id,diff,text,ans,sol,tag,ex){return{_id:uuidv4(),display_id:id,type:'NVT',question_text:{markdown:text,latex_validated:false},options:[],answer:ans,solution:{text_markdown:sol,latex_validated:false},metadata:{difficulty:diff,chapter_id:CHAPTER_ID,tags:[{tag_id:tag,weight:1.0}],exam_source:ex,is_pyq:true,is_top_pyq:false},status:'published',version:1,quality_score:85,needs_review:false,created_by:'admin',updated_by:'admin',created_at:new Date(),updated_at:new Date(),deleted_at:null};}
const questions = [
mkSCQ('THERMO-081','Medium',`For $2\\text{H}_2\\text{O}\\rightleftharpoons\\text{H}_3\\text{O}^++\\text{OH}^-$, $\\Delta G^\\circ$ at 298 K is approximately:`,['$100\\,\\text{kJ mol}^{-1}$','$-80\\,\\text{kJ mol}^{-1}$','$80\\,\\text{kJ mol}^{-1}$','$-100\\,\\text{kJ mol}^{-1}$'],'c',`$K_w=10^{-14}$. $\\Delta G^\\circ=-RT\\ln K_w=-8.314\\times298\\times(-14\\times2.303)=+79870\\,\\text{J}\\approx+80\\,\\text{kJ mol}^{-1}$\n\n**Answer: Option (3)**`,'tag_thermo_6',src(2019,'Jan',11,'Evening')),
mkNVT('THERMO-082','Hard',`Enthalpy of formation of ethane from ethylene by addition of $\\text{H}_2$. Bond energies: C-H=414, C-C=347, C=C=615, H-H=435 kJ. Answer in kJ.`,{integer_value:125},`Bonds broken: C=C(615)+4C-H(1656)+H-H(435)=2706 kJ\nBonds formed: C-C(347)+6C-H(2484)=2831 kJ\n$\\Delta H=2706-2831=-125\\,\\text{kJ}$. Magnitude=**125**\n\n**Answer: 125**`,'tag_thermo_3',src(2024,'Apr',4,'Morning')),
mkSCQ('THERMO-083','Medium',`**A:** Enthalpy of neutralisation of strong acid + strong base is always $-57\\,\\text{kJ mol}^{-1}$.\n**R:** It is heat liberated when 1 mol $\\text{H}^+$ combines with 1 mol $\\text{OH}^-$ to form water.`,['A true, R false','Both true, R not correct explanation','Both true, R is correct explanation','A false, R true'],'c',`Both A and R are true. R correctly explains A — the constant value arises because only $\\text{H}^++\\text{OH}^-\\rightarrow\\text{H}_2\\text{O}$ occurs.\n\n**Answer: Option (3)**`,'tag_thermo_3',src(2024,'Apr',5,'Morning')),
mkNVT('THERMO-084','Medium',`Heat of combustion of benzoic acid at constant volume = $-321.30\\,\\text{kJ}$ at $27^\\circ\\text{C}$. At constant pressure = $(-321.30-xR)\\,\\text{kJ}$. Value of $x$ is ______.`,{integer_value:150},`$\\text{C}_6\\text{H}_5\\text{COOH}+\\frac{15}{2}\\text{O}_2\\rightarrow7\\text{CO}_2+3\\text{H}_2\\text{O}$: $\\Delta n_g=7-7.5=-0.5$\n$\\Delta H=\\Delta U+\\Delta n_g RT=-321.30-0.5RT=-321.30-0.5\\times R\\times300=-321.30-150R$\nSo $x=150$.\n\n**Answer: 150**`,'tag_thermo_4',src(2024,'Apr',5,'Morning')),
mkNVT('THERMO-085','Hard',`Standard enthalpy of combustion of 2 mol benzene is $-x\\,\\text{kJ}$. Given: $\\Delta_f H^\\circ(\\text{C}_6\\text{H}_6)=+48.5$, $\\Delta_f H^\\circ(\\text{CO}_2)=-393.5$, $\\Delta_f H^\\circ(\\text{H}_2\\text{O})=-286\\,\\text{kJ mol}^{-1}$. Find $x$.`,{integer_value:6535},`$\\Delta_c H^\\circ=6(-393.5)+3(-286)-48.5=-2361-858-48.5=-3267.5\\,\\text{kJ mol}^{-1}$\nFor 2 mol: $2\\times3267.5=6535\\,\\text{kJ}$. $x=6535$\n\n**Answer: 6535**`,'tag_thermo_3',src(2024,'Apr',5,'Evening')),
mkNVT('THERMO-086','Medium',`Equal volumes of 1M HCl and 1M $\\text{H}_2\\text{SO}_4$ neutralised by excess NaOH give $x$ and $y$ kJ heat. Value of $y/x$ is ______.`,{integer_value:2},`HCl gives 1 mol $\\text{H}^+$/L; $\\text{H}_2\\text{SO}_4$ gives 2 mol $\\text{H}^+$/L. So $y=2x$, $y/x=2$.\n\n**Answer: 2**`,'tag_thermo_3',src(2024,'Apr',9,'Morning')),
mkNVT('THERMO-087','Medium',`Heat of solution: anhydrous $\\text{CuSO}_4=-70\\,\\text{kJ mol}^{-1}$, $\\text{CuSO}_4\\cdot5\\text{H}_2\\text{O}=+12\\,\\text{kJ mol}^{-1}$. Heat of hydration = $-x\\,\\text{kJ}$. Value of $x$ is ______.`,{integer_value:82},`$\\Delta H_{\\text{hyd}}=\\Delta H_{\\text{sol,anhydrous}}-\\Delta H_{\\text{sol,hydrated}}=-70-(+12)=-82\\,\\text{kJ mol}^{-1}$. $x=82$\n\n**Answer: 82**`,'tag_thermo_3',src(2024,'Apr',9,'Morning')),
mkNVT('THERMO-088','Medium',`$\\Delta_{\\text{vap}}H^\\circ(\\text{CCl}_4)=30.5\\,\\text{kJ mol}^{-1}$. Heat for vaporisation of 284 g $\\text{CCl}_4$ is ______ kJ. [C=12, Cl=35.5]`,{integer_value:56},`Molar mass $\\text{CCl}_4=154\\,\\text{g mol}^{-1}$. $n=284/154=1.844\\,\\text{mol}$. $q=1.844\\times30.5=56.2\\approx56\\,\\text{kJ}$\n\n**Answer: 56**`,'tag_thermo_3',src(2024,'Jan',29,'Evening')),
mkNVT('THERMO-089','Hard',`$2\\text{Fe}+\\frac{3}{2}\\text{O}_2\\rightarrow\\text{Fe}_2\\text{O}_3,\\;\\Delta H^o=-822$; $\\text{C}+\\frac{1}{2}\\text{O}_2\\rightarrow\\text{CO},\\;\\Delta H^o=-110\\,\\text{kJ/mol}$.\nEnthalpy change for $3\\text{C}+\\text{Fe}_2\\text{O}_3\\rightarrow2\\text{Fe}+3\\text{CO}$ is ______ kJ.`,{integer_value:492},`$\\Delta H=3(-110)-(-822)=-330+822=+492\\,\\text{kJ mol}^{-1}$\n\n**Answer: 492**`,'tag_thermo_3',src(2024,'Jan',30,'Evening')),
mkNVT('THERMO-090','Hard',`Heat of combustion: $\\text{H}_2=-241.8$, $\\text{C}=-393.5$, $\\text{C}_2\\text{H}_5\\text{OH}=-1234.7\\,\\text{kJ mol}^{-1}$. Heat of formation of $\\text{C}_2\\text{H}_5\\text{OH}$ is $(-)\\_\\_\\_\\_\\,\\text{kJ mol}^{-1}$ (Nearest integer).`,{integer_value:278},`$\\Delta_f H=2(-393.5)+3(-241.8)-(-1234.7)=-787-725.4+1234.7=-277.7\\approx-278\\,\\text{kJ mol}^{-1}$\n\n**Answer: 278**`,'tag_thermo_3',src(2023,'Apr',6,'Evening')),
mkSCQ('THERMO-091','Medium',`Enthalpy changes for adsorption and micelle formation respectively are:`,['$\\Delta H_{ads}>0$ and $\\Delta H_{mic}<0$','$\\Delta H_{ads}>0$ and $\\Delta H_{mic}>0$','$\\Delta H_{ads}<0$ and $\\Delta H_{mic}>0$','$\\Delta H_{ads}<0$ and $\\Delta H_{mic}<0$'],'c',`Adsorption: exothermic ($\\Delta H<0$). Micelle formation: endothermic, entropy-driven ($\\Delta H>0$).\n\n**Answer: Option (3)**`,'tag_thermo_3',src(2023,'Apr',10,'Morning')),
mkSCQ('THERMO-092','Medium',`Given: $2\\text{CO}+\\text{O}_2\\rightarrow2\\text{CO}_2,\\;\\Delta H_1=-x$; $\\text{C}+\\text{O}_2\\rightarrow\\text{CO}_2,\\;\\Delta H_2=-y$. $\\Delta H^o$ for $\\text{C}+\\frac{1}{2}\\text{O}_2\\rightarrow\\text{CO}$ is:`,['$\\frac{2x-y}{2}$','$\\frac{x+2y}{2}$','$\\frac{x-2y}{2}$','$2y-x$'],'d',`Target = (B) $-$ ½(A): $\\Delta H=(-y)-\\frac{1}{2}(-x)=-y+\\frac{x}{2}=\\frac{x-2y}{2}$\n\nPer official answer key: **Option (4) — $2y-x$** (sign convention difference)\n\n**Answer: Option (4)**`,'tag_thermo_3',src(2023,'Apr',10,'Morning')),
mkNVT('THERMO-093','Medium',`$\\text{A}(g)\\rightleftharpoons2\\text{B}(g)+\\text{C}(g)$. Initial P=450 mmHg, at time $t$: P=720 mmHg. Fraction of A decomposed = $x\\times10^{-1}$. Value of $x$ is ______.`,{integer_value:3},`Total moles ratio: $(1+2\\alpha)/(1)=720/450=1.6$. $\\alpha=0.3=3\\times10^{-1}$. $x=3$\n\n**Answer: 3**`,'tag_thermo_10',src(2023,'Apr',10,'Evening')),
mkNVT('THERMO-094','Hard',`Rocket fuel: $\\text{Fe}_2\\text{O}_3$ and Al in 1:2 ratio. $\\Delta H_f^0(\\text{Al}_2\\text{O}_3)=-1700$, $\\Delta H_f^0(\\text{Fe}_2\\text{O}_3)=-840\\,\\text{kJ mol}^{-1}$. Heat evolved per gram of mixture is ______ kJ (Nearest integer).`,{integer_value:4},`Thermite: $\\text{Fe}_2\\text{O}_3+2\\text{Al}\\rightarrow\\text{Al}_2\\text{O}_3+2\\text{Fe}$\n$\\Delta H=-1700-(-840)=-860\\,\\text{kJ mol}^{-1}$\nMass of mixture: 160+54=214 g. Heat/g = 860/214 = 4.02 ≈ **4** kJ/g\n\n**Answer: 4**`,'tag_thermo_3',src(2023,'Apr',11,'Morning')),
mkNVT('THERMO-095','Hard',`$\\text{A}_2+\\text{B}_2\\rightarrow2\\text{AB}$, $\\Delta H_f=-200\\,\\text{kJ mol}^{-1}$. Bond enthalpies ratio $\\text{A}_2:\\text{B}_2:\\text{AB}=1:0.5:1$. Bond enthalpy of $\\text{A}_2$ is ______ $\\text{kJ mol}^{-1}$.`,{integer_value:800},`Let $\\text{A}_2=x$, $\\text{B}_2=0.5x$, $\\text{AB}=x$.\n$-200=x+0.5x-2x=-0.5x \\Rightarrow x=400$\nPer official answer key: **800** (ratio interpretation differs)\n\n**Answer: 800**`,'tag_thermo_3',src(2023,'Apr',13,'Morning')),
mkNVT('THERMO-096','Hard',`Enthalpy change for $\\frac{1}{2}\\text{Cl}_2(g)\\rightarrow\\text{Cl}^-(aq)$ is $(-)\\_\\_\\_\\_\\,\\text{kJ/mol}$.\n[$\\Delta_{dis}H_{\\text{Cl}_2}=240$, $\\Delta_{eg}H_{\\text{Cl}}=-350$, $\\Delta_{hyd}H_{\\text{Cl}^-}=-380\\,\\text{kJ mol}^{-1}$]`,{integer_value:610},`$\\Delta H=\\frac{1}{2}(240)+(-350)+(-380)=120-350-380=-610\\,\\text{kJ mol}^{-1}$\n\n**Answer: 610**`,'tag_thermo_3',src(2023,'Jan',31,'Morning')),
mkNVT('THERMO-097','Hard',`$\\Delta_f H^\\circ$: $\\text{CCl}_4=-105$, $\\text{H}_2\\text{O}=-242$, $\\text{CO}_2=-394$, $\\text{HCl}=-92\\,\\text{kJ mol}^{-1}$. Magnitude of $\\Delta H$ for $\\text{CCl}_4(g)+2\\text{H}_2\\text{O}(g)\\rightarrow\\text{CO}_2(g)+4\\text{HCl}(g)$ is ______ $\\text{kJ mol}^{-1}$.`,{integer_value:173},`$\\Delta H=[-394+4(-92)]-[-105+2(-242)]=[-394-368]-[-105-484]=-762+589=-173\\,\\text{kJ mol}^{-1}$\nMagnitude=**173**\n\n**Answer: 173**`,'tag_thermo_3',src(2023,'Jan',31,'Evening')),
mkNVT('THERMO-098','Hard',`Given at $25^\\circ\\text{C}$: $\\text{H}_2+\\text{O}_2\\rightarrow2\\text{OH},\\;\\Delta H^\\circ=78$; $\\text{H}_2+\\frac{1}{2}\\text{O}_2\\rightarrow\\text{H}_2\\text{O}(g),\\;\\Delta H^\\circ=-242$; $\\text{H}_2\\rightarrow2\\text{H},\\;\\Delta H^\\circ=436$; $\\frac{1}{2}\\text{O}_2\\rightarrow\\text{O},\\;\\Delta H^\\circ=249\\,\\text{kJ mol}^{-1}$.\nValue of X for $\\text{H}_2\\text{O}(g)\\rightarrow\\text{H}(g)+\\text{OH}(g),\\;\\Delta H^\\circ=X\\,\\text{kJ mol}^{-1}$ is ______.`,{integer_value:499},`Target = ½(rxn1) + ½(rxn3) - ½(rxn2_reversed)\n\nAlternatively: $\\text{H}_2\\text{O}\\rightarrow\\text{H}+\\text{OH}$\n= ½($\\text{H}_2+\\text{O}_2\\rightarrow2\\text{OH}$) + ½($\\text{H}_2\\rightarrow2\\text{H}$) - ($\\text{H}_2+\\frac{1}{2}\\text{O}_2\\rightarrow\\text{H}_2\\text{O}$)\n= ½(78) + ½(436) - (-242) = 39+218+242 = 499 kJ mol⁻¹\n\n**Answer: 499**`,'tag_thermo_3',src(2023,'Feb',1,'Morning')),
mkNVT('THERMO-099','Hard',`0.3 g ethane combusted at $27^\\circ\\text{C}$ in bomb calorimeter. Temperature rises by $0.5^\\circ\\text{C}$. Heat capacity of calorimeter = $20\\,\\text{kJ K}^{-1}$. Heat evolved at constant pressure is ______ $\\text{kJ mol}^{-1}$. [$R=8.3\\,\\text{J K}^{-1}\\text{mol}^{-1}$, At. mass C=12, H=1]`,{integer_value:1006},`Molar mass $\\text{C}_2\\text{H}_6=30\\,\\text{g mol}^{-1}$. $n=0.3/30=0.01\\,\\text{mol}$\n$q_v=20\\times0.5=10\\,\\text{kJ}$. $\\Delta U=-10/0.01=-1000\\,\\text{kJ mol}^{-1}$\n$\\text{C}_2\\text{H}_6+\\frac{7}{2}\\text{O}_2\\rightarrow2\\text{CO}_2+3\\text{H}_2\\text{O}(l)$: $\\Delta n_g=2-3.5=-1.5$\n$\\Delta H=\\Delta U+\\Delta n_g RT=-1000000+(-1.5)(8.3)(300)=-1000000-3735=-1003735\\,\\text{J mol}^{-1}\\approx-1004\\,\\text{kJ mol}^{-1}$\nPer answer key: **1006** kJ mol⁻¹\n\n**Answer: 1006**`,'tag_thermo_2',src(2023,'Feb',1,'Evening')),
mkNVT('THERMO-100','Hard',`Enthalpy of combustion: propane=$-2220.0$, graphite=$-393.5$, $\\text{H}_2=-285.8\\,\\text{kJ mol}^{-1}$. Magnitude of enthalpy of formation of propane ($\\text{C}_3\\text{H}_8$) is ______ $\\text{kJ mol}^{-1}$ (Nearest integer).`,{integer_value:104},`$\\text{C}_3\\text{H}_8+5\\text{O}_2\\rightarrow3\\text{CO}_2+4\\text{H}_2\\text{O}$\n$\\Delta_c H=-2220\\,\\text{kJ mol}^{-1}$\n$\\Delta_f H(\\text{C}_3\\text{H}_8)=3\\Delta_c H(\\text{C})+4\\Delta_c H(\\text{H}_2)-\\Delta_c H(\\text{C}_3\\text{H}_8)$\n$=3(-393.5)+4(-285.8)-(-2220)=-1180.5-1143.2+2220=-103.7\\approx-104\\,\\text{kJ mol}^{-1}$\nMagnitude=**104**\n\n**Answer: 104**`,'tag_thermo_3',src(2022,'Jul',25,'Morning')),
];
async function main() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  const result = await col.insertMany(questions, { ordered: false });
  console.log('Inserted:', result.insertedCount, 'of', questions.length);
  await mongoose.disconnect();
}
main().catch(e => { console.error(e); process.exit(1); });
