'use strict';
/**
 * Page 6 — simplify the language in the bidirectional stress-breathing beat just
 * added (founder: "keep the language simple" — a standing rule, see
 * feedback_plain_english memory). Cuts writerly/abstract phrasing: "reporting
 * your state", "hijack", "the wire runs both ways", "whether you notice it or
 * not", "That is not a coincidence" → plain, concrete, spoken-register wording.
 *
 * Matches blocks by CONTENT (not saved ids — this script didn't record the
 * uuids generated by the previous insert script), so it's independent of the
 * earlier script's run. Text-only edits; 0 blocks removed/added; no
 * content-loss guard needed.
 *
 * Run: node scripts/lifeskills_focus_page6_simplify.js [--dry]
 */
require('dotenv').config({ path: '.env.local' });
const bw = require('./lib/book-writer');

const BOOK_SLUG = 'life-skills-class-9';
const SLUG = 'breath-the-remote-control';
const DRY = process.argv.includes('--dry');

const NEW_TEXT_MARKDOWN =
  "At first, this looks like a one-way trick: press a button (breathe slowly) and the alarm quiets down. But look closer — it's actually a **two-way street**.\n\n" +
  "Your breathing already shows how you feel, even when you don't notice it. Feel anxious, nervous, or under pressure, and your breathing goes " +
  '**shallow and fast, high in the chest** — small sips of air, because your body is bracing, not settling. Feel calm, relaxed, happy, or deeply ' +
  "focused, and your breathing goes **slow, deep, and steady, low in the belly** — because there's nothing to brace against.\n\n" +
  "So stress can take over your breath. And because it works both ways, your **breath can take over your stress right back**. That's the whole trick " +
  'behind the pattern below.';

const NEW_OPTIONS = {
  Excited: "Excitement makes you breathe faster too — but it usually stays light and doesn't get stuck in your chest. Fast breathing isn't the problem; tight, shallow breathing is.",
  Sad: 'Sadness often brings slow, heavy breathing with long sighs. Your body reaches for that calm, long breath out before your mind even decides to.',
  Relaxed: 'Slow, deep, even, low in the belly — you barely notice it, because nothing is bracing for anything. This is the exact pattern the 4-4-6 below is trying to copy on purpose.',
  Happy: "Usually easy and full, sometimes with a big sigh — or a laugh (laughing is really just short bursts of breathing out). Your breath opens up when there's nothing to guard against.",
  Stressed: 'Fast, shallow, high in the chest — small sips of air instead of full breaths. Your body is bracing, not settling. This is the exact moment the 4-4-6 is built for.',
};

const NEW_COMPLETION_NOTE =
  "Notice the pattern: when you're calm, breathing goes low and slow. When you're stressed, it goes high and fast — often before you even realise you're " +
  'stressed. That makes your breath an early-warning system. Catch the fast, high pattern, and you already have your tool: the 4-4-6 below.';

const NEW_QUIZ_Q = "Which pattern usually shows up when you're anxious or under pressure — often before you even notice you're stressed?";
const NEW_QUIZ_EXPLANATION =
  "Stress shows up in your breath first — fast, shallow, high in the chest — often before you even notice you're stressed. That's why your breath works as an early-warning system.";

async function main() {
  await bw.withDb(async (db) => {
    const book = await db.collection('books').findOne({ slug: BOOK_SLUG });
    if (!book) throw new Error(`book ${BOOK_SLUG} not found`);
    const page = await db.collection('book_pages').findOne({ book_id: String(book._id), slug: SLUG });
    if (!page) throw new Error(`page ${SLUG} not found`);

    let textFixed = false, expFixed = false, quizFixed = false;
    const out = page.blocks.map((b) => {
      if (b.type === 'text' && typeof b.markdown === 'string' && b.markdown.startsWith('So far this looks like a one-way trick')) {
        textFixed = true;
        return { ...b, markdown: NEW_TEXT_MARKDOWN };
      }
      if (b.type === 'self_experiment' && b.title === 'Catch Your Breath') {
        expFixed = true;
        return {
          ...b,
          options: b.options.map((o) => (NEW_OPTIONS[o.label] ? { ...o, explanation: NEW_OPTIONS[o.label] } : o)),
          completion_note: NEW_COMPLETION_NOTE,
        };
      }
      if (b.type === 'inline_quiz') {
        const idx = b.questions.findIndex((q) => q.question.startsWith("Which pattern usually shows up when you're anxious or under pressure — often before you've"));
        if (idx === -1) return b;
        quizFixed = true;
        const questions = [...b.questions];
        questions[idx] = { ...questions[idx], question: NEW_QUIZ_Q, explanation: NEW_QUIZ_EXPLANATION };
        return { ...b, questions };
      }
      return b;
    });
    if (!textFixed) throw new Error('two-way-street text block not found');
    if (!expFixed) throw new Error('"Catch Your Breath" self_experiment block not found');
    if (!quizFixed) throw new Error('new quiz question not found');

    const res = await bw.savePage(db, { pageId: page._id }, out, {
      author: 'agent',
      summary: 'page 6: simplify language on the two-way stress-breathing beat + Catch Your Breath + quiz Q (plain classroom English)',
      dryRun: DRY,
    });
    console.log(DRY
      ? `[dry] ${SLUG}: removed=${res.diff.removedBlockIds.length} added=${res.diff.addedBlockIds.length} (expect 0/0 — text-only)`
      : `✓ ${SLUG}: v${res.version} · language simplified`);
  });
  console.log(DRY ? '\n[dry] no writes.' : '\n✅ Page 6 language simplified.');
}
main().catch((e) => { console.error('❌', e.message); process.exit(1); });
