'use strict';
/**
 * livebooks-state.js
 *
 * Regenerates the DB-state inventory inside _agents/state/LIVE_BOOKS_STATE.md.
 *
 * Reads the `books` + `book_pages` collections and rewrites ONLY the region
 * between the <!-- AUTO:BEGIN --> / <!-- AUTO:END --> markers. Everything else
 * in the file (header, Changelog) is preserved untouched. If the file does not
 * exist yet, a full scaffold (header + empty Changelog) is created.
 *
 * Run after ANY Live Books content change (new pages, Hinglish, publish toggle,
 * chapter restructure), then add a dated line to the Changelog by hand.
 *
 * Run: node scripts/livebooks-state.js
 */
const dotenv = require('dotenv');
dotenv.config({ path: '.env.local' });
const fs = require('fs');
const path = require('path');
const { MongoClient } = require('mongodb');

const OUT = path.join(__dirname, '..', '_agents', 'state', 'LIVE_BOOKS_STATE.md');
const AUTO_BEGIN = '<!-- AUTO:BEGIN — generated by scripts/livebooks-state.js; do not edit by hand -->';
const AUTO_END = '<!-- AUTO:END -->';

function scaffold(autoBlock, today) {
  return `# Live Books — Project State

> **Single source of truth for what content exists in the Live Books database.**
> Read this at the start of any Live Books task instead of re-querying Mongo from
> scratch. The inventory below is generated from the \`crucible\` DB
> (\`books\` + \`book_pages\`), so it reflects real state, not intentions.
>
> **Keep this current.** After any change to book/page content — new pages,
> Hinglish blocks, publish toggles, chapter restructure — run
> \`node scripts/livebooks-state.js\` to refresh the inventory, then add one dated
> line to the Changelog at the bottom. The script only rewrites the AUTO region;
> it never touches the Changelog.

${AUTO_BEGIN}
${autoBlock}
${AUTO_END}

## Changelog

<!-- Newest first. One line per change: \`- YYYY-MM-DD — what changed (book / chapter / pages)\`. -->

- ${today} — Initial state file created.
`;
}

// Escape characters that would break a markdown table cell.
function cell(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|');
}

function buildAutoBlock(books, pagesByBook, today) {
  const lines = [];
  lines.push(`_Last regenerated: ${today}_`);
  lines.push('');
  lines.push('Legend: **Pages** = pages wired into the chapter · **Pub** = published/total · **Hinglish** = pages with a Hinglish twin/total · stub = page with 0 text blocks.');
  lines.push('');

  for (const book of books) {
    const pages = pagesByBook.get(book._id) || new Map();
    const chapters = (book.chapters || []).slice().sort((a, b) => a.number - b.number);

    let totPages = 0, totPub = 0, totH = 0;
    const rows = [];
    const notes = [];

    for (const ch of chapters) {
      const ids = ch.page_ids || [];
      if (ids.length === 0) {
        rows.push({ num: ch.number, title: ch.title, pages: 0, pub: 0, h: 0, stubs: 0, empty: true });
        continue;
      }
      let pub = 0, h = 0, stubs = 0;
      const hSlugs = [];
      for (const id of ids) {
        const p = pages.get(id);
        if (!p) { stubs++; continue; }
        const textN = (p.blocks || []).filter(b => b.type === 'text').length;
        const hN = (p.hinglish_blocks || []).length;
        if (textN === 0) stubs++;
        if (p.published) pub++;
        if (hN > 0) { h++; hSlugs.push(p.slug); }
      }
      rows.push({ num: ch.number, title: ch.title, pages: ids.length, pub, h, stubs, empty: false });
      totPages += ids.length; totPub += pub; totH += h;
      // List slugs only when Hinglish is partial — full/none is clear from the count.
      if (h > 0 && h < ids.length) notes.push(`  - Ch${ch.number} Hinglish pages: ${hSlugs.join(', ')}`);
    }

    const titleClean = book.title;
    lines.push(`### ${titleClean}  \`${book.slug}\` · ${book.subject || '?'}`);
    lines.push(`Totals: ${totPages} pages · ${totPub}/${totPages} published · ${totH}/${totPages} with Hinglish`);
    lines.push('');
    lines.push('| Ch | Title | Pages | Pub | Hinglish | Stubs |');
    lines.push('|---|---|---|---|---|---|');
    for (const r of rows) {
      if (r.empty) {
        lines.push(`| ${r.num} | ${cell(r.title)} | — | — | — | — |`);
      } else {
        lines.push(`| ${r.num} | ${cell(r.title)} | ${r.pages} | ${r.pub}/${r.pages} | ${r.h}/${r.pages} | ${r.stubs || ''} |`);
      }
    }
    if (notes.length) {
      lines.push('');
      lines.push('Partial-Hinglish detail:');
      lines.push(...notes);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

async function main() {
  const client = new MongoClient(process.env.MONGODB_URI);
  await client.connect();
  const db = client.db('crucible');

  // Order books for stable output: by subject then title.
  const books = await db.collection('books').find({}).toArray();
  books.sort((a, b) => (a.title || '').localeCompare(b.title || ''));

  const pagesByBook = new Map();
  for (const book of books) {
    const ids = (book.chapters || []).flatMap(c => c.page_ids || []);
    const docs = ids.length
      ? await db.collection('book_pages')
          .find({ _id: { $in: ids } })
          .project({ slug: 1, page_number: 1, title: 1, published: 1, hinglish_blocks: 1, blocks: 1 })
          .toArray()
      : [];
    pagesByBook.set(book._id, new Map(docs.map(d => [d._id, d])));
  }
  await client.close();

  const today = new Date().toISOString().slice(0, 10);
  const autoBlock = buildAutoBlock(books, pagesByBook, today);

  fs.mkdirSync(path.dirname(OUT), { recursive: true });

  if (!fs.existsSync(OUT)) {
    fs.writeFileSync(OUT, scaffold(autoBlock, today));
    console.log(`Created ${path.relative(path.join(__dirname, '..'), OUT)} (scaffold + inventory).`);
    return;
  }

  const existing = fs.readFileSync(OUT, 'utf8');
  const begin = existing.indexOf(AUTO_BEGIN);
  const end = existing.indexOf(AUTO_END);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error('AUTO markers not found or malformed in LIVE_BOOKS_STATE.md — refusing to overwrite.');
  }
  const updated =
    existing.slice(0, begin + AUTO_BEGIN.length) + '\n' + autoBlock + '\n' + existing.slice(end);
  fs.writeFileSync(OUT, updated);
  console.log(`Refreshed inventory in ${path.relative(path.join(__dirname, '..'), OUT)} (Changelog preserved).`);
}

main().catch(err => { console.error(err); process.exit(1); });
