// POC Fix Batch 1a: POC-001 to POC-005
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');

const fixes = [
  {
    id: 'POC-001',
    q: `Match List-I with List-II.\n\n| | List-I (Purification technique) | | List-II (Mixture of organic compounds) |\n|---|---|---|---|\n| A | Distillation (simple) | I | Diesel + Petrol |\n| B | Fractional distillation | II | Aniline + Water |\n| C | Distillation under reduced pressure | III | Chloroform + Aniline |\n| D | Steam distillation | IV | Glycerol + Spent-lye |\n\nChoose the correct answer from the options given below:`,
    sol: `**Step 1: Understand Each Purification Technique**\n\n- **Simple Distillation:** Used when boiling point difference > 25°C between two components\n- **Fractional Distillation:** Used when boiling point difference < 25°C; requires a fractionating column\n- **Vacuum Distillation:** Used when the compound decomposes at its normal boiling point\n- **Steam Distillation:** Used for steam-volatile, water-immiscible compounds; mixture boils below 100°C\n\n**Step 2: Analyse Each Mixture**\n\n- **CHCl₃ + Aniline:** Chloroform bp = 61°C, Aniline bp = 184°C → difference = 123°C (> 25°C) → Simple distillation ✅\n- **Diesel + Petrol:** Both are petroleum fractions with close boiling points → Fractional distillation ✅\n- **Glycerol + Spent-lye:** Glycerol bp = 290°C, decomposes at that temperature → Vacuum distillation ✅\n- **Aniline + Water:** Aniline is steam-volatile (bp 184°C) and water-immiscible → Steam distillation ✅\n\n**Step 3: Build the Match**\n\n| List-I | List-II |\n|---|---|\n| A — Distillation (simple) | III — Chloroform + Aniline |\n| B — Fractional distillation | I — Diesel + Petrol |\n| C — Distillation under reduced pressure | IV — Glycerol + Spent-lye |\n| D — Steam distillation | II — Aniline + Water |\n\n**Step 4: Conclusion**\n\nCorrect match: **(A)-(III), (B)-(I), (C)-(IV), (D)-(II)** → **Answer: (d)**\n\n**Key Points to Remember:**\n- Simple distillation criterion: bp difference > 25°C\n- Fractional distillation criterion: bp difference < 25°C, uses fractionating column\n- Glycerol (triol, bp 290°C) is always purified by vacuum distillation — it is heat-sensitive\n- Steam distillation requires both: steam-volatile AND water-immiscible`
  },
  {
    id: 'POC-002',
    q: `Match List-I with List-II.\n\n| | List-I (Separation of) | | List-II (Separation Technique) |\n|---|---|---|---|\n| A | Aniline from aniline-water mixture | I | Simple distillation |\n| B | Glycerol from spent-lye in soap industry | II | Fractional distillation |\n| C | Different fractions of crude oil in petroleum industry | III | Distillation at reduced pressure |\n| D | Chloroform-Aniline mixture | IV | Steam distillation |\n\nChoose the correct answer from the options given below:`,
    sol: `**Step 1: Key Properties of Each Mixture**\n\n- **Aniline + Water:** Aniline (bp 184°C) is steam-volatile and immiscible with water\n- **Glycerol from spent-lye:** Glycerol bp = 290°C; decomposes at its normal bp\n- **Crude oil fractions:** Contains hundreds of hydrocarbons with bp ranging from 20°C to 400°C\n- **Chloroform + Aniline:** CHCl₃ bp = 61°C, Aniline bp = 184°C → difference = 123°C\n\n**Step 2: Select the Correct Technique for Each**\n\n**(A) Aniline + Water → (IV) Steam distillation**\n$$P_{\\text{total}} = P_{\\text{aniline}} + P_{\\text{water}} = P_{\\text{atm}}$$\nMixture boils at ~98°C (below 100°C). After condensation, aniline separates from water (immiscible).\n\n**(B) Glycerol from spent-lye → (III) Distillation at reduced pressure**\nReducing pressure lowers bp from 290°C to ~150°C, preventing decomposition of glycerol.\n\n**(C) Crude oil fractions → (II) Fractional distillation**\nIndustrial fractionating tower separates: petroleum gas (<40°C), petrol (40–180°C), kerosene (180–250°C), diesel (250–350°C).\n\n**(D) Chloroform–Aniline → (I) Simple distillation**\nLarge bp difference (123°C > 25°C) → single distillation step is sufficient.\n\n**Step 3: Match Table**\n\n| List-I | List-II |\n|---|---|\n| A | IV |\n| B | III |\n| C | II |\n| D | I |\n\n**Step 4: Conclusion**\n\nAnswer: **(A)-(IV), (B)-(III), (C)-(II), (D)-(I)** → **Option (a)**\n\n**Key Points to Remember:**\n- Aniline + water → steam distillation; Aniline + chloroform → simple distillation (key distinction!)\n- Glycerol always requires vacuum distillation (heat-sensitive triol)\n- Crude oil separation is the most important industrial application of fractional distillation\n- Multiple small-volume extractions more efficient than one large extraction (for differential extraction)`
  },
  {
    id: 'POC-003',
    sol: `**Step 1: Identify the Physical Transformation**\n\nThe diagram shows the sequence: **Solid → (on heating) → Vapour → (on cooling) → Solid**\n\nThis is a direct solid ↔ vapour transition with **no liquid phase** involved at any stage.\n\n**Step 2: Identify the Purification Technique**\n\nThis is **Sublimation** — the process in which a solid directly converts to vapour on heating, and the vapour directly converts back to solid on cooling, completely bypassing the liquid state.\n\n**Step 3: Compare with Other Techniques**\n\n| Technique | Phase Transitions |\n|---|---|\n| **Sublimation** ✅ | Solid ↔ Vapour (no liquid intermediate) |\n| Crystallisation ❌ | Solid dissolves in liquid → recrystallises on cooling |\n| Extraction ❌ | Transfer of compound between two immiscible liquid solvents |\n| Distillation ❌ | Liquid → Vapour → Liquid (liquid phase essential) |\n\n**Step 4: How Sublimation Works in Practice**\n\n1. The impure solid is heated in a sublimation apparatus\n2. The substance with appreciable vapour pressure converts to vapour\n3. Vapour passes to the cold finger (cooler surface) above\n4. Pure sublimate collects on the cold surface\n5. Non-sublimable impurities remain as residue\n\n**Answer: (a) Sublimation**\n\n**Key Points to Remember:**\n- Sublimation requires the compound to have significant vapour pressure below its melting point\n- Impurities must NOT sublime — this is the basis of purification\n- Substances that sublime: camphor, naphthalene, iodine, benzoic acid, ammonium chloride, anthracene\n- A cold finger is used to collect the pure sublimate`
  },
  {
    id: 'POC-004',
    sol: `**Step 1: Analyse Statement I**\n\n*"In partition chromatography, the stationary phase is a thin film of liquid present in the inert support."*\n\n✅ **TRUE** — In partition chromatography, the stationary phase is a liquid film (e.g., water) coated on an inert solid support. The mobile phase is also a liquid. Separation occurs due to differential distribution (partitioning) of solutes between the two liquid phases.\n\n**Step 2: Analyse Statement II**\n\n*"In paper chromatography, the material of paper acts as a stationary phase."*\n\n✅ **TRUE** — Cellulose fibres of the paper absorb water in their pores, and this water film serves as the stationary phase. The paper physically supports this stationary liquid. It is correct to say "paper acts as the stationary phase" in this context.\n\n**Step 3: Compare Adsorption vs Partition Chromatography**\n\n| Feature | Adsorption Chromatography | Partition Chromatography |\n|---|---|---|\n| Stationary phase | Solid (silica gel, alumina) | Liquid film on solid support |\n| Principle | Differential adsorption | Differential partitioning |\n| Examples | Column chromatography, TLC | Paper chromatography |\n\n**Step 4: Conclusion**\n\nBoth Statement I and Statement II are true → **Option (d)**\n\n**Key Points to Remember:**\n- Paper chromatography = partition chromatography (NOT adsorption chromatography)\n- Stationary phase in paper chromatography = water held in cellulose fibres\n- Mobile phase moves by capillary action (ascending paper chromatography)\n- $R_f = \\frac{\\text{Distance moved by compound}}{\\text{Distance moved by solvent front}}$ (always 0 to 1)`
  },
  {
    id: 'POC-005',
    sol: `**Step 1: Define the Two Key Requirements**\n\nA "steam volatile, water-immiscible substance" has:\n1. **Steam volatile** — appreciable vapour pressure; can vaporise along with steam\n2. **Water-immiscible** — does not dissolve in water; separates as a distinct layer after condensation\n\n**Step 2: Evaluate Each Technique**\n\n| Technique | Based On | Suitable? |\n|---|---|---|\n| Fractional distillation | Close boiling points of miscible liquids | ❌ |\n| Fractional distillation under reduced pressure | High-bp, heat-sensitive miscible liquids | ❌ |\n| Distillation | Boiling point differences between miscible/single-component liquids | ❌ |\n| Steam distillation | Steam-volatile + water-immiscible compounds | ✅ |\n\n**Step 3: Principle of Steam Distillation**\n\n$$P_{\\text{total}} = P_{\\text{organic}} + P_{\\text{water}} = P_{\\text{atm}}$$\n\nThe mixture boils at a temperature **below 100°C**, regardless of the individual boiling points. This prevents thermal decomposition of heat-sensitive organic compounds.\n\nAfter condensation, the two immiscible layers separate — the organic compound is collected from the organic layer using a separating funnel.\n\n**Step 4: Conclusion**\n\nAnswer: **(d) Steam distillation**\n\n**Key Points to Remember:**\n- Both conditions essential: steam-volatile AND water-immiscible\n- Examples: aniline (bp 184°C), nitrobenzene, turpentine oil, essential oils\n- Distillation temperature always < 100°C in steam distillation\n- Recovery: condensate collected → layers separated using separating funnel`
  }
];

async function runFix() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  for (const f of fixes) {
    const update = { $set: {} };
    if (f.q) update.$set['question_text.markdown'] = f.q;
    if (f.sol) update.$set['solution.text_markdown'] = f.sol;
    if (f.difficulty) update.$set['metadata.difficulty'] = f.difficulty;
    const res = await col.updateOne({ display_id: f.id }, update);
    console.log(`${f.id}: matched=${res.matchedCount}, modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log('Done batch 1a');
}
runFix().catch(e => { console.error(e); process.exit(1); });
