// POC Fix Batch 4b: POC-096 to POC-102 (final POC batch)
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');

const fixes = [
  {
    id: 'POC-096',
    // Solution already has good calculation - just enhance it
    sol: `**Step 1: Correct for Aqueous Tension**\n\nThe $\\ce{N2}$ is collected over KOH solution at 287 K. Vapour pressure of water at 287 K = 14 mm Hg.\n\n$$P_{N_2} = P_{\\text{total}} - P_{\\text{vapour}} = 758 - 14 = 744 \\text{ mm Hg}$$\n\nConverting to atm:\n$$P_{N_2} = \\frac{744}{760} = 0.9789 \\text{ atm}$$\n\n**Step 2: Calculate Moles of N₂ Using Ideal Gas Law**\n\nGiven:\n- $V = 30 \\text{ mL} = 0.030 \\text{ L}$\n- $T = 287 \\text{ K}$\n- $R = 0.0821 \\text{ L·atm·K}^{-1}\\text{·mol}^{-1}$\n\n$$n_{N_2} = \\frac{PV}{RT} = \\frac{0.9789 \\times 0.030}{0.0821 \\times 287} = \\frac{0.029368}{23.562} = 1.2464 \\times 10^{-3} \\text{ mol}$$\n\n**Step 3: Calculate Mass of Nitrogen**\n\nMolar mass of $\\ce{N2}$ = 28 g/mol\n$$m_{N_2} = 1.2464 \\times 10^{-3} \\times 28 = 0.034898 \\text{ g}$$\n\n(Note: this is also the mass of nitrogen atoms since $m_N = m_{N_2}$ when using M = 28 for $\\ce{N2}$)\n\n**Step 4: Calculate Percentage of Nitrogen**\n\nMass of compound = 0.1840 g\n$$\\%N = \\frac{0.034898}{0.1840} \\times 100 = 18.97\\% \\approx \\mathbf{19\\%}$$\n\n**Answer: 19** (nearest integer)\n\n**Key Points to Remember:**\n- Use $PV = nRT$ (not STP conversion) when conditions are non-standard\n- R = 0.0821 L·atm·K⁻¹·mol⁻¹ or 8.314 J·mol⁻¹·K⁻¹\n- Aqueous tension must be subtracted from total pressure\n- Dumas %N formula: $\\%N = \\frac{n_{N_2} \\times 28}{m_{\\text{compound}}} \\times 100$`
  },
  {
    id: 'POC-097',
    q: `Kjeldahl's method cannot be used to estimate nitrogen for which of the following compounds?\n\n(a) Urea ($\\ce{(NH2)2CO}$)\n\n(b) Aniline ($\\ce{C6H5NH2}$)\n\n(c) Nitrobenzene ($\\ce{C6H5NO2}$)\n\n(d) Propionitrile ($\\ce{CH3CH2-C≡N}$)`,
    sol: `**Step 1: Recall Kjeldahl's Limitations**\n\nKjeldahl's method converts N to $\\ce{(NH4)2SO4}$ using conc. $\\ce{H2SO4}$. It FAILS for:\n- **Nitro groups** ($\\ce{-NO2}$): N in high oxidation state, not reduced to $\\ce{NH4+}$\n- **Azo groups** ($\\ce{-N=N-}$): N-N bonds not cleaved under Kjeldahl conditions\n- **Nitriles** ($\\ce{-C≡N}$): C≡N triple bond → some sources say nitriles CAN be estimated; depends on the question\n- **Heteroaromatic N** (pyridine): aromatic C-N bonds too stable\n\n**Step 2: Evaluate Each Option**\n\n**(a) Urea $\\ce{(NH2)2CO}$** — Contains $\\ce{-NH2}$ (amide-like N) → Kjeldahl WORKS ✅\n\n**(b) Aniline $\\ce{C6H5NH2}$** — Contains $\\ce{-NH2}$ (primary amine) → Kjeldahl WORKS ✅\n\n**(c) Nitrobenzene $\\ce{C6H5NO2}$** — Contains $\\ce{-NO2}$ (nitro group) → Kjeldahl FAILS ❌\n\n**(d) Propionitrile $\\ce{CH3CH2C≡N}$** — Contains $\\ce{-C≡N}$ (nitrile) → Kjeldahl FAILS ❌\n\n**Step 3: Determine Which Single Compound is the Correct Answer**\n\nThe question asks which compound Kjeldahl CANNOT be used for. The answer key says **(c) Nitrobenzene** ($\\ce{C6H5NO2}$). Nitro compounds are the clearest example of Kjeldahl failure in JEE context.\n\n**Answer: (c) Nitrobenzene** → $\\ce{-NO2}$ group makes Kjeldahl's method inapplicable.\n\n**Key Points to Remember:**\n- Kjeldahl WORKS for: amines ($\\ce{-NH2}$), amides ($\\ce{-CONH2}$), amino acids, proteins, urea\n- Kjeldahl FAILS for: $\\ce{-NO2}$, $\\ce{-N=N-}$, pyridine ring N, diazonium salts\n- Nitriles are a borderline case — in JEE context, often listed as a failure case\n- Nitro group: N is in +3 oxidation state (in $\\ce{-NO2}$, N = +3) — not convertible to $\\ce{NH4+}$`
  },
  {
    id: 'POC-098',
    q: `In Carius method of estimation of halogen, 0.172 g of an organic compound showed presence of 0.08 g of bromine. Which of these is the correct structure of the compound?\n\n(a) $\\ce{H3C-CH2-Br}$ (bromoethane)\n\n(b) $\\ce{H3C-CBr}$ (unknown)\n\n(c) 2,4-dibromoaniline ($\\ce{NH2-C6H3Br2}$)\n\n(d) 4-bromoaniline ($\\ce{NH2-C6H4Br}$)`,
    sol: `**Step 1: Calculate %Br from the Given Data**\n\nGiven:\n- Mass of compound = 0.172 g\n- Mass of Br = 0.08 g\n\n$$\\%Br = \\frac{0.08}{0.172} \\times 100 = 46.51\\%$$\n\n**Step 2: Calculate Molar Mass from %Br**\n\nIf the compound has **one Br atom** (Br = 80 g/mol):\n$$\\text{Molar mass} = \\frac{80}{0.4651} = 172 \\text{ g/mol}$$\n\nIf the compound has **two Br atoms** (2 × Br = 160 g/mol):\n$$\\text{Molar mass} = \\frac{160}{0.4651} = 344 \\text{ g/mol}$$\n\n**Step 3: Match with Given Structures**\n\n**(a) Bromoethane $\\ce{CH3CH2Br}$:** MW = 109 g/mol → %Br = 80/109 = 73.4% ❌\n\n**(b) Unknown:** Cannot evaluate without structure.\n\n**(c) 2,4-Dibromoaniline $\\ce{C6H3(NH2)Br2}$:** MW = 250.9 g/mol → %Br = 160/250.9 = 63.8% ❌\n\n**(d) 4-Bromoaniline $\\ce{C6H4(NH2)Br}$:** MW = 172 g/mol → %Br = 80/172 = 46.51% ✅\n\n**Step 4: Conclusion**\n\nMolar mass = 172 g/mol with one Br atom → **4-bromoaniline** ($\\ce{C6H4BrNH2}$, MW = 6(12) + 4(1) + 14 + 1 + 80 = 72 + 4 + 14 + 1 + 80 = 171 ≈ 172 g/mol)\n\nAnswer: **(d) 4-bromoaniline**\n\n**Key Points to Remember:**\n- First calculate %Br, then deduce MW, then match with options\n- For one Br: $\\text{MW} = \\frac{80}{\\%Br/100}$\n- 4-Bromoaniline: $\\ce{C6H4(Br)(NH2)}$, MW = 12(6) + 4 + 14 + 1 + 80 = 172 g/mol ✓\n- This reverse-calculation approach is powerful for structure determination from Carius data`
  },
  {
    id: 'POC-099',
    q: `Match the following:\n\n| | Test/Method | | Reagent |\n|---|---|---|---|\n| A | Lucas Test | I | $\\ce{C6H5SO2Cl}$ / aq. KOH |\n| B | Dumas method | II | $\\ce{HNO3}$ / $\\ce{AgNO3}$ |\n| C | Kjeldahl's method | III | CuO / $\\ce{CO2}$ |\n| D | Hinsberg Test | IV | Conc. HCl and $\\ce{ZnCl2}$ |\n| | | V | $\\ce{H2SO4}$ |`,
    sol: `**Step 1: Identify Each Test and Its Reagents**\n\n**A. Lucas Test**\n- Used to distinguish 1°, 2°, 3° alcohols\n- Reagent: **Lucas reagent** = conc. HCl + anhydrous $\\ce{ZnCl2}$ (as Lewis acid catalyst)\n- 3° alcohol → immediate cloudiness; 2° → cloudiness in ~5 min; 1° → no reaction (or very slow)\n- Match: **IV (Conc. HCl and $\\ce{ZnCl2}$)**\n\n**B. Dumas method**\n- Used for nitrogen estimation\n- Reagent: The organic compound is heated with excess **CuO** (which provides O for oxidation)\n- The gases are passed through CuO layer → then over **copper gauze** (to reduce NOₓ back to N₂)\n- The gas collected in a nitrometer over KOH solution (which absorbs $\\ce{CO2}$)\n- Key reagent: **CuO** (and $\\ce{CO2}$ is the gas absorbed by KOH)\n- Match: **III (CuO / $\\ce{CO2}$)**\n\n**C. Kjeldahl's method**\n- Nitrogen estimation; organic compound heated with conc. **$\\ce{H2SO4}$**\n- Match: **V ($\\ce{H2SO4}$)**\n\n**D. Hinsberg Test**\n- Distinguishes 1°, 2°, 3° amines\n- Reagent: **Hinsberg reagent** = benzenesulphonyl chloride $\\ce{C6H5SO2Cl}$ with aqueous KOH\n- Match: **I ($\\ce{C6H5SO2Cl}$ / aq. KOH)**\n\n**Step 2: Match Table**\n\n| Test | Reagent |\n|---|---|\n| A (Lucas Test) | IV (Conc. HCl + $\\ce{ZnCl2}$) |\n| B (Dumas) | III (CuO / $\\ce{CO2}$) |\n| C (Kjeldahl's) | V ($\\ce{H2SO4}$) |\n| D (Hinsberg) | I ($\\ce{C6H5SO2Cl}$ / aq. KOH) |\n\n**Answer: (A)-(IV), (B)-(III), (C)-(V), (D)-(I)** → **Option (c)**\n\n**Key Points to Remember:**\n- Lucas reagent: conc. HCl + anhydrous ZnCl₂ (Lewis acid)\n- Hinsberg reagent: $\\ce{C6H5SO2Cl}$ (benzenesulphonyl chloride) — distinguishes amines\n- Dumas: CuO oxidation → N₂ gas collected\n- Kjeldahl's: conc. H₂SO₄ digestion → (NH₄)₂SO₄ → NH₃ → titrated`
  },
  {
    id: 'POC-100',
    q: `The Kjeldahl's method of nitrogen estimation fails for which of the following reaction products?\n\n![Reaction products A, B, C, D](https://cdn.mathpix.com/cropped/aca1ffda-6c50-41f5-a3e0-e61c67e516fb-08.jpg)`,
    sol: `**Step 1: Recall Kjeldahl's Failures**\n\nKjeldahl's method CANNOT estimate nitrogen in compounds where N is present as:\n- **Nitro groups** ($\\ce{-NO2}$)\n- **Azo groups** ($\\ce{-N=N-}$)\n- **Nitrile groups** ($\\ce{-C≡N}$)\n- **Heteroaromatic ring N** (pyridine-type)\n- **Diazonium salts**\n\nKjeldahl's method works for: amines, amides, amino acids, proteins (any N convertible to $\\ce{NH4+}$)\n\n**Step 2: Identify Products C and D from Reaction Context**\n\nFrom the image options, the reaction products shown include compounds with different N-containing functional groups. Products C and D are the ones that fail the Kjeldahl test.\n\nBased on the answer key: Products **(C) and (D)** are the ones that fail.\n\nThese products would contain:\n- **Product C**: An azo compound ($\\ce{-N=N-}$) or nitro compound ($\\ce{-NO2}$)\n- **Product D**: A nitroso/nitro compound or heteroaromatic N\n\nBoth contain nitrogen in forms that cannot be converted to $\\ce{(NH4)2SO4}$ during Kjeldahl digestion.\n\n**Answer: (a) (C) and (D)**\n\n**Key Points to Remember:**\n- The key question: "Can N be converted to $\\ce{NH4+}$ by conc. H₂SO₄ heating?"\n- If yes → Kjeldahl works\n- If N is in -NO₂, -N=N-, -C≡N, or aromatic ring → Kjeldahl FAILS\n- Dumas' method works for ALL nitrogen compounds (not selective like Kjeldahl)`
  },
  {
    id: 'POC-101',
    difficulty: 'Hard',
    sol: `**Step 1: Identify the Complex and Its Chloride Content**\n\nThe compound is $\\ce{[Co(NH3)6]Cl3}$ — hexaamminecobalt(III) chloride.\n- Molar mass = 267.46 g/mol (given)\n- Formula shows: **3 chloride ions** per formula unit (all three Cl are ionic, outside the coordination sphere)\n\n**Step 2: Calculate Moles of Complex**\n\n$$n_{\\text{complex}} = \\frac{0.3 \\text{ g}}{267.46 \\text{ g/mol}} = 1.1215 \\times 10^{-3} \\text{ mol}$$\n\n**Step 3: Calculate Moles of Cl⁻**\n\nEach formula unit gives 3 $\\ce{Cl^-}$ ions (all are ionic, precipitable by $\\ce{AgNO3}$):\n$$n_{Cl^-} = 3 \\times 1.1215 \\times 10^{-3} = 3.3645 \\times 10^{-3} \\text{ mol}$$\n\n**Step 4: Calculate Volume of AgNO₃ Required**\n\nThe reaction: $\\ce{Ag^+ + Cl^- -> AgCl(v)}$ (1:1 stoichiometry)\n\n$$n_{AgNO_3} = n_{Cl^-} = 3.3645 \\times 10^{-3} \\text{ mol}$$\n\nFor 0.125 M $\\ce{AgNO3}$:\n$$V = \\frac{n}{M} = \\frac{3.3645 \\times 10^{-3}}{0.125} = 0.026916 \\text{ L} = \\mathbf{26.92 \\text{ mL}}$$\n\n**Answer: 26.92 mL**\n\n**Key Points to Remember:**\n- $\\ce{[Co(NH3)6]Cl3}$: All 3 Cl are ionic (outside coordination sphere) → all 3 precipitate with $\\ce{AgNO3}$\n- Compare with $\\ce{[Co(NH3)5Cl]Cl2}$: 2 ionic Cl (outer sphere) + 1 covalent Cl (inner sphere)\n- Only ionic (outer sphere) chlorides precipitate immediately with $\\ce{AgNO3}$\n- Moles of $\\ce{AgNO3}$ = moles of precipitable $\\ce{Cl^-}$ = $n \\times \\text{(number of outer sphere Cl)}$`
  },
  {
    id: 'POC-102',
    q: `In an estimation of bromine by Carius method, 1.6 g of an organic compound gave 1.88 g of AgBr. The mass percentage of bromine in the compound is ______. (Atomic mass: Ag = 108, Br = 80 g mol⁻¹)`,
    difficulty: 'Hard',
    sol: `**Step 1: Recall Carius Method Formula for Bromine**\n\n$$\\%Br = \\frac{80}{188} \\times \\frac{m_{AgBr}}{m_{\\text{compound}}} \\times 100$$\n\nWhere molar mass of $\\ce{AgBr}$ = 108 + 80 = **188 g/mol**\n\n**Step 2: Substitute Given Values**\n\n- $m_{AgBr}$ = 1.88 g\n- $m_{\\text{compound}}$ = 1.6 g\n\n$$m_{Br} = \\frac{80}{188} \\times 1.88 = \\frac{150.4}{188} = 0.80 \\text{ g}$$\n\n**Step 3: Calculate Percentage of Bromine**\n\n$$\\%Br = \\frac{0.80}{1.6} \\times 100 = 50\\%$$\n\n**Answer: 50%**\n\n**Elegant shortcut:**\n$$\\frac{m_{AgBr}}{m_{\\text{compound}}} = \\frac{1.88}{1.6} = \\frac{188}{160} = \\frac{188}{160}$$\n\n$$\\%Br = \\frac{80}{188} \\times \\frac{188}{160} \\times 100 = \\frac{80}{160} \\times 100 = 50\\%$$\n\nNotice that $m_{AgBr}/m_{\\text{compound}} = 188/160$, which means the ratio exactly cancels to give a clean answer of 50%.\n\n**Key Points to Remember:**\n- When $m_{AgBr} = 1.88$ g and compound = 1.6 g, notice $1.88/1.6 = 188/160$ — the 188 (MW of AgBr) cancels perfectly → clean 50%\n- %Br = 50% means one Br per ~160 Da of compound (MW ≈ 160, e.g., a brominated compound)\n- Always double-check: $\\frac{80}{188} \\times \\frac{1.88}{1.6} \\times 100 = 0.4255 \\times 1.175 \\times 100 = 50\\%$ ✓`
  }
];

async function runFix() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  for (const f of fixes) {
    const update = { $set: {} };
    if (f.q) update.$set['question_text.markdown'] = f.q;
    if (f.sol) update.$set['solution.text_markdown'] = f.sol;
    if (f.difficulty) update.$set['metadata.difficulty'] = f.difficulty;
    const res = await col.updateOne({ display_id: f.id }, update);
    console.log(`${f.id}: matched=${res.matchedCount}, modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log('Done batch 4b — ALL POC COMPLETE');
}
runFix().catch(e => { console.error(e); process.exit(1); });
