// POC Fix Batch 1b: POC-006 to POC-010
require('dotenv').config({ path: '.env.local' });
const mongoose = require('mongoose');

const fixes = [
  {
    id: 'POC-006',
    sol: `**Step 1: Define Differential Adsorption**\n\nDifferential adsorption means different compounds adsorb on a solid adsorbent surface with different strengths. More polar compounds interact more strongly with a polar adsorbent (like silica gel or alumina), while less polar compounds adsorb weakly.\n\n**Step 2: Analyse Each Technique**\n\n**A. Column Chromatography** ✅\n- Stationary phase: solid adsorbent (silica gel or alumina) packed in a glass column\n- Mobile phase: liquid solvent (eluent)\n- Separation mechanism: differential adsorption — components travel at different speeds through the column\n- Less polar compounds elute first; more polar ones are retained longer\n\n**B. Thin Layer Chromatography (TLC)** ✅\n- Stationary phase: thin layer of silica gel or alumina coated on a glass/aluminium plate\n- Mobile phase: liquid solvent\n- Separation mechanism: same differential adsorption principle as column chromatography\n- Used for quick qualitative analysis and monitoring reactions\n\n**C. Paper Chromatography** ❌\n- Stationary phase: water absorbed in cellulose fibres of the paper (a **liquid** stationary phase)\n- Separation mechanism: **differential partition** between mobile organic solvent and stationary water film\n- This is partition chromatography, NOT adsorption chromatography\n\n**Step 3: Summary Table**\n\n| Technique | Stationary Phase | Principle |\n|---|---|---|\n| Column chromatography | Solid (silica gel / alumina) | Differential adsorption ✅ |\n| TLC | Solid (silica gel / alumina) | Differential adsorption ✅ |\n| Paper chromatography | Liquid (water in cellulose) | Differential partition ❌ |\n\n**Step 4: Conclusion**\n\nOnly A and B are based on differential adsorption → **Option (c) A & B only**\n\n**Key Points to Remember:**\n- Column chromatography and TLC: adsorption principle (solid adsorbent)\n- Paper chromatography: partition principle (liquid stationary phase)\n- Polar compound → stronger adsorption → lower $R_f$ → elutes last\n- Silica gel and alumina are the two standard polar adsorbents in organic chemistry`
  },
  {
    id: 'POC-007',
    difficulty: 'Easy',
    sol: `**Step 1: Recall the $R_f$ Formula**\n\nThe retardation factor is defined as:\n$$R_f = \\frac{\\text{Distance moved by the compound}}{\\text{Distance moved by the solvent front}}$$\n\n**Step 2: Identify the Given Data**\n\n- Distance moved by organic compound = 3.5 cm\n- Distance moved by solvent front = 5.0 cm\n\n**Step 3: Calculate $R_f$**\n\n$$R_f = \\frac{3.5}{5.0} = 0.7$$\n\n**Step 4: Convert to Required Format**\n\nThe question asks for the answer as $x \\times 10^{-1}$:\n$$0.7 = 7 \\times 10^{-1}$$\n\nTherefore $x = \\mathbf{7}$.\n\n**Key Points to Remember:**\n- $R_f$ always lies between 0 and 1 (inclusive)\n- $R_f = 0$: compound does not move at all (maximum adsorption)\n- $R_f = 1$: compound moves exactly with the solvent front (no adsorption)\n- Polar compounds have lower $R_f$; non-polar compounds have higher $R_f$\n- $R_f$ is reproducible only under the same conditions (adsorbent, solvent, temperature, chamber saturation)`
  },
  {
    id: 'POC-008',
    sol: `**Step 1: Understand "Solubility in Two Different Solvents"**\n\nThis principle exploits the fact that a compound has **different solubilities** in two immiscible solvents. The compound migrates preferentially into the solvent in which it is more soluble. This is governed by the distribution (partition) coefficient:\n\n$$K_D = \\frac{\\text{Concentration in organic solvent}}{\\text{Concentration in aqueous phase}}$$\n\n**Step 2: Evaluate Each Option**\n\n| Method | Underlying Principle |\n|---|---|\n| Column Chromatography | Differential adsorption on solid stationary phase |\n| Sublimation | Vapour pressure (solid → vapour direct conversion) |\n| Distillation | Boiling point differences between liquid components |\n| **Differential Extraction** ✅ | Differential solubility in two immiscible solvents |\n\n**Step 3: Mechanism of Differential Extraction**\n\n1. Impure compound dissolved in water is placed in a separating funnel\n2. An immiscible organic solvent (diethyl ether, CH₂Cl₂, etc.) is added\n3. The funnel is shaken — compound migrates toward the solvent where $K_D$ is higher\n4. Layers are allowed to separate; the organic layer is drained off\n5. Organic solvent is evaporated to recover the purified compound\n6. Repeated extractions with small volumes of fresh solvent are more efficient\n\n**Step 4: Conclusion**\n\nAnswer: **(d) Differential Extraction**\n\n**Key Points to Remember:**\n- Uses two immiscible solvents (water + organic solvent)\n- Distribution coefficient $K_D$ determines how effectively the compound is extracted\n- Multiple small-volume extractions > one large-volume extraction (efficiency)\n- Equipment used: separating funnel`
  },
  {
    id: 'POC-009',
    sol: `**Step 1: Define Adsorption in Purification Context**\n\nAdsorption is the process by which molecules (adsorbate) stick to the surface of a solid (adsorbent). Different compounds adsorb with different strengths based on their polarity and the nature of the adsorbent.\n\n**Step 2: Match Each Method to Its Principle**\n\n| Method | Principle |\n|---|---|\n| Extraction | Differential solubility (partition) in two immiscible solvents |\n| **Chromatography** ✅ | Differential adsorption on a solid stationary phase |\n| Distillation | Differences in boiling points (vapour pressure) |\n| Sublimation | Direct solid ↔ vapour conversion (vapour pressure) |\n\n**Step 3: How Adsorption Chromatography Works**\n\nIn column chromatography and TLC:\n- **Stationary phase:** solid adsorbent ($\\ce{SiO2}$ or $\\ce{Al2O3}$)\n- **Mobile phase:** liquid solvent\n- Components with different polarity adsorb with different strengths\n- More polar compound → stronger adsorption → slower movement → lower $R_f$\n- Less polar compound → weaker adsorption → faster movement → higher $R_f$\n\n**Step 4: Conclusion**\n\nAnswer: **(b) Chromatography**\n\n**Key Points to Remember:**\n- Adsorption uses a **solid** stationary phase; partition uses a **liquid** stationary phase\n- Adsorption order on polar adsorbent: $\\text{COOH} > \\text{OH} > \\text{C=O} > \\text{COOR} > \\text{C-X} > \\text{aromatic} > \\text{alkene} > \\text{alkane}$\n- Silica gel ($\\ce{SiO2 . xH2O}$) and alumina ($\\ce{Al2O3}$) are the standard adsorbents\n- Activated charcoal is a non-polar adsorbent (special case)`
  },
  {
    id: 'POC-010',
    q: `Match List-I with List-II.\n\n| | List-I (Technique) | | List-II (Application) |\n|---|---|---|---|\n| A | Distillation | I | Separation of glycerol from spent-lye |\n| B | Fractional distillation | II | Aniline - Water mixture |\n| C | Steam distillation | III | Separation of crude oil fractions |\n| D | Distillation under reduced pressure | IV | Chloroform - Aniline |\n\nChoose the correct answer from the options given below:`,
    sol: `**Step 1: Criteria for Each Technique**\n\n- **Distillation (Simple):** bp difference > 25°C between two components\n- **Fractional Distillation:** bp difference < 25°C or multiple components with overlapping boiling points\n- **Steam Distillation:** compound must be steam-volatile AND water-immiscible\n- **Distillation under Reduced Pressure:** compound decomposes at normal boiling point\n\n**Step 2: Analyse Each Application**\n\n- **Chloroform–Aniline (IV):** CHCl₃ bp = 61°C, Aniline bp = 184°C → difference = 123°C → **Technique A (Simple distillation)**\n- **Aniline–Water (II):** Aniline is steam-volatile and immiscible with water → **Technique C (Steam distillation)**\n- **Crude oil fractions (III):** Hundreds of hydrocarbons with close boiling points → **Technique B (Fractional distillation)**\n- **Glycerol from spent-lye (I):** Glycerol bp = 290°C, decomposes at normal bp → **Technique D (Vacuum distillation)**\n\n**Step 3: Match Table**\n\n| List-I | List-II |\n|---|---|\n| A (Distillation) | IV (Chloroform–Aniline) |\n| B (Fractional distillation) | III (Crude oil fractions) |\n| C (Steam distillation) | II (Aniline–Water) |\n| D (Reduced pressure) | I (Glycerol from spent-lye) |\n\n**Step 4: Conclusion**\n\nAnswer: **A-IV, B-III, C-II, D-I** → **Option (b)**\n\n**Key Points to Remember:**\n- Glycerol (triol, bp 290°C) → always vacuum distillation\n- Aniline + water → steam distillation; Aniline + chloroform → simple distillation (common exam trap!)\n- Industrial crude oil separation is the most important example of fractional distillation\n- Fractionating column increases the number of vaporisation–condensation cycles (theoretical plates)`
  }
];

async function runFix() {
  await mongoose.connect(process.env.MONGODB_URI);
  const col = mongoose.connection.db.collection('questions_v2');
  for (const f of fixes) {
    const update = { $set: {} };
    if (f.q) update.$set['question_text.markdown'] = f.q;
    if (f.sol) update.$set['solution.text_markdown'] = f.sol;
    if (f.difficulty) update.$set['metadata.difficulty'] = f.difficulty;
    const res = await col.updateOne({ display_id: f.id }, update);
    console.log(`${f.id}: matched=${res.matchedCount}, modified=${res.modifiedCount}`);
  }
  await mongoose.disconnect();
  console.log('Done batch 1b');
}
runFix().catch(e => { console.error(e); process.exit(1); });
