import type { Reaction, QuickRefTable } from './types';

export const REACTIONS: Reaction[] = [

{id:"aldol",name:"Aldol Condensation",type:"Condensation",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["enolate","alpha-H","NaOH","beta-hydroxy carbonyl","crotonaldehyde"],
 summary:"Aldehydes or ketones with at least one alpha-H undergo base-catalysed condensation: enolate attacks a second carbonyl to give a beta-hydroxy carbonyl compound (aldol product). On heating, water is eliminated to yield an alpha,beta-unsaturated carbonyl (condensation product). Cross-aldol between two different carbonyls gives a mixture — JEE Advanced tests which product predominates.",
 reactants:"Aldehyde or ketone with at least one alpha-H",
 reagents:"Dil. NaOH (base) or dil. HCl (acid)",
 conditions:"Cold dil. NaOH = aldol product. Heat = dehydration = condensation product.",
 product:"Cold: beta-hydroxy carbonyl. Heat: alpha,beta-unsaturated carbonyl. Classic: CH₃CHO → crotonaldehyde (CH₃CH=CHCHO).",
 mechanism:"Enolate attacks carbonyl C of second molecule → aldol. Heating → E1cb dehydration → alpha,beta-unsaturated product.",
 stereo:"New stereocentre at beta-C in aldol product → racemic mixture without chiral catalyst.",
 mistake:"Applying to HCHO or PhCHO — no alpha-H → they do Cannizzaro, NOT aldol. Also confusing the cold (aldol) and hot (condensation) products — they are different.",
 hook:"No alpha-H = no aldol = Cannizzaro instead. Cold = aldol. Heat = condensation. Acetaldehyde → crotonaldehyde is the go-to JEE example.",
 jee:"Very high frequency. Cross-aldol with two different carbonyls gives a mixture — JEE Advanced tests which product predominates."},

{id:"cannizzaro",name:"Cannizzaro Reaction",type:"Disproportionation",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["no alpha-H","HCHO","PhCHO","conc NaOH","hydride transfer"],
 summary:"Aldehydes that lack alpha-H (HCHO, PhCHO, CCl₃CHO) undergo self-oxidation-reduction in concentrated NaOH: one molecule is oxidised to a carboxylate salt while the other is reduced to a primary alcohol via hydride transfer. In a crossed Cannizzaro (HCHO + PhCHO), HCHO is always oxidised and PhCHO is always reduced — a classic JEE trap.",
 reactants:"Aldehydes with NO alpha-H: HCHO, PhCHO, CCl₃CHO",
 reagents:"Conc. NaOH (concentrated — dilute gives aldol if alpha-H present)",
 conditions:"Concentrated aqueous NaOH, mild heat",
 product:"Carboxylate salt + primary alcohol. HCHO + NaOH → HCOONa + CH₃OH",
 mechanism:"OH⁻ attacks C=O → tetrahedral alkoxide → H⁻ transfer (rate-determining) to second aldehyde → two products.",
 stereo:null,
 mistake:"Using dilute NaOH — need CONC. In crossed Cannizzaro (HCHO + PhCHO), HCHO is ALWAYS oxidised (gives HCOO⁻), PhCHO is ALWAYS reduced (gives PhCH₂OH). Students reverse these roles.",
 hook:"Cannizzaro = CAN'T do aldol (no alpha-H). CONC NaOH. One up (acid salt), one down (alcohol). HCHO always sacrifices itself in crossed Cannizzaro.",
 jee:"Crossed Cannizzaro popular in JEE Advanced — given products, identify reaction and roles of each aldehyde."},

{id:"carbylamine",name:"Carbylamine Reaction",type:"Amine Test",chapter:"Amines",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["isocyanide","1° amine only","CHCl₃","KOH","foul smell"],
 summary:"Primary amines (aliphatic or aromatic) react with CHCl₃ and alcoholic KOH to form isocyanides (R-N≡C) — compounds with an intensely foul, nauseating odour. The reaction proceeds via dichlorocarbene (:CCl₂) intermediate and is strictly a test for 1° amines only; secondary and tertiary amines give a negative result.",
 reactants:"Primary amine ONLY (RNH₂) — aliphatic or aromatic",
 reagents:"CHCl₃ + alcoholic KOH, heat",
 conditions:"Alcoholic KOH, heat. Smell is the indicator.",
 product:"Isocyanide (R-N≡C). Extremely foul odour = positive test.",
 mechanism:"CHCl₃ + KOH → :CCl₂ (dichlorocarbene) → reacts with -NH₂ → R-N=CCl₂ → double HCl elimination → R-N≡C",
 stereo:null,
 mistake:"Applying to 2° or 3° amines — NEGATIVE. Only 1° amines react. Also: isocyanide is R-N≡C (N bonded to R), NOT R-C≡N (nitrile). Structure is inverted — students draw it backwards.",
 hook:"Carbylamine = Foul = 1° amine ONLY. CHCl₃ + alc. KOH. 2° and 3° = negative. If it stinks = positive.",
 jee:"'Distinguish 1° from 2°/3° amine?' → Carbylamine test. Works for both aliphatic and aromatic 1° amines."},

{id:"clemmensen",name:"Clemmensen Reduction",type:"Reduction",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["Zn amalgam","HCl","C=O to CH₂","acid conditions"],
 summary:"Clemmensen reduction converts the carbonyl group (C=O) of aldehydes and ketones directly to a methylene group (CH₂) using zinc amalgam [Zn(Hg)] in concentrated HCl. The strongly acidic conditions mean the substrate must be acid-stable; for base-sensitive substrates use Wolff-Kishner instead. Both methods give the same alkane product from the same carbonyl starting material.",
 reactants:"Aldehyde or ketone (not carboxylic acids)",
 reagents:"Zn(Hg) amalgam + conc. HCl",
 conditions:"Strongly acidic (conc. HCl), heat. Substrate must be acid-stable.",
 product:"Alkane: R-CO-R' → R-CH₂-R'. C=O becomes CH₂.",
 mechanism:"Heterogeneous surface mechanism on Zn. Not a simple ionic pathway.",
 stereo:null,
 mistake:"Using for acid-sensitive substrates — they are destroyed. Use Wolff-Kishner (basic) instead. Also: does NOT reduce COOH or esters — only aldehyde/ketone C=O.",
 hook:"Clemmensen = Zn(Hg) + HCl = ACID. Use when substrate is BASE-sensitive. Wolff-Kishner = KOH = BASE. Use when ACID-sensitive. Same product, opposite conditions.",
 jee:"Always paired with Wolff-Kishner in JEE. 'Which to use if substrate has acid-sensitive group?' → Wolff-Kishner."},

{id:"diazotisation",name:"Diazotisation",type:"Diazonium Chemistry",chapter:"Amines",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["ArN₂⁺","NaNO₂","HCl","0–5°C","ice bath","gateway reaction"],
 summary:"Primary aromatic amines react with NaNO₂ and HCl at 0–5°C to form diazonium salts (ArN₂⁺Cl⁻) — the essential gateway to Sandmeyer, Balz-Schiemann, and azo-coupling reactions. Temperature control is critical: above 5°C the diazonium decomposes to phenol + N₂. Aliphatic diazonium salts are too unstable to isolate and immediately lose N₂.",
 reactants:"Primary aromatic amine (ArNH₂): aniline, substituted anilines",
 reagents:"NaNO₂ + HCl (generates HNO₂ in situ)",
 conditions:"ICE COLD: 0–5°C. Above 5°C → diazonium decomposes to phenol + N₂.",
 product:"Diazonium salt (ArN₂⁺Cl⁻): C₆H₅NH₂ → C₆H₅N₂⁺Cl⁻",
 mechanism:"HNO₂ + ArNH₂ → N-nitrosoamine → tautomerism → ArN₂⁺",
 stereo:null,
 mistake:"Using aliphatic amines — alkyl diazonium instantly decomposes to alcohol + N₂. Only AROMATIC amines form stable diazonium. Also: above 5°C → decomposition to phenol.",
 hook:"Diazotisation = ICE COLD always. ArNH₂ + NaNO₂ + HCl at 0–5°C = ArN₂⁺. Gateway to all diazonium reactions.",
 jee:"Master this first — Sandmeyer, Balz-Schiemann and azo coupling all start here."},

{id:"fc-acylation",name:"Friedel-Crafts Acylation",type:"Electrophilic Aromatic Substitution",chapter:"Aromatic Compounds",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["AlCl₃","RCOCl","acylium ion","aryl ketone","no rearrangement"],
 summary:"Benzene reacts with an acyl chloride (RCOCl) in the presence of anhydrous AlCl₃ to give an aryl ketone via EAS. Because the electrophile is a resonance-stabilised acylium ion (RCO⁺), no carbocation rearrangement occurs and the product ketone deactivates the ring — preventing polyacylation. More than one equivalent of AlCl₃ is required since the product carbonyl complexes with it.",
 reactants:"Benzene + acyl chloride (RCOCl) or acid anhydride",
 reagents:"Anhydrous AlCl₃ (>1 equiv — one equiv complexes with product C=O)",
 conditions:"Anhydrous. Excess AlCl₃ needed because product ketone complexes with AlCl₃.",
 product:"Aryl ketone: PhH + CH₃COCl + AlCl₃ → PhCOCH₃ (acetophenone) + HCl",
 mechanism:"RCOCl + AlCl₃ → RCO⁺ (acylium — resonance-stabilised → no rearrangement). EAS. Product C=O complexes AlCl₃ → ring deactivated → no polyacylation.",
 stereo:null,
 mistake:"Forgetting that >1 equiv AlCl₃ is needed. Acylation also FAILS on deactivated rings. Best way to put a long-chain alkyl on a ring without rearrangement: FC acylation → Clemmensen/WK.",
 hook:"FC Acylation = no rearrangement, no polyacylation. Same limitation as alkylation: fails on deactivated rings. Acylation + Clemmensen = rearrangement-free alkylation.",
 jee:"JEE contrasts acylation vs alkylation limitations. Two-step (acylation + Clemmensen) = classic synthesis question."},

{id:"fc-alkylation",name:"Friedel-Crafts Alkylation",type:"Electrophilic Aromatic Substitution",chapter:"Aromatic Compounds",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["AlCl₃","RX","carbocation","EAS","rearrangement","polyalkylation"],
 summary:"Benzene reacts with alkyl halides in the presence of anhydrous AlCl₃ to give alkylbenzenes via electrophilic aromatic substitution. Three critical limitations make this reaction unreliable: (1) carbocation rearrangement (n-PrCl gives isopropylbenzene, not n-propylbenzene), (2) polyalkylation since the product is more reactive than benzene, and (3) complete failure with deactivated rings such as nitrobenzene.",
 reactants:"Benzene + alkyl halide (RX)",
 reagents:"Anhydrous AlCl₃ (Lewis acid)",
 conditions:"Anhydrous AlCl₃, anhydrous conditions. H₂O destroys catalyst.",
 product:"Alkylbenzene: PhH + CH₃Cl + AlCl₃ → PhCH₃ + HCl",
 mechanism:"RX + AlCl₃ → R⁺ + AlCl₄⁻. R⁺ attacks benzene (EAS) → sigma complex → H⁺ loss → product.",
 stereo:null,
 mistake:"Three JEE limitations: (1) REARRANGEMENT — 1° carbocations rearrange (n-PrCl + Ph + AlCl₃ → isopropylbenzene, NOT n-propylbenzene). (2) POLYALKYLATION — product is more reactive than benzene. (3) FAILS on deactivated rings (nitrobenzene, etc.).",
 hook:"FC Alkylation Three Enemies: Rearrangement. Polyalkylation. Deactivated rings fail. n-Pr → isopropyl (rearranges!). Use Acylation + Clemmensen to avoid rearrangement.",
 jee:"All three limitations are exam staples. n-propyl chloride → cumene (isopropylbenzene) via rearrangement is a classic trap."},

{id:"grignard",name:"Grignard Reaction",type:"Nucleophilic Addition",chapter:"Multiple Chapters",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["RMgX","organometallic","C-C bond","anhydrous","dry ether","carbanion"],
 summary:"Grignard reagents (RMgX) behave as carbanions and add nucleophilically to carbonyl compounds: HCHO gives 1° alcohol, RCHO gives 2°, R₂CO gives 3°, CO₂ gives carboxylic acid, and esters consume 2 moles to give 3° alcohol. Strictly anhydrous conditions are essential — even a trace of water destroys the reagent by protonation (RMgX + H₂O → RH). This is the most versatile C–C bond-forming reaction tested in JEE.",
 reactants:"RMgX + HCHO → 1° OH  |  RCHO → 2° OH  |  R₂CO → 3° OH  |  CO₂ → RCOOH  |  Ester → 3° OH (2 moles RMgX)",
 reagents:"Mg in dry ether for prep. Then carbonyl. Then H₃O⁺ workup.",
 conditions:"Strictly anhydrous and aprotic. Dry ether or THF. One drop of water destroys Grignard: RMgX + H₂O → RH.",
 product:"1° OH (HCHO), 2° OH (RCHO), 3° OH (R₂CO), RCOOH (CO₂), 3° OH same R (ester)",
 mechanism:"C(δ−)-Mg(δ+): C is nucleophile. Attacks electrophilic carbonyl C → Mg-alkoxide → H₃O⁺ → alcohol.",
 stereo:"New stereocentre at former carbonyl C → RACEMIC mixture (attack from both faces).",
 mistake:"Using with ANY protic compound (H₂O, ROH, NH₃, RCOOH, RNH₂) — IMMEDIATELY DESTROYED → gives only RH. Also with esters: 2 moles of RMgX react (first → ketone intermediate, second → 3° alcohol with R added twice).",
 hook:"Grignard = R⁻ in disguise. Kills with moisture. HCHO=1°, RCHO=2°, R₂CO=3°, CO₂=RCOOH, ester=3° (2 moles). DRY EVERYTHING.",
 jee:"Most important reaction in JEE organics. Which product from which carbonyl? How many moles? Every paper has a Grignard question."},

// ─── BATCH 2 ───────────────────────────────────────────────────────────────

{id:"hofmann-bromamide",name:"Hofmann Bromamide Reaction",type:"Rearrangement",chapter:"Amines",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["RCONH₂","Br₂","NaOH","1° amine","n-1 carbons","isocyanate"],
 summary:"Primary amide + Br₂/NaOH → primary amine with ONE FEWER carbon. The carbonyl is lost as CO₂. Amide → amine with carbon loss.",
 reactants:"Primary amide (RCONH₂) ONLY. Does not work for 2° or 3° amides.",
 reagents:"Br₂ + NaOH (NaOBr is the active species)",
 conditions:"Aqueous NaOH + Br₂, 0°C then warm",
 product:"RNH₂ (n-1 carbons): CH₃CONH₂ → CH₃NH₂. CO₂ is lost.",
 mechanism:"NaOBr → N-bromoamide → base removes N-H → Br⁻ leaves → isocyanate (R-N=C=O) → H₂O → carbamic acid → CO₂ + RNH₂",
 stereo:"Configuration at R is RETAINED (rearrangement at carbonyl, not at R).",
 mistake:"Writing the same number of carbons in product as in starting amide — WRONG. Amide has n C, amine has n-1 C. CO₂ escapes! Also: confusing with Hofmann ELIMINATION (quaternary salt → least substituted alkene) — completely different reaction.",
 hook:"Hofmann Bromamide: RCONH₂ → RNH₂. ONE carbon LESS. Carbonyl runs away as CO₂. Br₂ + NaOH. Primary amide only. CH₃CONH₂ → CH₃NH₂ (not C₂H₅NH₂).",
 jee:"Very high frequency. 'CH₃CONH₂ + Br₂/NaOH → ?' → CH₃NH₂. Propanamide → ethylamine (C3 → C2). Tests carbon counting."},

{id:"haloform",name:"Haloform / Iodoform Reaction",type:"Halogenation",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["CHI₃","iodoform","yellow precipitate","methyl ketone","NaOI","qualitative test"],
 summary:"Methyl ketones (CH₃COR) and CH₃CHO react with I₂/NaOH → yellow CHI₃ (iodoform). Qualitative test for methyl ketone group.",
 reactants:"CH₃COR (methyl ketone), CH₃CHO, ethanol, isopropanol (all oxidised to methyl carbonyl in situ)",
 reagents:"I₂ + NaOH (NaOI formed in situ)",
 conditions:"Alkaline medium (NaOH), room temperature. Yellow ppt = positive.",
 product:"CHI₃ (yellow iodoform ppt) + RCOONa (one fewer carbon than starting material)",
 mechanism:"Step 1: all 3 alpha-H on methyl replaced by I (trihalogenation). Step 2: OH⁻ cleaves C-C → CHI₃ + RCOO⁻",
 stereo:null,
 mistake:"ALL ketones give iodoform — FALSE. Only METHYL ketones (CH₃CO-). Ethanol → YES, Isopropanol → YES (oxidised to acetone), n-Propanol → NO (gives propanal, no CH₃CO-), Diethyl ketone → NO.",
 hook:"Iodoform test: look for CH₃CO- group. Ethanol ✓  Isopropanol ✓  n-Propanol ✗  Acetone ✓  Diethyl ketone ✗. Yellow CHI₃ = positive.",
 jee:"Positive/negative iodoform test lists are extremely common. JEE gives a set of compounds and asks which give CHI₃."},

{id:"kolbe",name:"Kolbe's Reaction (Kolbe-Schmitt)",type:"Carboxylation",chapter:"Phenols",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["phenol","CO₂","salicylic acid","Na phenoxide","pressure","aspirin"],
 summary:"Sodium phenoxide + CO₂ under pressure at 125°C → salicylic acid (2-hydroxybenzoic acid) after acidification. Precursor of aspirin.",
 reactants:"Sodium phenoxide (C₆H₅ONa) — phenol + NaOH first",
 reagents:"CO₂ gas at 4–5 atm, then H⁺ workup",
 conditions:"125°C, 4–5 atm CO₂. Na-phenoxide → ortho. K-phenoxide at 250°C → para (p-hydroxybenzoic acid).",
 product:"Salicylic acid (2-hydroxybenzoic acid). Aspirin = salicylic acid + acetic anhydride.",
 mechanism:"CO₂ (weak electrophile) attacks ortho of electron-rich phenoxide ring → H⁺ workup → salicylic acid.",
 stereo:null,
 mistake:"Temperature and cation matter: Na + 125°C = ORTHO. K + 250°C = PARA. Using free phenol (need the Na-salt). Students mix up temperature and product.",
 hook:"Kolbe = CO₂ + Na-phenoxide + pressure = SALICYLIC ACID. Low T = ortho. High T = para. Na≠K. Kolbe made aspirin's parent!",
 jee:"'Phenol + CO₂ under pressure → ?' → salicylic acid. Direct factual question every alternate year."},

{id:"reimer-tiemann",name:"Reimer-Tiemann Reaction",type:"Electrophilic Aromatic Substitution",chapter:"Phenols",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["phenol","CHCl₃","NaOH","salicylaldehyde","dichlorocarbene"],
 summary:"Phenol + CHCl₃ + NaOH → dichlorocarbene electrophile attacks phenoxide ortho → hydrolysis → salicylaldehyde (2-hydroxybenzaldehyde).",
 reactants:"Phenol (C₆H₅OH)",
 reagents:"CHCl₃ + conc. NaOH (aqueous)",
 conditions:"NaOH/H₂O, ~60–70°C",
 product:"Salicylaldehyde (2-hydroxybenzaldehyde) — major; para-hydroxybenzaldehyde — minor.",
 mechanism:"CHCl₃ + NaOH → :CCl₂ (dichlorocarbene) → attacks ortho of phenoxide → gem-dichloride intermediate + 2NaOH → CHO + 2NaCl (hydrolysis).",
 stereo:null,
 mistake:"Writing CHO⁺ as the electrophile — WRONG. The electrophile is :CCl₂ (dichlorocarbene). Also: works ONLY for phenols — not plain benzene (use Gattermann-Koch for benzene).",
 hook:"RT = CHCl₃ + NaOH on PHENOL = carbene = salicylaldehyde. G-K = CO + HCl + AlCl₃ on BENZENE. Carbene is the electrophile, not CHO⁺.",
 jee:"'Phenol + CHCl₃ + NaOH → ?' → salicylaldehyde. Asked almost every year."},

// ─── BATCH 3 ───────────────────────────────────────────────────────────────

{id:"rosenmund",name:"Rosenmund Reduction",type:"Reduction",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["RCOCl","H₂","Pd/BaSO₄","poisoned catalyst","RCHO"],
 summary:"Acid chloride (RCOCl) reduced selectively to aldehyde (RCHO) by H₂ over POISONED Pd/BaSO₄. Poison prevents over-reduction to alcohol.",
 reactants:"Acid chloride (RCOCl)",
 reagents:"H₂ + Pd/BaSO₄ (catalyst poisoned with quinoline-S)",
 conditions:"H₂ atmosphere, Pd/BaSO₄, gentle",
 product:"Aldehyde: RCOCl + H₂ → RCHO + HCl",
 mechanism:"Surface hydrogenation on poisoned Pd. Stops at aldehyde — un-poisoned Pd would reduce to alcohol.",
 stereo:null,
 mistake:"Using normal Pd/C — over-reduces to primary alcohol. Pd/BaSO₄ (POISONED) is essential. Also: LiAlH₄ or NaBH₄ cannot stop at aldehyde.",
 hook:"Rosenmund = Pd/BaSO₄ = POISONED Pd = STOPS at ALDEHYDE. Unpoisoned Pd → alcohol. Poison = halfway stop.",
 jee:"'RCOCl → RCHO, which reagent?' → H₂/Pd-BaSO₄. Distinguish from Stephen (SnCl₂/HCl on RCN)."},

{id:"sandmeyer",name:"Sandmeyer Reaction",type:"Diazonium Chemistry",chapter:"Amines",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["ArN₂⁺","CuCl","CuBr","CuCN","aryl halide","radical"],
 summary:"Diazonium salt + CuCl/CuBr/CuCN → ArCl/ArBr/ArCN. Makes aryl halides not accessible by direct substitution.",
 reactants:"Benzenediazonium salt (ArN₂⁺Cl⁻)",
 reagents:"CuCl → ArCl; CuBr → ArBr; CuCN → ArCN. For ArF: Balz-Schiemann (HBF₄). For ArI: KI directly (no Cu needed). For ArOH: H₂O/heat. For ArH: H₃PO₂.",
 conditions:"Cu(I) salts, mild heat. Balz-Schiemann: HBF₄ then heat dry diazonium tetrafluoroborate.",
 product:"ArCl, ArBr, ArCN, ArF, ArI, ArOH, ArH depending on reagent.",
 mechanism:"Cu(I) radical mechanism: Cu(I) → Cu(II) + e⁻ → Ar• → Ar-X. NOT a simple SN2.",
 stereo:null,
 mistake:"Using Cu for ArI (use KI directly) or ArF (use Balz-Schiemann). Also: Sandmeyer is for AROMATIC diazonium — aliphatic diazonium is too unstable.",
 hook:"Sandmeyer: Cu(I) + diazonium = aryl halide. CuCl=ArCl, CuBr=ArBr, CuCN=ArCN. No Cu for I (use KI) and no Cu for F (use Balz-Schiemann).",
 jee:"'ArNH₂ → ArCl in two steps?' → Diazotise then Sandmeyer. Very common synthesis question."},

{id:"stephen",name:"Stephen Reduction",type:"Reduction",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["RCN","SnCl₂","HCl","RCHO","nitrile to aldehyde"],
 summary:"Nitrile (RCN) + SnCl₂ + HCl → imine salt → hydrolysis → aldehyde (RCHO). Converts nitrile to aldehyde (same carbon count).",
 reactants:"Nitrile (RCN)",
 reagents:"SnCl₂ + HCl (anhydrous), then H₂O workup",
 conditions:"Anhydrous HCl + SnCl₂, then aqueous workup",
 product:"Aldehyde (RCHO): CH₃CN → CH₃CHO",
 mechanism:"SnCl₂ reduces C≡N to C=NH (imine) as Sn(II) complex → H₂O hydrolysis → RCHO + NH₃",
 stereo:null,
 mistake:"Confusing with Rosenmund (RCOCl → RCHO) — both give aldehyde but from different starting materials. Stephen: nitrile → aldehyde (same C count). Also: LiAlH₄ on nitrile gives PRIMARY AMINE (not aldehyde).",
 hook:"Stephen = SnCl₂ + HCl on NITRILE = ALDEHYDE. Same C count. LiAlH₄ on nitrile = amine (not aldehyde). Rosenmund = acid chloride → aldehyde.",
 jee:"'RCN → RCHO, which reagent?' → SnCl₂/HCl (Stephen). 'RCN → RCH₂NH₂?' → LiAlH₄."},

{id:"wolff-kishner",name:"Wolff-Kishner Reduction",type:"Reduction",chapter:"Aldehydes & Ketones",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["NH₂NH₂","KOH","ethylene glycol","C=O to CH₂","base conditions"],
 summary:"Aldehyde/ketone + NH₂NH₂ + KOH/ethylene glycol → hydrazone → CH₂. Base conditions — use when substrate is acid-sensitive.",
 reactants:"Aldehyde or ketone",
 reagents:"NH₂NH₂ (hydrazine) + KOH in ethylene glycol (high boiling point solvent)",
 conditions:"High temperature (~200°C), strongly basic (KOH). Substrate must be base-stable.",
 product:"Alkane: R-CO-R' → R-CH₂-R'. Same as Clemmensen but under basic conditions.",
 mechanism:"C=O + NH₂NH₂ → hydrazone (C=N-NH₂) → KOH/heat → N₂ loss → carbanion → protonation → CH₂",
 stereo:null,
 mistake:"Using for base-sensitive substrates. Use Clemmensen (acid) instead. Also: Huang Minlon modification (aqueous KOH + diethylene glycol) is a variant — same product.",
 hook:"Wolff-Kishner = NH₂NH₂ + KOH = BASE. Use when ACID-sensitive. Clemmensen = Zn(Hg) + HCl = ACID. Use when BASE-sensitive. Same product, opposite pH.",
 jee:"Always tested alongside Clemmensen. 'Which reagent for C=O → CH₂ if substrate has acid-labile group?' → Wolff-Kishner."},

{id:"fischer",name:"Fischer Esterification",type:"Acyl Substitution",chapter:"Carboxylic Acids",
 priority:"high",exam:"both",difficulty:"easy",
 tags:["RCOOH","alcohol","H⁺","reversible","¹⁸O labelling","ester"],
 summary:"Carboxylic acid + alcohol + H⁺ catalyst ⇌ ester + water. Reversible equilibrium reaction — must be driven forward.",
 reactants:"Carboxylic acid (RCOOH) + alcohol (R'OH)",
 reagents:"H⁺ catalyst (conc. H₂SO₄ or dry HCl), heat",
 conditions:"Reversible. Drive forward: excess alcohol, remove water (distillation/molecular sieves), or conc. H₂SO₄.",
 product:"Ester (RCOOR') + H₂O: CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O",
 mechanism:"H⁺ protonates C=O → R'OH attacks → tetrahedral intermediate → H₂O loss → ester. Acyl-oxygen cleavage (confirmed by ¹⁸O labelling).",
 stereo:null,
 mistake:"Forgetting it is REVERSIBLE. Also: ¹⁸O labelling shows the O in ester comes from the ALCOHOL (not the acid). The acid loses its -OH as water. Tertiary alcohols react poorly (elimination competes).",
 hook:"Reversible! ¹⁸O from ALCOHOL ends up in ester. Acid donates -OH as water. Drive equilibrium right: excess alcohol or remove water.",
 jee:"JEE tests ¹⁸O isotope labelling to confirm acyl-oxygen cleavage. RCOOH + ROH (reversible, H⁺) vs RCOCl + ROH (irreversible, fast, no catalyst) distinction."},

{id:"gabriel",name:"Gabriel Phthalimide Synthesis",type:"Amine Synthesis",chapter:"Amines",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["phthalimide","KOH","RX","SN2","1° amine only","hydrazinolysis"],
 summary:"Phthalimide + KOH → K-phthalimide + RX (SN2) → N-alkyl phthalimide + hydrolysis → PRIMARY AMINE ONLY. Cannot make 2° or 3° amines.",
 reactants:"Phthalimide + primary alkyl halide (RX)",
 reagents:"Step 1: KOH. Step 2: RX. Step 3: acid hydrolysis (H₃O⁺) or hydrazinolysis (N₂H₄).",
 conditions:"Anhydrous for SN2 step; then acidic hydrolysis or hydrazinolysis.",
 product:"Primary amine (RNH₂) only. Phthalate byproduct.",
 mechanism:"Phthalimide N-H (pKa ~8.3) deprotonated by KOH → N-nucleophile → SN2 on RX → N-alkyl phthalimide → hydrolysis → RNH₂.",
 stereo:"SN2 step: inversion of configuration at RX carbon if chiral.",
 mistake:"Gabriel cannot make secondary or tertiary amines — phthalimide has ONE N-H so only one alkyl group attaches. Also: primary aryl amines cannot be made (ArX doesn't undergo SN2 easily).",
 hook:"Gabriel = phthalimide + KOH + RX + hydrolysis = 1° AMINE ONLY. One N-H = one alkyl group. Never secondary, never tertiary.",
 jee:"'Which method gives only primary amine?' → Gabriel. 'Can Gabriel make 2° amine?' → No."},

// ─── BATCH 4 ───────────────────────────────────────────────────────────────

{id:"williamson",name:"Williamson Ether Synthesis",type:"SN2 Substitution",chapter:"Alcohols & Ethers",
 priority:"high",exam:"both",difficulty:"medium",
 tags:["alkoxide","SN2","mixed ether","primary halide","RONa + RX"],
 summary:"Alkoxide (RONa) + primary alkyl halide → ether by SN2. Best route to mixed ethers. Tertiary alkyl halides fail (elimination dominates).",
 reactants:"Sodium alkoxide (RONa) + primary (ideally) alkyl halide",
 reagents:"Na metal + alcohol → alkoxide, then RX. Or NaOH + phenol → phenoxide + RX.",
 conditions:"Anhydrous. SN2 requires primary RX.",
 product:"Ether (R-O-R'): CH₃ONa + C₂H₅Br → CH₃OC₂H₅ + NaBr",
 mechanism:"SN2: alkoxide O⁻ attacks back of C-X → concerted → ether + X⁻",
 stereo:"Inversion of configuration at RX carbon (SN2).",
 mistake:"Using tertiary RX — SN2 fails, elimination dominates. SWAP ROLES: tertiary group on the ALKOXIDE side. e.g. for (CH₃)₃C-O-CH₃: use (CH₃)₃CONa + CH₃I, NOT (CH₃)₃CI + CH₃ONa.",
 hook:"Williamson = alkoxide + PRIMARY halide → ether. Tertiary halide = elimination. Tertiary group goes on ALKOXIDE side.",
 jee:"'Which combination gives ether without elimination?' Tests SN2 vs E2. Anisole via PhONa + CH₃I is classic."},

{id:"azo-coupling",name:"Azo Coupling Reaction",type:"Diazonium Chemistry",chapter:"Amines",
 priority:"medium",exam:"both",difficulty:"medium",
 tags:["ArN₂⁺","phenol","aniline","azo dye","N=N bond","para coupling"],
 summary:"Diazonium salt (ArN₂⁺) + phenol or aryl amine → azo compound (Ar-N=N-Ar'). Coloured azo dyes. Para coupling preferred.",
 reactants:"Diazonium salt (electrophile) + phenol or aromatic amine (activated ring)",
 reagents:"Freshly prepared cold diazonium salt (ArN₂⁺Cl⁻)",
 conditions:"Phenol: mildly alkaline (pH 8–10, forms PhO⁻). Amine: weakly acidic/neutral. Temperature: 0–5°C always.",
 product:"Azo compound (Ar-N=N-Ar') — coloured dye. Para coupling major product.",
 mechanism:"ArN₂⁺ (weak electrophile) attacks para of activated ring (EAS) → sigma complex → H⁺ loss → azo dye.",
 stereo:"E/Z isomerism about N=N bond. E (trans) = thermodynamically more stable.",
 mistake:"Phenol coupling needs MILD BASE (PhO⁻ = more activated). Amine coupling needs WEAK ACID (strong acid protonates -NH₂ → -NH₃⁺ = deactivated ring). Students swap the pH conditions.",
 hook:"Coupling = ArN₂⁺ + activated ring = AZO DYE. Phenol: mild base. Amine: weak acid. Para preferred. Cold always.",
 jee:"diazonium + phenol → p-hydroxyazobenzene (orange/red). E/Z isomerism tested. Methyl orange, Orange II are azo dyes."},

{id:"balz-schiemann",name:"Balz-Schiemann Reaction",type:"Diazonium Chemistry",chapter:"Amines",
 priority:"medium",exam:"both",difficulty:"easy",
 tags:["ArF","NaBF₄","diazonium tetrafluoroborate","pyrolysis","fluorobenzene"],
 summary:"Only reliable route to aryl fluorides. ArN₂⁺ + HBF₄ → ArN₂⁺BF₄⁻ salt → dry pyrolysis → ArF + N₂ + BF₃.",
 reactants:"Benzenediazonium chloride (ArN₂⁺Cl⁻)",
 reagents:"HBF₄ or NaBF₄, then dry heat",
 conditions:"Step 1: form ArN₂⁺BF₄⁻ (precipitates). Step 2: dry pyrolysis of dry salt → ArF.",
 product:"Aryl fluoride (ArF) e.g. fluorobenzene from aniline.",
 mechanism:"Thermal decomposition of diazonium fluoroborate → aryl cation + N₂ + BF₄⁻ → ArF + BF₃",
 stereo:null,
 mistake:"Trying Sandmeyer for ArF — poor results. Must use Balz-Schiemann. It is a TWO-step process: form BF₄⁻ salt FIRST (precipitates out), THEN dry pyrolysis.",
 hook:"Balz-Schiemann = Fluorine's special reaction. BF₄ salt → dry heat → ArF. Sandmeyer cannot make ArF.",
 jee:"'How is fluorobenzene prepared from aniline?' → Diazotisation → Balz-Schiemann. Standard 2-mark question."},

{id:"beckmann",name:"Beckmann Rearrangement",type:"Rearrangement",chapter:"Aldehydes & Ketones",
 priority:"medium",exam:"advanced",difficulty:"hard",
 tags:["oxime","H₂SO₄","lactam","amide","ring expansion","anti migration"],
 summary:"Ketone oxime + H₂SO₄ (or PCl₅) → amide (or lactam for cyclic ketones) via 1,2-migration of the anti group. Ring expansion for cyclic ketones.",
 reactants:"Ketone oxime (R-C(=NOH)-R')",
 reagents:"Conc. H₂SO₄ or PCl₅",
 conditions:"Strong acid conditions. For cyclic ketones: ring expansion (cyclohexanone oxime → caprolactam, the nylon-6 precursor).",
 product:"Amide (R-CO-NHR') or lactam. The group ANTI to -OH migrates.",
 mechanism:"H⁺ protonates oxime -OH → H₂O leaves → nitrilium ion → anti-group migrates to N (1,2-shift) → H₂O attacks → amide.",
 stereo:"The group ANTI (trans) to -OH in the oxime migrates. Stereospecific: different oxime isomers give different amide products.",
 mistake:"Thinking either group can migrate — ONLY the anti group (trans to OH) migrates. Also: cyclic ketone → ring EXPANSION (cyclohexanone → 7-membered lactam, caprolactam). Students expect ring contraction.",
 hook:"Beckmann: anti-group migrates to N. Cyclic ketones → ring EXPANSION. Cyclohexanone oxime → caprolactam (nylon-6 monomer). Anti = moves.",
 jee:"JEE Advanced. 'Cyclohexanone oxime + H₂SO₄ → ?' → caprolactam (ring expansion). Anti-migration rule tested."},

{id:"benzoin",name:"Benzoin Condensation",type:"Condensation",chapter:"Aldehydes & Ketones",
 priority:"medium",exam:"advanced",difficulty:"hard",
 tags:["PhCHO","KCN","benzoin","acyloin","C-C bond","umpolung"],
 summary:"Two molecules of benzaldehyde condense with KCN (cyanide catalyst) to give benzoin (PhCH(OH)COPh). Cyanide acts as umpolung catalyst — reverses carbonyl reactivity.",
 reactants:"Benzaldehyde (PhCHO) — aromatic aldehydes only (not aliphatic)",
 reagents:"KCN (potassium cyanide) or NaCN; aqueous ethanol; heat",
 conditions:"KCN catalyst in aqueous ethanol, ~60°C.",
 product:"Benzoin (PhCH(OH)COPh) — an alpha-hydroxy ketone",
 mechanism:"CN⁻ adds to PhCHO → cyanohydrin → anion (umpolung) → attacks second PhCHO → rearrangement → CN⁻ expelled → benzoin",
 stereo:"Racemic benzoin formed (no stereocontrol with simple KCN).",
 mistake:"Confusing with aldol — benzaldehyde has NO alpha-H so it cannot do aldol. Benzoin uses CN⁻ catalyst. Aliphatic aldehydes do NOT give benzoin condensation with KCN.",
 hook:"Benzoin condensation = PhCHO + PhCHO + KCN → benzoin. CN⁻ flips carbonyl reactivity (umpolung). Only aromatic aldehydes. No alpha-H needed.",
 jee:"JEE Advanced synthesis. 'Benzaldehyde + KCN → ?' → benzoin. Umpolung concept."},

{id:"birch",name:"Birch Reduction",type:"Reduction",chapter:"Aromatic Compounds",
 priority:"medium",exam:"advanced",difficulty:"hard",
 tags:["Na/NH₃","liquid ammonia","1,4-diene","EDG","EWG","regioselectivity"],
 summary:"Partial reduction of aromatic ring to 1,4-cyclohexadiene using Na or Li in liquid NH₃ with alcohol proton source. Not full reduction.",
 reactants:"Benzene or substituted benzene",
 reagents:"Na or Li metal + liquid NH₃ (−33°C) + ROH (proton source)",
 conditions:"Liquid ammonia (−33°C), Na metal, alcohol as proton source essential.",
 product:"1,4-cyclohexadiene. Position of double bonds depends on substituents.",
 mechanism:"Na → solvated e⁻ in NH₃ → radical anion → protonation → second e⁻ → anion → protonation → 1,4-diene.",
 stereo:"EDG: double bonds ON substituted carbons (EDG stays on C=C). EWG: double bonds AWAY from EWG (EWG on sp³ carbon).",
 mistake:"Getting regioselectivity wrong: EDG → double bond ON those carbons. EWG → double bond AWAY. Also: result is 1,4-DIENE, not cyclohexane. Alcohol as proton source is essential.",
 hook:"Birch = Na/NH₃/alcohol = partial ring reduction = 1,4-diene. EDG stays on C=C. EWG ends up on sp³ C. Anisole (EDG) → double bonds on OCH₃-bearing carbons.",
 jee:"JEE Advanced only. 'Birch reduction of anisole → which diene?' Tests regioselectivity rule."},

{id:"claisen",name:"Claisen Condensation",type:"Condensation",chapter:"Carbonyl Compounds",
 priority:"medium",exam:"advanced",difficulty:"hard",
 tags:["ester","NaOEt","beta-ketoester","Claisen","ethyl acetoacetate","C-C bond"],
 summary:"Two ester molecules condense under base (NaOEt) to give a beta-ketoester. Classic: 2 ethyl acetate → ethyl acetoacetate.",
 reactants:"Ester (requires alpha-H for the donor). Two molecules of same ester (Claisen) or different esters (crossed Claisen).",
 reagents:"NaOEt (sodium ethoxide, strong base) in dry ethanol",
 conditions:"Anhydrous ethanol, NaOEt, reflux.",
 product:"Beta-ketoester: 2 CH₃COOEt + NaOEt → CH₃COCH₂COOEt (ethyl acetoacetate) + EtOH",
 mechanism:"NaOEt deprotonates alpha-C of ester → enolate → attacks carbonyl C of second ester → tetrahedral intermediate → EtO⁻ expelled → beta-ketoester",
 stereo:null,
 mistake:"Confusing with aldol (which involves aldehyde/ketone + NaOH). Claisen = ESTER + NaOEt. Also: one ester must have no alpha-H to act as acceptor in crossed Claisen, otherwise mixture results.",
 hook:"Claisen = ester + NaOEt = beta-ketoester. Two esters → one loses EtO⁻. Aldol uses NaOH, Claisen uses NaOEt. Ethyl acetate → ethyl acetoacetate = classic example.",
 jee:"JEE Advanced synthesis. Ethyl acetoacetate synthesis route, active methylene compounds, acetoacetic ester synthesis."},

// ─── BATCH 5 (final) ───────────────────────────────────────────────────────

{id:"decarboxylation",name:"Decarboxylation (Soda Lime)",type:"Decarboxylation",chapter:"Carboxylic Acids",
 priority:"medium",exam:"both",difficulty:"easy",
 tags:["RCOONa","soda lime","NaOH+CaO","n-1 carbons","alkane"],
 summary:"Sodium salt of carboxylic acid + soda lime (NaOH+CaO) + strong heat → alkane with one fewer carbon + CO₂.",
 reactants:"Sodium carboxylate (RCOONa)",
 reagents:"Soda lime = NaOH + CaO (1:3 ratio), strong heat (300°C+)",
 conditions:"Strong heat. CaO prevents NaOH melting and activates it.",
 product:"Alkane (n-1 C): CH₃COONa + soda lime → CH₄ + Na₂CO₃",
 mechanism:"CaO activates carboxylate → decarboxylation → carbanion → protonation → alkane",
 stereo:null,
 mistake:"NaOH alone is insufficient — need soda lime (NaOH + CaO). Confusing with Kolbe electrolysis: Kolbe = 2RCOO⁻ → R-R (coupling, gains C). Soda lime = RCOOH → RH (loses 1 C). Completely opposite.",
 hook:"Soda lime = lose 1 carbon (RH). Kolbe electrolysis = couple carbons (R-R). Thermal = lose. Kolbe = couple.",
 jee:"'Convert RCOONa to RH?' → Soda lime + heat. Common in multistep synthesis."},

{id:"etard",name:"Etard Reaction",type:"Oxidation",chapter:"Aldehydes & Ketones",
 priority:"medium",exam:"both",difficulty:"easy",
 tags:["toluene","CrO₂Cl₂","chromyl chloride","benzaldehyde","CCl₄","selective"],
 summary:"Toluene + CrO₂Cl₂ in CCl₄ → benzaldehyde. Chromyl chloride oxidises side-chain methyl selectively to CHO (not COOH).",
 reactants:"Toluene (PhCH₃) or alkylbenzene with methyl group",
 reagents:"CrO₂Cl₂ (chromyl chloride) in CCl₄",
 conditions:"CCl₄ solvent, room temperature. Then H₂O workup.",
 product:"Benzaldehyde (PhCHO): PhCH₃ + CrO₂Cl₂ → [complex] → H₂O → PhCHO",
 mechanism:"CrO₂Cl₂ forms chromate ester with methyl → hydrolysis gives aldehyde selectively.",
 stereo:null,
 mistake:"Confusing with KMnO₄ which burns toluene methyl all the way to COOH. CrO₂Cl₂ in CCl₄ = selective STOP at CHO. KMnO₄ = COOH.",
 hook:"Etard = CrO₂Cl₂ in CCl₄ = STOPS at ALDEHYDE. KMnO₄ = burns to COOH. E for Early stop.",
 jee:"'Toluene → benzaldehyde: which reagent?' → Etard. 'Toluene → benzoic acid?' → KMnO₄."},

{id:"finkelstein",name:"Finkelstein Reaction",type:"Halogen Exchange",chapter:"Haloalkanes",
 priority:"medium",exam:"mains",difficulty:"easy",
 tags:["NaI","acetone","SN2","RI","Le Chatelier","precipitation"],
 summary:"Alkyl Cl or Br + NaI in dry acetone → alkyl iodide. Driven by insolubility of NaCl/NaBr in acetone (Le Chatelier).",
 reactants:"Alkyl chloride (RCl) or alkyl bromide (RBr)",
 reagents:"NaI, dry acetone",
 conditions:"Dry acetone. NaCl/NaBr precipitate out → equilibrium shifts forward.",
 product:"Alkyl iodide (RI): RCl + NaI → RI + NaCl↓",
 mechanism:"SN2: I⁻ attacks C-Cl (backside). NaCl insoluble in acetone → precipitates → drives equilibrium.",
 stereo:"Inversion of configuration (SN2). (R) → (S).",
 mistake:"Reaction done in water — NaCl soluble in water → equilibrium doesn't shift → doesn't work. Dry acetone is essential. Also fails for 3° RX (SN2 impossible).",
 hook:"Finkelstein = NaI + dry ACETONE. NaCl precipitates → Le Chatelier pulls forward. Water kills it.",
 jee:"Paired with Swartz reaction. Le Chatelier's principle drive = classic JEE concept."},

{id:"fries",name:"Fries Rearrangement",type:"Rearrangement",chapter:"Phenols",
 priority:"medium",exam:"advanced",difficulty:"medium",
 tags:["phenyl ester","AlCl₃","phenol ketone","ortho/para","photo-Fries"],
 summary:"Phenyl ester + AlCl₃ (Lewis acid) → hydroxy aryl ketone. Ester rearranges to ortho or para hydroxyphenyl ketone depending on temperature.",
 reactants:"Phenyl ester (ArOCOR)",
 reagents:"AlCl₃ (Lewis acid), solvent or neat",
 conditions:"Low temp → para product. High temp → ortho product.",
 product:"Hydroxy aryl ketone: PhOCOR + AlCl₃ → o-HOC₆H₄COR (major at high T) + p-HOC₆H₄COR (major at low T)",
 mechanism:"AlCl₃ complexes with ester C=O → acylium migrates onto phenol ring (EAS) → ortho or para ketone",
 stereo:null,
 mistake:"Temperature selectivity is inverted vs intuition: HIGH temperature = ORTHO (thermodynamic control). LOW temperature = PARA (kinetic control). Students mix these up.",
 hook:"Fries = phenyl ester + AlCl₃ = hydroxyphenyl ketone. Low T = para (kinetic). High T = ortho (thermodynamic). Photo-Fries also possible.",
 jee:"JEE Advanced. Temperature-controlled ortho/para selectivity questions."},

{id:"gattermann-koch",name:"Gattermann-Koch Reaction",type:"Electrophilic Aromatic Substitution",chapter:"Aldehydes & Ketones",
 priority:"medium",exam:"both",difficulty:"medium",
 tags:["benzaldehyde","CO","HCl","AlCl₃","CuCl","formylation","benzene"],
 summary:"Benzene + CO + HCl + AlCl₃/CuCl → benzaldehyde. Formylation of activated benzene rings.",
 reactants:"Benzene or activated substituted benzene",
 reagents:"CO + HCl gas, anhydrous AlCl₃, CuCl catalyst, high pressure",
 conditions:"Anhydrous AlCl₃, CuCl, CO + HCl, high pressure. Fails on deactivated rings.",
 product:"Benzaldehyde (PhCHO) from benzene.",
 mechanism:"CO + HCl + AlCl₃/CuCl → formyl cation (HCO⁺) → EAS on benzene → benzaldehyde.",
 stereo:null,
 mistake:"Thinking it works on phenol (use Reimer-Tiemann for phenol). G-K is for BENZENE rings. Also fails on deactivated rings.",
 hook:"G-K = CO + HCl + AlCl₃ on BENZENE = benzaldehyde. Reimer-Tiemann = CHCl₃ + NaOH on PHENOL. Never swap.",
 jee:"'Benzene → benzaldehyde directly: which reaction?' → Gattermann-Koch."},

{id:"hvz",name:"Hell-Volhard-Zelinsky (HVZ)",type:"Halogenation",chapter:"Carboxylic Acids",
 priority:"medium",exam:"both",difficulty:"medium",
 tags:["alpha halogenation","Br₂","phosphorus","RCOOH","alpha-bromo acid","acyl bromide"],
 summary:"Alpha-halogenation of carboxylic acids using Br₂ + red phosphorus. Phosphorus converts acid to acyl bromide first, which enolises far more easily.",
 reactants:"Carboxylic acid with alpha-H (RCH₂COOH)",
 reagents:"Br₂ + red phosphorus (or PBr₃)",
 conditions:"P + Br₂ → PBr₃ in situ → RCOOH → RCOBr → enolisation → Br₂ at alpha-C → H₂O workup.",
 product:"Alpha-bromo carboxylic acid: CH₃COOH → BrCH₂COOH (bromoacetic acid)",
 mechanism:"P + Br₂ → PBr₃ → RCOOH → RCOBr → enol → Br₂ at alpha → alpha-bromo acyl bromide → H₂O → alpha-bromo acid.",
 stereo:"New stereocentre at alpha-C → racemic mixture (enol face attack from both sides).",
 mistake:"Applying to ketones or aldehydes — HVZ is SPECIFICALLY for carboxylic acids. Without phosphorus, RCOOH barely reacts with Br₂. Phosphorus is essential.",
 hook:"HVZ = alpha-Bromo CARBOXYLIC ACID. P + Br₂ = PBr₃ activates acid → acyl bromide enolises → Br₂ attacks alpha. No P = no reaction.",
 jee:"Alpha-bromo acid + NH₃ (SN2) → alpha-amino acid. Links HVZ to amino acid synthesis."},

{id:"perkin",name:"Perkin Reaction",type:"Condensation",chapter:"Carboxylic Acids",
 priority:"medium",exam:"advanced",difficulty:"medium",
 tags:["ArCHO","acetic anhydride","NaOAc","cinnamic acid","E-alkene","alpha,beta-unsaturated acid"],
 summary:"Aromatic aldehyde + acetic anhydride + NaOAc → alpha,beta-unsaturated carboxylic acid (trans). Classic: PhCHO → trans-cinnamic acid.",
 reactants:"Aromatic aldehyde (ArCHO) — benzaldehyde is textbook",
 reagents:"Acetic anhydride (Ac₂O), sodium acetate (NaOAc, mild base)",
 conditions:"Heat 150–200°C. NaOAc acts as mild base.",
 product:"Trans-cinnamic acid: PhCHO + Ac₂O → Ph-CH=CH-COOH + CH₃COOH",
 mechanism:"NaOAc deprotonates Ac₂O at alpha → enolate attacks ArCHO → beta-hydroxy → dehydration → alpha,beta-unsaturated acid.",
 stereo:"Trans (E) isomer is major product (thermodynamic control).",
 mistake:"Confusing with aldol — aldol uses NaOH, Perkin uses NaOAc + ACID ANHYDRIDE as carbon source. Aliphatic aldehydes work poorly.",
 hook:"Perkin = PhCHO + Ac₂O + NaOAc = TRANS-CINNAMIC ACID. Perkin = cinnamic acid (always). JEE Advanced synthesis final step.",
 jee:"'Which reaction gives trans-cinnamic acid from benzaldehyde?' → Perkin. Often the last step in multistep synthesis."},

{id:"pinacol",name:"Pinacol-Pinacolone Rearrangement",type:"Rearrangement",chapter:"Alcohols",
 priority:"medium",exam:"advanced",difficulty:"hard",
 tags:["1,2-diol","vicinal diol","H⁺","1,2-shift","carbocation","pinacolone"],
 summary:"Vicinal diol (1,2-diol) treated with H⁺ → 1,2-migration of alkyl/aryl group to adjacent carbocation → ketone (pinacolone). Classic: pinacol → pinacolone.",
 reactants:"Vicinal diol (1,2-diol): pinacol = (CH₃)₂C(OH)-C(OH)(CH₃)₂",
 reagents:"H⁺ (dil. H₂SO₄ or HCl)",
 conditions:"Aqueous acid, heat",
 product:"Ketone: pinacol + H⁺ → pinacolone ((CH₃)₃C-CO-CH₃, 3,3-dimethylbutan-2-one)",
 mechanism:"H⁺ protonates one OH → H₂O leaves → tertiary carbocation → 1,2-methyl shift → oxocarbenium ion stabilised by O lone pair → deprotonation → ketone.",
 stereo:"The migrating group is anti-periplanar to the leaving group in the concerted version.",
 mistake:"Thinking the less stable carbocation forms first — no, one OH is protonated and leaves to give the MORE stable initial carbocation. Then migration gives an even more stable oxocarbenium. Students mix up which carbon loses OH first.",
 hook:"Pinacol → Pinacolone: 1,2-diol + H⁺ → 1,2-shift → ketone. More stable intermediate drives migration. Diol → ketone (not alcohol).",
 jee:"JEE Advanced. 'Pinacol + H⁺ → ?' → pinacolone. 1,2-shift mechanism with driving force from oxocarbenium stabilisation."},

{id:"wurtz",name:"Wurtz Reaction",type:"C-C Coupling",chapter:"Haloalkanes",
 priority:"medium",exam:"both",difficulty:"easy",
 tags:["2RX + 2Na","dry ether","alkane","C-C bond","sodium"],
 summary:"Two alkyl halides + Na in dry ether → higher alkane via C-C coupling. Always doubles (or crosses) the carbon count.",
 reactants:"Alkyl halide (RX) — primary best. Tertiary fails (elimination).",
 reagents:"Na metal (2 eq), dry ether",
 conditions:"Dry ether, strictly anhydrous, reflux",
 product:"Alkane: 2RX + 2Na → R-R + 2NaX",
 mechanism:"RX + 2Na → RNa (organosodium) + NaX; RNa + RX → R-R + NaX",
 stereo:null,
 mistake:"Using a single RX to make an odd-carbon alkane — impossible. Single halide always gives even-carbon product. Mixed Wurtz (two different RX) gives three products (symmetrical + unsymmetrical alkane mixture).",
 hook:"Wurtz = two RX + Na = doubled alkane. One RX = even-carbon product. Mixed Wurtz = messy mixture.",
 jee:"'Which alkane CANNOT be made by Wurtz from one halide?' → any odd-carbon alkane."},

{id:"wurtz-fittig",name:"Wurtz-Fittig Reaction",type:"C-C Coupling",chapter:"Haloalkanes & Haloarenes",
 priority:"medium",exam:"mains",difficulty:"easy",
 tags:["ArX","RX","Na","alkylarene","toluene from PhBr+CH₃Br"],
 summary:"Aryl halide + alkyl halide + Na → alkylarene. Distinct from Fittig (ArX+ArX+Na → biaryl) and Wurtz (RX+RX+Na → alkane).",
 reactants:"Aryl halide (ArX) + Alkyl halide (RX)",
 reagents:"Na metal, dry ether",
 conditions:"Dry ether, anhydrous",
 product:"Alkylarene: PhBr + CH₃Br + 2Na → PhCH₃ + 2NaBr",
 mechanism:"Organosodium intermediate; aryl and alkyl groups couple",
 stereo:null,
 mistake:"Three-way confusion: Wurtz = alkyl+alkyl → alkane. Fittig = aryl+aryl → biaryl. Wurtz-Fittig = aryl+alkyl → alkylarene.",
 hook:"Fittig = two aryls = biaryl. Wurtz-Fittig = aryl + alkyl = alkylarene. Wurtz joins Fittig = mixed coupling.",
 jee:"Standard 3-way distinction question."},

{id:"dow",name:"Dow Process (Chlorobenzene Hydrolysis)",type:"Nucleophilic Aromatic Substitution",chapter:"Haloarenes",
 priority:"low",exam:"advanced",difficulty:"medium",
 tags:["chlorobenzene","NaOH","350°C","300 atm","sodium phenoxide","phenol","benzyne"],
 summary:"Chlorobenzene + NaOH (350°C, 300 atm, Cu catalyst) → sodium phenoxide → H⁺ → phenol. Industrial route to phenol. Proceeds via benzyne (elimination-addition).",
 reactants:"Chlorobenzene (C₆H₅Cl)",
 reagents:"NaOH (aq, very conc.), Cu catalyst",
 conditions:"350°C, 300 atm — extremely harsh.",
 product:"Phenol (C₆H₅OH) via sodium phenoxide intermediate",
 mechanism:"Benzyne (aryne) mechanism: E2-like elimination of HCl → benzyne → OH⁻ addition → sodium phenoxide → H⁺ → phenol.",
 stereo:null,
 mistake:"Treating it as simple SN2 on benzene — benzene rings do NOT do SN2. The mechanism goes through benzyne (aryne). Harsh conditions (350°C, 300 atm) are essential.",
 hook:"Dow Process = chlorobenzene + NaOH at extreme T & P → phenol via benzyne. Not SN2 — benzyne mechanism. Industrial phenol production.",
 jee:"JEE Advanced. Benzyne mechanism. 'Why harsh conditions for ArCl vs RCl?' — resonance stabilisation makes ArCl less reactive."},

{id:"kolbe-electrolysis",name:"Kolbe Electrolysis",type:"C-C Coupling",chapter:"Carboxylic Acids",
 priority:"low",exam:"advanced",difficulty:"medium",
 tags:["electrolysis","RCOO⁻","anode","R-R","decarboxylation","coupling"],
 summary:"Electrolysis of carboxylate salt solution: 2RCOO⁻ → R-R + 2CO₂ at anode. Electrochemical C-C coupling via radical mechanism.",
 reactants:"Carboxylate salt (RCOONa) in aqueous solution",
 reagents:"Electrolysis — platinum anode, DC current",
 conditions:"Aqueous RCOONa solution, electrolysis, Pt anode",
 product:"Symmetrical alkane: 2RCOO⁻ → R-R + 2CO₂ + 2e⁻ (at anode). e.g. 2CH₃COO⁻ → C₂H₆",
 mechanism:"RCOO⁻ oxidised at anode → RCOO• → loses CO₂ → R• → R• + R• → R-R (radical coupling)",
 stereo:null,
 mistake:"Confusing with soda lime decarboxylation: soda lime gives RH (lose 1C). Kolbe electrolysis gives R-R (doubled carbons). Thermal = lose. Kolbe = couple.",
 hook:"Kolbe electrolysis = 2RCOO⁻ at anode → R-R + 2CO₂. Soda lime = RH (n-1 C). Opposite outcomes!",
 jee:"JEE: contrast with soda lime decarboxylation. Same starting material → opposite products depending on method."},

];

export const QUICK_REF: QuickRefTable[] = [
  {title:"Acidity Order of Organic Compounds",rows:[
    ["Carboxylic acids (RCOOH)","pKa ~4–5","Most acidic organic"],
    ["Phenol (ArOH)","pKa ~10","More acidic than alcohols"],
    ["Water (H₂O)","pKa ~15.7","Reference"],
    ["Alcohol (ROH)","pKa ~16–18","Slightly less acidic than water"],
    ["Terminal alkyne (RC≡CH)","pKa ~25","sp C-H"],
    ["Alkene (sp² C-H)","pKa ~44","Very weakly acidic"],
    ["Alkane (sp³ C-H)","pKa ~50","Essentially non-acidic"],
  ]},
  {title:"Leaving Group Ability",rows:[
    ["I⁻ (iodide)","Best LG","Weakest conjugate base"],
    ["Br⁻","Good LG",""],
    ["Cl⁻","Moderate LG",""],
    ["TsO⁻ (tosylate)","Excellent LG","Common in synthesis"],
    ["H₂O (after protonation)","Good LG","Why ROH needs acid"],
    ["OH⁻ (hydroxide)","Very poor","Must protonate first"],
    ["F⁻","Worst halide LG","Strong base = poor LG"],
  ]},
  {title:"Carbon Oxidation States",rows:[
    ["CH₄ (methane)","−4","Most reduced"],
    ["CH₃OH (methanol)","−2",""],
    ["HCHO (formaldehyde)","0",""],
    ["HCOOH (formic acid)","+2",""],
    ["CO₂","+4","Most oxidised"],
  ]},
];

export const TYPE_COLOR: Record<string, [string, string, string]> = {
  "C-C Coupling":                        ["rgba(96,165,250,0.12)","rgba(96,165,250,0.35)","#93c5fd"],
  "Condensation":                        ["rgba(139,92,246,0.12)","rgba(139,92,246,0.35)","#c4b5fd"],
  "Diazonium Chemistry":                 ["rgba(251,191,36,0.12)","rgba(251,191,36,0.35)","#fcd34d"],
  "Disproportionation":                  ["rgba(96,165,250,0.12)","rgba(96,165,250,0.35)","#93c5fd"],
  "Electrophilic Aromatic Substitution": ["rgba(251,146,60,0.12)","rgba(251,146,60,0.35)","#fdba74"],
  "Reduction":                           ["rgba(248,113,113,0.12)","rgba(248,113,113,0.35)","#fca5a5"],
  "Oxidation":                           ["rgba(251,113,133,0.12)","rgba(251,113,133,0.35)","#fda4af"],
  "Halogenation":                        ["rgba(251,191,36,0.12)","rgba(251,191,36,0.35)","#fcd34d"],
  "Nucleophilic Addition":               ["rgba(52,211,153,0.12)","rgba(52,211,153,0.35)","#6ee7b7"],
  "SN2 Substitution":                    ["rgba(96,165,250,0.12)","rgba(96,165,250,0.35)","#93c5fd"],
  "Rearrangement":                       ["rgba(251,146,60,0.12)","rgba(251,146,60,0.35)","#fdba74"],
  "Amine Synthesis":                     ["rgba(139,92,246,0.12)","rgba(139,92,246,0.35)","#c4b5fd"],
  "Amine Test":                          ["rgba(52,211,153,0.12)","rgba(52,211,153,0.35)","#6ee7b7"],
  "Decarboxylation":                     ["rgba(96,165,250,0.12)","rgba(96,165,250,0.35)","#93c5fd"],
  "Acyl Substitution":                   ["rgba(52,211,153,0.12)","rgba(52,211,153,0.35)","#6ee7b7"],
  "Carboxylation":                       ["rgba(52,211,153,0.12)","rgba(52,211,153,0.35)","#6ee7b7"],
  "Halogen Exchange":                    ["rgba(251,191,36,0.12)","rgba(251,191,36,0.35)","#fcd34d"],
  "Chain Homologation":                  ["rgba(139,92,246,0.12)","rgba(139,92,246,0.35)","#c4b5fd"],
  "Nucleophilic Aromatic Substitution":  ["rgba(248,113,113,0.12)","rgba(248,113,113,0.35)","#fca5a5"],
};
