import type { Reaction, QuickRefTable } from './types';

import reactionsData from './reactions.json';

export const REACTIONS: Reaction[] = reactionsData as Reaction[];

export const QUICK_REF: QuickRefTable[] = [
  {
    title: "pKa values",
    headers: ["Acid", "Approximate pKa", "Conjugate Base"],
    rows: [
      { name: "HSbF₆", value: "−12", note: "SbF₆⁻ (Weakest base)" },
      { name: "HI", value: "−10", note: "I⁻" },
      { name: "H₂SO₄", value: "−9", note: "HSO₄⁻" },
      { name: "HBr", value: "−9", note: "Br⁻" },
      { name: "HCl", value: "−7", note: "Cl⁻" },
      { name: "C₆H₅SO₃H", value: "−6.5", note: "C₆H₅SO₃⁻" },
      { name: "(CH₃)₂O⁺H", value: "−3.8", note: "(CH₃)₂O" },
      { name: "(CH₃)₂C=O⁺H", value: "−2.9", note: "(CH₃)₂C=O" },
      { name: "CH₃O⁺H₂", value: "−2.5", note: "CH₃OH" },
      { name: "H₃O⁺", value: "−1.74", note: "H₂O" },
      { name: "HNO₃", value: "−1.4", note: "NO₃⁻" },
      { name: "CF₃CO₂H", value: "0.18", note: "CF₃CO₂⁻" },
      { name: "HF", value: "3.2", note: "F⁻" },
      { name: "C₆H₅CO₂H", value: "4.21", note: "C₆H₅CO₂⁻" },
      { name: "C₆H₅NH₃⁺", value: "4.63", note: "C₆H₅NH₂" },
      { name: "CH₃CO₂H", value: "4.75", note: "CH₃CO₂⁻" },
      { name: "H₂CO₃", value: "6.35", note: "HCO₃⁻" },
      { name: "CH₃COCH₂COCH₃", value: "9.0", note: "CH₃COC⁻HCOCH₃" },
      { name: "NH₄⁺", value: "9.2", note: "NH₃" },
      { name: "C₆H₅OH", value: "9.9", note: "C₆H₅O⁻" },
      { name: "HCO₃⁻", value: "10.2", note: "CO₃²⁻" },
      { name: "CH₃NH₃⁺", value: "10.6", note: "CH₃NH₂" },
      { name: "H₂O", value: "15.7", note: "HO⁻" },
      { name: "CH₃CH₂OH", value: "16", note: "CH₃CH₂O⁻" },
      { name: "(CH₃)₃COH", value: "18", note: "(CH₃)₃CO⁻" },
      { name: "CH₃COCH₃", value: "19.2", note: "⁻CH₂COCH₃" },
      { name: "HC≡CH", value: "25", note: "HC≡C⁻" },
      { name: "C₆H₅NH₂", value: "31", note: "C₆H₅NH⁻" },
      { name: "H₂", value: "35", note: "H⁻" },
      { name: "(i-Pr)₂NH", value: "36", note: "(i-Pr)₂N⁻" },
      { name: "NH₃", value: "38", note: "⁻NH₂" },
      { name: "CH₂=CH₂", value: "44", note: "CH₂=CH⁻" },
      { name: "CH₃CH₃", value: "50", note: "CH₃CH₂⁻ (Strongest base)" },
    ]
  },

  {
    title: "Carbocation stability",
    description: "pKr+ provides a quantitative measure of carbocation stability. A HIGHER (more positive) value indicates GREATER stability. Determined by equilibrium of carbocation with water.",
    headers: ["Carbocation", "pKr+", "Category"],
    rows: [
      { name: "Triphenylmethyl", value: "-6.63", note: "Triarylmethyl" },
      { name: "4,4',4''-Trimethyltriphenylmethyl", value: "-3.56", note: "Triarylmethyl" },
      { name: "4-Methoxytriphenylmethyl", value: "-3.40", note: "Triarylmethyl" },
      { name: "4,4'-Dimethoxytriphenylmethyl", value: "-1.24", note: "Triarylmethyl" },
      { name: "4,4',4''-Trimethoxytriphenylmethyl", value: "+0.82", note: "Triarylmethyl" },
      { name: "4,4',4''-Trichlorotriphenylmethyl", value: "-7.74", note: "Triarylmethyl" },
      { name: "4-Nitrotriphenylmethyl", value: "-9.15", note: "Triarylmethyl" },
      { name: "4,4',4''-Trinitrotriphenylmethyl", value: "-16.27", note: "Triarylmethyl" },
      { name: "4,4',4''-Tri(dimethylamino)triphenylmethyl", value: "+9.36", note: "Triarylmethyl" },
      { name: "Sesquixanthydryl", value: "+9.05", note: "Triarylmethyl" },
      { name: "Diphenylmethyl", value: "-13.3", note: "Diarylmethyl" },
      { name: "4,4'-Dimethyldiphenylmethyl", value: "-10.4", note: "Diarylmethyl" },
      { name: "4,4'-Dimethoxydiphenylmethyl", value: "-5.71", note: "Diarylmethyl" },
      { name: "2,2',4,4',6,6'-Hexamethyldiphenylmethyl", value: "-6.6", note: "Diarylmethyl" },
      { name: "4,4'-Dichlorodiphenylmethyl", value: "-13.96", note: "Diarylmethyl" },
      { name: "Benzyl", value: "-20", note: "Miscellaneous" },
      { name: "2-Phenyl-2-propyl", value: "-12.3", note: "Miscellaneous" },
      { name: "Tricyclopropylmethyl", value: "-2.3", note: "Miscellaneous" },
      { name: "Tropylium (cycloheptatrienyl)", value: "+4.7", note: "Miscellaneous" },
      { name: "Triphenylcyclopropenyl", value: "+3.1", note: "Miscellaneous" },
      { name: "Trimethylcyclopropenyl", value: "+7.8", note: "Miscellaneous" },
      { name: "Tricyclopropylcyclopropenyl", value: "+9.7", note: "Miscellaneous" },
    ]
  },
  {
    title: "Bond Energies (Inorganic)",
    headers: ["Bond", "Energy (kJ/mol)", "Category"],
    rows: [
      { name: "H–H", value: "432", note: "Hydrogen" },
      { name: "H–B", value: "389", note: "Hydrogen" },
      { name: "H–C", value: "411", note: "Hydrogen" },
      { name: "H–N", value: "386", note: "Hydrogen" },
      { name: "H–O", value: "459", note: "Hydrogen" },
      { name: "H–S", value: "363", note: "Hydrogen" },
      { name: "H–F", value: "565", note: "Hydrogen" },
      { name: "H–Cl", value: "428", note: "Hydrogen" },
      { name: "H–Br", value: "362", note: "Hydrogen" },
      { name: "H–I", value: "295", note: "Hydrogen" },
      { name: "B–C", value: "372", note: "Group 13 (Boron)" },
      { name: "B–O", value: "536", note: "Group 13 (Boron)" },
      { name: "B=O", value: "636", note: "Group 13 (Boron)" },
      { name: "B–F", value: "613", note: "Group 13 (Boron)" },
      { name: "B–Cl", value: "456", note: "Group 13 (Boron)" },
      { name: "B–Br", value: "377", note: "Group 13 (Boron)" },
      { name: "C–C", value: "346", note: "Group 14 (Carbon)" },
      { name: "C=C", value: "602", note: "Group 14 (Carbon)" },
      { name: "C≡C", value: "835", note: "Group 14 (Carbon)" },
      { name: "C–N", value: "305", note: "Group 14 (Carbon)" },
      { name: "C=N", value: "615", note: "Group 14 (Carbon)" },
      { name: "C≡N", value: "887", note: "Group 14 (Carbon)" },
      { name: "C–P", value: "264", note: "Group 14 (Carbon)" },
      { name: "C–O", value: "358", note: "Group 14 (Carbon)" },
      { name: "C=O", value: "799", note: "Group 14 (Carbon)" },
      { name: "C≡O", value: "1072", note: "Group 14 (Carbon)" },
      { name: "C–F", value: "485", note: "Group 14 (Carbon)" },
      { name: "C–Cl", value: "327", note: "Group 14 (Carbon)" },
      { name: "C–Br", value: "310", note: "Group 14 (Carbon)" },
      { name: "C–I", value: "213", note: "Group 14 (Carbon)" },
      { name: "Si–Si", value: "222", note: "Group 14 (Silicon)" },
      { name: "Si–O", value: "452", note: "Group 14 (Silicon)" },
      { name: "Si=O", value: "642", note: "Group 14 (Silicon)" },
      { name: "Si–F", value: "565", note: "Group 14 (Silicon)" },
      { name: "Si–Cl", value: "381", note: "Group 14 (Silicon)" },
      { name: "Si–Br", value: "310", note: "Group 14 (Silicon)" },
      { name: "Si–I", value: "234", note: "Group 14 (Silicon)" },
      { name: "N–N", value: "247", note: "Group 15 (Nitrogen)" },
      { name: "N=N", value: "418", note: "Group 15 (Nitrogen)" },
      { name: "N≡N", value: "942", note: "Group 15 (Nitrogen)" },
      { name: "N–O", value: "201", note: "Group 15 (Nitrogen)" },
      { name: "N=O", value: "607", note: "Group 15 (Nitrogen)" },
      { name: "N–F", value: "278", note: "Group 15 (Nitrogen)" },
      { name: "N–Cl", value: "192", note: "Group 15 (Nitrogen)" },
      { name: "P–P", value: "200", note: "Group 15 (Phosphorus)" },
      { name: "P≡P", value: "481", note: "Group 15 (Phosphorus)" },
      { name: "P–O", value: "335", note: "Group 15 (Phosphorus)" },
      { name: "P–F", value: "490", note: "Group 15 (Phosphorus)" },
      { name: "P–Cl", value: "326", note: "Group 15 (Phosphorus)" },
      { name: "P–Br", value: "264", note: "Group 15 (Phosphorus)" },
      { name: "P–I", value: "184", note: "Group 15 (Phosphorus)" },
      { name: "O–O", value: "142", note: "Group 16 (Oxygen)" },
      { name: "O=O", value: "494", note: "Group 16 (Oxygen)" },
      { name: "O=S", value: "523", note: "Group 16 (Oxygen)" },
      { name: "O–Xe", value: "84", note: "Group 16 (Oxygen)" },
      { name: "O–F", value: "190", note: "Group 16 (Oxygen)" },
      { name: "O–Cl", value: "218", note: "Group 16 (Oxygen)" },
      { name: "O–Br", value: "201", note: "Group 16 (Oxygen)" },
      { name: "O–I", value: "201", note: "Group 16 (Oxygen)" },
      { name: "S–S", value: "268", note: "Group 16 (Sulfur)" },
      { name: "S=S", value: "425", note: "Group 16 (Sulfur)" },
      { name: "S–F", value: "327", note: "Group 16 (Sulfur)" },
      { name: "S–Cl", value: "271", note: "Group 16 (Sulfur)" },
      { name: "F–F", value: "155", note: "Group 17 (Fluorine)" },
      { name: "F–Kr", value: "50", note: "Group 17 (Fluorine)" },
      { name: "F–Xe", value: "133", note: "Group 17 (Fluorine)" },
      { name: "F–Cl", value: "249", note: "Group 17 (Fluorine)" },
      { name: "F–Br", value: "250", note: "Group 17 (Fluorine)" },
      { name: "F–I", value: "278", note: "Group 17 (Fluorine)" },
      { name: "Cl–Cl", value: "240", note: "Group 17 (Chlorine)" },
      { name: "Cl–Br", value: "216", note: "Group 17 (Chlorine)" },
      { name: "Cl–I", value: "208", note: "Group 17 (Chlorine)" },
      { name: "Br–Br", value: "190", note: "Group 17 (Bromine)" },
      { name: "Br–I", value: "175", note: "Group 17 (Bromine)" },
      { name: "I–I", value: "149", note: "Group 17 (Iodine)" },
    ]
  },
  {
    title: "Bond Energies (Organic)",
    headers: ["Bond", "Energy (kJ/mol)", "Category"],
    rows: [
      { name: "H–F", value: "569", note: "H–Z bonds" },
      { name: "H–Cl", value: "431", note: "H–Z bonds" },
      { name: "H–Br", value: "368", note: "H–Z bonds" },
      { name: "H–I", value: "297", note: "H–Z bonds" },
      { name: "H–OH", value: "498", note: "H–Z bonds" },
      { name: "H–H", value: "435", note: "Z–Z bonds" },
      { name: "F–F", value: "159", note: "Z–Z bonds" },
      { name: "Cl–Cl", value: "242", note: "Z–Z bonds" },
      { name: "Br–Br", value: "192", note: "Z–Z bonds" },
      { name: "I–I", value: "151", note: "Z–Z bonds" },
      { name: "HO–OH", value: "213", note: "Z–Z bonds" },
      { name: "CH₃–H", value: "435", note: "R–H bonds" },
      { name: "CH₃CH₂–H", value: "410", note: "R–H bonds" },
      { name: "CH₃CH₂CH₂–H", value: "410", note: "R–H bonds" },
      { name: "(CH₃)₂CH–H", value: "397", note: "R–H bonds" },
      { name: "(CH₃)₃C–H", value: "381", note: "R–H bonds" },
      { name: "CH₂=CH–H", value: "435", note: "R–H bonds" },
      { name: "HC≡C–H", value: "523", note: "R–H bonds" },
      { name: "CH₂=CHCH₂–H", value: "364", note: "R–H bonds" },
      { name: "C₆H₅–H", value: "460", note: "R–H bonds" },
      { name: "C₆H₅CH₂–H", value: "356", note: "R–H bonds" },
      { name: "CH₃–CH₃", value: "368", note: "R–R bonds" },
      { name: "CH₃–CH₂CH₃", value: "356", note: "R–R bonds" },
      { name: "CH₃–CH=CH₂", value: "385", note: "R–R bonds" },
      { name: "CH₃–C≡CH", value: "489", note: "R–R bonds" },
      { name: "CH₃–F", value: "456", note: "R–X bonds" },
      { name: "CH₃–Cl", value: "351", note: "R–X bonds" },
      { name: "CH₃–Br", value: "293", note: "R–X bonds" },
      { name: "CH₃–I", value: "234", note: "R–X bonds" },
      { name: "CH₃CH₂–F", value: "448", note: "R–X bonds" },
      { name: "CH₃CH₂–Cl", value: "339", note: "R–X bonds" },
      { name: "CH₃CH₂–Br", value: "285", note: "R–X bonds" },
      { name: "CH₃CH₂–I", value: "222", note: "R–X bonds" },
      { name: "(CH₃)₂CH–F", value: "444", note: "R–X bonds" },
      { name: "(CH₃)₂CH–Cl", value: "335", note: "R–X bonds" },
      { name: "(CH₃)₂CH–Br", value: "285", note: "R–X bonds" },
      { name: "(CH₃)₂CH–I", value: "222", note: "R–X bonds" },
      { name: "(CH₃)₃C–F", value: "444", note: "R–X bonds" },
      { name: "(CH₃)₃C–Cl", value: "331", note: "R–X bonds" },
      { name: "(CH₃)₃C–Br", value: "272", note: "R–X bonds" },
      { name: "(CH₃)₃C–I", value: "209", note: "R–X bonds" },
      { name: "CH₃–OH", value: "389", note: "R–OH bonds" },
      { name: "CH₃CH₂–OH", value: "393", note: "R–OH bonds" },
      { name: "CH₃CH₂CH₂–OH", value: "385", note: "R–OH bonds" },
      { name: "(CH₃)₂CH–OH", value: "401", note: "R–OH bonds" },
      { name: "(CH₃)₃C–OH", value: "401", note: "R–OH bonds" },
      { name: "CH₂=CH₂", value: "635", note: "Other bonds" },
      { name: "HC≡CH", value: "837", note: "Other bonds" },
      { name: "O=C=O", value: "535", note: "Other bonds" },
      { name: "O₂", value: "497", note: "Other bonds" },
    ]
  }
];

export const TYPE_COLOR: Record<string, [string, string, string]> = {
  "C-C Coupling": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Condensation": ["rgba(167,139,250,0.06)", "rgba(167,139,250,0.2)", "#c4b5fd"],
  "Diazonium Chemistry": ["rgba(251,191,36,0.06)", "rgba(251,191,36,0.2)", "#fbbf24"],
  "Disproportionation": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Electrophilic Aromatic Substitution": ["rgba(251,146,60,0.06)", "rgba(251,146,60,0.2)", "#fdba74"],
  "Reduction": ["rgba(244,114,182,0.06)", "rgba(244,114,182,0.2)", "#f9a8d4"],
  "Oxidation": ["rgba(251,113,133,0.06)", "rgba(251,113,133,0.2)", "#fda4af"],
  "Halogenation": ["rgba(251,191,36,0.06)", "rgba(251,191,36,0.2)", "#fbbf24"],
  "Nucleophilic Addition": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "SN2 Substitution": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Rearrangement": ["rgba(251,146,60,0.06)", "rgba(251,146,60,0.2)", "#fdba74"],
  "Amine Synthesis": ["rgba(167,139,250,0.06)", "rgba(167,139,250,0.2)", "#c4b5fd"],
  "Amine Test": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "Decarboxylation": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Acyl Substitution": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "Carboxylation": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "Halogen Exchange": ["rgba(251,191,36,0.06)", "rgba(251,191,36,0.2)", "#fbbf24"],
  "Chain Homologation": ["rgba(167,139,250,0.06)", "rgba(167,139,250,0.2)", "#c4b5fd"],
  "Nucleophilic Aromatic Substitution": ["rgba(244,114,182,0.06)", "rgba(244,114,182,0.2)", "#f9a8d4"],
};
