import type { Reaction, QuickRefTable } from './types';

export const REACTIONS: Reaction[] = [

  {
    id: "aldol", name: "Aldol Condensation", type: "Condensation", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["enolate", "alpha-H", "NaOH", "beta-hydroxy carbonyl", "crotonaldehyde"],
    summary: "Aldehydes or ketones with at least one alpha-H undergo base-catalysed condensation: enolate attacks a second carbonyl to give a beta-hydroxy carbonyl compound (aldol product). On heating, water is eliminated to yield an alpha,beta-unsaturated carbonyl (condensation product). Cross-aldol between two different carbonyls gives a mixture — JEE Advanced tests which product predominates.",
    reactants: "Aldehyde or ketone with at least one alpha-H",
    reagents: "Dil. NaOH (base) or dil. HCl (acid)",
    conditions: "Cold dil. NaOH = aldol product. Heat = dehydration = condensation product.",
    product: "Cold: beta-hydroxy carbonyl. Heat: alpha,beta-unsaturated carbonyl. Classic: CH₃CHO → crotonaldehyde (CH₃CH=CHCHO).",
    mechanism: "Enolate attacks carbonyl C of second molecule → aldol. Heating → E1cb dehydration → alpha,beta-unsaturated product.",
    stereo: "New stereocentre at beta-C in aldol product → racemic mixture without chiral catalyst.",
    mistake: "Applying to HCHO or PhCHO — no alpha-H → they do Cannizzaro, NOT aldol. Also confusing the cold (aldol) and hot (condensation) products — they are different.",
    hook: "No alpha-H = no aldol = Cannizzaro instead. Cold = aldol. Heat = condensation. Acetaldehyde → crotonaldehyde is the go-to JEE example.",
    jee: "Very high frequency. Cross-aldol with two different carbonyls gives a mixture — JEE Advanced tests which product predominates."
  },

  {
    id: "cannizzaro", name: "Cannizzaro Reaction", type: "Disproportionation", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["no alpha-H", "HCHO", "PhCHO", "conc NaOH", "hydride transfer"],
    summary: "Aldehydes that lack alpha-H (HCHO, PhCHO, CCl₃CHO) undergo self-oxidation-reduction in concentrated NaOH: one molecule is oxidised to a carboxylate salt while the other is reduced to a primary alcohol via hydride transfer. In a crossed Cannizzaro (HCHO + PhCHO), HCHO is always oxidised and PhCHO is always reduced — a classic JEE trap.",
    reactants: "Aldehydes with NO alpha-H: HCHO, PhCHO, CCl₃CHO",
    reagents: "Conc. NaOH (concentrated — dilute gives aldol if alpha-H present)",
    conditions: "Concentrated aqueous NaOH, mild heat",
    product: "Carboxylate salt + primary alcohol. HCHO + NaOH → HCOONa + CH₃OH",
    mechanism: "OH⁻ attacks C=O → tetrahedral alkoxide → H⁻ transfer (rate-determining) to second aldehyde → two products.",
    stereo: null,
    mistake: "Using dilute NaOH — need CONC. In crossed Cannizzaro (HCHO + PhCHO), HCHO is ALWAYS oxidised (gives HCOO⁻), PhCHO is ALWAYS reduced (gives PhCH₂OH). Students reverse these roles.",
    hook: "Cannizzaro = CAN'T do aldol (no alpha-H). CONC NaOH. One up (acid salt), one down (alcohol). HCHO always sacrifices itself in crossed Cannizzaro.",
    jee: "Crossed Cannizzaro popular in JEE Advanced — given products, identify reaction and roles of each aldehyde."
  },

  {
    id: "carbylamine", name: "Carbylamine Reaction", type: "Amine Test", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["isocyanide", "1° amine only", "CHCl₃", "KOH", "foul smell"],
    summary: "Primary amines (aliphatic or aromatic) react with CHCl₃ and alcoholic KOH to form isocyanides (R-N≡C) — compounds with an intensely foul, nauseating odour. The reaction proceeds via dichlorocarbene (:CCl₂) intermediate and is strictly a test for 1° amines only; secondary and tertiary amines give a negative result.",
    reactants: "Primary amine ONLY (RNH₂) — aliphatic or aromatic",
    reagents: "CHCl₃ + alcoholic KOH, heat",
    conditions: "Alcoholic KOH, heat. Smell is the indicator.",
    product: "Isocyanide (R-N≡C). Extremely foul odour = positive test.",
    mechanism: "CHCl₃ + KOH → :CCl₂ (dichlorocarbene) → reacts with -NH₂ → R-N=CCl₂ → double HCl elimination → R-N≡C",
    stereo: null,
    mistake: "Applying to 2° or 3° amines — NEGATIVE. Only 1° amines react. Also: isocyanide is R-N≡C (N bonded to R), NOT R-C≡N (nitrile). Structure is inverted — students draw it backwards.",
    hook: "Carbylamine = Foul = 1° amine ONLY. CHCl₃ + alc. KOH. 2° and 3° = negative. If it stinks = positive.",
    jee: "'Distinguish 1° from 2°/3° amine?' → Carbylamine test. Works for both aliphatic and aromatic 1° amines."
  },

  {
    id: "clemmensen", name: "Clemmensen Reduction", type: "Reduction", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["Zn amalgam", "HCl", "C=O to CH₂", "acid conditions"],
    summary: "Clemmensen reduction converts the carbonyl group (C=O) of aldehydes and ketones directly to a methylene group (CH₂) using zinc amalgam [Zn(Hg)] in concentrated HCl. The strongly acidic conditions mean the substrate must be acid-stable; for base-sensitive substrates use Wolff-Kishner instead. Both methods give the same alkane product from the same carbonyl starting material.",
    reactants: "Aldehyde or ketone (not carboxylic acids)",
    reagents: "Zn(Hg) amalgam + conc. HCl",
    conditions: "Strongly acidic (conc. HCl), heat. Substrate must be acid-stable.",
    product: "Alkane: R-CO-R' → R-CH₂-R'. C=O becomes CH₂.",
    mechanism: "Heterogeneous surface mechanism on Zn. Not a simple ionic pathway.",
    stereo: null,
    mistake: "Using for acid-sensitive substrates — they are destroyed. Use Wolff-Kishner (basic) instead. Also: does NOT reduce COOH or esters — only aldehyde/ketone C=O.",
    hook: "Clemmensen = Zn(Hg) + HCl = ACID. Use when substrate is BASE-sensitive. Wolff-Kishner = KOH = BASE. Use when ACID-sensitive. Same product, opposite conditions.",
    jee: "Always paired with Wolff-Kishner in JEE. 'Which to use if substrate has acid-sensitive group?' → Wolff-Kishner."
  },

  {
    id: "diazotisation", name: "Diazotisation", type: "Diazonium Chemistry", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["ArN₂⁺", "NaNO₂", "HCl", "0–5°C", "ice bath", "gateway reaction"],
    summary: "Primary aromatic amines react with NaNO₂ and HCl at 0–5°C to form diazonium salts (ArN₂⁺Cl⁻) — the essential gateway to Sandmeyer, Balz-Schiemann, and azo-coupling reactions. Temperature control is critical: above 5°C the diazonium decomposes to phenol + N₂. Aliphatic diazonium salts are too unstable to isolate and immediately lose N₂.",
    reactants: "Primary aromatic amine (ArNH₂): aniline, substituted anilines",
    reagents: "NaNO₂ + HCl (generates HNO₂ in situ)",
    conditions: "ICE COLD: 0–5°C. Above 5°C → diazonium decomposes to phenol + N₂.",
    product: "Diazonium salt (ArN₂⁺Cl⁻): C₆H₅NH₂ → C₆H₅N₂⁺Cl⁻",
    mechanism: "HNO₂ + ArNH₂ → N-nitrosoamine → tautomerism → ArN₂⁺",
    stereo: null,
    mistake: "Using aliphatic amines — alkyl diazonium instantly decomposes to alcohol + N₂. Only AROMATIC amines form stable diazonium. Also: above 5°C → decomposition to phenol.",
    hook: "Diazotisation = ICE COLD always. ArNH₂ + NaNO₂ + HCl at 0–5°C = ArN₂⁺. Gateway to all diazonium reactions.",
    jee: "Master this first — Sandmeyer, Balz-Schiemann and azo coupling all start here."
  },

  {
    id: "fc-acylation", name: "Friedel-Crafts Acylation", type: "Electrophilic Aromatic Substitution", chapter: "Aromatic Compounds",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["AlCl₃", "RCOCl", "acylium ion", "aryl ketone", "no rearrangement"],
    summary: "Benzene reacts with an acyl chloride (RCOCl) in the presence of anhydrous AlCl₃ to give an aryl ketone via EAS. Because the electrophile is a resonance-stabilised acylium ion (RCO⁺), no carbocation rearrangement occurs and the product ketone deactivates the ring — preventing polyacylation. More than one equivalent of AlCl₃ is required since the product carbonyl complexes with it.",
    reactants: "Benzene + acyl chloride (RCOCl) or acid anhydride",
    reagents: "Anhydrous AlCl₃ (>1 equiv — one equiv complexes with product C=O)",
    conditions: "Anhydrous. Excess AlCl₃ needed because product ketone complexes with AlCl₃.",
    product: "Aryl ketone: PhH + CH₃COCl + AlCl₃ → PhCOCH₃ (acetophenone) + HCl",
    mechanism: "RCOCl + AlCl₃ → RCO⁺ (acylium — resonance-stabilised → no rearrangement). EAS. Product C=O complexes AlCl₃ → ring deactivated → no polyacylation.",
    stereo: null,
    mistake: "Forgetting that >1 equiv AlCl₃ is needed. Acylation also FAILS on deactivated rings. Best way to put a long-chain alkyl on a ring without rearrangement: FC acylation → Clemmensen/WK.",
    hook: "FC Acylation = no rearrangement, no polyacylation. Same limitation as alkylation: fails on deactivated rings. Acylation + Clemmensen = rearrangement-free alkylation.",
    jee: "JEE contrasts acylation vs alkylation limitations. Two-step (acylation + Clemmensen) = classic synthesis question."
  },

  {
    id: "fc-alkylation", name: "Friedel-Crafts Alkylation", type: "Electrophilic Aromatic Substitution", chapter: "Aromatic Compounds",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["AlCl₃", "RX", "carbocation", "EAS", "rearrangement", "polyalkylation"],
    summary: "Benzene reacts with alkyl halides in the presence of anhydrous AlCl₃ to give alkylbenzenes via electrophilic aromatic substitution. Three critical limitations make this reaction unreliable: (1) carbocation rearrangement (n-PrCl gives isopropylbenzene, not n-propylbenzene), (2) polyalkylation since the product is more reactive than benzene, and (3) complete failure with deactivated rings such as nitrobenzene.",
    reactants: "Benzene + alkyl halide (RX)",
    reagents: "Anhydrous AlCl₃ (Lewis acid)",
    conditions: "Anhydrous AlCl₃, anhydrous conditions. H₂O destroys catalyst.",
    product: "Alkylbenzene: PhH + CH₃Cl + AlCl₃ → PhCH₃ + HCl",
    mechanism: "RX + AlCl₃ → R⁺ + AlCl₄⁻. R⁺ attacks benzene (EAS) → sigma complex → H⁺ loss → product.",
    stereo: null,
    mistake: "Three JEE limitations: (1) REARRANGEMENT — 1° carbocations rearrange (n-PrCl + Ph + AlCl₃ → isopropylbenzene, NOT n-propylbenzene). (2) POLYALKYLATION — product is more reactive than benzene. (3) FAILS on deactivated rings (nitrobenzene, etc.).",
    hook: "FC Alkylation Three Enemies: Rearrangement. Polyalkylation. Deactivated rings fail. n-Pr → isopropyl (rearranges!). Use Acylation + Clemmensen to avoid rearrangement.",
    jee: "All three limitations are exam staples. n-propyl chloride → cumene (isopropylbenzene) via rearrangement is a classic trap."
  },

  {
    id: "grignard", name: "Grignard Reaction", type: "Nucleophilic Addition", chapter: "Multiple Chapters",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["RMgX", "organometallic", "C-C bond", "anhydrous", "dry ether", "carbanion"],
    summary: "Grignard reagents (RMgX) behave as carbanions and add nucleophilically to carbonyl compounds: HCHO gives 1° alcohol, RCHO gives 2°, R₂CO gives 3°, CO₂ gives carboxylic acid, and esters consume 2 moles to give 3° alcohol. Strictly anhydrous conditions are essential — even a trace of water destroys the reagent by protonation (RMgX + H₂O → RH). This is the most versatile C–C bond-forming reaction tested in JEE.",
    reactants: "RMgX + HCHO → 1° OH  |  RCHO → 2° OH  |  R₂CO → 3° OH  |  CO₂ → RCOOH  |  Ester → 3° OH (2 moles RMgX)",
    reagents: "Mg in dry ether for prep. Then carbonyl. Then H₃O⁺ workup.",
    conditions: "Strictly anhydrous and aprotic. Dry ether or THF. One drop of water destroys Grignard: RMgX + H₂O → RH.",
    product: "1° OH (HCHO), 2° OH (RCHO), 3° OH (R₂CO), RCOOH (CO₂), 3° OH same R (ester)",
    mechanism: "C(δ−)-Mg(δ+): C is nucleophile. Attacks electrophilic carbonyl C → Mg-alkoxide → H₃O⁺ → alcohol.",
    stereo: "New stereocentre at former carbonyl C → RACEMIC mixture (attack from both faces).",
    mistake: "Using with ANY protic compound (H₂O, ROH, NH₃, RCOOH, RNH₂) — IMMEDIATELY DESTROYED → gives only RH. Also with esters: 2 moles of RMgX react (first → ketone intermediate, second → 3° alcohol with R added twice).",
    hook: "Grignard = R⁻ in disguise. Kills with moisture. HCHO=1°, RCHO=2°, R₂CO=3°, CO₂=RCOOH, ester=3° (2 moles). DRY EVERYTHING.",
    jee: "Most important reaction in JEE organics. Which product from which carbonyl? How many moles? Every paper has a Grignard question."
  },

  // ─── BATCH 2 ───────────────────────────────────────────────────────────────

  {
    id: "hofmann-bromamide", name: "Hofmann Bromamide Reaction", type: "Rearrangement", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["RCONH₂", "Br₂", "NaOH", "1° amine", "n-1 carbons", "isocyanate"],
    summary: "Primary amide + Br₂/NaOH → primary amine with ONE FEWER carbon. The carbonyl is lost as CO₂. Amide → amine with carbon loss.",
    reactants: "Primary amide (RCONH₂) ONLY. Does not work for 2° or 3° amides.",
    reagents: "Br₂ + NaOH (NaOBr is the active species)",
    conditions: "Aqueous NaOH + Br₂, 0°C then warm",
    product: "RNH₂ (n-1 carbons): CH₃CONH₂ → CH₃NH₂. CO₂ is lost.",
    mechanism: "NaOBr → N-bromoamide → base removes N-H → Br⁻ leaves → isocyanate (R-N=C=O) → H₂O → carbamic acid → CO₂ + RNH₂",
    stereo: "Configuration at R is RETAINED (rearrangement at carbonyl, not at R).",
    mistake: "Writing the same number of carbons in product as in starting amide — WRONG. Amide has n C, amine has n-1 C. CO₂ escapes! Also: confusing with Hofmann ELIMINATION (quaternary salt → least substituted alkene) — completely different reaction.",
    hook: "Hofmann Bromamide: RCONH₂ → RNH₂. ONE carbon LESS. Carbonyl runs away as CO₂. Br₂ + NaOH. Primary amide only. CH₃CONH₂ → CH₃NH₂ (not C₂H₅NH₂).",
    jee: "Very high frequency. 'CH₃CONH₂ + Br₂/NaOH → ?' → CH₃NH₂. Propanamide → ethylamine (C3 → C2). Tests carbon counting."
  },

  {
    id: "haloform", name: "Haloform / Iodoform Reaction", type: "Halogenation", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["CHI₃", "iodoform", "yellow precipitate", "methyl ketone", "NaOI", "qualitative test"],
    summary: "Methyl ketones (CH₃COR) and CH₃CHO react with I₂/NaOH → yellow CHI₃ (iodoform). Qualitative test for methyl ketone group.",
    reactants: "CH₃COR (methyl ketone), CH₃CHO, ethanol, isopropanol (all oxidised to methyl carbonyl in situ)",
    reagents: "I₂ + NaOH (NaOI formed in situ)",
    conditions: "Alkaline medium (NaOH), room temperature. Yellow ppt = positive.",
    product: "CHI₃ (yellow iodoform ppt) + RCOONa (one fewer carbon than starting material)",
    mechanism: "Step 1: all 3 alpha-H on methyl replaced by I (trihalogenation). Step 2: OH⁻ cleaves C-C → CHI₃ + RCOO⁻",
    stereo: null,
    mistake: "ALL ketones give iodoform — FALSE. Only METHYL ketones (CH₃CO-). Ethanol → YES, Isopropanol → YES (oxidised to acetone), n-Propanol → NO (gives propanal, no CH₃CO-), Diethyl ketone → NO.",
    hook: "Iodoform test: look for CH₃CO- group. Ethanol ✓  Isopropanol ✓  n-Propanol ✗  Acetone ✓  Diethyl ketone ✗. Yellow CHI₃ = positive.",
    jee: "Positive/negative iodoform test lists are extremely common. JEE gives a set of compounds and asks which give CHI₃."
  },

  {
    id: "kolbe", name: "Kolbe's Reaction (Kolbe-Schmitt)", type: "Carboxylation", chapter: "Phenols",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["phenol", "CO₂", "salicylic acid", "Na phenoxide", "pressure", "aspirin"],
    summary: "Sodium phenoxide + CO₂ under pressure at 125°C → salicylic acid (2-hydroxybenzoic acid) after acidification. Precursor of aspirin.",
    reactants: "Sodium phenoxide (C₆H₅ONa) — phenol + NaOH first",
    reagents: "CO₂ gas at 4–5 atm, then H⁺ workup",
    conditions: "125°C, 4–5 atm CO₂. Na-phenoxide → ortho. K-phenoxide at 250°C → para (p-hydroxybenzoic acid).",
    product: "Salicylic acid (2-hydroxybenzoic acid). Aspirin = salicylic acid + acetic anhydride.",
    mechanism: "CO₂ (weak electrophile) attacks ortho of electron-rich phenoxide ring → H⁺ workup → salicylic acid.",
    stereo: null,
    mistake: "Temperature and cation matter: Na + 125°C = ORTHO. K + 250°C = PARA. Using free phenol (need the Na-salt). Students mix up temperature and product.",
    hook: "Kolbe = CO₂ + Na-phenoxide + pressure = SALICYLIC ACID. Low T = ortho. High T = para. Na≠K. Kolbe made aspirin's parent!",
    jee: "'Phenol + CO₂ under pressure → ?' → salicylic acid. Direct factual question every alternate year."
  },

  {
    id: "reimer-tiemann", name: "Reimer-Tiemann Reaction", type: "Electrophilic Aromatic Substitution", chapter: "Phenols",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["phenol", "CHCl₃", "NaOH", "salicylaldehyde", "dichlorocarbene"],
    summary: "Phenol + CHCl₃ + NaOH → dichlorocarbene electrophile attacks phenoxide ortho → hydrolysis → salicylaldehyde (2-hydroxybenzaldehyde).",
    reactants: "Phenol (C₆H₅OH)",
    reagents: "CHCl₃ + conc. NaOH (aqueous)",
    conditions: "NaOH/H₂O, ~60–70°C",
    product: "Salicylaldehyde (2-hydroxybenzaldehyde) — major; para-hydroxybenzaldehyde — minor.",
    mechanism: "CHCl₃ + NaOH → :CCl₂ (dichlorocarbene) → attacks ortho of phenoxide → gem-dichloride intermediate + 2NaOH → CHO + 2NaCl (hydrolysis).",
    stereo: null,
    mistake: "Writing CHO⁺ as the electrophile — WRONG. The electrophile is :CCl₂ (dichlorocarbene). Also: works ONLY for phenols — not plain benzene (use Gattermann-Koch for benzene).",
    hook: "RT = CHCl₃ + NaOH on PHENOL = carbene = salicylaldehyde. G-K = CO + HCl + AlCl₃ on BENZENE. Carbene is the electrophile, not CHO⁺.",
    jee: "'Phenol + CHCl₃ + NaOH → ?' → salicylaldehyde. Asked almost every year."
  },

  // ─── BATCH 3 ───────────────────────────────────────────────────────────────

  {
    id: "rosenmund", name: "Rosenmund Reduction", type: "Reduction", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["RCOCl", "H₂", "Pd/BaSO₄", "poisoned catalyst", "RCHO"],
    summary: "Acid chloride (RCOCl) reduced selectively to aldehyde (RCHO) by H₂ over POISONED Pd/BaSO₄. Poison prevents over-reduction to alcohol.",
    reactants: "Acid chloride (RCOCl)",
    reagents: "H₂ + Pd/BaSO₄ (catalyst poisoned with quinoline-S)",
    conditions: "H₂ atmosphere, Pd/BaSO₄, gentle",
    product: "Aldehyde: RCOCl + H₂ → RCHO + HCl",
    mechanism: "Surface hydrogenation on poisoned Pd. Stops at aldehyde — un-poisoned Pd would reduce to alcohol.",
    stereo: null,
    mistake: "Using normal Pd/C — over-reduces to primary alcohol. Pd/BaSO₄ (POISONED) is essential. Also: LiAlH₄ or NaBH₄ cannot stop at aldehyde.",
    hook: "Rosenmund = Pd/BaSO₄ = POISONED Pd = STOPS at ALDEHYDE. Unpoisoned Pd → alcohol. Poison = halfway stop.",
    jee: "'RCOCl → RCHO, which reagent?' → H₂/Pd-BaSO₄. Distinguish from Stephen (SnCl₂/HCl on RCN)."
  },

  {
    id: "sandmeyer", name: "Sandmeyer Reaction", type: "Diazonium Chemistry", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["ArN₂⁺", "CuCl", "CuBr", "CuCN", "aryl halide", "radical"],
    summary: "Diazonium salt + CuCl/CuBr/CuCN → ArCl/ArBr/ArCN. Makes aryl halides not accessible by direct substitution.",
    reactants: "Benzenediazonium salt (ArN₂⁺Cl⁻)",
    reagents: "CuCl → ArCl; CuBr → ArBr; CuCN → ArCN. For ArF: Balz-Schiemann (HBF₄). For ArI: KI directly (no Cu needed). For ArOH: H₂O/heat. For ArH: H₃PO₂.",
    conditions: "Cu(I) salts, mild heat. Balz-Schiemann: HBF₄ then heat dry diazonium tetrafluoroborate.",
    product: "ArCl, ArBr, ArCN, ArF, ArI, ArOH, ArH depending on reagent.",
    mechanism: "Cu(I) radical mechanism: Cu(I) → Cu(II) + e⁻ → Ar• → Ar-X. NOT a simple SN2.",
    stereo: null,
    mistake: "Using Cu for ArI (use KI directly) or ArF (use Balz-Schiemann). Also: Sandmeyer is for AROMATIC diazonium — aliphatic diazonium is too unstable.",
    hook: "Sandmeyer: Cu(I) + diazonium = aryl halide. CuCl=ArCl, CuBr=ArBr, CuCN=ArCN. No Cu for I (use KI) and no Cu for F (use Balz-Schiemann).",
    jee: "'ArNH₂ → ArCl in two steps?' → Diazotise then Sandmeyer. Very common synthesis question."
  },

  {
    id: "stephen", name: "Stephen Reduction", type: "Reduction", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["RCN", "SnCl₂", "HCl", "RCHO", "nitrile to aldehyde"],
    summary: "Nitrile (RCN) + SnCl₂ + HCl → imine salt → hydrolysis → aldehyde (RCHO). Converts nitrile to aldehyde (same carbon count).",
    reactants: "Nitrile (RCN)",
    reagents: "SnCl₂ + HCl (anhydrous), then H₂O workup",
    conditions: "Anhydrous HCl + SnCl₂, then aqueous workup",
    product: "Aldehyde (RCHO): CH₃CN → CH₃CHO",
    mechanism: "SnCl₂ reduces C≡N to C=NH (imine) as Sn(II) complex → H₂O hydrolysis → RCHO + NH₃",
    stereo: null,
    mistake: "Confusing with Rosenmund (RCOCl → RCHO) — both give aldehyde but from different starting materials. Stephen: nitrile → aldehyde (same C count). Also: LiAlH₄ on nitrile gives PRIMARY AMINE (not aldehyde).",
    hook: "Stephen = SnCl₂ + HCl on NITRILE = ALDEHYDE. Same C count. LiAlH₄ on nitrile = amine (not aldehyde). Rosenmund = acid chloride → aldehyde.",
    jee: "'RCN → RCHO, which reagent?' → SnCl₂/HCl (Stephen). 'RCN → RCH₂NH₂?' → LiAlH₄."
  },

  {
    id: "wolff-kishner", name: "Wolff-Kishner Reduction", type: "Reduction", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["NH₂NH₂", "KOH", "ethylene glycol", "C=O to CH₂", "base conditions"],
    summary: "Aldehyde/ketone + NH₂NH₂ + KOH/ethylene glycol → hydrazone → CH₂. Base conditions — use when substrate is acid-sensitive.",
    reactants: "Aldehyde or ketone",
    reagents: "NH₂NH₂ (hydrazine) + KOH in ethylene glycol (high boiling point solvent)",
    conditions: "High temperature (~200°C), strongly basic (KOH). Substrate must be base-stable.",
    product: "Alkane: R-CO-R' → R-CH₂-R'. Same as Clemmensen but under basic conditions.",
    mechanism: "C=O + NH₂NH₂ → hydrazone (C=N-NH₂) → KOH/heat → N₂ loss → carbanion → protonation → CH₂",
    stereo: null,
    mistake: "Using for base-sensitive substrates. Use Clemmensen (acid) instead. Also: Huang Minlon modification (aqueous KOH + diethylene glycol) is a variant — same product.",
    hook: "Wolff-Kishner = NH₂NH₂ + KOH = BASE. Use when ACID-sensitive. Clemmensen = Zn(Hg) + HCl = ACID. Use when BASE-sensitive. Same product, opposite pH.",
    jee: "Always tested alongside Clemmensen. 'Which reagent for C=O → CH₂ if substrate has acid-labile group?' → Wolff-Kishner."
  },

  {
    id: "fischer", name: "Fischer Esterification", type: "Acyl Substitution", chapter: "Carboxylic Acids",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["RCOOH", "alcohol", "H⁺", "reversible", "¹⁸O labelling", "ester"],
    summary: "Carboxylic acid + alcohol + H⁺ catalyst ⇌ ester + water. Reversible equilibrium reaction — must be driven forward.",
    reactants: "Carboxylic acid (RCOOH) + alcohol (R'OH)",
    reagents: "H⁺ catalyst (conc. H₂SO₄ or dry HCl), heat",
    conditions: "Reversible. Drive forward: excess alcohol, remove water (distillation/molecular sieves), or conc. H₂SO₄.",
    product: "Ester (RCOOR') + H₂O: CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O",
    mechanism: "H⁺ protonates C=O → R'OH attacks → tetrahedral intermediate → H₂O loss → ester. Acyl-oxygen cleavage (confirmed by ¹⁸O labelling).",
    stereo: null,
    mistake: "Forgetting it is REVERSIBLE. Also: ¹⁸O labelling shows the O in ester comes from the ALCOHOL (not the acid). The acid loses its -OH as water. Tertiary alcohols react poorly (elimination competes).",
    hook: "Reversible! ¹⁸O from ALCOHOL ends up in ester. Acid donates -OH as water. Drive equilibrium right: excess alcohol or remove water.",
    jee: "JEE tests ¹⁸O isotope labelling to confirm acyl-oxygen cleavage. RCOOH + ROH (reversible, H⁺) vs RCOCl + ROH (irreversible, fast, no catalyst) distinction."
  },

  {
    id: "gabriel", name: "Gabriel Phthalimide Synthesis", type: "Amine Synthesis", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["phthalimide", "KOH", "RX", "SN2", "1° amine only", "hydrazinolysis"],
    summary: "Phthalimide + KOH → K-phthalimide + RX (SN2) → N-alkyl phthalimide + hydrolysis → PRIMARY AMINE ONLY. Cannot make 2° or 3° amines.",
    reactants: "Phthalimide + primary alkyl halide (RX)",
    reagents: "Step 1: KOH. Step 2: RX. Step 3: acid hydrolysis (H₃O⁺) or hydrazinolysis (N₂H₄).",
    conditions: "Anhydrous for SN2 step; then acidic hydrolysis or hydrazinolysis.",
    product: "Primary amine (RNH₂) only. Phthalate byproduct.",
    mechanism: "Phthalimide N-H (pKa ~8.3) deprotonated by KOH → N-nucleophile → SN2 on RX → N-alkyl phthalimide → hydrolysis → RNH₂.",
    stereo: "SN2 step: inversion of configuration at RX carbon if chiral.",
    mistake: "Gabriel cannot make secondary or tertiary amines — phthalimide has ONE N-H so only one alkyl group attaches. Also: primary aryl amines cannot be made (ArX doesn't undergo SN2 easily).",
    hook: "Gabriel = phthalimide + KOH + RX + hydrolysis = 1° AMINE ONLY. One N-H = one alkyl group. Never secondary, never tertiary.",
    jee: "'Which method gives only primary amine?' → Gabriel. 'Can Gabriel make 2° amine?' → No."
  },

  // ─── BATCH 4 ───────────────────────────────────────────────────────────────

  {
    id: "williamson", name: "Williamson Ether Synthesis", type: "SN2 Substitution", chapter: "Alcohols & Ethers",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["alkoxide", "SN2", "mixed ether", "primary halide", "RONa + RX"],
    summary: "Alkoxide (RONa) + primary alkyl halide → ether by SN2. Best route to mixed ethers. Tertiary alkyl halides fail (elimination dominates).",
    reactants: "Sodium alkoxide (RONa) + primary (ideally) alkyl halide",
    reagents: "Na metal + alcohol → alkoxide, then RX. Or NaOH + phenol → phenoxide + RX.",
    conditions: "Anhydrous. SN2 requires primary RX.",
    product: "Ether (R-O-R'): CH₃ONa + C₂H₅Br → CH₃OC₂H₅ + NaBr",
    mechanism: "SN2: alkoxide O⁻ attacks back of C-X → concerted → ether + X⁻",
    stereo: "Inversion of configuration at RX carbon (SN2).",
    mistake: "Using tertiary RX — SN2 fails, elimination dominates. SWAP ROLES: tertiary group on the ALKOXIDE side. e.g. for (CH₃)₃C-O-CH₃: use (CH₃)₃CONa + CH₃I, NOT (CH₃)₃CI + CH₃ONa.",
    hook: "Williamson = alkoxide + PRIMARY halide → ether. Tertiary halide = elimination. Tertiary group goes on ALKOXIDE side.",
    jee: "'Which combination gives ether without elimination?' Tests SN2 vs E2. Anisole via PhONa + CH₃I is classic."
  },

  {
    id: "azo-coupling", name: "Azo Coupling Reaction", type: "Diazonium Chemistry", chapter: "Amines",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["ArN₂⁺", "phenol", "aniline", "azo dye", "N=N bond", "para coupling"],
    summary: "Diazonium salt (ArN₂⁺) + phenol or aryl amine → azo compound (Ar-N=N-Ar'). Coloured azo dyes. Para coupling preferred.",
    reactants: "Diazonium salt (electrophile) + phenol or aromatic amine (activated ring)",
    reagents: "Freshly prepared cold diazonium salt (ArN₂⁺Cl⁻)",
    conditions: "Phenol: mildly alkaline (pH 8–10, forms PhO⁻). Amine: weakly acidic/neutral. Temperature: 0–5°C always.",
    product: "Azo compound (Ar-N=N-Ar') — coloured dye. Para coupling major product.",
    mechanism: "ArN₂⁺ (weak electrophile) attacks para of activated ring (EAS) → sigma complex → H⁺ loss → azo dye.",
    stereo: "E/Z isomerism about N=N bond. E (trans) = thermodynamically more stable.",
    mistake: "Phenol coupling needs MILD BASE (PhO⁻ = more activated). Amine coupling needs WEAK ACID (strong acid protonates -NH₂ → -NH₃⁺ = deactivated ring). Students swap the pH conditions.",
    hook: "Coupling = ArN₂⁺ + activated ring = AZO DYE. Phenol: mild base. Amine: weak acid. Para preferred. Cold always.",
    jee: "diazonium + phenol → p-hydroxyazobenzene (orange/red). E/Z isomerism tested. Methyl orange, Orange II are azo dyes."
  },

  {
    id: "balz-schiemann", name: "Balz-Schiemann Reaction", type: "Diazonium Chemistry", chapter: "Amines",
    priority: "medium", exam: "both", difficulty: "easy",
    tags: ["ArF", "NaBF₄", "diazonium tetrafluoroborate", "pyrolysis", "fluorobenzene"],
    summary: "Only reliable route to aryl fluorides. ArN₂⁺ + HBF₄ → ArN₂⁺BF₄⁻ salt → dry pyrolysis → ArF + N₂ + BF₃.",
    reactants: "Benzenediazonium chloride (ArN₂⁺Cl⁻)",
    reagents: "HBF₄ or NaBF₄, then dry heat",
    conditions: "Step 1: form ArN₂⁺BF₄⁻ (precipitates). Step 2: dry pyrolysis of dry salt → ArF.",
    product: "Aryl fluoride (ArF) e.g. fluorobenzene from aniline.",
    mechanism: "Thermal decomposition of diazonium fluoroborate → aryl cation + N₂ + BF₄⁻ → ArF + BF₃",
    stereo: null,
    mistake: "Trying Sandmeyer for ArF — poor results. Must use Balz-Schiemann. It is a TWO-step process: form BF₄⁻ salt FIRST (precipitates out), THEN dry pyrolysis.",
    hook: "Balz-Schiemann = Fluorine's special reaction. BF₄ salt → dry heat → ArF. Sandmeyer cannot make ArF.",
    jee: "'How is fluorobenzene prepared from aniline?' → Diazotisation → Balz-Schiemann. Standard 2-mark question."
  },

  {
    id: "beckmann", name: "Beckmann Rearrangement", type: "Rearrangement", chapter: "Aldehydes & Ketones",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["oxime", "H₂SO₄", "lactam", "amide", "ring expansion", "anti migration"],
    summary: "Ketone oxime + H₂SO₄ (or PCl₅) → amide (or lactam for cyclic ketones) via 1,2-migration of the anti group. Ring expansion for cyclic ketones.",
    reactants: "Ketone oxime (R-C(=NOH)-R')",
    reagents: "Conc. H₂SO₄ or PCl₅",
    conditions: "Strong acid conditions. For cyclic ketones: ring expansion (cyclohexanone oxime → caprolactam, the nylon-6 precursor).",
    product: "Amide (R-CO-NHR') or lactam. The group ANTI to -OH migrates.",
    mechanism: "H⁺ protonates oxime -OH → H₂O leaves → nitrilium ion → anti-group migrates to N (1,2-shift) → H₂O attacks → amide.",
    stereo: "The group ANTI (trans) to -OH in the oxime migrates. Stereospecific: different oxime isomers give different amide products.",
    mistake: "Thinking either group can migrate — ONLY the anti group (trans to OH) migrates. Also: cyclic ketone → ring EXPANSION (cyclohexanone → 7-membered lactam, caprolactam). Students expect ring contraction.",
    hook: "Beckmann: anti-group migrates to N. Cyclic ketones → ring EXPANSION. Cyclohexanone oxime → caprolactam (nylon-6 monomer). Anti = moves.",
    jee: "JEE Advanced. 'Cyclohexanone oxime + H₂SO₄ → ?' → caprolactam (ring expansion). Anti-migration rule tested."
  },

  {
    id: "benzoin", name: "Benzoin Condensation", type: "Condensation", chapter: "Aldehydes & Ketones",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["PhCHO", "KCN", "benzoin", "acyloin", "C-C bond", "umpolung"],
    summary: "Two molecules of benzaldehyde condense with KCN (cyanide catalyst) to give benzoin (PhCH(OH)COPh). Cyanide acts as umpolung catalyst — reverses carbonyl reactivity.",
    reactants: "Benzaldehyde (PhCHO) — aromatic aldehydes only (not aliphatic)",
    reagents: "KCN (potassium cyanide) or NaCN; aqueous ethanol; heat",
    conditions: "KCN catalyst in aqueous ethanol, ~60°C.",
    product: "Benzoin (PhCH(OH)COPh) — an alpha-hydroxy ketone",
    mechanism: "CN⁻ adds to PhCHO → cyanohydrin → anion (umpolung) → attacks second PhCHO → rearrangement → CN⁻ expelled → benzoin",
    stereo: "Racemic benzoin formed (no stereocontrol with simple KCN).",
    mistake: "Confusing with aldol — benzaldehyde has NO alpha-H so it cannot do aldol. Benzoin uses CN⁻ catalyst. Aliphatic aldehydes do NOT give benzoin condensation with KCN.",
    hook: "Benzoin condensation = PhCHO + PhCHO + KCN → benzoin. CN⁻ flips carbonyl reactivity (umpolung). Only aromatic aldehydes. No alpha-H needed.",
    jee: "JEE Advanced synthesis. 'Benzaldehyde + KCN → ?' → benzoin. Umpolung concept."
  },

  {
    id: "birch", name: "Birch Reduction", type: "Reduction", chapter: "Aromatic Compounds",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["Na/NH₃", "liquid ammonia", "1,4-diene", "EDG", "EWG", "regioselectivity"],
    summary: "Partial reduction of aromatic ring to 1,4-cyclohexadiene using Na or Li in liquid NH₃ with alcohol proton source. Not full reduction.",
    reactants: "Benzene or substituted benzene",
    reagents: "Na or Li metal + liquid NH₃ (−33°C) + ROH (proton source)",
    conditions: "Liquid ammonia (−33°C), Na metal, alcohol as proton source essential.",
    product: "1,4-cyclohexadiene. Position of double bonds depends on substituents.",
    mechanism: "Na → solvated e⁻ in NH₃ → radical anion → protonation → second e⁻ → anion → protonation → 1,4-diene.",
    stereo: "EDG: double bonds ON substituted carbons (EDG stays on C=C). EWG: double bonds AWAY from EWG (EWG on sp³ carbon).",
    mistake: "Getting regioselectivity wrong: EDG → double bond ON those carbons. EWG → double bond AWAY. Also: result is 1,4-DIENE, not cyclohexane. Alcohol as proton source is essential.",
    hook: "Birch = Na/NH₃/alcohol = partial ring reduction = 1,4-diene. EDG stays on C=C. EWG ends up on sp³ C. Anisole (EDG) → double bonds on OCH₃-bearing carbons.",
    jee: "JEE Advanced only. 'Birch reduction of anisole → which diene?' Tests regioselectivity rule."
  },

  {
    id: "claisen", name: "Claisen Condensation", type: "Condensation", chapter: "Carbonyl Compounds",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["ester", "NaOEt", "beta-ketoester", "Claisen", "ethyl acetoacetate", "C-C bond"],
    summary: "Two ester molecules condense under base (NaOEt) to give a beta-ketoester. Classic: 2 ethyl acetate → ethyl acetoacetate.",
    reactants: "Ester (requires alpha-H for the donor). Two molecules of same ester (Claisen) or different esters (crossed Claisen).",
    reagents: "NaOEt (sodium ethoxide, strong base) in dry ethanol",
    conditions: "Anhydrous ethanol, NaOEt, reflux.",
    product: "Beta-ketoester: 2 CH₃COOEt + NaOEt → CH₃COCH₂COOEt (ethyl acetoacetate) + EtOH",
    mechanism: "NaOEt deprotonates alpha-C of ester → enolate → attacks carbonyl C of second ester → tetrahedral intermediate → EtO⁻ expelled → beta-ketoester",
    stereo: null,
    mistake: "Confusing with aldol (which involves aldehyde/ketone + NaOH). Claisen = ESTER + NaOEt. Also: one ester must have no alpha-H to act as acceptor in crossed Claisen, otherwise mixture results.",
    hook: "Claisen = ester + NaOEt = beta-ketoester. Two esters → one loses EtO⁻. Aldol uses NaOH, Claisen uses NaOEt. Ethyl acetate → ethyl acetoacetate = classic example.",
    jee: "JEE Advanced synthesis. Ethyl acetoacetate synthesis route, active methylene compounds, acetoacetic ester synthesis."
  },

  // ─── BATCH 5 (final) ───────────────────────────────────────────────────────

  {
    id: "decarboxylation", name: "Decarboxylation (Soda Lime)", type: "Decarboxylation", chapter: "Carboxylic Acids",
    priority: "medium", exam: "both", difficulty: "easy",
    tags: ["RCOONa", "soda lime", "NaOH+CaO", "n-1 carbons", "alkane"],
    summary: "Sodium salt of carboxylic acid + soda lime (NaOH+CaO) + strong heat → alkane with one fewer carbon + CO₂.",
    reactants: "Sodium carboxylate (RCOONa)",
    reagents: "Soda lime = NaOH + CaO (1:3 ratio), strong heat (300°C+)",
    conditions: "Strong heat. CaO prevents NaOH melting and activates it.",
    product: "Alkane (n-1 C): CH₃COONa + soda lime → CH₄ + Na₂CO₃",
    mechanism: "CaO activates carboxylate → decarboxylation → carbanion → protonation → alkane",
    stereo: null,
    mistake: "NaOH alone is insufficient — need soda lime (NaOH + CaO). Confusing with Kolbe electrolysis: Kolbe = 2RCOO⁻ → R-R (coupling, gains C). Soda lime = RCOOH → RH (loses 1 C). Completely opposite.",
    hook: "Soda lime = lose 1 carbon (RH). Kolbe electrolysis = couple carbons (R-R). Thermal = lose. Kolbe = couple.",
    jee: "'Convert RCOONa to RH?' → Soda lime + heat. Common in multistep synthesis."
  },

  {
    id: "etard", name: "Etard Reaction", type: "Oxidation", chapter: "Aldehydes & Ketones",
    priority: "medium", exam: "both", difficulty: "easy",
    tags: ["toluene", "CrO₂Cl₂", "chromyl chloride", "benzaldehyde", "CCl₄", "selective"],
    summary: "Toluene + CrO₂Cl₂ in CCl₄ → benzaldehyde. Chromyl chloride oxidises side-chain methyl selectively to CHO (not COOH).",
    reactants: "Toluene (PhCH₃) or alkylbenzene with methyl group",
    reagents: "CrO₂Cl₂ (chromyl chloride) in CCl₄",
    conditions: "CCl₄ solvent, room temperature. Then H₂O workup.",
    product: "Benzaldehyde (PhCHO): PhCH₃ + CrO₂Cl₂ → [complex] → H₂O → PhCHO",
    mechanism: "CrO₂Cl₂ forms chromate ester with methyl → hydrolysis gives aldehyde selectively.",
    stereo: null,
    mistake: "Confusing with KMnO₄ which burns toluene methyl all the way to COOH. CrO₂Cl₂ in CCl₄ = selective STOP at CHO. KMnO₄ = COOH.",
    hook: "Etard = CrO₂Cl₂ in CCl₄ = STOPS at ALDEHYDE. KMnO₄ = burns to COOH. E for Early stop.",
    jee: "'Toluene → benzaldehyde: which reagent?' → Etard. 'Toluene → benzoic acid?' → KMnO₄."
  },

  {
    id: "finkelstein", name: "Finkelstein Reaction", type: "Halogen Exchange", chapter: "Haloalkanes",
    priority: "medium", exam: "mains", difficulty: "easy",
    tags: ["NaI", "acetone", "SN2", "RI", "Le Chatelier", "precipitation"],
    summary: "Alkyl Cl or Br + NaI in dry acetone → alkyl iodide. Driven by insolubility of NaCl/NaBr in acetone (Le Chatelier).",
    reactants: "Alkyl chloride (RCl) or alkyl bromide (RBr)",
    reagents: "NaI, dry acetone",
    conditions: "Dry acetone. NaCl/NaBr precipitate out → equilibrium shifts forward.",
    product: "Alkyl iodide (RI): RCl + NaI → RI + NaCl↓",
    mechanism: "SN2: I⁻ attacks C-Cl (backside). NaCl insoluble in acetone → precipitates → drives equilibrium.",
    stereo: "Inversion of configuration (SN2). (R) → (S).",
    mistake: "Reaction done in water — NaCl soluble in water → equilibrium doesn't shift → doesn't work. Dry acetone is essential. Also fails for 3° RX (SN2 impossible).",
    hook: "Finkelstein = NaI + dry ACETONE. NaCl precipitates → Le Chatelier pulls forward. Water kills it.",
    jee: "Paired with Swartz reaction. Le Chatelier's principle drive = classic JEE concept."
  },

  {
    id: "fries", name: "Fries Rearrangement", type: "Rearrangement", chapter: "Phenols",
    priority: "medium", exam: "advanced", difficulty: "medium",
    tags: ["phenyl ester", "AlCl₃", "phenol ketone", "ortho/para", "photo-Fries"],
    summary: "Phenyl ester + AlCl₃ (Lewis acid) → hydroxy aryl ketone. Ester rearranges to ortho or para hydroxyphenyl ketone depending on temperature.",
    reactants: "Phenyl ester (ArOCOR)",
    reagents: "AlCl₃ (Lewis acid), solvent or neat",
    conditions: "Low temp → para product. High temp → ortho product.",
    product: "Hydroxy aryl ketone: PhOCOR + AlCl₃ → o-HOC₆H₄COR (major at high T) + p-HOC₆H₄COR (major at low T)",
    mechanism: "AlCl₃ complexes with ester C=O → acylium migrates onto phenol ring (EAS) → ortho or para ketone",
    stereo: null,
    mistake: "Temperature selectivity is inverted vs intuition: HIGH temperature = ORTHO (thermodynamic control). LOW temperature = PARA (kinetic control). Students mix these up.",
    hook: "Fries = phenyl ester + AlCl₃ = hydroxyphenyl ketone. Low T = para (kinetic). High T = ortho (thermodynamic). Photo-Fries also possible.",
    jee: "JEE Advanced. Temperature-controlled ortho/para selectivity questions."
  },

  {
    id: "gattermann-koch", name: "Gattermann-Koch Reaction", type: "Electrophilic Aromatic Substitution", chapter: "Aldehydes & Ketones",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["benzaldehyde", "CO", "HCl", "AlCl₃", "CuCl", "formylation", "benzene"],
    summary: "Benzene + CO + HCl + AlCl₃/CuCl → benzaldehyde. Formylation of activated benzene rings.",
    reactants: "Benzene or activated substituted benzene",
    reagents: "CO + HCl gas, anhydrous AlCl₃, CuCl catalyst, high pressure",
    conditions: "Anhydrous AlCl₃, CuCl, CO + HCl, high pressure. Fails on deactivated rings.",
    product: "Benzaldehyde (PhCHO) from benzene.",
    mechanism: "CO + HCl + AlCl₃/CuCl → formyl cation (HCO⁺) → EAS on benzene → benzaldehyde.",
    stereo: null,
    mistake: "Thinking it works on phenol (use Reimer-Tiemann for phenol). G-K is for BENZENE rings. Also fails on deactivated rings.",
    hook: "G-K = CO + HCl + AlCl₃ on BENZENE = benzaldehyde. Reimer-Tiemann = CHCl₃ + NaOH on PHENOL. Never swap.",
    jee: "'Benzene → benzaldehyde directly: which reaction?' → Gattermann-Koch."
  },

  {
    id: "hvz", name: "Hell-Volhard-Zelinsky (HVZ)", type: "Halogenation", chapter: "Carboxylic Acids",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["alpha halogenation", "Br₂", "phosphorus", "RCOOH", "alpha-bromo acid", "acyl bromide"],
    summary: "Alpha-halogenation of carboxylic acids using Br₂ + red phosphorus. Phosphorus converts acid to acyl bromide first, which enolises far more easily.",
    reactants: "Carboxylic acid with alpha-H (RCH₂COOH)",
    reagents: "Br₂ + red phosphorus (or PBr₃)",
    conditions: "P + Br₂ → PBr₃ in situ → RCOOH → RCOBr → enolisation → Br₂ at alpha-C → H₂O workup.",
    product: "Alpha-bromo carboxylic acid: CH₃COOH → BrCH₂COOH (bromoacetic acid)",
    mechanism: "P + Br₂ → PBr₃ → RCOOH → RCOBr → enol → Br₂ at alpha → alpha-bromo acyl bromide → H₂O → alpha-bromo acid.",
    stereo: "New stereocentre at alpha-C → racemic mixture (enol face attack from both sides).",
    mistake: "Applying to ketones or aldehydes — HVZ is SPECIFICALLY for carboxylic acids. Without phosphorus, RCOOH barely reacts with Br₂. Phosphorus is essential.",
    hook: "HVZ = alpha-Bromo CARBOXYLIC ACID. P + Br₂ = PBr₃ activates acid → acyl bromide enolises → Br₂ attacks alpha. No P = no reaction.",
    jee: "Alpha-bromo acid + NH₃ (SN2) → alpha-amino acid. Links HVZ to amino acid synthesis."
  },

  {
    id: "perkin", name: "Perkin Reaction", type: "Condensation", chapter: "Carboxylic Acids",
    priority: "medium", exam: "advanced", difficulty: "medium",
    tags: ["ArCHO", "acetic anhydride", "NaOAc", "cinnamic acid", "E-alkene", "alpha,beta-unsaturated acid"],
    summary: "Aromatic aldehyde + acetic anhydride + NaOAc → alpha,beta-unsaturated carboxylic acid (trans). Classic: PhCHO → trans-cinnamic acid.",
    reactants: "Aromatic aldehyde (ArCHO) — benzaldehyde is textbook",
    reagents: "Acetic anhydride (Ac₂O), sodium acetate (NaOAc, mild base)",
    conditions: "Heat 150–200°C. NaOAc acts as mild base.",
    product: "Trans-cinnamic acid: PhCHO + Ac₂O → Ph-CH=CH-COOH + CH₃COOH",
    mechanism: "NaOAc deprotonates Ac₂O at alpha → enolate attacks ArCHO → beta-hydroxy → dehydration → alpha,beta-unsaturated acid.",
    stereo: "Trans (E) isomer is major product (thermodynamic control).",
    mistake: "Confusing with aldol — aldol uses NaOH, Perkin uses NaOAc + ACID ANHYDRIDE as carbon source. Aliphatic aldehydes work poorly.",
    hook: "Perkin = PhCHO + Ac₂O + NaOAc = TRANS-CINNAMIC ACID. Perkin = cinnamic acid (always). JEE Advanced synthesis final step.",
    jee: "'Which reaction gives trans-cinnamic acid from benzaldehyde?' → Perkin. Often the last step in multistep synthesis."
  },

  {
    id: "pinacol", name: "Pinacol-Pinacolone Rearrangement", type: "Rearrangement", chapter: "Alcohols",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["1,2-diol", "vicinal diol", "H⁺", "1,2-shift", "carbocation", "pinacolone"],
    summary: "Vicinal diol (1,2-diol) treated with H⁺ → 1,2-migration of alkyl/aryl group to adjacent carbocation → ketone (pinacolone). Classic: pinacol → pinacolone.",
    reactants: "Vicinal diol (1,2-diol): pinacol = (CH₃)₂C(OH)-C(OH)(CH₃)₂",
    reagents: "H⁺ (dil. H₂SO₄ or HCl)",
    conditions: "Aqueous acid, heat",
    product: "Ketone: pinacol + H⁺ → pinacolone ((CH₃)₃C-CO-CH₃, 3,3-dimethylbutan-2-one)",
    mechanism: "H⁺ protonates one OH → H₂O leaves → tertiary carbocation → 1,2-methyl shift → oxocarbenium ion stabilised by O lone pair → deprotonation → ketone.",
    stereo: "The migrating group is anti-periplanar to the leaving group in the concerted version.",
    mistake: "Thinking the less stable carbocation forms first — no, one OH is protonated and leaves to give the MORE stable initial carbocation. Then migration gives an even more stable oxocarbenium. Students mix up which carbon loses OH first.",
    hook: "Pinacol → Pinacolone: 1,2-diol + H⁺ → 1,2-shift → ketone. More stable intermediate drives migration. Diol → ketone (not alcohol).",
    jee: "JEE Advanced. 'Pinacol + H⁺ → ?' → pinacolone. 1,2-shift mechanism with driving force from oxocarbenium stabilisation."
  },

  {
    id: "wurtz", name: "Wurtz Reaction", type: "C-C Coupling", chapter: "Haloalkanes",
    priority: "medium", exam: "both", difficulty: "easy",
    tags: ["2RX + 2Na", "dry ether", "alkane", "C-C bond", "sodium"],
    summary: "Two alkyl halides + Na in dry ether → higher alkane via C-C coupling. Always doubles (or crosses) the carbon count.",
    reactants: "Alkyl halide (RX) — primary best. Tertiary fails (elimination).",
    reagents: "Na metal (2 eq), dry ether",
    conditions: "Dry ether, strictly anhydrous, reflux",
    product: "Alkane: 2RX + 2Na → R-R + 2NaX",
    mechanism: "RX + 2Na → RNa (organosodium) + NaX; RNa + RX → R-R + NaX",
    stereo: null,
    mistake: "Using a single RX to make an odd-carbon alkane — impossible. Single halide always gives even-carbon product. Mixed Wurtz (two different RX) gives three products (symmetrical + unsymmetrical alkane mixture).",
    hook: "Wurtz = two RX + Na = doubled alkane. One RX = even-carbon product. Mixed Wurtz = messy mixture.",
    jee: "'Which alkane CANNOT be made by Wurtz from one halide?' → any odd-carbon alkane."
  },

  {
    id: "wurtz-fittig", name: "Wurtz-Fittig Reaction", type: "C-C Coupling", chapter: "Haloalkanes & Haloarenes",
    priority: "medium", exam: "mains", difficulty: "easy",
    tags: ["ArX", "RX", "Na", "alkylarene", "toluene from PhBr+CH₃Br"],
    summary: "Aryl halide + alkyl halide + Na → alkylarene. Distinct from Fittig (ArX+ArX+Na → biaryl) and Wurtz (RX+RX+Na → alkane).",
    reactants: "Aryl halide (ArX) + Alkyl halide (RX)",
    reagents: "Na metal, dry ether",
    conditions: "Dry ether, anhydrous",
    product: "Alkylarene: PhBr + CH₃Br + 2Na → PhCH₃ + 2NaBr",
    mechanism: "Organosodium intermediate; aryl and alkyl groups couple",
    stereo: null,
    mistake: "Three-way confusion: Wurtz = alkyl+alkyl → alkane. Fittig = aryl+aryl → biaryl. Wurtz-Fittig = aryl+alkyl → alkylarene.",
    hook: "Fittig = two aryls = biaryl. Wurtz-Fittig = aryl + alkyl = alkylarene. Wurtz joins Fittig = mixed coupling.",
    jee: "Standard 3-way distinction question."
  },

  {
    id: "dow", name: "Dow Process (Chlorobenzene Hydrolysis)", type: "Nucleophilic Aromatic Substitution", chapter: "Haloarenes",
    priority: "low", exam: "advanced", difficulty: "medium",
    tags: ["chlorobenzene", "NaOH", "350°C", "300 atm", "sodium phenoxide", "phenol", "benzyne"],
    summary: "Chlorobenzene + NaOH (350°C, 300 atm, Cu catalyst) → sodium phenoxide → H⁺ → phenol. Industrial route to phenol. Proceeds via benzyne (elimination-addition).",
    reactants: "Chlorobenzene (C₆H₅Cl)",
    reagents: "NaOH (aq, very conc.), Cu catalyst",
    conditions: "350°C, 300 atm — extremely harsh.",
    product: "Phenol (C₆H₅OH) via sodium phenoxide intermediate",
    mechanism: "Benzyne (aryne) mechanism: E2-like elimination of HCl → benzyne → OH⁻ addition → sodium phenoxide → H⁺ → phenol.",
    stereo: null,
    mistake: "Treating it as simple SN2 on benzene — benzene rings do NOT do SN2. The mechanism goes through benzyne (aryne). Harsh conditions (350°C, 300 atm) are essential.",
    hook: "Dow Process = chlorobenzene + NaOH at extreme T & P → phenol via benzyne. Not SN2 — benzyne mechanism. Industrial phenol production.",
    jee: "JEE Advanced. Benzyne mechanism. 'Why harsh conditions for ArCl vs RCl?' — resonance stabilisation makes ArCl less reactive."
  },

  {
    id: "kolbe-electrolysis", name: "Kolbe Electrolysis", type: "C-C Coupling", chapter: "Carboxylic Acids",
    priority: "low", exam: "advanced", difficulty: "medium",
    tags: ["electrolysis", "RCOO⁻", "anode", "R-R", "decarboxylation", "coupling"],
    summary: "Electrolysis of carboxylate salt solution: 2RCOO⁻ → R-R + 2CO₂ at anode. Electrochemical C-C coupling via radical mechanism.",
    reactants: "Carboxylate salt (RCOONa) in aqueous solution",
    reagents: "Electrolysis — platinum anode, DC current",
    conditions: "Aqueous RCOONa solution, electrolysis, Pt anode",
    product: "Symmetrical alkane: 2RCOO⁻ → R-R + 2CO₂ + 2e⁻ (at anode). e.g. 2CH₃COO⁻ → C₂H₆",
    mechanism: "RCOO⁻ oxidised at anode → RCOO• → loses CO₂ → R• → R• + R• → R-R (radical coupling)",
    stereo: null,
    mistake: "Confusing with soda lime decarboxylation: soda lime gives RH (lose 1C). Kolbe electrolysis gives R-R (doubled carbons). Thermal = lose. Kolbe = couple.",
    hook: "Kolbe electrolysis = 2RCOO⁻ at anode → R-R + 2CO₂. Soda lime = RH (n-1 C). Opposite outcomes!",
    jee: "JEE: contrast with soda lime decarboxylation. Same starting material → opposite products depending on method."
  },


  {
    id: "kharasch", name: "Kharasch Effect (Peroxide Effect)", type: "Electrophilic Addition", chapter: "Hydrocarbons",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["anti-Markovnikov", "peroxide", "HBr", "free radical"],
    summary: "Anti-Markovnikov addition of HBr to alkenes only in the presence of peroxides. Proceeds via a free radical mechanism.",
    reactants: "Alkenes",
    reagents: "HBr and peroxide (e.g. benzoyl peroxide)",
    conditions: "Presence of peroxides",
    product: "Anti-Markovnikov alkyl bromide",
    mechanism: "Free radical addition. Peroxide initiation forms Br radical, which adds to the least substituted carbon.",
    stereo: null,
    mistake: "Applying it to HCl or HI. Only HBr works with peroxide effect.",
    hook: "Peroxide = Anti-Markovnikov for HBr.",
    jee: "Often asked in 'A -> B -> C' conversion questions to place Br on the terminal carbon."
  },

  {
    id: "swarts", name: "Swarts Reaction", type: "Halogen Exchange", chapter: "Haloalkanes",
    priority: "high", exam: "both", difficulty: "easy",
    tags: ["alkyl fluoride", "AgF", "Hg2F2", "halogen exchange"],
    summary: "Best method to prepare alkyl fluorides by heating an alkyl chloride/bromide with a metallic fluoride.",
    reactants: "Alkyl chloride or bromide",
    reagents: "Heavy metal fluorides like AgF, Hg2F2, CoF2, SbF3",
    conditions: "Heating",
    product: "Alkyl fluoride",
    mechanism: "Nucleophilic substitution (halogen exchange).",
    stereo: null,
    mistake: "Thinking Finkelstein makes alkyl fluorides. Swarts = Fluorides; Finkelstein = Iodides.",
    hook: "Swarts sounds like 'swords' -> 'F' for fencing -> makes Alkyl Fluorides.",
    jee: "Direct factual mechanism or naming reaction question."
  },

  {
    id: "gattermann", name: "Gattermann Reaction", type: "Diazonium Chemistry", chapter: "Amines",
    priority: "medium", exam: "both", difficulty: "easy",
    tags: ["Cu powder", "HCl", "HBr", "diazonium"],
    summary: "Similar to Sandmeyer but uses finely divided Copper powder instead of Copper(I) salts to convert diazonium salts to aryl halides.",
    reactants: "Diazonium salt",
    reagents: "Cu powder / HCl or Cu powder / HBr",
    conditions: "Room temperature / mild heating",
    product: "Aryl chloride or aryl bromide",
    mechanism: "Free radical mechanism similar to Sandmeyer.",
    stereo: null,
    mistake: "Confusing Sandmeyer (CuCl/CuBr) with Gattermann (Cu powder).",
    hook: "Gattermann = Cu POWDER. Sandmeyer = Cu SALT.",
    jee: "Tested as an alternative to Sandmeyer reaction."
  },

  {
    id: "fittig", name: "Fittig Reaction", type: "C-C Coupling", chapter: "Haloarenes",
    priority: "medium", exam: "mains", difficulty: "easy",
    tags: ["ArX + ArX", "Na", "biaryl", "dry ether"],
    summary: "Coupling of two aryl halides using Sodium in dry ether to form a biaryl compound.",
    reactants: "Two aryl halides (e.g., chlorobenzene)",
    reagents: "Na metal",
    conditions: "Dry ether",
    product: "Biaryl (e.g., biphenyl)",
    mechanism: "Similar to Wurtz reaction, via radical or organosodium intermediate.",
    stereo: null,
    mistake: "Mixing up Wurtz (alkyl+alkyl), Fittig (aryl+aryl), Wurtz-Fittig (alkyl+aryl).",
    hook: "Fittig = Two Aryls fit together.",
    jee: "Standard distinguishing question."
  },

  {
    id: "tollens", name: "Tollens' Test", type: "Oxidation", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["silver mirror", "ammoniacal silver nitrate", "aldehyde test"],
    summary: "Chemical test to distinguish aldehydes from ketones. Aldehydes are oxidized to carboxylate salts, and silver ions are reduced to metallic silver.",
    reactants: "Aldehydes (aliphatic and aromatic)",
    reagents: "Ammoniacal silver nitrate (Tollens' reagent)",
    conditions: "Mild heating in alkaline medium",
    product: "Carboxylate salt and Silver mirror",
    mechanism: "Oxidation of aldehyde by Ag(NH3)2+ complex.",
    stereo: null,
    mistake: "Thinking ketones give a positive test (only alpha-hydroxy ketones do).",
    hook: "Tollens = Silver mirror for ALDEHYDES.",
    jee: "Classical qualitative analysis question."
  },

  {
    id: "fehling", name: "Fehling's Test", type: "Oxidation", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["red ppt", "Cu2O", "aliphatic aldehyde test"],
    summary: "Chemical test for aliphatic aldehydes. Aldehydes reduce Cu2+ to a red precipitate of Cu2O.",
    reactants: "Aliphatic aldehydes (aromatic aldehydes give negative test)",
    reagents: "Fehling A (aq CuSO4) + Fehling B (Rochelle salt + NaOH)",
    conditions: "Heating",
    product: "Carboxylate salt and red Cu2O precipitate",
    mechanism: "Oxidation of aldehyde and reduction of Cu2+ to Cu+.",
    stereo: null,
    mistake: "Thinking benzaldehyde gives a positive test. Fehling's only works for ALIPHATIC aldehydes.",
    hook: "Fehling = red Cu2O. Aliphatic ONLY.",
    jee: "Often used to distinguish aliphatic and aromatic aldehydes."
  },

  {
    id: "hinsberg", name: "Hinsberg Test", type: "Amine Test", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["benzenesulfonyl chloride", "1/2/3 degree amines", "solubility"],
    summary: "Test to distinguish primary, secondary, and tertiary amines using benzenesulfonyl chloride (Hinsberg's reagent).",
    reactants: "Primary, secondary, or tertiary amines",
    reagents: "Benzenesulfonyl chloride and NaOH",
    conditions: "Alkaline medium, then acidification",
    product: "1° gives soluble salt, 2° gives insoluble compound, 3° does not react.",
    mechanism: "Formation of sulfonamides.",
    stereo: null,
    mistake: "Forgetting the solubility: 1° sulfonamide has an acidic H, so it dissolves in NaOH. 2° does not.",
    hook: "Hinsberg = 1° dissolves, 2° ppt, 3° no reaction.",
    jee: "Classic separation and identification test for amines."
  },

  {
    id: "tiffeneau", name: "Tiffeneau-Demjanov Rearrangement", type: "Rearrangement", chapter: "Misc",
    priority: "low", exam: "advanced", difficulty: "hard",
    tags: ["amino alcohol", "HNO2", "ring expansion", "ketone"],
    summary: "Rearrangement of 1-aminomethylcycloalkanols using HNO2 to yield expanded cyclic ketones.",
    reactants: "1-aminomethylcycloalkanol (beta-amino alcohol)",
    reagents: "HNO2 (NaNO2 / HCl)",
    conditions: "Cold aqueous acid",
    product: "Ring-expanded cyclic ketone",
    mechanism: "Diazotization of amine, loss of N2, and ring expansion via 1,2-alkyl shift.",
    stereo: null,
    mistake: "Similar to Pinacol rearrangement but uses amine and HNO2 instead of diol and H+.",
    hook: "Tiffeneau = Aminomethylcycloalkanol -> Ring expanded ketone.",
    jee: "JEE Advanced ring expansion topic."
  },

  {
    id: "curtius", name: "Curtius Rearrangement", type: "Rearrangement", chapter: "Amines",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["acyl azide", "isocyanate", "amine", "heat"],
    summary: "Thermal decomposition of an acyl azide to an isocyanate, which optionally hydrolyzes to a primary amine.",
    reactants: "Acyl azide",
    reagents: "Heat, then optionally H2O",
    conditions: "Thermal decomposition",
    product: "Isocyanate (or primary amine after hydrolysis)",
    mechanism: "Loss of N2 and simultaneous 1,2-shift of alkyl/aryl group from carbonyl carbon to nitrogen.",
    stereo: null,
    mistake: "Confusing Hofman, Curtius, Schmidt. Curtius uses acyl AZIDE.",
    hook: "Curtius = Acyl aZide -> Isocyanate.",
    jee: "Often part of synthesis sequences requiring elimination of one carbon via amine."
  },

  {
    id: "arndteistert", name: "Arndt-Eistert Reaction", type: "Chain Homologation", chapter: "Carboxylic Acids",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["homologation", "diazomethane", "wolf rearrangement", "ketene"],
    summary: "Process to convert a carboxylic acid to its next higher homolog (adds one CH2).",
    reactants: "Acyl chloride from a carboxylic acid",
    reagents: "CH2N2 (diazomethane), then Ag2O / H2O",
    conditions: "Formation of diazoketone, then Wolff rearrangement",
    product: "Higher homologous carboxylic acid",
    mechanism: "Diazoketone undergoes Wolff rearrangement to a ketene intermediate, which hydrolyzes.",
    stereo: null,
    mistake: "Thinking it loses a carbon. It ADDS a CH2 group.",
    hook: "Arndt-Eistert = Add a CH2 to Carboxylic Acid.",
    jee: "Classic homologation reaction in JEE Advanced."
  },

  {
    id: "bouveault", name: "Bouveault-Blanc Reduction", type: "Reduction", chapter: "Alcohols",
    priority: "medium", exam: "mains", difficulty: "medium",
    tags: ["Na/EtOH", "ester", "aldehyde", "alcohol"],
    summary: "Reduction of esters, aldehydes, or ketones to primary or secondary alcohols using metallic Sodium in Ethanol.",
    reactants: "Esters, aldehydes, or ketones",
    reagents: "Na metal and Ethanol",
    conditions: "Reflux",
    product: "Alcohol",
    mechanism: "Single electron transfer (SET) from Na, forming radical anions, followed by protonation from ethanol.",
    stereo: null,
    mistake: "Thinking LiAlH4 is the only way to reduce esters. Bouveault-Blanc is the classic non-hydride alternative.",
    hook: "Bouveault-Blanc = Na/EtOH reduction.",
    jee: "Often tested as a reagent-recognition question."
  },

  {
    id: "elbs", name: "Elbs-Persulphate Oxidation", type: "Oxidation", chapter: "Phenols",
    priority: "low", exam: "advanced", difficulty: "hard",
    tags: ["phenol", "persulfate", "para-diphenol", "quinol"],
    summary: "Oxidation of phenols with alkaline potassium persulfate to form para-diphenols (hydroquinones).",
    reactants: "Phenol",
    reagents: "K2S2O8 (Potassium persulfate) and NaOH",
    conditions: "Alkaline medium",
    product: "para-Diphenol (e.g., hydroquinone)",
    mechanism: "Electrophilic attack by persulfate on the phenoxide ion, typically at the para position.",
    stereo: null,
    mistake: "Oxidation does not break the ring; it simply hydroxylates it at the para position.",
    hook: "Elbs = Persulfate -> para-OH addition on Phenol.",
    jee: "Rare, but appears in JEE Advanced passages."
  },

  {
    id: "borodine", name: "Borodine-Hunsdiecker Reaction", type: "Decarboxylation", chapter: "Haloalkanes",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["Ag salt", "Br2/CCl4", "decarboxylation"],
    summary: "Silver salt of carboxylic acid reacts with Br2 in CCl4 to form Alkyl Bromides, decreasing the carbon chain by one.",
    reactants: "Silver carboxylate (RCOOAg)",
    reagents: "Br2 in CCl4",
    conditions: "Reflux",
    product: "Alkyl bromide (R-Br) + AgBr + CO2",
    mechanism: "Free radical mechanism: forms acyl hypobromite which loses CO2 to form an alkyl radical that captures Br.",
    stereo: null,
    mistake: "Writing product with same number of carbons. It loses CO2!",
    hook: "Hunsdiecker = Ag salt + Br2 -> Lose CO2, get RBr.",
    jee: "Important for step-down synthesis."
  },

  {
    id: "benzidine", name: "Benzidine Rearrangement", type: "Rearrangement", chapter: "Amines",
    priority: "low", exam: "advanced", difficulty: "hard",
    tags: ["hydrazobenzene", "benzidine", "acid-catalyzed"],
    summary: "Conversion of Hydrazobenzene (1,2-diphenylhydrazine) to Benzidine (4,4'-diaminobiphenyl) in an acidic medium.",
    reactants: "Hydrazobenzene",
    reagents: "Strong acid (e.g., HCl)",
    conditions: "Acidic medium",
    product: "Benzidine",
    mechanism: "Intramolecular sigmatropic rearrangement.",
    stereo: null,
    mistake: "Thinking the N-N bond breaks completely free. It is an intramolecular rearrangement.",
    hook: "Benzidine Rearrangement = Hydrazobenzene to 4,4'-diaminobiphenyl.",
    jee: "Used in dye chemistry, occasionally tested in passages."
  },

  {
    id: "cope", name: "Cope Elimination", type: "Elimination", chapter: "Amines",
    priority: "medium", exam: "advanced", difficulty: "hard",
    tags: ["amine oxide", "syn-elimination", "alkene", "pyrolysis"],
    summary: "Thermal decomposition of Tertiary Amine Oxides to give Alkenes and Hydroxylamine via a syn-elimination.",
    reactants: "Tertiary amine oxide",
    reagents: "Heat (150-200°C)",
    conditions: "Pyrolysis",
    product: "Alkene and N,N-dialkylhydroxylamine",
    mechanism: "Concerted syn-elimination through a cyclic 5-membered transition state.",
    stereo: "Syn-elimination, crucial for stereochemistry questions.",
    mistake: "Confusing with Hofmann elimination which requires base. Cope only needs heat and is SYN.",
    hook: "Cope = Amine Oxide pyrolyzes -> Alkene (Syn elimination).",
    jee: "Stereochemistry prediction based on syn-elimination."
  },

  {
    id: "knoevenagel", name: "Knoevenagel Reaction", type: "Condensation", chapter: "Carbonyl Compounds",
    priority: "medium", exam: "advanced", difficulty: "medium",
    tags: ["active methylene", "aldehyde", "weak base", "alpha-beta unsaturated"],
    summary: "Condensation of an aldehyde/ketone with an active methylene compound using a weak base like an amine.",
    reactants: "Aldehyde/ketone and active methylene compound (e.g., malonic ester)",
    reagents: "Weak base (e.g., piperidine, pyridine)",
    conditions: "Mild heating",
    product: "Alpha, beta-unsaturated compound",
    mechanism: "Enolate of active methylene attacks carbonyl, followed by dehydration.",
    stereo: null,
    mistake: "Confusing with Aldol. Knoevenagel uses active methylene (two EWGs) and a weak base.",
    hook: "Knoevenagel = Active methylene + Aldehyde + Amine base.",
    jee: "Precursor to making alpha-beta unsaturated acids."
  },

  {
    id: "baeyer", name: "Baeyer-Villiger Oxidation", type: "Oxidation", chapter: "Aldehydes & Ketones",
    priority: "high", exam: "advanced", difficulty: "hard",
    tags: ["peroxyacid", "ester", "lactone", "migratory aptitude"],
    summary: "Oxidation of ketones to esters (or cyclic ketones to lactones) using peroxyacids (e.g. mCPBA).",
    reactants: "Ketone (or cyclic ketone)",
    reagents: "Peroxyacid (e.g. mCPBA, CF3CO3H)",
    conditions: "Room temperature",
    product: "Ester (or lactone)",
    mechanism: "Nucleophilic attack of peracid on carbonyl, followed by rearrangement with alkyl group migration.",
    stereo: "Retention of configuration for the migrating group.",
    mistake: "Migrating the wrong group. Migratory aptitude: H > 3° > 2°/Ph > 1° > Methyl.",
    hook: "Baeyer-Villiger = Ketone + Peroxyacid = Ester (Lactone).",
    jee: "Questions often focus on the migratory aptitude to predict the major ester isomer."
  },

  {
    id: "libermann", name: "Libermann Nitroso Reaction", type: "Amine Test", chapter: "Phenols",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["phenol test", "NaNO2", "H2SO4", "blue-green", "indophenol"],
    summary: "Chemical test for Phenols yielding a deep blue/green color (Indophenol), which turns red on dilution.",
    reactants: "Phenol",
    reagents: "NaNO2 and conc. H2SO4",
    conditions: "Warming, then dilution, then addition of NaOH",
    product: "Indophenol (blue/green in base, red in acid)",
    mechanism: "Formation of nitrous acid, nitrosation of phenol, followed by condensation with another phenol molecule.",
    stereo: null,
    mistake: "Confusing the color sequence. Red in acidic dilution, Blue in alkaline.",
    hook: "Libermann = Phenol gives Red/Blue color with NaNO2/H2SO4.",
    jee: "Standard identification test for phenols."
  },

  {
    id: "mendius", name: "Mendius Reaction", type: "Reduction", chapter: "Amines",
    priority: "medium", exam: "mains", difficulty: "easy",
    tags: ["nitrile", "Na/EtOH", "primary amine"],
    summary: "Reduction of Alkyl Cyanides (Nitriles) to Primary Amines using Sodium and Ethanol.",
    reactants: "Alkyl cyanide (nitrile)",
    reagents: "Na and Ethanol",
    conditions: "Reflux",
    product: "Primary amine",
    mechanism: "Similar to Bouveault-Blanc, SET reduction.",
    stereo: null,
    mistake: "LiAlH4 also does this, but Mendius specifically refers to Na/EtOH.",
    hook: "Mendius = Nitrile reduced to 1° Amine by Na/EtOH.",
    jee: "Historical naming reaction for reduction of cyanides."
  },

  {
    id: "tischenko", name: "Tischenko Reaction", type: "Disproportionation", chapter: "Aldehydes & Ketones",
    priority: "low", exam: "advanced", difficulty: "hard",
    tags: ["aldehyde", "Al(OEt)3", "ester", "modified cannizzaro"],
    summary: "Modified Cannizzaro reaction where all aldehydes (even with alpha-H) form esters using Aluminum Ethoxide.",
    reactants: "Aldehydes",
    reagents: "Al(OEt)3 (Aluminum ethoxide)",
    conditions: "Anhydrous",
    product: "Ester",
    mechanism: "Coordination to Al followed by hydride transfer between two aldehyde units.",
    stereo: null,
    mistake: "Cannizzaro requires NO alpha-H. Tischenko works with ANY aldehyde.",
    hook: "Tischenko = Cannizzaro's trick to make an ESTER using Al(OEt)3.",
    jee: "Alternative to converting aldehyde to ester directly."
  },

  {
    id: "ulmann", name: "Ulmann Reaction", type: "C-C Coupling", chapter: "Haloarenes",
    priority: "medium", exam: "both", difficulty: "medium",
    tags: ["ArI", "Cu powder", "biaryl"],
    summary: "Coupling of Aryl Halides (usually Iodides) using Copper powder at high temp to form Biaryls.",
    reactants: "Aryl iodide",
    reagents: "Copper powder",
    conditions: "High temperature in sealed tube",
    product: "Biaryl (e.g. biphenyl)",
    mechanism: "Radical mechanism or via organocopper intermediates.",
    stereo: null,
    mistake: "Using Aryl Chloride without activating groups. Typically needs Aryl Iodide.",
    hook: "Ullmann = ArI + Cu -> Biphenyl.",
    jee: "Coupling of iodobenzene is a classic example."
  },

  {
    id: "ozonolysis", name: "Ozonolysis", type: "Oxidation", chapter: "Hydrocarbons",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["O3", "Zn/H2O", "cleavage", "alkene", "carbonyl"],
    summary: "Cleavage of alkenes/alkynes using Ozone. Reductive workup yields aldehydes/ketones. Oxidative workup yields carboxylic acids.",
    reactants: "Alkenes or alkynes",
    reagents: "O3, then Zn/H2O (reductive) or H2O2 (oxidative)",
    conditions: "Low temperature for ozonide formation",
    product: "Aldehydes/Ketones (Reductive) or Carboxylic Acids (Oxidative)",
    mechanism: "Cycloaddition forming primary ozonide, rearrangement to stable ozonide, then cleavage.",
    stereo: null,
    mistake: "Forgetting the workup type. Zn/H2O means STOP at aldehyde. H2O2 means GO to carboxylic acid.",
    hook: "Ozonolysis = Cut the double bond, slap O on both sides.",
    jee: "Extremely common for structural elucidation based on cleavage products."
  },

  {
    id: "oxymercuration", name: "Oxymercuration-Demercuration", type: "Electrophilic Addition", chapter: "Hydrocarbons",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["Hg(OAc)2", "NaBH4", "Markovnikov", "no rearrangement"],
    summary: "Converts Alkenes to Alcohols following Markovnikov's rule WITHOUT carbocation rearrangement.",
    reactants: "Alkene",
    reagents: "1) Hg(OAc)2 / H2O, 2) NaBH4",
    conditions: "Aqueous medium",
    product: "Markovnikov alcohol",
    mechanism: "Cyclic mercurinium ion prevents rearrangement. Water attacks the more substituted carbon (anti-addition).",
    stereo: "Anti-addition of H and OH.",
    mistake: "Rearranging the skeleton as in acid-catalyzed hydration.",
    hook: "OMDM = Markovnikov OH with NO Rearrangement.",
    jee: "Always tested in contrast with acid catalyzed hydration (which rearranges)."
  },

  {
    id: "hydroboration", name: "Hydroboration - Oxidation", type: "Electrophilic Addition", chapter: "Hydrocarbons",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["B2H6", "H2O2/OH-", "anti-Markovnikov", "syn addition"],
    summary: "Converts alkenes to alcohols following Anti-Markovnikov's rule with Syn-addition.",
    reactants: "Alkene",
    reagents: "1) B2H6 / THF, 2) H2O2 / OH-",
    conditions: "Alkaline peroxide workup",
    product: "Anti-Markovnikov alcohol",
    mechanism: "Concerted syn-addition of B and H, placing B on the less sterically hindered carbon, followed by oxidation with retention of configuration.",
    stereo: "Syn-addition. Essential for stereoisomeric products.",
    mistake: "Markovnikov addition instead of Anti-Markovnikov, or getting the stereochemistry wrong.",
    hook: "HBO = Anti-Markovnikov, SYN addition.",
    jee: "Often paired with OMDM to check understanding of regiochemistry & stereochemistry."
  },

  {
    id: "hoffman-elim", name: "Hoffmann Elimination", type: "Elimination", chapter: "Amines",
    priority: "high", exam: "both", difficulty: "medium",
    tags: ["quaternary ammonium", "least substituted", "E2", "heat"],
    summary: "Thermal decomposition of Quaternary Ammonium Hydroxides to form the least substituted alkene (Hofmann product).",
    reactants: "Quaternary ammonium hydroxide",
    reagents: "Heat",
    conditions: "High temperature",
    product: "Hoffmann (least substituted) alkene",
    mechanism: "E2 elimination. Bulky leaving group and strong base character drive formation of less sterically hindered carbanion-like TS.",
    stereo: null,
    mistake: "Forming the Saytzeff (more substituted) product. Hofmann's rule prefers the less substituted alkene.",
    hook: "Hofmann Elimination = Least Substituted Alkene.",
    jee: "Given an amine, students must exhaustive methylate it, use Ag2O/H2O, then heat to find the alkene."
  },

  {
    id: "claisen-rearrang", name: "Claisen Rearrangement", type: "Rearrangement", chapter: "Phenols",
    priority: "high", exam: "advanced", difficulty: "medium",
    tags: ["allyl aryl ether", "heat", "o-allyl phenol", "sigmatropic"],
    summary: "Thermal conversion of Allyl Aryl Ethers to o-Allyl Phenols. Proceeds via a concerted [3,3]-Sigmatropic Shift.",
    reactants: "Allyl aryl ether",
    reagents: "Heat (200°C)",
    conditions: "Purely thermal, no catalyst needed",
    product: "o-Allyl phenol",
    mechanism: "Concerted [3,3]-sigmatropic rearrangement through a 6-membered cyclic transition state.",
    stereo: "Retention of configuration regarding the alkene if substituents are present.",
    mistake: "Not realizing the allyl group INVERTS. If labeled, the end that was free attaches to the ring.",
    hook: "Claisen Rearrangement = [3,3]-shift. Allyl flips while attaching to ortho position.",
    jee: "Often asked with isotopic labeling to trace the flipping of the allyl group."
  }

];

export const QUICK_REF: QuickRefTable[] = [
  {
    title: "pKa values",
    headers: ["Acid", "Approximate pKa", "Conjugate Base"],
    rows: [
      { name: "HSbF₆", value: "−12", note: "SbF₆⁻ (Weakest base)" },
      { name: "HI", value: "−10", note: "I⁻" },
      { name: "H₂SO₄", value: "−9", note: "HSO₄⁻" },
      { name: "HBr", value: "−9", note: "Br⁻" },
      { name: "HCl", value: "−7", note: "Cl⁻" },
      { name: "C₆H₅SO₃H", value: "−6.5", note: "C₆H₅SO₃⁻" },
      { name: "(CH₃)₂O⁺H", value: "−3.8", note: "(CH₃)₂O" },
      { name: "(CH₃)₂C=O⁺H", value: "−2.9", note: "(CH₃)₂C=O" },
      { name: "CH₃O⁺H₂", value: "−2.5", note: "CH₃OH" },
      { name: "H₃O⁺", value: "−1.74", note: "H₂O" },
      { name: "HNO₃", value: "−1.4", note: "NO₃⁻" },
      { name: "CF₃CO₂H", value: "0.18", note: "CF₃CO₂⁻" },
      { name: "HF", value: "3.2", note: "F⁻" },
      { name: "C₆H₅CO₂H", value: "4.21", note: "C₆H₅CO₂⁻" },
      { name: "C₆H₅NH₃⁺", value: "4.63", note: "C₆H₅NH₂" },
      { name: "CH₃CO₂H", value: "4.75", note: "CH₃CO₂⁻" },
      { name: "H₂CO₃", value: "6.35", note: "HCO₃⁻" },
      { name: "CH₃COCH₂COCH₃", value: "9.0", note: "CH₃COC⁻HCOCH₃" },
      { name: "NH₄⁺", value: "9.2", note: "NH₃" },
      { name: "C₆H₅OH", value: "9.9", note: "C₆H₅O⁻" },
      { name: "HCO₃⁻", value: "10.2", note: "CO₃²⁻" },
      { name: "CH₃NH₃⁺", value: "10.6", note: "CH₃NH₂" },
      { name: "H₂O", value: "15.7", note: "HO⁻" },
      { name: "CH₃CH₂OH", value: "16", note: "CH₃CH₂O⁻" },
      { name: "(CH₃)₃COH", value: "18", note: "(CH₃)₃CO⁻" },
      { name: "CH₃COCH₃", value: "19.2", note: "⁻CH₂COCH₃" },
      { name: "HC≡CH", value: "25", note: "HC≡C⁻" },
      { name: "C₆H₅NH₂", value: "31", note: "C₆H₅NH⁻" },
      { name: "H₂", value: "35", note: "H⁻" },
      { name: "(i-Pr)₂NH", value: "36", note: "(i-Pr)₂N⁻" },
      { name: "NH₃", value: "38", note: "⁻NH₂" },
      { name: "CH₂=CH₂", value: "44", note: "CH₂=CH⁻" },
      { name: "CH₃CH₃", value: "50", note: "CH₃CH₂⁻ (Strongest base)" },
    ]
  },

  {
    title: "Carbocation stability",
    description: "pKr+ provides a quantitative measure of carbocation stability. A HIGHER (more positive) value indicates GREATER stability. Determined by equilibrium of carbocation with water.",
    headers: ["Carbocation", "pKr+", "Category"],
    rows: [
      { name: "Triphenylmethyl", value: "-6.63", note: "Triarylmethyl" },
      { name: "4,4',4''-Trimethyltriphenylmethyl", value: "-3.56", note: "Triarylmethyl" },
      { name: "4-Methoxytriphenylmethyl", value: "-3.40", note: "Triarylmethyl" },
      { name: "4,4'-Dimethoxytriphenylmethyl", value: "-1.24", note: "Triarylmethyl" },
      { name: "4,4',4''-Trimethoxytriphenylmethyl", value: "+0.82", note: "Triarylmethyl" },
      { name: "4,4',4''-Trichlorotriphenylmethyl", value: "-7.74", note: "Triarylmethyl" },
      { name: "4-Nitrotriphenylmethyl", value: "-9.15", note: "Triarylmethyl" },
      { name: "4,4',4''-Trinitrotriphenylmethyl", value: "-16.27", note: "Triarylmethyl" },
      { name: "4,4',4''-Tri(dimethylamino)triphenylmethyl", value: "+9.36", note: "Triarylmethyl" },
      { name: "Sesquixanthydryl", value: "+9.05", note: "Triarylmethyl" },
      { name: "Diphenylmethyl", value: "-13.3", note: "Diarylmethyl" },
      { name: "4,4'-Dimethyldiphenylmethyl", value: "-10.4", note: "Diarylmethyl" },
      { name: "4,4'-Dimethoxydiphenylmethyl", value: "-5.71", note: "Diarylmethyl" },
      { name: "2,2',4,4',6,6'-Hexamethyldiphenylmethyl", value: "-6.6", note: "Diarylmethyl" },
      { name: "4,4'-Dichlorodiphenylmethyl", value: "-13.96", note: "Diarylmethyl" },
      { name: "Benzyl", value: "-20", note: "Miscellaneous" },
      { name: "2-Phenyl-2-propyl", value: "-12.3", note: "Miscellaneous" },
      { name: "Tricyclopropylmethyl", value: "-2.3", note: "Miscellaneous" },
      { name: "Tropylium (cycloheptatrienyl)", value: "+4.7", note: "Miscellaneous" },
      { name: "Triphenylcyclopropenyl", value: "+3.1", note: "Miscellaneous" },
      { name: "Trimethylcyclopropenyl", value: "+7.8", note: "Miscellaneous" },
      { name: "Tricyclopropylcyclopropenyl", value: "+9.7", note: "Miscellaneous" },
    ]
  },
  {
    title: "Bond Energies (Inorganic)",
    headers: ["Bond", "Energy (kJ/mol)", "Category"],
    rows: [
      { name: "H–H", value: "432", note: "Hydrogen" },
      { name: "H–B", value: "389", note: "Hydrogen" },
      { name: "H–C", value: "411", note: "Hydrogen" },
      { name: "H–N", value: "386", note: "Hydrogen" },
      { name: "H–O", value: "459", note: "Hydrogen" },
      { name: "H–S", value: "363", note: "Hydrogen" },
      { name: "H–F", value: "565", note: "Hydrogen" },
      { name: "H–Cl", value: "428", note: "Hydrogen" },
      { name: "H–Br", value: "362", note: "Hydrogen" },
      { name: "H–I", value: "295", note: "Hydrogen" },
      { name: "B–C", value: "372", note: "Group 13 (Boron)" },
      { name: "B–O", value: "536", note: "Group 13 (Boron)" },
      { name: "B=O", value: "636", note: "Group 13 (Boron)" },
      { name: "B–F", value: "613", note: "Group 13 (Boron)" },
      { name: "B–Cl", value: "456", note: "Group 13 (Boron)" },
      { name: "B–Br", value: "377", note: "Group 13 (Boron)" },
      { name: "C–C", value: "346", note: "Group 14 (Carbon)" },
      { name: "C=C", value: "602", note: "Group 14 (Carbon)" },
      { name: "C≡C", value: "835", note: "Group 14 (Carbon)" },
      { name: "C–N", value: "305", note: "Group 14 (Carbon)" },
      { name: "C=N", value: "615", note: "Group 14 (Carbon)" },
      { name: "C≡N", value: "887", note: "Group 14 (Carbon)" },
      { name: "C–P", value: "264", note: "Group 14 (Carbon)" },
      { name: "C–O", value: "358", note: "Group 14 (Carbon)" },
      { name: "C=O", value: "799", note: "Group 14 (Carbon)" },
      { name: "C≡O", value: "1072", note: "Group 14 (Carbon)" },
      { name: "C–F", value: "485", note: "Group 14 (Carbon)" },
      { name: "C–Cl", value: "327", note: "Group 14 (Carbon)" },
      { name: "C–Br", value: "310", note: "Group 14 (Carbon)" },
      { name: "C–I", value: "213", note: "Group 14 (Carbon)" },
      { name: "Si–Si", value: "222", note: "Group 14 (Silicon)" },
      { name: "Si–O", value: "452", note: "Group 14 (Silicon)" },
      { name: "Si=O", value: "642", note: "Group 14 (Silicon)" },
      { name: "Si–F", value: "565", note: "Group 14 (Silicon)" },
      { name: "Si–Cl", value: "381", note: "Group 14 (Silicon)" },
      { name: "Si–Br", value: "310", note: "Group 14 (Silicon)" },
      { name: "Si–I", value: "234", note: "Group 14 (Silicon)" },
      { name: "N–N", value: "247", note: "Group 15 (Nitrogen)" },
      { name: "N=N", value: "418", note: "Group 15 (Nitrogen)" },
      { name: "N≡N", value: "942", note: "Group 15 (Nitrogen)" },
      { name: "N–O", value: "201", note: "Group 15 (Nitrogen)" },
      { name: "N=O", value: "607", note: "Group 15 (Nitrogen)" },
      { name: "N–F", value: "278", note: "Group 15 (Nitrogen)" },
      { name: "N–Cl", value: "192", note: "Group 15 (Nitrogen)" },
      { name: "P–P", value: "200", note: "Group 15 (Phosphorus)" },
      { name: "P≡P", value: "481", note: "Group 15 (Phosphorus)" },
      { name: "P–O", value: "335", note: "Group 15 (Phosphorus)" },
      { name: "P–F", value: "490", note: "Group 15 (Phosphorus)" },
      { name: "P–Cl", value: "326", note: "Group 15 (Phosphorus)" },
      { name: "P–Br", value: "264", note: "Group 15 (Phosphorus)" },
      { name: "P–I", value: "184", note: "Group 15 (Phosphorus)" },
      { name: "O–O", value: "142", note: "Group 16 (Oxygen)" },
      { name: "O=O", value: "494", note: "Group 16 (Oxygen)" },
      { name: "O=S", value: "523", note: "Group 16 (Oxygen)" },
      { name: "O–Xe", value: "84", note: "Group 16 (Oxygen)" },
      { name: "O–F", value: "190", note: "Group 16 (Oxygen)" },
      { name: "O–Cl", value: "218", note: "Group 16 (Oxygen)" },
      { name: "O–Br", value: "201", note: "Group 16 (Oxygen)" },
      { name: "O–I", value: "201", note: "Group 16 (Oxygen)" },
      { name: "S–S", value: "268", note: "Group 16 (Sulfur)" },
      { name: "S=S", value: "425", note: "Group 16 (Sulfur)" },
      { name: "S–F", value: "327", note: "Group 16 (Sulfur)" },
      { name: "S–Cl", value: "271", note: "Group 16 (Sulfur)" },
      { name: "F–F", value: "155", note: "Group 17 (Fluorine)" },
      { name: "F–Kr", value: "50", note: "Group 17 (Fluorine)" },
      { name: "F–Xe", value: "133", note: "Group 17 (Fluorine)" },
      { name: "F–Cl", value: "249", note: "Group 17 (Fluorine)" },
      { name: "F–Br", value: "250", note: "Group 17 (Fluorine)" },
      { name: "F–I", value: "278", note: "Group 17 (Fluorine)" },
      { name: "Cl–Cl", value: "240", note: "Group 17 (Chlorine)" },
      { name: "Cl–Br", value: "216", note: "Group 17 (Chlorine)" },
      { name: "Cl–I", value: "208", note: "Group 17 (Chlorine)" },
      { name: "Br–Br", value: "190", note: "Group 17 (Bromine)" },
      { name: "Br–I", value: "175", note: "Group 17 (Bromine)" },
      { name: "I–I", value: "149", note: "Group 17 (Iodine)" },
    ]
  },
  {
    title: "Bond Energies (Organic)",
    headers: ["Bond", "Energy (kJ/mol)", "Category"],
    rows: [
      { name: "H–F", value: "569", note: "H–Z bonds" },
      { name: "H–Cl", value: "431", note: "H–Z bonds" },
      { name: "H–Br", value: "368", note: "H–Z bonds" },
      { name: "H–I", value: "297", note: "H–Z bonds" },
      { name: "H–OH", value: "498", note: "H–Z bonds" },
      { name: "H–H", value: "435", note: "Z–Z bonds" },
      { name: "F–F", value: "159", note: "Z–Z bonds" },
      { name: "Cl–Cl", value: "242", note: "Z–Z bonds" },
      { name: "Br–Br", value: "192", note: "Z–Z bonds" },
      { name: "I–I", value: "151", note: "Z–Z bonds" },
      { name: "HO–OH", value: "213", note: "Z–Z bonds" },
      { name: "CH₃–H", value: "435", note: "R–H bonds" },
      { name: "CH₃CH₂–H", value: "410", note: "R–H bonds" },
      { name: "CH₃CH₂CH₂–H", value: "410", note: "R–H bonds" },
      { name: "(CH₃)₂CH–H", value: "397", note: "R–H bonds" },
      { name: "(CH₃)₃C–H", value: "381", note: "R–H bonds" },
      { name: "CH₂=CH–H", value: "435", note: "R–H bonds" },
      { name: "HC≡C–H", value: "523", note: "R–H bonds" },
      { name: "CH₂=CHCH₂–H", value: "364", note: "R–H bonds" },
      { name: "C₆H₅–H", value: "460", note: "R–H bonds" },
      { name: "C₆H₅CH₂–H", value: "356", note: "R–H bonds" },
      { name: "CH₃–CH₃", value: "368", note: "R–R bonds" },
      { name: "CH₃–CH₂CH₃", value: "356", note: "R–R bonds" },
      { name: "CH₃–CH=CH₂", value: "385", note: "R–R bonds" },
      { name: "CH₃–C≡CH", value: "489", note: "R–R bonds" },
      { name: "CH₃–F", value: "456", note: "R–X bonds" },
      { name: "CH₃–Cl", value: "351", note: "R–X bonds" },
      { name: "CH₃–Br", value: "293", note: "R–X bonds" },
      { name: "CH₃–I", value: "234", note: "R–X bonds" },
      { name: "CH₃CH₂–F", value: "448", note: "R–X bonds" },
      { name: "CH₃CH₂–Cl", value: "339", note: "R–X bonds" },
      { name: "CH₃CH₂–Br", value: "285", note: "R–X bonds" },
      { name: "CH₃CH₂–I", value: "222", note: "R–X bonds" },
      { name: "(CH₃)₂CH–F", value: "444", note: "R–X bonds" },
      { name: "(CH₃)₂CH–Cl", value: "335", note: "R–X bonds" },
      { name: "(CH₃)₂CH–Br", value: "285", note: "R–X bonds" },
      { name: "(CH₃)₂CH–I", value: "222", note: "R–X bonds" },
      { name: "(CH₃)₃C–F", value: "444", note: "R–X bonds" },
      { name: "(CH₃)₃C–Cl", value: "331", note: "R–X bonds" },
      { name: "(CH₃)₃C–Br", value: "272", note: "R–X bonds" },
      { name: "(CH₃)₃C–I", value: "209", note: "R–X bonds" },
      { name: "CH₃–OH", value: "389", note: "R–OH bonds" },
      { name: "CH₃CH₂–OH", value: "393", note: "R–OH bonds" },
      { name: "CH₃CH₂CH₂–OH", value: "385", note: "R–OH bonds" },
      { name: "(CH₃)₂CH–OH", value: "401", note: "R–OH bonds" },
      { name: "(CH₃)₃C–OH", value: "401", note: "R–OH bonds" },
      { name: "CH₂=CH₂", value: "635", note: "Other bonds" },
      { name: "HC≡CH", value: "837", note: "Other bonds" },
      { name: "O=C=O", value: "535", note: "Other bonds" },
      { name: "O₂", value: "497", note: "Other bonds" },
    ]
  }
];

export const TYPE_COLOR: Record<string, [string, string, string]> = {
  "C-C Coupling": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Condensation": ["rgba(167,139,250,0.06)", "rgba(167,139,250,0.2)", "#c4b5fd"],
  "Diazonium Chemistry": ["rgba(251,191,36,0.06)", "rgba(251,191,36,0.2)", "#fbbf24"],
  "Disproportionation": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Electrophilic Aromatic Substitution": ["rgba(251,146,60,0.06)", "rgba(251,146,60,0.2)", "#fdba74"],
  "Reduction": ["rgba(244,114,182,0.06)", "rgba(244,114,182,0.2)", "#f9a8d4"],
  "Oxidation": ["rgba(251,113,133,0.06)", "rgba(251,113,133,0.2)", "#fda4af"],
  "Halogenation": ["rgba(251,191,36,0.06)", "rgba(251,191,36,0.2)", "#fbbf24"],
  "Nucleophilic Addition": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "SN2 Substitution": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Rearrangement": ["rgba(251,146,60,0.06)", "rgba(251,146,60,0.2)", "#fdba74"],
  "Amine Synthesis": ["rgba(167,139,250,0.06)", "rgba(167,139,250,0.2)", "#c4b5fd"],
  "Amine Test": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "Decarboxylation": ["rgba(56,189,248,0.06)", "rgba(56,189,248,0.2)", "#7dd3fc"],
  "Acyl Substitution": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "Carboxylation": ["rgba(52,211,153,0.06)", "rgba(52,211,153,0.2)", "#6ee7b7"],
  "Halogen Exchange": ["rgba(251,191,36,0.06)", "rgba(251,191,36,0.2)", "#fbbf24"],
  "Chain Homologation": ["rgba(167,139,250,0.06)", "rgba(167,139,250,0.2)", "#c4b5fd"],
  "Nucleophilic Aromatic Substitution": ["rgba(244,114,182,0.06)", "rgba(244,114,182,0.2)", "#f9a8d4"],
};
